In [1]:
!pip install statsmodels

Collecting statsmodels
  Downloading statsmodels-0.14.5-cp312-cp312-win_amd64.whl.metadata (9.8 kB)
Collecting numpy<3,>=1.22.3 (from statsmodels)
  Using cached numpy-2.3.4-cp312-cp312-win_amd64.whl.metadata (60 kB)
Collecting scipy!=1.9.2,>=1.8 (from statsmodels)
  Downloading scipy-1.16.3-cp312-cp312-win_amd64.whl.metadata (60 kB)
Collecting pandas!=2.1.0,>=1.4 (from statsmodels)
  Using cached pandas-2.3.3-cp312-cp312-win_amd64.whl.metadata (19 kB)
Collecting patsy>=0.5.6 (from statsmodels)
  Downloading patsy-1.0.2-py2.py3-none-any.whl.metadata (3.6 kB)
Requirement already satisfied: packaging>=21.3 in e:\pysingscore_replicate\.venv\lib\site-packages (from statsmodels) (25.0)
Requirement already satisfied: python-dateutil>=2.8.2 in e:\pysingscore_replicate\.venv\lib\site-packages (from pandas!=2.1.0,>=1.4->statsmodels) (2.9.0.post0)
Collecting pytz>=2020.1 (from pandas!=2.1.0,>=1.4->statsmodels)
  Using cached pytz-2025.2-py2.py3-none-any.whl.metadata (22 kB)
Collecting tzdata>=2022.7 (from pandas!=2.1.0,>=1.4->statsmodels)
  Using cached tzdata-2025.2-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in e:\pysingscore_replicate\.venv\lib\site-packages (from python-dateutil>=2.8.2->pandas!=2.1.0,>=1.4->statsmodels) (1.17.0)
Downloading statsmodels-0.14.5-cp312-cp312-win_amd64.whl (9.6 MB)
   ---------------------------------------- 0.0/9.6 MB ? eta -:--:--
   ---------------------------------------- 9.6/9.6 MB 66.8 MB/s  0:00:00
Using cached numpy-2.3.4-cp312-cp312-win_amd64.whl (12.8 MB)
Using cached pandas-2.3.3-cp312-cp312-win_amd64.whl (11.0 MB)
Downloading patsy-1.0.2-py2.py3-none-any.whl (233 kB)
Using cached pytz-2025.2-py2.py3-none-any.whl (509 kB)
Downloading scipy-1.16.3-cp312-cp312-win_amd64.whl (38.6 MB)
   ---------------------------------------- 0.0/38.6 MB ? eta -:--:--
   ------------------- -------------------- 19.1/38.6 MB 93.0 MB/s eta 0:00:01
   ---------------------------------------  38.5/38.6 MB 94.3 MB/s eta 0:00:01
   ---------------------------------------- 38.6/38.6 MB 84.5 MB/s  0:00:00
Using cached tzdata-2025.2-py2.py3-none-any.whl (347 kB)
Installing collected packages: pytz, tzdata, numpy, scipy, patsy, pandas, statsmodels

   ---------------------------------------- 0/7 [pytz]
   ----- ---------------------------------- 1/7 [tzdata]
   ----- ---------------------------------- 1/7 [tzdata]
   ----------- ---------------------------- 2/7 [numpy]
   ----------- ---------------------------- 2/7 [numpy]
   ----------- ---------------------------- 2/7 [numpy]
   ----------- ---------------------------- 2/7 [numpy]
   ----------- ---------------------------- 2/7 [numpy]
   ----------- ---------------------------- 2/7 [numpy]
   ----------- ---------------------------- 2/7 [numpy]
   ----------- ---------------------------- 2/7 [numpy]
   ----------- ---------------------------- 2/7 [numpy]
   ----------- ---------------------------- 2/7 [numpy]
   ----------- ---------------------------- 2/7 [numpy]
   ----------------- ---------------------- 3/7 [scipy]
   ----------------- ---------------------- 3/7 [scipy]
   ----------------- ---------------------- 3/7 [scipy]
   ----------------- ---------------------- 3/7 [scipy]
   ----------------- ---------------------- 3/7 [scipy]
   ----------------- ---------------------- 3/7 [scipy]
   ----------------- ---------------------- 3/7 [scipy]
   ----------------- ---------------------- 3/7 [scipy]
   ----------------- ---------------------- 3/7 [scipy]
   ----------------- ---------------------- 3/7 [scipy]
   ----------------- ---------------------- 3/7 [scipy]
   ----------------- ---------------------- 3/7 [scipy]
   ----------------- ---------------------- 3/7 [scipy]
   ----------------- ---------------------- 3/7 [scipy]
   ----------------- ---------------------- 3/7 [scipy]
   ----------------- ---------------------- 3/7 [scipy]
   ----------------- ---------------------- 3/7 [scipy]
   ----------------- ---------------------- 3/7 [scipy]
   ----------------- ---------------------- 3/7 [scipy]
   ----------------- ---------------------- 3/7 [scipy]
   ----------------- ---------------------- 3/7 [scipy]
   ----------------- ---------------------- 3/7 [scipy]
   ---------------------- ----------------- 4/7 [patsy]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------------- ----- 6/7 [statsmodels]
   ---------------------------------- ----- 6/7 [statsmodels]
   ---------------------------------- ----- 6/7 [statsmodels]
   ---------------------------------- ----- 6/7 [statsmodels]
   ---------------------------------- ----- 6/7 [statsmodels]
   ---------------------------------- ----- 6/7 [statsmodels]
   ---------------------------------- ----- 6/7 [statsmodels]
   ---------------------------------- ----- 6/7 [statsmodels]
   ---------------------------------- ----- 6/7 [statsmodels]
   ---------------------------------- ----- 6/7 [statsmodels]
   ---------------------------------- ----- 6/7 [statsmodels]
   ---------------------------------- ----- 6/7 [statsmodels]
   ---------------------------------- ----- 6/7 [statsmodels]
   ---------------------------------- ----- 6/7 [statsmodels]
   ---------------------------------- ----- 6/7 [statsmodels]
   ---------------------------------- ----- 6/7 [statsmodels]
   ---------------------------------- ----- 6/7 [statsmodels]
   ---------------------------------- ----- 6/7 [statsmodels]
   ---------------------------------- ----- 6/7 [statsmodels]
   ---------------------------------------- 7/7 [statsmodels]

Successfully installed numpy-2.3.4 pandas-2.3.3 patsy-1.0.2 pytz-2025.2 scipy-1.16.3 statsmodels-0.14.5 tzdata-2025.2

In [5]:
! pip install tqdm

Collecting tqdm
  Using cached tqdm-4.67.1-py3-none-any.whl.metadata (57 kB)
Requirement already satisfied: colorama in e:\pysingscore_replicate\.venv\lib\site-packages (from tqdm) (0.4.6)
Using cached tqdm-4.67.1-py3-none-any.whl (78 kB)
Installing collected packages: tqdm
Successfully installed tqdm-4.67.1

In [2]:
! pip install seaborn

Collecting seaborn
  Downloading seaborn-0.13.2-py3-none-any.whl.metadata (5.4 kB)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in e:\pysingscore_replicate\.venv\lib\site-packages (from seaborn) (2.3.4)
Requirement already satisfied: pandas>=1.2 in e:\pysingscore_replicate\.venv\lib\site-packages (from seaborn) (2.3.3)
Collecting matplotlib!=3.6.1,>=3.4 (from seaborn)
  Downloading matplotlib-3.10.7-cp312-cp312-win_amd64.whl.metadata (11 kB)
Collecting contourpy>=1.0.1 (from matplotlib!=3.6.1,>=3.4->seaborn)
  Downloading contourpy-1.3.3-cp312-cp312-win_amd64.whl.metadata (5.5 kB)
Collecting cycler>=0.10 (from matplotlib!=3.6.1,>=3.4->seaborn)
  Downloading cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
Collecting fonttools>=4.22.0 (from matplotlib!=3.6.1,>=3.4->seaborn)
  Downloading fonttools-4.60.1-cp312-cp312-win_amd64.whl.metadata (114 kB)
Collecting kiwisolver>=1.3.1 (from matplotlib!=3.6.1,>=3.4->seaborn)
  Downloading kiwisolver-1.4.9-cp312-cp312-win_amd64.whl.metadata (6.4 kB)
Requirement already satisfied: packaging>=20.0 in e:\pysingscore_replicate\.venv\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (25.0)
Collecting pillow>=8 (from matplotlib!=3.6.1,>=3.4->seaborn)
  Downloading pillow-12.0.0-cp312-cp312-win_amd64.whl.metadata (9.0 kB)
Collecting pyparsing>=3 (from matplotlib!=3.6.1,>=3.4->seaborn)
  Downloading pyparsing-3.2.5-py3-none-any.whl.metadata (5.0 kB)
Requirement already satisfied: python-dateutil>=2.7 in e:\pysingscore_replicate\.venv\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in e:\pysingscore_replicate\.venv\lib\site-packages (from pandas>=1.2->seaborn) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in e:\pysingscore_replicate\.venv\lib\site-packages (from pandas>=1.2->seaborn) (2025.2)
Requirement already satisfied: six>=1.5 in e:\pysingscore_replicate\.venv\lib\site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.17.0)
Downloading seaborn-0.13.2-py3-none-any.whl (294 kB)
Downloading matplotlib-3.10.7-cp312-cp312-win_amd64.whl (8.1 MB)
   ---------------------------------------- 0.0/8.1 MB ? eta -:--:--
   ------------------ --------------------- 3.7/8.1 MB 18.1 MB/s eta 0:00:01
   ------------------------------ --------- 6.3/8.1 MB 15.4 MB/s eta 0:00:01
   ---------------------------------------- 8.1/8.1 MB 17.9 MB/s  0:00:00
Downloading contourpy-1.3.3-cp312-cp312-win_amd64.whl (226 kB)
Downloading cycler-0.12.1-py3-none-any.whl (8.3 kB)
Downloading fonttools-4.60.1-cp312-cp312-win_amd64.whl (2.3 MB)
   ---------------------------------------- 0.0/2.3 MB ? eta -:--:--
   ---------------------------------------- 2.3/2.3 MB 64.7 MB/s  0:00:00
Downloading kiwisolver-1.4.9-cp312-cp312-win_amd64.whl (73 kB)
Downloading pillow-12.0.0-cp312-cp312-win_amd64.whl (7.0 MB)
   ---------------------------------------- 0.0/7.0 MB ? eta -:--:--
   ---------------------------------------- 7.0/7.0 MB 71.7 MB/s  0:00:00
Downloading pyparsing-3.2.5-py3-none-any.whl (113 kB)
Installing collected packages: pyparsing, pillow, kiwisolver, fonttools, cycler, contourpy, matplotlib, seaborn

   ----- ---------------------------------- 1/8 [pillow]
   ----- ---------------------------------- 1/8 [pillow]
   ---------- ----------------------------- 2/8 [kiwisolver]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   ------------------------- -------------- 5/8 [contourpy]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ----------------------------------- ---- 7/8 [seaborn]
   ---------------------------------------- 8/8 [seaborn]

Successfully installed contourpy-1.3.3 cycler-0.12.1 fonttools-4.60.1 kiwisolver-1.4.9 matplotlib-3.10.7 pillow-12.0.0 pyparsing-3.2.5 seaborn-0.13.2

In [3]:
import os
from pathlib import Path

## Setting the path to input files

In [2]:
import os
from singscore.singscore import *

BASE_DIR = os.getcwd()   # current working directory
print(BASE_DIR)

entrez_sample_path = os.path.normpath('{}/{}'.format(BASE_DIR,
                                'singscore_new_code/UK65_clean_gene_log_tpm.txt'))

sig_path = os.path.normpath('{}/{}'.format(BASE_DIR,
                                'singscore/test/test_sigs/tgfb_upDown.txt'))

d:\GS\PySingscore_replicate

## Reading the data

In [3]:
data = pandas.read_csv(open(entrez_sample_path, 'r'), header=
'infer', sep='\t')
data = data.set_index(keys='GeneName')
data

               log2_TPM
GeneName
7SK           17.004583
A1BG           5.457517
A1BG-AS1       7.251618
A1CF           1.187320
A2M            8.725599
...                 ...
ZYG11B         4.011921
ZYX            7.907273
ZZEF1          6.529184
ZZZ3           8.051912
hsa-mir-1253   4.325359

[24510 rows x 1 columns]

# prepare signatures

### seperating the aanotated up and downregulated genes

In [ ]:
#  up= pandas.read_csv("singscore_new_code/FOROUTAN_PRODRANK_TGFB_EMT_UP.txt", sep="\t",header=None)
#  up= up[0].to_list()
#  up

['ABCA1',
 'ACKR3',
 'ACTN1',
 'ADAM12',
 'ADAM19',
 'ADAMTS6',
 'AKT3',
 'ALOX5AP',
 'AMIGO2',
 'ANGPTL4',
 'ANKLE2',
 'AP1S2',
 'APBB2',
 'ARFGAP1',
 'ARHGEF40',
 'BHLHE40',
 'BMAL1',
 'BMP1',
 'BMP2',
 'BMPR2',
 'BPGM',
 'C3orf52',
 'CALD1',
 'CCN2',
 'CD59',
 'CDH11',
 'CDH2',
 'CDK14',
 'CHRNA9',
 'CHST11',
 'COL1A1',
 'COL4A1',
 'COL4A2',
 'COL5A1',
 'COL7A1',
 'CRLF1',
 'CYTH1',
 'DAAM1',
 'DACT1',
 'DHRS2',
 'DIXDC1',
 'DLC1',
 'DOCK4',
 'DSE',
 'DUSP10',
 'ELK3',
 'EML1',
 'EPHB2',
 'ETS2',
 'FAM114A1',
 'FBN1',
 'FERMT2',
 'FHOD3',
 'FN1',
 'FOXD1',
 'FSTL3',
 'GADD45B',
 'GAL',
 'GALNT10',
 'GASK1B',
 'GFPT2',
 'GLIPR1',
 'GNG11',
 'GRB10',
 'GREM1',
 'HMGA2',
 'HMOX1',
 'HRH1',
 'HS3ST3A1',
 'HSF2BP',
 'HTRA1',
 'IGFBP5',
 'IGFBP7',
 'IL11',
 'INHBA',
 'INPP4B',
 'ITGA5',
 'ITGB3',
 'JAG1',
 'JARID2',
 'JUN',
 'JUNB',
 'KCNJ15',
 'KCNMA1',
 'KDELR3',
 'KLF7',
 'LAMC2',
 'LARP6',
 'LBH',
 'LMCD1',
 'LOX',
 'MAF',
 'MAGED2',
 'MAP1LC3B',
 'MATN3',
 'MBOAT2',
 'MFAP2',
 'MICAL2',
 'MMP1',
 'MMP10',
 'MMP2',
 'MMP9',
 'MN1',
 'MRC2',
 'MYL9',
 'MYO10',
 'NCF2',
 'NEDD9',
 'NKX3-1',
 'NREP',
 'NRIP3',
 'NT5E',
 'NUAK1',
 'PALLD',
 'PDGFA',
 'PDGFC',
 'PDLIM7',
 'PEA15',
 'PID1',
 'PIK3CD',
 'PLAUR',
 'PLEK2',
 'PMEPA1',
 'PODXL',
 'POSTN',
 'PRR5L',
 'PSMD2',
 'PTHLH',
 'PTPN21',
 'PTPRK',
 'PXDC1',
 'RALA',
 'RFTN1',
 'RGS4',
 'RUNX2',
 'SACS',
 'SCG5',
 'SEMA3C',
 'SERPINE1',
 'SERPINE2',
 'SIK1',
 'SKIL',
 'SLC22A4',
 'SLC26A2',
 'SLCO2A1',
 'SLN',
 'SMAD7',
 'SMURF2',
 'SNAI2',
 'SPARC',
 'SPDL1',
 'SPHK1',
 'SPOCK1',
 'SRPX',
 'SRRD',
 'STC1',
 'TAGLN',
 'TAGLN2',
 'TBX3',
 'TCF4',
 'TFPI2',
 'TGFB1',
 'TGFB1I1',
 'TGFBI',
 'TGM2',
 'THBS1',
 'TIMP2',
 'TMCC1',
 'TNFAIP6',
 'TNS1',
 'TP53I3',
 'TPM1',
 'TPM4',
 'TPST1',
 'TPST2',
 'TUBA1A',
 'TUBA4A',
 'TUFT1',
 'VCAN',
 'VEGFC',
 'VIM',
 'WNT5A',
 'WNT5B',
 'XYLT1',
 'ZNF365']

In [ ]:
# down= pandas.read_csv("singscore_new_code/FOROUTAN_PRODRANK_TGFB_EMT_DN.txt", sep="\t",header=None)
# down= down[0].to_list()
# down

['ABLIM1',
 'ADORA2B',
 'AGR2',
 'ALDH3A2',
 'ALDH5A1',
 'ANK3',
 'AREG',
 'ARHGAP29',
 'BIRC3',
 'C1orf115',
 'C1orf116',
 'CAVIN2',
 'CD9',
 'CDH1',
 'CEBPD',
 'CITED2',
 'CXADR',
 'CYB5A',
 'CYP1B1',
 'DEPTOR',
 'DST',
 'EHF',
 'ELF3',
 'EPAS1',
 'EPB41L4B',
 'EPCAM',
 'ERBB3',
 'EREG',
 'ERMP1',
 'ESRP1',
 'FOXA2',
 'GDF15',
 'GLDC',
 'GPRC5C',
 'GSE1',
 'GULP1',
 'HOOK1',
 'HPGD',
 'IMPA2',
 'JAG2',
 'KITLG',
 'KRT19',
 'LAMA5',
 'LY6E',
 'MAP7',
 'MBP',
 'MITF',
 'MMP7',
 'MTUS1',
 'MUC1',
 'MYO5C',
 'NR2F2',
 'NUP210',
 'PDK4',
 'PEG10',
 'PKP2',
 'PLAAT3',
 'PLAAT4',
 'PLS1',
 'PPL',
 'PPP1R9A',
 'RAB26',
 'RAB38',
 'RBM47',
 'S100P',
 'SCNN1A',
 'SERPINB1',
 'SLC16A7',
 'SLC27A2',
 'SLCO4A1',
 'SMPDL3B',
 'SORD',
 'SPRY1',
 'SQOR',
 'SULT1A1',
 'SYBU',
 'TBC1D8',
 'TFAP2A',
 'TJP2',
 'TMT1A',
 'TNFAIP2',
 'TPD52L1']

In [ ]:
# sigs = pandas.read_csv(open(sig_path, 'r'), header=
# 'infer', sep='\t')
# sigs

,EntrezID,Symbol,upDown_integrative_signature,upDown_comparative_signature,upDown
0,19,ABCA1,0,up,up
1,87,ACTN1,0,up,up
2,136,ADORA2B,0,down,down
3,182,JAG1,up,up,up
4,220,ALDH1A3,down,0,down
...,...,...,...,...,...
296,161291,TMEM30B,down,0,down
297,221749,C6orf145,0,up,up
298,347902,AMIGO2,0,up,up
299,389136,VGLL3,up,0,up
300,402055,SRRD,0,up,up

In [ ]:
# # subset the data for up and down
# up = sigs[sigs['upDown'] == 'up']
# down = sigs[sigs['upDown'] == 'down']
# up

,EntrezID,Symbol,upDown_integrative_signature,upDown_comparative_signature,upDown
0,19,ABCA1,0,up,up
1,87,ACTN1,0,up,up
3,182,JAG1,up,up,up
6,241,ALOX5AP,up,up,up
8,323,APBB2,0,up,up
...,...,...,...,...,...
295,150094,SIK1,0,up,up
297,221749,C6orf145,0,up,up
298,347902,AMIGO2,0,up,up
299,389136,VGLL3,up,0,up
300,402055,SRRD,0,up,up

In [ ]:
# get a list of ids
# up = list(up['Symbol'])
# down = list(down['Symbol'])
# up

['ABCA1',
 'ACTN1',
 'JAG1',
 'ALOX5AP',
 'APBB2',
 'ARNTL',
 'BMP1',
 'BMP2',
 'BMPR2',
 'BPGM',
 'CALD1',
 'RUNX2',
 'CD59',
 'CDH2',
 'CDH11',
 'COL1A1',
 'COL3A1',
 'COL4A1',
 'COL4A2',
 'COL5A1',
 'COL5A2',
 'COL6A3',
 'COL7A1',
 'VCAN',
 'CTGF',
 'SLC26A2',
 'ELK3',
 'EML1',
 'EPHB2',
 'ETS2',
 'FBN1',
 'FOXD1',
 'FN1',
 'GNG11',
 'GRB10',
 'HMOX1',
 'HRH1',
 'IGFBP5',
 'IGFBP7',
 'IL11',
 'INHBA',
 'ITGA5',
 'ITGB3',
 'JARID2',
 'JUN',
 'JUNB',
 'KCNJ15',
 'KCNMA1',
 'LAMC2',
 'LOX',
 'LUM',
 'SMAD7',
 'MAF',
 'MATN3',
 'MFAP2',
 'MMP1',
 'MMP2',
 'MMP9',
 'MMP10',
 'MN1',
 'GADD45B',
 'MYO10',
 'NCF2',
 'NEDD9',
 'NKX3-1',
 'NT5E',
 'SERPINE1',
 'PDGFA',
 'PFTK1',
 'SERPINE2',
 'PIK3CD',
 'PLAUR',
 'PODXL',
 'HTRA1',
 'PSMD2',
 'PTHLH',
 'PTPRK',
 'RALA',
 'RGS4',
 'SCG5',
 'SKIL',
 'SLCO2A1',
 'SLC22A4',
 'SLN',
 'SNAI2',
 'SPARC',
 'SPOCK1',
 'STC1',
 'TAGLN',
 'TCF4',
 'TBX3',
 'TGFB1',
 'TGFB1I1',
 'TGFBI',
 'TGM2',
 'THBS1',
 'TIMP2',
 'TNFAIP6',
 'TNS1',
 'TPM1',
 'TPM4',
 'TUBA4A',
 'TUFT1',
 'VEGFC',
 'VIM',
 'WNT5A',
 'TUBA1A',
 'SCG2',
 'TFPI2',
 'ADAM12',
 'HMGA2',
 'SRPX',
 'TAGLN2',
 'TPST2',
 'TPST1',
 'BHLHB2',
 'KLF7',
 'PEA15',
 'ADAM19',
 'INPP4B',
 'SPHK1',
 'AP1S2',
 'CRLF1',
 'PDLIM7',
 'PSCD1',
 'C5orf13',
 'TP53I3',
 'MICAL2',
 'DOCK4',
 'NUAK1',
 'MRC2',
 'GFPT2',
 'HS3ST3B1',
 'HS3ST3A1',
 'AKT3',
 'DHRS2',
 'FSTL3',
 'DLC1',
 'MYL9',
 'SEMA3C',
 'POSTN',
 'MAGED2',
 'FERMT2',
 'GLIPR1',
 'KDELR3',
 'HSF2BP',
 'PTPN21',
 'ADAMTS6',
 'DUSP10',
 'ZNF365',
 'DAAM1',
 'PALLD',
 'TMCC1',
 'KIAA0692',
 'RFTN1',
 'SACS',
 'PLEK2',
 'GREM1',
 'LOH3CR2A',
 'DSE',
 'LMCD1',
 'CHST11',
 'GAL',
 'ANGPTL4',
 'C4orf18',
 'DACT1',
 'CCDC99',
 'PID1',
 'LARP6',
 'GALNT10',
 'CHRNA9',
 'FLJ10357',
 'ARFGAP1',
 'PDGFC',
 'NRIP3',
 'PMEPA1',
 'CXCR7',
 'XYLT1',
 'SMURF2',
 'C3orf52',
 'FLJ14213',
 'FHOD3',
 'WNT5B',
 'LBH',
 'MAP1LC3B',
 'DIXDC1',
 'FAM114A1',
 'MBOAT2',
 'SIK1',
 'C6orf145',
 'AMIGO2',
 'VGLL3',
 'SRRD']

## Palbocilib resistance check

In [ ]:
# down= pandas.read_csv("singscore_new_code/Palbocilib_resistance_down_genes.txt", sep="\t",header=None)
# down= down[0].to_list()
# down

['P3H3',
 'CPNE7',
 'ITGBL1',
 'AFAP1L1',
 'PLEKHH2',
 'NUDT13',
 'HELB',
 'SEL1L3',
 'DMC1',
 'NRP2',
 'AK7',
 'MACROD1',
 'DOCK10',
 'TMEM71',
 'LUCAT1',
 'RAB38',
 'CCDC110',
 'FAM160A1',
 'C2orf88',
 'GABBR2',
 'DUSP5',
 'MIR17HG',
 'CHEK1',
 'KRBOX1',
 'SLAIN1',
 'NAGS',
 'FABP3',
 'VSIG2',
 'TMC8',
 'ALDH8A1',
 'ZNF287',
 'KDELC2',
 'FXYD3',
 'LURAP1L-AS1',
 'C1orf115',
 'ACSM3',
 'PDE3B',
 'CLMN',
 'NPAT',
 'RN7SL73P',
 'CPNE9',
 'HNRNPA1P67',
 'TRPC3',
 'SULT1A1',
 'STRIP2',
 'IL1RL2',
 'OSMR-AS1',
 'FAM184A',
 'C3orf67',
 'ARNTL2',
 'CA9',
 'KBTBD3',
 'BUD13',
 'SFTA1P',
 'BCL2L11',
 'E2F8',
 'DAW1',
 'RNA5SP236',
 'PARD6A',
 'RFX3',
 'C6orf141',
 'HTR1D',
 'ARHGAP9',
 'ALMS1-IT1',
 'PYY',
 'TAF1D',
 'RPL7AP30',
 'NSUN7',
 'CRHBP',
 'SLC37A4',
 'TNIP3',
 'EFEMP2',
 'FDXACB1',
 'MIR4500HG',
 'ARHGAP32',
 'ERI1',
 'NQO1',
 'STEAP1',
 'CEP57',
 'ADGRV1',
 'DGKH',
 'PDE4D',
 'C5',
 'RPL22L1',
 'NCAM2',
 'PDLIM3',
 'GPR17',
 'HMGB2',
 'NYNRIN',
 'CNTRL',
 'IL24',
 'GRB14',
 'PPP1R3C',
 'ARHGAP30',
 'KISS1',
 'MYO7B',
 'FIGF',
 'NEMP2',
 'ZNF660',
 'RN7SKP11',
 'APBB1IP',
 'MIR100HG',
 'USP2-AS1',
 'C2orf48',
 'ZNF747',
 'HPSE',
 'FAM109B',
 'CRNDE',
 'KIAA1211',
 'SLC7A11',
 'ALDH1L1',
 'SLC7A2',
 'PCSK9',
 'MT1JP',
 'CHST4',
 'ECSCR',
 'LINC01322',
 'PPP1R3B',
 'IRX5',
 'COBLL1',
 'TMEM45B',
 'EPCAM',
 'APOC1',
 'RGN',
 'RAP1GAP2',
 'STOM',
 'CKMT1B',
 'TEX14',
 'MTMR8',
 'GMFG',
 'CCNA1',
 'IL18',
 'FAM24B',
 'ESAM',
 'MBOAT1',
 'ACOT4',
 'OCLN',
 'CACNB4',
 'ST6GALNAC3',
 'SMCO2',
 'PIK3CG',
 'CA2',
 'FAM83B',
 'HENMT1',
 'GPM6B',
 'CIART',
 'MAGI2-AS3',
 'EXPH5',
 'HTRA3',
 'SLC15A1',
 'ESR1',
 'CKMT1A',
 'NPR3',
 'SPTSSB',
 'MEI4',
 'BMP6',
 'KCTD19',
 'ESRP2',
 'PHGDH',
 'LINC00942',
 'SOBP',
 'ATF7IP2',
 'KIF5C',
 'LRRC36',
 'NRIP3',
 'GSX2',
 'TMEM163',
 'GALNT14',
 'NUP210',
 'KDR',
 'ARL10',
 'MYB',
 'LINC00707',
 'CNKSR2',
 'SNCAIP',
 'TSTD1',
 'ZNF662',
 'CST6',
 'GAL',
 'CD2',
 'RAMP2',
 'PQLC2L',
 'ANKRD20A7P',
 'IGHV3OR16-7',
 'TPTE']

In [ ]:
#  up= pandas.read_csv("singscore_new_code/Palbocilib_resistance_up_genes.txt", sep="\t",header=None)
#  up= up[0].to_list()
#  up

['DGKG',
 'DUSP13',
 'PALMD',
 'CLEC11A',
 'CCL2',
 'GCG',
 'TREM1',
 'DEFB126',
 'IDO1',
 'FCRLA',
 'LINC00470',
 'JCHAIN',
 'DYDC2',
 'SLCO2B1',
 'SLC2A5',
 'ZNF300',
 'KCNK13',
 'ART3',
 'LYZL4',
 'PAGE5',
 'S100B',
 'SLAMF9',
 'SPINK1',
 'DRGX',
 'BTNL9',
 'TMEM100',
 'SPRY3',
 'VGLL2',
 'SLN',
 'CST5',
 'C8orf74',
 'ANO5',
 'RIIAD1',
 'PDE6G',
 'MORN5',
 'NAP1L3',
 'CYP4X1',
 'SNTN',
 'DCAF8L2',
 'CSAG1',
 'LRRC37A5P',
 'TRAV18',
 'SPINK13',
 'LINC01133',
 'ZNF503-AS1',
 'SLC8A1-AS1',
 'LINC01515',
 'KRT16P4',
 'LINC00892',
 'ZDHHC20P1',
 'CBX1P3',
 'HLA-DQA2',
 'RNU2-11P',
 'SYNPR-AS1',
 'LINC00871',
 'LINC00639',
 'LINC00648',
 'RN7SL811P',
 'TOP1P1',
 'SIGLEC22P',
 'ERVV-2',
 'CCL3',
 'GRAMD1B',
 'RYR2',
 'CPA3',
 'SLC9C2',
 'FLRT3',
 'CHRDL1',
 'LBH',
 'LRRC15',
 'INHBA',
 'FAM134B',
 'SLCO1A2',
 'CLIC2',
 'TNFSF15',
 'TSPAN7',
 'IGFBP5',
 'VIPR1',
 'CYP17A1',
 'FAM133A',
 'SPN',
 'BCHE',
 'LGALS9',
 'SH2D1B',
 'ANGPTL4',
 'KCNN3',
 'SPOCK1',
 'CPEB1',
 'SLITRK6',
 'SCN8A',
 'VIPR1-AS1',
 'DNAH10',
 'CD33',
 'LCN2',
 'SPANXB1',
 'TTC3P1',
 'PLEKHS1',
 'SPANXC',
 'LINC01268',
 'GPR158',
 'SEPP1',
 'DAAM2',
 'ANXA8L1',
 'LDLRAD4',
 'TCN1',
 'RNF43',
 'LINC01615',
 'NGFR',
 'OVCH2',
 'MOB3B',
 'HSPB8',
 'TMEM63C',
 'MEIS1',
 'FAM26E',
 'PITX2',
 'PLCZ1',
 'FOLR1',
 'MRGPRX3',
 'TMEM98',
 'MYL1',
 'FAM83A',
 'ANO2',
 'MMP8',
 'SEMA6D',
 'CDH11',
 'ADGRF4',
 'SERPINA5',
 'DNER',
 'C4orf19',
 'TFCP2L1',
 'AFAP1-AS1',
 'SCARA5',
 'C4orf26',
 'UCA1',
 'FRMD3',
 'ADCY5',
 'CCL5',
 'SCG2',
 'SLAMF7',
 'PCDHB2',
 'GPRC5C',
 'DIO2',
 'DUSP15',
 'PLCH2',
 'KRT81',
 'UNC13A',
 'QPRT',
 'AP3B2',
 'PMEPA1',
 'FLI1',
 'VSTM2L',
 'COL21A1',
 'C15orf48',
 'LINC01085',
 'OAS1',
 'RARRES2',
 'INHBB',
 'VASH1',
 'PDE1C',
 'APOL1',
 'CHST9',
 'VSTM4',
 'PBX1',
 'ADAM28',
 'DNAH10OS',
 'SDR16C5',
 'TLR4',
 'LONRF2',
 'ANKRD30B',
 'RAB6B',
 'ALPK2',
 'ZNF542P',
 'ARHGAP28',
 'TGM2',
 'TMEM169',
 'AADACP1',
 'HSD17B3',
 'EDARADD',
 'SLC16A2',
 'COL6A2',
 'CST4',
 'KATNAL2',
 'SPX',
 'COL6A1',
 'CPA4',
 'CIB2',
 'FIRRE',
 'FBXO39',
 'CES3',
 'ENPP2',
 'NLRP2',
 'APOE',
 'COL6A3',
 'THSD7B',
 'ADORA1',
 'LYPD8',
 'NDP',
 'PROM2',
 'CNTN1',
 'ROBO1',
 'ACKR3',
 'HOXB-AS1',
 'CXCL11',
 'CCL26',
 'RHOJ',
 'NXF3',
 'HSPA6',
 'FPR1',
 'MAOB',
 'ADGRG2',
 'FBXO2',
 'TRIM61',
 'CST2',
 'CFI',
 'LYZ',
 'ICOSLG',
 'COL15A1',
 'OR2T4',
 'ADAMTS14',
 'CST7',
 'F13A1',
 'CEMIP',
 'PARK2',
 'KCNJ15',
 'CYGB',
 'ST6GALNAC5',
 'SH2D2A',
 'FGF13',
 'CSF2',
 'HIST1H4H',
 'CEACAM1',
 'TRPV4',
 'FPR2',
 'ANXA10',
 'BPI',
 'PLP1',
 'TSPEAR-AS2',
 'GPR35',
 'SAMD9L',
 'LINC01341',
 'PCDH1',
 'SELENBP1',
 'GPR55',
 'TUBB4A',
 'ARL14',
 'ABCA1',
 'EHD3',
 'CRYAB',
 'PTPRB',
 'MGAM',
 'ALOX5AP',
 'RCAN2',
 'ZC3H12B',
 'RTP4',
 'LEMD1',
 'TFAP2C',
 'SAA2',
 'NHSL2',
 'PCBP3',
 'ALPP',
 'TP53I11',
 'DTNA',
 'RASD2',
 'CASC10',
 'WNK2',
 'MCF2L',
 'MLLT11',
 'LINC00473',
 'C10orf11',
 'TMEM221',
 'PLA2G4C',
 'ATOH8',
 'ZDHHC11',
 'MFNG',
 'VAV1',
 'TFF2',
 'EHF',
 'SCG5',
 'SAA1',
 'HLA-DQB2',
 'DGCR5',
 'ABCA7',
 'LINC01139',
 'ABCA13',
 'KIAA1462',
 'TMTC1',
 'PTPN6',
 'F2RL2',
 'AK8',
 'KLHL3',
 'CXCL16',
 'ITGB8',
 'LINC01561',
 'SLC2A10',
 'GRIK2',
 'HOXC4',
 'PSG1',
 'C10orf90',
 'ANXA8',
 'SMAD6',
 'FGF11',
 'SGSM1',
 'SCEL',
 'CDK20',
 'A2M',
 'SLC26A7',
 'SLC9A7P1',
 'DKKL1',
 'RINL',
 'MISP',
 'KLRC4-KLRK1',
 'IL1B',
 'RYR3',
 'NAPSA',
 'AQP1',
 'SYT17',
 'TNS1',
 'SERPINF1',
 'MAP1A',
 'BLACAT1',
 'STXBP6',
 'CAMSAP3',
 'P2RX6',
 'PAPPA-AS1',
 'KCNAB3',
 'GAS7',
 'TRHDE',
 'FABP6',
 'FAM222A',
 'TNFSF10',
 'SCN2A',
 'RORA',
 'HLF',
 'IGF2',
 'COL5A1',
 'CXCL14',
 'CAMK1G',
 'BSCL2',
 'NKAPP1',
 'LANCL3',
 'ABCA8',
 'CYP2E1',
 'PSG6',
 'VNN1',
 'TMEM229B',
 'CACNG7',
 'DDO',
 'PAPPA',
 'PPP5D1',
 'NPL',
 'ZNF575',
 'POU2F3',
 'PLAT',
 'FOSB',
 'SPON1',
 'DHRS3',
 'GBP5',
 'TIMP3',
 'NTNG2',
 'LRP1',
 'GNAZ',
 'MIR22HG',
 'PSG9',
 'WNT9A',
 'ALS2CR11',
 'CD177',
 'FAM20C',
 'PROM1',
 'PIGZ',
 'POPDC2',
 'SLC7A9',
 'GCNT3',
 'MDFI',
 'SLC30A10',
 'BRSK2',
 'NTM',
 'SPP1',
 'PLD5',
 'GABRE',
 'DNAH12',
 'NWD1',
 'NLRP10',
 'S100A1',
 'TSPAN9',
 'MAP2K6',
 'LYPD6B',
 'ZNF521',
 'LINC01589',
 'CST1',
 'TESC',
 'IPO5P1',
 'ASB2',
 'DOCK8',
 'MIR3142HG',
 'PTGS2',
 'PAX9',
 'GPER1',
 'PRKRIRP8',
 'KLRC2',
 'NDST3',
 'MUC1',
 'FAM179A',
 'C1S',
 'DPF3',
 'MIA',
 'SERPING1',
 'RPL23AP49',
 'HLA-DRB6',
 'LINC00887',
 'EML1',
 'PDGFB',
 'MAP1LC3C',
 'ITGA7',
 'FAM198B',
 'PSG5',
 'ADGRF1',
 'AARD',
 'SULT1C2',
 'RAB3A',
 'C1orf145',
 'DBH',
 'KLRC3',
 'TDO2',
 'DYNLRB2',
 'TMIE',
 'BMPER',
 'MYO15B',
 'ZNF117',
 'RSAD2',
 'HDX',
 'LTBP3',
 'CD34',
 'TTLL9',
 'INPP5J',
 'NOTCH3',
 'TSACC',
 'ZFP3',
 'RIMS1',
 'COPZ2',
 'C1orf106',
 'SEMA6A',
 'COL4A6',
 'SDC2',
 'SHROOM2',
 'TNFAIP8L3',
 'SERPINF2',
 'LPAR2',
 'CT62',
 'EFNB1',
 'RASSF9',
 'ANKLE1',
 'C5AR1',
 'LINC01296',
 'FAM155A',
 'SCNN1A',
 'ZNF594',
 'LST1',
 'ADGRF5',
 'MB',
 'PADI1',
 'ATP6V0D2',
 'GPR85',
 'DPYSL3',
 'C15orf54',
 'LFNG',
 'LAMA5',
 'ZNF467',
 'TNFSF13B',
 'RGS7',
 'MPZL2',
 'CALCR',
 'LINC00973',
 'ALDH1A2',
 'SOST',
 'CHI3L2',
 'RASA4CP',
 'SHISA4',
 'TSNAXIP1',
 'OLFML3',
 'SYT7',
 'HIST2H2BE',
 'FER1L4',
 'LPAR5',
 'ROGDI',
 'HLA-DQB1',
 'CCR1',
 'CXCL1',
 'KRT7',
 'C17orf97',
 'WNT7B',
 'SEMA3A',
 'MSX2',
 'C3',
 'OPRL1',
 'PRSS22',
 'CFH',
 'L1CAM',
 'ABCD1',
 'MIR99AHG',
 'CSF1R',
 'CDK18',
 'VCAN',
 'APOBEC3G',
 'SYT1',
 'ZC3H12D',
 'PALM',
 'CCDC190',
 'CDK5R2',
 'MX2',
 'DACT3',
 'ZSWIM5',
 'FAM172BP',
 'ADCK1',
 'ISG15',
 'TMCC2',
 'CDNF',
 'C21orf2',
 'CMKLR1',
 'ESM1',
 'TNFSF4',
 'AFP',
 'SLCO3A1',
 'NCF2',
 'LINC01411',
 'F3',
 'ATP8A1',
 'S1PR3',
 'LCMT1-AS1',
 'ZNF66',
 'ARHGEF37',
 'FAM189A2',
 'ITGA2B',
 'BTC',
 'PRR29',
 'IDUA',
 'SELPLG',
 'CSGALNACT1',
 'MICALL2',
 'XDH',
 'NEBL',
 'GPR1',
 'GBP4',
 'LINC01234',
 'AFF3',
 'CYP19A1',
 'DENND6B',
 'S100A5',
 'TAGLN2',
 'OAS2',
 'OR2M4',
 'CFAP44',
 'WT1',
 'PPP1R1B',
 'APLP1',
 'WFDC2',
 'ADAMTS9-AS1',
 'SLC22A4',
 'MROH6',
 'OLFM2',
 'BZRAP1',
 'VNN2',
 'SOX4',
 'HLA-DRB5',
 'ONECUT2',
 'KIAA1755',
 'SRGAP3',
 'XAF1',
 'ADAMTS9',
 'LCP1',
 'MXRA8',
 'RGAG4',
 'HIST1H2AC',
 'DBH-AS1',
 'IFI6',
 'TNFRSF9',
 'NRG2',
 'NRG4',
 'QRICH2',
 'TNFRSF19',
 'ID3',
 'LINC01012',
 'PTGFRN',
 'PLAU',
 'SERINC2',
 'SPNS2',
 'ARHGEF6',
 'ASIC3',
 'OASL',
 'ARSA',
 'SHC2',
 'RNASEL',
 'HIST2H2BA',
 'LAPTM5',
 'PTPRR',
 'KLHDC9',
 'LY6E',
 'KIFC2',
 'LMNTD2',
 'DMPK',
 'PLXDC2',
 'C2',
 'GBP1',
 'GPRC5B',
 'FBN1',
 'FGFBP1',
 'GIMAP2',
 'GNG2',
 'RRAD',
 'TNFRSF11B',
 'COL5A2',
 'TDRD12',
 'ABLIM2',
 'FLG',
 'LPAR4',
 'CCDC40',
 'FBXO32',
 'ATF5',
 'LOXL4',
 'MID2',
 'LINC00632',
 'CSF3',
 'MNX1-AS1',
 'MPZL3',
 'MSLN',
 'RGS4',
 'RCSD1',
 'FHDC1',
 'TMEM86A',
 'BMP5',
 'IFNLR1',
 'NOV',
 'SWSAP1',
 'ENTPD3',
 'SLC52A3',
 'VSIG1',
 'ADGRF5P2',
 'EGF',
 'TRIM9',
 'ONECUT1',
 'MEI1',
 'LINC01224',
 'LINC00313',
 'P4HA2',
 'TJP3',
 'PAQR6',
 'IFI30',
 'SORBS2',
 'DZIP1',
 'PLXNA1',
 'CYB5R2',
 'SEMA6C',
 'MBL1P',
 'TPRG1',
 'RPS6KA2',
 'MAL2',
 'MFAP5',
 'GRPR',
 'PLEKHB1',
 'PCDH18',
 'GPR65',
 'FILIP1',
 'SNAI2',
 'TBXA2R',
 'C5orf56',
 'MPP4',
 'CCDC64',
 'JUP',
 'PLXNB3',
 'PLXNA3',
 'ATP2A1',
 'SLC12A7',
 'APOL3',
 'FN1',
 'GPR153',
 'PCDH7',
 'GBGT1',
 'NBEAP3',
 'SLC25A21',
 'CMAHP',
 'B3GALT5',
 'SIRT2',
 'GALNT16',
 'LINC00342',
 'HCAR1',
 'TCEA2',
 'PRUNE2',
 'ZNF324B',
 'DCDC1',
 'SLC16A4',
 'SORBS1',
 'VDR',
 'ZNF703',
 'HIST2H2BF',
 'PCDHB8',
 'MYL9',
 'LINC01443',
 'FMO5',
 'CMYA5',
 'IL7R',
 'HAND1',
 'PTPRU',
 'APOL2',
 'PRSS54',
 'FAM174B',
 'GPX7',
 'SERPINC1',
 'SLC6A8',
 'PSG4',
 'SORCS2',
 'FHOD3',
 'ZBTB7B',
 'NES',
 'PIK3C2B',
 'SLC7A5',
 'ANO8',
 'OVGP1',
 'SDSL',
 'LINC00205',
 'EEF1A2',
 'P2RY6',
 'MYO15A',
 'C10orf91',
 'LINC00460',
 'ABCC6P1',
 'LOXL1',
 'HES2',
 'HES1',
 'IFIT2',
 'PADI3',
 'FKBP9P1',
 'KCNIP3',
 'NIM1K',
 'SEMA7A',
 'SYPL2',
 'GNG7',
 'PLOD1',
 'FAM58A',
 'MUSK',
 'CD96',
 'YJEFN3',
 'CD37',
 'PEX5L',
 'COL18A1',
 'CES4A',
 'SLC38A4',
 'Mar-10',
 'LINC01134',
 'GPRASP1',
 'DHRS2',
 'TRIML2',
 'FOS',
 'S100A4',
 'DOK3',
 'CCDC69',
 'USP18',
 'KYNU',
 'TMEM102',
 'RABAC1',
 'AIM2',
 'H2BFM',
 'FAXDC2',
 'LINC00520',
 'SAMD9',
 'TPM1',
 'C19orf57',
 'CNIH3',
 'TGFB2-OT1',
 'CCDC24',
 'HHIPL2',
 'CD99L2',
 'PLPPR2',
 'SERPINB9P1',
 'SLC9A2',
 'C19orf18',
 'CD226',
 'FAM43A',
 'LINC00337',
 'C1orf101',
 'LYPD1',
 'ATG9B',
 'TP53TG3D',
 'ECM1']

## gene set reactome cyclinD associated events in G1

In [4]:
down= pandas.read_csv("singscore_new_code/cyclind_down_genes.txt", sep="\t",header=None)
down= down[0].to_list()
down

['CCND1',
 'CCND2',
 'CCND3',
 'CDK2',
 'CDK4',
 'CDK6',
 'CDK7',
 'CUL1',
 'E2F1',
 'E2F2',
 'E2F3',
 'E2F4',
 'E2F5',
 'SKP1',
 'SKP2']

In [5]:
up= pandas.read_csv("singscore_new_code/cyclind_up_genes.txt", sep="\t",header=None)
up= up[0].to_list()
up

['CCNE1',
 'CCNE2',
 'CDKN1A',
 'CDKN1B',
 'CDKN1C',
 'CDKN2A',
 'CDKN2B',
 'CDKN2C',
 'CDKN2D',
 'RB1',
 'RBL1',
 'RBL2',
 'UBA52',
 'UBB',
 'UBC']

In [6]:
print(f'{len(up), len(down)}')

(15, 15)

In [7]:
up_present = [gene for gene in up if gene in data.index]
down_present = [gene for gene in down if gene in data.index]

# Print counts and summary
print(f"Total up genes in signature: {len(up)}")
print(f"Up genes found in expression data: {len(up_present)}")

print(f"Total down genes in signature: {len(down)}")
print(f"Down genes found in expression data: {len(down_present)}")

# Optionally, print the missing ones
missing_up = set(up) - set(data.index)
missing_down = set(down) - set(data.index)

print(f"Missing up genes: {len(missing_up)}")
print(f"Missing down genes: {len(missing_down)}")

Total up genes in signature: 15
Up genes found in expression data: 15
Total down genes in signature: 15
Down genes found in expression data: 15
Missing up genes: 0
Missing down genes: 0

# Scoring the genes

In [11]:
scored_data = score(up_gene=up, down_gene=False, sample=data,
                    norm_method='theoretical', full_data=True)
print(scored_data)

          total_score    total_mad
log2_TPM     0.168305  4919.274161

In [47]:
# plot dispersion of scores
output_path = os.path.normpath('{}/{}'.format(BASE_DIR,
                                    'singscore/test/output_JN/dispersion_UK65_cyclind.png'))

plotdispersion(scored_data, ctrlstring='Ctrl', teststring='TGFb',
               testlabel='TGFb', colour_1='g', colour_2='b',
               outpath=output_path, show=False)

### for permutations/pvalue to be correctly calculated the genes rtandomly selected shiould be equal to the genes present in the rna-seq data of up and down gene list

In [64]:
output_path = os.path.normpath('{}/{}'.format(BASE_DIR,
                                        'singscore/test/output_JN/nulldist_UK65_cyclind.png'))
permd = permutate(data, n_up=len(up_present), n_down=False)
pvals = empiricalpval(permutations=permd, score=scored_data)
print(pvals)

          empirical p value
log2_TPM           0.011299

In [49]:
nulldistribution(permutations=permd, score=scored_data, nrows=2, ncols=5,
                 threshold=0.05, outpath=output_path, show=False)

d:\GS\PySingscore_replicate\singscore\singscore.py:857: UserWarning:

`distplot` is a deprecated function and will be removed in seaborn v0.14.0.

Please adapt your code to use either `displot` (a figure-level function with
similar flexibility) or `histplot` (an axes-level function for histograms).

For a guide to updating your code to use the new functions, please see
https://gist.github.com/mwaskom/de44147ed2974457ad6372750bbe5751

  seaborn.distplot(permutations[p],hist=True, kde_kws={'color':color},

In [4]:
import os
import json
import pandas as pd
from pathlib import Path
from datetime import datetime
import shutil
import tempfile
from typing import Dict

# import singscore functions (adjust import if your package layout differs)
from singscore.singscore import *

def singscore_pathway_report(entrez_sample_path: str,
                             up_path: str,
                             down_path: str,
                             pathway_name: str,
                             norm_method: str = 'theoretical',
                             perms: int = 10000,
                             full_data: bool = True):
    """
    Run singscore for a pathway and return results in dict (JSON-able) format.

    Parameters
    ----------
    entrez_sample_path : str
        Path to expression matrix (tab-delimited). First column = gene id column name (e.g. "GeneName").
    up_path : str
        Path to file with up-regulated gene symbols (one per line).
    down_path : str
        Path to file with down-regulated gene symbols (one per line).
    pathway_name : str
        Display name for the pathway.
    norm_method : str
        Normalisation used by score(); default 'theoretical'.
    perms : int
        Number of permutations for empirical p-value (default 10000).
    full_data : bool
        Whether to request full_data=True from score().

    Returns
    -------
    dict
        JSON-serializable dictionary with pathway, gene_set_info, scores, statistics.
    """
    # --- Read expression data ---
    if not os.path.exists(entrez_sample_path):
        raise FileNotFoundError(f"Expression file not found: {entrez_sample_path}")
    # autodetect separator: assume tab-delimited like your example
    df = pd.read_csv(entrez_sample_path, sep="\t", header=0, index_col=0)
    # df index are gene identifiers (matching the signature)
    
    # --- Read gene lists ---
    def read_list(path):
        if not os.path.exists(path):
            raise FileNotFoundError(f"Gene list file not found: {path}")
        s = pd.read_csv(path, header=None, sep="\t", comment='#', engine='python')
        # first column contains gene symbols/ids
        return [str(x).strip() for x in s.iloc[:,0].tolist() if pd.notna(x)]
    
    up = read_list(up_path)
    down = read_list(down_path)
    
    # --- Check coverage in dataset (genes present) ---
    up_present = [g for g in up if g in df.index]
    down_present = [g for g in down if g in df.index]
    
    # --- Optional: warn about missing genes ---
    missing_up = set(up) - set(up_present)
    missing_down = set(down) - set(down_present)
    
    # --- Compute singscore ---
    # Use the original lists as inputs to score(); singscore internally ignores missing genes.
    scored = score(up_gene=up, down_gene=down, sample=df,
                   norm_method=norm_method, full_data=full_data)
    # scored is typically a DataFrame (rows = sample(s), columns include up_score, down_score, total_score)
    
    # Attempt to extract the numeric scores for the first sample (or the only sample)
    if isinstance(scored, pd.DataFrame):
        # If there are multiple rows (samples), pick the first row
        sample_row = scored.iloc[0]
        # Common column names in singscore outputs:
        # try several possibilities for column names
        col_names = {c.lower(): c for c in scored.columns}
        def pick_col(key_options):
            for k in key_options:
                if k in col_names:
                    return col_names[k]
            return None
        up_col = pick_col(['up_score', 's_up', 'sdir', 's_up_score', 's_up'])
        down_col = pick_col(['down_score', 's_down', 'sdir_down', 's_down_score', 's_down'])
        total_col = pick_col(['total_score', 's_total', 'stotal', 'score', 'total'])
        # fallback: if we can't find names, try to detect numeric columns by content
        if up_col is None or down_col is None or total_col is None:
            # find numeric columns and attempt to match by position or names containing 'up'/'down'
            numeric_cols = [c for c in scored.columns if pd.api.types.is_numeric_dtype(scored[c])]
            # name matching heuristic
            for c in scored.columns:
                cl = c.lower()
                if 'up' in cl and up_col is None:
                    up_col = c
                if 'down' in cl and down_col is None:
                    down_col = c
                if ('total' in cl or 'score' in cl) and total_col is None:
                    total_col = c
            # final fallback: first three numeric columns
            if (up_col is None or down_col is None or total_col is None) and len(numeric_cols) >= 3:
                up_col, down_col, total_col = numeric_cols[:3]
        # extract values (if still None, set to None)
        up_score = float(sample_row[up_col]) if up_col is not None else None
        down_score = float(sample_row[down_col]) if down_col is not None else None
        total_score = float(sample_row[total_col]) if total_col is not None else None
    else:
        # If scored is a scalar or other structure, attempt to convert
        # most robust approach is to convert to DataFrame first, but if not possible:
        raise ValueError("Unexpected return type from score(): expected DataFrame-like output.")
    
    # --- Permutation and empirical p-value ---
    # Use number of up/down genes actually present in data (so permutations are matched to effective sizes)
    n_up_used = len(up_present)
    n_down_used = len(down_present)
    permd = permutate(df, n_up=n_up_used, n_down=n_down_used, reps=perms, norm_method=norm_method)
    pvals_df = empiricalpval(permutations=permd, score=scored)
    # pvals_df often contains a column 'empirical p value' or similar; extract numeric value for first sample
    if isinstance(pvals_df, pd.DataFrame):
        # pick first numeric column
        numeric_cols = [c for c in pvals_df.columns if pd.api.types.is_numeric_dtype(pvals_df[c])]
        if len(numeric_cols) == 0:
            # try to find a column name containing 'p' or 'empir'
            numeric_cols = [c for c in pvals_df.columns if 'p' in c.lower() or 'empir' in c.lower()]
        if len(numeric_cols) == 0:
            empirical_p = None
        else:
            empirical_p = float(pvals_df.iloc[0][numeric_cols[0]])
    else:
        empirical_p = None
    
    # --- Build result dict ---
    result = {
        pathway_name: {
            "pathway_display_name": pathway_name,
            "gene_set_info": {
                "up_geneset_size": len(up),
                "down_geneset_size": len(down),
                "geneset_covered_in_sample": n_up_used + n_down_used
            },
            "scores": {
                "up_geneset_score": up_score,
                "down_geneset_score": down_score,
                "total_singscore": total_score
            },
            "statistics": {
                "p_value": empirical_p,
                "method": "permutation (empirical)",
                "permutations": perms
            }
        }
    }
    
    return result


def append_report_to_json(report: Dict, out_json_path: str,
                          overwrite: bool = True,
                          backup: bool = True):
    """
    Append or merge a `report` dict into a JSON file at out_json_path.

    Parameters
    ----------
    report : dict
        JSON-serializable dictionary containing one or more pathway entries
        (same format as your 'report' returned by singscore_pathway_report).
    out_json_path : str
        Path to the JSON file to update (will be created if missing).
    overwrite : bool
        If True, replace an existing pathway entry with the same key. If False,
        and the key exists, the function will create a new key by appending a suffix.
    backup : bool
        If True and the output file already exists, create a timestamped backup copy.
    """
    out_path = Path(out_json_path)
    # Load existing content if present
    if out_path.exists():
        try:
            with out_path.open("r", encoding="utf-8") as fh:
                existing = json.load(fh)
                if not isinstance(existing, dict):
                    raise ValueError("Existing JSON root is not a dict. Aborting.")
        except Exception as e:
            raise RuntimeError(f"Failed to read existing JSON file: {e}")

        # Optionally backup original file
        if backup:
            ts = datetime.now().strftime("%Y%m%d_%H%M%S")
            backup_path = out_path.with_name(out_path.stem + f"_backup_{ts}" + out_path.suffix)
            shutil.copy2(out_path, backup_path)
            print(f"Backup of existing JSON saved to: {backup_path}")
    else:
        existing = {}

    # Merge report into existing dictionary
    for pathway_key, pathway_val in report.items():
        if pathway_key in existing:
            if overwrite:
                existing[pathway_key] = pathway_val
                print(f"Overwrote existing entry for pathway: {pathway_key}")
            else:
                # Create unique key by appending timestamp (or a counter)
                ts = datetime.now().strftime("%Y%m%d_%H%M%S")
                new_key = f"{pathway_key}__dup__{ts}"
                existing[new_key] = pathway_val
                print(f"Pathway key exists. Added as new key: {new_key}")
        else:
            existing[pathway_key] = pathway_val
            print(f"Appended new pathway: {pathway_key}")

    # Write atomically to avoid partial writes (write to temp then move)
    tmp_fd, tmp_path = tempfile.mkstemp(dir=str(out_path.parent), prefix=".tmp_", suffix=".json")
    try:
        with open(tmp_fd, "w", encoding="utf-8") as tmpf:
            json.dump(existing, tmpf, indent=2, ensure_ascii=False)
            tmpf.flush()
        # Atomically replace
        Path(tmp_path).replace(out_path)
        print(f"Updated JSON written to: {out_path}")
    except Exception as e:
        # cleanup temp file on failure
        try:
            Path(tmp_path).unlink(missing_ok=True)
        except Exception:
            pass
        raise RuntimeError(f"Failed to write updated JSON file: {e}")

## Tamoxifen resistance

In [5]:
# -------------------------
# Example usage:
# -------------------------
report = singscore_pathway_report(
    "singscore_new_code/UK65_clean_gene_log_tpm.txt",
    "singscore_new_code/tamoxcifen/BECKER_TAMOXIFEN_RESISTANCE_UP.txt",
    "singscore_new_code/tamoxcifen/BECKER_TAMOXIFEN_RESISTANCE_DN.txt",
    "Tamoxifen_resistance",
    norm_method='theoretical',
    perms=10000
)
append_report_to_json(report, "singscore_new_code/results/pathway_enrichment_analysis_output_modified.json", overwrite=True, backup=True)

Backup of existing JSON saved to: singscore_new_code\results\pathway_enrichment_analysis_output_modified_backup_20251110_155535.json
Appended new pathway: Tamoxifen_resistance
Updated JSON written to: singscore_new_code\results\pathway_enrichment_analysis_output_modified.json

In [8]:
! pip install gseapy

Collecting gseapy
  Downloading gseapy-1.1.10-cp312-cp312-win_amd64.whl.metadata (12 kB)
Requirement already satisfied: numpy>=1.13.0 in e:\pysingscore_replicate\.venv\lib\site-packages (from gseapy) (2.3.4)
Requirement already satisfied: scipy in e:\pysingscore_replicate\.venv\lib\site-packages (from gseapy) (1.16.3)
Requirement already satisfied: pandas in e:\pysingscore_replicate\.venv\lib\site-packages (from gseapy) (2.3.3)
Requirement already satisfied: matplotlib>=2.2 in e:\pysingscore_replicate\.venv\lib\site-packages (from gseapy) (3.10.7)
Collecting requests (from gseapy)
  Using cached requests-2.32.5-py3-none-any.whl.metadata (4.9 kB)
Requirement already satisfied: contourpy>=1.0.1 in e:\pysingscore_replicate\.venv\lib\site-packages (from matplotlib>=2.2->gseapy) (1.3.3)
Requirement already satisfied: cycler>=0.10 in e:\pysingscore_replicate\.venv\lib\site-packages (from matplotlib>=2.2->gseapy) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in e:\pysingscore_replicate\.venv\lib\site-packages (from matplotlib>=2.2->gseapy) (4.60.1)
Requirement already satisfied: kiwisolver>=1.3.1 in e:\pysingscore_replicate\.venv\lib\site-packages (from matplotlib>=2.2->gseapy) (1.4.9)
Requirement already satisfied: packaging>=20.0 in e:\pysingscore_replicate\.venv\lib\site-packages (from matplotlib>=2.2->gseapy) (25.0)
Requirement already satisfied: pillow>=8 in e:\pysingscore_replicate\.venv\lib\site-packages (from matplotlib>=2.2->gseapy) (12.0.0)
Requirement already satisfied: pyparsing>=3 in e:\pysingscore_replicate\.venv\lib\site-packages (from matplotlib>=2.2->gseapy) (3.2.5)
Requirement already satisfied: python-dateutil>=2.7 in e:\pysingscore_replicate\.venv\lib\site-packages (from matplotlib>=2.2->gseapy) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in e:\pysingscore_replicate\.venv\lib\site-packages (from python-dateutil>=2.7->matplotlib>=2.2->gseapy) (1.17.0)
Requirement already satisfied: pytz>=2020.1 in e:\pysingscore_replicate\.venv\lib\site-packages (from pandas->gseapy) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in e:\pysingscore_replicate\.venv\lib\site-packages (from pandas->gseapy) (2025.2)
Collecting charset_normalizer<4,>=2 (from requests->gseapy)
  Using cached charset_normalizer-3.4.4-cp312-cp312-win_amd64.whl.metadata (38 kB)
Collecting idna<4,>=2.5 (from requests->gseapy)
  Using cached idna-3.11-py3-none-any.whl.metadata (8.4 kB)
Collecting urllib3<3,>=1.21.1 (from requests->gseapy)
  Using cached urllib3-2.5.0-py3-none-any.whl.metadata (6.5 kB)
Collecting certifi>=2017.4.17 (from requests->gseapy)
  Using cached certifi-2025.10.5-py3-none-any.whl.metadata (2.5 kB)
Downloading gseapy-1.1.10-cp312-cp312-win_amd64.whl (421 kB)
Using cached requests-2.32.5-py3-none-any.whl (64 kB)
Using cached charset_normalizer-3.4.4-cp312-cp312-win_amd64.whl (107 kB)
Using cached idna-3.11-py3-none-any.whl (71 kB)
Using cached urllib3-2.5.0-py3-none-any.whl (129 kB)
Using cached certifi-2025.10.5-py3-none-any.whl (163 kB)
Installing collected packages: urllib3, idna, charset_normalizer, certifi, requests, gseapy

   ------ --------------------------------- 1/6 [idna]
   ------------- -------------------------- 2/6 [charset_normalizer]
   --------------------------------- ------ 5/6 [gseapy]
   ---------------------------------------- 6/6 [gseapy]

Successfully installed certifi-2025.10.5 charset_normalizer-3.4.4 gseapy-1.1.10 idna-3.11 requests-2.32.5 urllib3-2.5.0

In [1]:
import gseapy as gp

In [2]:
hallmark  = gp.get_library_name(organism='Human')
hallmark

['ARCHS4_Cell-lines',
 'ARCHS4_IDG_Coexp',
 'ARCHS4_Kinases_Coexp',
 'ARCHS4_TFs_Coexp',
 'ARCHS4_Tissues',
 'Achilles_fitness_decrease',
 'Achilles_fitness_increase',
 'Aging_Perturbations_from_GEO_down',
 'Aging_Perturbations_from_GEO_up',
 'Allen_Brain_Atlas_10x_scRNA_2021',
 'Allen_Brain_Atlas_down',
 'Allen_Brain_Atlas_up',
 'Azimuth_2023',
 'Azimuth_Cell_Types_2021',
 'BioCarta_2013',
 'BioCarta_2015',
 'BioCarta_2016',
 'BioPlanet_2019',
 'BioPlex_2017',
 'CCLE_Proteomics_2020',
 'CM4AI_U2OS_Protein_Localization_Assemblies',
 'COMPARTMENTS_Curated_2025',
 'COMPARTMENTS_Experimental_2025',
 'CORUM',
 'COVID-19_Related_Gene_Sets',
 'COVID-19_Related_Gene_Sets_2021',
 'Cancer_Cell_Line_Encyclopedia',
 'CellMarker_2024',
 'CellMarker_Augmented_2021',
 'ChEA_2013',
 'ChEA_2015',
 'ChEA_2016',
 'ChEA_2022',
 'Chromosome_Location',
 'Chromosome_Location_hg19',
 'ClinVar_2019',
 'ClinVar_2025',
 'DGIdb_Drug_Targets_2024',
 'DSigDB',
 'Data_Acquisition_Method_Most_Popular_Genes',
 'DepMap_CRISPR_GeneDependency_CellLines_2023',
 'DepMap_WG_CRISPR_Screens_Broad_CellLines_2019',
 'DepMap_WG_CRISPR_Screens_Sanger_CellLines_2019',
 'Descartes_Cell_Types_and_Tissue_2021',
 'Diabetes_Perturbations_GEO_2022',
 'DisGeNET',
 'Disease_Perturbations_from_GEO_down',
 'Disease_Perturbations_from_GEO_up',
 'Disease_Signatures_from_GEO_down_2014',
 'Disease_Signatures_from_GEO_up_2014',
 'DrugMatrix',
 'Drug_Perturbations_from_GEO_2014',
 'Drug_Perturbations_from_GEO_down',
 'Drug_Perturbations_from_GEO_up',
 'ENCODE_Histone_Modifications_2013',
 'ENCODE_Histone_Modifications_2015',
 'ENCODE_TF_ChIP-seq_2014',
 'ENCODE_TF_ChIP-seq_2015',
 'ENCODE_and_ChEA_Consensus_TFs_from_ChIP-X',
 'ESCAPE',
 'Elsevier_Pathway_Collection',
 'Enrichr_Libraries_Most_Popular_Genes',
 'Enrichr_Submissions_TF-Gene_Coocurrence',
 'Enrichr_Users_Contributed_Lists_2020',
 'Epigenomics_Roadmap_HM_ChIP-seq',
 'FANTOM6_lncRNA_KD_DEGs',
 'GO_Biological_Process_2021',
 'GO_Biological_Process_2023',
 'GO_Biological_Process_2025',
 'GO_Cellular_Component_2021',
 'GO_Cellular_Component_2023',
 'GO_Cellular_Component_2025',
 'GO_Molecular_Function_2021',
 'GO_Molecular_Function_2023',
 'GO_Molecular_Function_2025',
 'GTEx_Aging_Signatures_2021',
 'GTEx_Tissue_Expression_Down',
 'GTEx_Tissue_Expression_Up',
 'GTEx_Tissues_V8_2023',
 'GWAS_Catalog_2019',
 'GWAS_Catalog_2023',
 'GWAS_Catalog_2025',
 'GeDiPNet_2023',
 'GeneSigDB',
 'Gene_Perturbations_from_GEO_down',
 'Gene_Perturbations_from_GEO_up',
 'Genes_Associated_with_NIH_Grants',
 'Genome_Browser_PWMs',
 'GlyGen_Glycosylated_Proteins_2022',
 'HDSigDB_Human_2021',
 'HDSigDB_Mouse_2021',
 'HMDB_Metabolites',
 'HMS_LINCS_KinomeScan',
 'HomoloGene',
 'HuBMAP_ASCT_plus_B_augmented_w_RNAseq_Coexpression',
 'HuBMAP_ASCTplusB_augmented_2022',
 'HumanCyc_2015',
 'HumanCyc_2016',
 'Human_Gene_Atlas',
 'Human_Phenotype_Ontology',
 'IDG_Drug_Targets_2022',
 'InterPro_Domains_2019',
 'JASPAR_PWM_Human_2025',
 'JASPAR_PWM_Mouse_2025',
 'Jensen_COMPARTMENTS',
 'Jensen_DISEASES',
 'Jensen_DISEASES_Curated_2025',
 'Jensen_DISEASES_Experimental_2025',
 'Jensen_TISSUES',
 'KEA_2013',
 'KEA_2015',
 'KEGG_2013',
 'KEGG_2015',
 'KEGG_2016',
 'KEGG_2019_Human',
 'KEGG_2019_Mouse',
 'KEGG_2021_Human',
 'KOMP2_Mouse_Phenotypes_2022',
 'Kinase_Perturbations_from_GEO_down',
 'Kinase_Perturbations_from_GEO_up',
 'L1000_Kinase_and_GPCR_Perturbations_down',
 'L1000_Kinase_and_GPCR_Perturbations_up',
 'LINCS_L1000_CRISPR_KO_Consensus_Sigs',
 'LINCS_L1000_Chem_Pert_Consensus_Sigs',
 'LINCS_L1000_Chem_Pert_down',
 'LINCS_L1000_Chem_Pert_up',
 'LINCS_L1000_Ligand_Perturbations_down',
 'LINCS_L1000_Ligand_Perturbations_up',
 'Ligand_Perturbations_from_GEO_down',
 'Ligand_Perturbations_from_GEO_up',
 'MAGMA_Drugs_and_Diseases',
 'MAGNET_2023',
 'MCF7_Perturbations_from_GEO_down',
 'MCF7_Perturbations_from_GEO_up',
 'MGI_Mammalian_Phenotype_Level_4_2021',
 'MGI_Mammalian_Phenotype_Level_4_2024',
 'MSigDB_Computational',
 'MSigDB_Hallmark_2020',
 'MSigDB_Oncogenic_Signatures',
 'Metabolomics_Workbench_Metabolites_2022',
 'Microbe_Perturbations_from_GEO_down',
 'Microbe_Perturbations_from_GEO_up',
 'MoTrPAC_2023',
 'Mouse_Gene_Atlas',
 'NCI-60_Cancer_Cell_Lines',
 'NCI-Nature_2016',
 'NIBR_DRUGseq_2025_down',
 'NIBR_DRUGseq_2025_up',
 'NURSA_Human_Endogenous_Complexome',
 'OMIM_Disease',
 'OMIM_Expanded',
 'Old_CMAP_down',
 'Old_CMAP_up',
 'Orphanet_Augmented_2021',
 'PFOCR_Pathways_2023',
 'PPI_Hub_Proteins',
 'PanglaoDB_Augmented_2021',
 'Panther_2015',
 'Panther_2016',
 'PerturbAtlas',
 'PerturbAtlas_MouseGenePerturbationSigs',
 'PerturbSeq_ReplogleK562',
 'PerturbSeq_ReplogleRPE1',
 'Pfam_Domains_2019',
 'Pfam_InterPro_Domains',
 'PheWeb_2019',
 'PhenGenI_Association_2021',
 'Phosphatase_Substrates_from_DEPOD',
 'ProteomicsDB_2020',
 'Proteomics_Drug_Atlas_2023',
 'RNA-Seq_Disease_Gene_and_Drug_Signatures_from_GEO',
 'Rare_Diseases_AutoRIF_ARCHS4_Predictions',
 'Rare_Diseases_AutoRIF_Gene_Lists',
 'Rare_Diseases_GeneRIF_ARCHS4_Predictions',
 'Rare_Diseases_GeneRIF_Gene_Lists',
 'Reactome_2022',
 'Reactome_Pathways_2024',
 'RummaGEO_DrugPerturbations_2025',
 'RummaGEO_GenePerturbations_2025',
 'Rummagene_kinases',
 'Rummagene_signatures',
 'Rummagene_transcription_factors',
 'SILAC_Phosphoproteomics',
 'Sciplex_Drug_Perturbation_Signatures_2025',
 'SubCell_BarCode',
 'SynGO_2022',
 'SynGO_2024',
 'SysMyo_Muscle_Gene_Sets',
 'TF-LOF_Expression_from_GEO',
 'TF_Perturbations_Followed_by_Expression',
 'TG_GATES_2020',
 'TISSUES_Curated_2025',
 'TISSUES_Experimental_2025',
 'TRANSFAC_and_JASPAR_PWMs',
 'TRRUST_Transcription_Factors_2019',
 'Table_Mining_of_CRISPR_Studies',
 'Tabula_Muris',
 'Tabula_Sapiens',
 'TargetScan_microRNA',
 'TargetScan_microRNA_2017',
 'The_Kinase_Library_2023',
 'The_Kinase_Library_2024',
 'Tissue_Protein_Expression_from_Human_Proteome_Map',
 'Tissue_Protein_Expression_from_ProteomicsDB',
 'Transcription_Factor_PPIs',
 'UK_Biobank_GWAS_v1',
 'Virus-Host_PPI_P-HIPSTer_2020',
 'VirusMINT',
 'Virus_Perturbations_from_GEO_down',
 'Virus_Perturbations_from_GEO_up',
 'WikiPathway_2021_Human',
 'WikiPathway_2023_Human',
 'WikiPathways_2013',
 'WikiPathways_2015',
 'WikiPathways_2016',
 'WikiPathways_2019_Human',
 'WikiPathways_2019_Mouse',
 'WikiPathways_2024_Human',
 'WikiPathways_2024_Mouse',
 'dbGaP',
 'huMAP',
 'lncHUB_lncRNA_Co-Expression',
 'miRTarBase_2017']

In [7]:
hallmark  = gp.get_library(organism='Human', name ='MSigDB_Hallmark_2020')
hallmark

{'TNF-alpha Signaling via NF-kB': ['MARCKS',
  'IL23A',
  'NINJ1',
  'TNFSF9',
  'SIK1',
  'ATF3',
  'SERPINE1',
  'MYC',
  'HES1',
  'CCN1',
  'CCNL1',
  'EGR1',
  'EGR2',
  'EGR3',
  'JAG1',
  'ABCA1',
  'GADD45B',
  'GADD45A',
  'KLF10',
  'PLK2',
  'EIF1',
  'EHD1',
  'FOSL2',
  'FOSL1',
  'GPR183',
  'PLPP3',
  'IFIT2',
  'ICAM1',
  'ZC3H12A',
  'IER2',
  'IL12B',
  'IER5',
  'JUNB',
  'IER3',
  'STAT5A',
  'DUSP5',
  'EDN1',
  'DUSP4',
  'JUN',
  'DUSP1',
  'DUSP2',
  'TSC22D1',
  'CCL20',
  'SPHK1',
  'LIF',
  'IL18',
  'TUBB2A',
  'RHOB',
  'VEGFA',
  'IL1A',
  'PTPRE',
  'TLR2',
  'IL1B',
  'BHLHE40',
  'CLCF1',
  'ID2',
  'REL',
  'FJX1',
  'SGK1',
  'BTG3',
  'BTG2',
  'BTG1',
  'SDC4',
  'LITAF',
  'AREG',
  'SOCS3',
  'PANX1',
  'RIPK2',
  'NFIL3',
  'SERPINB2',
  'GCH1',
  'IFNGR2',
  'G0S2',
  'FOS',
  'F3',
  'SERPINB8',
  'SPSB1',
  'FOSB',
  'PER1',
  'F2RL1',
  'HBEGF',
  'CD44',
  'TRIP10',
  'CDKN1A',
  'PTGER4',
  'PTGS2',
  'IFIH1',
  'NAMPT',
  'OLR1',
  'ICOSLG',
  'PHLDA1',
  'ZBTB10',
  'TAP1',
  'PNRC1',
  'CXCL10',
  'CXCL11',
  'IL6ST',
  'CD69',
  'SQSTM1',
  'RELA',
  'CD83',
  'CSF2',
  'CSF1',
  'CD80',
  'PPP1R15A',
  'TNC',
  'TNF',
  'RELB',
  'TANK',
  'ZFP36',
  'CCND1',
  'RNF19B',
  'CCRL2',
  'DENND5A',
  'MAP3K8',
  'PHLDA2',
  'LDLR',
  'SLC16A6',
  'SMAD3',
  'TGIF1',
  'MAP2K3',
  'DDX58',
  'INHBA',
  'TRAF1',
  'NFKB1',
  'NFKB2',
  'GEM',
  'MAFF',
  'NR4A3',
  'RCAN1',
  'EFNA1',
  'NR4A2',
  'MXD1',
  'BIRC2',
  'BIRC3',
  'YRDC',
  'IL7R',
  'PFKFB3',
  'IRS2',
  'SLC2A3',
  'PLAU',
  'SAT1',
  'SLC2A6',
  'ETS2',
  'NR4A1',
  'SNN',
  'PMEPA1',
  'TNFRSF9',
  'MSC',
  'TIPARP',
  'LAMB3',
  'GFPT2',
  'CFLAR',
  'TNIP1',
  'IRF1',
  'NFKBIA',
  'BMP2',
  'IL6',
  'TNIP2',
  'BCL6',
  'BCL3',
  'NFKBIE',
  'NFE2L2',
  'B4GALT1',
  'NFAT5',
  'BCL2A1',
  'TNFAIP8',
  'TNFAIP6',
  'TNFAIP3',
  'CXCL2',
  'CXCL1',
  'TNFAIP2',
  'CXCL3',
  'CXCL6',
  'FUT4',
  'DRAM1',
  'DNAJB4',
  'PDE4B',
  'PDLIM5',
  'MCL1',
  'KDM6B',
  'IL15RA',
  'PLAUR',
  'ATP2B1',
  'KLF4',
  'KLF2',
  'SOD2',
  'KLF9',
  'KLF6',
  'ACKR3',
  'PTX3',
  'B4GALT5',
  'TRIB1',
  'CEBPB',
  'CEBPD',
  'PLEK',
  'CCL5',
  'KYNU',
  'CCL4',
  'CCL2'],
 'Hypoxia': ['WSB1',
  'JMJD6',
  'XPNPEP1',
  'RRAGD',
  'PPP1R3C',
  'MT1E',
  'TES',
  'ATF3',
  'SERPINE1',
  'GLRX',
  'UGP2',
  'NOCT',
  'MXI1',
  'DPYSL4',
  'CCN5',
  'CCN2',
  'PPARGC1A',
  'CCN1',
  'DTNA',
  'SIAH2',
  'MIF',
  'PRKCA',
  'EXT1',
  'FOSL2',
  'SLC6A6',
  'SULT2B1',
  'BCAN',
  'LALBA',
  'CHST2',
  'SDC2',
  'HOXB9',
  'CHST3',
  'LXN',
  'NEDD4L',
  'PDGFB',
  'ENO1',
  'ENO2',
  'ENO3',
  'RBPJ',
  'MT2A',
  'PLAC8',
  'PRDX5',
  'HMOX1',
  'PDK1',
  'IER3',
  'PDK3',
  'EDN2',
  'ANXA2',
  'JUN',
  'DUSP1',
  'TPI1',
  'AMPD3',
  'CP',
  'VEGFA',
  'P4HA1',
  'P4HA2',
  'BHLHE40',
  'CCNG2',
  'PAM',
  'ALDOC',
  'ALDOB',
  'ALDOA',
  'GPI',
  'BTG1',
  'CITED2',
  'SDC3',
  'SDC4',
  'STC1',
  'ADM',
  'STC2',
  'VLDLR',
  'BRS3',
  'LDHC',
  'LDHA',
  'CSRP2',
  'IDS',
  'NFIL3',
  'PCK1',
  'TPD52',
  'PKLR',
  'PGAM2',
  'GAA',
  'FOS',
  'BGN',
  'F3',
  'TPST2',
  'ANGPTL4',
  'PLIN2',
  'INHA',
  'ERRFI1',
  'SRPX',
  'CDKN1B',
  'CDKN1C',
  'ERO1A',
  'HEXA',
  'CDKN1A',
  'NCAN',
  'GBE1',
  'GCNT2',
  'PYGM',
  'GYS1',
  'NDST2',
  'NDST1',
  'AKAP12',
  'STBD1',
  'CXCR4',
  'CA12',
  'HS3ST1',
  'MAP3K1',
  'TGFB3',
  'CAVIN1',
  'CAVIN3',
  'KLHL24',
  'PNRC1',
  'SAP30',
  'GCK',
  'ILVBL',
  'COL5A1',
  'TGFBI',
  'GAPDHS',
  'S100A4',
  'PKP1',
  'PPP1R15A',
  'HDLBP',
  'EGFR',
  'FOXO3',
  'NDRG1',
  'KIF5A',
  'ZFP36',
  'GPC1',
  'HAS1',
  'GPC4',
  'GPC3',
  'PPFIA4',
  'IGFBP1',
  'BNIP3L',
  'IGFBP3',
  'B3GALT6',
  'PGF',
  'MAFF',
  'EFNA1',
  'ISG20',
  'EFNA3',
  'LOX',
  'PFKFB3',
  'IRS2',
  'SLC2A1',
  'AK4',
  'SLC2A3',
  'SLC2A5',
  'ETS1',
  'RORA',
  'TGM2',
  'FAM162A',
  'PIM1',
  'ANKZF1',
  'TIPARP',
  'HSPA5',
  'CAV1',
  'GALK1',
  'GRHPR',
  'IL6',
  'ADORA2B',
  'MYH9',
  'BCL2',
  'FBP1',
  'TMEM45A',
  'SLC25A1',
  'TNFAIP3',
  'HK1',
  'HK2',
  'CASP6',
  'PGK1',
  'B4GALNT2',
  'SLC37A4',
  'TKTL1',
  'TPBG',
  'PLAUR',
  'DCN',
  'SELENBP1',
  'KLF7',
  'NAGK',
  'KLF6',
  'PFKL',
  'DDIT4',
  'DDIT3',
  'ACKR3',
  'KDELR3',
  'GAPDH',
  'PFKP',
  'KDM3A',
  'ZNF292',
  'NR3C1',
  'PHKG1',
  'VHL',
  'ATP7A',
  'PGM2',
  'SCARB1',
  'LARGE1',
  'PGM1'],
 'Cholesterol Homeostasis': ['STARD4',
  'GSTM2',
  'CHKA',
  'HMGCS1',
  'TNFRSF12A',
  'ANXA5',
  'ECH1',
  'GPX8',
  'PNRC1',
  'CPEB2',
  'SCD',
  'CD9',
  'ETHE1',
  'ALDOC',
  'DHCR7',
  'IDI1',
  'ATF3',
  'CLU',
  'HSD17B7',
  'ANTXR2',
  'CXCL16',
  'ACAT2',
  'ATXN2',
  'PMVK',
  'SC5D',
  'MAL2',
  'STX5',
  'NFIL3',
  'ACSS2',
  'FDFT1',
  'LDLR',
  'S100A11',
  'ABCA2',
  'FDPS',
  'NIBAN1',
  'SREBF2',
  'JAG1',
  'CYP51A1',
  'PCYT2',
  'ANXA13',
  'TP53INP1',
  'AVPR1A',
  'LSS',
  'PLAUR',
  'SQLE',
  'FABP5',
  'PLSCR1',
  'FASN',
  'LGMN',
  'PPARG',
  'MVD',
  'TRIB3',
  'ATF5',
  'ERRFI1',
  'MVK',
  'GLDC',
  'CTNNB1',
  'LPL',
  'SEMA3B',
  'ACTG1',
  'HMGCR',
  'TMEM97',
  'GNAI1',
  'TM7SF2',
  'ADH4',
  'CBS',
  'LGALS3',
  'EBP',
  'NSDHL',
  'ALCAM',
  'FBXO6',
  'GUSB',
  'FADS2',
  'PDK3'],
 'Mitotic Spindle': ['ACTN4',
  'PCGF5',
  'APC',
  'MARCKS',
  'NIN',
  'KIF20B',
  'EPB41',
  'STAU1',
  'CD2AP',
  'UXT',
  'PPP4R2',
  'CSNK1D',
  'RACGAP1',
  'CDC27',
  'PREX1',
  'STK38L',
  'ARFIP2',
  'PLK1',
  'BCR',
  'LATS1',
  'CCDC88A',
  'TPX2',
  'BIN1',
  'NET1',
  'SASS6',
  'EZR',
  'TRIO',
  'ITSN1',
  'NUMA1',
  'SMC4',
  'SMC3',
  'ABR',
  'EPB41L2',
  'CDK5RAP2',
  'CEP72',
  'KIFAP3',
  'CEP192',
  'SYNPO',
  'RHOF',
  'LRPPRC',
  'ANLN',
  'CENPE',
  'CENPF',
  'INCENP',
  'CENPJ',
  'PAFAH1B1',
  'ARHGEF2',
  'ARHGEF3',
  'RAPGEF6',
  'KPTN',
  'ARHGEF7',
  'RAPGEF5',
  'RABGAP1',
  'KIF11',
  'PIF1',
  'TOP2A',
  'KIF15',
  'NEDD9',
  'RASAL2',
  'BRCA2',
  'CNTRL',
  'KIF1B',
  'SPTBN1',
  'CEP57',
  'DLGAP5',
  'MAP1S',
  'SORBS2',
  'DYNLL2',
  'MYO9B',
  'FARP1',
  'RANBP9',
  'SEPTIN9',
  'CLIP2',
  'CLIP1',
  'CTTN',
  'TAOK2',
  'LLGL1',
  'ARF6',
  'DYNC1H1',
  'MAPRE1',
  'RAB3GAP1',
  'ALMS1',
  'TUBD1',
  'WASL',
  'AKAP13',
  'PCM1',
  'OPHN1',
  'NUSAP1',
  'RICTOR',
  'SPTAN1',
  'GSN',
  'RALBP1',
  'ARHGAP29',
  'TSC1',
  'ARHGAP27',
  'MID1',
  'TUBA4A',
  'ABI1',
  'KIF4A',
  'TUBGCP6',
  'ARL8A',
  'TUBGCP5',
  'CNTROB',
  'ROCK1',
  'GEMIN4',
  'AURKA',
  'KATNB1',
  'FGD4',
  'BCL2L11',
  'FGD6',
  'KIF5B',
  'CEP250',
  'FLNA',
  'CLASP1',
  'FLNB',
  'KNTC1',
  'MYH10',
  'PCNT',
  'ARHGEF12',
  'ARHGEF11',
  'KIF22',
  'TBCD',
  'KIF23',
  'CKAP5',
  'NDC80',
  'SSH2',
  'DLG1',
  'ARHGAP10',
  'CDC42EP4',
  'BIRC5',
  'CDC42EP2',
  'FSCN1',
  'MAP3K11',
  'CDC42EP1',
  'KIF2C',
  'VCL',
  'DOCK4',
  'NOTCH2',
  'PXN',
  'TUBGCP2',
  'TUBGCP3',
  'ARHGAP4',
  'ARHGAP5',
  'CCNB2',
  'KIF3C',
  'KIF3B',
  'NEK2',
  'ABL1',
  'MARK4',
  'SAC3D1',
  'SUN2',
  'ARFGEF1',
  'RFC1',
  'ARAP3',
  'SHROOM1',
  'SHROOM2',
  'CDC42BPA',
  'SMC1A',
  'RASA1',
  'HOOK3',
  'ESPL1',
  'RASA2',
  'MYH9',
  'CDK1',
  'NF1',
  'ATG4B',
  'DOCK2',
  'BCAR1',
  'SOS1',
  'YWHAE',
  'LMNB1',
  'KLC1',
  'RHOT2',
  'CAPZB',
  'ECT2',
  'WASF1',
  'WASF2',
  'PDLIM5',
  'PLEKHG2',
  'DST',
  'CEP131',
  'MID1IP1',
  'KATNA1',
  'PRC1',
  'TIAM1',
  'CDC42',
  'MYO1E',
  'PALLD',
  'ALS2',
  'HDAC6',
  'TTK',
  'PKD2',
  'ARHGDIA',
  'FBXO5',
  'TLK1',
  'BUB1',
  'CYTH2',
  'NCK1',
  'NCK2'],
 'Wnt-beta Catenin Signaling': ['FZD1',
  'JAG1',
  'JAG2',
  'FZD8',
  'WNT5B',
  'AXIN2',
  'AXIN1',
  'PTCH1',
  'CSNK1E',
  'DKK1',
  'DKK4',
  'ADAM17',
  'KAT2A',
  'NCOR2',
  'TCF7',
  'PPARD',
  'TP53',
  'NUMB',
  'HDAC5',
  'LEF1',
  'NOTCH4',
  'NOTCH1',
  'HDAC11',
  'HDAC2',
  'CTNNB1',
  'MAML1',
  'CUL1',
  'PSEN2',
  'DLL1',
  'GNAI1',
  'NKD1',
  'RBPJ',
  'WNT6',
  'FRAT1',
  'CCND2',
  'HEY2',
  'HEY1',
  'DVL2',
  'MYC',
  'WNT1',
  'NCSTN',
  'SKP2'],
 'TGF-beta Signaling': ['TGFB1',
  'ACVR1',
  'RHOA',
  'SMURF2',
  'SMURF1',
  'HIPK2',
  'TGFBR1',
  'PPP1CA',
  'CDK9',
  'SKI',
  'RAB31',
  'APC',
  'BMP2',
  'NCOR2',
  'ID1',
  'ID3',
  'ID2',
  'BMPR1A',
  'BCAR3',
  'BMPR2',
  'SERPINE1',
  'UBE2D3',
  'PPP1R15A',
  'ARID4B',
  'CDH1',
  'MAP3K7',
  'SKIL',
  'SPTBN1',
  'SMAD3',
  'WWTR1',
  'TGIF1',
  'LEFTY2',
  'NOG',
  'IFNGR2',
  'SMAD1',
  'KLF10',
  'SMAD7',
  'SMAD6',
  'PPM1A',
  'FKBP1A',
  'TJP1',
  'XIAP',
  'ENG',
  'TRIM33',
  'CDKN1C',
  'HDAC1',
  'FURIN',
  'CTNNB1',
  'SLC20A1',
  'THBS1',
  'LTBP2',
  'FNTA',
  'PMEPA1',
  'JUNB'],
 'IL-6/JAK/STAT3 Signaling': ['PTPN1',
  'TGFB1',
  'CCR1',
  'PTPN2',
  'IL4R',
  'JUN',
  'IL1R1',
  'IL1R2',
  'ITGA4',
  'TNFRSF12A',
  'IL10RB',
  'PLA2G2A',
  'DNTT',
  'PTPN11',
  'TYK2',
  'OSMR',
  'TNFRSF1A',
  'TNFRSF1B',
  'CXCL10',
  'HAX1',
  'TLR2',
  'CXCL11',
  'IL1B',
  'IRF1',
  'TNFRSF21',
  'IL7',
  'CXCL13',
  'IL6',
  'CD9',
  'FAS',
  'IL3RA',
  'IL9R',
  'IRF9',
  'IL6ST',
  'PF4',
  'STAM2',
  'CRLF2',
  'IL18R1',
  'CNTFR',
  'ACVRL1',
  'CSF3R',
  'CXCL9',
  'CSF2',
  'CSF1',
  'EBI3',
  'PIK3R5',
  'TNF',
  'CXCL1',
  'IL2RG',
  'CXCL3',
  'SOCS3',
  'SOCS1',
  'CD38',
  'CD36',
  'IL12RB1',
  'MAP3K8',
  'IL17RA',
  'IL15RA',
  'IFNGR1',
  'STAT1',
  'IFNGR2',
  'STAT2',
  'STAT3',
  'INHBE',
  'IL17RB',
  'MYD88',
  'LTBR',
  'IL2RA',
  'LTB',
  'GRB2',
  'IFNAR1',
  'CD44',
  'REG1A',
  'ITGB3',
  'PDGFC',
  'CSF2RA',
  'ACVR1B',
  'CBL',
  'CSF2RB',
  'CCL7',
  'HMOX1',
  'LEPR',
  'PIM1',
  'BAK1',
  'A2M',
  'CD14',
  'IL13RA1'],
 'DNA Repair': ['DUT',
  'BRF2',
  'LIG1',
  'PDE6G',
  'ALYREF',
  'UPF3B',
  'GTF2F1',
  'RBX1',
  'TARBP2',
  'POLR3C',
  'POLE4',
  'SRSF6',
  'EIF1B',
  'CDA',
  'TP53',
  'VPS28',
  'PCNA',
  'MPG',
  'RNMT',
  'RALA',
  'GTF2B',
  'TYMS',
  'ADCY6',
  'PNP',
  'TAF1C',
  'ZNF707',
  'CLP1',
  'NT5C',
  'RAE1',
  'STX3',
  'SMAD5',
  'SURF1',
  'VPS37D',
  'VPS37B',
  'SUPT5H',
  'SDCBP',
  'BCAM',
  'NT5C3A',
  'ITPA',
  'HPRT1',
  'CCNO',
  'TSG101',
  'POM121',
  'COX17',
  'ARL6IP1',
  'AK1',
  'CSTF3',
  'AK3',
  'XPC',
  'AAAS',
  'DGUOK',
  'MPC2',
  'NELFE',
  'NELFB',
  'SAC3D1',
  'GSDME',
  'RFC4',
  'RFC5',
  'NCBP2',
  'POLR3GL',
  'RFC2',
  'GPX4',
  'RFC3',
  'NME3',
  'EDF1',
  'NME4',
  'ZWINT',
  'NME1',
  'POLA1',
  'POLA2',
  'AGO4',
  'NFX1',
  'RRM2B',
  'ADA',
  'UMPS',
  'GTF2A2',
  'GTF3C5',
  'CETN2',
  'ELL',
  'NPR2',
  'SUPT4H1',
  'MRPL40',
  'ZNRD1',
  'SNAPC4',
  'SNAPC5',
  'NELFCD',
  'PDE4B',
  'DGCR8',
  'TMED2',
  'TK2',
  'BCAP31',
  'SF3A3',
  'TAF13',
  'ADRM1',
  'TAF12',
  'BOLA2',
  'RPA2',
  'GTF2H1',
  'RPA3',
  'TAF10',
  'SSRP1',
  'GTF2H3',
  'GTF2H5',
  'APRT',
  'DDB2',
  'DDB1',
  'ERCC1',
  'NUDT21',
  'RAD51',
  'NUDT9',
  'RAD52',
  'ERCC4',
  'ERCC5',
  'IMPDH2',
  'DAD1',
  'ERCC2',
  'POLR1C',
  'ERCC3',
  'POLR1D',
  'CMPK2',
  'ERCC8',
  'HCLS1',
  'TAF9',
  'TAF6',
  'FEN1',
  'CANT1',
  'GMPR2',
  'USP11',
  'DCTN4',
  'PRIM1',
  'POLD4',
  'POLB',
  'GUK1',
  'POLR2A',
  'POLD1',
  'POLR2C',
  'POLR2D',
  'SEC61A1',
  'POLD3',
  'POLR2E',
  'ELOA',
  'POLR2F',
  'POLR2G',
  'POLR2H',
  'POLL',
  'POLR2I',
  'POLR2J',
  'POLR2K',
  'POLH',
  'REV3L'],
 'G2-M Checkpoint': ['H2AZ2',
  'CASP8AP2',
  'EGF',
  'H2AZ1',
  'KNL1',
  'SLC12A2',
  'HUS1',
  'CDC20',
  'MAPK14',
  'PML',
  'DDX39A',
  'MARCKS',
  'NUP98',
  'HNRNPD',
  'KIF20B',
  'CCNF',
  'HNRNPU',
  'NOLC1',
  'EWSR1',
  'CHEK1',
  'RACGAP1',
  'CDC27',
  'RAD54L',
  'SNRPD1',
  'E2F1',
  'MYC',
  'E2F2',
  'E2F3',
  'E2F4',
  'PLK4',
  'PLK1',
  'SQLE',
  'STAG1',
  'TPX2',
  'UCK2',
  'EZH2',
  'ATF5',
  'JPT1',
  'NUMA1',
  'HIF1A',
  'SMC4',
  'SMC2',
  'GSPT1',
  'TMPO',
  'MT2A',
  'SYNCRIP',
  'STMN1',
  'MYBL2',
  'BARD1',
  'SS18',
  'UPF1',
  'CDC7',
  'CDC6',
  'CENPE',
  'SLC7A5',
  'CENPF',
  'INCENP',
  'MTF2',
  'PAFAH1B1',
  'CDKN3',
  'DTYMK',
  'KIF11',
  'YTHDC1',
  'SUV39H1',
  'TOP2A',
  'KIF15',
  'RASAL2',
  'BRCA2',
  'CTCF',
  'SLC7A1',
  'HOXC10',
  'PBK',
  'MAP3K20',
  'CDKN2C',
  'PRMT5',
  'RPA2',
  'TRAIP',
  'CKS2',
  'TACC3',
  'H2AX',
  'CDKN1B',
  'PRIM2',
  'MKI67',
  'CENPA',
  'XPO1',
  'WRN',
  'DMD',
  'NUSAP1',
  'SRSF10',
  'GINS2',
  'TGFB1',
  'TLE3',
  'UBE2C',
  'CDC25A',
  'PRPF4B',
  'LIG3',
  'ILF3',
  'CDC25B',
  'SAP30',
  'DKC1',
  'UBE2S',
  'KIF4A',
  'PTTG3P',
  'MAD2L1',
  'CCNT1',
  'ODC1',
  'SRSF1',
  'SRSF2',
  'ARID4A',
  'AURKA',
  'EFNA5',
  'HIRA',
  'AURKB',
  'CCND1',
  'NSD2',
  'PURA',
  'KIF5B',
  'PTTG1',
  'KMT5A',
  'HMGN2',
  'KPNA2',
  'SMAD3',
  'SLC38A1',
  'KIF22',
  'ODF2',
  'STIL',
  'FANCC',
  'KIF23',
  'NASP',
  'FOXN3',
  'NDC80',
  'CCNA2',
  'TFDP1',
  'NCL',
  'BIRC5',
  'TROAP',
  'KIF2C',
  'MNAT1',
  'NOTCH2',
  'CUL5',
  'CUL3',
  'CUL1',
  'PDS5B',
  'CHAF1A',
  'CCNB2',
  'G3BP1',
  'CHMP1A',
  'NEK2',
  'ABL1',
  'DR1',
  'HSPA8',
  'CBX1',
  'RAD23B',
  'HMGA1',
  'SMC1A',
  'CUL4A',
  'NUP50',
  'POLA2',
  'MEIS2',
  'RBL1',
  'MEIS1',
  'ESPL1',
  'SFPQ',
  'CDK4',
  'H2BC12',
  'BCL3',
  'CDK1',
  'MCM5',
  'MCM6',
  'TOP1',
  'MCM2',
  'MCM3',
  'AMD1',
  'CKS1B',
  'HMGB3',
  'HMMR',
  'LMNB1',
  'TENT4A',
  'ORC6',
  'ORC5',
  'RAD21',
  'LBR',
  'TNPO2',
  'RBM14',
  'SMARCC1',
  'ATRX',
  'POLQ',
  'KATNA1',
  'PRC1',
  'KPNB1',
  'DBF4',
  'TTK',
  'RPS6KA5',
  'CDC45',
  'POLE',
  'EXO1',
  'TRA2B',
  'FBXO5',
  'BUB3',
  'BUB1'],
 'Apoptosis': ['GSN',
  'PDGFRB',
  'BIK',
  'LUM',
  'TGFB2',
  'GSR',
  'TAP1',
  'CDC25B',
  'EREG',
  'MADD',
  'CD2',
  'FEZ1',
  'FAS',
  'CTH',
  'BAX',
  'PDCD4',
  'CD69',
  'SQSTM1',
  'APP',
  'DAP3',
  'LEF1',
  'ATF3',
  'RELA',
  'IFITM3',
  'ROCK1',
  'SATB1',
  'RETSAT',
  'CLU',
  'TNF',
  'LMNA',
  'BCL2L11',
  'PAK1',
  'CCND2',
  'BCL2L10',
  'CCND1',
  'SC5D',
  'CREBBP',
  'IGF2R',
  'EGR3',
  'F2R',
  'IGFBP6',
  'GADD45B',
  'BNIP3L',
  'GADD45A',
  'HGF',
  'AVPR1A',
  'H1-0',
  'SMAD7',
  'PTK2',
  'ISG20',
  'CCNA1',
  'BCL2L1',
  'PPT1',
  'BIRC3',
  'BCL2L2',
  'BCL10',
  'PRF1',
  'PSEN1',
  'ENO2',
  'FASLG',
  'PLAT',
  'PSEN2',
  'SAT1',
  'PPP3R1',
  'LGALS3',
  'EBP',
  'ANKH',
  'FDXR',
  'HMOX1',
  'PMAIP1',
  'BMF',
  'TNFSF10',
  'CD14',
  'IER3',
  'DNM1L',
  'GPX1',
  'ANXA1',
  'GPX3',
  'JUN',
  'GSTM1',
  'GPX4',
  'MMP2',
  'TNFRSF12A',
  'CAV1',
  'CFLAR',
  'EMP1',
  'PPP2R5B',
  'IL18',
  'RHOB',
  'TGFBR3',
  'IL1A',
  'DNAJC3',
  'IL1B',
  'IRF1',
  'CYLD',
  'BMP2',
  'DAP',
  'IL6',
  'KRT18',
  'DPYD',
  'CDK2',
  'ETF1',
  'RARA',
  'GUCY2D',
  'BTG3',
  'BTG2',
  'DIABLO',
  'TOP2A',
  'PEA15',
  'BRCA1',
  'NEDD9',
  'HMGB2',
  'HSPB1',
  'CASP8',
  'CASP9',
  'RHOT2',
  'CASP6',
  'CASP7',
  'CASP4',
  'ERBB2',
  'ERBB3',
  'CASP2',
  'TIMP3',
  'CASP3',
  'CD38',
  'TIMP1',
  'CASP1',
  'TIMP2',
  'MCL1',
  'BCAP31',
  'DFFA',
  'IFNGR1',
  'MGMT',
  'GCH1',
  'BGN',
  'F2',
  'SOD1',
  'DCN',
  'SOD2',
  'DNAJA1',
  'WEE1',
  'XIAP',
  'TXNIP',
  'DDIT3',
  'VDAC2',
  'PLCB2',
  'CD44',
  'CDKN1B',
  'RNASEL',
  'CDKN1A',
  'PLPPR4',
  'CTNNB1',
  'SLC20A1',
  'ADD1',
  'GNA15',
  'AIFM3',
  'IFNB1',
  'TSPO',
  'NEFH',
  'SPTAN1',
  'BID'],
 'Notch Signaling': ['FZD1',
  'PSENEN',
  'JAG1',
  'TCF7L2',
  'FBXW11',
  'FZD5',
  'WNT5A',
  'FZD7',
  'PRKCA',
  'HEYL',
  'RBX1',
  'SAP30',
  'KAT2A',
  'PPARD',
  'NOTCH3',
  'NOTCH1',
  'NOTCH2',
  'MAML2',
  'DTX1',
  'CUL1',
  'DTX2',
  'DTX4',
  'PSEN2',
  'DLL1',
  'APH1A',
  'LFNG',
  'ARRB1',
  'CCND1',
  'ST3GAL6',
  'HES1',
  'WNT2',
  'SKP1'],
 'Adipogenesis': ['ECH1',
  'CIDEA',
  'PEX14',
  'LEP',
  'UQCRC1',
  'SPARCL1',
  'PREB',
  'SUCLG1',
  'ITIH5',
  'RETSAT',
  'UQCR10',
  'GHITM',
  'RETN',
  'ARAF',
  'UQCR11',
  'TOB1',
  'ADCY6',
  'SLC5A6',
  'SNCG',
  'STOM',
  'COX8A',
  'FZD4',
  'ABCA1',
  'OMD',
  'GADD45A',
  'TALDO1',
  'RMDN3',
  'CMBL',
  'POR',
  'UCK1',
  'SSPN',
  'CD302',
  'PEMT',
  'NMT1',
  'ITSN1',
  'BAZ2A',
  'MGST3',
  'MRPL15',
  'MYLK',
  'C3',
  'PRDX3',
  'SULT1A1',
  'LIPE',
  'GRPEL1',
  'SCP2',
  'APOE',
  'SLC19A1',
  'DECR1',
  'STAT5A',
  'CS',
  'VEGFB',
  'CCNG2',
  'MRAP',
  'ALDOA',
  'MGLL',
  'COX7B',
  'MTARC2',
  'ADIPOR2',
  'ECHS1',
  'NKIRAS1',
  'CD36',
  'ADIG',
  'ADIPOQ',
  'MAP4K3',
  'CDKN2C',
  'IFNGR1',
  'MDH2',
  'DGAT1',
  'ELOVL6',
  'ELMOD3',
  'MCCC1',
  'SQOR',
  'SORBS1',
  'DHRS7',
  'COL4A1',
  'FABP4',
  'ESYT1',
  'GPAM',
  'NDUFAB1',
  'LPCAT3',
  'ANGPTL4',
  'ATP5PO',
  'PPARG',
  'DLD',
  'PLIN2',
  'TKT',
  'CMPK1',
  'ORM1',
  'SLC66A3',
  'ATL2',
  'PTGER3',
  'GBE1',
  'SAMM50',
  'ACADM',
  'ACADL',
  'AIFM1',
  'ENPP2',
  'DLAT',
  'GPAT4',
  'RIOK3',
  'ACADS',
  'CAVIN1',
  'PHYH',
  'PTCD3',
  'CAVIN2',
  'APLP2',
  'ATP1B3',
  'LIFR',
  'SDHB',
  'FAH',
  'SDHC',
  'RAB34',
  'UQCRQ',
  'GPD2',
  'PDCD4',
  'DHCR7',
  'CRAT',
  'PPP1R15B',
  'PHLDB1',
  'SLC27A1',
  'UCP2',
  'SLC1A5',
  'TANK',
  'COX6A1',
  'BCL2L13',
  'ESRRA',
  'IDH1',
  'NABP1',
  'EPHX2',
  'CHCHD10',
  'DNAJC15',
  'ACLY',
  'QDPR',
  'REEP6',
  'REEP5',
  'PFKFB3',
  'CD151',
  'LPL',
  'AK2',
  'UBC',
  'G3BP2',
  'PIM3',
  'ACAA2',
  'CYC1',
  'HADH',
  'BCKDHA',
  'GPX3',
  'JAGN1',
  'ANGPT1',
  'GPX4',
  'COQ9',
  'COQ5',
  'COQ3',
  'BCL6',
  'ACOX1',
  'NDUFS3',
  'ACO2',
  'ITGA7',
  'ARL4A',
  'RTN3',
  'SLC25A1',
  'YWHAG',
  'NDUFB7',
  'ABCB8',
  'HSPB8',
  'DHRS7B',
  'AGPAT3',
  'DRAM2',
  'DBT',
  'CPT2',
  'ME1',
  'DNAJB9',
  'RREB1',
  'HIBCH',
  'IDH3G',
  'MIGA2',
  'CHUK',
  'NDUFA5',
  'CYP4B1',
  'IMMT',
  'SOD1',
  'PPM1B',
  'PFKL',
  'CAT',
  'TST',
  'SLC25A10',
  'MTCH2',
  'RNF11',
  'SOWAHC',
  'COL15A1',
  'LAMA4',
  'ETFB',
  'GPHN',
  'LTC4S',
  'DDT',
  'ALDH2',
  'UBQLN1',
  'IDH3A',
  'SCARB1',
  'PGM1'],
 'Estrogen Response Early': ['TTC39A',
  'AMFR',
  'KRT8',
  'MED13L',
  'GLA',
  'NBL1',
  'RETREG1',
  'AKAP1',
  'ADCY1',
  'PEX11A',
  'ADCY9',
  'AQP3',
  'ABAT',
  'TOB1',
  'MUC1',
  'MYB',
  'MYC',
  'CCN5',
  'HES1',
  'FDFT1',
  'ABCA3',
  'EGR3',
  'XBP1',
  'BCL11B',
  'KLF10',
  'SIAH2',
  'PLAAT3',
  'CBFA2T3',
  'OVOL2',
  'PDZK1',
  'IL17RB',
  'AR',
  'SULT2B1',
  'FASN',
  'UNC119',
  'PTGES',
  'SLC22A5',
  'RAPGEFL1',
  'TSKU',
  'SOX3',
  'GJA1',
  'INPP5F',
  'SFN',
  'MYBL1',
  'SLC19A2',
  'GREB1',
  'ITPK1',
  'MYOF',
  'GAB2',
  'KRT13',
  'FAM102A',
  'KLK10',
  'RHOD',
  'SLC7A5',
  'KRT19',
  'NCOR2',
  'TUBB2B',
  'KRT18',
  'MAPT',
  'MPPED2',
  'BHLHE40',
  'KRT15',
  'TFF3',
  'RARA',
  'TFF1',
  'RET',
  'FOXC1',
  'ABHD2',
  'ENDOD1',
  'STC2',
  'TMPRSS3',
  'AREG',
  'SLC7A2',
  'TMEM164',
  'UGCG',
  'SEC14L2',
  'CLIC3',
  'ELOVL2',
  'SVIL',
  'ELOVL5',
  'FOS',
  'SNX24',
  'GFRA1',
  'DHRS2',
  'DHRS3',
  'FARP1',
  'MYBBP1A',
  'DLC1',
  'CD44',
  'TJP3',
  'LAD1',
  'PRSS23',
  'OLFML3',
  'TBC1D30',
  'ANXA9',
  'RRP12',
  'DEPTOR',
  'JAK2',
  'CA12',
  'TFAP2C',
  'MREG',
  'SLC16A1',
  'NPY1R',
  'KAZN',
  'OLFM1',
  'CXCL12',
  'RAB31',
  'PPIF',
  'IL6ST',
  'DHCR7',
  'FKBP5',
  'FKBP4',
  'FRK',
  'SLC27A2',
  'CELSR1',
  'SLC1A1',
  'SCNN1A',
  'HR',
  'SLC1A4',
  'ASB13',
  'CELSR2',
  'PAPSS2',
  'ABLIM1',
  'CCND1',
  'FLNB',
  'SH3BP5',
  'SLC39A6',
  'RBBP8',
  'MICB',
  'OPN3',
  'TGIF2',
  'WFS1',
  'CISH',
  'IGFBP4',
  'INHBB',
  'SLC9A3R1',
  'MED24',
  'REEP1',
  'PGR',
  'BLVRB',
  'FCMR',
  'SLC26A2',
  'WWC1',
  'MINDY1',
  'SLC2A1',
  'ARL3',
  'ISG20L2',
  'IGF1R',
  'RHOBTB3',
  'TGM2',
  'CALCR',
  'RASGRP1',
  'PODXL',
  'BAG1',
  'ALDH3B1',
  'PMAIP1',
  'SYBU',
  'SLC37A1',
  'KDM4B',
  'TIPARP',
  'NAV2',
  'ELF1',
  'ELF3',
  'CHPT1',
  'ESRP2',
  'BCL2',
  'KCNK5',
  'B4GALT1',
  'MAST4',
  'HSPB8',
  'AFF1',
  'SYNGR1',
  'CALB2',
  'CYP26B1',
  'PDLIM3',
  'NRIP1',
  'P2RY2',
  'ZNF185',
  'DYNLT3',
  'TPBG',
  'KCNK15',
  'KLF4',
  'TIAM1',
  'TPD52L1',
  'CLDN7',
  'MLPH',
  'SYT12',
  'RAB17',
  'SLC24A3',
  'CANT1',
  'NXT1',
  'SEMA3B',
  'FHL2',
  'ADD3',
  'NADSYN1',
  'THSD4',
  'RPS6KA2',
  'LRIG1',
  'MSMB',
  'SCARB1'],
 'Estrogen Response Late': ['UNC13B',
  'HOMER2',
  'CACNA2D2',
  'AMFR',

## Getting the genesets for the selected pathways collections

In [ ]:
import gseapy as gp
import pandas as pd

libraries = [
    'MSigDB_Hallmark_2020',
    'KEGG_2021_Human',
    'Reactome_Pathways_2024',
    'GO_Biological_Process_2025',
    'GO_Molecular_Function_2025'
]

combined_gene_sets = {}

# Download and merge all gene sets
for lib_name in libraries:
    print(f"Downloading library: {lib_name}")
    gs = gp.get_library(name=lib_name)
    combined_gene_sets.update(gs)

# Optional: convert to DataFrame
gene_set_df = pd.DataFrame([
    {'set_name': k, 'genes': ','.join(v)} for k, v in combined_gene_sets.items()
])

print(f"Total gene sets combined: {len(combined_gene_sets)}")
gene_set_df

Downloading library: MSigDB_Hallmark_2020
Downloading library: KEGG_2021_Human
Downloading library: Reactome_Pathways_2024
Downloading library: GO_Biological_Process_2025
Total gene sets combined: 7802

,set_name,genes
0,TNF-alpha Signaling via NF-kB,"MARCKS,IL23A,NINJ1,TNFSF9,SIK1,ATF3,SERPINE1,M..."
1,Hypoxia,"WSB1,JMJD6,XPNPEP1,RRAGD,PPP1R3C,MT1E,TES,ATF3..."
2,Cholesterol Homeostasis,"STARD4,GSTM2,CHKA,HMGCS1,TNFRSF12A,ANXA5,ECH1,..."
3,Mitotic Spindle,"ACTN4,PCGF5,APC,MARCKS,NIN,KIF20B,EPB41,STAU1,..."
4,Wnt-beta Catenin Signaling,"FZD1,JAG1,JAG2,FZD8,WNT5B,AXIN2,AXIN1,PTCH1,CS..."
...,...,...
7797,Zinc Ion Import Across Plasma Membrane (GO:007...,"SLC30A8,SLC39A10,SLC39A12,SLC39A6,SLC39A14,SLC..."
7798,Zinc Ion Import Into Organelle (GO:0062111),"SLC30A8,SLC30A7,SLC30A4,SLC30A3,SLC30A6,SLC30A..."
7799,Zinc Ion Transmembrane Transport (GO:0071577),"SLC30A8,SLC39A1,SLC30A4,SLC30A3,SLC30A5,SLC39A..."
7800,Zinc Ion Transport (GO:0006829),"SLC30A8,SLC39A1,SLC30A9,SLC30A4,SLC30A3,SLC30A..."
7801,Zymogen Activation (GO:0031638),"FGB,FGG,F12,ZNF160,F9,MMP14,DLC1,KLKB1,C1R,KLK..."

## Getting the gene targets for the drugs

In [6]:
# Load the IDG Drug Target 2022 library
idg = gp.get_library(name="IDG_Drug_Targets_2022")

# Inspect
print(len(idg), "drug-target sets loaded")

# Example: see which genes Palbociclib targets
# print(idg.get("Palbociclib"))
idg

888 drug-target sets loaded

{'Levobupivacaine': ['KCND3',
  'PTGER1',
  'CYP2D6',
  'KCNA5',
  'SCN4A',
  'SCN1A',
  'HTR3A',
  'KCNH2'],
 '(S)-nitrendipine': ['CACNA1C', 'CACNA1S', 'CACNA1D', 'KCNN4', 'CACNA1F'],
 'Acamprosate': ['GRIN3A',
  'GABRB3',
  'GABRA1',
  'GRIN2B',
  'GRIN2A',
  'GRIN3B',
  'GRIN2D',
  'GRIN2C',
  'GRIN1',
  'GABRG2'],
 'Acarbose': ['MGAM', 'AMY2A', 'AMY1A', 'SI', 'GAA'],
 'Paracetamol': ['CA13',
  'CA12',
  'NR1I3',
  'ALOX15',
  'ALOX5AP',
  'TRPV1',
  'PTGS2',
  'CA2',
  'CA1',
  'CA4',
  'MB',
  'CA3',
  'CNR1',
  'CA7',
  'CA9',
  'CA14'],
 'Acetazolamide': ['CA13',
  'CA12',
  'CA11',
  'AQP1',
  'CA2',
  'CA1',
  'CA4',
  'CA3',
  'CA5B',
  'CA5A',
  'CA6',
  'CA7',
  'CA9',
  'CA14'],
 'Acetoxolone': ['CES1', 'HSD11B2', 'HSD17B1', 'HSD17B2', 'CES2', 'HSD11B1'],
 'Acetylcholine': ['CHRM3',
  'CHRNA2',
  'CHRND',
  'CHRM4',
  'CHRNB2',
  'CHRM1',
  'CHRNA4',
  'CHRM2',
  'CHRNA3',
  'CHRNB4',
  'CHRM5',
  'CHRNA7'],
 'Acetylcysteine': ['GSS', 'CYCS', 'SLC7A11', 'VEGFA', 'SOD2'],
 'Acetyldigitoxin': ['FXYD2',
  'ATP1A4',
  'ATP1A3',
  'ATP1A2',
  'ATP1B3',
  'ATP1A1',
  'ATP1B2',
  'ATP1B1'],
 'Acetylsalicylic Acid': ['NAPRT', 'ASIC3', 'GGT1', 'PTGS1', 'PTGS2'],
 'Aclarubicin': ['TOP2B', 'MMP2', 'TOP2A', 'HTR2B', 'TOP1'],
 'Aclatonium': ['CHRM3', 'CHRM4', 'CHRM1', 'CHRM2', 'CHRM5'],
 'Adenine': ['PI4KB', 'PI4KA', 'XDH', 'PI4K2B', 'PI4K2A'],
 'Adenosine': ['DOT1L',
  'AHCY',
  'ADK',
  'ADORA2B',
  'PRKAR2B',
  'ADORA2A',
  'PRKAR2A',
  'ADORA3',
  'ADORA1',
  'MAP3K7',
  'PRKACB',
  'ADA',
  'GAPDH',
  'PI4K2B',
  'PI4K2A',
  'PRKACA'],
 'Adenosine Triphosphate': ['GPR17',
  'P2RY13',
  'P2RY11',
  'HSPA8',
  'TRAP1',
  'AK2',
  'HSP90B1',
  'P2RX6',
  'P2RX5',
  'P2RX4',
  'P2RX3',
  'P2RY4',
  'MAPKAPK2',
  'P2RX2',
  'P2RX1',
  'P2RY2',
  'HSPA1A',
  'P2RY1',
  'MAP3K7',
  'TRPM4',
  'JAK2'],
 'Adenosine Phosphate': ['TRPM2',
  'SRC',
  'LDHA',
  'AK2',
  'DNPH1',
  'FBP1',
  'TRPM4'],
 'Adinazolam': ['GABRA3',
  'GABRA2',
  'GABRB3',
  'GABRA1',
  'GABRB2',
  'GABRB1',
  'GABRA6',
  'GABRA5',
  'GABRA4',
  'GABRG1',
  'GABRG3',
  'GABRG2',
  'TSPO',
  'GABRD'],
 'Adiphenine': ['CHRM3', 'CHRM4', 'CHRM1', 'CHRM2', 'HRH1', 'CHRM5'],
 'Agomelatine': ['MTNR1B', 'MTNR1A', 'HTR2C', 'HTR2A', 'HTR2B'],
 'Alcuronium': ['CHRM3',
  'CHRNA2',
  'CHRND',
  'CHRM4',
  'CHRNA1',
  'CHRM1',
  'CHRNA4',
  'CHRM2',
  'CHRNB4',
  'CHRNA7',
  'CHRNB1'],
 'Alfentanil': ['SIGMAR1', 'ABCB1', 'OPRD1', 'OPRK1', 'OPRM1'],
 'Alfuzosin': ['ACHE', 'SLC22A1', 'ADRA1D', 'ADRA1B', 'ADRA1A'],
 'Alfaxalone': ['GABRA3',
  'GABRA2',
  'GABRB3',
  'GABRQ',
  'GABRA1',
  'GABRB2',
  'GABRP',
  'GABRB1',
  'GABRA6',
  'GABRA5',
  'GABRA4',
  'GABRG1',
  'SLC6A1',
  'GABRG3',
  'GABRG2',
  'GABRE',
  'GABRD'],
 'Alpidem': ['GABRA3',
  'GABRA2',
  'GABRB3',
  'GABRQ',
  'GABRA1',
  'GABRB2',
  'GABRP',
  'GABRB1',
  'GABRA6',
  'GABRA5',
  'GABRA4',
  'GABRG1',
  'GABRG3',
  'GABRG2',
  'ABCB11',
  'TSPO',
  'GABRE',
  'GABRD'],
 'Alprazolam': ['BRD4',
  'GABRA3',
  'GABRA2',
  'GABRB3',
  'GABRA1',
  'GABRB2',
  'CCKAR',
  'GABRA5',
  'PTAFR',
  'CYP3A4',
  'GABRG2'],
 'Alprenolol': ['ADRB1', 'ADRB2', 'HTR2A', 'ADRB3', 'HTR1A', 'FDFT1'],
 'Alprostadil': ['CATSPER2',
  'CATSPER1',
  'CATSPER4',
  'CATSPER3',
  'PTGER1',
  'PTGER2',
  'PTGIR',
  'PTGER3',
  'PTGER4',
  'PTGDR'],
 'Amantadine': ['GRIN3A',
  'SIGMAR1',
  'GRIN2B',
  'SLC47A1',
  'GRIN2A',
  'GRIN3B',
  'GRIN2D',
  'GRIN2C',
  'GRIN1'],
 'Amidefrine': ['ADRA1D', 'ADRA1B', 'ADRA2C', 'ADRA1A', 'ADRA2B', 'ADRA2A'],
 'Amiloride': ['AOC3',
  'SLC22A1',
  'MAOA',
  'SCNN1A',
  'PLAU',
  'SLC9A1',
  'SLC9A2',
  'SCNN1G',
  'SLC9A5',
  'ADORA2A',
  'SCNN1B',
  'ASIC3',
  'ASIC1',
  'ASIC2'],
 'Amiodarone': ['CCR2',
  'HTR1B',
  'OPRM1',
  'TACR2',
  'MC3R',
  'CYP2C9',
  'KDM5A',
  'CHRM3',
  'CHRM4',
  'HCN4',
  'ABCB1',
  'CHRM1',
  'CHRM2',
  'OPRD1',
  'CHRM5',
  'HTR2C',
  'ADRB1',
  'HTR2A',
  'ADRB3',
  'CYP3A4',
  'HTR2B',
  'HRH2',
  'ERBB2',
  'ADORA3',
  'BDKRB2',
  'DRD1',
  'DRD2',
  'DRD3',
  'DRD4',
  'CCR4',
  'FDFT1',
  'KCNH2',
  'SIGMAR1',
  'OPRK1',
  'THAP1',
  'PGRMC1',
  'ADRA2B',
  'ADRA2A',
  'AR',
  'SQLE',
  'MC5R',
  'KDM7A',
  'THRB',
  'THRA',
  'PHF2',
  'KCNA7',
  'SLC6A2',
  'HTR6',
  'SLC6A3',
  'SLC6A4',
  'CACNA1H',
  'EDNRA',
  'EBP',
  'MC4R',
  'SCN5A',
  'FYN'],
 'Amisulpride': ['HTR7',
  'HTR1D',
  'HTR1B',
  'HTR2A',
  'DRD2',
  'HTR2B',
  'DRD3',
  'ADRA2C',
  'DRD4',
  'HTR6',
  'ADRA2A'],
 'Amitriptyline': ['SIGMAR1',
  'KCNJ6',
  'NTRK1',
  'HTR1B',
  'HTR1A',
  'ADRA2C',
  'ADRA2B',
  'ADRA2A',
  'SCN2A',
  'CHRM3',
  'CHRM4',
  'RET',
  'CHRM1',
  'CHRM2',
  'SLC22A1',
  'CHRM5',
  'SLC22A2',
  'HTR2C',
  'HTR2A',
  'ADRA1D',
  'HTR2B',
  'SLC6A2',
  'ADRA1B',
  'HTR6',
  'SLC6A3',
  'ADRA1A',
  'SLC6A4',
  'HRH2',
  'HTR7',
  'HRH1',
  'HRH4',
  'SCN9A',
  'AOX1',
  'SCN5A',
  'DRD1',
  'DRD2',
  'DRD3',
  'DRD5',
  'KCNH2'],
 'Amlexanox': ['GPR35', 'TBK1', 'PDE4D', 'PDE4C', 'PDE4B', 'PDE4A', 'IKBKE'],
 'Amlodipine': ['CACNA2D1',
  'CACNA1C',
  'ADRA1D',
  'CACNA1D',
  'ADRA1B',
  'ADRA2C',
  'HTR6',
  'SLC6A3',
  'ADRA1A',
  'ADRA2A',
  'CACNA1H',
  'CA1',
  'AOX1',
  'CACNG1',
  'KCNK2'],
 'Amoxapine': ['GABRA1',
  'HTR1A',
  'ADRA2C',
  'HTR3A',
  'ADRA2B',
  'ADRA2A',
  'GABRG2',
  'CHRM3',
  'CHRM4',
  'ABCB1',
  'CHRM1',
  'GABRB2',
  'CHRM2',
  'CHRM5',
  'HTR2C',
  'HTR2A',
  'ADRA1D',
  'HTR2B',
  'SLC6A2',
  'ADRA1B',
  'HTR6',
  'SLC6A3',
  'ADRA1A',
  'SLC6A4',
  'SLC6A5',
  'HTR7',
  'HRH1',
  'CYP2D6',
  'DRD1',
  'DRD2',
  'DRD3',
  'DRD4'],
 'Amfetamine': ['HTR1F',
  'HTR1D',
  'MAOA',
  'HTR1B',
  'HTR2C',
  'HTR2A',
  'HTR3B',
  'HTR1A',
  'HTR2B',
  'CARTPT',
  'SLC6A2',
  'TAAR1',
  'HTR3A',
  'HTR6',
  'SLC6A3',
  'ADRA1A',
  'SLC6A4',
  'ADRA2A',
  'HTR4',
  'HTR5A',
  'HTR7'],
 'Amrinone': ['PDE4D', 'PDE3B', 'PDE4C', 'PDE3A', 'PDE4B', 'PDE4A', 'TTK'],
 'Amsacrine': ['TOP2B',
  'SLC22A1',
  'CYP2D6',
  'TOP1MT',
  'TOP2A',
  'TOP1',
  'KCNH2'],
 'Androstenediol': ['AR', 'ESR1', 'ESR2', 'SERPINA6', 'SHBG'],
 'Androstenedione': ['AR', 'HSD17B3', 'CYP19A1', 'SERPINA6', 'SHBG'],
 'Anhydrovinblastine': ['ABCB1', 'ABCC2', 'ABCC10', 'ABCC1', 'TUBB4B'],
 'Apomorphine': ['SIGMAR1',
  'HTR1F',
  'HTR1D',
  'TRPA1',
  'HTR1B',
  'OPRK1',
  'HTR3B',
  'OPRM1',
  'HTR1A',
  'ADRA2C',
  'HTR3A',
  'ADRA2B',
  'ADRA2A',
  'HTR5A',
  'MDM2',
  'OPRD1',
  'MPI',
  'SLC22A1',
  'HTR2C',
  'HTR2A',
  'ADRA1D',
  'HTR2B',
  'ADRA1B',
  'HTR6',
  'ADRA1A',
  'HTR4',
  'HTR7',
  'DRD1',
  'DRD2',
  'DRD3',
  'DRD4',
  'DRD5'],
 'Apraclonidine': ['ADRA1D', 'ADRA1B', 'ADRA2C', 'ADRA1A', 'ADRA2B', 'ADRA2A'],
 'Aprindine': ['HCN4',
  'CYP2D6',
  'PSMA1',
  'SCN5A',
  'CALM2',
  'CALM3',
  'SLC8A1',
  'CALM1',
  'KCNH2'],
 'Aripiprazole': ['HTR1D',
  'HTR1E',
  'HTR1B',
  'HTR1A',
  'ADRA2C',
  'HTR3A',
  'ADRA2B',
  'ADRA2A',
  'HTR5A',
  'CHRM3',
  'CHRM4',
  'ABCB1',
  'CHRM1',
  'CHRM2',
  'CHRM5',
  'HTR2C',
  'ADRB1',
  'ADRB2',
  'HTR2A',
  'HTR2B',
  'SLC6A2',
  'ADRA1B',
  'HTR6',
  'SLC6A3',
  'ADRA1A',
  'SLC6A4',
  'HTR7',
  'HRH1',
  'DRD1',
  'DRD2',
  'DRD3',
  'DRD4',
  'DRD5',
  'KCNH2'],
 'Astemizole': ['HTR1B',
  'OPRM1',
  'TACR1',
  'HTR1A',
  'TACR2',
  'SSTR5',
  'MC3R',
  'CALM2',
  'CALM3',
  'ABCG2',
  'CALM1',
  'CHRM3',
  'CHRM4',
  'ABCB1',
  'CHRM1',
  'CHRM2',
  'OPRD1',
  'CHRM5',
  'HTR2C',
  'ADRB1',
  'HTR2A',
  'ADRA1D',
  'ADRB3',
  'CYP3A4',
  'HTR2B',
  'ADRA1B',
  'EGFR',
  'ADRA1A',
  'HRH2',
  'HRH1',
  'HRH4',
  'ERBB2',
  'ADORA3',
  'DRD1',
  'DRD2',
  'DRD3',
  'DRD4',
  'KCNH1',
  'KCNH2',
  'SIGMAR1',
  'EED',
  'OPRK1',
  'HLA-A',
  'ADRA2C',
  'HTR3A',
  'PGRMC1',
  'ADRA2B',
  'ADRA2A',
  'LCK',
  'MC5R',
  'SLC28A1',
  'SLC47A1',
  'TMEM97',
  'SLC6A2',
  'HTR6',
  'SLC6A3',
  'SLC6A4',
  'GLRA1',
  'FNTB',
  'FNTA',
  'MC4R',
  'FYN'],
 'Atazanavir': ['ABCB1', 'CYP2C9', 'UGT1A1', 'CYP1A2', 'CYP3A4'],
 'Atomoxetine': ['KCNJ5',
  'KCNJ6',
  'CYP2D6',
  'KLF10',
  'SLC6A2',
  'SLC6A3',
  'KCNJ3',
  'SLC6A4',
  'KCNH2'],
 'Atorvastatin': ['HDAC6', 'HDAC1', 'HDAC2', 'NR1I3', 'HMGCR', 'CYP3A4'],
 'Atracurium': ['CHRNA2',
  'CHRND',
  'CHRNA1',
  'CHRNA4',
  'CHRNA3',
  'CHRNA7',
  'KCNN3',
  'CHRNB1'],
 'Atropine': ['ACHE',
  'CHRM3',
  'CHRM4',
  'CHRM1',
  'CHRM2',
  'HRH1',
  'SLC22A1',
  'CHRM5',
  'HTR2C',
  'HTR2A',
  'ADRA1D',
  'ADRA2A'],
 'Azapetine': ['ADRA1D', 'ADRA1B', 'ADRA2C', 'ADRA1A', 'ADRA2B', 'ADRA2A'],
 'Azathioprine': ['ABCC4', 'ABCC5', 'TPMT', 'RAC1', 'ABCG2'],
 'Azelastine': ['ABCB1',
  'CHRM1',
  'HRH1',
  'HRH3',
  'HTR2C',
  'HTR2B',
  'ADRA1B',
  'ADRA1A',
  'KCNH2'],
 'Baclofen': ['GABRA3',
  'GABRA2',
  'GABRB3',
  'GABRQ',
  'GABBR2',
  'GABRA1',
  'GABRB2',
  'GABRP',
  'GABBR1',
  'GABRB1',
  'GABRA6',
  'GABRA5',
  'GABRA4',
  'GABRG1',
  'GABRG3',
  'GABRG2',
  'ADORA3',
  'GABRE',
  'GABRD'],
 'Beclometasone Dipropionate': ['AR',
  'IL5',
  'ADGRG3',
  'PGR',
  'MMP9',
  'NR3C2',
  'NR3C1'],
 'Bendamustine': ['HDAC6', 'HDAC3', 'HDAC1', 'HDAC10', 'HDAC2', 'HDAC8'],
 'Bendroflumethiazide': ['SLC12A3', 'CA2', 'CA1', 'CA4', 'KCNMA1'],
 'Benperidol': ['SIGMAR1', 'HTR2A', 'DRD2', 'DRD3', 'DRD4', 'KCNH2'],
 'Diphenidol': ['CHRM3',
  'SIGMAR1',
  'CHRM4',
  'CHRM1',
  'CHRM2',
  'CHRM5',
  'HTR2A',
  'ADRA1B',
  'CYP2D6',
  'SCN3A',
  'DRD2',
  'DRD3',
  'SCN1A',
  'SCN2A'],
 'Benserazide': ['DDC', 'UBA2', 'ESR2', 'HK2', 'SAE1'],
 'Benzbromarone': ['PTPN1',
  'CYP2C9',
  'EYA2',
  'EYA3',
  'AKR1C1',
  'ADORA3',
  'MAPK1',
  'PDE4A',
  'HTR2B',
  'ABCC1',
  'MAPK14',
  'SLC22A12'],
 'Benzocaine': ['SCN11A',
  'SCN9A',
  'SCN10A',
  'SCN7A',
  'SCN8A',
  'SCN5A',
  'SCN3A',
  'SCN4A',
  'SCN1A',
  'SCN2A'],
 'Benzquinamide': ['DRD2',
  'DRD3',
  'ADRA2C',
  'DRD4',
  'ADRA2B',
  'ADRA2A',
  'PTGS2'],
 'Benzthiazide': ['SLC12A3', 'CA2', 'CA1', 'CA4', 'KCNMA1'],
 'Benzatropine': ['CHRM3',
  'SIGMAR1',
  'CHRM4',
  'CHRM1',
  'CHRM2',
  'SLC6A19',
  'CHRM5',
  'HTR2C',
  'HTR2A',
  'ADRA1D',
  'HTR2B',
  'SLC6A2',
  'ADRA1B',
  'ADRA2C',
  'HTR6',
  'PGRMC1',
  'SLC6A3',
  'ADRA1A',
  'ADRA2B',
  'SLC6A4',
  'ADRA2A',
  'HRH2',
  'HRH1',
  'DRD3'],
 'Bepridil': ['HCN4',
  'KCNT1',
  'CACNA1A',
  'CACNA1C',
  'KCNQ4',
  'SCN5A',
  'SCN3A',
  'CACNA1D',
  'SCN1A',
  'SCN2A',
  'CACNA1H',
  'KCNH2'],
 'Bexarotene': ['CYP26A1',
  'RXRA',
  'CYP26B1',
  'RXRB',
  'RARG',
  'NR1H3',
  'NR1H2',
  'RARB',
  'PPARG',
  'RARA',
  'RXRG'],
 'Bezafibrate': ['FABP2', 'PPARA', 'LPL', 'PPARG', 'HMGCR', 'PPARD', 'FABP1'],
 'Biperiden': ['CHRM3', 'CHRNA2', 'CHRM4', 'CHRM1', 'CHRM2', 'CHRM5'],
 'Bopindolol': ['CYP2D6',
  'ADRB1',
  'ADRB2',
  'HTR2A',
  'ADRB3',
  'HTR1A',
  'HTR2B'],
 'Bortezomib': ['CA13',
  'CA12',
  'CTSA',
  'PSD',
  'CMA1',
  'F2',
  'NFKB1',
  'NFKB2',
  'PSMB9',
  'PSMA1',
  'CTRB1',
  'RELA',
  'CYP2C19',
  'PSMB10',
  'PSMB8',
  'CA2',
  'PSMB5',
  'CA1',
  'CA4',
  'CA3',
  'CA5B',
  'CA5A',
  'CA6',
  'PSMB1',
  'PSMB2',
  'PSMD1',
  'CA7',
  'CA9',
  'CTSG',
  'CA14',
  'ELANE'],
 'Brimonidine': ['ADRA1D',
  'HTR1A',
  'ADRA1B',
  'ADRA2C',
  'ADRA1A',
  'ADRA2B',
  'ADRA2A'],
 'Brinzolamide': ['CA13',
  'CA12',
  'CA2',
  'CA1',
  'CA4',
  'CA5B',
  'CA5A',
  'CA6',
  'CA7',
  'CA9',
  'CA14'],
 'Bromocriptine': ['HTR1D',
  'HTR1B',
  'HTR2C',
  'ADRB1',
  'ADRB2',
  'HTR2A',
  'ADRA1D',
  'CYP3A4',
  'HTR1A',
  'HTR2B',
  'ADRA1B',
  'ADRA2C',
  'HTR6',
  'ADRA1A',
  'ADRA2B',
  'ADRA2A',
  'AR',
  'HTR7',
  'DRD1',
  'SLC17A8',
  'DRD2',
  'DRD3',
  'DRD4',
  'DRD5'],
 'Bromperidol': ['CHRM3',
  'SIGMAR1',
  'CHRM4',
  'CHRM1',
  'CHRM2',
  'HRH1',
  'CHRM5',
  'DRD1',
  'DRD2',
  'DRD3',
  'DRD4',
  'ADRA1A'],
 'Brompheniramine': ['HRH1', 'SCN3A', 'SCN1A', 'SCN2A', 'KCNH2'],
 'Budesonide': ['AR', 'IL5', 'ABCB1', 'IFNG', 'PGR', 'MMP9', 'NR3C2', 'NR3C1'],
 'Budipine': ['GRIN3A',
  'GRIN2B',
  'GRIN2A',
  'GRIN3B',
  'GRIN2D',
  'GRIN2C',
  'GRIN1',
  'KCNH2'],
 'Buflomedil': ['SIGMAR1',
  'EBP',
  'CACNG1',
  'ADRA1D',
  'ADRA1B',
  'ADRA2C',
  'ADRA1A',
  'ADRA2A'],
 'Levobunolol': ['SIGMAR1', 'ADRB1', 'ADRB2', 'ADRB3', 'HTR1A', 'SLC6A4'],
 'Bupivacaine': ['KCND3',
  'PTGER1',
  'CYP2D6',
  'SCN5A',
  'KCNA5',
  'SCN4A',
  'SCN1A',
  'HTR3A',
  'KCNK3',
  'KCNH2'],
 'Buprenorphine': ['OPRD1', 'OPRK1', 'OPRM1', 'OPRL1', 'KCNH2'],
 'Bupropion': ['CHRNB2',
  'CHRNA3',
  'CHRNB4',
  'CYP2D6',
  'CHRNA7',
  'SLC6A2',
  'CYP2C19',
  'PGRMC1',
  'SLC6A3',
  'ADRA1A',
  'SLC6A4'],
 'Buspirone': ['SIGMAR1',
  'HTR1F',
  'HTR1D',
  'HTR1B',
  'HTR1A',
  'ADRA2C',
  'PGRMC1',
  'ADRA2B',
  'ADRA2A',
  'SLC47A1',
  'SLC47A2',
  'SLC22A2',
  'HTR2C',
  'HTR2A',
  'ADRA1D',
  'CYP3A4',
  'HTR2B',
  'ADRA1B',
  'ADRA1A',
  'HTR7',
  'DRD1',
  'DRD2',
  'DRD3',
  'DRD4',
  'DRD5',
  'KCNH2'],
 'Butenafine': ['ACHE',
  'SIGMAR1',
  'CYP2D6',
  'SLC6A2',
  'PGRMC1',
  'SLC6A4',
  'ADRA2A'],
 'Cabergoline': ['HTR1D',
  'HTR1B',
  'HTR2C',
  'HTR2A',
  'ADRA1D',
  'HTR1A',
  'HTR2B',
  'ADRA1B',
  'ADRA2C',
  'ADRA1A',
  'ADRA2B',
  'ADRA2A',
  'DRD1',
  'DRD2',
  'DRD3',
  'DRD4',
  'DRD5'],
 'Caffeine': ['ACHE',
  'GDA',
  'ADORA2B',
  'ADORA2A',
  'ADORA3',
  'PIK3CD',
  'ADORA1',
  'PYGM',
  'KCNH2'],
 'Camostat': ['SLC47A1',
  'PRSS1',
  'SLC47A2',
  'HPN',
  'KLK1',
  'SLC22A2',
  'TMPRSS2',
  'F2',
  'PLG',
  'HGFAC'],
 'Candesartan Cilexetil': ['ADRB3',
  'CYP3A4',
  'SLC6A2',
  'EGFR',
  'ADRA2B',
  'CYP2C9',
  'ERBB2',
  'TBXAS1',
  'POLK',
  'ADORA3',
  'AGTR1',
  'POLI',
  'POLH'],
 'Captopril': ['ACE', 'LTA4H', 'F2', 'REN', 'PTGS1', 'PTGS2'],
 'Caramiphen': ['SIGMAR1', 'CHRM1', 'CHRM2', 'PRCP', 'SLC6A3'],
 'Carbachol': ['ACHE',
  'CHRM3',
  'CHRNA2',
  'CHRM4',
  'CHRNA1',
  'CHRNB2',
  'CHRM1',
  'CHRNA4',
  'CHRM2',
  'CHRNA3',
  'CHRNB4',
  'CHRM5',
  'CHRNA7',
  'CHRND'],
 'Carbamazepine': ['CHRNA2',
  'GABRA1',
  'GABRB2',
  'CHRNB4',
  'HRH1',
  'NR1I2',
  'SCN9A',
  'FZD8',
  'SCN5A',
  'SCN4A',
  'SLC6A4',
  'GABRG2'],
 'Pentoxyverine': ['SIGMAR1', 'CHRM1', 'CHRM2', 'SLC22A1', 'PRCP', 'SLC6A3'],
 'Carvedilol': ['KCNK10',
  'HTR1B',
  'HTR1A',
  'ADRA2C',
  'ADRA2B',
  'ADRA2A',
  'KCNK2',
  'TLR4',
  'APP',
  'RYR2',
  'SLC47A1',
  'SLC22A1',
  'SLC22A2',
  'HTR2C',
  'ADRB1',
  'ADRB2',
  'HTR2A',
  'ADRA1D',
  'ADRB3',
  'HTR2B',
  'SLC6A2',
  'ADRA1B',
  'HTR6',
  'SLC6A3',
  'ADRA1A',
  'SLC6A4',
  'HTR4',
  'DRD1',
  'DRD2',
  'DRD3',
  'KCNH2'],
 'Cefotetan': ['MMP1', 'MMP2', 'MMP9', 'COMT', 'PTGS2'],
 'Cefsulodin': ['GRK2', 'L3MBTL1', 'PTPN11', 'PTPN6', 'TPT1'],
 'Celecoxib': ['CA13',
  'CA12',
  'PDPK1',
  'ADRA2B',
  'MAPK14',
  'PDE5A',
  'PGR',
  'PTGES',
  'HDAC6',
  'HDAC1',
  'ADRB3',
  'SLC6A2',
  'SLC6A3',
  'PTGS1',
  'SLC6A4',
  'PTGS2',
  'CA2',
  'CA1',
  'CA4',
  'CA3',
  'CA5B',
  'CA5A',
  'CA6',
  'CYP2D6',
  'ADORA3',
  'CA7',
  'DRD1',
  'PDE4A',
  'CA9',
  'CA14'],
 'Cefalotin': ['PTPN7', 'MMP9', 'SLC22A8', 'SSTR4', 'SLC22A11', 'PTGS2'],
 'Cefapirin': ['SIGMAR1',
  'OPRD1',
  'MMP1',
  'OPRK1',
  'OPRM1',
  'TACR1',
  'CYP3A4',
  'HTR1A',
  'HTR2B',
  'TACR2',
  'CYP3A5',
  'ADRA2C',
  'SSTR4',
  'NISCH',
  'HRH2',
  'CNR1',
  'CYP2D6',
  'DRD2',
  'DRD3',
  'DRD4'],
 'Cevimeline': ['CHRM3', 'CHRM4', 'CHRM1', 'CHRM2', 'CHRM5'],
 'Chlorambucil': ['OPRD1', 'AKR1B1', 'ADAM9', 'CTSE', 'CTSD'],
 'Chlordiazepoxide': ['ACHE',
  'GABRA3',
  'TRHR',
  'GABRA2',
  'GABRB3',
  'GABRQ',
  'BCHE',
  'GABRA1',
  'GABRB2',
  'GABRP',
  'GABRB1',
  'GABRA6',
  'GABRA5',
  'GABRA4',
  'GABRG1',
  'GABRG3',
  'GABRG2',
  'HRH1',
  'CCKAR',
  'CCKBR',
  'TSPO',
  'GABRE',
  'GABRD'],
 'Chlorhexidine': ['SLC47A1',
  'SLC47A2',
  'SLC22A1',
  'SYNJ2',
  'TPR',
  'MMP2',
  'SLC22A3',
  'SLC22A2',
  'RCE1',
  'MMP9'],
 'Chlormadinone': ['AR', 'ATP1A2', 'PGR', 'CYP2C19', 'NR3C1'],
 'Chloroquine': ['APP',
  'CHRM3',
  'SIGMAR1',
  'CHRM4',
  'NQO2',
  'CHRM1',
  'CHRM2',
  'CHRM5',
  'PRNP',
  'TMEM97',
  'ADRA2C',
  'ADRA2B',
  'ADRA2A',
  'BACE1',
  'DHFR',
  'KCNH2'],
 'Chlorphenamine': ['L3MBTL1',
  'L3MBTL3',
  'HTR2B',
  'SLC6A2',
  'SLC6A3',
  'SLC6A4',
  'HRH1',
  'HRH4',
  'CYP2D6',
  'MBTD1',
  'SCN3A',
  'SCN1A',
  'SCN2A',
  'KCNH2'],
 'Chlorpromazine': ['HTR1D',
  'HTR1E',
  'HTR1B',
  'OPRM1',
  'TRPV1',
  'HTR1A',
  'TACR2',
  'GRIN2D',
  'GRIN2C',
  'GRIN1',
  'HTR5A',
  'GRIN3A',
  'MC3R',
  'GRIN3B',
  'CALM2',
  'KCNK2',
  'CALM3',
  'CALM1',
  'CHRM3',
  'CHRM4',
  'CHRNA1',
  'ABCB1',
  'CHRM1',
  'CHRM2',
  'OPRD1',
  'ADCY1',
  'CHRM5',
  'ADCY5',
  'ALOX15',
  'HTR2C',
  'ADCY4',
  'ADCY3',
  'HTR2A',
  'ADCY2',
  'ADRA1D',
  'HTR2B',
  'ADCY8',
  'ADRA1B',
  'EGFR',
  'ADRA1A',
  'ADCY6',
  'HRH2',
  'HRH1',
  'HRH4',
  'CYP2D6',
  'ERBB2',
  'AOX1',
  'DRD1',
  'SCN3A',
  'DRD2',
  'DRD3',
  'DRD4',
  'DRD5',
  'KCNH2',
  'SIGMAR1',
  'PRNP',
  'OPRK1',
  'GFER',
  'ADRA2C',
  'HTR3A',
  'PGRMC1',
  'ADRA2B',
  'ADRA2A',
  'MC5R',
  'SCN2A',
  'RYR1',
  'SLC22A1',
  'SLC22A2',
  'SLC6A2',
  'HTR6',
  'SLC6A3',
  'SLC6A4',
  'GRIN2B',
  'HTR7',
  'GRIN2A',
  'TPR',
  'MC4R',
  'SMPD1',
  'FYN',
  'SCN1A'],
 'Chlorprothixene': ['CHRM3',
  'CHRM4',
  'CHRM1',
  'CHRM2',
  'SLC22A1',
  'CHRM5',
  'HTR2A',
  'HTR6',
  'HTR7',
  'HRH1',
  'DRD1',
  'DRD2',
  'DRD3',
  'DRD4',
  'DRD5'],
 'Chlortalidone': ['CA13',
  'SLC12A3',
  'CA12',
  'CA2',
  'CA1',
  'CA4',
  'CA3',
  'CA5B',
  'CA5A',
  'CA6',
  'CA7',
  'CA9',
  'CA14'],
 'Chlorzoxazone': ['NOS3', 'KCNMA1', 'KCNN2', 'NOS1', 'KCNN4', 'NOS2'],
 'Cianidanol': ['APP',
  'CA13',
  'CA12',
  'F2',
  'DHODH',
  'PTGS1',
  'BACE1',
  'PTGS2',
  'CA2',
  'CA1',
  'CA4',
  'KIT',
  'CA3',
  'CA5B',
  'CA5A',
  'CA6',
  'CA7',
  'CA9',
  'CA14'],
 'Cicaprost': ['PTGFR',
  'PTGER1',
  'PTGER2',
  'PTGIR',
  'PTGER3',
  'PTGER4',
  'PTGDR'],
 'Cinnarizine': ['SIGMAR1',
  'OPRM1',
  'HTR1A',
  'ADRA2C',
  'PGRMC1',
  'ADRA2B',
  'ADRA2A',
  'SCN2A',
  'CHRM3',
  'CHRM4',
  'CHRM1',
  'CHRM5',
  'HTR2A',
  'ADRA1D',
  'HTR2B',
  'SLC6A2',
  'ADRA1B',
  'SLC6A3',
  'ADRA1A',
  'SLC6A4',
  'HRH1',
  'HRH4',
  'SCN3A',
  'DRD2',
  'DRD3',
  'SCN1A'],
 'Ciprofloxacin': ['GABRA3',
  'TOP2B',
  'GABRA2',
  'GABRB3',
  'GABRQ',
  'GABRA1',
  'GABRB2',
  'GABRP',
  'GABRB1',
  'GABRA6',
  'GABRA5',
  'GABRA4',
  'TOP2A',
  'GABRG1',
  'GABRG3',
  'GABRG2',
  'HRH3',
  'GABRE',
  'GABRD'],
 'Cisapride': ['SIGMAR1',
  'HTR1F',
  'HTR1D',
  'HTR1B',
  'HTR3D',
  'HTR3E',
  'HTR3B',
  'HTR1A',
  'HTR3C',
  'ADRA2C',
  'HTR3A',
  'PGRMC1',
  'ADRA2B',
  'ADRA2A',
  'HTR2C',
  'HMGCR',
  'HTR2A',
  'ADRA1D',
  'CYP3A4',
  'HTR2B',
  'ADRA1B',
  'ADRA1A',
  'SLC6A4',
  'HTR4',
  'HTR7',
  'CYP2D6',
  'DRD1',
  'DRD2',
  'DRD3',
  'KCNH2'],
 'Citalopram': ['SIGMAR1',
  'CHRM1',
  'SLC22A1',
  'HTR2C',
  'HTR2A',
  'ADRA1D',
  'HTR1A',
  'HTR2B',
  'SLC6A2',
  'ADRA1B',
  'SLC6A3',
  'ADRA1A',
  'SLC6A4',
  'HRH1',
  'KCNH2'],
 'Clebopride': ['ACHE',
  'HTR2C',
  'HTR2A',
  'HTR2B',
  'ADRA2C',
  'ADRA2B',
  'ADRA2A',
  'HTR4',
  'DRD1',
  'DRD2',
  'DRD3',
  'DRD4',
  'KCNH2'],
 'Clemastine': ['SIGMAR1',
  'HTR1B',
  'ADRA2C',
  'PGRMC1',
  'ADRA2B',
  'ADRA2A',
  'CHRM3',
  'CHRM4',
  'CHRM1',
  'CHRM2',
  'SLC22A1',
  'CHRM5',
  'HTR2C',
  'HTR2A',
  'TMEM97',
  'ADRA1D',
  'HTR2B',
  'SLC6A2',
  'ADRA1B',
  'CYP2C19',
  'HTR6',
  'SLC6A3',
  'ADRA1A',
  'HRH2',
  'HRH1',
  'CYP2D6',
  'DRD1',
  'DRD2',
  'DRD3',
  'KCNH2'],
 'Clemizole': ['TRPC6', 'HRH4', 'TRPC4', 'TRPC5', 'TRPC3', 'HMOX2'],
 'Clodronic Acid': ['PTPN1', 'SLC25A4', 'SLC17A9', 'SLC25A6', 'SLC25A5'],
 'Clofarabine': ['POLA1', 'RRM2', 'UCK2', 'UCK1', 'RRM1', 'PRPS1', 'PDE2A'],
 'Clomifene': ['SIGMAR1',
  'TACR2',
  'ESR1',
  'ADRA2C',
  'PGRMC1',
  'ADRA2B',
  'ADRA2A',
  'AR',
  'CHRM3',
  'CHRM4',
  'CHRM1',
  'CHRM2',
  'CHRM5',
  'HTR2C',
  'HTR2A',
  'ADRB3',
  'HTR2B',
  'SLC6A2',
  'ADRA1B',
  'EGFR',
  'HTR6',
  'SLC6A3',
  'PTGS1',
  'SLC6A4',
  'EBP',
  'HRH1',
  'CYP2D6',
  'ERBB2',
  'ADORA3',
  'FYN',
  'DRD3',
  'KCNH2'],
 'Clomipramine': ['SIGMAR1',
  'KCNJ6',
  'HTR1F',
  'HTR1D',
  'HTR1B',
  'HTR3B',
  'HTR1A',
  'ADRA2C',
  'HTR3A',
  'PGRMC1',
  'ADRA2B',
  'ADRA2A',
  'HTR5A',
  'CHRM3',
  'CHRM4',
  'CHRM1',
  'CHRM2',

## 6 drugs given to the UK65 patient

In [37]:
# List of drugs you want to keep
target_drugs = [
    "Doxorubicin",
    "Paclitaxel",
    "Zoledronic Acid",
    "Fulvestrant",
    "Palbociclib",
    "Gemcitabine"
]
target_drugs_lower = [d.lower() for d in target_drugs]


UK65_drug_administered_dict = {
    k: v for k, v in idg.items()
    if k.lower() in target_drugs_lower
}
UK65_drug_administered_dict

{'Doxorubicin': ['TOP2B',
  'ABCB1',
  'ABCC2',
  'CHRM1',
  'MMP2',
  'ABCC6',
  'TOP2A',
  'ALOX15',
  'AURKA',
  'HTR1B',
  'CISD1',
  'RNASE1',
  'HTR4',
  'LCK',
  'TERT',
  'ERBB2',
  'CASP1',
  'FYN',
  'TOP1',
  'ABCC1',
  'ABCG2'],
 'Fulvestrant': ['ESRRA',
  'NR1I2',
  'EPHX2',
  'GPER1',
  'NR1H4',
  'PGR',
  'ESR1',
  'ESR2'],
 'Gemcitabine': ['POLA1',
  'POLE',
  'RRM2',
  'POLD1',
  'RRM1',
  'DCK',
  'TYMS',
  'CMPK1'],
 'Paclitaxel': ['ABCB1',
  'OPRD1',
  'NR1I2',
  'TUBB',
  'TUBB1',
  'NOD2',
  'TACR2',
  'TUBB2A',
  'MERTK',
  'TUBB4B',
  'TUBB4A',
  'TUBB8',
  'ABCB11',
  'ABCC10',
  'TUBB2B',
  'TUBB6',
  'CCKAR',
  'ERBB2',
  'MC5R',
  'TUBB3',
  'FYN'],
 'Zoledronic Acid': ['FDPS',
  'CA12',
  'CA2',
  'MMP14',
  'MMP8',
  'BTN3A1',
  'MMP2',
  'GGPS1',
  'CA9',
  'MMP9',
  'CA14'],
 'Palbociclib': ['CCNA2',
  'CDK9',
  'CDK6',
  'FLT3',
  'RPS6KA1',
  'CCND1',
  'CDK4',
  'CDK2',
  'DYRK1A',
  'JAK3']}

## Calculating the jaccard siliarity to get the top pathways for given drugs

In [38]:
from typing import Dict, List, Iterable

def jaccard_similarity(list1: Iterable[str], list2: Iterable[str]) -> float:
    """
    Compute Jaccard similarity between two gene lists (case-insensitive).
    Returns 0.0 if union is empty.
    """
    s1 = {g.upper() for g in list1 if isinstance(g, str) and g.strip()}
    s2 = {g.upper() for g in list2 if isinstance(g, str) and g.strip()}
    if not s1 and not s2:
        return 0.0
    inter = s1.intersection(s2)
    union = s1.union(s2)
    return len(inter) / len(union) if union else 0.0

def compute_jaccard_for_df(
    gene_set_df: pd.DataFrame,
    drug_targets: Dict[str, List[str]],
    gene_col: str = "genes",
    setname_col: str = "set_name",
    genes_separator: str = ",",
    case_insensitive: bool = True,
) -> pd.DataFrame:
    """
    Compute Jaccard similarity between each gene set in gene_set_df and each drug in drug_targets.

    Parameters
    ----------
    gene_set_df : pd.DataFrame
        DataFrame with at least two columns: set_name and genes (comma-separated string OR list).
    drug_targets : dict
        Mapping from drug name -> list of target genes (strings).
    gene_col : str
        Column name in gene_set_df that contains gene lists (string or list).
    setname_col : str
        Column name that contains pathway / gene set names.
    genes_separator : str
        If gene_col contains strings, split by this separator to get genes.
    case_insensitive : bool
        If True, matching is case-insensitive (recommended).

    Returns
    -------
    pd.DataFrame
        Rows = gene sets; columns = set_name + one column per drug with Jaccard scores (float).
    """
    # Validate input
    if setname_col not in gene_set_df.columns or gene_col not in gene_set_df.columns:
        raise ValueError(f"DataFrame must contain columns '{setname_col}' and '{gene_col}'")

    # Prepare drug targets (normalize case if requested)
    if case_insensitive:
        drug_targets_norm = {drug: [g.upper() for g in genes if isinstance(g, str)] for drug, genes in drug_targets.items()}
    else:
        drug_targets_norm = {drug: [g for g in genes if isinstance(g, str)] for drug, genes in drug_targets.items()}

    results = []
    for idx, row in gene_set_df.iterrows():
        set_name = row[setname_col]
        raw_genes = row[gene_col]
        # If genes are a string (comma-separated), split them
        if isinstance(raw_genes, str):
            genes_list = [g.strip() for g in raw_genes.split(genes_separator) if g.strip()]
        elif isinstance(raw_genes, (list, tuple, set, pd.Series)):
            genes_list = [str(g).strip() for g in raw_genes if pd.notna(g)]
        else:
            genes_list = []
        # Normalize case if requested
        if case_insensitive:
            genes_list_norm = [g.upper() for g in genes_list]
        else:
            genes_list_norm = genes_list

        # Compute jaccard vs each drug
        row_result = {setname_col: set_name}
        for drug, targets in drug_targets_norm.items():
            score = jaccard_similarity(genes_list_norm, targets)
            row_result[drug] = score
        results.append(row_result)

    out_df = pd.DataFrame(results)
    # Optional: keep set_name as first column
    cols = [setname_col] + [c for c in out_df.columns if c != setname_col]
    out_df = out_df[cols]
    return out_df

In [41]:
# Compute Jaccard scores
jaccard_df = compute_jaccard_for_df(gene_set_df, UK65_drug_administered_dict,
                                    gene_col='genes', setname_col='set_name',
                                    genes_separator=',', case_insensitive=True)

# Save results to CSV_
jaccard_df.to_csv("singscore_new_code/UK65_jaccard_for_6drugs_vs_pathways.csv", index=False)
jaccard_df

,set_name,Doxorubicin,Fulvestrant,Gemcitabine,Paclitaxel,Zoledronic Acid,Palbociclib
0,TNF-alpha Signaling via NF-kB,0.000000,0.0,0.0,0.004545,0.000000,0.004785
1,Hypoxia,0.000000,0.0,0.0,0.000000,0.004762,0.000000
2,Cholesterol Homeostasis,0.000000,0.0,0.0,0.000000,0.011905,0.000000
3,Mitotic Spindle,0.009174,0.0,0.0,0.000000,0.000000,0.000000
4,Wnt-beta Catenin Signaling,0.000000,0.0,0.0,0.000000,0.000000,0.000000
...,...,...,...,...,...,...,...
7797,Zinc Ion Import Across Plasma Membrane (GO:007...,0.000000,0.0,0.0,0.000000,0.000000,0.000000
7798,Zinc Ion Import Into Organelle (GO:0062111),0.000000,0.0,0.0,0.000000,0.000000,0.000000
7799,Zinc Ion Transmembrane Transport (GO:0071577),0.000000,0.0,0.0,0.000000,0.000000,0.000000
7800,Zinc Ion Transport (GO:0006829),0.000000,0.0,0.0,0.000000,0.000000,0.000000
7801,Zymogen Activation (GO:0031638),0.000000,0.0,0.0,0.000000,0.027027,0.000000

### Saving relevant pathways by filteritng jaccard score > 0 for each drug

In [53]:
def save_drug_relevant_pathways(drugname: str,
                                jaccard_df: pd.DataFrame,
                                gene_set_df: pd.DataFrame,
                                output_root: str = "singscore_new_code",
                                jaccard_col_check: bool = True,
                                save_json: bool = True) -> pd.DataFrame:
    """
    Filter gene_set_df for pathways relevant to a given drug using jaccard_df,
    save both a CSV and a JSON file.

    JSON format example:
    {
      "TNF-alpha Signaling via NF-kB": ["MARCKS", "IL23A", "NINJ1", ...],
      "MTOR_PATHWAY": ["G1", "G2"]
    }

    Parameters
    ----------
    drugname : str
        Drug name (must exist as a column in jaccard_df).
    jaccard_df : pd.DataFrame
        DataFrame containing 'set_name' and drug Jaccard scores.
    gene_set_df : pd.DataFrame
        DataFrame with columns ['set_name', 'genes'] (genes can be comma-separated string).
    output_root : str
        Folder where the subfolder per drug will be created.
    jaccard_col_check : bool
        Check column existence for safety.
    save_json : bool
        Whether to save a JSON version of the relevant pathways.

    Returns
    -------
    pd.DataFrame
        Filtered DataFrame containing relevant pathways.
    """


    # 2️⃣ Filter pathways with positive Jaccard similarity
    df1 = jaccard_df.sort_values(by=drugname, ascending=False)
    df2 = df1[df1[drugname] > 0]
    relevant_pathways = df2["set_name"].tolist()

    df4 = gene_set_df[gene_set_df["set_name"].isin(relevant_pathways)].reset_index(drop=True)

    # 3️⃣ Create output directory for this drug
    drug_dir = Path(output_root) / drugname.replace(" ", "_")
    drug_dir.mkdir(parents=True, exist_ok=True)

    # 5️⃣ Save JSON (key = set_name, value = list of genes)
    if save_json:
        json_dict = {}
        for _, row in df4.iterrows():
            genes = row["genes"]
            if isinstance(genes, str):
                gene_list = [g.strip() for g in genes.replace("\n", ",").split(",") if g.strip()]
            elif isinstance(genes, (list, tuple, set)):
                gene_list = list(genes)
            else:
                gene_list = []
            json_dict[row["set_name"]] = gene_list

        json_path = drug_dir / f"{drugname.replace(' ', '_')}_relevant_pathways.json"
        with open(json_path, "w", encoding="utf-8") as f:
            json.dump(json_dict, f, indent=2, ensure_ascii=False)

        print(f"✅ JSON saved to: {json_path}")

    return df4

In [55]:
for i in target_drugs:
    df4 = save_drug_relevant_pathways(f"{i}", jaccard_df, gene_set_df)

✅ JSON saved to: singscore_new_code\Doxorubicin\Doxorubicin_relevant_pathways.json
✅ JSON saved to: singscore_new_code\Paclitaxel\Paclitaxel_relevant_pathways.json
✅ JSON saved to: singscore_new_code\Zoledronic_Acid\Zoledronic_Acid_relevant_pathways.json
✅ JSON saved to: singscore_new_code\Fulvestrant\Fulvestrant_relevant_pathways.json
✅ JSON saved to: singscore_new_code\Palbociclib\Palbociclib_relevant_pathways.json
✅ JSON saved to: singscore_new_code\Gemcitabine\Gemcitabine_relevant_pathways.json

## SingScores for the hallmark genes for UK65 patient

In [32]:
hallmark  = gp.get_library(organism='Human', name ='MSigDB_Hallmark_2020')
hallmark

{'TNF-alpha Signaling via NF-kB': ['MARCKS',
  'IL23A',
  'NINJ1',
  'TNFSF9',
  'SIK1',
  'ATF3',
  'SERPINE1',
  'MYC',
  'HES1',
  'CCN1',
  'CCNL1',
  'EGR1',
  'EGR2',
  'EGR3',
  'JAG1',
  'ABCA1',
  'GADD45B',
  'GADD45A',
  'KLF10',
  'PLK2',
  'EIF1',
  'EHD1',
  'FOSL2',
  'FOSL1',
  'GPR183',
  'PLPP3',
  'IFIT2',
  'ICAM1',
  'ZC3H12A',
  'IER2',
  'IL12B',
  'IER5',
  'JUNB',
  'IER3',
  'STAT5A',
  'DUSP5',
  'EDN1',
  'DUSP4',
  'JUN',
  'DUSP1',
  'DUSP2',
  'TSC22D1',
  'CCL20',
  'SPHK1',
  'LIF',
  'IL18',
  'TUBB2A',
  'RHOB',
  'VEGFA',
  'IL1A',
  'PTPRE',
  'TLR2',
  'IL1B',
  'BHLHE40',
  'CLCF1',
  'ID2',
  'REL',
  'FJX1',
  'SGK1',
  'BTG3',
  'BTG2',
  'BTG1',
  'SDC4',
  'LITAF',
  'AREG',
  'SOCS3',
  'PANX1',
  'RIPK2',
  'NFIL3',
  'SERPINB2',
  'GCH1',
  'IFNGR2',
  'G0S2',
  'FOS',
  'F3',
  'SERPINB8',
  'SPSB1',
  'FOSB',
  'PER1',
  'F2RL1',
  'HBEGF',
  'CD44',
  'TRIP10',
  'CDKN1A',
  'PTGER4',
  'PTGS2',
  'IFIH1',
  'NAMPT',
  'OLR1',
  'ICOSLG',
  'PHLDA1',
  'ZBTB10',
  'TAP1',
  'PNRC1',
  'CXCL10',
  'CXCL11',
  'IL6ST',
  'CD69',
  'SQSTM1',
  'RELA',
  'CD83',
  'CSF2',
  'CSF1',
  'CD80',
  'PPP1R15A',
  'TNC',
  'TNF',
  'RELB',
  'TANK',
  'ZFP36',
  'CCND1',
  'RNF19B',
  'CCRL2',
  'DENND5A',
  'MAP3K8',
  'PHLDA2',
  'LDLR',
  'SLC16A6',
  'SMAD3',
  'TGIF1',
  'MAP2K3',
  'DDX58',
  'INHBA',
  'TRAF1',
  'NFKB1',
  'NFKB2',
  'GEM',
  'MAFF',
  'NR4A3',
  'RCAN1',
  'EFNA1',
  'NR4A2',
  'MXD1',
  'BIRC2',
  'BIRC3',
  'YRDC',
  'IL7R',
  'PFKFB3',
  'IRS2',
  'SLC2A3',
  'PLAU',
  'SAT1',
  'SLC2A6',
  'ETS2',
  'NR4A1',
  'SNN',
  'PMEPA1',
  'TNFRSF9',
  'MSC',
  'TIPARP',
  'LAMB3',
  'GFPT2',
  'CFLAR',
  'TNIP1',
  'IRF1',
  'NFKBIA',
  'BMP2',
  'IL6',
  'TNIP2',
  'BCL6',
  'BCL3',
  'NFKBIE',
  'NFE2L2',
  'B4GALT1',
  'NFAT5',
  'BCL2A1',
  'TNFAIP8',
  'TNFAIP6',
  'TNFAIP3',
  'CXCL2',
  'CXCL1',
  'TNFAIP2',
  'CXCL3',
  'CXCL6',
  'FUT4',
  'DRAM1',
  'DNAJB4',
  'PDE4B',
  'PDLIM5',
  'MCL1',
  'KDM6B',
  'IL15RA',
  'PLAUR',
  'ATP2B1',
  'KLF4',
  'KLF2',
  'SOD2',
  'KLF9',
  'KLF6',
  'ACKR3',
  'PTX3',
  'B4GALT5',
  'TRIB1',
  'CEBPB',
  'CEBPD',
  'PLEK',
  'CCL5',
  'KYNU',
  'CCL4',
  'CCL2'],
 'Hypoxia': ['WSB1',
  'JMJD6',
  'XPNPEP1',
  'RRAGD',
  'PPP1R3C',
  'MT1E',
  'TES',
  'ATF3',
  'SERPINE1',
  'GLRX',
  'UGP2',
  'NOCT',
  'MXI1',
  'DPYSL4',
  'CCN5',
  'CCN2',
  'PPARGC1A',
  'CCN1',
  'DTNA',
  'SIAH2',
  'MIF',
  'PRKCA',
  'EXT1',
  'FOSL2',
  'SLC6A6',
  'SULT2B1',
  'BCAN',
  'LALBA',
  'CHST2',
  'SDC2',
  'HOXB9',
  'CHST3',
  'LXN',
  'NEDD4L',
  'PDGFB',
  'ENO1',
  'ENO2',
  'ENO3',
  'RBPJ',
  'MT2A',
  'PLAC8',
  'PRDX5',
  'HMOX1',
  'PDK1',
  'IER3',
  'PDK3',
  'EDN2',
  'ANXA2',
  'JUN',
  'DUSP1',
  'TPI1',
  'AMPD3',
  'CP',
  'VEGFA',
  'P4HA1',
  'P4HA2',
  'BHLHE40',
  'CCNG2',
  'PAM',
  'ALDOC',
  'ALDOB',
  'ALDOA',
  'GPI',
  'BTG1',
  'CITED2',
  'SDC3',
  'SDC4',
  'STC1',
  'ADM',
  'STC2',
  'VLDLR',
  'BRS3',
  'LDHC',
  'LDHA',
  'CSRP2',
  'IDS',
  'NFIL3',
  'PCK1',
  'TPD52',
  'PKLR',
  'PGAM2',
  'GAA',
  'FOS',
  'BGN',
  'F3',
  'TPST2',
  'ANGPTL4',
  'PLIN2',
  'INHA',
  'ERRFI1',
  'SRPX',
  'CDKN1B',
  'CDKN1C',
  'ERO1A',
  'HEXA',
  'CDKN1A',
  'NCAN',
  'GBE1',
  'GCNT2',
  'PYGM',
  'GYS1',
  'NDST2',
  'NDST1',
  'AKAP12',
  'STBD1',
  'CXCR4',
  'CA12',
  'HS3ST1',
  'MAP3K1',
  'TGFB3',
  'CAVIN1',
  'CAVIN3',
  'KLHL24',
  'PNRC1',
  'SAP30',
  'GCK',
  'ILVBL',
  'COL5A1',
  'TGFBI',
  'GAPDHS',
  'S100A4',
  'PKP1',
  'PPP1R15A',
  'HDLBP',
  'EGFR',
  'FOXO3',
  'NDRG1',
  'KIF5A',
  'ZFP36',
  'GPC1',
  'HAS1',
  'GPC4',
  'GPC3',
  'PPFIA4',
  'IGFBP1',
  'BNIP3L',
  'IGFBP3',
  'B3GALT6',
  'PGF',
  'MAFF',
  'EFNA1',
  'ISG20',
  'EFNA3',
  'LOX',
  'PFKFB3',
  'IRS2',
  'SLC2A1',
  'AK4',
  'SLC2A3',
  'SLC2A5',
  'ETS1',
  'RORA',
  'TGM2',
  'FAM162A',
  'PIM1',
  'ANKZF1',
  'TIPARP',
  'HSPA5',
  'CAV1',
  'GALK1',
  'GRHPR',
  'IL6',
  'ADORA2B',
  'MYH9',
  'BCL2',
  'FBP1',
  'TMEM45A',
  'SLC25A1',
  'TNFAIP3',
  'HK1',
  'HK2',
  'CASP6',
  'PGK1',
  'B4GALNT2',
  'SLC37A4',
  'TKTL1',
  'TPBG',
  'PLAUR',
  'DCN',
  'SELENBP1',
  'KLF7',
  'NAGK',
  'KLF6',
  'PFKL',
  'DDIT4',
  'DDIT3',
  'ACKR3',
  'KDELR3',
  'GAPDH',
  'PFKP',
  'KDM3A',
  'ZNF292',
  'NR3C1',
  'PHKG1',
  'VHL',
  'ATP7A',
  'PGM2',
  'SCARB1',
  'LARGE1',
  'PGM1'],
 'Cholesterol Homeostasis': ['STARD4',
  'GSTM2',
  'CHKA',
  'HMGCS1',
  'TNFRSF12A',
  'ANXA5',
  'ECH1',
  'GPX8',
  'PNRC1',
  'CPEB2',
  'SCD',
  'CD9',
  'ETHE1',
  'ALDOC',
  'DHCR7',
  'IDI1',
  'ATF3',
  'CLU',
  'HSD17B7',
  'ANTXR2',
  'CXCL16',
  'ACAT2',
  'ATXN2',
  'PMVK',
  'SC5D',
  'MAL2',
  'STX5',
  'NFIL3',
  'ACSS2',
  'FDFT1',
  'LDLR',
  'S100A11',
  'ABCA2',
  'FDPS',
  'NIBAN1',
  'SREBF2',
  'JAG1',
  'CYP51A1',
  'PCYT2',
  'ANXA13',
  'TP53INP1',
  'AVPR1A',
  'LSS',
  'PLAUR',
  'SQLE',
  'FABP5',
  'PLSCR1',
  'FASN',
  'LGMN',
  'PPARG',
  'MVD',
  'TRIB3',
  'ATF5',
  'ERRFI1',
  'MVK',
  'GLDC',
  'CTNNB1',
  'LPL',
  'SEMA3B',
  'ACTG1',
  'HMGCR',
  'TMEM97',
  'GNAI1',
  'TM7SF2',
  'ADH4',
  'CBS',
  'LGALS3',
  'EBP',
  'NSDHL',
  'ALCAM',
  'FBXO6',
  'GUSB',
  'FADS2',
  'PDK3'],
 'Mitotic Spindle': ['ACTN4',
  'PCGF5',
  'APC',
  'MARCKS',
  'NIN',
  'KIF20B',
  'EPB41',
  'STAU1',
  'CD2AP',
  'UXT',
  'PPP4R2',
  'CSNK1D',
  'RACGAP1',
  'CDC27',
  'PREX1',
  'STK38L',
  'ARFIP2',
  'PLK1',
  'BCR',
  'LATS1',
  'CCDC88A',
  'TPX2',
  'BIN1',
  'NET1',
  'SASS6',
  'EZR',
  'TRIO',
  'ITSN1',
  'NUMA1',
  'SMC4',
  'SMC3',
  'ABR',
  'EPB41L2',
  'CDK5RAP2',
  'CEP72',
  'KIFAP3',
  'CEP192',
  'SYNPO',
  'RHOF',
  'LRPPRC',
  'ANLN',
  'CENPE',
  'CENPF',
  'INCENP',
  'CENPJ',
  'PAFAH1B1',
  'ARHGEF2',
  'ARHGEF3',
  'RAPGEF6',
  'KPTN',
  'ARHGEF7',
  'RAPGEF5',
  'RABGAP1',
  'KIF11',
  'PIF1',
  'TOP2A',
  'KIF15',
  'NEDD9',
  'RASAL2',
  'BRCA2',
  'CNTRL',
  'KIF1B',
  'SPTBN1',
  'CEP57',
  'DLGAP5',
  'MAP1S',
  'SORBS2',
  'DYNLL2',
  'MYO9B',
  'FARP1',
  'RANBP9',
  'SEPTIN9',
  'CLIP2',
  'CLIP1',
  'CTTN',
  'TAOK2',
  'LLGL1',
  'ARF6',
  'DYNC1H1',
  'MAPRE1',
  'RAB3GAP1',
  'ALMS1',
  'TUBD1',
  'WASL',
  'AKAP13',
  'PCM1',
  'OPHN1',
  'NUSAP1',
  'RICTOR',
  'SPTAN1',
  'GSN',
  'RALBP1',
  'ARHGAP29',
  'TSC1',
  'ARHGAP27',
  'MID1',
  'TUBA4A',
  'ABI1',
  'KIF4A',
  'TUBGCP6',
  'ARL8A',
  'TUBGCP5',
  'CNTROB',
  'ROCK1',
  'GEMIN4',
  'AURKA',
  'KATNB1',
  'FGD4',
  'BCL2L11',
  'FGD6',
  'KIF5B',
  'CEP250',
  'FLNA',
  'CLASP1',
  'FLNB',
  'KNTC1',
  'MYH10',
  'PCNT',
  'ARHGEF12',
  'ARHGEF11',
  'KIF22',
  'TBCD',
  'KIF23',
  'CKAP5',
  'NDC80',
  'SSH2',
  'DLG1',
  'ARHGAP10',
  'CDC42EP4',
  'BIRC5',
  'CDC42EP2',
  'FSCN1',
  'MAP3K11',
  'CDC42EP1',
  'KIF2C',
  'VCL',
  'DOCK4',
  'NOTCH2',
  'PXN',
  'TUBGCP2',
  'TUBGCP3',
  'ARHGAP4',
  'ARHGAP5',
  'CCNB2',
  'KIF3C',
  'KIF3B',
  'NEK2',
  'ABL1',
  'MARK4',
  'SAC3D1',
  'SUN2',
  'ARFGEF1',
  'RFC1',
  'ARAP3',
  'SHROOM1',
  'SHROOM2',
  'CDC42BPA',
  'SMC1A',
  'RASA1',
  'HOOK3',
  'ESPL1',
  'RASA2',
  'MYH9',
  'CDK1',
  'NF1',
  'ATG4B',
  'DOCK2',
  'BCAR1',
  'SOS1',
  'YWHAE',
  'LMNB1',
  'KLC1',
  'RHOT2',
  'CAPZB',
  'ECT2',
  'WASF1',
  'WASF2',
  'PDLIM5',
  'PLEKHG2',
  'DST',
  'CEP131',
  'MID1IP1',
  'KATNA1',
  'PRC1',
  'TIAM1',
  'CDC42',
  'MYO1E',
  'PALLD',
  'ALS2',
  'HDAC6',
  'TTK',
  'PKD2',
  'ARHGDIA',
  'FBXO5',
  'TLK1',
  'BUB1',
  'CYTH2',
  'NCK1',
  'NCK2'],
 'Wnt-beta Catenin Signaling': ['FZD1',
  'JAG1',
  'JAG2',
  'FZD8',
  'WNT5B',
  'AXIN2',
  'AXIN1',
  'PTCH1',
  'CSNK1E',
  'DKK1',
  'DKK4',
  'ADAM17',
  'KAT2A',
  'NCOR2',
  'TCF7',
  'PPARD',
  'TP53',
  'NUMB',
  'HDAC5',
  'LEF1',
  'NOTCH4',
  'NOTCH1',
  'HDAC11',
  'HDAC2',
  'CTNNB1',
  'MAML1',
  'CUL1',
  'PSEN2',
  'DLL1',
  'GNAI1',
  'NKD1',
  'RBPJ',
  'WNT6',
  'FRAT1',
  'CCND2',
  'HEY2',
  'HEY1',
  'DVL2',
  'MYC',
  'WNT1',
  'NCSTN',
  'SKP2'],
 'TGF-beta Signaling': ['TGFB1',
  'ACVR1',
  'RHOA',
  'SMURF2',
  'SMURF1',
  'HIPK2',
  'TGFBR1',
  'PPP1CA',
  'CDK9',
  'SKI',
  'RAB31',
  'APC',
  'BMP2',
  'NCOR2',
  'ID1',
  'ID3',
  'ID2',
  'BMPR1A',
  'BCAR3',
  'BMPR2',
  'SERPINE1',
  'UBE2D3',
  'PPP1R15A',
  'ARID4B',
  'CDH1',
  'MAP3K7',
  'SKIL',
  'SPTBN1',
  'SMAD3',
  'WWTR1',
  'TGIF1',
  'LEFTY2',
  'NOG',
  'IFNGR2',
  'SMAD1',
  'KLF10',
  'SMAD7',
  'SMAD6',
  'PPM1A',
  'FKBP1A',
  'TJP1',
  'XIAP',
  'ENG',
  'TRIM33',
  'CDKN1C',
  'HDAC1',
  'FURIN',
  'CTNNB1',
  'SLC20A1',
  'THBS1',
  'LTBP2',
  'FNTA',
  'PMEPA1',
  'JUNB'],
 'IL-6/JAK/STAT3 Signaling': ['PTPN1',
  'TGFB1',
  'CCR1',
  'PTPN2',
  'IL4R',
  'JUN',
  'IL1R1',
  'IL1R2',
  'ITGA4',
  'TNFRSF12A',
  'IL10RB',
  'PLA2G2A',
  'DNTT',
  'PTPN11',
  'TYK2',
  'OSMR',
  'TNFRSF1A',
  'TNFRSF1B',
  'CXCL10',
  'HAX1',
  'TLR2',
  'CXCL11',
  'IL1B',
  'IRF1',
  'TNFRSF21',
  'IL7',
  'CXCL13',
  'IL6',
  'CD9',
  'FAS',
  'IL3RA',
  'IL9R',
  'IRF9',
  'IL6ST',
  'PF4',
  'STAM2',
  'CRLF2',
  'IL18R1',
  'CNTFR',
  'ACVRL1',
  'CSF3R',
  'CXCL9',
  'CSF2',
  'CSF1',
  'EBI3',
  'PIK3R5',
  'TNF',
  'CXCL1',
  'IL2RG',
  'CXCL3',
  'SOCS3',
  'SOCS1',
  'CD38',
  'CD36',
  'IL12RB1',
  'MAP3K8',
  'IL17RA',
  'IL15RA',
  'IFNGR1',
  'STAT1',
  'IFNGR2',
  'STAT2',
  'STAT3',
  'INHBE',
  'IL17RB',
  'MYD88',
  'LTBR',
  'IL2RA',
  'LTB',
  'GRB2',
  'IFNAR1',
  'CD44',
  'REG1A',
  'ITGB3',
  'PDGFC',
  'CSF2RA',
  'ACVR1B',
  'CBL',
  'CSF2RB',
  'CCL7',
  'HMOX1',
  'LEPR',
  'PIM1',
  'BAK1',
  'A2M',
  'CD14',
  'IL13RA1'],
 'DNA Repair': ['DUT',
  'BRF2',
  'LIG1',
  'PDE6G',
  'ALYREF',
  'UPF3B',
  'GTF2F1',
  'RBX1',
  'TARBP2',
  'POLR3C',
  'POLE4',
  'SRSF6',
  'EIF1B',
  'CDA',
  'TP53',
  'VPS28',
  'PCNA',
  'MPG',
  'RNMT',
  'RALA',
  'GTF2B',
  'TYMS',
  'ADCY6',
  'PNP',
  'TAF1C',
  'ZNF707',
  'CLP1',
  'NT5C',
  'RAE1',
  'STX3',
  'SMAD5',
  'SURF1',
  'VPS37D',
  'VPS37B',
  'SUPT5H',
  'SDCBP',
  'BCAM',
  'NT5C3A',
  'ITPA',
  'HPRT1',
  'CCNO',
  'TSG101',
  'POM121',
  'COX17',
  'ARL6IP1',
  'AK1',
  'CSTF3',
  'AK3',
  'XPC',
  'AAAS',
  'DGUOK',
  'MPC2',
  'NELFE',
  'NELFB',
  'SAC3D1',
  'GSDME',
  'RFC4',
  'RFC5',
  'NCBP2',
  'POLR3GL',
  'RFC2',
  'GPX4',
  'RFC3',
  'NME3',
  'EDF1',
  'NME4',
  'ZWINT',
  'NME1',
  'POLA1',
  'POLA2',
  'AGO4',
  'NFX1',
  'RRM2B',
  'ADA',
  'UMPS',
  'GTF2A2',
  'GTF3C5',
  'CETN2',
  'ELL',
  'NPR2',
  'SUPT4H1',
  'MRPL40',
  'ZNRD1',
  'SNAPC4',
  'SNAPC5',
  'NELFCD',
  'PDE4B',
  'DGCR8',
  'TMED2',
  'TK2',
  'BCAP31',
  'SF3A3',
  'TAF13',
  'ADRM1',
  'TAF12',
  'BOLA2',
  'RPA2',
  'GTF2H1',
  'RPA3',
  'TAF10',
  'SSRP1',
  'GTF2H3',
  'GTF2H5',
  'APRT',
  'DDB2',
  'DDB1',
  'ERCC1',
  'NUDT21',
  'RAD51',
  'NUDT9',
  'RAD52',
  'ERCC4',
  'ERCC5',
  'IMPDH2',
  'DAD1',
  'ERCC2',
  'POLR1C',
  'ERCC3',
  'POLR1D',
  'CMPK2',
  'ERCC8',
  'HCLS1',
  'TAF9',
  'TAF6',
  'FEN1',
  'CANT1',
  'GMPR2',
  'USP11',
  'DCTN4',
  'PRIM1',
  'POLD4',
  'POLB',
  'GUK1',
  'POLR2A',
  'POLD1',
  'POLR2C',
  'POLR2D',
  'SEC61A1',
  'POLD3',
  'POLR2E',
  'ELOA',
  'POLR2F',
  'POLR2G',
  'POLR2H',
  'POLL',
  'POLR2I',
  'POLR2J',
  'POLR2K',
  'POLH',
  'REV3L'],
 'G2-M Checkpoint': ['H2AZ2',
  'CASP8AP2',
  'EGF',
  'H2AZ1',
  'KNL1',
  'SLC12A2',
  'HUS1',
  'CDC20',
  'MAPK14',
  'PML',
  'DDX39A',
  'MARCKS',
  'NUP98',
  'HNRNPD',
  'KIF20B',
  'CCNF',
  'HNRNPU',
  'NOLC1',
  'EWSR1',
  'CHEK1',
  'RACGAP1',
  'CDC27',
  'RAD54L',
  'SNRPD1',
  'E2F1',
  'MYC',
  'E2F2',
  'E2F3',
  'E2F4',
  'PLK4',
  'PLK1',
  'SQLE',
  'STAG1',
  'TPX2',
  'UCK2',
  'EZH2',
  'ATF5',
  'JPT1',
  'NUMA1',
  'HIF1A',
  'SMC4',
  'SMC2',
  'GSPT1',
  'TMPO',
  'MT2A',
  'SYNCRIP',
  'STMN1',
  'MYBL2',
  'BARD1',
  'SS18',
  'UPF1',
  'CDC7',
  'CDC6',
  'CENPE',
  'SLC7A5',
  'CENPF',
  'INCENP',
  'MTF2',
  'PAFAH1B1',
  'CDKN3',
  'DTYMK',
  'KIF11',
  'YTHDC1',
  'SUV39H1',
  'TOP2A',
  'KIF15',
  'RASAL2',
  'BRCA2',
  'CTCF',
  'SLC7A1',
  'HOXC10',
  'PBK',
  'MAP3K20',
  'CDKN2C',
  'PRMT5',
  'RPA2',
  'TRAIP',
  'CKS2',
  'TACC3',
  'H2AX',
  'CDKN1B',
  'PRIM2',
  'MKI67',
  'CENPA',
  'XPO1',
  'WRN',
  'DMD',
  'NUSAP1',
  'SRSF10',
  'GINS2',
  'TGFB1',
  'TLE3',
  'UBE2C',
  'CDC25A',
  'PRPF4B',
  'LIG3',
  'ILF3',
  'CDC25B',
  'SAP30',
  'DKC1',
  'UBE2S',
  'KIF4A',
  'PTTG3P',
  'MAD2L1',
  'CCNT1',
  'ODC1',
  'SRSF1',
  'SRSF2',
  'ARID4A',
  'AURKA',
  'EFNA5',
  'HIRA',
  'AURKB',
  'CCND1',
  'NSD2',
  'PURA',
  'KIF5B',
  'PTTG1',
  'KMT5A',
  'HMGN2',
  'KPNA2',
  'SMAD3',
  'SLC38A1',
  'KIF22',
  'ODF2',
  'STIL',
  'FANCC',
  'KIF23',
  'NASP',
  'FOXN3',
  'NDC80',
  'CCNA2',
  'TFDP1',
  'NCL',
  'BIRC5',
  'TROAP',
  'KIF2C',
  'MNAT1',
  'NOTCH2',
  'CUL5',
  'CUL3',
  'CUL1',
  'PDS5B',
  'CHAF1A',
  'CCNB2',
  'G3BP1',
  'CHMP1A',
  'NEK2',
  'ABL1',
  'DR1',
  'HSPA8',
  'CBX1',
  'RAD23B',
  'HMGA1',
  'SMC1A',
  'CUL4A',
  'NUP50',
  'POLA2',
  'MEIS2',
  'RBL1',
  'MEIS1',
  'ESPL1',
  'SFPQ',
  'CDK4',
  'H2BC12',
  'BCL3',
  'CDK1',
  'MCM5',
  'MCM6',
  'TOP1',
  'MCM2',
  'MCM3',
  'AMD1',
  'CKS1B',
  'HMGB3',
  'HMMR',
  'LMNB1',
  'TENT4A',
  'ORC6',
  'ORC5',
  'RAD21',
  'LBR',
  'TNPO2',
  'RBM14',
  'SMARCC1',
  'ATRX',
  'POLQ',
  'KATNA1',
  'PRC1',
  'KPNB1',
  'DBF4',
  'TTK',
  'RPS6KA5',
  'CDC45',
  'POLE',
  'EXO1',
  'TRA2B',
  'FBXO5',
  'BUB3',
  'BUB1'],
 'Apoptosis': ['GSN',
  'PDGFRB',
  'BIK',
  'LUM',
  'TGFB2',
  'GSR',
  'TAP1',
  'CDC25B',
  'EREG',
  'MADD',
  'CD2',
  'FEZ1',
  'FAS',
  'CTH',
  'BAX',
  'PDCD4',
  'CD69',
  'SQSTM1',
  'APP',
  'DAP3',
  'LEF1',
  'ATF3',
  'RELA',
  'IFITM3',
  'ROCK1',
  'SATB1',
  'RETSAT',
  'CLU',
  'TNF',
  'LMNA',
  'BCL2L11',
  'PAK1',
  'CCND2',
  'BCL2L10',
  'CCND1',
  'SC5D',
  'CREBBP',
  'IGF2R',
  'EGR3',
  'F2R',
  'IGFBP6',
  'GADD45B',
  'BNIP3L',
  'GADD45A',
  'HGF',
  'AVPR1A',
  'H1-0',
  'SMAD7',
  'PTK2',
  'ISG20',
  'CCNA1',
  'BCL2L1',
  'PPT1',
  'BIRC3',
  'BCL2L2',
  'BCL10',
  'PRF1',
  'PSEN1',
  'ENO2',
  'FASLG',
  'PLAT',
  'PSEN2',
  'SAT1',
  'PPP3R1',
  'LGALS3',
  'EBP',
  'ANKH',
  'FDXR',
  'HMOX1',
  'PMAIP1',
  'BMF',
  'TNFSF10',
  'CD14',
  'IER3',
  'DNM1L',
  'GPX1',
  'ANXA1',
  'GPX3',
  'JUN',
  'GSTM1',
  'GPX4',
  'MMP2',
  'TNFRSF12A',
  'CAV1',
  'CFLAR',
  'EMP1',
  'PPP2R5B',
  'IL18',
  'RHOB',
  'TGFBR3',
  'IL1A',
  'DNAJC3',
  'IL1B',
  'IRF1',
  'CYLD',
  'BMP2',
  'DAP',
  'IL6',
  'KRT18',
  'DPYD',
  'CDK2',
  'ETF1',
  'RARA',
  'GUCY2D',
  'BTG3',
  'BTG2',
  'DIABLO',
  'TOP2A',
  'PEA15',
  'BRCA1',
  'NEDD9',
  'HMGB2',
  'HSPB1',
  'CASP8',
  'CASP9',
  'RHOT2',
  'CASP6',
  'CASP7',
  'CASP4',
  'ERBB2',
  'ERBB3',
  'CASP2',
  'TIMP3',
  'CASP3',
  'CD38',
  'TIMP1',
  'CASP1',
  'TIMP2',
  'MCL1',
  'BCAP31',
  'DFFA',
  'IFNGR1',
  'MGMT',
  'GCH1',
  'BGN',
  'F2',
  'SOD1',
  'DCN',
  'SOD2',
  'DNAJA1',
  'WEE1',
  'XIAP',
  'TXNIP',
  'DDIT3',
  'VDAC2',
  'PLCB2',
  'CD44',
  'CDKN1B',
  'RNASEL',
  'CDKN1A',
  'PLPPR4',
  'CTNNB1',
  'SLC20A1',
  'ADD1',
  'GNA15',
  'AIFM3',
  'IFNB1',
  'TSPO',
  'NEFH',
  'SPTAN1',
  'BID'],
 'Notch Signaling': ['FZD1',
  'PSENEN',
  'JAG1',
  'TCF7L2',
  'FBXW11',
  'FZD5',
  'WNT5A',
  'FZD7',
  'PRKCA',
  'HEYL',
  'RBX1',
  'SAP30',
  'KAT2A',
  'PPARD',
  'NOTCH3',
  'NOTCH1',
  'NOTCH2',
  'MAML2',
  'DTX1',
  'CUL1',
  'DTX2',
  'DTX4',
  'PSEN2',
  'DLL1',
  'APH1A',
  'LFNG',
  'ARRB1',
  'CCND1',
  'ST3GAL6',
  'HES1',
  'WNT2',
  'SKP1'],
 'Adipogenesis': ['ECH1',
  'CIDEA',
  'PEX14',
  'LEP',
  'UQCRC1',
  'SPARCL1',
  'PREB',
  'SUCLG1',
  'ITIH5',
  'RETSAT',
  'UQCR10',
  'GHITM',
  'RETN',
  'ARAF',
  'UQCR11',
  'TOB1',
  'ADCY6',
  'SLC5A6',
  'SNCG',
  'STOM',
  'COX8A',
  'FZD4',
  'ABCA1',
  'OMD',
  'GADD45A',
  'TALDO1',
  'RMDN3',
  'CMBL',
  'POR',
  'UCK1',
  'SSPN',
  'CD302',
  'PEMT',
  'NMT1',
  'ITSN1',
  'BAZ2A',
  'MGST3',
  'MRPL15',
  'MYLK',
  'C3',
  'PRDX3',
  'SULT1A1',
  'LIPE',
  'GRPEL1',
  'SCP2',
  'APOE',
  'SLC19A1',
  'DECR1',
  'STAT5A',
  'CS',
  'VEGFB',
  'CCNG2',
  'MRAP',
  'ALDOA',
  'MGLL',
  'COX7B',
  'MTARC2',
  'ADIPOR2',
  'ECHS1',
  'NKIRAS1',
  'CD36',
  'ADIG',
  'ADIPOQ',
  'MAP4K3',
  'CDKN2C',
  'IFNGR1',
  'MDH2',
  'DGAT1',
  'ELOVL6',
  'ELMOD3',
  'MCCC1',
  'SQOR',
  'SORBS1',
  'DHRS7',
  'COL4A1',
  'FABP4',
  'ESYT1',
  'GPAM',
  'NDUFAB1',
  'LPCAT3',
  'ANGPTL4',
  'ATP5PO',
  'PPARG',
  'DLD',
  'PLIN2',
  'TKT',
  'CMPK1',
  'ORM1',
  'SLC66A3',
  'ATL2',
  'PTGER3',
  'GBE1',
  'SAMM50',
  'ACADM',
  'ACADL',
  'AIFM1',
  'ENPP2',
  'DLAT',
  'GPAT4',
  'RIOK3',
  'ACADS',
  'CAVIN1',
  'PHYH',
  'PTCD3',
  'CAVIN2',
  'APLP2',
  'ATP1B3',
  'LIFR',
  'SDHB',
  'FAH',
  'SDHC',
  'RAB34',
  'UQCRQ',
  'GPD2',
  'PDCD4',
  'DHCR7',
  'CRAT',
  'PPP1R15B',
  'PHLDB1',
  'SLC27A1',
  'UCP2',
  'SLC1A5',
  'TANK',
  'COX6A1',
  'BCL2L13',
  'ESRRA',
  'IDH1',
  'NABP1',
  'EPHX2',
  'CHCHD10',
  'DNAJC15',
  'ACLY',
  'QDPR',
  'REEP6',
  'REEP5',
  'PFKFB3',
  'CD151',
  'LPL',
  'AK2',
  'UBC',
  'G3BP2',
  'PIM3',
  'ACAA2',
  'CYC1',
  'HADH',
  'BCKDHA',
  'GPX3',
  'JAGN1',
  'ANGPT1',
  'GPX4',
  'COQ9',
  'COQ5',
  'COQ3',
  'BCL6',
  'ACOX1',
  'NDUFS3',
  'ACO2',
  'ITGA7',
  'ARL4A',
  'RTN3',
  'SLC25A1',
  'YWHAG',
  'NDUFB7',
  'ABCB8',
  'HSPB8',
  'DHRS7B',
  'AGPAT3',
  'DRAM2',
  'DBT',
  'CPT2',
  'ME1',
  'DNAJB9',
  'RREB1',
  'HIBCH',
  'IDH3G',
  'MIGA2',
  'CHUK',
  'NDUFA5',
  'CYP4B1',
  'IMMT',
  'SOD1',
  'PPM1B',
  'PFKL',
  'CAT',
  'TST',
  'SLC25A10',
  'MTCH2',
  'RNF11',
  'SOWAHC',
  'COL15A1',
  'LAMA4',
  'ETFB',
  'GPHN',
  'LTC4S',
  'DDT',
  'ALDH2',
  'UBQLN1',
  'IDH3A',
  'SCARB1',
  'PGM1'],
 'Estrogen Response Early': ['TTC39A',
  'AMFR',
  'KRT8',
  'MED13L',
  'GLA',
  'NBL1',
  'RETREG1',
  'AKAP1',
  'ADCY1',
  'PEX11A',
  'ADCY9',
  'AQP3',
  'ABAT',
  'TOB1',
  'MUC1',
  'MYB',
  'MYC',
  'CCN5',
  'HES1',
  'FDFT1',
  'ABCA3',
  'EGR3',
  'XBP1',
  'BCL11B',
  'KLF10',
  'SIAH2',
  'PLAAT3',
  'CBFA2T3',
  'OVOL2',
  'PDZK1',
  'IL17RB',
  'AR',
  'SULT2B1',
  'FASN',
  'UNC119',
  'PTGES',
  'SLC22A5',
  'RAPGEFL1',
  'TSKU',
  'SOX3',
  'GJA1',
  'INPP5F',
  'SFN',
  'MYBL1',
  'SLC19A2',
  'GREB1',
  'ITPK1',
  'MYOF',
  'GAB2',
  'KRT13',
  'FAM102A',
  'KLK10',
  'RHOD',
  'SLC7A5',
  'KRT19',
  'NCOR2',
  'TUBB2B',
  'KRT18',
  'MAPT',
  'MPPED2',
  'BHLHE40',
  'KRT15',
  'TFF3',
  'RARA',
  'TFF1',
  'RET',
  'FOXC1',
  'ABHD2',
  'ENDOD1',
  'STC2',
  'TMPRSS3',
  'AREG',
  'SLC7A2',
  'TMEM164',
  'UGCG',
  'SEC14L2',
  'CLIC3',
  'ELOVL2',
  'SVIL',
  'ELOVL5',
  'FOS',
  'SNX24',
  'GFRA1',
  'DHRS2',
  'DHRS3',
  'FARP1',
  'MYBBP1A',
  'DLC1',
  'CD44',
  'TJP3',
  'LAD1',
  'PRSS23',
  'OLFML3',
  'TBC1D30',
  'ANXA9',
  'RRP12',
  'DEPTOR',
  'JAK2',
  'CA12',
  'TFAP2C',
  'MREG',
  'SLC16A1',
  'NPY1R',
  'KAZN',
  'OLFM1',
  'CXCL12',
  'RAB31',
  'PPIF',
  'IL6ST',
  'DHCR7',
  'FKBP5',
  'FKBP4',
  'FRK',
  'SLC27A2',
  'CELSR1',
  'SLC1A1',
  'SCNN1A',
  'HR',
  'SLC1A4',
  'ASB13',
  'CELSR2',
  'PAPSS2',
  'ABLIM1',
  'CCND1',
  'FLNB',
  'SH3BP5',
  'SLC39A6',
  'RBBP8',
  'MICB',
  'OPN3',
  'TGIF2',
  'WFS1',
  'CISH',
  'IGFBP4',
  'INHBB',
  'SLC9A3R1',
  'MED24',
  'REEP1',
  'PGR',
  'BLVRB',
  'FCMR',
  'SLC26A2',
  'WWC1',
  'MINDY1',
  'SLC2A1',
  'ARL3',
  'ISG20L2',
  'IGF1R',
  'RHOBTB3',
  'TGM2',
  'CALCR',
  'RASGRP1',
  'PODXL',
  'BAG1',
  'ALDH3B1',
  'PMAIP1',
  'SYBU',
  'SLC37A1',
  'KDM4B',
  'TIPARP',
  'NAV2',
  'ELF1',
  'ELF3',
  'CHPT1',
  'ESRP2',
  'BCL2',
  'KCNK5',
  'B4GALT1',
  'MAST4',
  'HSPB8',
  'AFF1',
  'SYNGR1',
  'CALB2',
  'CYP26B1',
  'PDLIM3',
  'NRIP1',
  'P2RY2',
  'ZNF185',
  'DYNLT3',
  'TPBG',
  'KCNK15',
  'KLF4',
  'TIAM1',
  'TPD52L1',
  'CLDN7',
  'MLPH',
  'SYT12',
  'RAB17',
  'SLC24A3',
  'CANT1',
  'NXT1',
  'SEMA3B',
  'FHL2',
  'ADD3',
  'NADSYN1',
  'THSD4',
  'RPS6KA2',
  'LRIG1',
  'MSMB',
  'SCARB1'],
 'Estrogen Response Late': ['UNC13B',
  'HOMER2',
  'CACNA2D2',
  'AMFR',

In [65]:
import os
import json
from pathlib import Path
from typing import List, Dict, Any, Optional
import pandas as pd

# Import singscore functions (adjust path if your package layout differs)
from singscore.singscore import *

def extract_single_numeric_from_df(df: pd.DataFrame, preferred_cols: Optional[List[str]] = None) -> Optional[float]:
    """
    Extract a single numeric value from a one-row DataFrame.
    pref_cols: list of column name substrings to try in order (case-insensitive)
    """
    if df is None:
        return None
    # if DataFrame has a single row and single numeric column, return it
    try:
        # If one row and one numeric column, return that
        if df.shape[0] == 1:
            numeric_cols = [c for c in df.columns if pd.api.types.is_numeric_dtype(df[c])]
            # If preferred_cols provided, try to find match
            if preferred_cols:
                for pc in preferred_cols:
                    for c in df.columns:
                        if pc.lower() in c.lower() and (pd.api.types.is_numeric_dtype(df[c]) or pd.api.types.is_numeric_dtype(df.iloc[:, df.columns.get_loc(c)])):
                            return float(df.iloc[0][c])
            if numeric_cols:
                return float(df.iloc[0][numeric_cols[0]])
            # else try first column convertible to float
            first_val = df.iloc[0, 0]
            try:
                return float(first_val)
            except Exception:
                return None
        else:
            # more than one row: pick first row and try same logic
            first_row = df.iloc[0:1]
            numeric_cols = [c for c in first_row.columns if pd.api.types.is_numeric_dtype(first_row[c])]
            if numeric_cols:
                return float(first_row[numeric_cols[0]].iloc[0])
            first_val = first_row.iloc[0, 0]
            try:
                return float(first_val)
            except Exception:
                return None
    except Exception:
        return None

def compute_pathway_score_for_upgenes(
    data: pd.DataFrame,
    up_genes: List[str],
    norm_method: str = "theoretical",
    perms: int = 10000
) -> Dict[str, Any]:
    """
    Given expression DataFrame and up_genes list, compute up-only singscore and empirical p-value.
    Returns dict with gene_set_info, scores, statistics.
    """
    # Genes present
    up_present = [g for g in up_genes if g in data.index]
    n_up_used = len(up_present)

    # compute score (up only). down_gene=False per user snippet
    scored = score(up_gene=up_genes, down_gene=False, sample=data, norm_method=norm_method, full_data=False)
    total_score = extract_single_numeric_from_df(scored, preferred_cols=['total_score', 'total'])

    # permutations matched to n_up_used
    permd = permutate(data, n_up=n_up_used, n_down=False, reps=perms, norm_method=norm_method)
    pvals = empiricalpval(permutations=permd, score=scored)
    empirical_p = extract_single_numeric_from_df(pvals, preferred_cols=['empirical', 'p', 'empirical p'])

    result = {
        "gene_set_info": {
            "geneset_size": len(up_genes),
            "geneset_covered_in_sample": n_up_used
        },
        "scores": {
            "total_singscore": total_score
        },
        "statistics": {
            "p_value": empirical_p,
            "method": "permutation (empirical)",
            "permutations": perms
        }
    }
    return result

def run_singscore_on_drug_folder(
    drug_dir: Path,
    entrez_sample_path: str,
    norm_method: str = "theoretical",
    perms: int = 10000,
    output_root: Optional[Path] = None
) -> Dict[str, Any]:
    """
    Given a folder containing {drug}_relevant_pathways.json, read it and compute singscore for each pathway.
    Returns result dict for the drug and writes a JSON file <drug>_singscore_results.json in the drug folder (or output_root).
    """
    # discover json file
    drug_name = drug_dir.name
    in_json = None
    # accept "{drug}_relevant_pathways.json" or anything ending with "_relevant_pathways.json"
    for p in drug_dir.glob("*_relevant_pathways.json"):
        in_json = p
        break
    if in_json is None:
        # fallback: look for exact name
        candidate = drug_dir / f"{drug_name}_relevant_pathways.json"
        if candidate.exists():
            in_json = candidate
    if in_json is None:
        raise FileNotFoundError(f"No '*_relevant_pathways.json' found in {drug_dir}")

    # read expression data once
    if not Path(entrez_sample_path).exists():
        raise FileNotFoundError(f"Expression file not found: {entrez_sample_path}")
    df_expr = pd.read_csv(open(entrez_sample_path, 'r'), header='infer', sep='\t', index_col=0)
    # ensure index matches gene naming used in json (assumes 'GeneName' or similar; user used set_index(keys='GeneName'))
    # If index name is not 'GeneName' but first column is 'GeneName', above already set index_col=0.
    # Convert index to str for safety
    df_expr.index = df_expr.index.map(str)

    # read gene sets json
    with open(in_json, "r", encoding="utf-8") as f:
        pathway_dict = json.load(f)

    result_per_drug: Dict[str, Any] = {}
    for pathway_name, gene_list in pathway_dict.items():
        # gene_list expected to be list of gene symbols/ids
        # compute
        res = compute_pathway_score_for_upgenes(df_expr, gene_list, norm_method=norm_method, perms=perms)
        result_per_drug[pathway_name] = res

    # prepare output path
    if output_root is None:
        out_dir = drug_dir
    else:
        out_dir = Path(output_root) / drug_name
        out_dir.mkdir(parents=True, exist_ok=True)
    out_json = out_dir / f"{drug_name}_singscore_results.json"

    # wrap in top-level dict {Drug: {pathway...}}
    final_output = {drug_name: result_per_drug}
    with open(out_json, "w", encoding="utf-8") as f:
        json.dump(final_output, f, indent=2, ensure_ascii=False)
    print(f"Wrote results for '{drug_name}' to {out_json}")

    return final_output

def batch_run_on_drug_dirs(
    drug_dirs: List[str],
    entrez_sample_path: str,
    norm_method: str = "theoretical",
    perms: int = 10000,
    output_root: Optional[str] = None
) -> Dict[str, Any]:
    """
    Loop over a list of drug directory paths and run scoring for each.
    Returns a combined dict of all results.
    """
    combined = {}
    for d in drug_dirs:
        drug_dir = Path(d)
        if not drug_dir.exists() or not drug_dir.is_dir():
            print(f"Skipping non-directory: {d}")
            continue
        try:
            result = run_singscore_on_drug_folder(drug_dir, entrez_sample_path, norm_method=norm_method, perms=perms, output_root=output_root)
            combined.update(result)
        except Exception as e:
            print(f"Error processing {d}: {e}")
    return combined

In [ ]:
import os
import json
from pathlib import Path
from typing import List, Dict, Any, Optional
import pandas as pd
from tqdm import tqdm  # ✅ added for progress bars

# Import singscore functions (adjust path if needed)
from singscore.singscore import score, permutate, empiricalpval


def extract_single_numeric_from_df(df: pd.DataFrame, preferred_cols: Optional[List[str]] = None) -> Optional[float]:
    """Extract a single numeric value from a one-row DataFrame."""
    if df is None:
        return None
    try:
        if df.shape[0] == 1:
            numeric_cols = [c for c in df.columns if pd.api.types.is_numeric_dtype(df[c])]
            if preferred_cols:
                for pc in preferred_cols:
                    for c in df.columns:
                        if pc.lower() in c.lower() and pd.api.types.is_numeric_dtype(df[c]):
                            return float(df.iloc[0][c])
            if numeric_cols:
                return float(df.iloc[0][numeric_cols[0]])
            return float(df.iloc[0, 0])
        else:
            first_row = df.iloc[0:1]
            numeric_cols = [c for c in first_row.columns if pd.api.types.is_numeric_dtype(first_row[c])]
            if numeric_cols:
                return float(first_row[numeric_cols[0]].iloc[0])
            return float(first_row.iloc[0, 0])
    except Exception:
        return None


def compute_pathway_score_for_upgenes(
    data: pd.DataFrame,
    up_genes: List[str],
    norm_method: str = "theoretical",
    perms: int = 5000
) -> Dict[str, Any]:
    """
    Given expression DataFrame and up_genes list, compute up-only singScore and empirical p-value.
    """
    up_present = [g for g in up_genes if g in data.index]
    n_up_used = len(up_present)

    # Calculate singscore (up only)
    scored = score(up_gene=up_genes, down_gene=False, sample=data, norm_method=norm_method, full_data=False)
    total_score = extract_single_numeric_from_df(scored, preferred_cols=['total_score', 'total'])

    # Calculate permutation-based p-value
    permd = permutate(data, n_up=n_up_used, n_down=False, reps=perms, norm_method=norm_method)
    pvals = empiricalpval(permutations=permd, score=scored)
    empirical_p = extract_single_numeric_from_df(pvals, preferred_cols=['empirical', 'p', 'empirical p'])

    result = {
        "gene_set_info": {
            "geneset_size": len(up_genes),
            "geneset_covered_in_sample": n_up_used
        },
        "scores": {
            "total_singscore": total_score
        },
        "statistics": {
            "p_value": empirical_p,
            "method": "permutation (empirical)",
            "permutations": perms
        }
    }
    return result


def run_singscore_on_drug_folder(
    drug_dir: Path,
    entrez_sample_path: str,
    norm_method: str = "theoretical",
    perms: int = 5000,
    output_root: Optional[Path] = None
) -> Dict[str, Any]:
    """
    Given a folder containing {drug}_relevant_pathways.json, read it and compute singScore for each pathway.
    """
    drug_name = drug_dir.name
    # Find input JSON file
    in_json = None
    for p in drug_dir.glob("*_relevant_pathways.json"):
        in_json = p
        break
    if in_json is None:
        candidate = drug_dir / f"{drug_name}_relevant_pathways.json"
        if candidate.exists():
            in_json = candidate
    if in_json is None:
        raise FileNotFoundError(f"No '*_relevant_pathways.json' found in {drug_dir}")

    # Load expression data
    if not Path(entrez_sample_path).exists():
        raise FileNotFoundError(f"Expression file not found: {entrez_sample_path}")
    df_expr = pd.read_csv(open(entrez_sample_path, 'r'), header='infer', sep='\t', index_col=0)
    df_expr.index = df_expr.index.map(str)

    # Load pathways JSON
    with open(in_json, "r", encoding="utf-8") as f:
        pathway_dict = json.load(f)

    result_per_drug: Dict[str, Any] = {}

    # ✅ tqdm progress bar for pathways
    for pathway_name, gene_list in tqdm(pathway_dict.items(), desc=f"Processing pathways for {drug_name}", leave=False):
        try:
            res = compute_pathway_score_for_upgenes(df_expr, gene_list, norm_method=norm_method, perms=perms)
            result_per_drug[pathway_name] = res
        except Exception as e:
            print(f"⚠️ Error computing {pathway_name} for {drug_name}: {e}")

    # Prepare output
    if output_root is None:
        out_dir = drug_dir
    else:
        out_dir = Path(output_root) / drug_name
        out_dir.mkdir(parents=True, exist_ok=True)

    out_json = out_dir / f"{drug_name}_singscore_results.json"

    final_output = {drug_name: result_per_drug}
    with open(out_json, "w", encoding="utf-8") as f:
        json.dump(final_output, f, indent=2, ensure_ascii=False)

    print(f"✅ Wrote results for '{drug_name}' → {out_json}")
    return final_output


def batch_run_on_drug_dirs(
    drug_dirs: List[str],
    entrez_sample_path: str,
    norm_method: str = "theoretical",
    perms: int = 5000,
    output_root: Optional[str] = None
) -> Dict[str, Any]:
    """
    Loop over a list of drug directories and run singScore for each.
    """
    combined = {}
    # ✅ tqdm for drugs
    for d in tqdm(drug_dirs, desc="Processing drugs"):
        drug_dir = Path(d)
        if not drug_dir.exists() or not drug_dir.is_dir():
            print(f"⚠️ Skipping non-directory: {d}")
            continue
        try:
            result = run_singscore_on_drug_folder(
                drug_dir,
                entrez_sample_path,
                norm_method=norm_method,
                perms=perms,
                output_root=output_root
            )
            combined.update(result)
        except Exception as e:
            print(f"❌ Error processing {d}: {e}")
    return combined

In [68]:
# -----------------------
# Example usage:
# -----------------------
# Suppose you have a parent folder "singscore_new_code" with subfolders:
# singscore_new_code/Doxorubicin/
# singscore_new_code/Paclitaxel/
# each containing Doxorubicin_relevant_pathways.json etc.
#
drug_dirs = ["singscore_new_code/Doxorubicin"] #"singscore_new_code/Paclitaxel", "singscore_new_code/Palbociclib", "singscore_new_code/Zoledronic_Acid", "singscore_new_code/Gemcitabine", "singscore_new_code/Fulvestrant"]
entrez_sample_path = "singscore_new_code/UK65_clean_gene_log_tpm.txt"

# drug_dirs_1 = ["singscore_new_code/Gemcitabine", "singscore_new_code/Fulvestrant"]
#
results = batch_run_on_drug_dirs(drug_dirs, entrez_sample_path, norm_method='theoretical', perms=5000)
#
# This writes per-drug JSON files and returns a dict of all results.

Processing drugs:   0%|          | 0/1 [01:05<?, ?it/s]

KeyboardInterrupt:

## getting scores for each drug-related pathway

In [35]:
import os
from singscore.singscore import *
import pandas as pd
import json
from tqdm import tqdm

In [ ]:
import os
from singscore.singscore import *
import pandas as pd
import json
from tqdm import tqdm

## loading the patient uk65 data 
uk65 = pd.read_csv("singscore_new_code/UK65_clean_gene_log_tpm.txt", header='infer', sep='\t')
uk65 = uk65.set_index(keys='GeneName')
uk65

               log2_TPM
GeneName
7SK           17.004583
A1BG           5.457517
A1BG-AS1       7.251618
A1CF           1.187320
A2M            8.725599
...                 ...
ZYG11B         4.011921
ZYX            7.907273
ZZEF1          6.529184
ZZZ3           8.051912
hsa-mir-1253   4.325359

[24510 rows x 1 columns]

In [1]:
import os
from singscore.singscore import *
import pandas as pd
import json
from tqdm import tqdm

## loading the patient uk65 data 
uk65 = pd.read_csv("singscore_new_code/UK65_clean_gene_log_tpm.txt", header='infer', sep='\t')
uk65 = uk65.set_index(keys='GeneName')

#loading drug_data
drug_data = json.load(open("singscore_new_code/Doxorubicin/Doxorubicin_relevant_pathways.json"))
count = len(drug_data)
print("Number of items:", count)

Number of items: 796

In [13]:
first_key = next(iter(drug_data.keys()))
print(first_key)

Mitotic Spindle

In [14]:
up = next(iter(drug_data.values()))
print(up)

['ACTN4', 'PCGF5', 'APC', 'MARCKS', 'NIN', 'KIF20B', 'EPB41', 'STAU1', 'CD2AP', 'UXT', 'PPP4R2', 'CSNK1D', 'RACGAP1', 'CDC27', 'PREX1', 'STK38L', 'ARFIP2', 'PLK1', 'BCR', 'LATS1', 'CCDC88A', 'TPX2', 'BIN1', 'NET1', 'SASS6', 'EZR', 'TRIO', 'ITSN1', 'NUMA1', 'SMC4', 'SMC3', 'ABR', 'EPB41L2', 'CDK5RAP2', 'CEP72', 'KIFAP3', 'CEP192', 'SYNPO', 'RHOF', 'LRPPRC', 'ANLN', 'CENPE', 'CENPF', 'INCENP', 'CENPJ', 'PAFAH1B1', 'ARHGEF2', 'ARHGEF3', 'RAPGEF6', 'KPTN', 'ARHGEF7', 'RAPGEF5', 'RABGAP1', 'KIF11', 'PIF1', 'TOP2A', 'KIF15', 'NEDD9', 'RASAL2', 'BRCA2', 'CNTRL', 'KIF1B', 'SPTBN1', 'CEP57', 'DLGAP5', 'MAP1S', 'SORBS2', 'DYNLL2', 'MYO9B', 'FARP1', 'RANBP9', 'SEPTIN9', 'CLIP2', 'CLIP1', 'CTTN', 'TAOK2', 'LLGL1', 'ARF6', 'DYNC1H1', 'MAPRE1', 'RAB3GAP1', 'ALMS1', 'TUBD1', 'WASL', 'AKAP13', 'PCM1', 'OPHN1', 'NUSAP1', 'RICTOR', 'SPTAN1', 'GSN', 'RALBP1', 'ARHGAP29', 'TSC1', 'ARHGAP27', 'MID1', 'TUBA4A', 'ABI1', 'KIF4A', 'TUBGCP6', 'ARL8A', 'TUBGCP5', 'CNTROB', 'ROCK1', 'GEMIN4', 'AURKA', 'KATNB1', 'FGD4', 'BCL2L11', 'FGD6', 'KIF5B', 'CEP250', 'FLNA', 'CLASP1', 'FLNB', 'KNTC1', 'MYH10', 'PCNT', 'ARHGEF12', 'ARHGEF11', 'KIF22', 'TBCD', 'KIF23', 'CKAP5', 'NDC80', 'SSH2', 'DLG1', 'ARHGAP10', 'CDC42EP4', 'BIRC5', 'CDC42EP2', 'FSCN1', 'MAP3K11', 'CDC42EP1', 'KIF2C', 'VCL', 'DOCK4', 'NOTCH2', 'PXN', 'TUBGCP2', 'TUBGCP3', 'ARHGAP4', 'ARHGAP5', 'CCNB2', 'KIF3C', 'KIF3B', 'NEK2', 'ABL1', 'MARK4', 'SAC3D1', 'SUN2', 'ARFGEF1', 'RFC1', 'ARAP3', 'SHROOM1', 'SHROOM2', 'CDC42BPA', 'SMC1A', 'RASA1', 'HOOK3', 'ESPL1', 'RASA2', 'MYH9', 'CDK1', 'NF1', 'ATG4B', 'DOCK2', 'BCAR1', 'SOS1', 'YWHAE', 'LMNB1', 'KLC1', 'RHOT2', 'CAPZB', 'ECT2', 'WASF1', 'WASF2', 'PDLIM5', 'PLEKHG2', 'DST', 'CEP131', 'MID1IP1', 'KATNA1', 'PRC1', 'TIAM1', 'CDC42', 'MYO1E', 'PALLD', 'ALS2', 'HDAC6', 'TTK', 'PKD2', 'ARHGDIA', 'FBXO5', 'TLK1', 'BUB1', 'CYTH2', 'NCK1', 'NCK2']

In [ ]:

up_present = [gene for gene in up if gene in uk65.index]

# Print counts and summary
print(f"Total up genes in signature: {len(up)}")
print(f"Up genes found in expression data: {len(up_present)}")

# Optionally, print the missing ones
missing_up = set(up) - set(uk65.index)

print(f"Missing up genes: {len(missing_up)}")

Total up genes in signature: 199
Up genes found in expression data: 199
Missing up genes: 0

In [25]:
scored_data = score(up_gene=up, down_gene=False, sample=uk65,
                    norm_method='theoretical', full_data=True)
#getting the scored data for a pathway
total_score = scored_data["total_score"].to_list()[0]
total_score

0.23076831651160246

In [26]:
permd = permutate(uk65, n_up=len(up_present), n_down=False)
pvals = empiricalpval(permutations=permd, score=scored_data)
empirical_p_value = pvals["empirical p value"].to_list()[0]
empirical_p_value

9.999000099990002e-05

In [30]:
result = {
    f"{first_key}":{
        "gene_set_info": {
            "geneset_size": len(up),
            "geneset_covered_in_sample": len(up_present)
        },
        "scores": {
            "total_singscore": total_score
        },
        "statistics": {
            "p_value": empirical_p_value,
            "method": "permutation (empirical)",
            "permutations": 10000
        }
    }
}
result

{'Mitotic Spindle': {'gene_set_info': {'geneset_size': 199,
   'geneset_covered_in_sample': 199},
  'scores': {'total_singscore': 0.23076831651160246},
  'statistics': {'p_value': 9.999000099990002e-05,
   'method': 'permutation (empirical)',
   'permutations': 10000}}}

## Doxorubicin_relevant_pathway

In [6]:
import os
from singscore.singscore import *
import pandas as pd
import json
from tqdm import tqdm

## loading the patient uk65 data 
uk65 = pd.read_csv("singscore_new_code/UK65_clean_gene_log_tpm.txt", header='infer', sep='\t')
uk65 = uk65.set_index(keys='GeneName')

#loading drug_data
drug_data = json.load(open("singscore_new_code/Doxorubicin/Doxorubicin_relevant_pathways.json"))
count = len(drug_data)
print("Number of items:", count)

final_result = {}

for key, value in tqdm(drug_data.items(), desc="Calculating pathways"):
    print(f"{key}: Calculation started")
    up = drug_data[key]
    up_present = [gene for gene in up if gene in uk65.index]

    # Print counts and summary
    # print(f"Total up genes in signature: {len(up)}")
    # print(f"Up genes found in expression data: {len(up_present)}")

    # Optionally, print the missing ones
    missing_up = set(up) - set(uk65.index)

    # print(f"Missing up genes: {len(missing_up)}")
    scored_data = score(up_gene=up, down_gene=False, sample=uk65,
                    norm_method='theoretical', full_data=True)
    #getting the scored data for a pathway
    total_score = scored_data["total_score"].to_list()[0]
    print(f"{key}: scoring computed")
    permd = permutate(uk65, n_up=len(up_present), n_down=False)
    pvals = empiricalpval(permutations=permd, score=scored_data)
    empirical_p_value = pvals["empirical p value"].to_list()[0]
    print(f"{key}: pvalue calculation completed")
    result = {
    f"{key}":{
        "gene_set_info": {
            "geneset_size": len(up),
            "geneset_covered_in_sample": len(up_present)
        },
        "scores": {
            "total_singscore": total_score
        },
        "statistics": {
            "p_value": empirical_p_value,
            "method": "permutation (empirical)",
            "permutations": 10000
        }}}
    print(f"{key}: Calculation completed")
    final_result.update(result)

# Save final combined JSON
with open("singscore_new_code/Doxorubicin/Doxorubicin_singscore_results.json", "w", encoding="utf-8") as f:
    json.dump(final_result, f, indent=2, ensure_ascii=False)

Number of items: 796

Calculating pathways:   0%|          | 0/796 [00:00<?, ?it/s]

Mitotic Spindle: Calculation started
Mitotic Spindle: scoring computed

Calculating pathways:   0%|          | 1/796 [00:05<1:15:29,  5.70s/it]

Mitotic Spindle: pvalue calculation completed
Mitotic Spindle: Calculation completed
G2-M Checkpoint: Calculation started
G2-M Checkpoint: scoring computed

Calculating pathways:   0%|          | 2/796 [00:11<1:14:58,  5.67s/it]

G2-M Checkpoint: pvalue calculation completed
G2-M Checkpoint: Calculation completed
Estrogen Response Late: Calculation started
Estrogen Response Late: scoring computed

Calculating pathways:   0%|          | 3/796 [00:16<1:14:31,  5.64s/it]

Estrogen Response Late: pvalue calculation completed
Estrogen Response Late: Calculation completed
Interferon Alpha Response: Calculation started
Interferon Alpha Response: scoring computed

Calculating pathways:   1%|          | 4/796 [00:21<1:08:08,  5.16s/it]

Interferon Alpha Response: pvalue calculation completed
Interferon Alpha Response: Calculation completed
Interferon Gamma Response: Calculation started
Interferon Gamma Response: scoring computed

Calculating pathways:   1%|          | 5/796 [00:27<1:10:36,  5.36s/it]

Interferon Gamma Response: pvalue calculation completed
Interferon Gamma Response: Calculation completed
Apical Junction: Calculation started
Apical Junction: scoring computed

Calculating pathways:   1%|          | 6/796 [00:32<1:10:57,  5.39s/it]

Apical Junction: pvalue calculation completed
Apical Junction: Calculation completed
Complement: Calculation started
Complement: scoring computed

Calculating pathways:   1%|          | 7/796 [00:37<1:11:03,  5.40s/it]

Complement: pvalue calculation completed
Complement: Calculation completed
PI3K/AKT/mTOR  Signaling: Calculation started
PI3K/AKT/mTOR  Signaling: scoring computed

Calculating pathways:   1%|          | 8/796 [00:42<1:06:45,  5.08s/it]

PI3K/AKT/mTOR  Signaling: pvalue calculation completed
PI3K/AKT/mTOR  Signaling: Calculation completed
mTORC1 Signaling: Calculation started
mTORC1 Signaling: scoring computed

Calculating pathways:   1%|          | 9/796 [00:47<1:08:25,  5.22s/it]

mTORC1 Signaling: pvalue calculation completed
mTORC1 Signaling: Calculation completed
E2F Targets: Calculation started
E2F Targets: scoring computed

Calculating pathways:   1%|▏         | 10/796 [00:53<1:10:10,  5.36s/it]

E2F Targets: pvalue calculation completed
E2F Targets: Calculation completed
Epithelial Mesenchymal Transition: Calculation started
Epithelial Mesenchymal Transition: scoring computed

Calculating pathways:   1%|▏         | 11/796 [00:59<1:11:01,  5.43s/it]

Epithelial Mesenchymal Transition: pvalue calculation completed
Epithelial Mesenchymal Transition: Calculation completed
Inflammatory Response: Calculation started
Inflammatory Response: scoring computed

Calculating pathways:   2%|▏         | 12/796 [01:04<1:11:30,  5.47s/it]

Inflammatory Response: pvalue calculation completed
Inflammatory Response: Calculation completed
Xenobiotic Metabolism: Calculation started
Xenobiotic Metabolism: scoring computed

Calculating pathways:   2%|▏         | 13/796 [01:10<1:10:47,  5.43s/it]

Xenobiotic Metabolism: pvalue calculation completed
Xenobiotic Metabolism: Calculation completed
Fatty Acid Metabolism: Calculation started
Fatty Acid Metabolism: scoring computed

Calculating pathways:   2%|▏         | 14/796 [01:15<1:10:34,  5.42s/it]

Fatty Acid Metabolism: pvalue calculation completed
Fatty Acid Metabolism: Calculation completed
Reactive Oxygen Species Pathway: Calculation started
Reactive Oxygen Species Pathway: scoring computed

Calculating pathways:   2%|▏         | 15/796 [01:19<1:04:52,  4.98s/it]

Reactive Oxygen Species Pathway: pvalue calculation completed
Reactive Oxygen Species Pathway: Calculation completed
p53 Pathway: Calculation started
p53 Pathway: scoring computed

Calculating pathways:   2%|▏         | 16/796 [01:25<1:07:26,  5.19s/it]

p53 Pathway: pvalue calculation completed
p53 Pathway: Calculation completed
UV Response Up: Calculation started
UV Response Up: scoring computed

Calculating pathways:   2%|▏         | 17/796 [01:30<1:07:47,  5.22s/it]

UV Response Up: pvalue calculation completed
UV Response Up: Calculation completed
UV Response Dn: Calculation started
UV Response Dn: scoring computed

Calculating pathways:   2%|▏         | 18/796 [01:35<1:06:34,  5.13s/it]

UV Response Dn: pvalue calculation completed
UV Response Dn: Calculation completed
heme Metabolism: Calculation started
heme Metabolism: scoring computed

Calculating pathways:   2%|▏         | 19/796 [01:40<1:07:43,  5.23s/it]

heme Metabolism: pvalue calculation completed
heme Metabolism: Calculation completed
Coagulation: Calculation started
Coagulation: scoring computed

Calculating pathways:   3%|▎         | 20/796 [01:45<1:05:50,  5.09s/it]

Coagulation: pvalue calculation completed
Coagulation: Calculation completed
IL-2/STAT5 Signaling: Calculation started
IL-2/STAT5 Signaling: scoring computed

Calculating pathways:   3%|▎         | 21/796 [01:51<1:07:35,  5.23s/it]

IL-2/STAT5 Signaling: pvalue calculation completed
IL-2/STAT5 Signaling: Calculation completed
Bile Acid Metabolism: Calculation started
Bile Acid Metabolism: scoring computed

Calculating pathways:   3%|▎         | 22/796 [01:55<1:04:09,  4.97s/it]

Bile Acid Metabolism: pvalue calculation completed
Bile Acid Metabolism: Calculation completed
Pperoxisome: Calculation started
Pperoxisome: scoring computed

Calculating pathways:   3%|▎         | 23/796 [02:00<1:02:46,  4.87s/it]

Pperoxisome: pvalue calculation completed
Pperoxisome: Calculation completed
Allograft Rejection: Calculation started
Allograft Rejection: scoring computed

Calculating pathways:   3%|▎         | 24/796 [02:05<1:04:19,  5.00s/it]

Allograft Rejection: pvalue calculation completed
Allograft Rejection: Calculation completed
Spermatogenesis: Calculation started
Spermatogenesis: scoring computed

Calculating pathways:   3%|▎         | 25/796 [02:09<1:02:46,  4.88s/it]

Spermatogenesis: pvalue calculation completed
Spermatogenesis: Calculation completed
KRAS Signaling Up: Calculation started
KRAS Signaling Up: scoring computed

Calculating pathways:   3%|▎         | 26/796 [02:15<1:04:36,  5.04s/it]

KRAS Signaling Up: pvalue calculation completed
KRAS Signaling Up: Calculation completed
KRAS Signaling Dn: Calculation started
KRAS Signaling Dn: scoring computed

Calculating pathways:   3%|▎         | 27/796 [02:20<1:04:30,  5.03s/it]

KRAS Signaling Dn: pvalue calculation completed
KRAS Signaling Dn: Calculation completed
ABC transporters: Calculation started
ABC transporters: scoring computed

Calculating pathways:   4%|▎         | 28/796 [02:24<59:57,  4.68s/it]

ABC transporters: pvalue calculation completed
ABC transporters: Calculation completed
AGE-RAGE signaling pathway in diabetic complications: Calculation started
AGE-RAGE signaling pathway in diabetic complications: scoring computed

Calculating pathways:   4%|▎         | 29/796 [02:28<59:18,  4.64s/it]

AGE-RAGE signaling pathway in diabetic complications: pvalue calculation completed
AGE-RAGE signaling pathway in diabetic complications: Calculation completed
Adherens junction: Calculation started
Adherens junction: scoring computed

Calculating pathways:   4%|▍         | 30/796 [02:32<57:26,  4.50s/it]

Adherens junction: pvalue calculation completed
Adherens junction: Calculation completed
Alzheimer disease: Calculation started
Alzheimer disease: scoring computed

Calculating pathways:   4%|▍         | 31/796 [02:40<1:08:47,  5.39s/it]

Alzheimer disease: pvalue calculation completed
Alzheimer disease: Calculation completed
Amyotrophic lateral sclerosis: Calculation started
Amyotrophic lateral sclerosis: scoring computed

Calculating pathways:   4%|▍         | 32/796 [02:48<1:18:46,  6.19s/it]

Amyotrophic lateral sclerosis: pvalue calculation completed
Amyotrophic lateral sclerosis: Calculation completed
Arachidonic acid metabolism: Calculation started
Arachidonic acid metabolism: scoring computed

Calculating pathways:   4%|▍         | 33/796 [02:52<1:11:09,  5.60s/it]

Arachidonic acid metabolism: pvalue calculation completed
Arachidonic acid metabolism: Calculation completed
Autophagy: Calculation started
Autophagy: scoring computed

Calculating pathways:   4%|▍         | 34/796 [02:58<1:10:25,  5.54s/it]

Autophagy: pvalue calculation completed
Autophagy: Calculation completed
Axon guidance: Calculation started
Axon guidance: scoring computed

Calculating pathways:   4%|▍         | 35/796 [03:04<1:11:57,  5.67s/it]

Axon guidance: pvalue calculation completed
Axon guidance: Calculation completed
Bile secretion: Calculation started
Bile secretion: scoring computed

Calculating pathways:   5%|▍         | 36/796 [03:08<1:07:49,  5.35s/it]

Bile secretion: pvalue calculation completed
Bile secretion: Calculation completed
Bladder cancer: Calculation started
Bladder cancer: scoring computed

Calculating pathways:   5%|▍         | 37/796 [03:12<1:03:01,  4.98s/it]

Bladder cancer: pvalue calculation completed
Bladder cancer: Calculation completed
Breast cancer: Calculation started
Breast cancer: scoring computed

Calculating pathways:   5%|▍         | 38/796 [03:18<1:04:39,  5.12s/it]

Breast cancer: pvalue calculation completed
Breast cancer: Calculation completed
C-type lectin receptor signaling pathway: Calculation started
C-type lectin receptor signaling pathway: scoring computed

Calculating pathways:   5%|▍         | 39/796 [03:23<1:03:41,  5.05s/it]

C-type lectin receptor signaling pathway: pvalue calculation completed
C-type lectin receptor signaling pathway: Calculation completed
Calcium signaling pathway: Calculation started
Calcium signaling pathway: scoring computed

Calculating pathways:   5%|▌         | 40/796 [03:29<1:08:39,  5.45s/it]

Calcium signaling pathway: pvalue calculation completed
Calcium signaling pathway: Calculation completed
Central carbon metabolism in cancer: Calculation started
Central carbon metabolism in cancer: scoring computed

Calculating pathways:   5%|▌         | 41/796 [03:34<1:04:54,  5.16s/it]

Central carbon metabolism in cancer: pvalue calculation completed
Central carbon metabolism in cancer: Calculation completed
Cholinergic synapse: Calculation started
Cholinergic synapse: scoring computed

Calculating pathways:   5%|▌         | 42/796 [03:38<1:03:39,  5.07s/it]

Cholinergic synapse: pvalue calculation completed
Cholinergic synapse: Calculation completed
Coronavirus disease: Calculation started
Coronavirus disease: scoring computed

Calculating pathways:   5%|▌         | 43/796 [03:45<1:08:36,  5.47s/it]

Coronavirus disease: pvalue calculation completed
Coronavirus disease: Calculation completed
Cytosolic DNA-sensing pathway: Calculation started
Cytosolic DNA-sensing pathway: scoring computed

Calculating pathways:   6%|▌         | 44/796 [03:49<1:03:46,  5.09s/it]

Cytosolic DNA-sensing pathway: pvalue calculation completed
Cytosolic DNA-sensing pathway: Calculation completed
Diabetic cardiomyopathy: Calculation started
Diabetic cardiomyopathy: scoring computed

Calculating pathways:   6%|▌         | 45/796 [03:55<1:07:22,  5.38s/it]

Diabetic cardiomyopathy: pvalue calculation completed
Diabetic cardiomyopathy: Calculation completed
Endometrial cancer: Calculation started
Endometrial cancer: scoring computed

Calculating pathways:   6%|▌         | 46/796 [03:59<1:03:34,  5.09s/it]

Endometrial cancer: pvalue calculation completed
Endometrial cancer: Calculation completed
ErbB signaling pathway: Calculation started
ErbB signaling pathway: scoring computed

Calculating pathways:   6%|▌         | 47/796 [04:04<1:02:29,  5.01s/it]

ErbB signaling pathway: pvalue calculation completed
ErbB signaling pathway: Calculation completed
Estrogen signaling pathway: Calculation started
Estrogen signaling pathway: scoring computed

Calculating pathways:   6%|▌         | 48/796 [04:09<1:02:46,  5.04s/it]

Estrogen signaling pathway: pvalue calculation completed
Estrogen signaling pathway: Calculation completed
Fc epsilon RI signaling pathway: Calculation started
Fc epsilon RI signaling pathway: scoring computed

Calculating pathways:   6%|▌         | 49/796 [04:14<1:01:08,  4.91s/it]

Fc epsilon RI signaling pathway: pvalue calculation completed
Fc epsilon RI signaling pathway: Calculation completed
Ferroptosis: Calculation started
Ferroptosis: scoring computed

Calculating pathways:   6%|▋         | 50/796 [04:18<58:18,  4.69s/it]

Ferroptosis: pvalue calculation completed
Ferroptosis: Calculation completed
Fluid shear stress and atherosclerosis: Calculation started
Fluid shear stress and atherosclerosis: scoring computed

Calculating pathways:   6%|▋         | 51/796 [04:24<1:01:01,  4.91s/it]

Fluid shear stress and atherosclerosis: pvalue calculation completed
Fluid shear stress and atherosclerosis: Calculation completed
Focal adhesion: Calculation started
Focal adhesion: scoring computed

Calculating pathways:   7%|▋         | 52/796 [04:30<1:05:31,  5.28s/it]

Focal adhesion: pvalue calculation completed
Focal adhesion: Calculation completed
Gastric cancer: Calculation started
Gastric cancer: scoring computed

Calculating pathways:   7%|▋         | 53/796 [04:35<1:05:59,  5.33s/it]

Gastric cancer: pvalue calculation completed
Gastric cancer: Calculation completed
GnRH signaling pathway: Calculation started
GnRH signaling pathway: scoring computed

Calculating pathways:   7%|▋         | 54/796 [04:40<1:03:50,  5.16s/it]

GnRH signaling pathway: pvalue calculation completed
GnRH signaling pathway: Calculation completed
HIF-1 signaling pathway: Calculation started
HIF-1 signaling pathway: scoring computed

Calculating pathways:   7%|▋         | 55/796 [04:45<1:03:14,  5.12s/it]

HIF-1 signaling pathway: pvalue calculation completed
HIF-1 signaling pathway: Calculation completed
Hepatocellular carcinoma: Calculation started
Hepatocellular carcinoma: scoring computed

Calculating pathways:   7%|▋         | 56/796 [04:51<1:05:58,  5.35s/it]

Hepatocellular carcinoma: pvalue calculation completed
Hepatocellular carcinoma: Calculation completed
Human T-cell leukemia virus 1 infection: Calculation started
Human T-cell leukemia virus 1 infection: scoring computed

Calculating pathways:   7%|▋         | 57/796 [04:57<1:09:23,  5.63s/it]

Human T-cell leukemia virus 1 infection: pvalue calculation completed
Human T-cell leukemia virus 1 infection: Calculation completed
Human papillomavirus infection: Calculation started
Human papillomavirus infection: scoring computed

Calculating pathways:   7%|▋         | 58/796 [05:04<1:13:41,  5.99s/it]

Human papillomavirus infection: pvalue calculation completed
Human papillomavirus infection: Calculation completed
Influenza A: Calculation started
Influenza A: scoring computed

Calculating pathways:   7%|▋         | 59/796 [05:09<1:09:10,  5.63s/it]

Influenza A: pvalue calculation completed
Influenza A: Calculation completed
Legionellosis: Calculation started
Legionellosis: scoring computed

Calculating pathways:   8%|▊         | 60/796 [05:13<1:02:41,  5.11s/it]

Legionellosis: pvalue calculation completed
Legionellosis: Calculation completed
Leukocyte transendothelial migration: Calculation started
Leukocyte transendothelial migration: scoring computed

Calculating pathways:   8%|▊         | 61/796 [05:17<1:00:04,  4.90s/it]

Leukocyte transendothelial migration: pvalue calculation completed
Leukocyte transendothelial migration: Calculation completed
Linoleic acid metabolism: Calculation started
Linoleic acid metabolism: scoring computed

Calculating pathways:   8%|▊         | 62/796 [05:21<55:03,  4.50s/it]

Linoleic acid metabolism: pvalue calculation completed
Linoleic acid metabolism: Calculation completed
Lipid and atherosclerosis: Calculation started
Lipid and atherosclerosis: scoring computed

Calculating pathways:   8%|▊         | 63/796 [05:26<58:11,  4.76s/it]

Lipid and atherosclerosis: pvalue calculation completed
Lipid and atherosclerosis: Calculation completed
MAPK signaling pathway: Calculation started
MAPK signaling pathway: scoring computed

Calculating pathways:   8%|▊         | 64/796 [05:32<1:04:14,  5.27s/it]

MAPK signaling pathway: pvalue calculation completed
MAPK signaling pathway: Calculation completed
MicroRNAs in cancer: Calculation started
MicroRNAs in cancer: scoring computed

Calculating pathways:   8%|▊         | 65/796 [05:38<1:05:11,  5.35s/it]

MicroRNAs in cancer: pvalue calculation completed
MicroRNAs in cancer: Calculation completed
NF-kappa B signaling pathway: Calculation started
NF-kappa B signaling pathway: scoring computed

Calculating pathways:   8%|▊         | 66/796 [05:42<1:01:23,  5.05s/it]

NF-kappa B signaling pathway: pvalue calculation completed
NF-kappa B signaling pathway: Calculation completed
NOD-like receptor signaling pathway: Calculation started
NOD-like receptor signaling pathway: scoring computed

Calculating pathways:   8%|▊         | 67/796 [05:47<1:01:19,  5.05s/it]

NOD-like receptor signaling pathway: pvalue calculation completed
NOD-like receptor signaling pathway: Calculation completed
Natural killer cell mediated cytotoxicity: Calculation started
Natural killer cell mediated cytotoxicity: scoring computed

Calculating pathways:   9%|▊         | 68/796 [05:52<58:54,  4.85s/it]

Natural killer cell mediated cytotoxicity: pvalue calculation completed
Natural killer cell mediated cytotoxicity: Calculation completed
Necroptosis: Calculation started
Necroptosis: scoring computed

Calculating pathways:   9%|▊         | 69/796 [05:57<58:43,  4.85s/it]

Necroptosis: pvalue calculation completed
Necroptosis: Calculation completed
Neuroactive ligand-receptor interaction: Calculation started
Neuroactive ligand-receptor interaction: scoring computed

Calculating pathways:   9%|▉         | 70/796 [06:03<1:02:42,  5.18s/it]

Neuroactive ligand-receptor interaction: pvalue calculation completed
Neuroactive ligand-receptor interaction: Calculation completed
Neutrophil extracellular trap formation: Calculation started
Neutrophil extracellular trap formation: scoring computed

Calculating pathways:   9%|▉         | 71/796 [06:08<1:02:08,  5.14s/it]

Neutrophil extracellular trap formation: pvalue calculation completed
Neutrophil extracellular trap formation: Calculation completed
Non-small cell lung cancer: Calculation started
Non-small cell lung cancer: scoring computed

Calculating pathways:   9%|▉         | 72/796 [06:12<58:14,  4.83s/it]

Non-small cell lung cancer: pvalue calculation completed
Non-small cell lung cancer: Calculation completed
Oocyte meiosis: Calculation started
Oocyte meiosis: scoring computed

Calculating pathways:   9%|▉         | 73/796 [06:16<57:21,  4.76s/it]

Oocyte meiosis: pvalue calculation completed
Oocyte meiosis: Calculation completed
Osteoclast differentiation: Calculation started
Osteoclast differentiation: scoring computed

Calculating pathways:   9%|▉         | 74/796 [06:21<57:09,  4.75s/it]

Osteoclast differentiation: pvalue calculation completed
Osteoclast differentiation: Calculation completed
PD-L1 expression and PD-1 checkpoint pathway in cancer: Calculation started
PD-L1 expression and PD-1 checkpoint pathway in cancer: scoring computed

Calculating pathways:   9%|▉         | 75/796 [06:25<55:20,  4.60s/it]

PD-L1 expression and PD-1 checkpoint pathway in cancer: pvalue calculation completed
PD-L1 expression and PD-1 checkpoint pathway in cancer: Calculation completed
PI3K-Akt signaling pathway: Calculation started
PI3K-Akt signaling pathway: scoring computed

Calculating pathways:  10%|▉         | 76/796 [06:32<1:02:48,  5.23s/it]

PI3K-Akt signaling pathway: pvalue calculation completed
PI3K-Akt signaling pathway: Calculation completed
Pancreatic cancer: Calculation started
Pancreatic cancer: scoring computed

Calculating pathways:  10%|▉         | 77/796 [06:36<58:39,  4.89s/it]

Pancreatic cancer: pvalue calculation completed
Pancreatic cancer: Calculation completed
Pathogenic Escherichia coli infection: Calculation started
Pathogenic Escherichia coli infection: scoring computed

Calculating pathways:  10%|▉         | 78/796 [06:41<1:00:05,  5.02s/it]

Pathogenic Escherichia coli infection: pvalue calculation completed
Pathogenic Escherichia coli infection: Calculation completed
Pathways in cancer: Calculation started
Pathways in cancer: scoring computed

Calculating pathways:  10%|▉         | 79/796 [06:50<1:12:49,  6.09s/it]

Pathways in cancer: pvalue calculation completed
Pathways in cancer: Calculation completed
Pathways of neurodegeneration: Calculation started
Pathways of neurodegeneration: scoring computed

Calculating pathways:  10%|█         | 80/796 [06:58<1:20:11,  6.72s/it]

Pathways of neurodegeneration: pvalue calculation completed
Pathways of neurodegeneration: Calculation completed
Pertussis: Calculation started
Pertussis: scoring computed

Calculating pathways:  10%|█         | 81/796 [07:02<1:10:28,  5.91s/it]

Pertussis: pvalue calculation completed
Pertussis: Calculation completed
Phospholipase D signaling pathway: Calculation started
Phospholipase D signaling pathway: scoring computed

Calculating pathways:  10%|█         | 82/796 [07:07<1:07:06,  5.64s/it]

Phospholipase D signaling pathway: pvalue calculation completed
Phospholipase D signaling pathway: Calculation completed
Platelet activation: Calculation started
Platelet activation: scoring computed

Calculating pathways:  10%|█         | 83/796 [07:12<1:03:35,  5.35s/it]

Platelet activation: pvalue calculation completed
Platelet activation: Calculation completed
Primary immunodeficiency: Calculation started
Primary immunodeficiency: scoring computed

Calculating pathways:  11%|█         | 84/796 [07:16<57:18,  4.83s/it]

Primary immunodeficiency: pvalue calculation completed
Primary immunodeficiency: Calculation completed
Prion disease: Calculation started
Prion disease: scoring computed

Calculating pathways:  11%|█         | 85/796 [07:22<1:01:39,  5.20s/it]

Prion disease: pvalue calculation completed
Prion disease: Calculation completed
Progesterone-mediated oocyte maturation: Calculation started
Progesterone-mediated oocyte maturation: scoring computed

Calculating pathways:  11%|█         | 86/796 [07:26<58:42,  4.96s/it]

Progesterone-mediated oocyte maturation: pvalue calculation completed
Progesterone-mediated oocyte maturation: Calculation completed
Prostate cancer: Calculation started
Prostate cancer: scoring computed

Calculating pathways:  11%|█         | 87/796 [07:30<56:45,  4.80s/it]

Prostate cancer: pvalue calculation completed
Prostate cancer: Calculation completed
Proteoglycans in cancer: Calculation started
Proteoglycans in cancer: scoring computed

Calculating pathways:  11%|█         | 88/796 [07:36<59:08,  5.01s/it]

Proteoglycans in cancer: pvalue calculation completed
Proteoglycans in cancer: Calculation completed
Regulation of actin cytoskeleton: Calculation started
Regulation of actin cytoskeleton: scoring computed

Calculating pathways:  11%|█         | 89/796 [07:42<1:01:02,  5.18s/it]

Regulation of actin cytoskeleton: pvalue calculation completed
Regulation of actin cytoskeleton: Calculation completed
Relaxin signaling pathway: Calculation started
Relaxin signaling pathway: scoring computed

Calculating pathways:  11%|█▏        | 90/796 [07:46<59:06,  5.02s/it]

Relaxin signaling pathway: pvalue calculation completed
Relaxin signaling pathway: Calculation completed
Salmonella infection: Calculation started
Salmonella infection: scoring computed

Calculating pathways:  11%|█▏        | 91/796 [07:52<1:02:47,  5.34s/it]

Salmonella infection: pvalue calculation completed
Salmonella infection: Calculation completed
Serotonergic synapse: Calculation started
Serotonergic synapse: scoring computed

Calculating pathways:  12%|█▏        | 92/796 [07:57<59:05,  5.04s/it]

Serotonergic synapse: pvalue calculation completed
Serotonergic synapse: Calculation completed
Shigellosis: Calculation started
Shigellosis: scoring computed

Calculating pathways:  12%|█▏        | 93/796 [08:03<1:02:21,  5.32s/it]

Shigellosis: pvalue calculation completed
Shigellosis: Calculation completed
Sphingolipid signaling pathway: Calculation started
Sphingolipid signaling pathway: scoring computed

Calculating pathways:  12%|█▏        | 94/796 [08:07<59:42,  5.10s/it]

Sphingolipid signaling pathway: pvalue calculation completed
Sphingolipid signaling pathway: Calculation completed
T cell receptor signaling pathway: Calculation started
T cell receptor signaling pathway: scoring computed

Calculating pathways:  12%|█▏        | 95/796 [08:12<56:59,  4.88s/it]

T cell receptor signaling pathway: pvalue calculation completed
T cell receptor signaling pathway: Calculation completed
Taste transduction: Calculation started
Taste transduction: scoring computed

Calculating pathways:  12%|█▏        | 96/796 [08:16<54:14,  4.65s/it]

Taste transduction: pvalue calculation completed
Taste transduction: Calculation completed
Th1 and Th2 cell differentiation: Calculation started
Th1 and Th2 cell differentiation: scoring computed

Calculating pathways:  12%|█▏        | 97/796 [08:20<52:50,  4.54s/it]

Th1 and Th2 cell differentiation: pvalue calculation completed
Th1 and Th2 cell differentiation: Calculation completed
Th17 cell differentiation: Calculation started
Th17 cell differentiation: scoring computed

Calculating pathways:  12%|█▏        | 98/796 [08:24<52:25,  4.51s/it]

Th17 cell differentiation: pvalue calculation completed
Th17 cell differentiation: Calculation completed
Tight junction: Calculation started
Tight junction: scoring computed

Calculating pathways:  12%|█▏        | 99/796 [08:29<54:31,  4.69s/it]

Tight junction: pvalue calculation completed
Tight junction: Calculation completed
Viral myocarditis: Calculation started
Viral myocarditis: scoring computed

Calculating pathways:  13%|█▎        | 100/796 [08:33<51:24,  4.43s/it]

Viral myocarditis: pvalue calculation completed
Viral myocarditis: Calculation completed
Vitamin digestion and absorption: Calculation started
Vitamin digestion and absorption: scoring computed

Calculating pathways:  13%|█▎        | 101/796 [08:37<48:10,  4.16s/it]

Vitamin digestion and absorption: pvalue calculation completed
Vitamin digestion and absorption: Calculation completed
Yersinia infection: Calculation started
Yersinia infection: scoring computed

Calculating pathways:  13%|█▎        | 102/796 [08:42<50:23,  4.36s/it]

Yersinia infection: pvalue calculation completed
Yersinia infection: Calculation completed
cAMP signaling pathway: Calculation started
cAMP signaling pathway: scoring computed

Calculating pathways:  13%|█▎        | 103/796 [08:47<54:03,  4.68s/it]

cAMP signaling pathway: pvalue calculation completed
cAMP signaling pathway: Calculation completed
ABC Transporter Disorders: Calculation started
ABC Transporter Disorders: scoring computed

Calculating pathways:  13%|█▎        | 104/796 [08:51<51:25,  4.46s/it]

ABC Transporter Disorders: pvalue calculation completed
ABC Transporter Disorders: Calculation completed
ABC-family Proteins Mediated Transport: Calculation started
ABC-family Proteins Mediated Transport: scoring computed

Calculating pathways:  13%|█▎        | 105/796 [08:55<51:04,  4.43s/it]

ABC-family Proteins Mediated Transport: pvalue calculation completed
ABC-family Proteins Mediated Transport: Calculation completed
APC C-mediated Degradation of Cell Cycle Proteins: Calculation started
APC C-mediated Degradation of Cell Cycle Proteins: scoring computed

Calculating pathways:  13%|█▎        | 106/796 [08:59<49:47,  4.33s/it]

APC C-mediated Degradation of Cell Cycle Proteins: pvalue calculation completed
APC C-mediated Degradation of Cell Cycle Proteins: Calculation completed
APC C Cdh1 Mediated Degradation of Cdc20 and Other APC C Cdh1 Targets in Late Mitosis Early G1: Calculation started
APC C Cdh1 Mediated Degradation of Cdc20 and Other APC C Cdh1 Targets in Late Mitosis Early G1: scoring computed

Calculating pathways:  13%|█▎        | 107/796 [09:03<48:35,  4.23s/it]

APC C Cdh1 Mediated Degradation of Cdc20 and Other APC C Cdh1 Targets in Late Mitosis Early G1: pvalue calculation completed
APC C Cdh1 Mediated Degradation of Cdc20 and Other APC C Cdh1 Targets in Late Mitosis Early G1: Calculation completed
AURKA Activation by TPX2: Calculation started
AURKA Activation by TPX2: scoring computed

Calculating pathways:  14%|█▎        | 108/796 [09:08<48:11,  4.20s/it]

AURKA Activation by TPX2: pvalue calculation completed
AURKA Activation by TPX2: Calculation completed
Abacavir ADME: Calculation started
Abacavir ADME: scoring computed

Calculating pathways:  14%|█▎        | 109/796 [09:11<45:28,  3.97s/it]

Abacavir ADME: pvalue calculation completed
Abacavir ADME: Calculation completed
Abacavir Transmembrane Transport: Calculation started
Abacavir Transmembrane Transport: scoring computed

Calculating pathways:  14%|█▍        | 110/796 [09:14<43:17,  3.79s/it]

Abacavir Transmembrane Transport: pvalue calculation completed
Abacavir Transmembrane Transport: Calculation completed
Activated NTRK2 Signals Through FYN: Calculation started
Activated NTRK2 Signals Through FYN: scoring computed

Calculating pathways:  14%|█▍        | 111/796 [09:18<41:49,  3.66s/it]

Activated NTRK2 Signals Through FYN: pvalue calculation completed
Activated NTRK2 Signals Through FYN: Calculation completed
Activation of Matrix Metalloproteinases: Calculation started
Activation of Matrix Metalloproteinases: scoring computed

Calculating pathways:  14%|█▍        | 112/796 [09:22<41:59,  3.68s/it]

Activation of Matrix Metalloproteinases: pvalue calculation completed
Activation of Matrix Metalloproteinases: Calculation completed
Adaptive Immune System: Calculation started
Adaptive Immune System: scoring computed

Calculating pathways:  14%|█▍        | 113/796 [09:33<1:06:57,  5.88s/it]

Adaptive Immune System: pvalue calculation completed
Adaptive Immune System: Calculation completed
Amine Ligand-Binding Receptors: Calculation started
Amine Ligand-Binding Receptors: scoring computed

Calculating pathways:  14%|█▍        | 114/796 [09:36<59:32,  5.24s/it]

Amine Ligand-Binding Receptors: pvalue calculation completed
Amine Ligand-Binding Receptors: Calculation completed
Anti-inflammatory Response Favouring Leishmania Parasite Infection: Calculation started
Anti-inflammatory Response Favouring Leishmania Parasite Infection: scoring computed

Calculating pathways:  14%|█▍        | 115/796 [09:41<56:56,  5.02s/it]

Anti-inflammatory Response Favouring Leishmania Parasite Infection: pvalue calculation completed
Anti-inflammatory Response Favouring Leishmania Parasite Infection: Calculation completed
Antigen Activates B Cell Receptor (BCR) Leading to Generation of Second Messengers: Calculation started
Antigen Activates B Cell Receptor (BCR) Leading to Generation of Second Messengers: scoring computed

Calculating pathways:  15%|█▍        | 116/796 [09:44<52:14,  4.61s/it]

Antigen Activates B Cell Receptor (BCR) Leading to Generation of Second Messengers: pvalue calculation completed
Antigen Activates B Cell Receptor (BCR) Leading to Generation of Second Messengers: Calculation completed
Arachidonate Metabolism: Calculation started
Arachidonate Metabolism: scoring computed

Calculating pathways:  15%|█▍        | 117/796 [09:48<49:43,  4.39s/it]

Arachidonate Metabolism: pvalue calculation completed
Arachidonate Metabolism: Calculation completed
Aspirin ADME: Calculation started
Aspirin ADME: scoring computed

Calculating pathways:  15%|█▍        | 118/796 [09:52<46:42,  4.13s/it]

Aspirin ADME: pvalue calculation completed
Aspirin ADME: Calculation completed
Atorvastatin ADME: Calculation started
Atorvastatin ADME: scoring computed

Calculating pathways:  15%|█▍        | 119/796 [09:55<44:03,  3.90s/it]

Atorvastatin ADME: pvalue calculation completed
Atorvastatin ADME: Calculation completed
Axon Guidance: Calculation started
Axon Guidance: scoring computed

Calculating pathways:  15%|█▌        | 120/796 [10:04<1:00:55,  5.41s/it]

Axon Guidance: pvalue calculation completed
Axon Guidance: Calculation completed
Biosynthesis of DHA-derived SPMs: Calculation started
Biosynthesis of DHA-derived SPMs: scoring computed

Calculating pathways:  15%|█▌        | 121/796 [10:08<54:32,  4.85s/it]

Biosynthesis of DHA-derived SPMs: pvalue calculation completed
Biosynthesis of DHA-derived SPMs: Calculation completed
Biosynthesis of E-series 18(S)-resolvins: Calculation started
Biosynthesis of E-series 18(S)-resolvins: scoring computed

Calculating pathways:  15%|█▌        | 122/796 [10:11<49:28,  4.40s/it]

Biosynthesis of E-series 18(S)-resolvins: pvalue calculation completed
Biosynthesis of E-series 18(S)-resolvins: Calculation completed
Biosynthesis of EPA-derived SPMs: Calculation started
Biosynthesis of EPA-derived SPMs: scoring computed

Calculating pathways:  15%|█▌        | 123/796 [10:14<45:46,  4.08s/it]

Biosynthesis of EPA-derived SPMs: pvalue calculation completed
Biosynthesis of EPA-derived SPMs: Calculation completed
Biosynthesis of Specialized Proresolving Mediators (SPMs): Calculation started
Biosynthesis of Specialized Proresolving Mediators (SPMs): scoring computed

Calculating pathways:  16%|█▌        | 124/796 [10:18<43:35,  3.89s/it]

Biosynthesis of Specialized Proresolving Mediators (SPMs): pvalue calculation completed
Biosynthesis of Specialized Proresolving Mediators (SPMs): Calculation completed
C-type Lectin Receptors (CLRs): Calculation started
C-type Lectin Receptors (CLRs): scoring computed

Calculating pathways:  16%|█▌        | 125/796 [10:22<45:47,  4.09s/it]

C-type Lectin Receptors (CLRs): pvalue calculation completed
C-type Lectin Receptors (CLRs): Calculation completed
CD209 (DC-SIGN) Signaling: Calculation started
CD209 (DC-SIGN) Signaling: scoring computed

Calculating pathways:  16%|█▌        | 126/796 [10:26<43:42,  3.91s/it]

CD209 (DC-SIGN) Signaling: pvalue calculation completed
CD209 (DC-SIGN) Signaling: Calculation completed
CD28 Co-Stimulation: Calculation started
CD28 Co-Stimulation: scoring computed

Calculating pathways:  16%|█▌        | 127/796 [10:30<42:44,  3.83s/it]

CD28 Co-Stimulation: pvalue calculation completed
CD28 Co-Stimulation: Calculation completed
CD28 Dependent PI3K Akt Signaling: Calculation started
CD28 Dependent PI3K Akt Signaling: scoring computed

Calculating pathways:  16%|█▌        | 128/796 [10:33<41:37,  3.74s/it]

CD28 Dependent PI3K Akt Signaling: pvalue calculation completed
CD28 Dependent PI3K Akt Signaling: Calculation completed
CD28 Dependent Vav1 Pathway: Calculation started
CD28 Dependent Vav1 Pathway: scoring computed

Calculating pathways:  16%|█▌        | 129/796 [10:37<41:11,  3.70s/it]

CD28 Dependent Vav1 Pathway: pvalue calculation completed
CD28 Dependent Vav1 Pathway: Calculation completed
CRMPs in Sema3A Signaling: Calculation started
CRMPs in Sema3A Signaling: scoring computed

Calculating pathways:  16%|█▋        | 130/796 [10:40<40:52,  3.68s/it]

CRMPs in Sema3A Signaling: pvalue calculation completed
CRMPs in Sema3A Signaling: Calculation completed
CTLA4 Inhibitory Signaling: Calculation started
CTLA4 Inhibitory Signaling: scoring computed

Calculating pathways:  16%|█▋        | 131/796 [10:44<40:25,  3.65s/it]

CTLA4 Inhibitory Signaling: pvalue calculation completed
CTLA4 Inhibitory Signaling: Calculation completed
Cell Cycle: Calculation started
Cell Cycle: scoring computed

Calculating pathways:  17%|█▋        | 132/796 [10:54<1:02:03,  5.61s/it]

Cell Cycle: pvalue calculation completed
Cell Cycle: Calculation completed
Cell Cycle, Mitotic: Calculation started
Cell Cycle, Mitotic: scoring computed

Calculating pathways:  17%|█▋        | 133/796 [11:03<1:12:39,  6.58s/it]

Cell Cycle, Mitotic: pvalue calculation completed
Cell Cycle, Mitotic: Calculation completed
Cell Recruitment (Pro-Inflammatory Response): Calculation started
Cell Recruitment (Pro-Inflammatory Response): scoring computed

Calculating pathways:  17%|█▋        | 134/796 [11:07<1:02:51,  5.70s/it]

Cell Recruitment (Pro-Inflammatory Response): pvalue calculation completed
Cell Recruitment (Pro-Inflammatory Response): Calculation completed
Cell Surface Interactions at the Vascular Wall: Calculation started
Cell Surface Interactions at the Vascular Wall: scoring computed

Calculating pathways:  17%|█▋        | 135/796 [11:11<1:00:13,  5.47s/it]

Cell Surface Interactions at the Vascular Wall: pvalue calculation completed
Cell Surface Interactions at the Vascular Wall: Calculation completed
Cell-Cell Communication: Calculation started
Cell-Cell Communication: scoring computed

Calculating pathways:  17%|█▋        | 136/796 [11:17<58:46,  5.34s/it]

Cell-Cell Communication: pvalue calculation completed
Cell-Cell Communication: Calculation completed
Cellular Response to Chemical Stress: Calculation started
Cellular Response to Chemical Stress: scoring computed

Calculating pathways:  17%|█▋        | 137/796 [11:22<59:10,  5.39s/it]

Cellular Response to Chemical Stress: pvalue calculation completed
Cellular Response to Chemical Stress: Calculation completed
Cellular Responses to Mechanical Stimuli: Calculation started
Cellular Responses to Mechanical Stimuli: scoring computed

Calculating pathways:  17%|█▋        | 138/796 [11:26<55:26,  5.06s/it]

Cellular Responses to Mechanical Stimuli: pvalue calculation completed
Cellular Responses to Mechanical Stimuli: Calculation completed
Cellular Responses to Stimuli: Calculation started
Cellular Responses to Stimuli: scoring computed

Calculating pathways:  17%|█▋        | 139/796 [11:38<1:18:43,  7.19s/it]

Cellular Responses to Stimuli: pvalue calculation completed
Cellular Responses to Stimuli: Calculation completed
Cellular Responses to Stress: Calculation started
Cellular Responses to Stress: scoring computed

Calculating pathways:  18%|█▊        | 140/796 [11:50<1:31:53,  8.41s/it]

Cellular Responses to Stress: pvalue calculation completed
Cellular Responses to Stress: Calculation completed
Chaperone Mediated Autophagy: Calculation started
Chaperone Mediated Autophagy: scoring computed

Calculating pathways:  18%|█▊        | 141/796 [11:53<1:16:13,  6.98s/it]

Chaperone Mediated Autophagy: pvalue calculation completed
Chaperone Mediated Autophagy: Calculation completed
Chromosome Maintenance: Calculation started
Chromosome Maintenance: scoring computed

Calculating pathways:  18%|█▊        | 142/796 [11:58<1:08:03,  6.24s/it]

Chromosome Maintenance: pvalue calculation completed
Chromosome Maintenance: Calculation completed
Ciprofloxacin ADME: Calculation started
Ciprofloxacin ADME: scoring computed

Calculating pathways:  18%|█▊        | 143/796 [12:01<58:25,  5.37s/it]

Ciprofloxacin ADME: pvalue calculation completed
Ciprofloxacin ADME: Calculation completed
Class A 1 (Rhodopsin-like Receptors): Calculation started
Class A 1 (Rhodopsin-like Receptors): scoring computed

Calculating pathways:  18%|█▊        | 144/796 [12:07<1:00:23,  5.56s/it]

Class A 1 (Rhodopsin-like Receptors): pvalue calculation completed
Class A 1 (Rhodopsin-like Receptors): Calculation completed
Cobalamin (Cbl, Vitamin B12) Transport and Metabolism: Calculation started
Cobalamin (Cbl, Vitamin B12) Transport and Metabolism: scoring computed

Calculating pathways:  18%|█▊        | 145/796 [12:11<53:32,  4.93s/it]

Cobalamin (Cbl, Vitamin B12) Transport and Metabolism: pvalue calculation completed
Cobalamin (Cbl, Vitamin B12) Transport and Metabolism: Calculation completed
Collagen Degradation: Calculation started
Collagen Degradation: scoring computed

Calculating pathways:  18%|█▊        | 146/796 [12:15<50:12,  4.63s/it]

Collagen Degradation: pvalue calculation completed
Collagen Degradation: Calculation completed
Constitutive Signaling by Aberrant PI3K in Cancer: Calculation started
Constitutive Signaling by Aberrant PI3K in Cancer: scoring computed

Calculating pathways:  18%|█▊        | 147/796 [12:19<48:14,  4.46s/it]

Constitutive Signaling by Aberrant PI3K in Cancer: pvalue calculation completed
Constitutive Signaling by Aberrant PI3K in Cancer: Calculation completed
Constitutive Signaling by Overexpressed ERBB2: Calculation started
Constitutive Signaling by Overexpressed ERBB2: scoring computed

Calculating pathways:  19%|█▊        | 148/796 [12:22<44:40,  4.14s/it]

Constitutive Signaling by Overexpressed ERBB2: pvalue calculation completed
Constitutive Signaling by Overexpressed ERBB2: Calculation completed
Costimulation by the CD28 Family: Calculation started
Costimulation by the CD28 Family: scoring computed

Calculating pathways:  19%|█▊        | 149/796 [12:26<44:31,  4.13s/it]

Costimulation by the CD28 Family: pvalue calculation completed
Costimulation by the CD28 Family: Calculation completed
Cytokine Signaling in Immune System: Calculation started
Cytokine Signaling in Immune System: scoring computed

Calculating pathways:  19%|█▉        | 150/796 [12:37<1:05:54,  6.12s/it]

Cytokine Signaling in Immune System: pvalue calculation completed
Cytokine Signaling in Immune System: Calculation completed
Cytoprotection by HMOX1: Calculation started
Cytoprotection by HMOX1: scoring computed

Calculating pathways:  19%|█▉        | 151/796 [12:41<58:34,  5.45s/it]

Cytoprotection by HMOX1: pvalue calculation completed
Cytoprotection by HMOX1: Calculation completed
DAP12 Interactions: Calculation started
DAP12 Interactions: scoring computed

Calculating pathways:  19%|█▉        | 152/796 [12:45<53:26,  4.98s/it]

DAP12 Interactions: pvalue calculation completed
DAP12 Interactions: Calculation completed
DAP12 Signaling: Calculation started
DAP12 Signaling: scoring computed

Calculating pathways:  19%|█▉        | 153/796 [12:48<49:14,  4.59s/it]

DAP12 Signaling: pvalue calculation completed
DAP12 Signaling: Calculation completed
DCC Mediated Attractive Signaling: Calculation started
DCC Mediated Attractive Signaling: scoring computed

Calculating pathways:  19%|█▉        | 154/796 [12:52<45:23,  4.24s/it]

DCC Mediated Attractive Signaling: pvalue calculation completed
DCC Mediated Attractive Signaling: Calculation completed
Dectin-2 Family: Calculation started
Dectin-2 Family: scoring computed

Calculating pathways:  19%|█▉        | 155/796 [12:55<42:48,  4.01s/it]

Dectin-2 Family: pvalue calculation completed
Dectin-2 Family: Calculation completed
Degradation of the Extracellular Matrix: Calculation started
Degradation of the Extracellular Matrix: scoring computed

Calculating pathways:  20%|█▉        | 156/796 [13:00<45:12,  4.24s/it]

Degradation of the Extracellular Matrix: pvalue calculation completed
Degradation of the Extracellular Matrix: Calculation completed
Developmental Biology: Calculation started
Developmental Biology: scoring computed

Calculating pathways:  20%|█▉        | 157/796 [13:15<1:18:13,  7.34s/it]

Developmental Biology: pvalue calculation completed
Developmental Biology: Calculation completed
Diseases of Signal Transduction by Growth Factor Receptors and Second Messengers: Calculation started
Diseases of Signal Transduction by Growth Factor Receptors and Second Messengers: scoring computed

Calculating pathways:  20%|█▉        | 158/796 [13:23<1:20:37,  7.58s/it]

Diseases of Signal Transduction by Growth Factor Receptors and Second Messengers: pvalue calculation completed
Diseases of Signal Transduction by Growth Factor Receptors and Second Messengers: Calculation completed
Disorders of Transmembrane Transporters: Calculation started
Disorders of Transmembrane Transporters: scoring computed

Calculating pathways:  20%|█▉        | 159/796 [13:28<1:12:19,  6.81s/it]

Disorders of Transmembrane Transporters: pvalue calculation completed
Disorders of Transmembrane Transporters: Calculation completed
Downregulation of ERBB2 Signaling: Calculation started
Downregulation of ERBB2 Signaling: scoring computed

Calculating pathways:  20%|██        | 160/796 [13:31<1:02:14,  5.87s/it]

Downregulation of ERBB2 Signaling: pvalue calculation completed
Downregulation of ERBB2 Signaling: Calculation completed
Downregulation of ERBB2 ERBB3 Signaling: Calculation started
Downregulation of ERBB2 ERBB3 Signaling: scoring computed

Calculating pathways:  20%|██        | 161/796 [13:35<54:21,  5.14s/it]

Downregulation of ERBB2 ERBB3 Signaling: pvalue calculation completed
Downregulation of ERBB2 ERBB3 Signaling: Calculation completed
Downstream TCR Signaling: Calculation started
Downstream TCR Signaling: scoring computed

Calculating pathways:  20%|██        | 162/796 [13:39<51:38,  4.89s/it]

Downstream TCR Signaling: pvalue calculation completed
Downstream TCR Signaling: Calculation completed
Drug ADME: Calculation started
Drug ADME: scoring computed

Calculating pathways:  20%|██        | 163/796 [13:43<49:36,  4.70s/it]

Drug ADME: pvalue calculation completed
Drug ADME: Calculation completed
EPH-Ephrin Signaling: Calculation started
EPH-Ephrin Signaling: scoring computed

Calculating pathways:  21%|██        | 164/796 [13:48<48:27,  4.60s/it]

EPH-Ephrin Signaling: pvalue calculation completed
EPH-Ephrin Signaling: Calculation completed
EPH-ephrin Mediated Repulsion of Cells: Calculation started
EPH-ephrin Mediated Repulsion of Cells: scoring computed

Calculating pathways:  21%|██        | 165/796 [13:52<46:29,  4.42s/it]

EPH-ephrin Mediated Repulsion of Cells: pvalue calculation completed
EPH-ephrin Mediated Repulsion of Cells: Calculation completed
EPHA-mediated Growth Cone Collapse: Calculation started
EPHA-mediated Growth Cone Collapse: scoring computed

Calculating pathways:  21%|██        | 166/796 [13:56<44:11,  4.21s/it]

EPHA-mediated Growth Cone Collapse: pvalue calculation completed
EPHA-mediated Growth Cone Collapse: Calculation completed
EPHB-mediated Forward Signaling: Calculation started
EPHB-mediated Forward Signaling: scoring computed

Calculating pathways:  21%|██        | 167/796 [13:59<42:45,  4.08s/it]

EPHB-mediated Forward Signaling: pvalue calculation completed
EPHB-mediated Forward Signaling: Calculation completed
ERBB2 Activates PTK6 Signaling: Calculation started
ERBB2 Activates PTK6 Signaling: scoring computed

Calculating pathways:  21%|██        | 168/796 [14:03<40:42,  3.89s/it]

ERBB2 Activates PTK6 Signaling: pvalue calculation completed
ERBB2 Activates PTK6 Signaling: Calculation completed
ERBB2 Regulates Cell Motility: Calculation started
ERBB2 Regulates Cell Motility: scoring computed

Calculating pathways:  21%|██        | 169/796 [14:06<39:20,  3.76s/it]

ERBB2 Regulates Cell Motility: pvalue calculation completed
ERBB2 Regulates Cell Motility: Calculation completed
ESR-mediated Signaling: Calculation started
ESR-mediated Signaling: scoring computed

Calculating pathways:  21%|██▏       | 170/796 [14:12<44:20,  4.25s/it]

ESR-mediated Signaling: pvalue calculation completed
ESR-mediated Signaling: Calculation completed
Ephrin Signaling: Calculation started
Ephrin Signaling: scoring computed

Calculating pathways:  21%|██▏       | 171/796 [14:15<42:01,  4.03s/it]

Ephrin Signaling: pvalue calculation completed
Ephrin Signaling: Calculation completed
Extension of Telomeres: Calculation started
Extension of Telomeres: scoring computed

Calculating pathways:  22%|██▏       | 172/796 [14:19<41:44,  4.01s/it]

Extension of Telomeres: pvalue calculation completed
Extension of Telomeres: Calculation completed
Extra-nuclear Estrogen Signaling: Calculation started
Extra-nuclear Estrogen Signaling: scoring computed

Calculating pathways:  22%|██▏       | 173/796 [14:23<42:12,  4.06s/it]

Extra-nuclear Estrogen Signaling: pvalue calculation completed
Extra-nuclear Estrogen Signaling: Calculation completed
Extracellular Matrix Organization: Calculation started
Extracellular Matrix Organization: scoring computed

Calculating pathways:  22%|██▏       | 174/796 [14:30<49:04,  4.73s/it]

Extracellular Matrix Organization: pvalue calculation completed
Extracellular Matrix Organization: Calculation completed
FBXL7 Down-Regulates AURKA During Mitotic Entry and in Early Mitosis: Calculation started
FBXL7 Down-Regulates AURKA During Mitotic Entry and in Early Mitosis: scoring computed

Calculating pathways:  22%|██▏       | 175/796 [14:33<46:03,  4.45s/it]

FBXL7 Down-Regulates AURKA During Mitotic Entry and in Early Mitosis: pvalue calculation completed
FBXL7 Down-Regulates AURKA During Mitotic Entry and in Early Mitosis: Calculation completed
FCGR Activation: Calculation started
FCGR Activation: scoring computed

Calculating pathways:  22%|██▏       | 176/796 [14:37<43:22,  4.20s/it]

FCGR Activation: pvalue calculation completed
FCGR Activation: Calculation completed
FCGR3A-mediated IL10 Synthesis: Calculation started
FCGR3A-mediated IL10 Synthesis: scoring computed

Calculating pathways:  22%|██▏       | 177/796 [14:41<42:07,  4.08s/it]

FCGR3A-mediated IL10 Synthesis: pvalue calculation completed
FCGR3A-mediated IL10 Synthesis: Calculation completed
FCGR3A-mediated Phagocytosis: Calculation started
FCGR3A-mediated Phagocytosis: scoring computed

Calculating pathways:  22%|██▏       | 178/796 [14:45<42:14,  4.10s/it]

FCGR3A-mediated Phagocytosis: pvalue calculation completed
FCGR3A-mediated Phagocytosis: Calculation completed
FLT3 Signaling: Calculation started
FLT3 Signaling: scoring computed

Calculating pathways:  22%|██▏       | 179/796 [14:49<41:31,  4.04s/it]

FLT3 Signaling: pvalue calculation completed
FLT3 Signaling: Calculation completed
FLT3 Signaling Through SRC Family Kinases: Calculation started
FLT3 Signaling Through SRC Family Kinases: scoring computed

Calculating pathways:  23%|██▎       | 180/796 [14:52<39:18,  3.83s/it]

FLT3 Signaling Through SRC Family Kinases: pvalue calculation completed
FLT3 Signaling Through SRC Family Kinases: Calculation completed
Fc Epsilon Receptor (FCERI) Signaling: Calculation started
Fc Epsilon Receptor (FCERI) Signaling: scoring computed

Calculating pathways:  23%|██▎       | 181/796 [14:57<41:59,  4.10s/it]

Fc Epsilon Receptor (FCERI) Signaling: pvalue calculation completed
Fc Epsilon Receptor (FCERI) Signaling: Calculation completed
Fcgamma Receptor (FCGR) Dependent Phagocytosis: Calculation started
Fcgamma Receptor (FCGR) Dependent Phagocytosis: scoring computed

Calculating pathways:  23%|██▎       | 182/796 [15:01<42:55,  4.20s/it]

Fcgamma Receptor (FCGR) Dependent Phagocytosis: pvalue calculation completed
Fcgamma Receptor (FCGR) Dependent Phagocytosis: Calculation completed
Formation of the Beta-Catenin TCF Transactivating Complex: Calculation started
Formation of the Beta-Catenin TCF Transactivating Complex: scoring computed

Calculating pathways:  23%|██▎       | 183/796 [15:05<41:37,  4.07s/it]

Formation of the Beta-Catenin TCF Transactivating Complex: pvalue calculation completed
Formation of the Beta-Catenin TCF Transactivating Complex: Calculation completed
G Alpha (I) Signalling Events: Calculation started
G Alpha (I) Signalling Events: scoring computed

Calculating pathways:  23%|██▎       | 184/796 [15:11<47:41,  4.68s/it]

G Alpha (I) Signalling Events: pvalue calculation completed
G Alpha (I) Signalling Events: Calculation completed
G Alpha (Q) Signalling Events: Calculation started
G Alpha (Q) Signalling Events: scoring computed

Calculating pathways:  23%|██▎       | 185/796 [15:17<49:54,  4.90s/it]

G Alpha (Q) Signalling Events: pvalue calculation completed
G Alpha (Q) Signalling Events: Calculation completed
G Alpha (S) Signalling Events: Calculation started
G Alpha (S) Signalling Events: scoring computed

Calculating pathways:  23%|██▎       | 186/796 [15:21<48:43,  4.79s/it]

G Alpha (S) Signalling Events: pvalue calculation completed
G Alpha (S) Signalling Events: Calculation completed
G0 and Early G1: Calculation started
G0 and Early G1: scoring computed

Calculating pathways:  23%|██▎       | 187/796 [15:25<45:03,  4.44s/it]

G0 and Early G1: pvalue calculation completed
G0 and Early G1: Calculation completed
G2 M Transition: Calculation started
G2 M Transition: scoring computed

Calculating pathways:  24%|██▎       | 188/796 [15:31<49:05,  4.84s/it]

G2 M Transition: pvalue calculation completed
G2 M Transition: Calculation completed
GPCR Downstream Signalling: Calculation started
GPCR Downstream Signalling: scoring computed

Calculating pathways:  24%|██▎       | 189/796 [15:40<1:02:54,  6.22s/it]

GPCR Downstream Signalling: pvalue calculation completed
GPCR Downstream Signalling: Calculation completed
GPCR Ligand Binding: Calculation started
GPCR Ligand Binding: scoring computed

Calculating pathways:  24%|██▍       | 190/796 [15:48<1:06:52,  6.62s/it]

GPCR Ligand Binding: pvalue calculation completed
GPCR Ligand Binding: Calculation completed
GPVI-mediated Activation Cascade: Calculation started
GPVI-mediated Activation Cascade: scoring computed

Calculating pathways:  24%|██▍       | 191/796 [15:52<58:40,  5.82s/it]

GPVI-mediated Activation Cascade: pvalue calculation completed
GPVI-mediated Activation Cascade: Calculation completed
GRB2 Events in ERBB2 Signaling: Calculation started
GRB2 Events in ERBB2 Signaling: scoring computed

Calculating pathways:  24%|██▍       | 192/796 [15:55<52:12,  5.19s/it]

GRB2 Events in ERBB2 Signaling: pvalue calculation completed
GRB2 Events in ERBB2 Signaling: Calculation completed
GRB7 Events in ERBB2 Signaling: Calculation started
GRB7 Events in ERBB2 Signaling: scoring computed

Calculating pathways:  24%|██▍       | 193/796 [15:59<47:24,  4.72s/it]

GRB7 Events in ERBB2 Signaling: pvalue calculation completed
GRB7 Events in ERBB2 Signaling: Calculation completed
Gene Expression (Transcription): Calculation started
Gene Expression (Transcription): scoring computed

Calculating pathways:  24%|██▍       | 194/796 [16:19<1:34:04,  9.38s/it]

Gene Expression (Transcription): pvalue calculation completed
Gene Expression (Transcription): Calculation completed
Generation of Second Messenger Molecules: Calculation started
Generation of Second Messenger Molecules: scoring computed

Calculating pathways:  24%|██▍       | 195/796 [16:23<1:17:50,  7.77s/it]

Generation of Second Messenger Molecules: pvalue calculation completed
Generation of Second Messenger Molecules: Calculation completed
Generic Transcription Pathway: Calculation started
Generic Transcription Pathway: scoring computed

Calculating pathways:  25%|██▍       | 196/796 [16:41<1:47:40, 10.77s/it]

Generic Transcription Pathway: pvalue calculation completed
Generic Transcription Pathway: Calculation completed
HIV Infection: Calculation started
HIV Infection: scoring computed

Calculating pathways:  25%|██▍       | 197/796 [16:47<1:34:52,  9.50s/it]

HIV Infection: pvalue calculation completed
HIV Infection: Calculation completed
Heme Biosynthesis: Calculation started
Heme Biosynthesis: scoring computed

Calculating pathways:  25%|██▍       | 198/796 [16:51<1:18:10,  7.84s/it]

Heme Biosynthesis: pvalue calculation completed
Heme Biosynthesis: Calculation completed
Heme Degradation: Calculation started
Heme Degradation: scoring computed

Calculating pathways:  25%|██▌       | 199/796 [16:55<1:05:23,  6.57s/it]

Heme Degradation: pvalue calculation completed
Heme Degradation: Calculation completed
Hemostasis: Calculation started
Hemostasis: scoring computed

Calculating pathways:  25%|██▌       | 200/796 [17:05<1:16:30,  7.70s/it]

Hemostasis: pvalue calculation completed
Hemostasis: Calculation completed
High Laminar Flow Shear Stress Activates Signaling by PIEZO1 and PECAM1 CDH5 KDR in Endothelial Cell: Calculation started
High Laminar Flow Shear Stress Activates Signaling by PIEZO1 and PECAM1 CDH5 KDR in Endothelial Cell: scoring computed

Calculating pathways:  25%|██▌       | 201/796 [17:10<1:05:51,  6.64s/it]

High Laminar Flow Shear Stress Activates Signaling by PIEZO1 and PECAM1 CDH5 KDR in Endothelial Cell: pvalue calculation completed
High Laminar Flow Shear Stress Activates Signaling by PIEZO1 and PECAM1 CDH5 KDR in Endothelial Cell: Calculation completed
Host Interactions of HIV Factors: Calculation started
Host Interactions of HIV Factors: scoring computed

Calculating pathways:  25%|██▌       | 202/796 [17:15<1:01:16,  6.19s/it]

Host Interactions of HIV Factors: pvalue calculation completed
Host Interactions of HIV Factors: Calculation completed
Infectious Disease: Calculation started
Infectious Disease: scoring computed

Calculating pathways:  26%|██▌       | 203/796 [17:29<1:25:31,  8.65s/it]

Infectious Disease: pvalue calculation completed
Infectious Disease: Calculation completed
Inflammasomes: Calculation started
Inflammasomes: scoring computed

Calculating pathways:  26%|██▌       | 204/796 [17:33<1:11:02,  7.20s/it]

Inflammasomes: pvalue calculation completed
Inflammasomes: Calculation completed
Innate Immune System: Calculation started
Innate Immune System: scoring computed

Calculating pathways:  26%|██▌       | 205/796 [17:47<1:32:16,  9.37s/it]

Innate Immune System: pvalue calculation completed
Innate Immune System: Calculation completed
Interleukin-1 Family Signaling: Calculation started
Interleukin-1 Family Signaling: scoring computed

Calculating pathways:  26%|██▌       | 206/796 [17:52<1:19:48,  8.12s/it]

Interleukin-1 Family Signaling: pvalue calculation completed
Interleukin-1 Family Signaling: Calculation completed
Interleukin-1 Processing: Calculation started
Interleukin-1 Processing: scoring computed

Calculating pathways:  26%|██▌       | 207/796 [17:56<1:06:02,  6.73s/it]

Interleukin-1 Processing: pvalue calculation completed
Interleukin-1 Processing: Calculation completed
Interleukin-2 Family Signaling: Calculation started
Interleukin-2 Family Signaling: scoring computed

Calculating pathways:  26%|██▌       | 208/796 [18:00<57:24,  5.86s/it]

Interleukin-2 Family Signaling: pvalue calculation completed
Interleukin-2 Family Signaling: Calculation completed
Interleukin-2 Signaling: Calculation started
Interleukin-2 Signaling: scoring computed

Calculating pathways:  26%|██▋       | 209/796 [18:03<50:56,  5.21s/it]

Interleukin-2 Signaling: pvalue calculation completed
Interleukin-2 Signaling: Calculation completed
Interleukin-3, Interleukin-5 and GM-CSF Signaling: Calculation started
Interleukin-3, Interleukin-5 and GM-CSF Signaling: scoring computed

Calculating pathways:  26%|██▋       | 210/796 [18:07<47:03,  4.82s/it]

Interleukin-3, Interleukin-5 and GM-CSF Signaling: pvalue calculation completed
Interleukin-3, Interleukin-5 and GM-CSF Signaling: Calculation completed
Interleukin-37 Signaling: Calculation started
Interleukin-37 Signaling: scoring computed

Calculating pathways:  27%|██▋       | 211/796 [18:11<43:26,  4.46s/it]

Interleukin-37 Signaling: pvalue calculation completed
Interleukin-37 Signaling: Calculation completed
Interleukin-4 and Interleukin-13 Signaling: Calculation started
Interleukin-4 and Interleukin-13 Signaling: scoring computed

Calculating pathways:  27%|██▋       | 212/796 [18:16<44:04,  4.53s/it]

Interleukin-4 and Interleukin-13 Signaling: pvalue calculation completed
Interleukin-4 and Interleukin-13 Signaling: Calculation completed
Intracellular Signaling by Second Messengers: Calculation started
Intracellular Signaling by Second Messengers: scoring computed

Calculating pathways:  27%|██▋       | 213/796 [18:23<51:26,  5.29s/it]

Intracellular Signaling by Second Messengers: pvalue calculation completed
Intracellular Signaling by Second Messengers: Calculation completed
Iron Uptake and Transport: Calculation started
Iron Uptake and Transport: scoring computed

Calculating pathways:  27%|██▋       | 214/796 [18:27<47:51,  4.93s/it]

Iron Uptake and Transport: pvalue calculation completed
Iron Uptake and Transport: Calculation completed
KEAP1-NFE2L2 Pathway: Calculation started
KEAP1-NFE2L2 Pathway: scoring computed

Calculating pathways:  27%|██▋       | 215/796 [18:32<47:33,  4.91s/it]

KEAP1-NFE2L2 Pathway: pvalue calculation completed
KEAP1-NFE2L2 Pathway: Calculation completed
Late Endosomal Microautophagy: Calculation started
Late Endosomal Microautophagy: scoring computed

Calculating pathways:  27%|██▋       | 216/796 [18:35<44:06,  4.56s/it]

Late Endosomal Microautophagy: pvalue calculation completed
Late Endosomal Microautophagy: Calculation completed
Leishmania Infection: Calculation started
Leishmania Infection: scoring computed

Calculating pathways:  27%|██▋       | 217/796 [18:41<47:22,  4.91s/it]

Leishmania Infection: pvalue calculation completed
Leishmania Infection: Calculation completed
Leishmania Parasite Growth and Survival: Calculation started
Leishmania Parasite Growth and Survival: scoring computed

Calculating pathways:  27%|██▋       | 218/796 [18:46<46:44,  4.85s/it]

Leishmania Parasite Growth and Survival: pvalue calculation completed
Leishmania Parasite Growth and Survival: Calculation completed
Leishmania Phagocytosis: Calculation started
Leishmania Phagocytosis: scoring computed

Calculating pathways:  28%|██▊       | 219/796 [18:50<44:59,  4.68s/it]

Leishmania Phagocytosis: pvalue calculation completed
Leishmania Phagocytosis: Calculation completed
MAPK Family Signaling Cascades: Calculation started
MAPK Family Signaling Cascades: scoring computed

Calculating pathways:  28%|██▊       | 220/796 [18:57<52:10,  5.44s/it]

MAPK Family Signaling Cascades: pvalue calculation completed
MAPK Family Signaling Cascades: Calculation completed
MAPK1 MAPK3 Signaling: Calculation started
MAPK1 MAPK3 Signaling: scoring computed

Calculating pathways:  28%|██▊       | 221/796 [19:04<55:39,  5.81s/it]

MAPK1 MAPK3 Signaling: pvalue calculation completed
MAPK1 MAPK3 Signaling: Calculation completed
MAPK6 MAPK4 Signaling: Calculation started
MAPK6 MAPK4 Signaling: scoring computed

Calculating pathways:  28%|██▊       | 222/796 [19:08<51:16,  5.36s/it]

MAPK6 MAPK4 Signaling: pvalue calculation completed
MAPK6 MAPK4 Signaling: Calculation completed
MITF-M-dependent Gene Expression: Calculation started
MITF-M-dependent Gene Expression: scoring computed

Calculating pathways:  28%|██▊       | 223/796 [19:13<49:01,  5.13s/it]

MITF-M-dependent Gene Expression: pvalue calculation completed
MITF-M-dependent Gene Expression: Calculation completed
MITF-M-regulated Melanocyte Development: Calculation started
MITF-M-regulated Melanocyte Development: scoring computed

Calculating pathways:  28%|██▊       | 224/796 [19:18<49:14,  5.17s/it]

MITF-M-regulated Melanocyte Development: pvalue calculation completed
MITF-M-regulated Melanocyte Development: Calculation completed
Metabolism of Lipids: Calculation started
Metabolism of Lipids: scoring computed

Calculating pathways:  28%|██▊       | 225/796 [19:30<1:07:39,  7.11s/it]

Metabolism of Lipids: pvalue calculation completed
Metabolism of Lipids: Calculation completed
Metabolism of Porphyrins: Calculation started
Metabolism of Porphyrins: scoring computed

Calculating pathways:  28%|██▊       | 226/796 [19:34<57:54,  6.10s/it]

Metabolism of Porphyrins: pvalue calculation completed
Metabolism of Porphyrins: Calculation completed
Metabolism of Vitamins and Cofactors: Calculation started
Metabolism of Vitamins and Cofactors: scoring computed

Calculating pathways:  29%|██▊       | 227/796 [19:40<57:16,  6.04s/it]

Metabolism of Vitamins and Cofactors: pvalue calculation completed
Metabolism of Vitamins and Cofactors: Calculation completed
Metabolism of Water-Soluble Vitamins and Cofactors: Calculation started
Metabolism of Water-Soluble Vitamins and Cofactors: scoring computed

Calculating pathways:  29%|██▊       | 228/796 [19:45<54:43,  5.78s/it]

Metabolism of Water-Soluble Vitamins and Cofactors: pvalue calculation completed
Metabolism of Water-Soluble Vitamins and Cofactors: Calculation completed
Mitotic G1 Phase and G1 S Transition: Calculation started
Mitotic G1 Phase and G1 S Transition: scoring computed

Calculating pathways:  29%|██▉       | 229/796 [19:50<53:32,  5.67s/it]

Mitotic G1 Phase and G1 S Transition: pvalue calculation completed
Mitotic G1 Phase and G1 S Transition: Calculation completed
Mitotic G2-G2 M Phases: Calculation started
Mitotic G2-G2 M Phases: scoring computed

Calculating pathways:  29%|██▉       | 230/796 [19:56<54:06,  5.74s/it]

Mitotic G2-G2 M Phases: pvalue calculation completed
Mitotic G2-G2 M Phases: Calculation completed
Muscarinic Acetylcholine Receptors: Calculation started
Muscarinic Acetylcholine Receptors: scoring computed

Calculating pathways:  29%|██▉       | 231/796 [19:59<47:43,  5.07s/it]

Muscarinic Acetylcholine Receptors: pvalue calculation completed
Muscarinic Acetylcholine Receptors: Calculation completed
NCAM Signaling for Neurite Out-Growth: Calculation started
NCAM Signaling for Neurite Out-Growth: scoring computed

Calculating pathways:  29%|██▉       | 232/796 [20:04<45:24,  4.83s/it]

NCAM Signaling for Neurite Out-Growth: pvalue calculation completed
NCAM Signaling for Neurite Out-Growth: Calculation completed
NFE2L2 Regulating MDR Associated Enzymes: Calculation started
NFE2L2 Regulating MDR Associated Enzymes: scoring computed

Calculating pathways:  29%|██▉       | 233/796 [20:07<41:39,  4.44s/it]

NFE2L2 Regulating MDR Associated Enzymes: pvalue calculation completed
NFE2L2 Regulating MDR Associated Enzymes: Calculation completed
NOD1 2 Signaling Pathway: Calculation started
NOD1 2 Signaling Pathway: scoring computed

Calculating pathways:  29%|██▉       | 234/796 [20:11<40:36,  4.34s/it]

NOD1 2 Signaling Pathway: pvalue calculation completed
NOD1 2 Signaling Pathway: Calculation completed
NTRK2 Activates RAC1: Calculation started
NTRK2 Activates RAC1: scoring computed

Calculating pathways:  30%|██▉       | 235/796 [20:15<38:21,  4.10s/it]

NTRK2 Activates RAC1: pvalue calculation completed
NTRK2 Activates RAC1: Calculation completed
Nef Mediated CD4 Down-regulation: Calculation started
Nef Mediated CD4 Down-regulation: scoring computed

Calculating pathways:  30%|██▉       | 236/796 [20:19<36:46,  3.94s/it]

Nef Mediated CD4 Down-regulation: pvalue calculation completed
Nef Mediated CD4 Down-regulation: Calculation completed
Nef and Signal Transduction: Calculation started
Nef and Signal Transduction: scoring computed

Calculating pathways:  30%|██▉       | 237/796 [20:22<35:42,  3.83s/it]

Nef and Signal Transduction: pvalue calculation completed
Nef and Signal Transduction: Calculation completed
Nef-mediates Down Modulation of Cell Surface Receptors by Recruiting Them to Clathrin Adapters: Calculation started
Nef-mediates Down Modulation of Cell Surface Receptors by Recruiting Them to Clathrin Adapters: scoring computed

Calculating pathways:  30%|██▉       | 238/796 [20:26<35:06,  3.77s/it]

Nef-mediates Down Modulation of Cell Surface Receptors by Recruiting Them to Clathrin Adapters: pvalue calculation completed
Nef-mediates Down Modulation of Cell Surface Receptors by Recruiting Them to Clathrin Adapters: Calculation completed
Negative Regulation of the PI3K AKT Network: Calculation started
Negative Regulation of the PI3K AKT Network: scoring computed

Calculating pathways:  30%|███       | 239/796 [20:31<38:14,  4.12s/it]

Negative Regulation of the PI3K AKT Network: pvalue calculation completed
Negative Regulation of the PI3K AKT Network: Calculation completed
Nephrin Family Interactions: Calculation started
Nephrin Family Interactions: scoring computed

Calculating pathways:  30%|███       | 240/796 [20:34<37:23,  4.03s/it]

Nephrin Family Interactions: pvalue calculation completed
Nephrin Family Interactions: Calculation completed
Nervous System Development: Calculation started
Nervous System Development: scoring computed

Calculating pathways:  30%|███       | 241/796 [20:44<53:17,  5.76s/it]

Nervous System Development: pvalue calculation completed
Nervous System Development: Calculation completed
Netrin-1 Signaling: Calculation started
Netrin-1 Signaling: scoring computed

Calculating pathways:  30%|███       | 242/796 [20:48<48:18,  5.23s/it]

Netrin-1 Signaling: pvalue calculation completed
Netrin-1 Signaling: Calculation completed
Nuclear Events Mediated by NFE2L2: Calculation started
Nuclear Events Mediated by NFE2L2: scoring computed

Calculating pathways:  31%|███       | 243/796 [20:53<46:40,  5.06s/it]

Nuclear Events Mediated by NFE2L2: pvalue calculation completed
Nuclear Events Mediated by NFE2L2: Calculation completed
Nucleotide-binding Domain, Leucine Rich Repeat Containing Receptor (NLR) Signaling Pathways: Calculation started
Nucleotide-binding Domain, Leucine Rich Repeat Containing Receptor (NLR) Signaling Pathways: scoring computed

Calculating pathways:  31%|███       | 244/796 [20:57<44:05,  4.79s/it]

Nucleotide-binding Domain, Leucine Rich Repeat Containing Receptor (NLR) Signaling Pathways: pvalue calculation completed
Nucleotide-binding Domain, Leucine Rich Repeat Containing Receptor (NLR) Signaling Pathways: Calculation completed
PD-1 Signaling: Calculation started
PD-1 Signaling: scoring computed

Calculating pathways:  31%|███       | 245/796 [21:01<41:02,  4.47s/it]

PD-1 Signaling: pvalue calculation completed
PD-1 Signaling: Calculation completed
PECAM1 Interactions: Calculation started
PECAM1 Interactions: scoring computed

Calculating pathways:  31%|███       | 246/796 [21:04<38:22,  4.19s/it]

PECAM1 Interactions: pvalue calculation completed
PECAM1 Interactions: Calculation completed
PI3K Events in ERBB2 Signaling: Calculation started
PI3K Events in ERBB2 Signaling: scoring computed

Calculating pathways:  31%|███       | 247/796 [21:08<36:44,  4.02s/it]

PI3K Events in ERBB2 Signaling: pvalue calculation completed
PI3K Events in ERBB2 Signaling: Calculation completed
PI3K AKT Signaling in Cancer: Calculation started
PI3K AKT Signaling in Cancer: scoring computed

Calculating pathways:  31%|███       | 248/796 [21:13<38:36,  4.23s/it]

PI3K AKT Signaling in Cancer: pvalue calculation completed
PI3K AKT Signaling in Cancer: Calculation completed
PI5P, PP2A and IER3 Regulate PI3K AKT Signaling: Calculation started
PI5P, PP2A and IER3 Regulate PI3K AKT Signaling: scoring computed

Calculating pathways:  31%|███▏      | 249/796 [21:17<40:04,  4.40s/it]

PI5P, PP2A and IER3 Regulate PI3K AKT Signaling: pvalue calculation completed
PI5P, PP2A and IER3 Regulate PI3K AKT Signaling: Calculation completed
PIP3 Activates AKT Signaling: Calculation started
PIP3 Activates AKT Signaling: scoring computed

Calculating pathways:  31%|███▏      | 250/796 [21:24<46:19,  5.09s/it]

PIP3 Activates AKT Signaling: pvalue calculation completed
PIP3 Activates AKT Signaling: Calculation completed
Paracetamol ADME: Calculation started
Paracetamol ADME: scoring computed

Calculating pathways:  32%|███▏      | 251/796 [21:28<42:25,  4.67s/it]

Paracetamol ADME: pvalue calculation completed
Paracetamol ADME: Calculation completed
Parasite Infection: Calculation started
Parasite Infection: scoring computed

Calculating pathways:  32%|███▏      | 252/796 [21:32<41:26,  4.57s/it]

Parasite Infection: pvalue calculation completed
Parasite Infection: Calculation completed
Parasitic Infection Pathways: Calculation started
Parasitic Infection Pathways: scoring computed

Calculating pathways:  32%|███▏      | 253/796 [21:38<44:37,  4.93s/it]

Parasitic Infection Pathways: pvalue calculation completed
Parasitic Infection Pathways: Calculation completed
Phosphorylation of CD3 and TCR Zeta Chains: Calculation started
Phosphorylation of CD3 and TCR Zeta Chains: scoring computed

Calculating pathways:  32%|███▏      | 254/796 [21:42<41:04,  4.55s/it]

Phosphorylation of CD3 and TCR Zeta Chains: pvalue calculation completed
Phosphorylation of CD3 and TCR Zeta Chains: Calculation completed
Platelet Adhesion to Exposed Collagen: Calculation started
Platelet Adhesion to Exposed Collagen: scoring computed

Calculating pathways:  32%|███▏      | 255/796 [21:45<38:52,  4.31s/it]

Platelet Adhesion to Exposed Collagen: pvalue calculation completed
Platelet Adhesion to Exposed Collagen: Calculation completed
Platelet Activation, Signaling and Aggregation: Calculation started
Platelet Activation, Signaling and Aggregation: scoring computed

Calculating pathways:  32%|███▏      | 256/796 [21:52<44:56,  4.99s/it]

Platelet Activation, Signaling and Aggregation: pvalue calculation completed
Platelet Activation, Signaling and Aggregation: Calculation completed
Post-translational Protein Modification: Calculation started
Post-translational Protein Modification: scoring computed

Calculating pathways:  32%|███▏      | 257/796 [22:11<1:21:29,  9.07s/it]

Post-translational Protein Modification: pvalue calculation completed
Post-translational Protein Modification: Calculation completed
Prednisone ADME: Calculation started
Prednisone ADME: scoring computed

Calculating pathways:  32%|███▏      | 258/796 [22:14<1:06:09,  7.38s/it]

Prednisone ADME: pvalue calculation completed
Prednisone ADME: Calculation completed
Programmed Cell Death: Calculation started
Programmed Cell Death: scoring computed

Calculating pathways:  33%|███▎      | 259/796 [22:20<1:02:20,  6.97s/it]

Programmed Cell Death: pvalue calculation completed
Programmed Cell Death: Calculation completed
Purinergic Signaling in Leishmaniasis Infection: Calculation started
Purinergic Signaling in Leishmaniasis Infection: scoring computed

Calculating pathways:  33%|███▎      | 260/796 [22:24<53:34,  6.00s/it]

Purinergic Signaling in Leishmaniasis Infection: pvalue calculation completed
Purinergic Signaling in Leishmaniasis Infection: Calculation completed
Pyroptosis: Calculation started
Pyroptosis: scoring computed

Calculating pathways:  33%|███▎      | 261/796 [22:27<47:15,  5.30s/it]

Pyroptosis: pvalue calculation completed
Pyroptosis: Calculation completed
RAF MAP Kinase Cascade: Calculation started
RAF MAP Kinase Cascade: scoring computed

Calculating pathways:  33%|███▎      | 262/796 [22:34<50:42,  5.70s/it]

RAF MAP Kinase Cascade: pvalue calculation completed
RAF MAP Kinase Cascade: Calculation completed
RHO GTPase Cycle: Calculation started
RHO GTPase Cycle: scoring computed

Calculating pathways:  33%|███▎      | 263/796 [22:43<58:32,  6.59s/it]

RHO GTPase Cycle: pvalue calculation completed
RHO GTPase Cycle: Calculation completed
RHOH GTPase Cycle: Calculation started
RHOH GTPase Cycle: scoring computed

Calculating pathways:  33%|███▎      | 264/796 [22:47<50:57,  5.75s/it]

RHOH GTPase Cycle: pvalue calculation completed
RHOH GTPase Cycle: Calculation completed
RNA Polymerase II Transcription: Calculation started
RNA Polymerase II Transcription: scoring computed

Calculating pathways:  33%|███▎      | 265/796 [23:04<1:22:16,  9.30s/it]

RNA Polymerase II Transcription: pvalue calculation completed
RNA Polymerase II Transcription: Calculation completed
Reelin Signalling Pathway: Calculation started
Reelin Signalling Pathway: scoring computed

Calculating pathways:  33%|███▎      | 266/796 [23:08<1:06:47,  7.56s/it]

Reelin Signalling Pathway: pvalue calculation completed
Reelin Signalling Pathway: Calculation completed
Regulated Necrosis: Calculation started
Regulated Necrosis: scoring computed

Calculating pathways:  34%|███▎      | 267/796 [23:12<57:32,  6.53s/it]

Regulated Necrosis: pvalue calculation completed
Regulated Necrosis: Calculation completed
Regulation of IGF Transport and Uptake by Insulin-like Growth Factor Binding Proteins (IGFBPs): Calculation started
Regulation of IGF Transport and Uptake by Insulin-like Growth Factor Binding Proteins (IGFBPs): scoring computed

Calculating pathways:  34%|███▎      | 268/796 [23:17<53:13,  6.05s/it]

Regulation of IGF Transport and Uptake by Insulin-like Growth Factor Binding Proteins (IGFBPs): pvalue calculation completed
Regulation of IGF Transport and Uptake by Insulin-like Growth Factor Binding Proteins (IGFBPs): Calculation completed
Regulation of KIT Signaling: Calculation started
Regulation of KIT Signaling: scoring computed

Calculating pathways:  34%|███▍      | 269/796 [23:20<46:41,  5.32s/it]

Regulation of KIT Signaling: pvalue calculation completed
Regulation of KIT Signaling: Calculation completed
Regulation of PLK1 Activity at G2 M Transition: Calculation started
Regulation of PLK1 Activity at G2 M Transition: scoring computed

Calculating pathways:  34%|███▍      | 270/796 [23:25<44:18,  5.05s/it]

Regulation of PLK1 Activity at G2 M Transition: pvalue calculation completed
Regulation of PLK1 Activity at G2 M Transition: Calculation completed
Regulation of TP53 Activity: Calculation started
Regulation of TP53 Activity: scoring computed

Calculating pathways:  34%|███▍      | 271/796 [23:30<45:33,  5.21s/it]

Regulation of TP53 Activity: pvalue calculation completed
Regulation of TP53 Activity: Calculation completed
Regulation of TP53 Activity Through Phosphorylation: Calculation started
Regulation of TP53 Activity Through Phosphorylation: scoring computed

Calculating pathways:  34%|███▍      | 272/796 [23:35<44:22,  5.08s/it]

Regulation of TP53 Activity Through Phosphorylation: pvalue calculation completed
Regulation of TP53 Activity Through Phosphorylation: Calculation completed
Regulation of Mitotic Cell Cycle: Calculation started
Regulation of Mitotic Cell Cycle: scoring computed

Calculating pathways:  34%|███▍      | 273/796 [23:40<42:56,  4.93s/it]

Regulation of Mitotic Cell Cycle: pvalue calculation completed
Regulation of Mitotic Cell Cycle: Calculation completed
Regulation of Signaling by CBL: Calculation started
Regulation of Signaling by CBL: scoring computed

Calculating pathways:  34%|███▍      | 274/796 [23:43<39:44,  4.57s/it]

Regulation of Signaling by CBL: pvalue calculation completed
Regulation of Signaling by CBL: Calculation completed
Response of Endothelial Cells to Shear Stress: Calculation started
Response of Endothelial Cells to Shear Stress: scoring computed

Calculating pathways:  35%|███▍      | 275/796 [23:48<39:52,  4.59s/it]

Response of Endothelial Cells to Shear Stress: pvalue calculation completed
Response of Endothelial Cells to Shear Stress: Calculation completed
Role of LAT2 NTAL LAB on Calcium Mobilization: Calculation started
Role of LAT2 NTAL LAB on Calcium Mobilization: scoring computed

Calculating pathways:  35%|███▍      | 276/796 [23:52<37:30,  4.33s/it]

Role of LAT2 NTAL LAB on Calcium Mobilization: pvalue calculation completed
Role of LAT2 NTAL LAB on Calcium Mobilization: Calculation completed
SARS-CoV Infections: Calculation started
SARS-CoV Infections: scoring computed

Calculating pathways:  35%|███▍      | 277/796 [24:00<47:50,  5.53s/it]

SARS-CoV Infections: pvalue calculation completed
SARS-CoV Infections: Calculation completed
SARS-CoV-1 Infection: Calculation started
SARS-CoV-1 Infection: scoring computed

Calculating pathways:  35%|███▍      | 278/796 [24:05<47:19,  5.48s/it]

SARS-CoV-1 Infection: pvalue calculation completed
SARS-CoV-1 Infection: Calculation completed
SARS-CoV-1 Activates Modulates Innate Immune Responses: Calculation started
SARS-CoV-1 Activates Modulates Innate Immune Responses: scoring computed

Calculating pathways:  35%|███▌      | 279/796 [24:10<43:43,  5.07s/it]

SARS-CoV-1 Activates Modulates Innate Immune Responses: pvalue calculation completed
SARS-CoV-1 Activates Modulates Innate Immune Responses: Calculation completed
SARS-CoV-1-host Interactions: Calculation started
SARS-CoV-1-host Interactions: scoring computed

Calculating pathways:  35%|███▌      | 280/796 [24:14<42:37,  4.96s/it]

SARS-CoV-1-host Interactions: pvalue calculation completed
SARS-CoV-1-host Interactions: Calculation completed
SEMA3A-Plexin Repulsion Signaling by Inhibiting Integrin Adhesion: Calculation started
SEMA3A-Plexin Repulsion Signaling by Inhibiting Integrin Adhesion: scoring computed

Calculating pathways:  35%|███▌      | 281/796 [24:18<39:11,  4.57s/it]

SEMA3A-Plexin Repulsion Signaling by Inhibiting Integrin Adhesion: pvalue calculation completed
SEMA3A-Plexin Repulsion Signaling by Inhibiting Integrin Adhesion: Calculation completed
SHC1 Events in ERBB2 Signaling: Calculation started
SHC1 Events in ERBB2 Signaling: scoring computed

Calculating pathways:  35%|███▌      | 282/796 [24:22<37:14,  4.35s/it]

SHC1 Events in ERBB2 Signaling: pvalue calculation completed
SHC1 Events in ERBB2 Signaling: Calculation completed
SUMO E3 Ligases SUMOylate Target Proteins: Calculation started
SUMO E3 Ligases SUMOylate Target Proteins: scoring computed

Calculating pathways:  36%|███▌      | 283/796 [24:27<40:24,  4.73s/it]

SUMO E3 Ligases SUMOylate Target Proteins: pvalue calculation completed
SUMO E3 Ligases SUMOylate Target Proteins: Calculation completed
SUMOylation: Calculation started
SUMOylation: scoring computed

Calculating pathways:  36%|███▌      | 284/796 [24:33<42:57,  5.03s/it]

SUMOylation: pvalue calculation completed
SUMOylation: Calculation completed
SUMOylation of DNA Replication Proteins: Calculation started
SUMOylation of DNA Replication Proteins: scoring computed

Calculating pathways:  36%|███▌      | 285/796 [24:37<40:24,  4.74s/it]

SUMOylation of DNA Replication Proteins: pvalue calculation completed
SUMOylation of DNA Replication Proteins: Calculation completed
Sema3A PAK Dependent Axon Repulsion: Calculation started
Sema3A PAK Dependent Axon Repulsion: scoring computed

Calculating pathways:  36%|███▌      | 286/796 [24:41<37:43,  4.44s/it]

Sema3A PAK Dependent Axon Repulsion: pvalue calculation completed
Sema3A PAK Dependent Axon Repulsion: Calculation completed
Sema4D in Semaphorin Signaling: Calculation started
Sema4D in Semaphorin Signaling: scoring computed

Calculating pathways:  36%|███▌      | 287/796 [24:45<35:40,  4.20s/it]

Sema4D in Semaphorin Signaling: pvalue calculation completed
Sema4D in Semaphorin Signaling: Calculation completed
Sema4D Induced Cell Migration and Growth-Cone Collapse: Calculation started
Sema4D Induced Cell Migration and Growth-Cone Collapse: scoring computed

Calculating pathways:  36%|███▌      | 288/796 [24:48<34:13,  4.04s/it]

Sema4D Induced Cell Migration and Growth-Cone Collapse: pvalue calculation completed
Sema4D Induced Cell Migration and Growth-Cone Collapse: Calculation completed
Semaphorin Interactions: Calculation started
Semaphorin Interactions: scoring computed

Calculating pathways:  36%|███▋      | 289/796 [24:53<35:03,  4.15s/it]

Semaphorin Interactions: pvalue calculation completed
Semaphorin Interactions: Calculation completed
Serotonin Receptors: Calculation started
Serotonin Receptors: scoring computed

Calculating pathways:  36%|███▋      | 290/796 [24:56<33:50,  4.01s/it]

Serotonin Receptors: pvalue calculation completed
Serotonin Receptors: Calculation completed
Signaling by CSF1 (M-CSF) in Myeloid Cells: Calculation started
Signaling by CSF1 (M-CSF) in Myeloid Cells: scoring computed

Calculating pathways:  37%|███▋      | 291/796 [25:00<33:23,  3.97s/it]

Signaling by CSF1 (M-CSF) in Myeloid Cells: pvalue calculation completed
Signaling by CSF1 (M-CSF) in Myeloid Cells: Calculation completed
Signaling by ERBB2: Calculation started
Signaling by ERBB2: scoring computed

Calculating pathways:  37%|███▋      | 292/796 [25:04<33:26,  3.98s/it]

Signaling by ERBB2: pvalue calculation completed
Signaling by ERBB2: Calculation completed
Signaling by ERBB2 ECD Mutants: Calculation started
Signaling by ERBB2 ECD Mutants: scoring computed

Calculating pathways:  37%|███▋      | 293/796 [25:08<32:24,  3.87s/it]

Signaling by ERBB2 ECD Mutants: pvalue calculation completed
Signaling by ERBB2 ECD Mutants: Calculation completed
Signaling by ERBB2 KD Mutants: Calculation started
Signaling by ERBB2 KD Mutants: scoring computed

Calculating pathways:  37%|███▋      | 294/796 [25:12<32:07,  3.84s/it]

Signaling by ERBB2 KD Mutants: pvalue calculation completed
Signaling by ERBB2 KD Mutants: Calculation completed
Signaling by ERBB2 TMD JMD Mutants: Calculation started
Signaling by ERBB2 TMD JMD Mutants: scoring computed

Calculating pathways:  37%|███▋      | 295/796 [25:15<31:45,  3.80s/it]

Signaling by ERBB2 TMD JMD Mutants: pvalue calculation completed
Signaling by ERBB2 TMD JMD Mutants: Calculation completed
Signaling by ERBB2 in Cancer: Calculation started
Signaling by ERBB2 in Cancer: scoring computed

Calculating pathways:  37%|███▋      | 296/796 [25:19<31:40,  3.80s/it]

Signaling by ERBB2 in Cancer: pvalue calculation completed
Signaling by ERBB2 in Cancer: Calculation completed
Signaling by GPCR: Calculation started
Signaling by GPCR: scoring computed

Calculating pathways:  37%|███▋      | 297/796 [25:29<46:51,  5.63s/it]

Signaling by GPCR: pvalue calculation completed
Signaling by GPCR: Calculation completed
Signaling by Interleukins: Calculation started
Signaling by Interleukins: scoring computed

Calculating pathways:  37%|███▋      | 298/796 [25:37<53:17,  6.42s/it]

Signaling by Interleukins: pvalue calculation completed
Signaling by Interleukins: Calculation completed
Signaling by KIT in Disease: Calculation started
Signaling by KIT in Disease: scoring computed

Calculating pathways:  38%|███▊      | 299/796 [25:41<46:15,  5.58s/it]

Signaling by KIT in Disease: pvalue calculation completed
Signaling by KIT in Disease: Calculation completed
Signaling by NTRK2 (TRKB): Calculation started
Signaling by NTRK2 (TRKB): scoring computed

Calculating pathways:  38%|███▊      | 300/796 [25:45<41:30,  5.02s/it]

Signaling by NTRK2 (TRKB): pvalue calculation completed
Signaling by NTRK2 (TRKB): Calculation completed
Signaling by NTRKs: Calculation started
Signaling by NTRKs: scoring computed

Calculating pathways:  38%|███▊      | 301/796 [25:50<41:47,  5.07s/it]

Signaling by NTRKs: pvalue calculation completed
Signaling by NTRKs: Calculation completed
Signaling by Non-Receptor Tyrosine Kinases: Calculation started
Signaling by Non-Receptor Tyrosine Kinases: scoring computed

Calculating pathways:  38%|███▊      | 302/796 [25:54<39:13,  4.76s/it]

Signaling by Non-Receptor Tyrosine Kinases: pvalue calculation completed
Signaling by Non-Receptor Tyrosine Kinases: Calculation completed
Signaling by Nuclear Receptors: Calculation started
Signaling by Nuclear Receptors: scoring computed

Calculating pathways:  38%|███▊      | 303/796 [26:00<43:34,  5.30s/it]

Signaling by Nuclear Receptors: pvalue calculation completed
Signaling by Nuclear Receptors: Calculation completed
Signaling by PTK6: Calculation started
Signaling by PTK6: scoring computed

Calculating pathways:  38%|███▊      | 304/796 [26:04<40:24,  4.93s/it]

Signaling by PTK6: pvalue calculation completed
Signaling by PTK6: Calculation completed
Signaling by Receptor Tyrosine Kinases: Calculation started
Signaling by Receptor Tyrosine Kinases: scoring computed

Calculating pathways:  38%|███▊      | 305/796 [26:14<51:37,  6.31s/it]

Signaling by Receptor Tyrosine Kinases: pvalue calculation completed
Signaling by Receptor Tyrosine Kinases: Calculation completed
Signaling by Rho GTPases: Calculation started
Signaling by Rho GTPases: scoring computed

Calculating pathways:  38%|███▊      | 306/796 [26:25<1:02:51,  7.70s/it]

Signaling by Rho GTPases: pvalue calculation completed
Signaling by Rho GTPases: Calculation completed
Signaling by Rho GTPases, Miro GTPases and RHOBTB3: Calculation started
Signaling by Rho GTPases, Miro GTPases and RHOBTB3: scoring computed

Calculating pathways:  39%|███▊      | 307/796 [26:36<1:11:04,  8.72s/it]

Signaling by Rho GTPases, Miro GTPases and RHOBTB3: pvalue calculation completed
Signaling by Rho GTPases, Miro GTPases and RHOBTB3: Calculation completed
Signaling by SCF-KIT: Calculation started
Signaling by SCF-KIT: scoring computed

Calculating pathways:  39%|███▊      | 308/796 [26:40<59:16,  7.29s/it]

Signaling by SCF-KIT: pvalue calculation completed
Signaling by SCF-KIT: Calculation completed
Signaling by VEGF: Calculation started
Signaling by VEGF: scoring computed

Calculating pathways:  39%|███▉      | 309/796 [26:45<53:39,  6.61s/it]

Signaling by VEGF: pvalue calculation completed
Signaling by VEGF: Calculation completed
Signaling by WNT: Calculation started
Signaling by WNT: scoring computed

Calculating pathways:  39%|███▉      | 310/796 [26:52<54:09,  6.69s/it]

Signaling by WNT: pvalue calculation completed
Signaling by WNT: Calculation completed
Signaling by Phosphorylated Juxtamembrane, Extracellular and Kinase Domain KIT Mutants: Calculation started
Signaling by Phosphorylated Juxtamembrane, Extracellular and Kinase Domain KIT Mutants: scoring computed

Calculating pathways:  39%|███▉      | 311/796 [26:56<46:54,  5.80s/it]

Signaling by Phosphorylated Juxtamembrane, Extracellular and Kinase Domain KIT Mutants: pvalue calculation completed
Signaling by Phosphorylated Juxtamembrane, Extracellular and Kinase Domain KIT Mutants: Calculation completed
Signaling by the B Cell Receptor (BCR): Calculation started
Signaling by the B Cell Receptor (BCR): scoring computed

Calculating pathways:  39%|███▉      | 312/796 [27:01<44:49,  5.56s/it]

Signaling by the B Cell Receptor (BCR): pvalue calculation completed
Signaling by the B Cell Receptor (BCR): Calculation completed
Sphingolipid De Novo Biosynthesis: Calculation started
Sphingolipid De Novo Biosynthesis: scoring computed

Calculating pathways:  39%|███▉      | 313/796 [27:04<40:47,  5.07s/it]

Sphingolipid De Novo Biosynthesis: pvalue calculation completed
Sphingolipid De Novo Biosynthesis: Calculation completed
Sphingolipid Metabolism: Calculation started
Sphingolipid Metabolism: scoring computed

Calculating pathways:  39%|███▉      | 314/796 [27:09<40:22,  5.03s/it]

Sphingolipid Metabolism: pvalue calculation completed
Sphingolipid Metabolism: Calculation completed
Synthesis of 12-Eicosatetraenoic Acid Derivatives: Calculation started
Synthesis of 12-Eicosatetraenoic Acid Derivatives: scoring computed

Calculating pathways:  40%|███▉      | 315/796 [27:13<36:34,  4.56s/it]

Synthesis of 12-Eicosatetraenoic Acid Derivatives: pvalue calculation completed
Synthesis of 12-Eicosatetraenoic Acid Derivatives: Calculation completed
Synthesis of 15-Eicosatetraenoic Acid Derivatives: Calculation started
Synthesis of 15-Eicosatetraenoic Acid Derivatives: scoring computed

Calculating pathways:  40%|███▉      | 316/796 [27:16<33:47,  4.22s/it]

Synthesis of 15-Eicosatetraenoic Acid Derivatives: pvalue calculation completed
Synthesis of 15-Eicosatetraenoic Acid Derivatives: Calculation completed
Synthesis of Leukotrienes (LT) and Eoxins (EX): Calculation started
Synthesis of Leukotrienes (LT) and Eoxins (EX): scoring computed

Calculating pathways:  40%|███▉      | 317/796 [27:20<32:18,  4.05s/it]

Synthesis of Leukotrienes (LT) and Eoxins (EX): pvalue calculation completed
Synthesis of Leukotrienes (LT) and Eoxins (EX): Calculation completed
TCF Dependent Signaling in Response to WNT: Calculation started
TCF Dependent Signaling in Response to WNT: scoring computed

Calculating pathways:  40%|███▉      | 318/796 [27:26<36:18,  4.56s/it]

TCF Dependent Signaling in Response to WNT: pvalue calculation completed
TCF Dependent Signaling in Response to WNT: Calculation completed
TCR Signaling: Calculation started
TCR Signaling: scoring computed

Calculating pathways:  40%|████      | 319/796 [27:31<37:01,  4.66s/it]

TCR Signaling: pvalue calculation completed
TCR Signaling: Calculation completed
TFAP2 (AP-2) Family Regulates Transcription of Growth Factors and Their Receptors: Calculation started
TFAP2 (AP-2) Family Regulates Transcription of Growth Factors and Their Receptors: scoring computed

Calculating pathways:  40%|████      | 320/796 [27:34<34:20,  4.33s/it]

TFAP2 (AP-2) Family Regulates Transcription of Growth Factors and Their Receptors: pvalue calculation completed
TFAP2 (AP-2) Family Regulates Transcription of Growth Factors and Their Receptors: Calculation completed
TP53 Regulates Transcription of Caspase Activators and Caspases: Calculation started
TP53 Regulates Transcription of Caspase Activators and Caspases: scoring computed

Calculating pathways:  40%|████      | 321/796 [27:38<32:27,  4.10s/it]

TP53 Regulates Transcription of Caspase Activators and Caspases: pvalue calculation completed
TP53 Regulates Transcription of Caspase Activators and Caspases: Calculation completed
TP53 Regulates Transcription of Cell Cycle Genes: Calculation started
TP53 Regulates Transcription of Cell Cycle Genes: scoring computed

Calculating pathways:  40%|████      | 322/796 [27:42<32:11,  4.07s/it]

TP53 Regulates Transcription of Cell Cycle Genes: pvalue calculation completed
TP53 Regulates Transcription of Cell Cycle Genes: Calculation completed
TP53 Regulates Transcription of Cell Death Genes: Calculation started
TP53 Regulates Transcription of Cell Death Genes: scoring computed

Calculating pathways:  41%|████      | 323/796 [27:46<31:49,  4.04s/it]

TP53 Regulates Transcription of Cell Death Genes: pvalue calculation completed
TP53 Regulates Transcription of Cell Death Genes: Calculation completed
TP53 Regulates Transcription of Genes Involved in G2 Cell Cycle Arrest: Calculation started
TP53 Regulates Transcription of Genes Involved in G2 Cell Cycle Arrest: scoring computed

Calculating pathways:  41%|████      | 324/796 [27:50<31:22,  3.99s/it]

TP53 Regulates Transcription of Genes Involved in G2 Cell Cycle Arrest: pvalue calculation completed
TP53 Regulates Transcription of Genes Involved in G2 Cell Cycle Arrest: Calculation completed
Telomere Extension By Telomerase: Calculation started
Telomere Extension By Telomerase: scoring computed

Calculating pathways:  41%|████      | 325/796 [27:53<30:34,  3.89s/it]

Telomere Extension By Telomerase: pvalue calculation completed
Telomere Extension By Telomerase: Calculation completed
Telomere Maintenance: Calculation started
Telomere Maintenance: scoring computed

Calculating pathways:  41%|████      | 326/796 [27:58<31:28,  4.02s/it]

Telomere Maintenance: pvalue calculation completed
Telomere Maintenance: Calculation completed
The IPAF Inflammasome: Calculation started
The IPAF Inflammasome: scoring computed

Calculating pathways:  41%|████      | 327/796 [28:01<29:57,  3.83s/it]

The IPAF Inflammasome: pvalue calculation completed
The IPAF Inflammasome: Calculation completed
The NLRP3 Inflammasome: Calculation started
The NLRP3 Inflammasome: scoring computed

Calculating pathways:  41%|████      | 328/796 [28:04<29:17,  3.76s/it]

The NLRP3 Inflammasome: pvalue calculation completed
The NLRP3 Inflammasome: Calculation completed
The Role of Nef in HIV-1 Replication and Disease Pathogenesis: Calculation started
The Role of Nef in HIV-1 Replication and Disease Pathogenesis: scoring computed

Calculating pathways:  41%|████▏     | 329/796 [28:08<29:06,  3.74s/it]

The Role of Nef in HIV-1 Replication and Disease Pathogenesis: pvalue calculation completed
The Role of Nef in HIV-1 Replication and Disease Pathogenesis: Calculation completed
Transcription of E2F Targets Under Negative Control by DREAM Complex: Calculation started
Transcription of E2F Targets Under Negative Control by DREAM Complex: scoring computed

Calculating pathways:  41%|████▏     | 330/796 [28:12<29:09,  3.75s/it]

Transcription of E2F Targets Under Negative Control by DREAM Complex: pvalue calculation completed
Transcription of E2F Targets Under Negative Control by DREAM Complex: Calculation completed
Transcriptional Regulation by TP53: Calculation started
Transcriptional Regulation by TP53: scoring computed

Calculating pathways:  42%|████▏     | 331/796 [28:20<38:35,  4.98s/it]

Transcriptional Regulation by TP53: pvalue calculation completed
Transcriptional Regulation by TP53: Calculation completed
Transcriptional Regulation by the AP-2 (TFAP2) Family of Transcription Factors: Calculation started
Transcriptional Regulation by the AP-2 (TFAP2) Family of Transcription Factors: scoring computed

Calculating pathways:  42%|████▏     | 332/796 [28:24<36:07,  4.67s/it]

Transcriptional Regulation by the AP-2 (TFAP2) Family of Transcription Factors: pvalue calculation completed
Transcriptional Regulation by the AP-2 (TFAP2) Family of Transcription Factors: Calculation completed
Translocation of ZAP-70 to Immunological Synapse: Calculation started
Translocation of ZAP-70 to Immunological Synapse: scoring computed

Calculating pathways:  42%|████▏     | 333/796 [28:28<33:55,  4.40s/it]

Translocation of ZAP-70 to Immunological Synapse: pvalue calculation completed
Translocation of ZAP-70 to Immunological Synapse: Calculation completed
Transport of RCbl Within the Body: Calculation started
Transport of RCbl Within the Body: scoring computed

Calculating pathways:  42%|████▏     | 334/796 [28:31<31:59,  4.16s/it]

Transport of RCbl Within the Body: pvalue calculation completed
Transport of RCbl Within the Body: Calculation completed
Transport of Small Molecules: Calculation started
Transport of Small Molecules: scoring computed

Calculating pathways:  42%|████▏     | 335/796 [28:42<47:31,  6.19s/it]

Transport of Small Molecules: pvalue calculation completed
Transport of Small Molecules: Calculation completed
VEGFA-VEGFR2 Pathway: Calculation started
VEGFA-VEGFR2 Pathway: scoring computed

Calculating pathways:  42%|████▏     | 336/796 [28:47<44:09,  5.76s/it]

VEGFA-VEGFR2 Pathway: pvalue calculation completed
VEGFA-VEGFR2 Pathway: Calculation completed
Viral Infection Pathways: Calculation started
Viral Infection Pathways: scoring computed

Calculating pathways:  42%|████▏     | 337/796 [28:59<58:47,  7.69s/it]

Viral Infection Pathways: pvalue calculation completed
Viral Infection Pathways: Calculation completed
B Cell Activation (GO:0042113): Calculation started
B Cell Activation (GO:0042113): scoring computed

Calculating pathways:  42%|████▏     | 338/796 [29:04<51:32,  6.75s/it]

B Cell Activation (GO:0042113): pvalue calculation completed
B Cell Activation (GO:0042113): Calculation completed
B Cell Differentiation (GO:0030183): Calculation started
B Cell Differentiation (GO:0030183): scoring computed

Calculating pathways:  43%|████▎     | 339/796 [29:08<45:09,  5.93s/it]

B Cell Differentiation (GO:0030183): pvalue calculation completed
B Cell Differentiation (GO:0030183): Calculation completed
B Cell Receptor Signaling Pathway (GO:0050853): Calculation started
B Cell Receptor Signaling Pathway (GO:0050853): scoring computed

Calculating pathways:  43%|████▎     | 340/796 [29:11<40:11,  5.29s/it]

B Cell Receptor Signaling Pathway (GO:0050853): pvalue calculation completed
B Cell Receptor Signaling Pathway (GO:0050853): Calculation completed
DNA Biosynthetic Process (GO:0071897): Calculation started
DNA Biosynthetic Process (GO:0071897): scoring computed

Calculating pathways:  43%|████▎     | 341/796 [29:15<36:36,  4.83s/it]

DNA Biosynthetic Process (GO:0071897): pvalue calculation completed
DNA Biosynthetic Process (GO:0071897): Calculation completed
DNA Conformation Change (GO:0071103): Calculation started
DNA Conformation Change (GO:0071103): scoring computed

Calculating pathways:  43%|████▎     | 342/796 [29:19<33:56,  4.49s/it]

DNA Conformation Change (GO:0071103): pvalue calculation completed
DNA Conformation Change (GO:0071103): Calculation completed
DNA Damage Response (GO:0006974): Calculation started
DNA Damage Response (GO:0006974): scoring computed

Calculating pathways:  43%|████▎     | 343/796 [29:27<43:04,  5.70s/it]

DNA Damage Response (GO:0006974): pvalue calculation completed
DNA Damage Response (GO:0006974): Calculation completed
DNA Metabolic Process (GO:0006259): Calculation started
DNA Metabolic Process (GO:0006259): scoring computed

Calculating pathways:  43%|████▎     | 344/796 [29:34<46:13,  6.14s/it]

DNA Metabolic Process (GO:0006259): pvalue calculation completed
DNA Metabolic Process (GO:0006259): Calculation completed
DNA Replication (GO:0006260): Calculation started
DNA Replication (GO:0006260): scoring computed

Calculating pathways:  43%|████▎     | 345/796 [29:39<42:22,  5.64s/it]

DNA Replication (GO:0006260): pvalue calculation completed
DNA Replication (GO:0006260): Calculation completed
DNA Strand Elongation (GO:0022616): Calculation started
DNA Strand Elongation (GO:0022616): scoring computed

Calculating pathways:  43%|████▎     | 346/796 [29:43<37:35,  5.01s/it]

DNA Strand Elongation (GO:0022616): pvalue calculation completed
DNA Strand Elongation (GO:0022616): Calculation completed
DNA Topological Change (GO:0006265): Calculation started
DNA Topological Change (GO:0006265): scoring computed

Calculating pathways:  44%|████▎     | 347/796 [29:46<34:07,  4.56s/it]

DNA Topological Change (GO:0006265): pvalue calculation completed
DNA Topological Change (GO:0006265): Calculation completed
ERBB Signaling Pathway (GO:0038127): Calculation started
ERBB Signaling Pathway (GO:0038127): scoring computed

Calculating pathways:  44%|████▎     | 348/796 [29:50<33:25,  4.48s/it]

ERBB Signaling Pathway (GO:0038127): pvalue calculation completed
ERBB Signaling Pathway (GO:0038127): Calculation completed
ERBB2 Signaling Pathway (GO:0038128): Calculation started
ERBB2 Signaling Pathway (GO:0038128): scoring computed

Calculating pathways:  44%|████▍     | 349/796 [29:54<31:32,  4.23s/it]

ERBB2 Signaling Pathway (GO:0038128): pvalue calculation completed
ERBB2 Signaling Pathway (GO:0038128): Calculation completed
ERBB2-EGFR Signaling Pathway (GO:0038134): Calculation started
ERBB2-EGFR Signaling Pathway (GO:0038134): scoring computed

Calculating pathways:  44%|████▍     | 350/796 [29:58<29:57,  4.03s/it]

ERBB2-EGFR Signaling Pathway (GO:0038134): pvalue calculation completed
ERBB2-EGFR Signaling Pathway (GO:0038134): Calculation completed
Fc Receptor Mediated Stimulatory Signaling Pathway (GO:0002431): Calculation started
Fc Receptor Mediated Stimulatory Signaling Pathway (GO:0002431): scoring computed

Calculating pathways:  44%|████▍     | 351/796 [30:01<29:16,  3.95s/it]

Fc Receptor Mediated Stimulatory Signaling Pathway (GO:0002431): pvalue calculation completed
Fc Receptor Mediated Stimulatory Signaling Pathway (GO:0002431): Calculation completed
Fc Receptor Signaling Pathway (GO:0038093): Calculation started
Fc Receptor Signaling Pathway (GO:0038093): scoring computed

Calculating pathways:  44%|████▍     | 352/796 [30:05<28:55,  3.91s/it]

Fc Receptor Signaling Pathway (GO:0038093): pvalue calculation completed
Fc Receptor Signaling Pathway (GO:0038093): Calculation completed
Fc-gamma Receptor Signaling Pathway (GO:0038094): Calculation started
Fc-gamma Receptor Signaling Pathway (GO:0038094): scoring computed

Calculating pathways:  44%|████▍     | 353/796 [30:09<28:28,  3.86s/it]

Fc-gamma Receptor Signaling Pathway (GO:0038094): pvalue calculation completed
Fc-gamma Receptor Signaling Pathway (GO:0038094): Calculation completed
Fc-gamma Receptor Signaling Pathway Involved in Phagocytosis (GO:0038096): Calculation started
Fc-gamma Receptor Signaling Pathway Involved in Phagocytosis (GO:0038096): scoring computed

Calculating pathways:  44%|████▍     | 354/796 [30:13<28:20,  3.85s/it]

Fc-gamma Receptor Signaling Pathway Involved in Phagocytosis (GO:0038096): pvalue calculation completed
Fc-gamma Receptor Signaling Pathway Involved in Phagocytosis (GO:0038096): Calculation completed
G Protein-Coupled Acetylcholine Receptor Signaling Pathway (GO:0007213): Calculation started
G Protein-Coupled Acetylcholine Receptor Signaling Pathway (GO:0007213): scoring computed

Calculating pathways:  45%|████▍     | 355/796 [30:16<27:43,  3.77s/it]

G Protein-Coupled Acetylcholine Receptor Signaling Pathway (GO:0007213): pvalue calculation completed
G Protein-Coupled Acetylcholine Receptor Signaling Pathway (GO:0007213): Calculation completed
GPCR Sgnlng Pway, Coupled to Cyclic Nucleotide Second Messenger (GO:0007187): Calculation started
GPCR Sgnlng Pway, Coupled to Cyclic Nucleotide Second Messenger (GO:0007187): scoring computed

Calculating pathways:  45%|████▍     | 356/796 [30:20<27:45,  3.78s/it]

GPCR Sgnlng Pway, Coupled to Cyclic Nucleotide Second Messenger (GO:0007187): pvalue calculation completed
GPCR Sgnlng Pway, Coupled to Cyclic Nucleotide Second Messenger (GO:0007187): Calculation completed
G Protein-Coupled Serotonin Receptor Signaling Pathway (GO:0098664): Calculation started
G Protein-Coupled Serotonin Receptor Signaling Pathway (GO:0098664): scoring computed

Calculating pathways:  45%|████▍     | 357/796 [30:24<27:14,  3.72s/it]

G Protein-Coupled Serotonin Receptor Signaling Pathway (GO:0098664): pvalue calculation completed
G Protein-Coupled Serotonin Receptor Signaling Pathway (GO:0098664): Calculation completed
G2/M Transition of Mitotic Cell Cycle (GO:0000086): Calculation started
G2/M Transition of Mitotic Cell Cycle (GO:0000086): scoring computed

Calculating pathways:  45%|████▍     | 358/796 [30:28<27:49,  3.81s/it]

G2/M Transition of Mitotic Cell Cycle (GO:0000086): pvalue calculation completed
G2/M Transition of Mitotic Cell Cycle (GO:0000086): Calculation completed
RNA Biosynthetic Process (GO:0032774): Calculation started
RNA Biosynthetic Process (GO:0032774): scoring computed

Calculating pathways:  45%|████▌     | 359/796 [30:33<30:41,  4.21s/it]

RNA Biosynthetic Process (GO:0032774): pvalue calculation completed
RNA Biosynthetic Process (GO:0032774): Calculation completed
RNA-templated DNA Biosynthetic Process (GO:0006278): Calculation started
RNA-templated DNA Biosynthetic Process (GO:0006278): scoring computed

Calculating pathways:  45%|████▌     | 360/796 [30:36<29:24,  4.05s/it]

RNA-templated DNA Biosynthetic Process (GO:0006278): pvalue calculation completed
RNA-templated DNA Biosynthetic Process (GO:0006278): Calculation completed
Rac Protein Signal Transduction (GO:0016601): Calculation started
Rac Protein Signal Transduction (GO:0016601): scoring computed

Calculating pathways:  45%|████▌     | 361/796 [30:40<28:48,  3.97s/it]

Rac Protein Signal Transduction (GO:0016601): pvalue calculation completed
Rac Protein Signal Transduction (GO:0016601): Calculation completed
T Cell Activation (GO:0042110): Calculation started
T Cell Activation (GO:0042110): scoring computed

Calculating pathways:  45%|████▌     | 362/796 [30:45<30:06,  4.16s/it]

T Cell Activation (GO:0042110): pvalue calculation completed
T Cell Activation (GO:0042110): Calculation completed
T Cell Differentiation (GO:0030217): Calculation started
T Cell Differentiation (GO:0030217): scoring computed

Calculating pathways:  46%|████▌     | 363/796 [30:49<29:25,  4.08s/it]

T Cell Differentiation (GO:0030217): pvalue calculation completed
T Cell Differentiation (GO:0030217): Calculation completed
T Cell Receptor Signaling Pathway (GO:0050852): Calculation started
T Cell Receptor Signaling Pathway (GO:0050852): scoring computed

Calculating pathways:  46%|████▌     | 364/796 [30:53<30:23,  4.22s/it]

T Cell Receptor Signaling Pathway (GO:0050852): pvalue calculation completed
T Cell Receptor Signaling Pathway (GO:0050852): Calculation completed
Wnt Signaling Pathway, Planar Cell Polarity Pathway (GO:0060071): Calculation started
Wnt Signaling Pathway, Planar Cell Polarity Pathway (GO:0060071): scoring computed

Calculating pathways:  46%|████▌     | 365/796 [30:57<29:25,  4.10s/it]

Wnt Signaling Pathway, Planar Cell Polarity Pathway (GO:0060071): pvalue calculation completed
Wnt Signaling Pathway, Planar Cell Polarity Pathway (GO:0060071): Calculation completed
Acetylcholine Receptor Signaling Pathway (GO:0095500): Calculation started
Acetylcholine Receptor Signaling Pathway (GO:0095500): scoring computed

Calculating pathways:  46%|████▌     | 366/796 [31:01<28:35,  3.99s/it]

Acetylcholine Receptor Signaling Pathway (GO:0095500): pvalue calculation completed
Acetylcholine Receptor Signaling Pathway (GO:0095500): Calculation completed
Actin Filament Organization (GO:0007015): Calculation started
Actin Filament Organization (GO:0007015): scoring computed

Calculating pathways:  46%|████▌     | 367/796 [31:06<31:51,  4.45s/it]

Actin Filament Organization (GO:0007015): pvalue calculation completed
Actin Filament Organization (GO:0007015): Calculation completed
Actin Filament Polymerization (GO:0030041): Calculation started
Actin Filament Polymerization (GO:0030041): scoring computed

Calculating pathways:  46%|████▌     | 368/796 [31:10<30:16,  4.24s/it]

Actin Filament Polymerization (GO:0030041): pvalue calculation completed
Actin Filament Polymerization (GO:0030041): Calculation completed
Actin Polymerization or Depolymerization (GO:0008154): Calculation started
Actin Polymerization or Depolymerization (GO:0008154): scoring computed

Calculating pathways:  46%|████▋     | 369/796 [31:14<29:40,  4.17s/it]

Actin Polymerization or Depolymerization (GO:0008154): pvalue calculation completed
Actin Polymerization or Depolymerization (GO:0008154): Calculation completed
Adenine Nucleotide Transport (GO:0051503): Calculation started
Adenine Nucleotide Transport (GO:0051503): scoring computed

Calculating pathways:  46%|████▋     | 370/796 [31:18<28:45,  4.05s/it]

Adenine Nucleotide Transport (GO:0051503): pvalue calculation completed
Adenine Nucleotide Transport (GO:0051503): Calculation completed
Adenylate Cyclase-Activating G Protein-Coupled Receptor Signaling Pathway (GO:0007189): Calculation started
Adenylate Cyclase-Activating G Protein-Coupled Receptor Signaling Pathway (GO:0007189): scoring computed

Calculating pathways:  47%|████▋     | 371/796 [31:23<31:03,  4.39s/it]

Adenylate Cyclase-Activating G Protein-Coupled Receptor Signaling Pathway (GO:0007189): pvalue calculation completed
Adenylate Cyclase-Activating G Protein-Coupled Receptor Signaling Pathway (GO:0007189): Calculation completed
Adenylate Cyclase-Inhibiting G Protein-Coupled Receptor Signaling Pathway (GO:0007193): Calculation started
Adenylate Cyclase-Inhibiting G Protein-Coupled Receptor Signaling Pathway (GO:0007193): scoring computed

Calculating pathways:  47%|████▋     | 372/796 [31:27<30:21,  4.30s/it]

Adenylate Cyclase-Inhibiting G Protein-Coupled Receptor Signaling Pathway (GO:0007193): pvalue calculation completed
Adenylate Cyclase-Inhibiting G Protein-Coupled Receptor Signaling Pathway (GO:0007193): Calculation completed
Adenylate Cyclase-Inhibiting Serotonin Receptor Signaling Pathway (GO:0007198): Calculation started
Adenylate Cyclase-Inhibiting Serotonin Receptor Signaling Pathway (GO:0007198): scoring computed

Calculating pathways:  47%|████▋     | 373/796 [31:31<28:34,  4.05s/it]

Adenylate Cyclase-Inhibiting Serotonin Receptor Signaling Pathway (GO:0007198): pvalue calculation completed
Adenylate Cyclase-Inhibiting Serotonin Receptor Signaling Pathway (GO:0007198): Calculation completed
Adenylate Cyclase-Modulating G Protein-Coupled Receptor Signaling Pathway (GO:0007188): Calculation started
Adenylate Cyclase-Modulating G Protein-Coupled Receptor Signaling Pathway (GO:0007188): scoring computed

Calculating pathways:  47%|████▋     | 374/796 [31:36<32:01,  4.55s/it]

Adenylate Cyclase-Modulating G Protein-Coupled Receptor Signaling Pathway (GO:0007188): pvalue calculation completed
Adenylate Cyclase-Modulating G Protein-Coupled Receptor Signaling Pathway (GO:0007188): Calculation completed
Amide Transport (GO:0042886): Calculation started
Amide Transport (GO:0042886): scoring computed

Calculating pathways:  47%|████▋     | 375/796 [31:40<30:42,  4.38s/it]

Amide Transport (GO:0042886): pvalue calculation completed
Amide Transport (GO:0042886): Calculation completed
Anterograde Trans-Synaptic Signaling (GO:0098916): Calculation started
Anterograde Trans-Synaptic Signaling (GO:0098916): scoring computed

Calculating pathways:  47%|████▋     | 376/796 [31:46<33:19,  4.76s/it]

Anterograde Trans-Synaptic Signaling (GO:0098916): pvalue calculation completed
Anterograde Trans-Synaptic Signaling (GO:0098916): Calculation completed
Antigen Receptor-Mediated Signaling Pathway (GO:0050851): Calculation started
Antigen Receptor-Mediated Signaling Pathway (GO:0050851): scoring computed

Calculating pathways:  47%|████▋     | 377/796 [31:51<33:29,  4.80s/it]

Antigen Receptor-Mediated Signaling Pathway (GO:0050851): pvalue calculation completed
Antigen Receptor-Mediated Signaling Pathway (GO:0050851): Calculation completed
Apoptotic Cell Clearance (GO:0043277): Calculation started
Apoptotic Cell Clearance (GO:0043277): scoring computed

Calculating pathways:  47%|████▋     | 378/796 [31:55<31:27,  4.52s/it]

Apoptotic Cell Clearance (GO:0043277): pvalue calculation completed
Apoptotic Cell Clearance (GO:0043277): Calculation completed
Apoptotic Nuclear Changes (GO:0030262): Calculation started
Apoptotic Nuclear Changes (GO:0030262): scoring computed

Calculating pathways:  48%|████▊     | 379/796 [31:58<29:19,  4.22s/it]

Apoptotic Nuclear Changes (GO:0030262): pvalue calculation completed
Apoptotic Nuclear Changes (GO:0030262): Calculation completed
Arachidonate Metabolic Process (GO:0019369): Calculation started
Arachidonate Metabolic Process (GO:0019369): scoring computed

Calculating pathways:  48%|████▊     | 380/796 [32:02<28:39,  4.13s/it]

Arachidonate Metabolic Process (GO:0019369): pvalue calculation completed
Arachidonate Metabolic Process (GO:0019369): Calculation completed
Axon Guidance (GO:0007411): Calculation started
Axon Guidance (GO:0007411): scoring computed

Calculating pathways:  48%|████▊     | 381/796 [32:07<30:58,  4.48s/it]

Axon Guidance (GO:0007411): pvalue calculation completed
Axon Guidance (GO:0007411): Calculation completed
Axonogenesis (GO:0007409): Calculation started
Axonogenesis (GO:0007409): scoring computed

Calculating pathways:  48%|████▊     | 382/796 [32:13<33:52,  4.91s/it]

Axonogenesis (GO:0007409): pvalue calculation completed
Axonogenesis (GO:0007409): Calculation completed
Bile Acid and Bile Salt Transport (GO:0015721): Calculation started
Bile Acid and Bile Salt Transport (GO:0015721): scoring computed

Calculating pathways:  48%|████▊     | 383/796 [32:17<31:17,  4.55s/it]

Bile Acid and Bile Salt Transport (GO:0015721): pvalue calculation completed
Bile Acid and Bile Salt Transport (GO:0015721): Calculation completed
Calcium Ion Transmembrane Import Into Cytosol (GO:0097553): Calculation started
Calcium Ion Transmembrane Import Into Cytosol (GO:0097553): scoring computed

Calculating pathways:  48%|████▊     | 384/796 [32:21<30:25,  4.43s/it]

Calcium Ion Transmembrane Import Into Cytosol (GO:0097553): pvalue calculation completed
Calcium Ion Transmembrane Import Into Cytosol (GO:0097553): Calculation completed
Calcium Ion Transport (GO:0006816): Calculation started
Calcium Ion Transport (GO:0006816): scoring computed

Calculating pathways:  48%|████▊     | 385/796 [32:26<31:36,  4.61s/it]

Calcium Ion Transport (GO:0006816): pvalue calculation completed
Calcium Ion Transport (GO:0006816): Calculation completed
Carboxylic Acid Biosynthetic Process (GO:0046394): Calculation started
Carboxylic Acid Biosynthetic Process (GO:0046394): scoring computed

Calculating pathways:  48%|████▊     | 386/796 [32:30<29:46,  4.36s/it]

Carboxylic Acid Biosynthetic Process (GO:0046394): pvalue calculation completed
Carboxylic Acid Biosynthetic Process (GO:0046394): Calculation completed
Carboxylic Acid Transmembrane Transport (GO:1905039): Calculation started
Carboxylic Acid Transmembrane Transport (GO:1905039): scoring computed

Calculating pathways:  49%|████▊     | 387/796 [32:34<29:22,  4.31s/it]

Carboxylic Acid Transmembrane Transport (GO:1905039): pvalue calculation completed
Carboxylic Acid Transmembrane Transport (GO:1905039): Calculation completed
Carboxylic Acid Transport (GO:0046942): Calculation started
Carboxylic Acid Transport (GO:0046942): scoring computed

Calculating pathways:  49%|████▊     | 388/796 [32:38<29:03,  4.27s/it]

Carboxylic Acid Transport (GO:0046942): pvalue calculation completed
Carboxylic Acid Transport (GO:0046942): Calculation completed
Cell Chemotaxis (GO:0060326): Calculation started
Cell Chemotaxis (GO:0060326): scoring computed

Calculating pathways:  49%|████▉     | 389/796 [32:43<29:17,  4.32s/it]

Cell Chemotaxis (GO:0060326): pvalue calculation completed
Cell Chemotaxis (GO:0060326): Calculation completed
Cell Cycle G2/M Phase Transition (GO:0044839): Calculation started
Cell Cycle G2/M Phase Transition (GO:0044839): scoring computed

Calculating pathways:  49%|████▉     | 390/796 [32:47<28:30,  4.21s/it]

Cell Cycle G2/M Phase Transition (GO:0044839): pvalue calculation completed
Cell Cycle G2/M Phase Transition (GO:0044839): Calculation completed
Cell Projection Assembly (GO:0030031): Calculation started
Cell Projection Assembly (GO:0030031): scoring computed

Calculating pathways:  49%|████▉     | 391/796 [32:50<27:12,  4.03s/it]

Cell Projection Assembly (GO:0030031): pvalue calculation completed
Cell Projection Assembly (GO:0030031): Calculation completed
Cell Projection Organization (GO:0030030): Calculation started
Cell Projection Organization (GO:0030030): scoring computed

Calculating pathways:  49%|████▉     | 392/796 [32:54<26:20,  3.91s/it]

Cell Projection Organization (GO:0030030): pvalue calculation completed
Cell Projection Organization (GO:0030030): Calculation completed
Cell Surface Receptor Protein Tyrosine Kinase Signaling Pathway (GO:0007169): Calculation started
Cell Surface Receptor Protein Tyrosine Kinase Signaling Pathway (GO:0007169): scoring computed

Calculating pathways:  49%|████▉     | 393/796 [33:01<32:24,  4.83s/it]

Cell Surface Receptor Protein Tyrosine Kinase Signaling Pathway (GO:0007169): pvalue calculation completed
Cell Surface Receptor Protein Tyrosine Kinase Signaling Pathway (GO:0007169): Calculation completed
Cell-Matrix Adhesion (GO:0007160): Calculation started
Cell-Matrix Adhesion (GO:0007160): scoring computed

Calculating pathways:  49%|████▉     | 394/796 [33:06<32:19,  4.82s/it]

Cell-Matrix Adhesion (GO:0007160): pvalue calculation completed
Cell-Matrix Adhesion (GO:0007160): Calculation completed
Cellular Component Assembly (GO:0022607): Calculation started
Cellular Component Assembly (GO:0022607): scoring computed

Calculating pathways:  50%|████▉     | 395/796 [33:13<36:08,  5.41s/it]

Cellular Component Assembly (GO:0022607): pvalue calculation completed
Cellular Component Assembly (GO:0022607): Calculation completed
Cellular Component Disassembly (GO:0022411): Calculation started
Cellular Component Disassembly (GO:0022411): scoring computed

Calculating pathways:  50%|████▉     | 396/796 [33:17<33:07,  4.97s/it]

Cellular Component Disassembly (GO:0022411): pvalue calculation completed
Cellular Component Disassembly (GO:0022411): Calculation completed
Cellular Component Maintenance (GO:0043954): Calculation started
Cellular Component Maintenance (GO:0043954): scoring computed

Calculating pathways:  50%|████▉     | 397/796 [33:20<30:12,  4.54s/it]

Cellular Component Maintenance (GO:0043954): pvalue calculation completed
Cellular Component Maintenance (GO:0043954): Calculation completed
Cellular Response to UV (GO:0034644): Calculation started
Cellular Response to UV (GO:0034644): scoring computed

Calculating pathways:  50%|█████     | 398/796 [33:25<30:05,  4.54s/it]

Cellular Response to UV (GO:0034644): pvalue calculation completed
Cellular Response to UV (GO:0034644): Calculation completed
Cellular Response to UV-A (GO:0071492): Calculation started
Cellular Response to UV-A (GO:0071492): scoring computed

Calculating pathways:  50%|█████     | 399/796 [33:28<28:01,  4.24s/it]

Cellular Response to UV-A (GO:0071492): pvalue calculation completed
Cellular Response to UV-A (GO:0071492): Calculation completed
Cellular Response to Alkaloid (GO:0071312): Calculation started
Cellular Response to Alkaloid (GO:0071312): scoring computed

Calculating pathways:  50%|█████     | 400/796 [33:32<26:48,  4.06s/it]

Cellular Response to Alkaloid (GO:0071312): pvalue calculation completed
Cellular Response to Alkaloid (GO:0071312): Calculation completed
Cellular Response to Amino Acid Stimulus (GO:0071230): Calculation started
Cellular Response to Amino Acid Stimulus (GO:0071230): scoring computed

Calculating pathways:  50%|█████     | 401/796 [33:36<26:24,  4.01s/it]

Cellular Response to Amino Acid Stimulus (GO:0071230): pvalue calculation completed
Cellular Response to Amino Acid Stimulus (GO:0071230): Calculation completed
Cellular Response to Amyloid-Beta (GO:1904646): Calculation started
Cellular Response to Amyloid-Beta (GO:1904646): scoring computed

Calculating pathways:  51%|█████     | 402/796 [33:40<25:57,  3.95s/it]

Cellular Response to Amyloid-Beta (GO:1904646): pvalue calculation completed
Cellular Response to Amyloid-Beta (GO:1904646): Calculation completed
Cellular Response to Calcium Ion (GO:0071277): Calculation started
Cellular Response to Calcium Ion (GO:0071277): scoring computed

Calculating pathways:  51%|█████     | 403/796 [33:44<26:04,  3.98s/it]

Cellular Response to Calcium Ion (GO:0071277): pvalue calculation completed
Cellular Response to Calcium Ion (GO:0071277): Calculation completed
Cellular Response to Cytokine Stimulus (GO:0071345): Calculation started
Cellular Response to Cytokine Stimulus (GO:0071345): scoring computed

Calculating pathways:  51%|█████     | 404/796 [33:50<31:33,  4.83s/it]

Cellular Response to Cytokine Stimulus (GO:0071345): pvalue calculation completed
Cellular Response to Cytokine Stimulus (GO:0071345): Calculation completed
Cellular Response to Decreased Oxygen Levels (GO:0036294): Calculation started
Cellular Response to Decreased Oxygen Levels (GO:0036294): scoring computed

Calculating pathways:  51%|█████     | 405/796 [33:55<30:45,  4.72s/it]

Cellular Response to Decreased Oxygen Levels (GO:0036294): pvalue calculation completed
Cellular Response to Decreased Oxygen Levels (GO:0036294): Calculation completed
Cellular Response to Epidermal Growth Factor Stimulus (GO:0071364): Calculation started
Cellular Response to Epidermal Growth Factor Stimulus (GO:0071364): scoring computed

Calculating pathways:  51%|█████     | 406/796 [33:59<29:01,  4.47s/it]

Cellular Response to Epidermal Growth Factor Stimulus (GO:0071364): pvalue calculation completed
Cellular Response to Epidermal Growth Factor Stimulus (GO:0071364): Calculation completed
Cellular Response to Growth Factor Stimulus (GO:0071363): Calculation started
Cellular Response to Growth Factor Stimulus (GO:0071363): scoring computed

Calculating pathways:  51%|█████     | 407/796 [34:04<30:28,  4.70s/it]

Cellular Response to Growth Factor Stimulus (GO:0071363): pvalue calculation completed
Cellular Response to Growth Factor Stimulus (GO:0071363): Calculation completed
Cellular Response to Hydrogen Peroxide (GO:0070301): Calculation started
Cellular Response to Hydrogen Peroxide (GO:0070301): scoring computed

Calculating pathways:  51%|█████▏    | 408/796 [34:08<28:53,  4.47s/it]

Cellular Response to Hydrogen Peroxide (GO:0070301): pvalue calculation completed
Cellular Response to Hydrogen Peroxide (GO:0070301): Calculation completed
Cellular Response to Hypoxia (GO:0071456): Calculation started
Cellular Response to Hypoxia (GO:0071456): scoring computed

Calculating pathways:  51%|█████▏    | 409/796 [34:12<28:55,  4.48s/it]

Cellular Response to Hypoxia (GO:0071456): pvalue calculation completed
Cellular Response to Hypoxia (GO:0071456): Calculation completed
Cellular Response to Lectin (GO:1990858): Calculation started
Cellular Response to Lectin (GO:1990858): scoring computed

Calculating pathways:  52%|█████▏    | 410/796 [34:16<27:12,  4.23s/it]

Cellular Response to Lectin (GO:1990858): pvalue calculation completed
Cellular Response to Lectin (GO:1990858): Calculation completed
Cellular Response to Lipid (GO:0071396): Calculation started
Cellular Response to Lipid (GO:0071396): scoring computed

Calculating pathways:  52%|█████▏    | 411/796 [34:22<30:38,  4.77s/it]

Cellular Response to Lipid (GO:0071396): pvalue calculation completed
Cellular Response to Lipid (GO:0071396): Calculation completed
Cellular Response to Lipopolysaccharide (GO:0071222): Calculation started
Cellular Response to Lipopolysaccharide (GO:0071222): scoring computed

Calculating pathways:  52%|█████▏    | 412/796 [34:27<31:00,  4.85s/it]

Cellular Response to Lipopolysaccharide (GO:0071222): pvalue calculation completed
Cellular Response to Lipopolysaccharide (GO:0071222): Calculation completed
Cellular Response to Mechanical Stimulus (GO:0071260): Calculation started
Cellular Response to Mechanical Stimulus (GO:0071260): scoring computed

Calculating pathways:  52%|█████▏    | 413/796 [34:31<29:30,  4.62s/it]

Cellular Response to Mechanical Stimulus (GO:0071260): pvalue calculation completed
Cellular Response to Mechanical Stimulus (GO:0071260): Calculation completed
Cellular Response to Metal Ion (GO:0071248): Calculation started
Cellular Response to Metal Ion (GO:0071248): scoring computed

Calculating pathways:  52%|█████▏    | 414/796 [34:36<29:34,  4.65s/it]

Cellular Response to Metal Ion (GO:0071248): pvalue calculation completed
Cellular Response to Metal Ion (GO:0071248): Calculation completed
Cellular Response to Molecule of Bacterial Origin (GO:0071219): Calculation started
Cellular Response to Molecule of Bacterial Origin (GO:0071219): scoring computed

Calculating pathways:  52%|█████▏    | 415/796 [34:41<30:02,  4.73s/it]

Cellular Response to Molecule of Bacterial Origin (GO:0071219): pvalue calculation completed
Cellular Response to Molecule of Bacterial Origin (GO:0071219): Calculation completed
Cellular Response to Nitrogen Compound (GO:1901699): Calculation started
Cellular Response to Nitrogen Compound (GO:1901699): scoring computed

Calculating pathways:  52%|█████▏    | 416/796 [34:46<31:35,  4.99s/it]

Cellular Response to Nitrogen Compound (GO:1901699): pvalue calculation completed
Cellular Response to Nitrogen Compound (GO:1901699): Calculation completed
Cellular Response to Osmotic Stress (GO:0071470): Calculation started
Cellular Response to Osmotic Stress (GO:0071470): scoring computed

Calculating pathways:  52%|█████▏    | 417/796 [34:50<29:29,  4.67s/it]

Cellular Response to Osmotic Stress (GO:0071470): pvalue calculation completed
Cellular Response to Osmotic Stress (GO:0071470): Calculation completed
Cellular Response to Oxygen-Containing Compound (GO:1901701): Calculation started
Cellular Response to Oxygen-Containing Compound (GO:1901701): scoring computed

Calculating pathways:  53%|█████▎    | 418/796 [34:58<35:10,  5.58s/it]

Cellular Response to Oxygen-Containing Compound (GO:1901701): pvalue calculation completed
Cellular Response to Oxygen-Containing Compound (GO:1901701): Calculation completed
Cellular Response to Reactive Oxygen Species (GO:0034614): Calculation started
Cellular Response to Reactive Oxygen Species (GO:0034614): scoring computed

Calculating pathways:  53%|█████▎    | 419/796 [35:03<32:55,  5.24s/it]

Cellular Response to Reactive Oxygen Species (GO:0034614): pvalue calculation completed
Cellular Response to Reactive Oxygen Species (GO:0034614): Calculation completed
Cellular Response to Type II Interferon (GO:0071346): Calculation started
Cellular Response to Type II Interferon (GO:0071346): scoring computed

Calculating pathways:  53%|█████▎    | 420/796 [35:07<30:31,  4.87s/it]

Cellular Response to Type II Interferon (GO:0071346): pvalue calculation completed
Cellular Response to Type II Interferon (GO:0071346): Calculation completed
Cellular Response to Xenobiotic Stimulus (GO:0071466): Calculation started
Cellular Response to Xenobiotic Stimulus (GO:0071466): scoring computed

Calculating pathways:  53%|█████▎    | 421/796 [35:10<28:17,  4.53s/it]

Cellular Response to Xenobiotic Stimulus (GO:0071466): pvalue calculation completed
Cellular Response to Xenobiotic Stimulus (GO:0071466): Calculation completed
Ceramide Transport (GO:0035627): Calculation started
Ceramide Transport (GO:0035627): scoring computed

Calculating pathways:  53%|█████▎    | 422/796 [35:14<26:34,  4.26s/it]

Ceramide Transport (GO:0035627): pvalue calculation completed
Ceramide Transport (GO:0035627): Calculation completed
Chemical Synaptic Transmission (GO:0007268): Calculation started
Chemical Synaptic Transmission (GO:0007268): scoring computed

Calculating pathways:  53%|█████▎    | 423/796 [35:20<30:13,  4.86s/it]

Chemical Synaptic Transmission (GO:0007268): pvalue calculation completed
Chemical Synaptic Transmission (GO:0007268): Calculation completed
Chromatin Organization (GO:0006325): Calculation started
Chromatin Organization (GO:0006325): scoring computed

Calculating pathways:  53%|█████▎    | 424/796 [35:27<34:33,  5.57s/it]

Chromatin Organization (GO:0006325): pvalue calculation completed
Chromatin Organization (GO:0006325): Calculation completed
Chromatin Remodeling (GO:0006338): Calculation started
Chromatin Remodeling (GO:0006338): scoring computed

Calculating pathways:  53%|█████▎    | 425/796 [35:34<36:24,  5.89s/it]

Chromatin Remodeling (GO:0006338): pvalue calculation completed
Chromatin Remodeling (GO:0006338): Calculation completed
Chromosome Condensation (GO:0030261): Calculation started
Chromosome Condensation (GO:0030261): scoring computed

Calculating pathways:  54%|█████▎    | 426/796 [35:38<32:15,  5.23s/it]

Chromosome Condensation (GO:0030261): pvalue calculation completed
Chromosome Condensation (GO:0030261): Calculation completed
Chromosome Organization (GO:0051276): Calculation started
Chromosome Organization (GO:0051276): scoring computed

Calculating pathways:  54%|█████▎    | 427/796 [35:42<29:44,  4.84s/it]

Chromosome Organization (GO:0051276): pvalue calculation completed
Chromosome Organization (GO:0051276): Calculation completed
Cilium Organization (GO:0044782): Calculation started
Cilium Organization (GO:0044782): scoring computed

Calculating pathways:  54%|█████▍    | 428/796 [35:48<32:08,  5.24s/it]

Cilium Organization (GO:0044782): pvalue calculation completed
Cilium Organization (GO:0044782): Calculation completed
Collagen Catabolic Process (GO:0030574): Calculation started
Collagen Catabolic Process (GO:0030574): scoring computed

Calculating pathways:  54%|█████▍    | 429/796 [35:52<29:14,  4.78s/it]

Collagen Catabolic Process (GO:0030574): pvalue calculation completed
Collagen Catabolic Process (GO:0030574): Calculation completed
Cortical Cytoskeleton Organization (GO:0030865): Calculation started
Cortical Cytoskeleton Organization (GO:0030865): scoring computed

Calculating pathways:  54%|█████▍    | 430/796 [35:55<27:38,  4.53s/it]

Cortical Cytoskeleton Organization (GO:0030865): pvalue calculation completed
Cortical Cytoskeleton Organization (GO:0030865): Calculation completed
Cytoskeleton Organization (GO:0007010): Calculation started
Cytoskeleton Organization (GO:0007010): scoring computed

Calculating pathways:  54%|█████▍    | 431/796 [36:00<28:19,  4.66s/it]

Cytoskeleton Organization (GO:0007010): pvalue calculation completed
Cytoskeleton Organization (GO:0007010): Calculation completed
Defense Response to Gram-positive Bacterium (GO:0050830): Calculation started
Defense Response to Gram-positive Bacterium (GO:0050830): scoring computed

Calculating pathways:  54%|█████▍    | 432/796 [36:05<27:25,  4.52s/it]

Defense Response to Gram-positive Bacterium (GO:0050830): pvalue calculation completed
Defense Response to Gram-positive Bacterium (GO:0050830): Calculation completed
Defense Response to Bacterium (GO:0042742): Calculation started
Defense Response to Bacterium (GO:0042742): scoring computed

Calculating pathways:  54%|█████▍    | 433/796 [36:10<29:01,  4.80s/it]

Defense Response to Bacterium (GO:0042742): pvalue calculation completed
Defense Response to Bacterium (GO:0042742): Calculation completed
Defense Response to Virus (GO:0051607): Calculation started
Defense Response to Virus (GO:0051607): scoring computed

Calculating pathways:  55%|█████▍    | 434/796 [36:16<30:46,  5.10s/it]

Defense Response to Virus (GO:0051607): pvalue calculation completed
Defense Response to Virus (GO:0051607): Calculation completed
Dendritic Spine Organization (GO:0097061): Calculation started
Dendritic Spine Organization (GO:0097061): scoring computed

Calculating pathways:  55%|█████▍    | 435/796 [36:20<28:18,  4.71s/it]

Dendritic Spine Organization (GO:0097061): pvalue calculation completed
Dendritic Spine Organization (GO:0097061): Calculation completed
Endoderm Formation (GO:0001706): Calculation started
Endoderm Formation (GO:0001706): scoring computed

Calculating pathways:  55%|█████▍    | 436/796 [36:24<26:42,  4.45s/it]

Endoderm Formation (GO:0001706): pvalue calculation completed
Endoderm Formation (GO:0001706): Calculation completed
Endodermal Cell Differentiation (GO:0035987): Calculation started
Endodermal Cell Differentiation (GO:0035987): scoring computed

Calculating pathways:  55%|█████▍    | 437/796 [36:27<25:31,  4.27s/it]

Endodermal Cell Differentiation (GO:0035987): pvalue calculation completed
Endodermal Cell Differentiation (GO:0035987): Calculation completed
Enzyme-Linked Receptor Protein Signaling Pathway (GO:0007167): Calculation started
Enzyme-Linked Receptor Protein Signaling Pathway (GO:0007167): scoring computed

Calculating pathways:  55%|█████▌    | 438/796 [36:32<26:57,  4.52s/it]

Enzyme-Linked Receptor Protein Signaling Pathway (GO:0007167): pvalue calculation completed
Enzyme-Linked Receptor Protein Signaling Pathway (GO:0007167): Calculation completed
Ephrin Receptor Signaling Pathway (GO:0048013): Calculation started
Ephrin Receptor Signaling Pathway (GO:0048013): scoring computed

Calculating pathways:  55%|█████▌    | 439/796 [36:36<25:47,  4.33s/it]

Ephrin Receptor Signaling Pathway (GO:0048013): pvalue calculation completed
Ephrin Receptor Signaling Pathway (GO:0048013): Calculation completed
Epidermal Growth Factor Receptor Signaling Pathway (GO:0007173): Calculation started
Epidermal Growth Factor Receptor Signaling Pathway (GO:0007173): scoring computed

Calculating pathways:  55%|█████▌    | 440/796 [36:40<25:17,  4.26s/it]

Epidermal Growth Factor Receptor Signaling Pathway (GO:0007173): pvalue calculation completed
Epidermal Growth Factor Receptor Signaling Pathway (GO:0007173): Calculation completed
Establishment of Protein Localization to Chromosome (GO:0070199): Calculation started
Establishment of Protein Localization to Chromosome (GO:0070199): scoring computed

Calculating pathways:  55%|█████▌    | 441/796 [36:44<24:02,  4.06s/it]

Establishment of Protein Localization to Chromosome (GO:0070199): pvalue calculation completed
Establishment of Protein Localization to Chromosome (GO:0070199): Calculation completed
Establishment of Protein Localization to Organelle (GO:0072594): Calculation started
Establishment of Protein Localization to Organelle (GO:0072594): scoring computed

Calculating pathways:  56%|█████▌    | 442/796 [36:49<24:41,  4.19s/it]

Establishment of Protein Localization to Organelle (GO:0072594): pvalue calculation completed
Establishment of Protein Localization to Organelle (GO:0072594): Calculation completed
Establishment of Protein Localization to Telomere (GO:0070200): Calculation started
Establishment of Protein Localization to Telomere (GO:0070200): scoring computed

Calculating pathways:  56%|█████▌    | 443/796 [36:52<23:22,  3.97s/it]

Establishment of Protein Localization to Telomere (GO:0070200): pvalue calculation completed
Establishment of Protein Localization to Telomere (GO:0070200): Calculation completed
External Encapsulating Structure Organization (GO:0045229): Calculation started
External Encapsulating Structure Organization (GO:0045229): scoring computed

Calculating pathways:  56%|█████▌    | 444/796 [36:57<25:01,  4.27s/it]

External Encapsulating Structure Organization (GO:0045229): pvalue calculation completed
External Encapsulating Structure Organization (GO:0045229): Calculation completed
Extracellular Matrix Disassembly (GO:0022617): Calculation started
Extracellular Matrix Disassembly (GO:0022617): scoring computed

Calculating pathways:  56%|█████▌    | 445/796 [37:01<24:10,  4.13s/it]

Extracellular Matrix Disassembly (GO:0022617): pvalue calculation completed
Extracellular Matrix Disassembly (GO:0022617): Calculation completed
Extracellular Matrix Organization (GO:0030198): Calculation started
Extracellular Matrix Organization (GO:0030198): scoring computed

Calculating pathways:  56%|█████▌    | 446/796 [37:06<26:51,  4.60s/it]

Extracellular Matrix Organization (GO:0030198): pvalue calculation completed
Extracellular Matrix Organization (GO:0030198): Calculation completed
Extracellular Structure Organization (GO:0043062): Calculation started
Extracellular Structure Organization (GO:0043062): scoring computed

Calculating pathways:  56%|█████▌    | 447/796 [37:11<27:12,  4.68s/it]

Extracellular Structure Organization (GO:0043062): pvalue calculation completed
Extracellular Structure Organization (GO:0043062): Calculation completed
Fatty Acid Biosynthetic Process (GO:0006633): Calculation started
Fatty Acid Biosynthetic Process (GO:0006633): scoring computed

Calculating pathways:  56%|█████▋    | 448/796 [37:16<26:15,  4.53s/it]

Fatty Acid Biosynthetic Process (GO:0006633): pvalue calculation completed
Fatty Acid Biosynthetic Process (GO:0006633): Calculation completed
Fatty Acid Metabolic Process (GO:0006631): Calculation started
Fatty Acid Metabolic Process (GO:0006631): scoring computed

Calculating pathways:  56%|█████▋    | 449/796 [37:21<27:10,  4.70s/it]

Fatty Acid Metabolic Process (GO:0006631): pvalue calculation completed
Fatty Acid Metabolic Process (GO:0006631): Calculation completed
Fatty Acid Oxidation (GO:0019395): Calculation started
Fatty Acid Oxidation (GO:0019395): scoring computed

Calculating pathways:  57%|█████▋    | 450/796 [37:25<25:58,  4.50s/it]

Fatty Acid Oxidation (GO:0019395): pvalue calculation completed
Fatty Acid Oxidation (GO:0019395): Calculation completed
Gene Expression (GO:0010467): Calculation started
Gene Expression (GO:0010467): scoring computed

Calculating pathways:  57%|█████▋    | 451/796 [37:32<31:34,  5.49s/it]

Gene Expression (GO:0010467): pvalue calculation completed
Gene Expression (GO:0010467): Calculation completed
Generation of Neurons (GO:0048699): Calculation started
Generation of Neurons (GO:0048699): scoring computed

Calculating pathways:  57%|█████▋    | 452/796 [37:38<31:42,  5.53s/it]

Generation of Neurons (GO:0048699): pvalue calculation completed
Generation of Neurons (GO:0048699): Calculation completed
Glutamate Receptor Signaling Pathway (GO:0007215): Calculation started
Glutamate Receptor Signaling Pathway (GO:0007215): scoring computed

Calculating pathways:  57%|█████▋    | 453/796 [37:42<29:08,  5.10s/it]

Glutamate Receptor Signaling Pathway (GO:0007215): pvalue calculation completed
Glutamate Receptor Signaling Pathway (GO:0007215): Calculation completed
Glycerophospholipid Biosynthetic Process (GO:0046474): Calculation started
Glycerophospholipid Biosynthetic Process (GO:0046474): scoring computed

Calculating pathways:  57%|█████▋    | 454/796 [37:47<28:44,  5.04s/it]

Glycerophospholipid Biosynthetic Process (GO:0046474): pvalue calculation completed
Glycerophospholipid Biosynthetic Process (GO:0046474): Calculation completed
Heart Process (GO:0003015): Calculation started
Heart Process (GO:0003015): scoring computed

Calculating pathways:  57%|█████▋    | 455/796 [37:51<26:21,  4.64s/it]

Heart Process (GO:0003015): pvalue calculation completed
Heart Process (GO:0003015): Calculation completed
Heme Catabolic Process (GO:0042167): Calculation started
Heme Catabolic Process (GO:0042167): scoring computed

Calculating pathways:  57%|█████▋    | 456/796 [37:54<24:20,  4.30s/it]

Heme Catabolic Process (GO:0042167): pvalue calculation completed
Heme Catabolic Process (GO:0042167): Calculation completed
Heme Metabolic Process (GO:0042168): Calculation started
Heme Metabolic Process (GO:0042168): scoring computed

Calculating pathways:  57%|█████▋    | 457/796 [37:58<23:27,  4.15s/it]

Heme Metabolic Process (GO:0042168): pvalue calculation completed
Heme Metabolic Process (GO:0042168): Calculation completed
Hemopoiesis (GO:0030097): Calculation started
Hemopoiesis (GO:0030097): scoring computed

Calculating pathways:  58%|█████▊    | 458/796 [38:03<24:14,  4.30s/it]

Hemopoiesis (GO:0030097): pvalue calculation completed
Hemopoiesis (GO:0030097): Calculation completed
Hepatocyte Growth Factor Receptor Signaling Pathway (GO:0048012): Calculation started
Hepatocyte Growth Factor Receptor Signaling Pathway (GO:0048012): scoring computed

Calculating pathways:  58%|█████▊    | 459/796 [38:06<23:12,  4.13s/it]

Hepatocyte Growth Factor Receptor Signaling Pathway (GO:0048012): pvalue calculation completed
Hepatocyte Growth Factor Receptor Signaling Pathway (GO:0048012): Calculation completed
Hepoxilin Biosynthetic Process (GO:0051122): Calculation started
Hepoxilin Biosynthetic Process (GO:0051122): scoring computed

Calculating pathways:  58%|█████▊    | 460/796 [38:10<22:09,  3.96s/it]

Hepoxilin Biosynthetic Process (GO:0051122): pvalue calculation completed
Hepoxilin Biosynthetic Process (GO:0051122): Calculation completed
Hepoxilin Metabolic Process (GO:0051121): Calculation started
Hepoxilin Metabolic Process (GO:0051121): scoring computed

Calculating pathways:  58%|█████▊    | 461/796 [38:14<21:22,  3.83s/it]

Hepoxilin Metabolic Process (GO:0051121): pvalue calculation completed
Hepoxilin Metabolic Process (GO:0051121): Calculation completed
Icosanoid Biosynthetic Process (GO:0046456): Calculation started
Icosanoid Biosynthetic Process (GO:0046456): scoring computed

Calculating pathways:  58%|█████▊    | 462/796 [38:17<21:02,  3.78s/it]

Icosanoid Biosynthetic Process (GO:0046456): pvalue calculation completed
Icosanoid Biosynthetic Process (GO:0046456): Calculation completed
Icosanoid Metabolic Process (GO:0006690): Calculation started
Icosanoid Metabolic Process (GO:0006690): scoring computed

Calculating pathways:  58%|█████▊    | 463/796 [38:21<21:26,  3.86s/it]

Icosanoid Metabolic Process (GO:0006690): pvalue calculation completed
Icosanoid Metabolic Process (GO:0006690): Calculation completed
Icosanoid Transport (GO:0071715): Calculation started
Icosanoid Transport (GO:0071715): scoring computed

Calculating pathways:  58%|█████▊    | 464/796 [38:25<20:58,  3.79s/it]

Icosanoid Transport (GO:0071715): pvalue calculation completed
Icosanoid Transport (GO:0071715): Calculation completed
Import Into Nucleus (GO:0051170): Calculation started
Import Into Nucleus (GO:0051170): scoring computed

Calculating pathways:  58%|█████▊    | 465/796 [38:29<21:44,  3.94s/it]

Import Into Nucleus (GO:0051170): pvalue calculation completed
Import Into Nucleus (GO:0051170): Calculation completed
Inflammatory Response (GO:0006954): Calculation started
Inflammatory Response (GO:0006954): scoring computed

Calculating pathways:  59%|█████▊    | 466/796 [38:35<25:25,  4.62s/it]

Inflammatory Response (GO:0006954): pvalue calculation completed
Inflammatory Response (GO:0006954): Calculation completed
Innate Immune Response Activating Cell Surface Receptor Signaling Pathway (GO:0002220): Calculation started
Innate Immune Response Activating Cell Surface Receptor Signaling Pathway (GO:0002220): scoring computed

Calculating pathways:  59%|█████▊    | 467/796 [38:39<24:07,  4.40s/it]

Innate Immune Response Activating Cell Surface Receptor Signaling Pathway (GO:0002220): pvalue calculation completed
Innate Immune Response Activating Cell Surface Receptor Signaling Pathway (GO:0002220): Calculation completed
Innate Immune Response-Activating Signaling Pathway (GO:0002758): Calculation started
Innate Immune Response-Activating Signaling Pathway (GO:0002758): scoring computed

Calculating pathways:  59%|█████▉    | 468/796 [38:43<22:48,  4.17s/it]

Innate Immune Response-Activating Signaling Pathway (GO:0002758): pvalue calculation completed
Innate Immune Response-Activating Signaling Pathway (GO:0002758): Calculation completed
Intracellular Iron Ion Homeostasis (GO:0006879): Calculation started
Intracellular Iron Ion Homeostasis (GO:0006879): scoring computed

Calculating pathways:  59%|█████▉    | 469/796 [38:47<22:29,  4.13s/it]

Intracellular Iron Ion Homeostasis (GO:0006879): pvalue calculation completed
Intracellular Iron Ion Homeostasis (GO:0006879): Calculation completed
Intracellular Monoatomic Cation Homeostasis (GO:0030003): Calculation started
Intracellular Monoatomic Cation Homeostasis (GO:0030003): scoring computed

Calculating pathways:  59%|█████▉    | 470/796 [38:53<25:08,  4.63s/it]

Intracellular Monoatomic Cation Homeostasis (GO:0030003): pvalue calculation completed
Intracellular Monoatomic Cation Homeostasis (GO:0030003): Calculation completed
Intracellular Protein Transport (GO:0006886): Calculation started
Intracellular Protein Transport (GO:0006886): scoring computed

Calculating pathways:  59%|█████▉    | 471/796 [39:00<29:26,  5.43s/it]

Intracellular Protein Transport (GO:0006886): pvalue calculation completed
Intracellular Protein Transport (GO:0006886): Calculation completed
Intracellular Signaling Cassette (GO:0141124): Calculation started
Intracellular Signaling Cassette (GO:0141124): scoring computed

Calculating pathways:  59%|█████▉    | 472/796 [39:08<32:52,  6.09s/it]

Intracellular Signaling Cassette (GO:0141124): pvalue calculation completed
Intracellular Signaling Cassette (GO:0141124): Calculation completed
Intracellular Zinc Ion Homeostasis (GO:0006882): Calculation started
Intracellular Zinc Ion Homeostasis (GO:0006882): scoring computed

Calculating pathways:  59%|█████▉    | 473/796 [39:11<28:51,  5.36s/it]

Intracellular Zinc Ion Homeostasis (GO:0006882): pvalue calculation completed
Intracellular Zinc Ion Homeostasis (GO:0006882): Calculation completed
Lamellipodium Assembly (GO:0030032): Calculation started
Lamellipodium Assembly (GO:0030032): scoring computed

Calculating pathways:  60%|█████▉    | 474/796 [39:15<26:32,  4.95s/it]

Lamellipodium Assembly (GO:0030032): pvalue calculation completed
Lamellipodium Assembly (GO:0030032): Calculation completed
Lamellipodium Organization (GO:0097581): Calculation started
Lamellipodium Organization (GO:0097581): scoring computed

Calculating pathways:  60%|█████▉    | 475/796 [39:19<24:36,  4.60s/it]

Lamellipodium Organization (GO:0097581): pvalue calculation completed
Lamellipodium Organization (GO:0097581): Calculation completed
Learning (GO:0007612): Calculation started
Learning (GO:0007612): scoring computed

Calculating pathways:  60%|█████▉    | 476/796 [39:23<23:24,  4.39s/it]

Learning (GO:0007612): pvalue calculation completed
Learning (GO:0007612): Calculation completed
Leukotriene Transport (GO:0071716): Calculation started
Leukotriene Transport (GO:0071716): scoring computed

Calculating pathways:  60%|█████▉    | 477/796 [39:27<22:03,  4.15s/it]

Leukotriene Transport (GO:0071716): pvalue calculation completed
Leukotriene Transport (GO:0071716): Calculation completed
Linoleic Acid Metabolic Process (GO:0043651): Calculation started
Linoleic Acid Metabolic Process (GO:0043651): scoring computed

Calculating pathways:  60%|██████    | 478/796 [39:30<21:14,  4.01s/it]

Linoleic Acid Metabolic Process (GO:0043651): pvalue calculation completed
Linoleic Acid Metabolic Process (GO:0043651): Calculation completed
Lipid Metabolic Process (GO:0006629): Calculation started
Lipid Metabolic Process (GO:0006629): scoring computed

Calculating pathways:  60%|██████    | 479/796 [39:37<24:47,  4.69s/it]

Lipid Metabolic Process (GO:0006629): pvalue calculation completed
Lipid Metabolic Process (GO:0006629): Calculation completed
Lipid Modification (GO:0030258): Calculation started
Lipid Modification (GO:0030258): scoring computed

Calculating pathways:  60%|██████    | 480/796 [39:40<23:29,  4.46s/it]

Lipid Modification (GO:0030258): pvalue calculation completed
Lipid Modification (GO:0030258): Calculation completed
Lipid Oxidation (GO:0034440): Calculation started
Lipid Oxidation (GO:0034440): scoring computed

Calculating pathways:  60%|██████    | 481/796 [39:44<22:18,  4.25s/it]

Lipid Oxidation (GO:0034440): pvalue calculation completed
Lipid Oxidation (GO:0034440): Calculation completed
Lipid Translocation (GO:0034204): Calculation started
Lipid Translocation (GO:0034204): scoring computed

Calculating pathways:  61%|██████    | 482/796 [39:48<21:27,  4.10s/it]

Lipid Translocation (GO:0034204): pvalue calculation completed
Lipid Translocation (GO:0034204): Calculation completed
Lipid Transport (GO:0006869): Calculation started
Lipid Transport (GO:0006869): scoring computed

Calculating pathways:  61%|██████    | 483/796 [39:53<22:33,  4.32s/it]

Lipid Transport (GO:0006869): pvalue calculation completed
Lipid Transport (GO:0006869): Calculation completed
Lipoxygenase Pathway (GO:0019372): Calculation started
Lipoxygenase Pathway (GO:0019372): scoring computed

Calculating pathways:  61%|██████    | 484/796 [39:56<21:15,  4.09s/it]

Lipoxygenase Pathway (GO:0019372): pvalue calculation completed
Lipoxygenase Pathway (GO:0019372): Calculation completed
Liver Development (GO:0001889): Calculation started
Liver Development (GO:0001889): scoring computed

Calculating pathways:  61%|██████    | 485/796 [40:00<20:44,  4.00s/it]

Liver Development (GO:0001889): pvalue calculation completed
Liver Development (GO:0001889): Calculation completed
Long-Chain Fatty Acid Biosynthetic Process (GO:0042759): Calculation started
Long-Chain Fatty Acid Biosynthetic Process (GO:0042759): scoring computed

Calculating pathways:  61%|██████    | 486/796 [40:04<20:04,  3.89s/it]

Long-Chain Fatty Acid Biosynthetic Process (GO:0042759): pvalue calculation completed
Long-Chain Fatty Acid Biosynthetic Process (GO:0042759): Calculation completed
Long-Chain Fatty Acid Metabolic Process (GO:0001676): Calculation started
Long-Chain Fatty Acid Metabolic Process (GO:0001676): scoring computed

Calculating pathways:  61%|██████    | 487/796 [40:08<20:35,  4.00s/it]

Long-Chain Fatty Acid Metabolic Process (GO:0001676): pvalue calculation completed
Long-Chain Fatty Acid Metabolic Process (GO:0001676): Calculation completed
Lymphocyte Differentiation (GO:0030098): Calculation started
Lymphocyte Differentiation (GO:0030098): scoring computed

Calculating pathways:  61%|██████▏   | 488/796 [40:12<21:01,  4.10s/it]

Lymphocyte Differentiation (GO:0030098): pvalue calculation completed
Lymphocyte Differentiation (GO:0030098): Calculation completed
Macromolecule Biosynthetic Process (GO:0009059): Calculation started
Macromolecule Biosynthetic Process (GO:0009059): scoring computed

Calculating pathways:  61%|██████▏   | 489/796 [40:18<23:38,  4.62s/it]

Macromolecule Biosynthetic Process (GO:0009059): pvalue calculation completed
Macromolecule Biosynthetic Process (GO:0009059): Calculation completed
Membrane Lipid Biosynthetic Process (GO:0046467): Calculation started
Membrane Lipid Biosynthetic Process (GO:0046467): scoring computed

Calculating pathways:  62%|██████▏   | 490/796 [40:22<22:42,  4.45s/it]

Membrane Lipid Biosynthetic Process (GO:0046467): pvalue calculation completed
Membrane Lipid Biosynthetic Process (GO:0046467): Calculation completed
Metal Ion Transport (GO:0030001): Calculation started
Metal Ion Transport (GO:0030001): scoring computed

Calculating pathways:  62%|██████▏   | 491/796 [40:28<24:14,  4.77s/it]

Metal Ion Transport (GO:0030001): pvalue calculation completed
Metal Ion Transport (GO:0030001): Calculation completed
Mitochondrion Organization (GO:0007005): Calculation started
Mitochondrion Organization (GO:0007005): scoring computed

Calculating pathways:  62%|██████▏   | 492/796 [40:33<24:45,  4.89s/it]

Mitochondrion Organization (GO:0007005): pvalue calculation completed
Mitochondrion Organization (GO:0007005): Calculation completed
Mitotic Cell Cycle Phase Transition (GO:0044772): Calculation started
Mitotic Cell Cycle Phase Transition (GO:0044772): scoring computed

Calculating pathways:  62%|██████▏   | 493/796 [40:38<24:48,  4.91s/it]

Mitotic Cell Cycle Phase Transition (GO:0044772): pvalue calculation completed
Mitotic Cell Cycle Phase Transition (GO:0044772): Calculation completed
Mitotic Recombination (GO:0006312): Calculation started
Mitotic Recombination (GO:0006312): scoring computed

Calculating pathways:  62%|██████▏   | 494/796 [40:41<22:41,  4.51s/it]

Mitotic Recombination (GO:0006312): pvalue calculation completed
Mitotic Recombination (GO:0006312): Calculation completed
Mitotic Spindle Organization (GO:0007052): Calculation started
Mitotic Spindle Organization (GO:0007052): scoring computed

Calculating pathways:  62%|██████▏   | 495/796 [40:46<22:50,  4.55s/it]

Mitotic Spindle Organization (GO:0007052): pvalue calculation completed
Mitotic Spindle Organization (GO:0007052): Calculation completed
Monocarboxylic Acid Transport (GO:0015718): Calculation started
Monocarboxylic Acid Transport (GO:0015718): scoring computed

Calculating pathways:  62%|██████▏   | 496/796 [40:50<22:16,  4.45s/it]

Monocarboxylic Acid Transport (GO:0015718): pvalue calculation completed
Monocarboxylic Acid Transport (GO:0015718): Calculation completed
Motor Neuron Axon Guidance (GO:0008045): Calculation started
Motor Neuron Axon Guidance (GO:0008045): scoring computed

Calculating pathways:  62%|██████▏   | 497/796 [40:54<20:56,  4.20s/it]

Motor Neuron Axon Guidance (GO:0008045): pvalue calculation completed
Motor Neuron Axon Guidance (GO:0008045): Calculation completed
Natural Killer Cell Activation (GO:0030101): Calculation started
Natural Killer Cell Activation (GO:0030101): scoring computed

Calculating pathways:  63%|██████▎   | 498/796 [40:58<20:13,  4.07s/it]

Natural Killer Cell Activation (GO:0030101): pvalue calculation completed
Natural Killer Cell Activation (GO:0030101): Calculation completed
Negative Regulation of Apoptotic Process (GO:0043066): Calculation started
Negative Regulation of Apoptotic Process (GO:0043066): scoring computed

Calculating pathways:  63%|██████▎   | 499/796 [41:06<26:53,  5.43s/it]

Negative Regulation of Apoptotic Process (GO:0043066): pvalue calculation completed
Negative Regulation of Apoptotic Process (GO:0043066): Calculation completed
Negative Regulation of Cell Migration (GO:0030336): Calculation started
Negative Regulation of Cell Migration (GO:0030336): scoring computed

Calculating pathways:  63%|██████▎   | 500/796 [41:12<27:15,  5.53s/it]

Negative Regulation of Cell Migration (GO:0030336): pvalue calculation completed
Negative Regulation of Cell Migration (GO:0030336): Calculation completed
Negative Regulation of Cell Projection Organization (GO:0031345): Calculation started
Negative Regulation of Cell Projection Organization (GO:0031345): scoring computed

Calculating pathways:  63%|██████▎   | 501/796 [41:16<25:18,  5.15s/it]

Negative Regulation of Cell Projection Organization (GO:0031345): pvalue calculation completed
Negative Regulation of Cell Projection Organization (GO:0031345): Calculation completed
Negative Regulation of Cellular Process (GO:0048523): Calculation started
Negative Regulation of Cellular Process (GO:0048523): scoring computed

Calculating pathways:  63%|██████▎   | 502/796 [41:26<31:20,  6.40s/it]

Negative Regulation of Cellular Process (GO:0048523): pvalue calculation completed
Negative Regulation of Cellular Process (GO:0048523): Calculation completed
Negative Regulation of Cellular Senescence (GO:2000773): Calculation started
Negative Regulation of Cellular Senescence (GO:2000773): scoring computed

Calculating pathways:  63%|██████▎   | 503/796 [41:29<27:14,  5.58s/it]

Negative Regulation of Cellular Senescence (GO:2000773): pvalue calculation completed
Negative Regulation of Cellular Senescence (GO:2000773): Calculation completed
Negative Regulation of Cytokine Production (GO:0001818): Calculation started
Negative Regulation of Cytokine Production (GO:0001818): scoring computed

Calculating pathways:  63%|██████▎   | 504/796 [41:35<27:26,  5.64s/it]

Negative Regulation of Cytokine Production (GO:0001818): pvalue calculation completed
Negative Regulation of Cytokine Production (GO:0001818): Calculation completed
Negative Regulation of Endocytosis (GO:0045806): Calculation started
Negative Regulation of Endocytosis (GO:0045806): scoring computed

Calculating pathways:  63%|██████▎   | 505/796 [41:39<25:05,  5.18s/it]

Negative Regulation of Endocytosis (GO:0045806): pvalue calculation completed
Negative Regulation of Endocytosis (GO:0045806): Calculation completed
Negative Regulation of Extrinsic Apoptotic Signaling Pathway (GO:2001237): Calculation started
Negative Regulation of Extrinsic Apoptotic Signaling Pathway (GO:2001237): scoring computed

Calculating pathways:  64%|██████▎   | 506/796 [41:44<23:48,  4.93s/it]

Negative Regulation of Extrinsic Apoptotic Signaling Pathway (GO:2001237): pvalue calculation completed
Negative Regulation of Extrinsic Apoptotic Signaling Pathway (GO:2001237): Calculation completed
Negative Regulation of Extrinsic Apoptotic Signaling Pathway in Absence of Ligand (GO:2001240): Calculation started
Negative Regulation of Extrinsic Apoptotic Signaling Pathway in Absence of Ligand (GO:2001240): scoring computed

Calculating pathways:  64%|██████▎   | 507/796 [41:47<21:54,  4.55s/it]

Negative Regulation of Extrinsic Apoptotic Signaling Pathway in Absence of Ligand (GO:2001240): pvalue calculation completed
Negative Regulation of Extrinsic Apoptotic Signaling Pathway in Absence of Ligand (GO:2001240): Calculation completed
Negative Regulation of Fibroblast Migration (GO:0010764): Calculation started
Negative Regulation of Fibroblast Migration (GO:0010764): scoring computed

Calculating pathways:  64%|██████▍   | 508/796 [41:51<20:22,  4.25s/it]

Negative Regulation of Fibroblast Migration (GO:0010764): pvalue calculation completed
Negative Regulation of Fibroblast Migration (GO:0010764): Calculation completed
Negative Regulation of Gene Expression (GO:0010629): Calculation started
Negative Regulation of Gene Expression (GO:0010629): scoring computed

Calculating pathways:  64%|██████▍   | 509/796 [41:58<25:06,  5.25s/it]

Negative Regulation of Gene Expression (GO:0010629): pvalue calculation completed
Negative Regulation of Gene Expression (GO:0010629): Calculation completed
Negative Regulation of Immune Response (GO:0050777): Calculation started
Negative Regulation of Immune Response (GO:0050777): scoring computed

Calculating pathways:  64%|██████▍   | 510/796 [42:03<23:34,  4.94s/it]

Negative Regulation of Immune Response (GO:0050777): pvalue calculation completed
Negative Regulation of Immune Response (GO:0050777): Calculation completed
Negative Regulation of Inflammatory Response (GO:0050728): Calculation started
Negative Regulation of Inflammatory Response (GO:0050728): scoring computed

Calculating pathways:  64%|██████▍   | 511/796 [42:07<23:22,  4.92s/it]

Negative Regulation of Inflammatory Response (GO:0050728): pvalue calculation completed
Negative Regulation of Inflammatory Response (GO:0050728): Calculation completed
Negative Regulation of Inflammatory Response to Antigenic Stimulus (GO:0002862): Calculation started
Negative Regulation of Inflammatory Response to Antigenic Stimulus (GO:0002862): scoring computed

Calculating pathways:  64%|██████▍   | 512/796 [42:11<21:35,  4.56s/it]

Negative Regulation of Inflammatory Response to Antigenic Stimulus (GO:0002862): pvalue calculation completed
Negative Regulation of Inflammatory Response to Antigenic Stimulus (GO:0002862): Calculation completed
Negative Regulation of Intrinsic Apoptotic Signaling Pathway (GO:2001243): Calculation started
Negative Regulation of Intrinsic Apoptotic Signaling Pathway (GO:2001243): scoring computed

Calculating pathways:  64%|██████▍   | 513/796 [42:15<21:03,  4.46s/it]

Negative Regulation of Intrinsic Apoptotic Signaling Pathway (GO:2001243): pvalue calculation completed
Negative Regulation of Intrinsic Apoptotic Signaling Pathway (GO:2001243): Calculation completed
Negative Regulation of Macromolecule Biosynthetic Process (GO:0010558): Calculation started
Negative Regulation of Macromolecule Biosynthetic Process (GO:0010558): scoring computed

Calculating pathways:  65%|██████▍   | 514/796 [42:21<23:03,  4.91s/it]

Negative Regulation of Macromolecule Biosynthetic Process (GO:0010558): pvalue calculation completed
Negative Regulation of Macromolecule Biosynthetic Process (GO:0010558): Calculation completed
Negative Regulation of Monoatomic Ion Transport (GO:0043271): Calculation started
Negative Regulation of Monoatomic Ion Transport (GO:0043271): scoring computed

Calculating pathways:  65%|██████▍   | 515/796 [42:25<21:05,  4.50s/it]

Negative Regulation of Monoatomic Ion Transport (GO:0043271): pvalue calculation completed
Negative Regulation of Monoatomic Ion Transport (GO:0043271): Calculation completed
Negative Regulation of Oxidative Stress-Induced Intrinsic Apoptotic Signaling Pathway (GO:1902176): Calculation started
Negative Regulation of Oxidative Stress-Induced Intrinsic Apoptotic Signaling Pathway (GO:1902176): scoring computed

Calculating pathways:  65%|██████▍   | 516/796 [42:29<19:50,  4.25s/it]

Negative Regulation of Oxidative Stress-Induced Intrinsic Apoptotic Signaling Pathway (GO:1902176): pvalue calculation completed
Negative Regulation of Oxidative Stress-Induced Intrinsic Apoptotic Signaling Pathway (GO:1902176): Calculation completed
Negative Regulation of Programmed Cell Death (GO:0043069): Calculation started
Negative Regulation of Programmed Cell Death (GO:0043069): scoring computed

Calculating pathways:  65%|██████▍   | 517/796 [42:36<24:40,  5.31s/it]

Negative Regulation of Programmed Cell Death (GO:0043069): pvalue calculation completed
Negative Regulation of Programmed Cell Death (GO:0043069): Calculation completed
Negative Regulation of Protein Binding (GO:0032091): Calculation started
Negative Regulation of Protein Binding (GO:0032091): scoring computed

Calculating pathways:  65%|██████▌   | 518/796 [42:41<23:00,  4.96s/it]

Negative Regulation of Protein Binding (GO:0032091): pvalue calculation completed
Negative Regulation of Protein Binding (GO:0032091): Calculation completed
Negative Regulation of Reactive Oxygen Species Biosynthetic Process (GO:1903427): Calculation started
Negative Regulation of Reactive Oxygen Species Biosynthetic Process (GO:1903427): scoring computed

Calculating pathways:  65%|██████▌   | 519/796 [42:44<21:04,  4.56s/it]

Negative Regulation of Reactive Oxygen Species Biosynthetic Process (GO:1903427): pvalue calculation completed
Negative Regulation of Reactive Oxygen Species Biosynthetic Process (GO:1903427): Calculation completed
Negative Regulation of Receptor-Mediated Endocytosis (GO:0048261): Calculation started
Negative Regulation of Receptor-Mediated Endocytosis (GO:0048261): scoring computed

Calculating pathways:  65%|██████▌   | 520/796 [42:48<19:47,  4.30s/it]

Negative Regulation of Receptor-Mediated Endocytosis (GO:0048261): pvalue calculation completed
Negative Regulation of Receptor-Mediated Endocytosis (GO:0048261): Calculation completed
Negative Regulation of Secretion by Cell (GO:1903531): Calculation started
Negative Regulation of Secretion by Cell (GO:1903531): scoring computed

Calculating pathways:  65%|██████▌   | 521/796 [42:52<19:06,  4.17s/it]

Negative Regulation of Secretion by Cell (GO:1903531): pvalue calculation completed
Negative Regulation of Secretion by Cell (GO:1903531): Calculation completed
Negative Regulation of Sequestering of Calcium Ion (GO:0051283): Calculation started
Negative Regulation of Sequestering of Calcium Ion (GO:0051283): scoring computed

Calculating pathways:  66%|██████▌   | 522/796 [42:56<18:58,  4.15s/it]

Negative Regulation of Sequestering of Calcium Ion (GO:0051283): pvalue calculation completed
Negative Regulation of Sequestering of Calcium Ion (GO:0051283): Calculation completed
Negative Regulation of Signal Transduction in Absence of Ligand (GO:1901099): Calculation started
Negative Regulation of Signal Transduction in Absence of Ligand (GO:1901099): scoring computed

Calculating pathways:  66%|██████▌   | 523/796 [42:59<18:11,  4.00s/it]

Negative Regulation of Signal Transduction in Absence of Ligand (GO:1901099): pvalue calculation completed
Negative Regulation of Signal Transduction in Absence of Ligand (GO:1901099): Calculation completed
Nervous System Development (GO:0007399): Calculation started
Nervous System Development (GO:0007399): scoring computed

Calculating pathways:  66%|██████▌   | 524/796 [43:08<24:26,  5.39s/it]

Nervous System Development (GO:0007399): pvalue calculation completed
Nervous System Development (GO:0007399): Calculation completed
Neuron Differentiation (GO:0030182): Calculation started
Neuron Differentiation (GO:0030182): scoring computed

Calculating pathways:  66%|██████▌   | 525/796 [43:14<24:26,  5.41s/it]

Neuron Differentiation (GO:0030182): pvalue calculation completed
Neuron Differentiation (GO:0030182): Calculation completed
Neuron Migration (GO:0001764): Calculation started
Neuron Migration (GO:0001764): scoring computed

Calculating pathways:  66%|██████▌   | 526/796 [43:18<22:30,  5.00s/it]

Neuron Migration (GO:0001764): pvalue calculation completed
Neuron Migration (GO:0001764): Calculation completed
Neuron Projection Guidance (GO:0097485): Calculation started
Neuron Projection Guidance (GO:0097485): scoring computed

Calculating pathways:  66%|██████▌   | 527/796 [43:23<22:35,  5.04s/it]

Neuron Projection Guidance (GO:0097485): pvalue calculation completed
Neuron Projection Guidance (GO:0097485): Calculation completed
Nitrogen Compound Transport (GO:0071705): Calculation started
Nitrogen Compound Transport (GO:0071705): scoring computed

Calculating pathways:  66%|██████▋   | 528/796 [43:28<23:12,  5.20s/it]

Nitrogen Compound Transport (GO:0071705): pvalue calculation completed
Nitrogen Compound Transport (GO:0071705): Calculation completed
Non-Canonical Wnt Signaling Pathway (GO:0035567): Calculation started
Non-Canonical Wnt Signaling Pathway (GO:0035567): scoring computed

Calculating pathways:  66%|██████▋   | 529/796 [43:32<21:19,  4.79s/it]

Non-Canonical Wnt Signaling Pathway (GO:0035567): pvalue calculation completed
Non-Canonical Wnt Signaling Pathway (GO:0035567): Calculation completed
Nuclear Chromosome Segregation (GO:0098813): Calculation started
Nuclear Chromosome Segregation (GO:0098813): scoring computed

Calculating pathways:  67%|██████▋   | 530/796 [43:36<20:01,  4.52s/it]

Nuclear Chromosome Segregation (GO:0098813): pvalue calculation completed
Nuclear Chromosome Segregation (GO:0098813): Calculation completed
Nucleic Acid Biosynthetic Process (GO:0141187): Calculation started
Nucleic Acid Biosynthetic Process (GO:0141187): scoring computed

Calculating pathways:  67%|██████▋   | 531/796 [43:40<18:43,  4.24s/it]

Nucleic Acid Biosynthetic Process (GO:0141187): pvalue calculation completed
Nucleic Acid Biosynthetic Process (GO:0141187): Calculation completed
Organelle Disassembly (GO:1903008): Calculation started
Organelle Disassembly (GO:1903008): scoring computed

Calculating pathways:  67%|██████▋   | 532/796 [43:44<18:22,  4.18s/it]

Organelle Disassembly (GO:1903008): pvalue calculation completed
Organelle Disassembly (GO:1903008): Calculation completed
Organelle Organization (GO:0006996): Calculation started
Organelle Organization (GO:0006996): scoring computed

Calculating pathways:  67%|██████▋   | 533/796 [43:52<23:53,  5.45s/it]

Organelle Organization (GO:0006996): pvalue calculation completed
Organelle Organization (GO:0006996): Calculation completed
Organic Anion Transport (GO:0015711): Calculation started
Organic Anion Transport (GO:0015711): scoring computed

Calculating pathways:  67%|██████▋   | 534/796 [43:57<22:46,  5.22s/it]

Organic Anion Transport (GO:0015711): pvalue calculation completed
Organic Anion Transport (GO:0015711): Calculation completed
Organic Hydroxy Compound Transport (GO:0015850): Calculation started
Organic Hydroxy Compound Transport (GO:0015850): scoring computed

Calculating pathways:  67%|██████▋   | 535/796 [44:01<21:01,  4.83s/it]

Organic Hydroxy Compound Transport (GO:0015850): pvalue calculation completed
Organic Hydroxy Compound Transport (GO:0015850): Calculation completed
Pattern Recognition Receptor Signaling Pathway (GO:0002221): Calculation started
Pattern Recognition Receptor Signaling Pathway (GO:0002221): scoring computed

Calculating pathways:  67%|██████▋   | 536/796 [44:05<20:02,  4.63s/it]

Pattern Recognition Receptor Signaling Pathway (GO:0002221): pvalue calculation completed
Pattern Recognition Receptor Signaling Pathway (GO:0002221): Calculation completed
Peptidyl-Serine Modification (GO:0018209): Calculation started
Peptidyl-Serine Modification (GO:0018209): scoring computed

Calculating pathways:  67%|██████▋   | 537/796 [44:09<19:30,  4.52s/it]

Peptidyl-Serine Modification (GO:0018209): pvalue calculation completed
Peptidyl-Serine Modification (GO:0018209): Calculation completed
Peptidyl-Serine Phosphorylation (GO:0018105): Calculation started
Peptidyl-Serine Phosphorylation (GO:0018105): scoring computed

Calculating pathways:  68%|██████▊   | 538/796 [44:13<19:06,  4.44s/it]

Peptidyl-Serine Phosphorylation (GO:0018105): pvalue calculation completed
Peptidyl-Serine Phosphorylation (GO:0018105): Calculation completed
Peptidyl-Tyrosine Autophosphorylation (GO:0038083): Calculation started
Peptidyl-Tyrosine Autophosphorylation (GO:0038083): scoring computed

Calculating pathways:  68%|██████▊   | 539/796 [44:17<18:13,  4.25s/it]

Peptidyl-Tyrosine Autophosphorylation (GO:0038083): pvalue calculation completed
Peptidyl-Tyrosine Autophosphorylation (GO:0038083): Calculation completed
Peptidyl-Tyrosine Modification (GO:0018212): Calculation started
Peptidyl-Tyrosine Modification (GO:0018212): scoring computed

Calculating pathways:  68%|██████▊   | 540/796 [44:21<17:49,  4.18s/it]

Peptidyl-Tyrosine Modification (GO:0018212): pvalue calculation completed
Peptidyl-Tyrosine Modification (GO:0018212): Calculation completed
Peptidyl-Tyrosine Phosphorylation (GO:0018108): Calculation started
Peptidyl-Tyrosine Phosphorylation (GO:0018108): scoring computed

Calculating pathways:  68%|██████▊   | 541/796 [44:25<17:40,  4.16s/it]

Peptidyl-Tyrosine Phosphorylation (GO:0018108): pvalue calculation completed
Peptidyl-Tyrosine Phosphorylation (GO:0018108): Calculation completed
Phagocytosis (GO:0006909): Calculation started
Phagocytosis (GO:0006909): scoring computed

Calculating pathways:  68%|██████▊   | 542/796 [44:30<17:51,  4.22s/it]

Phagocytosis (GO:0006909): pvalue calculation completed
Phagocytosis (GO:0006909): Calculation completed
Phosphatidylethanolamine Metabolic Process (GO:0046337): Calculation started
Phosphatidylethanolamine Metabolic Process (GO:0046337): scoring computed

Calculating pathways:  68%|██████▊   | 543/796 [44:33<17:07,  4.06s/it]

Phosphatidylethanolamine Metabolic Process (GO:0046337): pvalue calculation completed
Phosphatidylethanolamine Metabolic Process (GO:0046337): Calculation completed
Phosphatidylinositol 3-Kinase/Protein Kinase B Signal Transduction (GO:0043491): Calculation started
Phosphatidylinositol 3-Kinase/Protein Kinase B Signal Transduction (GO:0043491): scoring computed

Calculating pathways:  68%|██████▊   | 544/796 [44:37<16:54,  4.03s/it]

Phosphatidylinositol 3-Kinase/Protein Kinase B Signal Transduction (GO:0043491): pvalue calculation completed
Phosphatidylinositol 3-Kinase/Protein Kinase B Signal Transduction (GO:0043491): Calculation completed
Phospholipase C-activating G Protein-Coupled Receptor Signaling Pathway (GO:0007200): Calculation started
Phospholipase C-activating G Protein-Coupled Receptor Signaling Pathway (GO:0007200): scoring computed

Calculating pathways:  68%|██████▊   | 545/796 [44:42<17:30,  4.18s/it]

Phospholipase C-activating G Protein-Coupled Receptor Signaling Pathway (GO:0007200): pvalue calculation completed
Phospholipase C-activating G Protein-Coupled Receptor Signaling Pathway (GO:0007200): Calculation completed
Phospholipid Translocation (GO:0045332): Calculation started
Phospholipid Translocation (GO:0045332): scoring computed

Calculating pathways:  69%|██████▊   | 546/796 [44:46<17:01,  4.09s/it]

Phospholipid Translocation (GO:0045332): pvalue calculation completed
Phospholipid Translocation (GO:0045332): Calculation completed
Phospholipid Transport (GO:0015914): Calculation started
Phospholipid Transport (GO:0015914): scoring computed

Calculating pathways:  69%|██████▊   | 547/796 [44:50<17:05,  4.12s/it]

Phospholipid Transport (GO:0015914): pvalue calculation completed
Phospholipid Transport (GO:0015914): Calculation completed
Phosphorylation (GO:0016310): Calculation started
Phosphorylation (GO:0016310): scoring computed

Calculating pathways:  69%|██████▉   | 548/796 [44:57<20:39,  5.00s/it]

Phosphorylation (GO:0016310): pvalue calculation completed
Phosphorylation (GO:0016310): Calculation completed
Pigment Catabolic Process (GO:0046149): Calculation started
Pigment Catabolic Process (GO:0046149): scoring computed

Calculating pathways:  69%|██████▉   | 549/796 [45:00<18:48,  4.57s/it]

Pigment Catabolic Process (GO:0046149): pvalue calculation completed
Pigment Catabolic Process (GO:0046149): Calculation completed
Plasma Membrane Bounded Cell Projection Assembly (GO:0120031): Calculation started
Plasma Membrane Bounded Cell Projection Assembly (GO:0120031): scoring computed

Calculating pathways:  69%|██████▉   | 550/796 [45:07<21:30,  5.25s/it]

Plasma Membrane Bounded Cell Projection Assembly (GO:0120031): pvalue calculation completed
Plasma Membrane Bounded Cell Projection Assembly (GO:0120031): Calculation completed
Plasma Membrane Bounded Cell Projection Organization (GO:0120036): Calculation started
Plasma Membrane Bounded Cell Projection Organization (GO:0120036): scoring computed

Calculating pathways:  69%|██████▉   | 551/796 [45:13<21:34,  5.28s/it]

Plasma Membrane Bounded Cell Projection Organization (GO:0120036): pvalue calculation completed
Plasma Membrane Bounded Cell Projection Organization (GO:0120036): Calculation completed
Porphyrin-Containing Compound Catabolic Process (GO:0006787): Calculation started
Porphyrin-Containing Compound Catabolic Process (GO:0006787): scoring computed

Calculating pathways:  69%|██████▉   | 552/796 [45:16<19:16,  4.74s/it]

Porphyrin-Containing Compound Catabolic Process (GO:0006787): pvalue calculation completed
Porphyrin-Containing Compound Catabolic Process (GO:0006787): Calculation completed
Positive Regulation of DNA-templated Transcription (GO:0045893): Calculation started
Positive Regulation of DNA-templated Transcription (GO:0045893): scoring computed

Calculating pathways:  69%|██████▉   | 553/796 [45:33<33:28,  8.27s/it]

Positive Regulation of DNA-templated Transcription (GO:0045893): pvalue calculation completed
Positive Regulation of DNA-templated Transcription (GO:0045893): Calculation completed
Positive Regulation of ERK1 and ERK2 Cascade (GO:0070374): Calculation started
Positive Regulation of ERK1 and ERK2 Cascade (GO:0070374): scoring computed

Calculating pathways:  70%|██████▉   | 554/796 [45:38<29:49,  7.40s/it]

Positive Regulation of ERK1 and ERK2 Cascade (GO:0070374): pvalue calculation completed
Positive Regulation of ERK1 and ERK2 Cascade (GO:0070374): Calculation completed
Positive Regulation of MAP Kinase Activity (GO:0043406): Calculation started
Positive Regulation of MAP Kinase Activity (GO:0043406): scoring computed

Calculating pathways:  70%|██████▉   | 555/796 [45:42<25:46,  6.42s/it]

Positive Regulation of MAP Kinase Activity (GO:0043406): pvalue calculation completed
Positive Regulation of MAP Kinase Activity (GO:0043406): Calculation completed
Positive Regulation of MAPK Cascade (GO:0043410): Calculation started
Positive Regulation of MAPK Cascade (GO:0043410): scoring computed

Calculating pathways:  70%|██████▉   | 556/796 [45:50<26:55,  6.73s/it]

Positive Regulation of MAPK Cascade (GO:0043410): pvalue calculation completed
Positive Regulation of MAPK Cascade (GO:0043410): Calculation completed
Positive Regulation of RNA Biosynthetic Process (GO:1902680): Calculation started
Positive Regulation of RNA Biosynthetic Process (GO:1902680): scoring computed

Calculating pathways:  70%|██████▉   | 557/796 [45:59<30:07,  7.56s/it]

Positive Regulation of RNA Biosynthetic Process (GO:1902680): pvalue calculation completed
Positive Regulation of RNA Biosynthetic Process (GO:1902680): Calculation completed
Positive Regulation of Rho Protein Signal Transduction (GO:0035025): Calculation started
Positive Regulation of Rho Protein Signal Transduction (GO:0035025): scoring computed

Calculating pathways:  70%|███████   | 558/796 [46:03<25:40,  6.47s/it]

Positive Regulation of Rho Protein Signal Transduction (GO:0035025): pvalue calculation completed
Positive Regulation of Rho Protein Signal Transduction (GO:0035025): Calculation completed
Positive Regulation of T Cell Activation (GO:0050870): Calculation started
Positive Regulation of T Cell Activation (GO:0050870): scoring computed

Calculating pathways:  70%|███████   | 559/796 [46:08<23:32,  5.96s/it]

Positive Regulation of T Cell Activation (GO:0050870): pvalue calculation completed
Positive Regulation of T Cell Activation (GO:0050870): Calculation completed
Positive Regulation of T Cell Receptor Signaling Pathway (GO:0050862): Calculation started
Positive Regulation of T Cell Receptor Signaling Pathway (GO:0050862): scoring computed

Calculating pathways:  70%|███████   | 560/796 [46:11<20:38,  5.25s/it]

Positive Regulation of T Cell Receptor Signaling Pathway (GO:0050862): pvalue calculation completed
Positive Regulation of T Cell Receptor Signaling Pathway (GO:0050862): Calculation completed
Positive Regulation of Wnt Signaling Pathway (GO:0030177): Calculation started
Positive Regulation of Wnt Signaling Pathway (GO:0030177): scoring computed

Calculating pathways:  70%|███████   | 561/796 [46:16<20:09,  5.15s/it]

Positive Regulation of Wnt Signaling Pathway (GO:0030177): pvalue calculation completed
Positive Regulation of Wnt Signaling Pathway (GO:0030177): Calculation completed
Positive Regulation of Actin Filament Bundle Assembly (GO:0032233): Calculation started
Positive Regulation of Actin Filament Bundle Assembly (GO:0032233): scoring computed

Calculating pathways:  71%|███████   | 562/796 [46:20<18:41,  4.79s/it]

Positive Regulation of Actin Filament Bundle Assembly (GO:0032233): pvalue calculation completed
Positive Regulation of Actin Filament Bundle Assembly (GO:0032233): Calculation completed
Positive Regulation of Antigen Receptor-Mediated Signaling Pathway (GO:0050857): Calculation started
Positive Regulation of Antigen Receptor-Mediated Signaling Pathway (GO:0050857): scoring computed

Calculating pathways:  71%|███████   | 563/796 [46:24<17:21,  4.47s/it]

Positive Regulation of Antigen Receptor-Mediated Signaling Pathway (GO:0050857): pvalue calculation completed
Positive Regulation of Antigen Receptor-Mediated Signaling Pathway (GO:0050857): Calculation completed
Positive Regulation of Apoptotic Process (GO:0043065): Calculation started
Positive Regulation of Apoptotic Process (GO:0043065): scoring computed

Calculating pathways:  71%|███████   | 564/796 [46:31<20:21,  5.26s/it]

Positive Regulation of Apoptotic Process (GO:0043065): pvalue calculation completed
Positive Regulation of Apoptotic Process (GO:0043065): Calculation completed
Positive Regulation of Apoptotic Signaling Pathway (GO:2001235): Calculation started
Positive Regulation of Apoptotic Signaling Pathway (GO:2001235): scoring computed

Calculating pathways:  71%|███████   | 565/796 [46:35<19:12,  4.99s/it]

Positive Regulation of Apoptotic Signaling Pathway (GO:2001235): pvalue calculation completed
Positive Regulation of Apoptotic Signaling Pathway (GO:2001235): Calculation completed
Positive Regulation of Bicellular Tight Junction Assembly (GO:1903348): Calculation started
Positive Regulation of Bicellular Tight Junction Assembly (GO:1903348): scoring computed

Calculating pathways:  71%|███████   | 566/796 [46:39<17:25,  4.55s/it]

Positive Regulation of Bicellular Tight Junction Assembly (GO:1903348): pvalue calculation completed
Positive Regulation of Bicellular Tight Junction Assembly (GO:1903348): Calculation completed
Positive Regulation of Binding (GO:0051099): Calculation started
Positive Regulation of Binding (GO:0051099): scoring computed

Calculating pathways:  71%|███████   | 567/796 [46:43<17:01,  4.46s/it]

Positive Regulation of Binding (GO:0051099): pvalue calculation completed
Positive Regulation of Binding (GO:0051099): Calculation completed
Positive Regulation of Canonical NF-kappaB Signal Transduction (GO:0043123): Calculation started
Positive Regulation of Canonical NF-kappaB Signal Transduction (GO:0043123): scoring computed

Calculating pathways:  71%|███████▏  | 568/796 [46:49<18:39,  4.91s/it]

Positive Regulation of Canonical NF-kappaB Signal Transduction (GO:0043123): pvalue calculation completed
Positive Regulation of Canonical NF-kappaB Signal Transduction (GO:0043123): Calculation completed
Positive Regulation of Cell Adhesion (GO:0045785): Calculation started
Positive Regulation of Cell Adhesion (GO:0045785): scoring computed

Calculating pathways:  71%|███████▏  | 569/796 [46:54<18:00,  4.76s/it]

Positive Regulation of Cell Adhesion (GO:0045785): pvalue calculation completed
Positive Regulation of Cell Adhesion (GO:0045785): Calculation completed
Positive Regulation of Cell Cycle (GO:0045787): Calculation started
Positive Regulation of Cell Cycle (GO:0045787): scoring computed

Calculating pathways:  72%|███████▏  | 570/796 [46:58<17:26,  4.63s/it]

Positive Regulation of Cell Cycle (GO:0045787): pvalue calculation completed
Positive Regulation of Cell Cycle (GO:0045787): Calculation completed
Positive Regulation of Cell Cycle Process (GO:0090068): Calculation started
Positive Regulation of Cell Cycle Process (GO:0090068): scoring computed

Calculating pathways:  72%|███████▏  | 571/796 [47:03<17:38,  4.71s/it]

Positive Regulation of Cell Cycle Process (GO:0090068): pvalue calculation completed
Positive Regulation of Cell Cycle Process (GO:0090068): Calculation completed
Positive Regulation of Cell Growth (GO:0030307): Calculation started
Positive Regulation of Cell Growth (GO:0030307): scoring computed

Calculating pathways:  72%|███████▏  | 572/796 [47:08<17:41,  4.74s/it]

Positive Regulation of Cell Growth (GO:0030307): pvalue calculation completed
Positive Regulation of Cell Growth (GO:0030307): Calculation completed
Positive Regulation of Cell Junction Assembly (GO:1901890): Calculation started
Positive Regulation of Cell Junction Assembly (GO:1901890): scoring computed

Calculating pathways:  72%|███████▏  | 573/796 [47:12<17:00,  4.58s/it]

Positive Regulation of Cell Junction Assembly (GO:1901890): pvalue calculation completed
Positive Regulation of Cell Junction Assembly (GO:1901890): Calculation completed
Positive Regulation of Cell Migration (GO:0030335): Calculation started
Positive Regulation of Cell Migration (GO:0030335): scoring computed

Calculating pathways:  72%|███████▏  | 574/796 [47:19<19:58,  5.40s/it]

Positive Regulation of Cell Migration (GO:0030335): pvalue calculation completed
Positive Regulation of Cell Migration (GO:0030335): Calculation completed
Positive Regulation of Cell Population Proliferation (GO:0008284): Calculation started
Positive Regulation of Cell Population Proliferation (GO:0008284): scoring computed

Calculating pathways:  72%|███████▏  | 575/796 [47:28<23:23,  6.35s/it]

Positive Regulation of Cell Population Proliferation (GO:0008284): pvalue calculation completed
Positive Regulation of Cell Population Proliferation (GO:0008284): Calculation completed
Positive Regulation of Cell-Cell Adhesion (GO:0022409): Calculation started
Positive Regulation of Cell-Cell Adhesion (GO:0022409): scoring computed

Calculating pathways:  72%|███████▏  | 576/796 [47:32<20:43,  5.65s/it]

Positive Regulation of Cell-Cell Adhesion (GO:0022409): pvalue calculation completed
Positive Regulation of Cell-Cell Adhesion (GO:0022409): Calculation completed
Positive Regulation of Cell-Matrix Adhesion (GO:0001954): Calculation started
Positive Regulation of Cell-Matrix Adhesion (GO:0001954): scoring computed

Calculating pathways:  72%|███████▏  | 577/796 [47:36<18:43,  5.13s/it]

Positive Regulation of Cell-Matrix Adhesion (GO:0001954): pvalue calculation completed
Positive Regulation of Cell-Matrix Adhesion (GO:0001954): Calculation completed
Positive Regulation of Cell-Substrate Adhesion (GO:0010811): Calculation started
Positive Regulation of Cell-Substrate Adhesion (GO:0010811): scoring computed

Calculating pathways:  73%|███████▎  | 578/796 [47:40<17:40,  4.86s/it]

Positive Regulation of Cell-Substrate Adhesion (GO:0010811): pvalue calculation completed
Positive Regulation of Cell-Substrate Adhesion (GO:0010811): Calculation completed
Positive Regulation of Cell-Substrate Junction Organization (GO:0150117): Calculation started
Positive Regulation of Cell-Substrate Junction Organization (GO:0150117): scoring computed

Calculating pathways:  73%|███████▎  | 579/796 [47:44<16:32,  4.57s/it]

Positive Regulation of Cell-Substrate Junction Organization (GO:0150117): pvalue calculation completed
Positive Regulation of Cell-Substrate Junction Organization (GO:0150117): Calculation completed
Positive Regulation of Cellular Process (GO:0048522): Calculation started
Positive Regulation of Cellular Process (GO:0048522): scoring computed

Calculating pathways:  73%|███████▎  | 580/796 [47:54<22:14,  6.18s/it]

Positive Regulation of Cellular Process (GO:0048522): pvalue calculation completed
Positive Regulation of Cellular Process (GO:0048522): Calculation completed
Positive Regulation of Cytokine Production (GO:0001819): Calculation started
Positive Regulation of Cytokine Production (GO:0001819): scoring computed

Calculating pathways:  73%|███████▎  | 581/796 [48:01<22:52,  6.38s/it]

Positive Regulation of Cytokine Production (GO:0001819): pvalue calculation completed
Positive Regulation of Cytokine Production (GO:0001819): Calculation completed
Positive Regulation of Cytokine-Mediated Signaling Pathway (GO:0001961): Calculation started
Positive Regulation of Cytokine-Mediated Signaling Pathway (GO:0001961): scoring computed

Calculating pathways:  73%|███████▎  | 582/796 [48:05<20:12,  5.67s/it]

Positive Regulation of Cytokine-Mediated Signaling Pathway (GO:0001961): pvalue calculation completed
Positive Regulation of Cytokine-Mediated Signaling Pathway (GO:0001961): Calculation completed
Positive Regulation of Defense Response (GO:0031349): Calculation started
Positive Regulation of Defense Response (GO:0031349): scoring computed

Calculating pathways:  73%|███████▎  | 583/796 [48:10<19:26,  5.48s/it]

Positive Regulation of Defense Response (GO:0031349): pvalue calculation completed
Positive Regulation of Defense Response (GO:0031349): Calculation completed
Positive Regulation of Developmental Process (GO:0051094): Calculation started
Positive Regulation of Developmental Process (GO:0051094): scoring computed

Calculating pathways:  73%|███████▎  | 584/796 [48:16<20:10,  5.71s/it]

Positive Regulation of Developmental Process (GO:0051094): pvalue calculation completed
Positive Regulation of Developmental Process (GO:0051094): Calculation completed
Positive Regulation of Endothelial Cell Migration (GO:0010595): Calculation started
Positive Regulation of Endothelial Cell Migration (GO:0010595): scoring computed

Calculating pathways:  73%|███████▎  | 585/796 [48:20<18:44,  5.33s/it]

Positive Regulation of Endothelial Cell Migration (GO:0010595): pvalue calculation completed
Positive Regulation of Endothelial Cell Migration (GO:0010595): Calculation completed
Positive Regulation of Epithelial Cell Proliferation (GO:0050679): Calculation started
Positive Regulation of Epithelial Cell Proliferation (GO:0050679): scoring computed

Calculating pathways:  74%|███████▎  | 586/796 [48:25<18:10,  5.19s/it]

Positive Regulation of Epithelial Cell Proliferation (GO:0050679): pvalue calculation completed
Positive Regulation of Epithelial Cell Proliferation (GO:0050679): Calculation completed
Positive Regulation of Establishment of Protein Localization (GO:1904951): Calculation started
Positive Regulation of Establishment of Protein Localization (GO:1904951): scoring computed

Calculating pathways:  74%|███████▎  | 587/796 [48:29<16:38,  4.78s/it]

Positive Regulation of Establishment of Protein Localization (GO:1904951): pvalue calculation completed
Positive Regulation of Establishment of Protein Localization (GO:1904951): Calculation completed
Positive Regulation of Focal Adhesion Assembly (GO:0051894): Calculation started
Positive Regulation of Focal Adhesion Assembly (GO:0051894): scoring computed

Calculating pathways:  74%|███████▍  | 588/796 [48:33<15:20,  4.43s/it]

Positive Regulation of Focal Adhesion Assembly (GO:0051894): pvalue calculation completed
Positive Regulation of Focal Adhesion Assembly (GO:0051894): Calculation completed
Positive Regulation of Gene Expression (GO:0010628): Calculation started
Positive Regulation of Gene Expression (GO:0010628): scoring computed

Calculating pathways:  74%|███████▍  | 589/796 [48:41<19:14,  5.58s/it]

Positive Regulation of Gene Expression (GO:0010628): pvalue calculation completed
Positive Regulation of Gene Expression (GO:0010628): Calculation completed
Positive Regulation of Granulocyte Chemotaxis (GO:0071624): Calculation started
Positive Regulation of Granulocyte Chemotaxis (GO:0071624): scoring computed

Calculating pathways:  74%|███████▍  | 590/796 [48:45<17:11,  5.01s/it]

Positive Regulation of Granulocyte Chemotaxis (GO:0071624): pvalue calculation completed
Positive Regulation of Granulocyte Chemotaxis (GO:0071624): Calculation completed
Positive Regulation of Growth (GO:0045927): Calculation started
Positive Regulation of Growth (GO:0045927): scoring computed

Calculating pathways:  74%|███████▍  | 591/796 [48:49<16:19,  4.78s/it]

Positive Regulation of Growth (GO:0045927): pvalue calculation completed
Positive Regulation of Growth (GO:0045927): Calculation completed
Positive Regulation of Heterotypic Cell-Cell Adhesion (GO:0034116): Calculation started
Positive Regulation of Heterotypic Cell-Cell Adhesion (GO:0034116): scoring computed

Calculating pathways:  74%|███████▍  | 592/796 [48:52<15:05,  4.44s/it]

Positive Regulation of Heterotypic Cell-Cell Adhesion (GO:0034116): pvalue calculation completed
Positive Regulation of Heterotypic Cell-Cell Adhesion (GO:0034116): Calculation completed
Positive Regulation of Inflammatory Response (GO:0050729): Calculation started
Positive Regulation of Inflammatory Response (GO:0050729): scoring computed

Calculating pathways:  74%|███████▍  | 593/796 [48:57<15:20,  4.54s/it]

Positive Regulation of Inflammatory Response (GO:0050729): pvalue calculation completed
Positive Regulation of Inflammatory Response (GO:0050729): Calculation completed
Positive Regulation of Interleukin-1 Beta Production (GO:0032731): Calculation started
Positive Regulation of Interleukin-1 Beta Production (GO:0032731): scoring computed

Calculating pathways:  75%|███████▍  | 594/796 [49:01<14:53,  4.42s/it]

Positive Regulation of Interleukin-1 Beta Production (GO:0032731): pvalue calculation completed
Positive Regulation of Interleukin-1 Beta Production (GO:0032731): Calculation completed
Positive Regulation of Interleukin-1 Production (GO:0032732): Calculation started
Positive Regulation of Interleukin-1 Production (GO:0032732): scoring computed

Calculating pathways:  75%|███████▍  | 595/796 [49:05<14:30,  4.33s/it]

Positive Regulation of Interleukin-1 Production (GO:0032732): pvalue calculation completed
Positive Regulation of Interleukin-1 Production (GO:0032732): Calculation completed
Positive Regulation of Intracellular Signal Transduction (GO:1902533): Calculation started
Positive Regulation of Intracellular Signal Transduction (GO:1902533): scoring computed

Calculating pathways:  75%|███████▍  | 596/796 [49:16<20:31,  6.16s/it]

Positive Regulation of Intracellular Signal Transduction (GO:1902533): pvalue calculation completed
Positive Regulation of Intracellular Signal Transduction (GO:1902533): Calculation completed
Positive Regulation of Intrinsic Apoptotic Signaling Pathway (GO:2001244): Calculation started
Positive Regulation of Intrinsic Apoptotic Signaling Pathway (GO:2001244): scoring computed

Calculating pathways:  75%|███████▌  | 597/796 [49:20<18:16,  5.51s/it]

Positive Regulation of Intrinsic Apoptotic Signaling Pathway (GO:2001244): pvalue calculation completed
Positive Regulation of Intrinsic Apoptotic Signaling Pathway (GO:2001244): Calculation completed
Positive Regulation of Lamellipodium Assembly (GO:0010592): Calculation started
Positive Regulation of Lamellipodium Assembly (GO:0010592): scoring computed

Calculating pathways:  75%|███████▌  | 598/796 [49:24<16:29,  5.00s/it]

Positive Regulation of Lamellipodium Assembly (GO:0010592): pvalue calculation completed
Positive Regulation of Lamellipodium Assembly (GO:0010592): Calculation completed
Positive Regulation of Lamellipodium Organization (GO:1902745): Calculation started
Positive Regulation of Lamellipodium Organization (GO:1902745): scoring computed

Calculating pathways:  75%|███████▌  | 599/796 [49:27<15:08,  4.61s/it]

Positive Regulation of Lamellipodium Organization (GO:1902745): pvalue calculation completed
Positive Regulation of Lamellipodium Organization (GO:1902745): Calculation completed
Positive Regulation of Leukocyte Cell-Cell Adhesion (GO:1903039): Calculation started
Positive Regulation of Leukocyte Cell-Cell Adhesion (GO:1903039): scoring computed

Calculating pathways:  75%|███████▌  | 600/796 [49:31<14:21,  4.39s/it]

Positive Regulation of Leukocyte Cell-Cell Adhesion (GO:1903039): pvalue calculation completed
Positive Regulation of Leukocyte Cell-Cell Adhesion (GO:1903039): Calculation completed
Positive Regulation of Lymphocyte Activation (GO:0051251): Calculation started
Positive Regulation of Lymphocyte Activation (GO:0051251): scoring computed

Calculating pathways:  76%|███████▌  | 601/796 [49:35<13:47,  4.24s/it]

Positive Regulation of Lymphocyte Activation (GO:0051251): pvalue calculation completed
Positive Regulation of Lymphocyte Activation (GO:0051251): Calculation completed
Positive Regulation of miRNA Metabolic Process (GO:2000630): Calculation started
Positive Regulation of miRNA Metabolic Process (GO:2000630): scoring computed

Calculating pathways:  76%|███████▌  | 602/796 [49:39<13:35,  4.20s/it]

Positive Regulation of miRNA Metabolic Process (GO:2000630): pvalue calculation completed
Positive Regulation of miRNA Metabolic Process (GO:2000630): Calculation completed
Positive Regulation of miRNA Transcription (GO:1902895): Calculation started
Positive Regulation of miRNA Transcription (GO:1902895): scoring computed

Calculating pathways:  76%|███████▌  | 603/796 [49:43<13:19,  4.14s/it]

Positive Regulation of miRNA Transcription (GO:1902895): pvalue calculation completed
Positive Regulation of miRNA Transcription (GO:1902895): Calculation completed
Positive Regulation of Microtubule Polymerization (GO:0031116): Calculation started
Positive Regulation of Microtubule Polymerization (GO:0031116): scoring computed

Calculating pathways:  76%|███████▌  | 604/796 [49:47<13:03,  4.08s/it]

Positive Regulation of Microtubule Polymerization (GO:0031116): pvalue calculation completed
Positive Regulation of Microtubule Polymerization (GO:0031116): Calculation completed
Positive Regulation of Microtubule Polymerization or Depolymerization (GO:0031112): Calculation started
Positive Regulation of Microtubule Polymerization or Depolymerization (GO:0031112): scoring computed

Calculating pathways:  76%|███████▌  | 605/796 [49:51<12:41,  3.99s/it]

Positive Regulation of Microtubule Polymerization or Depolymerization (GO:0031112): pvalue calculation completed
Positive Regulation of Microtubule Polymerization or Depolymerization (GO:0031112): Calculation completed
Positive Regulation of Mitotic Cell Cycle (GO:0045931): Calculation started
Positive Regulation of Mitotic Cell Cycle (GO:0045931): scoring computed

Calculating pathways:  76%|███████▌  | 606/796 [49:55<12:24,  3.92s/it]

Positive Regulation of Mitotic Cell Cycle (GO:0045931): pvalue calculation completed
Positive Regulation of Mitotic Cell Cycle (GO:0045931): Calculation completed
Positive Regulation of Mitotic Nuclear Division (GO:0045840): Calculation started
Positive Regulation of Mitotic Nuclear Division (GO:0045840): scoring computed

Calculating pathways:  76%|███████▋  | 607/796 [49:59<12:14,  3.89s/it]

Positive Regulation of Mitotic Nuclear Division (GO:0045840): pvalue calculation completed
Positive Regulation of Mitotic Nuclear Division (GO:0045840): Calculation completed
Positive Regulation of Monoatomic Ion Transport (GO:0043270): Calculation started
Positive Regulation of Monoatomic Ion Transport (GO:0043270): scoring computed

Calculating pathways:  76%|███████▋  | 608/796 [50:02<12:07,  3.87s/it]

Positive Regulation of Monoatomic Ion Transport (GO:0043270): pvalue calculation completed
Positive Regulation of Monoatomic Ion Transport (GO:0043270): Calculation completed
Positive Regulation of Monooxygenase Activity (GO:0032770): Calculation started
Positive Regulation of Monooxygenase Activity (GO:0032770): scoring computed

Calculating pathways:  77%|███████▋  | 609/796 [50:06<11:51,  3.80s/it]

Positive Regulation of Monooxygenase Activity (GO:0032770): pvalue calculation completed
Positive Regulation of Monooxygenase Activity (GO:0032770): Calculation completed
Positive Regulation of Multicellular Organismal Process (GO:0051240): Calculation started
Positive Regulation of Multicellular Organismal Process (GO:0051240): scoring computed

Calculating pathways:  77%|███████▋  | 610/796 [50:14<15:31,  5.01s/it]

Positive Regulation of Multicellular Organismal Process (GO:0051240): pvalue calculation completed
Positive Regulation of Multicellular Organismal Process (GO:0051240): Calculation completed
Positive Regulation of Neutrophil Chemotaxis (GO:0090023): Calculation started
Positive Regulation of Neutrophil Chemotaxis (GO:0090023): scoring computed

Calculating pathways:  77%|███████▋  | 611/796 [50:17<14:08,  4.59s/it]

Positive Regulation of Neutrophil Chemotaxis (GO:0090023): pvalue calculation completed
Positive Regulation of Neutrophil Chemotaxis (GO:0090023): Calculation completed
Positive Regulation of Neutrophil Migration (GO:1902624): Calculation started
Positive Regulation of Neutrophil Migration (GO:1902624): scoring computed

Calculating pathways:  77%|███████▋  | 612/796 [50:21<13:12,  4.31s/it]

Positive Regulation of Neutrophil Migration (GO:1902624): pvalue calculation completed
Positive Regulation of Neutrophil Migration (GO:1902624): Calculation completed
Positive Regulation of Nitric-Oxide Synthase Activity (GO:0051000): Calculation started
Positive Regulation of Nitric-Oxide Synthase Activity (GO:0051000): scoring computed

Calculating pathways:  77%|███████▋  | 613/796 [50:25<12:23,  4.06s/it]

Positive Regulation of Nitric-Oxide Synthase Activity (GO:0051000): pvalue calculation completed
Positive Regulation of Nitric-Oxide Synthase Activity (GO:0051000): Calculation completed
Positive Regulation of Organelle Organization (GO:0010638): Calculation started
Positive Regulation of Organelle Organization (GO:0010638): scoring computed

Calculating pathways:  77%|███████▋  | 614/796 [50:29<12:40,  4.18s/it]

Positive Regulation of Organelle Organization (GO:0010638): pvalue calculation completed
Positive Regulation of Organelle Organization (GO:0010638): Calculation completed
Positive Regulation of Phosphorylation (GO:0042327): Calculation started
Positive Regulation of Phosphorylation (GO:0042327): scoring computed

Calculating pathways:  77%|███████▋  | 615/796 [50:34<13:00,  4.31s/it]

Positive Regulation of Phosphorylation (GO:0042327): pvalue calculation completed
Positive Regulation of Phosphorylation (GO:0042327): Calculation completed
Positive Regulation of Plasma Membrane Bounded Cell Projection Assembly (GO:0120034): Calculation started
Positive Regulation of Plasma Membrane Bounded Cell Projection Assembly (GO:0120034): scoring computed

Calculating pathways:  77%|███████▋  | 616/796 [50:38<13:09,  4.39s/it]

Positive Regulation of Plasma Membrane Bounded Cell Projection Assembly (GO:0120034): pvalue calculation completed
Positive Regulation of Plasma Membrane Bounded Cell Projection Assembly (GO:0120034): Calculation completed
Positive Regulation of Programmed Cell Death (GO:0043068): Calculation started
Positive Regulation of Programmed Cell Death (GO:0043068): scoring computed

Calculating pathways:  78%|███████▊  | 617/796 [50:45<14:55,  5.01s/it]

Positive Regulation of Programmed Cell Death (GO:0043068): pvalue calculation completed
Positive Regulation of Programmed Cell Death (GO:0043068): Calculation completed
Positive Regulation of Protein Binding (GO:0032092): Calculation started
Positive Regulation of Protein Binding (GO:0032092): scoring computed

Calculating pathways:  78%|███████▊  | 618/796 [50:49<13:51,  4.67s/it]

Positive Regulation of Protein Binding (GO:0032092): pvalue calculation completed
Positive Regulation of Protein Binding (GO:0032092): Calculation completed
Positive Regulation of Protein Localization (GO:1903829): Calculation started
Positive Regulation of Protein Localization (GO:1903829): scoring computed

Calculating pathways:  78%|███████▊  | 619/796 [50:53<13:51,  4.70s/it]

Positive Regulation of Protein Localization (GO:1903829): pvalue calculation completed
Positive Regulation of Protein Localization (GO:1903829): Calculation completed
Positive Regulation of Protein Localization to Membrane (GO:1905477): Calculation started
Positive Regulation of Protein Localization to Membrane (GO:1905477): scoring computed

Calculating pathways:  78%|███████▊  | 620/796 [50:58<13:29,  4.60s/it]

Positive Regulation of Protein Localization to Membrane (GO:1905477): pvalue calculation completed
Positive Regulation of Protein Localization to Membrane (GO:1905477): Calculation completed
Positive Regulation of Protein Localization to Nucleus (GO:1900182): Calculation started
Positive Regulation of Protein Localization to Nucleus (GO:1900182): scoring computed

Calculating pathways:  78%|███████▊  | 621/796 [51:02<13:20,  4.58s/it]

Positive Regulation of Protein Localization to Nucleus (GO:1900182): pvalue calculation completed
Positive Regulation of Protein Localization to Nucleus (GO:1900182): Calculation completed
Positive Regulation of Protein Metabolic Process (GO:0051247): Calculation started
Positive Regulation of Protein Metabolic Process (GO:0051247): scoring computed

Calculating pathways:  78%|███████▊  | 622/796 [51:08<14:26,  4.98s/it]

Positive Regulation of Protein Metabolic Process (GO:0051247): pvalue calculation completed
Positive Regulation of Protein Metabolic Process (GO:0051247): Calculation completed
Positive Regulation of Protein Modification Process (GO:0031401): Calculation started
Positive Regulation of Protein Modification Process (GO:0031401): scoring computed

Calculating pathways:  78%|███████▊  | 623/796 [51:13<13:56,  4.83s/it]

Positive Regulation of Protein Modification Process (GO:0031401): pvalue calculation completed
Positive Regulation of Protein Modification Process (GO:0031401): Calculation completed
Positive Regulation of Protein Phosphorylation (GO:0001934): Calculation started
Positive Regulation of Protein Phosphorylation (GO:0001934): scoring computed

Calculating pathways:  78%|███████▊  | 624/796 [51:18<14:32,  5.07s/it]

Positive Regulation of Protein Phosphorylation (GO:0001934): pvalue calculation completed
Positive Regulation of Protein Phosphorylation (GO:0001934): Calculation completed
Positive Regulation of Protein Polymerization (GO:0032273): Calculation started
Positive Regulation of Protein Polymerization (GO:0032273): scoring computed

Calculating pathways:  79%|███████▊  | 625/796 [51:23<13:52,  4.87s/it]

Positive Regulation of Protein Polymerization (GO:0032273): pvalue calculation completed
Positive Regulation of Protein Polymerization (GO:0032273): Calculation completed
Positive Regulation of Protein Serine/Threonine Kinase Activity (GO:0071902): Calculation started
Positive Regulation of Protein Serine/Threonine Kinase Activity (GO:0071902): scoring computed

Calculating pathways:  79%|███████▊  | 626/796 [51:27<13:20,  4.71s/it]

Positive Regulation of Protein Serine/Threonine Kinase Activity (GO:0071902): pvalue calculation completed
Positive Regulation of Protein Serine/Threonine Kinase Activity (GO:0071902): Calculation completed
Positive Regulation of Protein Targeting to Membrane (GO:0090314): Calculation started
Positive Regulation of Protein Targeting to Membrane (GO:0090314): scoring computed

Calculating pathways:  79%|███████▉  | 627/796 [51:31<12:24,  4.41s/it]

Positive Regulation of Protein Targeting to Membrane (GO:0090314): pvalue calculation completed
Positive Regulation of Protein Targeting to Membrane (GO:0090314): Calculation completed
Positive Regulation of Response to External Stimulus (GO:0032103): Calculation started
Positive Regulation of Response to External Stimulus (GO:0032103): scoring computed

Calculating pathways:  79%|███████▉  | 628/796 [51:36<13:11,  4.71s/it]

Positive Regulation of Response to External Stimulus (GO:0032103): pvalue calculation completed
Positive Regulation of Response to External Stimulus (GO:0032103): Calculation completed
Positive Regulation of Signal Transduction (GO:0009967): Calculation started
Positive Regulation of Signal Transduction (GO:0009967): scoring computed

Calculating pathways:  79%|███████▉  | 629/796 [51:43<14:30,  5.21s/it]

Positive Regulation of Signal Transduction (GO:0009967): pvalue calculation completed
Positive Regulation of Signal Transduction (GO:0009967): Calculation completed
Positive Regulation of Small GTPase Mediated Signal Transduction (GO:0051057): Calculation started
Positive Regulation of Small GTPase Mediated Signal Transduction (GO:0051057): scoring computed

Calculating pathways:  79%|███████▉  | 630/796 [51:47<13:34,  4.91s/it]

Positive Regulation of Small GTPase Mediated Signal Transduction (GO:0051057): pvalue calculation completed
Positive Regulation of Small GTPase Mediated Signal Transduction (GO:0051057): Calculation completed
Positive Regulation of Smooth Muscle Cell Proliferation (GO:0048661): Calculation started
Positive Regulation of Smooth Muscle Cell Proliferation (GO:0048661): scoring computed

Calculating pathways:  79%|███████▉  | 631/796 [51:51<12:59,  4.72s/it]

Positive Regulation of Smooth Muscle Cell Proliferation (GO:0048661): pvalue calculation completed
Positive Regulation of Smooth Muscle Cell Proliferation (GO:0048661): Calculation completed
Positive Regulation of Stem Cell Proliferation (GO:2000648): Calculation started
Positive Regulation of Stem Cell Proliferation (GO:2000648): scoring computed

Calculating pathways:  79%|███████▉  | 632/796 [51:55<12:07,  4.44s/it]

Positive Regulation of Stem Cell Proliferation (GO:2000648): pvalue calculation completed
Positive Regulation of Stem Cell Proliferation (GO:2000648): Calculation completed
Positive Regulation of Stress Fiber Assembly (GO:0051496): Calculation started
Positive Regulation of Stress Fiber Assembly (GO:0051496): scoring computed

Calculating pathways:  80%|███████▉  | 633/796 [51:59<11:35,  4.27s/it]

Positive Regulation of Stress Fiber Assembly (GO:0051496): pvalue calculation completed
Positive Regulation of Stress Fiber Assembly (GO:0051496): Calculation completed
Positive Regulation of Substrate Adhesion-Dependent Cell Spreading (GO:1900026): Calculation started
Positive Regulation of Substrate Adhesion-Dependent Cell Spreading (GO:1900026): scoring computed

Calculating pathways:  80%|███████▉  | 634/796 [52:02<11:08,  4.13s/it]

Positive Regulation of Substrate Adhesion-Dependent Cell Spreading (GO:1900026): pvalue calculation completed
Positive Regulation of Substrate Adhesion-Dependent Cell Spreading (GO:1900026): Calculation completed
Positive Regulation of Supramolecular Fiber Organization (GO:1902905): Calculation started
Positive Regulation of Supramolecular Fiber Organization (GO:1902905): scoring computed

Calculating pathways:  80%|███████▉  | 635/796 [52:07<11:31,  4.30s/it]

Positive Regulation of Supramolecular Fiber Organization (GO:1902905): pvalue calculation completed
Positive Regulation of Supramolecular Fiber Organization (GO:1902905): Calculation completed
Positive Regulation of Transcription by RNA Polymerase I (GO:0045943): Calculation started
Positive Regulation of Transcription by RNA Polymerase I (GO:0045943): scoring computed

Calculating pathways:  80%|███████▉  | 636/796 [52:11<11:02,  4.14s/it]

Positive Regulation of Transcription by RNA Polymerase I (GO:0045943): pvalue calculation completed
Positive Regulation of Transcription by RNA Polymerase I (GO:0045943): Calculation completed
Positive Regulation of Translation (GO:0045727): Calculation started
Positive Regulation of Translation (GO:0045727): scoring computed

Calculating pathways:  80%|████████  | 637/796 [52:16<11:27,  4.32s/it]

Positive Regulation of Translation (GO:0045727): pvalue calculation completed
Positive Regulation of Translation (GO:0045727): Calculation completed
Positive Regulation of Transport (GO:0051050): Calculation started
Positive Regulation of Transport (GO:0051050): scoring computed

Calculating pathways:  80%|████████  | 638/796 [52:20<11:06,  4.22s/it]

Positive Regulation of Transport (GO:0051050): pvalue calculation completed
Positive Regulation of Transport (GO:0051050): Calculation completed
Positive Regulation of Tumor Necrosis Factor-Mediated Signaling Pathway (GO:1903265): Calculation started
Positive Regulation of Tumor Necrosis Factor-Mediated Signaling Pathway (GO:1903265): scoring computed

Calculating pathways:  80%|████████  | 639/796 [52:23<10:27,  4.00s/it]

Positive Regulation of Tumor Necrosis Factor-Mediated Signaling Pathway (GO:1903265): pvalue calculation completed
Positive Regulation of Tumor Necrosis Factor-Mediated Signaling Pathway (GO:1903265): Calculation completed
Positive Regulation of Vascular Associated Smooth Muscle Cell Proliferation (GO:1904707): Calculation started
Positive Regulation of Vascular Associated Smooth Muscle Cell Proliferation (GO:1904707): scoring computed

Calculating pathways:  80%|████████  | 640/796 [52:27<10:05,  3.88s/it]

Positive Regulation of Vascular Associated Smooth Muscle Cell Proliferation (GO:1904707): pvalue calculation completed
Positive Regulation of Vascular Associated Smooth Muscle Cell Proliferation (GO:1904707): Calculation completed
Positive Regulation of Viral Genome Replication (GO:0045070): Calculation started
Positive Regulation of Viral Genome Replication (GO:0045070): scoring computed

Calculating pathways:  81%|████████  | 641/796 [52:30<09:54,  3.83s/it]

Positive Regulation of Viral Genome Replication (GO:0045070): pvalue calculation completed
Positive Regulation of Viral Genome Replication (GO:0045070): Calculation completed
Protein Autophosphorylation (GO:0046777): Calculation started
Protein Autophosphorylation (GO:0046777): scoring computed

Calculating pathways:  81%|████████  | 642/796 [52:36<10:57,  4.27s/it]

Protein Autophosphorylation (GO:0046777): pvalue calculation completed
Protein Autophosphorylation (GO:0046777): Calculation completed
Protein Autoprocessing (GO:0016540): Calculation started
Protein Autoprocessing (GO:0016540): scoring computed

Calculating pathways:  81%|████████  | 643/796 [52:39<10:24,  4.08s/it]

Protein Autoprocessing (GO:0016540): pvalue calculation completed
Protein Autoprocessing (GO:0016540): Calculation completed
Protein Import Into Nucleus (GO:0006606): Calculation started
Protein Import Into Nucleus (GO:0006606): scoring computed

Calculating pathways:  81%|████████  | 644/796 [52:44<10:38,  4.20s/it]

Protein Import Into Nucleus (GO:0006606): pvalue calculation completed
Protein Import Into Nucleus (GO:0006606): Calculation completed
Protein Localization to Chromosome, Telomeric Region (GO:0070198): Calculation started
Protein Localization to Chromosome, Telomeric Region (GO:0070198): scoring computed

Calculating pathways:  81%|████████  | 645/796 [52:47<10:04,  4.00s/it]

Protein Localization to Chromosome, Telomeric Region (GO:0070198): pvalue calculation completed
Protein Localization to Chromosome, Telomeric Region (GO:0070198): Calculation completed
Protein Localization to Nucleus (GO:0034504): Calculation started
Protein Localization to Nucleus (GO:0034504): scoring computed

Calculating pathways:  81%|████████  | 646/796 [52:53<10:52,  4.35s/it]

Protein Localization to Nucleus (GO:0034504): pvalue calculation completed
Protein Localization to Nucleus (GO:0034504): Calculation completed
Protein Maturation (GO:0051604): Calculation started
Protein Maturation (GO:0051604): scoring computed

Calculating pathways:  81%|████████▏ | 647/796 [52:58<11:31,  4.64s/it]

Protein Maturation (GO:0051604): pvalue calculation completed
Protein Maturation (GO:0051604): Calculation completed
Protein Metabolic Process (GO:0019538): Calculation started
Protein Metabolic Process (GO:0019538): scoring computed

Calculating pathways:  81%|████████▏ | 648/796 [53:08<15:22,  6.23s/it]

Protein Metabolic Process (GO:0019538): pvalue calculation completed
Protein Metabolic Process (GO:0019538): Calculation completed
Protein Modification Process (GO:0036211): Calculation started
Protein Modification Process (GO:0036211): scoring computed

Calculating pathways:  82%|████████▏ | 649/796 [53:17<17:47,  7.26s/it]

Protein Modification Process (GO:0036211): pvalue calculation completed
Protein Modification Process (GO:0036211): Calculation completed
Protein Phosphorylation (GO:0006468): Calculation started
Protein Phosphorylation (GO:0006468): scoring computed

Calculating pathways:  82%|████████▏ | 650/796 [53:25<18:07,  7.45s/it]

Protein Phosphorylation (GO:0006468): pvalue calculation completed
Protein Phosphorylation (GO:0006468): Calculation completed
Protein Polymerization (GO:0051258): Calculation started
Protein Polymerization (GO:0051258): scoring computed

Calculating pathways:  82%|████████▏ | 651/796 [53:30<15:39,  6.48s/it]

Protein Polymerization (GO:0051258): pvalue calculation completed
Protein Polymerization (GO:0051258): Calculation completed
Protein Processing (GO:0016485): Calculation started
Protein Processing (GO:0016485): scoring computed

Calculating pathways:  82%|████████▏ | 652/796 [53:35<14:28,  6.03s/it]

Protein Processing (GO:0016485): pvalue calculation completed
Protein Processing (GO:0016485): Calculation completed
Protein-Containing Complex Assembly (GO:0065003): Calculation started
Protein-Containing Complex Assembly (GO:0065003): scoring computed

Calculating pathways:  82%|████████▏ | 653/796 [53:42<15:14,  6.40s/it]

Protein-Containing Complex Assembly (GO:0065003): pvalue calculation completed
Protein-Containing Complex Assembly (GO:0065003): Calculation completed
Proteolysis (GO:0006508): Calculation started
Proteolysis (GO:0006508): scoring computed

Calculating pathways:  82%|████████▏ | 654/796 [53:49<15:26,  6.53s/it]

Proteolysis (GO:0006508): pvalue calculation completed
Proteolysis (GO:0006508): Calculation completed
Purine Ribonucleotide Transport (GO:0015868): Calculation started
Purine Ribonucleotide Transport (GO:0015868): scoring computed

Calculating pathways:  82%|████████▏ | 655/796 [53:52<13:19,  5.67s/it]

Purine Ribonucleotide Transport (GO:0015868): pvalue calculation completed
Purine Ribonucleotide Transport (GO:0015868): Calculation completed
Pyroptotic Inflammatory Response (GO:0070269): Calculation started
Pyroptotic Inflammatory Response (GO:0070269): scoring computed

Calculating pathways:  82%|████████▏ | 656/796 [53:56<11:58,  5.13s/it]

Pyroptotic Inflammatory Response (GO:0070269): pvalue calculation completed
Pyroptotic Inflammatory Response (GO:0070269): Calculation completed
Reelin-Mediated Signaling Pathway (GO:0038026): Calculation started
Reelin-Mediated Signaling Pathway (GO:0038026): scoring computed

Calculating pathways:  83%|████████▎ | 657/796 [54:00<10:51,  4.69s/it]

Reelin-Mediated Signaling Pathway (GO:0038026): pvalue calculation completed
Reelin-Mediated Signaling Pathway (GO:0038026): Calculation completed
Regulation of ERK1 and ERK2 Cascade (GO:0070372): Calculation started
Regulation of ERK1 and ERK2 Cascade (GO:0070372): scoring computed

Calculating pathways:  83%|████████▎ | 658/796 [54:06<11:40,  5.08s/it]

Regulation of ERK1 and ERK2 Cascade (GO:0070372): pvalue calculation completed
Regulation of ERK1 and ERK2 Cascade (GO:0070372): Calculation completed
Regulation of MAP Kinase Activity (GO:0043405): Calculation started
Regulation of MAP Kinase Activity (GO:0043405): scoring computed

Calculating pathways:  83%|████████▎ | 659/796 [54:10<10:58,  4.80s/it]

Regulation of MAP Kinase Activity (GO:0043405): pvalue calculation completed
Regulation of MAP Kinase Activity (GO:0043405): Calculation completed
Regulation of MAPK Cascade (GO:0043408): Calculation started
Regulation of MAPK Cascade (GO:0043408): scoring computed

Calculating pathways:  83%|████████▎ | 660/796 [54:16<11:59,  5.29s/it]

Regulation of MAPK Cascade (GO:0043408): pvalue calculation completed
Regulation of MAPK Cascade (GO:0043408): Calculation completed
Regulation of Rho Protein Signal Transduction (GO:0035023): Calculation started
Regulation of Rho Protein Signal Transduction (GO:0035023): scoring computed

Calculating pathways:  83%|████████▎ | 661/796 [54:21<11:20,  5.04s/it]

Regulation of Rho Protein Signal Transduction (GO:0035023): pvalue calculation completed
Regulation of Rho Protein Signal Transduction (GO:0035023): Calculation completed
Regulation of T Cell Activation (GO:0050863): Calculation started
Regulation of T Cell Activation (GO:0050863): scoring computed

Calculating pathways:  83%|████████▎ | 662/796 [54:25<10:38,  4.76s/it]

Regulation of T Cell Activation (GO:0050863): pvalue calculation completed
Regulation of T Cell Activation (GO:0050863): Calculation completed
Regulation of T Cell Receptor Signaling Pathway (GO:0050856): Calculation started
Regulation of T Cell Receptor Signaling Pathway (GO:0050856): scoring computed

Calculating pathways:  83%|████████▎ | 663/796 [54:29<10:03,  4.54s/it]

Regulation of T Cell Receptor Signaling Pathway (GO:0050856): pvalue calculation completed
Regulation of T Cell Receptor Signaling Pathway (GO:0050856): Calculation completed
Regulation of Wnt Signaling Pathway (GO:0030111): Calculation started
Regulation of Wnt Signaling Pathway (GO:0030111): scoring computed

Calculating pathways:  83%|████████▎ | 664/796 [54:34<10:13,  4.65s/it]

Regulation of Wnt Signaling Pathway (GO:0030111): pvalue calculation completed
Regulation of Wnt Signaling Pathway (GO:0030111): Calculation completed
Regulation of Actin Cytoskeleton Organization (GO:0032956): Calculation started
Regulation of Actin Cytoskeleton Organization (GO:0032956): scoring computed

Calculating pathways:  84%|████████▎ | 665/796 [54:39<10:09,  4.65s/it]

Regulation of Actin Cytoskeleton Organization (GO:0032956): pvalue calculation completed
Regulation of Actin Cytoskeleton Organization (GO:0032956): Calculation completed
Regulation of Actin Filament Bundle Assembly (GO:0032231): Calculation started
Regulation of Actin Filament Bundle Assembly (GO:0032231): scoring computed

Calculating pathways:  84%|████████▎ | 666/796 [54:42<09:31,  4.39s/it]

Regulation of Actin Filament Bundle Assembly (GO:0032231): pvalue calculation completed
Regulation of Actin Filament Bundle Assembly (GO:0032231): Calculation completed
Regulation of Actin Filament Polymerization (GO:0030833): Calculation started
Regulation of Actin Filament Polymerization (GO:0030833): scoring computed

Calculating pathways:  84%|████████▍ | 667/796 [54:46<09:16,  4.31s/it]

Regulation of Actin Filament Polymerization (GO:0030833): pvalue calculation completed
Regulation of Actin Filament Polymerization (GO:0030833): Calculation completed
Regulation of Actin Filament-Based Process (GO:0032970): Calculation started
Regulation of Actin Filament-Based Process (GO:0032970): scoring computed

Calculating pathways:  84%|████████▍ | 668/796 [54:51<09:26,  4.42s/it]

Regulation of Actin Filament-Based Process (GO:0032970): pvalue calculation completed
Regulation of Actin Filament-Based Process (GO:0032970): Calculation completed
Regulation of Actomyosin Structure Organization (GO:0110020): Calculation started
Regulation of Actomyosin Structure Organization (GO:0110020): scoring computed

Calculating pathways:  84%|████████▍ | 669/796 [54:55<08:47,  4.16s/it]

Regulation of Actomyosin Structure Organization (GO:0110020): pvalue calculation completed
Regulation of Actomyosin Structure Organization (GO:0110020): Calculation completed
Regulation of Adaptive Immune Response (GO:0002819): Calculation started
Regulation of Adaptive Immune Response (GO:0002819): scoring computed

Calculating pathways:  84%|████████▍ | 670/796 [54:58<08:22,  3.99s/it]

Regulation of Adaptive Immune Response (GO:0002819): pvalue calculation completed
Regulation of Adaptive Immune Response (GO:0002819): Calculation completed
Regulation of Anatomical Structure Morphogenesis (GO:0022603): Calculation started
Regulation of Anatomical Structure Morphogenesis (GO:0022603): scoring computed

Calculating pathways:  84%|████████▍ | 671/796 [55:03<09:02,  4.34s/it]

Regulation of Anatomical Structure Morphogenesis (GO:0022603): pvalue calculation completed
Regulation of Anatomical Structure Morphogenesis (GO:0022603): Calculation completed
Regulation of Angiogenesis (GO:0045765): Calculation started
Regulation of Angiogenesis (GO:0045765): scoring computed

Calculating pathways:  84%|████████▍ | 672/796 [55:09<10:00,  4.84s/it]

Regulation of Angiogenesis (GO:0045765): pvalue calculation completed
Regulation of Angiogenesis (GO:0045765): Calculation completed
Regulation of Apoptotic Process (GO:0042981): Calculation started
Regulation of Apoptotic Process (GO:0042981): scoring computed

Calculating pathways:  85%|████████▍ | 673/796 [55:20<13:41,  6.68s/it]

Regulation of Apoptotic Process (GO:0042981): pvalue calculation completed
Regulation of Apoptotic Process (GO:0042981): Calculation completed
Regulation of Bicellular Tight Junction Assembly (GO:2000810): Calculation started
Regulation of Bicellular Tight Junction Assembly (GO:2000810): scoring computed

Calculating pathways:  85%|████████▍ | 674/796 [55:24<11:55,  5.86s/it]

Regulation of Bicellular Tight Junction Assembly (GO:2000810): pvalue calculation completed
Regulation of Bicellular Tight Junction Assembly (GO:2000810): Calculation completed
Regulation of Biosynthetic Process (GO:0009889): Calculation started
Regulation of Biosynthetic Process (GO:0009889): scoring computed

Calculating pathways:  85%|████████▍ | 675/796 [55:28<10:37,  5.27s/it]

Regulation of Biosynthetic Process (GO:0009889): pvalue calculation completed
Regulation of Biosynthetic Process (GO:0009889): Calculation completed
Regulation of Calcium Ion Import (GO:0090279): Calculation started
Regulation of Calcium Ion Import (GO:0090279): scoring computed

Calculating pathways:  85%|████████▍ | 676/796 [55:32<09:39,  4.83s/it]

Regulation of Calcium Ion Import (GO:0090279): pvalue calculation completed
Regulation of Calcium Ion Import (GO:0090279): Calculation completed
Regulation of Calcium Ion Import Across Plasma Membrane (GO:1905664): Calculation started
Regulation of Calcium Ion Import Across Plasma Membrane (GO:1905664): scoring computed

Calculating pathways:  85%|████████▌ | 677/796 [55:36<08:47,  4.43s/it]

Regulation of Calcium Ion Import Across Plasma Membrane (GO:1905664): pvalue calculation completed
Regulation of Calcium Ion Import Across Plasma Membrane (GO:1905664): Calculation completed
Regulation of Calcium Ion Transmembrane Transport (GO:1903169): Calculation started
Regulation of Calcium Ion Transmembrane Transport (GO:1903169): scoring computed

Calculating pathways:  85%|████████▌ | 678/796 [55:39<08:17,  4.21s/it]

Regulation of Calcium Ion Transmembrane Transport (GO:1903169): pvalue calculation completed
Regulation of Calcium Ion Transmembrane Transport (GO:1903169): Calculation completed
Regulation of Canonical NF-kappaB Signal Transduction (GO:0043122): Calculation started
Regulation of Canonical NF-kappaB Signal Transduction (GO:0043122): scoring computed

Calculating pathways:  85%|████████▌ | 679/796 [55:46<09:38,  4.95s/it]

Regulation of Canonical NF-kappaB Signal Transduction (GO:0043122): pvalue calculation completed
Regulation of Canonical NF-kappaB Signal Transduction (GO:0043122): Calculation completed
Regulation of Cell Adhesion (GO:0030155): Calculation started
Regulation of Cell Adhesion (GO:0030155): scoring computed

Calculating pathways:  85%|████████▌ | 680/796 [55:51<09:41,  5.02s/it]

Regulation of Cell Adhesion (GO:0030155): pvalue calculation completed
Regulation of Cell Adhesion (GO:0030155): Calculation completed
Regulation of Cell Cycle G2/M Phase Transition (GO:1902749): Calculation started
Regulation of Cell Cycle G2/M Phase Transition (GO:1902749): scoring computed

Calculating pathways:  86%|████████▌ | 681/796 [55:55<08:50,  4.62s/it]

Regulation of Cell Cycle G2/M Phase Transition (GO:1902749): pvalue calculation completed
Regulation of Cell Cycle G2/M Phase Transition (GO:1902749): Calculation completed
Regulation of Cell Cycle Process (GO:0010564): Calculation started
Regulation of Cell Cycle Process (GO:0010564): scoring computed

Calculating pathways:  86%|████████▌ | 682/796 [56:00<09:13,  4.85s/it]

Regulation of Cell Cycle Process (GO:0010564): pvalue calculation completed
Regulation of Cell Cycle Process (GO:0010564): Calculation completed
Regulation of Cell Division (GO:0051302): Calculation started
Regulation of Cell Division (GO:0051302): scoring computed

Calculating pathways:  86%|████████▌ | 683/796 [56:05<08:58,  4.77s/it]

Regulation of Cell Division (GO:0051302): pvalue calculation completed
Regulation of Cell Division (GO:0051302): Calculation completed
Regulation of Cell Growth (GO:0001558): Calculation started
Regulation of Cell Growth (GO:0001558): scoring computed

Calculating pathways:  86%|████████▌ | 684/796 [56:11<09:37,  5.16s/it]

Regulation of Cell Growth (GO:0001558): pvalue calculation completed
Regulation of Cell Growth (GO:0001558): Calculation completed
Regulation of Cell Migration (GO:0030334): Calculation started
Regulation of Cell Migration (GO:0030334): scoring computed

Calculating pathways:  86%|████████▌ | 685/796 [56:19<11:24,  6.17s/it]

Regulation of Cell Migration (GO:0030334): pvalue calculation completed
Regulation of Cell Migration (GO:0030334): Calculation completed
Regulation of Cell Motility (GO:2000145): Calculation started
Regulation of Cell Motility (GO:2000145): scoring computed

Calculating pathways:  86%|████████▌ | 686/796 [56:24<10:36,  5.78s/it]

Regulation of Cell Motility (GO:2000145): pvalue calculation completed
Regulation of Cell Motility (GO:2000145): Calculation completed
Regulation of Cell Population Proliferation (GO:0042127): Calculation started
Regulation of Cell Population Proliferation (GO:0042127): scoring computed

Calculating pathways:  86%|████████▋ | 687/796 [56:36<13:32,  7.45s/it]

Regulation of Cell Population Proliferation (GO:0042127): pvalue calculation completed
Regulation of Cell Population Proliferation (GO:0042127): Calculation completed
Regulation of Cell Size (GO:0008361): Calculation started
Regulation of Cell Size (GO:0008361): scoring computed

Calculating pathways:  86%|████████▋ | 688/796 [56:39<11:25,  6.35s/it]

Regulation of Cell Size (GO:0008361): pvalue calculation completed
Regulation of Cell Size (GO:0008361): Calculation completed
Regulation of Cell-Substrate Adhesion (GO:0010810): Calculation started
Regulation of Cell-Substrate Adhesion (GO:0010810): scoring computed

Calculating pathways:  87%|████████▋ | 689/796 [56:44<10:07,  5.68s/it]

Regulation of Cell-Substrate Adhesion (GO:0010810): pvalue calculation completed
Regulation of Cell-Substrate Adhesion (GO:0010810): Calculation completed
Regulation of Cellular Component Organization (GO:0051128): Calculation started
Regulation of Cellular Component Organization (GO:0051128): scoring computed

Calculating pathways:  87%|████████▋ | 690/796 [56:49<09:54,  5.61s/it]

Regulation of Cellular Component Organization (GO:0051128): pvalue calculation completed
Regulation of Cellular Component Organization (GO:0051128): Calculation completed
Regulation of Cellular Component Size (GO:0032535): Calculation started
Regulation of Cellular Component Size (GO:0032535): scoring computed

Calculating pathways:  87%|████████▋ | 691/796 [56:53<08:55,  5.10s/it]

Regulation of Cellular Component Size (GO:0032535): pvalue calculation completed
Regulation of Cellular Component Size (GO:0032535): Calculation completed
Regulation of Cellular Senescence (GO:2000772): Calculation started
Regulation of Cellular Senescence (GO:2000772): scoring computed

Calculating pathways:  87%|████████▋ | 692/796 [56:57<08:09,  4.70s/it]

Regulation of Cellular Senescence (GO:2000772): pvalue calculation completed
Regulation of Cellular Senescence (GO:2000772): Calculation completed
Regulation of Centrosome Cycle (GO:0046605): Calculation started
Regulation of Centrosome Cycle (GO:0046605): scoring computed

Calculating pathways:  87%|████████▋ | 693/796 [57:00<07:32,  4.39s/it]

Regulation of Centrosome Cycle (GO:0046605): pvalue calculation completed
Regulation of Centrosome Cycle (GO:0046605): Calculation completed
Regulation of Cytokinesis (GO:0032465): Calculation started
Regulation of Cytokinesis (GO:0032465): scoring computed

Calculating pathways:  87%|████████▋ | 694/796 [57:05<07:27,  4.39s/it]

Regulation of Cytokinesis (GO:0032465): pvalue calculation completed
Regulation of Cytokinesis (GO:0032465): Calculation completed
Regulation of Cytoskeleton Organization (GO:0051493): Calculation started
Regulation of Cytoskeleton Organization (GO:0051493): scoring computed

Calculating pathways:  87%|████████▋ | 695/796 [57:10<07:51,  4.67s/it]

Regulation of Cytoskeleton Organization (GO:0051493): pvalue calculation completed
Regulation of Cytoskeleton Organization (GO:0051493): Calculation completed
Regulation of Defense Response (GO:0031347): Calculation started
Regulation of Defense Response (GO:0031347): scoring computed

Calculating pathways:  87%|████████▋ | 696/796 [57:15<07:49,  4.70s/it]

Regulation of Defense Response (GO:0031347): pvalue calculation completed
Regulation of Defense Response (GO:0031347): Calculation completed
Regulation of Dendritic Spine Maintenance (GO:1902950): Calculation started
Regulation of Dendritic Spine Maintenance (GO:1902950): scoring computed

Calculating pathways:  88%|████████▊ | 697/796 [57:18<07:09,  4.34s/it]

Regulation of Dendritic Spine Maintenance (GO:1902950): pvalue calculation completed
Regulation of Dendritic Spine Maintenance (GO:1902950): Calculation completed
Regulation of Endothelial Cell Migration (GO:0010594): Calculation started
Regulation of Endothelial Cell Migration (GO:0010594): scoring computed

Calculating pathways:  88%|████████▊ | 698/796 [57:23<07:09,  4.38s/it]

Regulation of Endothelial Cell Migration (GO:0010594): pvalue calculation completed
Regulation of Endothelial Cell Migration (GO:0010594): Calculation completed
Regulation of Epithelial Cell Proliferation (GO:0050678): Calculation started
Regulation of Epithelial Cell Proliferation (GO:0050678): scoring computed

Calculating pathways:  88%|████████▊ | 699/796 [57:27<07:09,  4.43s/it]

Regulation of Epithelial Cell Proliferation (GO:0050678): pvalue calculation completed
Regulation of Epithelial Cell Proliferation (GO:0050678): Calculation completed
Regulation of Extrinsic Apoptotic Signaling Pathway in Absence of Ligand (GO:2001239): Calculation started
Regulation of Extrinsic Apoptotic Signaling Pathway in Absence of Ligand (GO:2001239): scoring computed

Calculating pathways:  88%|████████▊ | 700/796 [57:31<06:53,  4.31s/it]

Regulation of Extrinsic Apoptotic Signaling Pathway in Absence of Ligand (GO:2001239): pvalue calculation completed
Regulation of Extrinsic Apoptotic Signaling Pathway in Absence of Ligand (GO:2001239): Calculation completed
Regulation of Fibroblast Migration (GO:0010762): Calculation started
Regulation of Fibroblast Migration (GO:0010762): scoring computed

Calculating pathways:  88%|████████▊ | 701/796 [57:35<06:34,  4.16s/it]

Regulation of Fibroblast Migration (GO:0010762): pvalue calculation completed
Regulation of Fibroblast Migration (GO:0010762): Calculation completed
Regulation of Focal Adhesion Assembly (GO:0051893): Calculation started
Regulation of Focal Adhesion Assembly (GO:0051893): scoring computed

Calculating pathways:  88%|████████▊ | 702/796 [57:39<06:28,  4.13s/it]

Regulation of Focal Adhesion Assembly (GO:0051893): pvalue calculation completed
Regulation of Focal Adhesion Assembly (GO:0051893): Calculation completed
Regulation of Gene Expression (GO:0010468): Calculation started
Regulation of Gene Expression (GO:0010468): scoring computed

Calculating pathways:  88%|████████▊ | 703/796 [57:54<11:23,  7.35s/it]

Regulation of Gene Expression (GO:0010468): pvalue calculation completed
Regulation of Gene Expression (GO:0010468): Calculation completed
Regulation of Glutamate Receptor Signaling Pathway (GO:1900449): Calculation started
Regulation of Glutamate Receptor Signaling Pathway (GO:1900449): scoring computed

Calculating pathways:  88%|████████▊ | 704/796 [57:58<09:30,  6.20s/it]

Regulation of Glutamate Receptor Signaling Pathway (GO:1900449): pvalue calculation completed
Regulation of Glutamate Receptor Signaling Pathway (GO:1900449): Calculation completed
Regulation of Hair Cycle (GO:0042634): Calculation started
Regulation of Hair Cycle (GO:0042634): scoring computed

Calculating pathways:  89%|████████▊ | 705/796 [58:01<08:16,  5.46s/it]

Regulation of Hair Cycle (GO:0042634): pvalue calculation completed
Regulation of Hair Cycle (GO:0042634): Calculation completed
Regulation of Heterotypic Cell-Cell Adhesion (GO:0034114): Calculation started
Regulation of Heterotypic Cell-Cell Adhesion (GO:0034114): scoring computed

Calculating pathways:  89%|████████▊ | 706/796 [58:05<07:22,  4.92s/it]

Regulation of Heterotypic Cell-Cell Adhesion (GO:0034114): pvalue calculation completed
Regulation of Heterotypic Cell-Cell Adhesion (GO:0034114): Calculation completed
Regulation of Inflammatory Response (GO:0050727): Calculation started
Regulation of Inflammatory Response (GO:0050727): scoring computed

Calculating pathways:  89%|████████▉ | 707/796 [58:11<07:53,  5.32s/it]

Regulation of Inflammatory Response (GO:0050727): pvalue calculation completed
Regulation of Inflammatory Response (GO:0050727): Calculation completed
Regulation of Inflammatory Response to Antigenic Stimulus (GO:0002861): Calculation started
Regulation of Inflammatory Response to Antigenic Stimulus (GO:0002861): scoring computed

Calculating pathways:  89%|████████▉ | 708/796 [58:15<07:02,  4.80s/it]

Regulation of Inflammatory Response to Antigenic Stimulus (GO:0002861): pvalue calculation completed
Regulation of Inflammatory Response to Antigenic Stimulus (GO:0002861): Calculation completed
Regulation of Interleukin-1 Beta Production (GO:0032651): Calculation started
Regulation of Interleukin-1 Beta Production (GO:0032651): scoring computed

Calculating pathways:  89%|████████▉ | 709/796 [58:19<06:45,  4.66s/it]

Regulation of Interleukin-1 Beta Production (GO:0032651): pvalue calculation completed
Regulation of Interleukin-1 Beta Production (GO:0032651): Calculation completed
Regulation of Interleukin-23 Production (GO:0032667): Calculation started
Regulation of Interleukin-23 Production (GO:0032667): scoring computed

Calculating pathways:  89%|████████▉ | 710/796 [58:23<06:09,  4.30s/it]

Regulation of Interleukin-23 Production (GO:0032667): pvalue calculation completed
Regulation of Interleukin-23 Production (GO:0032667): Calculation completed
Regulation of Intracellular Signal Transduction (GO:1902531): Calculation started
Regulation of Intracellular Signal Transduction (GO:1902531): scoring computed

Calculating pathways:  89%|████████▉ | 711/796 [58:30<07:17,  5.15s/it]

Regulation of Intracellular Signal Transduction (GO:1902531): pvalue calculation completed
Regulation of Intracellular Signal Transduction (GO:1902531): Calculation completed
Regulation of Intrinsic Apoptotic Signaling Pathway (GO:2001242): Calculation started
Regulation of Intrinsic Apoptotic Signaling Pathway (GO:2001242): scoring computed

Calculating pathways:  89%|████████▉ | 712/796 [58:34<06:44,  4.82s/it]

Regulation of Intrinsic Apoptotic Signaling Pathway (GO:2001242): pvalue calculation completed
Regulation of Intrinsic Apoptotic Signaling Pathway (GO:2001242): Calculation completed
Regulation of Lamellipodium Assembly (GO:0010591): Calculation started
Regulation of Lamellipodium Assembly (GO:0010591): scoring computed

Calculating pathways:  90%|████████▉ | 713/796 [58:38<06:15,  4.53s/it]

Regulation of Lamellipodium Assembly (GO:0010591): pvalue calculation completed
Regulation of Lamellipodium Assembly (GO:0010591): Calculation completed
Regulation of Lamellipodium Organization (GO:1902743): Calculation started
Regulation of Lamellipodium Organization (GO:1902743): scoring computed

Calculating pathways:  90%|████████▉ | 714/796 [58:41<05:47,  4.24s/it]

Regulation of Lamellipodium Organization (GO:1902743): pvalue calculation completed
Regulation of Lamellipodium Organization (GO:1902743): Calculation completed
Regulation of Leukocyte Activation (GO:0002694): Calculation started
Regulation of Leukocyte Activation (GO:0002694): scoring computed

Calculating pathways:  90%|████████▉ | 715/796 [58:45<05:25,  4.02s/it]

Regulation of Leukocyte Activation (GO:0002694): pvalue calculation completed
Regulation of Leukocyte Activation (GO:0002694): Calculation completed
Regulation of Leukocyte Cell-Cell Adhesion (GO:1903037): Calculation started
Regulation of Leukocyte Cell-Cell Adhesion (GO:1903037): scoring computed

Calculating pathways:  90%|████████▉ | 716/796 [58:48<05:09,  3.87s/it]

Regulation of Leukocyte Cell-Cell Adhesion (GO:1903037): pvalue calculation completed
Regulation of Leukocyte Cell-Cell Adhesion (GO:1903037): Calculation completed
Regulation of Leukocyte Migration (GO:0002685): Calculation started
Regulation of Leukocyte Migration (GO:0002685): scoring computed

Calculating pathways:  90%|█████████ | 717/796 [58:52<04:57,  3.77s/it]

Regulation of Leukocyte Migration (GO:0002685): pvalue calculation completed
Regulation of Leukocyte Migration (GO:0002685): Calculation completed
Regulation of Lymphocyte Activation (GO:0051249): Calculation started
Regulation of Lymphocyte Activation (GO:0051249): scoring computed

Calculating pathways:  90%|█████████ | 718/796 [58:55<04:50,  3.72s/it]

Regulation of Lymphocyte Activation (GO:0051249): pvalue calculation completed
Regulation of Lymphocyte Activation (GO:0051249): Calculation completed
Regulation of Metabolic Process (GO:0019222): Calculation started
Regulation of Metabolic Process (GO:0019222): scoring computed

Calculating pathways:  90%|█████████ | 719/796 [58:59<04:52,  3.80s/it]

Regulation of Metabolic Process (GO:0019222): pvalue calculation completed
Regulation of Metabolic Process (GO:0019222): Calculation completed
Regulation of miRNA Transcription (GO:1902893): Calculation started
Regulation of miRNA Transcription (GO:1902893): scoring computed

Calculating pathways:  90%|█████████ | 720/796 [59:04<04:58,  3.93s/it]

Regulation of miRNA Transcription (GO:1902893): pvalue calculation completed
Regulation of miRNA Transcription (GO:1902893): Calculation completed
Regulation of Microtubule Polymerization (GO:0031113): Calculation started
Regulation of Microtubule Polymerization (GO:0031113): scoring computed

Calculating pathways:  91%|█████████ | 721/796 [59:08<04:54,  3.93s/it]

Regulation of Microtubule Polymerization (GO:0031113): pvalue calculation completed
Regulation of Microtubule Polymerization (GO:0031113): Calculation completed
Regulation of Microtubule-Based Process (GO:0032886): Calculation started
Regulation of Microtubule-Based Process (GO:0032886): scoring computed

Calculating pathways:  91%|█████████ | 722/796 [59:11<04:51,  3.93s/it]

Regulation of Microtubule-Based Process (GO:0032886): pvalue calculation completed
Regulation of Microtubule-Based Process (GO:0032886): Calculation completed
Regulation of Mitotic Cell Cycle (GO:0007346): Calculation started
Regulation of Mitotic Cell Cycle (GO:0007346): scoring computed

Calculating pathways:  91%|█████████ | 723/796 [59:17<05:12,  4.28s/it]

Regulation of Mitotic Cell Cycle (GO:0007346): pvalue calculation completed
Regulation of Mitotic Cell Cycle (GO:0007346): Calculation completed
Regulation of Mitotic Cell Cycle Phase Transition (GO:1901990): Calculation started
Regulation of Mitotic Cell Cycle Phase Transition (GO:1901990): scoring computed

Calculating pathways:  91%|█████████ | 724/796 [59:21<05:14,  4.36s/it]

Regulation of Mitotic Cell Cycle Phase Transition (GO:1901990): pvalue calculation completed
Regulation of Mitotic Cell Cycle Phase Transition (GO:1901990): Calculation completed
Regulation of Mitotic Nuclear Division (GO:0007088): Calculation started
Regulation of Mitotic Nuclear Division (GO:0007088): scoring computed

Calculating pathways:  91%|█████████ | 725/796 [59:25<05:03,  4.28s/it]

Regulation of Mitotic Nuclear Division (GO:0007088): pvalue calculation completed
Regulation of Mitotic Nuclear Division (GO:0007088): Calculation completed
Regulation of Monoatomic Ion Transport (GO:0043269): Calculation started
Regulation of Monoatomic Ion Transport (GO:0043269): scoring computed

Calculating pathways:  91%|█████████ | 726/796 [59:29<04:49,  4.13s/it]

Regulation of Monoatomic Ion Transport (GO:0043269): pvalue calculation completed
Regulation of Monoatomic Ion Transport (GO:0043269): Calculation completed
Regulation of Neutrophil Chemotaxis (GO:0090022): Calculation started
Regulation of Neutrophil Chemotaxis (GO:0090022): scoring computed

Calculating pathways:  91%|█████████▏| 727/796 [59:33<04:35,  3.99s/it]

Regulation of Neutrophil Chemotaxis (GO:0090022): pvalue calculation completed
Regulation of Neutrophil Chemotaxis (GO:0090022): Calculation completed
Regulation of Neutrophil Migration (GO:1902622): Calculation started
Regulation of Neutrophil Migration (GO:1902622): scoring computed

Calculating pathways:  91%|█████████▏| 728/796 [59:36<04:21,  3.84s/it]

Regulation of Neutrophil Migration (GO:1902622): pvalue calculation completed
Regulation of Neutrophil Migration (GO:1902622): Calculation completed
Regulation of Nitric Oxide Biosynthetic Process (GO:0045428): Calculation started
Regulation of Nitric Oxide Biosynthetic Process (GO:0045428): scoring computed

Calculating pathways:  92%|█████████▏| 729/796 [59:40<04:22,  3.92s/it]

Regulation of Nitric Oxide Biosynthetic Process (GO:0045428): pvalue calculation completed
Regulation of Nitric Oxide Biosynthetic Process (GO:0045428): Calculation completed
Regulation of Nitric Oxide Metabolic Process (GO:0080164): Calculation started
Regulation of Nitric Oxide Metabolic Process (GO:0080164): scoring computed

Calculating pathways:  92%|█████████▏| 730/796 [59:44<04:10,  3.80s/it]

Regulation of Nitric Oxide Metabolic Process (GO:0080164): pvalue calculation completed
Regulation of Nitric Oxide Metabolic Process (GO:0080164): Calculation completed
Regulation of Nitric-Oxide Synthase Activity (GO:0050999): Calculation started
Regulation of Nitric-Oxide Synthase Activity (GO:0050999): scoring computed

Calculating pathways:  92%|█████████▏| 731/796 [59:47<04:04,  3.76s/it]

Regulation of Nitric-Oxide Synthase Activity (GO:0050999): pvalue calculation completed
Regulation of Nitric-Oxide Synthase Activity (GO:0050999): Calculation completed
Regulation of Oxidative Stress-Induced Intrinsic Apoptotic Signaling Pathway (GO:1902175): Calculation started
Regulation of Oxidative Stress-Induced Intrinsic Apoptotic Signaling Pathway (GO:1902175): scoring computed

Calculating pathways:  92%|█████████▏| 732/796 [59:51<03:57,  3.70s/it]

Regulation of Oxidative Stress-Induced Intrinsic Apoptotic Signaling Pathway (GO:1902175): pvalue calculation completed
Regulation of Oxidative Stress-Induced Intrinsic Apoptotic Signaling Pathway (GO:1902175): Calculation completed
Regulation of Plasma Membrane Bounded Cell Projection Assembly (GO:0120032): Calculation started
Regulation of Plasma Membrane Bounded Cell Projection Assembly (GO:0120032): scoring computed

Calculating pathways:  92%|█████████▏| 733/796 [59:55<04:04,  3.88s/it]

Regulation of Plasma Membrane Bounded Cell Projection Assembly (GO:0120032): pvalue calculation completed
Regulation of Plasma Membrane Bounded Cell Projection Assembly (GO:0120032): Calculation completed
Regulation of Protein Binding (GO:0043393): Calculation started
Regulation of Protein Binding (GO:0043393): scoring computed

Calculating pathways:  92%|█████████▏| 734/796 [1:00:00<04:08,  4.02s/it]

Regulation of Protein Binding (GO:0043393): pvalue calculation completed
Regulation of Protein Binding (GO:0043393): Calculation completed
Regulation of Protein Localization to Membrane (GO:1905475): Calculation started
Regulation of Protein Localization to Membrane (GO:1905475): scoring computed

Calculating pathways:  92%|█████████▏| 735/796 [1:00:04<04:02,  3.98s/it]

Regulation of Protein Localization to Membrane (GO:1905475): pvalue calculation completed
Regulation of Protein Localization to Membrane (GO:1905475): Calculation completed
Regulation of Protein Localization to Nucleolus (GO:1904749): Calculation started
Regulation of Protein Localization to Nucleolus (GO:1904749): scoring computed

Calculating pathways:  92%|█████████▏| 736/796 [1:00:07<03:50,  3.85s/it]

Regulation of Protein Localization to Nucleolus (GO:1904749): pvalue calculation completed
Regulation of Protein Localization to Nucleolus (GO:1904749): Calculation completed
Regulation of Protein Phosphorylation (GO:0001932): Calculation started
Regulation of Protein Phosphorylation (GO:0001932): scoring computed

Calculating pathways:  93%|█████████▎| 737/796 [1:00:12<04:13,  4.29s/it]

Regulation of Protein Phosphorylation (GO:0001932): pvalue calculation completed
Regulation of Protein Phosphorylation (GO:0001932): Calculation completed
Regulation of Protein Targeting to Membrane (GO:0090313): Calculation started
Regulation of Protein Targeting to Membrane (GO:0090313): scoring computed

Calculating pathways:  93%|█████████▎| 738/796 [1:00:16<03:57,  4.09s/it]

Regulation of Protein Targeting to Membrane (GO:0090313): pvalue calculation completed
Regulation of Protein Targeting to Membrane (GO:0090313): Calculation completed
Regulation of Reactive Oxygen Species Metabolic Process (GO:2000377): Calculation started
Regulation of Reactive Oxygen Species Metabolic Process (GO:2000377): scoring computed

Calculating pathways:  93%|█████████▎| 739/796 [1:00:20<03:55,  4.14s/it]

Regulation of Reactive Oxygen Species Metabolic Process (GO:2000377): pvalue calculation completed
Regulation of Reactive Oxygen Species Metabolic Process (GO:2000377): Calculation completed
Regulation of Receptor-Mediated Endocytosis (GO:0048259): Calculation started
Regulation of Receptor-Mediated Endocytosis (GO:0048259): scoring computed

Calculating pathways:  93%|█████████▎| 740/796 [1:00:24<03:49,  4.09s/it]

Regulation of Receptor-Mediated Endocytosis (GO:0048259): pvalue calculation completed
Regulation of Receptor-Mediated Endocytosis (GO:0048259): Calculation completed
Regulation of Respiratory Burst (GO:0060263): Calculation started
Regulation of Respiratory Burst (GO:0060263): scoring computed

Calculating pathways:  93%|█████████▎| 741/796 [1:00:28<03:38,  3.97s/it]

Regulation of Respiratory Burst (GO:0060263): pvalue calculation completed
Regulation of Respiratory Burst (GO:0060263): Calculation completed
Regulation of Response to External Stimulus (GO:0032101): Calculation started
Regulation of Response to External Stimulus (GO:0032101): scoring computed

Calculating pathways:  93%|█████████▎| 742/796 [1:00:33<03:52,  4.30s/it]

Regulation of Response to External Stimulus (GO:0032101): pvalue calculation completed
Regulation of Response to External Stimulus (GO:0032101): Calculation completed
Regulation of Signal Transduction (GO:0009966): Calculation started
Regulation of Signal Transduction (GO:0009966): scoring computed

Calculating pathways:  93%|█████████▎| 743/796 [1:00:39<04:15,  4.81s/it]

Regulation of Signal Transduction (GO:0009966): pvalue calculation completed
Regulation of Signal Transduction (GO:0009966): Calculation completed
Regulation of Signal Transduction by P53 Class Mediator (GO:1901796): Calculation started
Regulation of Signal Transduction by P53 Class Mediator (GO:1901796): scoring computed

Calculating pathways:  93%|█████████▎| 744/796 [1:00:43<03:58,  4.59s/it]

Regulation of Signal Transduction by P53 Class Mediator (GO:1901796): pvalue calculation completed
Regulation of Signal Transduction by P53 Class Mediator (GO:1901796): Calculation completed
Reg of Single Stranded Viral RNA Replication via Double Stranded DNA Intermediate (GO:0045091): Calculation started
Reg of Single Stranded Viral RNA Replication via Double Stranded DNA Intermediate (GO:0045091): scoring computed

Calculating pathways:  94%|█████████▎| 745/796 [1:00:47<03:37,  4.26s/it]

Reg of Single Stranded Viral RNA Replication via Double Stranded DNA Intermediate (GO:0045091): pvalue calculation completed
Reg of Single Stranded Viral RNA Replication via Double Stranded DNA Intermediate (GO:0045091): Calculation completed
Regulation of Stem Cell Proliferation (GO:0072091): Calculation started
Regulation of Stem Cell Proliferation (GO:0072091): scoring computed

Calculating pathways:  94%|█████████▎| 746/796 [1:00:50<03:26,  4.12s/it]

Regulation of Stem Cell Proliferation (GO:0072091): pvalue calculation completed
Regulation of Stem Cell Proliferation (GO:0072091): Calculation completed
Regulation of Stress Fiber Assembly (GO:0051492): Calculation started
Regulation of Stress Fiber Assembly (GO:0051492): scoring computed

Calculating pathways:  94%|█████████▍| 747/796 [1:00:55<03:25,  4.20s/it]

Regulation of Stress Fiber Assembly (GO:0051492): pvalue calculation completed
Regulation of Stress Fiber Assembly (GO:0051492): Calculation completed
Regulation of Substrate Adhesion-Dependent Cell Spreading (GO:1900024): Calculation started
Regulation of Substrate Adhesion-Dependent Cell Spreading (GO:1900024): scoring computed

Calculating pathways:  94%|█████████▍| 748/796 [1:00:59<03:19,  4.15s/it]

Regulation of Substrate Adhesion-Dependent Cell Spreading (GO:1900024): pvalue calculation completed
Regulation of Substrate Adhesion-Dependent Cell Spreading (GO:1900024): Calculation completed
Regulation of Transcription by RNA Polymerase I (GO:0006356): Calculation started
Regulation of Transcription by RNA Polymerase I (GO:0006356): scoring computed

Calculating pathways:  94%|█████████▍| 749/796 [1:01:03<03:13,  4.12s/it]

Regulation of Transcription by RNA Polymerase I (GO:0006356): pvalue calculation completed
Regulation of Transcription by RNA Polymerase I (GO:0006356): Calculation completed
Regulation of Translation (GO:0006417): Calculation started
Regulation of Translation (GO:0006417): scoring computed

Calculating pathways:  94%|█████████▍| 750/796 [1:01:09<03:35,  4.68s/it]

Regulation of Translation (GO:0006417): pvalue calculation completed
Regulation of Translation (GO:0006417): Calculation completed
Regulation of Tumor Necrosis Factor-Mediated Signaling Pathway (GO:0010803): Calculation started
Regulation of Tumor Necrosis Factor-Mediated Signaling Pathway (GO:0010803): scoring computed

Calculating pathways:  94%|█████████▍| 751/796 [1:01:13<03:19,  4.44s/it]

Regulation of Tumor Necrosis Factor-Mediated Signaling Pathway (GO:0010803): pvalue calculation completed
Regulation of Tumor Necrosis Factor-Mediated Signaling Pathway (GO:0010803): Calculation completed
Regulation of Vascular Associated Smooth Muscle Cell Proliferation (GO:1904705): Calculation started
Regulation of Vascular Associated Smooth Muscle Cell Proliferation (GO:1904705): scoring computed

Calculating pathways:  94%|█████████▍| 752/796 [1:01:17<03:08,  4.29s/it]

Regulation of Vascular Associated Smooth Muscle Cell Proliferation (GO:1904705): pvalue calculation completed
Regulation of Vascular Associated Smooth Muscle Cell Proliferation (GO:1904705): Calculation completed
Regulation of Vasculature Development (GO:1901342): Calculation started
Regulation of Vasculature Development (GO:1901342): scoring computed

Calculating pathways:  95%|█████████▍| 753/796 [1:01:20<02:58,  4.14s/it]

Regulation of Vasculature Development (GO:1901342): pvalue calculation completed
Regulation of Vasculature Development (GO:1901342): Calculation completed
Regulatory ncRNA Processing (GO:0070918): Calculation started
Regulatory ncRNA Processing (GO:0070918): scoring computed

Calculating pathways:  95%|█████████▍| 754/796 [1:01:24<02:50,  4.06s/it]

Regulatory ncRNA Processing (GO:0070918): pvalue calculation completed
Regulatory ncRNA Processing (GO:0070918): Calculation completed
Release of Sequestered Calcium Ion Into Cytosol (GO:0051209): Calculation started
Release of Sequestered Calcium Ion Into Cytosol (GO:0051209): scoring computed

Calculating pathways:  95%|█████████▍| 755/796 [1:01:28<02:45,  4.03s/it]

Release of Sequestered Calcium Ion Into Cytosol (GO:0051209): pvalue calculation completed
Release of Sequestered Calcium Ion Into Cytosol (GO:0051209): Calculation completed
Resolution of Meiotic Recombination Intermediates (GO:0000712): Calculation started
Resolution of Meiotic Recombination Intermediates (GO:0000712): scoring computed

Calculating pathways:  95%|█████████▍| 756/796 [1:01:32<02:35,  3.89s/it]

Resolution of Meiotic Recombination Intermediates (GO:0000712): pvalue calculation completed
Resolution of Meiotic Recombination Intermediates (GO:0000712): Calculation completed
Response to UV-A (GO:0070141): Calculation started
Response to UV-A (GO:0070141): scoring computed

Calculating pathways:  95%|█████████▌| 757/796 [1:01:36<02:29,  3.84s/it]

Response to UV-A (GO:0070141): pvalue calculation completed
Response to UV-A (GO:0070141): Calculation completed
Response to Alkaloid (GO:0043279): Calculation started
Response to Alkaloid (GO:0043279): scoring computed

Calculating pathways:  95%|█████████▌| 758/796 [1:01:39<02:21,  3.71s/it]

Response to Alkaloid (GO:0043279): pvalue calculation completed
Response to Alkaloid (GO:0043279): Calculation completed
Response to Amyloid-Beta (GO:1904645): Calculation started
Response to Amyloid-Beta (GO:1904645): scoring computed

Calculating pathways:  95%|█████████▌| 759/796 [1:01:43<02:20,  3.79s/it]

Response to Amyloid-Beta (GO:1904645): pvalue calculation completed
Response to Amyloid-Beta (GO:1904645): Calculation completed
Response to Calcium Ion (GO:0051592): Calculation started
Response to Calcium Ion (GO:0051592): scoring computed

Calculating pathways:  95%|█████████▌| 760/796 [1:01:47<02:22,  3.95s/it]

Response to Calcium Ion (GO:0051592): pvalue calculation completed
Response to Calcium Ion (GO:0051592): Calculation completed
Response to Endoplasmic Reticulum Stress (GO:0034976): Calculation started
Response to Endoplasmic Reticulum Stress (GO:0034976): scoring computed

Calculating pathways:  96%|█████████▌| 761/796 [1:01:53<02:38,  4.53s/it]

Response to Endoplasmic Reticulum Stress (GO:0034976): pvalue calculation completed
Response to Endoplasmic Reticulum Stress (GO:0034976): Calculation completed
Response to Epidermal Growth Factor (GO:0070849): Calculation started
Response to Epidermal Growth Factor (GO:0070849): scoring computed

Calculating pathways:  96%|█████████▌| 762/796 [1:01:57<02:28,  4.38s/it]

Response to Epidermal Growth Factor (GO:0070849): pvalue calculation completed
Response to Epidermal Growth Factor (GO:0070849): Calculation completed
Response to Hydrogen Peroxide (GO:0042542): Calculation started
Response to Hydrogen Peroxide (GO:0042542): scoring computed

Calculating pathways:  96%|█████████▌| 763/796 [1:02:01<02:19,  4.22s/it]

Response to Hydrogen Peroxide (GO:0042542): pvalue calculation completed
Response to Hydrogen Peroxide (GO:0042542): Calculation completed
Response to Lipopolysaccharide (GO:0032496): Calculation started
Response to Lipopolysaccharide (GO:0032496): scoring computed

Calculating pathways:  96%|█████████▌| 764/796 [1:02:06<02:25,  4.56s/it]

Response to Lipopolysaccharide (GO:0032496): pvalue calculation completed
Response to Lipopolysaccharide (GO:0032496): Calculation completed
Response to Reactive Oxygen Species (GO:0000302): Calculation started
Response to Reactive Oxygen Species (GO:0000302): scoring computed

Calculating pathways:  96%|█████████▌| 765/796 [1:02:11<02:18,  4.47s/it]

Response to Reactive Oxygen Species (GO:0000302): pvalue calculation completed
Response to Reactive Oxygen Species (GO:0000302): Calculation completed
Response to Type II Interferon (GO:0034341): Calculation started
Response to Type II Interferon (GO:0034341): scoring computed

Calculating pathways:  96%|█████████▌| 766/796 [1:02:15<02:10,  4.36s/it]

Response to Type II Interferon (GO:0034341): pvalue calculation completed
Response to Type II Interferon (GO:0034341): Calculation completed
Ruffle Assembly (GO:0097178): Calculation started
Ruffle Assembly (GO:0097178): scoring computed

Calculating pathways:  96%|█████████▋| 767/796 [1:02:18<01:58,  4.08s/it]

Ruffle Assembly (GO:0097178): pvalue calculation completed
Ruffle Assembly (GO:0097178): Calculation completed
Ruffle Organization (GO:0031529): Calculation started
Ruffle Organization (GO:0031529): scoring computed

Calculating pathways:  96%|█████████▋| 768/796 [1:02:22<01:49,  3.93s/it]

Ruffle Organization (GO:0031529): pvalue calculation completed
Ruffle Organization (GO:0031529): Calculation completed
Semaphorin-Plexin Signaling Pathway (GO:0071526): Calculation started
Semaphorin-Plexin Signaling Pathway (GO:0071526): scoring computed

Calculating pathways:  97%|█████████▋| 769/796 [1:02:26<01:45,  3.93s/it]

Semaphorin-Plexin Signaling Pathway (GO:0071526): pvalue calculation completed
Semaphorin-Plexin Signaling Pathway (GO:0071526): Calculation completed
siRNA Processing (GO:0030422): Calculation started
siRNA Processing (GO:0030422): scoring computed

Calculating pathways:  97%|█████████▋| 770/796 [1:02:29<01:38,  3.80s/it]

siRNA Processing (GO:0030422): pvalue calculation completed
siRNA Processing (GO:0030422): Calculation completed
Signaling Receptor Ligand Precursor Processing (GO:0140448): Calculation started
Signaling Receptor Ligand Precursor Processing (GO:0140448): scoring computed

Calculating pathways:  97%|█████████▋| 771/796 [1:02:33<01:35,  3.82s/it]

Signaling Receptor Ligand Precursor Processing (GO:0140448): pvalue calculation completed
Signaling Receptor Ligand Precursor Processing (GO:0140448): Calculation completed
Sister Chromatid Segregation (GO:0000819): Calculation started
Sister Chromatid Segregation (GO:0000819): scoring computed

Calculating pathways:  97%|█████████▋| 772/796 [1:02:37<01:32,  3.84s/it]

Sister Chromatid Segregation (GO:0000819): pvalue calculation completed
Sister Chromatid Segregation (GO:0000819): Calculation completed
Small GTPase-mediated Signal Transduction (GO:0007264): Calculation started
Small GTPase-mediated Signal Transduction (GO:0007264): scoring computed

Calculating pathways:  97%|█████████▋| 773/796 [1:02:43<01:43,  4.52s/it]

Small GTPase-mediated Signal Transduction (GO:0007264): pvalue calculation completed
Small GTPase-mediated Signal Transduction (GO:0007264): Calculation completed
Sphingolipid Biosynthetic Process (GO:0030148): Calculation started
Sphingolipid Biosynthetic Process (GO:0030148): scoring computed

Calculating pathways:  97%|█████████▋| 774/796 [1:02:47<01:38,  4.48s/it]

Sphingolipid Biosynthetic Process (GO:0030148): pvalue calculation completed
Sphingolipid Biosynthetic Process (GO:0030148): Calculation completed
Sphingolipid Metabolic Process (GO:0006665): Calculation started
Sphingolipid Metabolic Process (GO:0006665): scoring computed

Calculating pathways:  97%|█████████▋| 775/796 [1:02:52<01:32,  4.42s/it]

Sphingolipid Metabolic Process (GO:0006665): pvalue calculation completed
Sphingolipid Metabolic Process (GO:0006665): Calculation completed
Sphingosine-1-Phosphate Receptor Signaling Pathway (GO:0003376): Calculation started
Sphingosine-1-Phosphate Receptor Signaling Pathway (GO:0003376): scoring computed

Calculating pathways:  97%|█████████▋| 776/796 [1:02:55<01:22,  4.13s/it]

Sphingosine-1-Phosphate Receptor Signaling Pathway (GO:0003376): pvalue calculation completed
Sphingosine-1-Phosphate Receptor Signaling Pathway (GO:0003376): Calculation completed
Stimulatory C-type Lectin Receptor Signaling Pathway (GO:0002223): Calculation started
Stimulatory C-type Lectin Receptor Signaling Pathway (GO:0002223): scoring computed

Calculating pathways:  98%|█████████▊| 777/796 [1:02:59<01:15,  3.98s/it]

Stimulatory C-type Lectin Receptor Signaling Pathway (GO:0002223): pvalue calculation completed
Stimulatory C-type Lectin Receptor Signaling Pathway (GO:0002223): Calculation completed
Substrate Adhesion-Dependent Cell Spreading (GO:0034446): Calculation started
Substrate Adhesion-Dependent Cell Spreading (GO:0034446): scoring computed

Calculating pathways:  98%|█████████▊| 778/796 [1:03:03<01:11,  3.96s/it]

Substrate Adhesion-Dependent Cell Spreading (GO:0034446): pvalue calculation completed
Substrate Adhesion-Dependent Cell Spreading (GO:0034446): Calculation completed
Superoxide Anion Generation (GO:0042554): Calculation started
Superoxide Anion Generation (GO:0042554): scoring computed

Calculating pathways:  98%|█████████▊| 779/796 [1:03:06<01:05,  3.85s/it]

Superoxide Anion Generation (GO:0042554): pvalue calculation completed
Superoxide Anion Generation (GO:0042554): Calculation completed
Superoxide Metabolic Process (GO:0006801): Calculation started
Superoxide Metabolic Process (GO:0006801): scoring computed

Calculating pathways:  98%|█████████▊| 780/796 [1:03:10<01:01,  3.86s/it]

Superoxide Metabolic Process (GO:0006801): pvalue calculation completed
Superoxide Metabolic Process (GO:0006801): Calculation completed
Supramolecular Fiber Organization (GO:0097435): Calculation started
Supramolecular Fiber Organization (GO:0097435): scoring computed

Calculating pathways:  98%|█████████▊| 781/796 [1:03:17<01:12,  4.84s/it]

Supramolecular Fiber Organization (GO:0097435): pvalue calculation completed
Supramolecular Fiber Organization (GO:0097435): Calculation completed
Telomere Maintenance (GO:0000723): Calculation started
Telomere Maintenance (GO:0000723): scoring computed

Calculating pathways:  98%|█████████▊| 782/796 [1:03:22<01:06,  4.72s/it]

Telomere Maintenance (GO:0000723): pvalue calculation completed
Telomere Maintenance (GO:0000723): Calculation completed
Telomere Maintenance via Recombination (GO:0000722): Calculation started
Telomere Maintenance via Recombination (GO:0000722): scoring computed

Calculating pathways:  98%|█████████▊| 783/796 [1:03:25<00:56,  4.37s/it]

Telomere Maintenance via Recombination (GO:0000722): pvalue calculation completed
Telomere Maintenance via Recombination (GO:0000722): Calculation completed
Telomere Maintenance via Telomerase (GO:0007004): Calculation started
Telomere Maintenance via Telomerase (GO:0007004): scoring computed

Calculating pathways:  98%|█████████▊| 784/796 [1:03:29<00:50,  4.21s/it]

Telomere Maintenance via Telomerase (GO:0007004): pvalue calculation completed
Telomere Maintenance via Telomerase (GO:0007004): Calculation completed
Telomere Maintenance via Telomere Lengthening (GO:0010833): Calculation started
Telomere Maintenance via Telomere Lengthening (GO:0010833): scoring computed

Calculating pathways:  99%|█████████▊| 785/796 [1:03:33<00:45,  4.09s/it]

Telomere Maintenance via Telomere Lengthening (GO:0010833): pvalue calculation completed
Telomere Maintenance via Telomere Lengthening (GO:0010833): Calculation completed
Telomere Organization (GO:0032200): Calculation started
Telomere Organization (GO:0032200): scoring computed

Calculating pathways:  99%|█████████▊| 786/796 [1:03:37<00:41,  4.15s/it]

Telomere Organization (GO:0032200): pvalue calculation completed
Telomere Organization (GO:0032200): Calculation completed
Transepithelial Transport (GO:0070633): Calculation started
Transepithelial Transport (GO:0070633): scoring computed

Calculating pathways:  99%|█████████▉| 787/796 [1:03:41<00:36,  4.02s/it]

Transepithelial Transport (GO:0070633): pvalue calculation completed
Transepithelial Transport (GO:0070633): Calculation completed
Transport Across Blood-Brain Barrier (GO:0150104): Calculation started
Transport Across Blood-Brain Barrier (GO:0150104): scoring computed

Calculating pathways:  99%|█████████▉| 788/796 [1:03:45<00:33,  4.13s/it]

Transport Across Blood-Brain Barrier (GO:0150104): pvalue calculation completed
Transport Across Blood-Brain Barrier (GO:0150104): Calculation completed
Unsaturated Fatty Acid Biosynthetic Process (GO:0006636): Calculation started
Unsaturated Fatty Acid Biosynthetic Process (GO:0006636): scoring computed

Calculating pathways:  99%|█████████▉| 789/796 [1:03:49<00:27,  3.95s/it]

Unsaturated Fatty Acid Biosynthetic Process (GO:0006636): pvalue calculation completed
Unsaturated Fatty Acid Biosynthetic Process (GO:0006636): Calculation completed
Unsaturated Fatty Acid Metabolic Process (GO:0033559): Calculation started
Unsaturated Fatty Acid Metabolic Process (GO:0033559): scoring computed

Calculating pathways:  99%|█████████▉| 790/796 [1:03:53<00:24,  4.03s/it]

Unsaturated Fatty Acid Metabolic Process (GO:0033559): pvalue calculation completed
Unsaturated Fatty Acid Metabolic Process (GO:0033559): Calculation completed
Vascular Endothelial Growth Factor Receptor Signaling Pathway (GO:0048010): Calculation started
Vascular Endothelial Growth Factor Receptor Signaling Pathway (GO:0048010): scoring computed

Calculating pathways:  99%|█████████▉| 791/796 [1:03:57<00:19,  3.94s/it]

Vascular Endothelial Growth Factor Receptor Signaling Pathway (GO:0048010): pvalue calculation completed
Vascular Endothelial Growth Factor Receptor Signaling Pathway (GO:0048010): Calculation completed
Vascular Transport (GO:0010232): Calculation started
Vascular Transport (GO:0010232): scoring computed

Calculating pathways:  99%|█████████▉| 792/796 [1:04:01<00:16,  4.08s/it]

Vascular Transport (GO:0010232): pvalue calculation completed
Vascular Transport (GO:0010232): Calculation completed
Vitamin Transport (GO:0051180): Calculation started
Vitamin Transport (GO:0051180): scoring computed

Calculating pathways: 100%|█████████▉| 793/796 [1:04:05<00:11,  4.00s/it]

Vitamin Transport (GO:0051180): pvalue calculation completed
Vitamin Transport (GO:0051180): Calculation completed
Wound Healing (GO:0042060): Calculation started
Wound Healing (GO:0042060): scoring computed

Calculating pathways: 100%|█████████▉| 794/796 [1:04:09<00:08,  4.06s/it]

Wound Healing (GO:0042060): pvalue calculation completed
Wound Healing (GO:0042060): Calculation completed
Xenobiotic Transport (GO:0042908): Calculation started
Xenobiotic Transport (GO:0042908): scoring computed

Calculating pathways: 100%|█████████▉| 795/796 [1:04:13<00:03,  3.96s/it]

Xenobiotic Transport (GO:0042908): pvalue calculation completed
Xenobiotic Transport (GO:0042908): Calculation completed
Xenobiotic Transport Across Blood-Brain Barrier (GO:1990962): Calculation started
Xenobiotic Transport Across Blood-Brain Barrier (GO:1990962): scoring computed

Calculating pathways: 100%|██████████| 796/796 [1:04:16<00:00,  4.85s/it]

Xenobiotic Transport Across Blood-Brain Barrier (GO:1990962): pvalue calculation completed
Xenobiotic Transport Across Blood-Brain Barrier (GO:1990962): Calculation completed

## Hallmark geneset scoring

In [11]:
import os
from singscore.singscore import *
import pandas as pd
import json
from tqdm import tqdm

## loading the patient uk65 data 
uk65 = pd.read_csv("singscore_new_code/UK65_clean_gene_log_tpm.txt", header='infer', sep='\t')
uk65 = uk65.set_index(keys='GeneName')

#loading drug_data
hallmark  = gp.get_library(organism='Human', name ='MSigDB_Hallmark_2020')
drug_data = hallmark
count = len(drug_data)
print("Number of items:", count)

final_result = {}

for key, value in tqdm(drug_data.items(), desc="Calculating pathways"):
    print(f"{key}: Calculation started")
    up = drug_data[key]
    up_present = [gene for gene in up if gene in uk65.index]

    # Print counts and summary
    # print(f"Total up genes in signature: {len(up)}")
    # print(f"Up genes found in expression data: {len(up_present)}")

    # Optionally, print the missing ones
    missing_up = set(up) - set(uk65.index)

    # print(f"Missing up genes: {len(missing_up)}")
    scored_data = score(up_gene=up, down_gene=False, sample=uk65,
                    norm_method='theoretical', full_data=True)
    #getting the scored data for a pathway
    total_score = scored_data["total_score"].to_list()[0]
    print(f"{key}: scoring computed")
    permd = permutate(uk65, n_up=len(up_present), n_down=False)
    pvals = empiricalpval(permutations=permd, score=scored_data)
    empirical_p_value = pvals["empirical p value"].to_list()[0]
    print(f"{key}: pvalue calculation completed")
    result = {
    f"{key}":{
        "gene_set_info": {
            "geneset_size": len(up),
            "geneset_covered_in_sample": len(up_present)
        },
        "scores": {
            "total_singscore": total_score
        },
        "statistics": {
            "p_value": empirical_p_value,
            "method": "permutation (empirical)",
            "permutations": 10000
        }}}
    print(f"{key}: Calculation completed")
    final_result.update(result)

# Save final combined JSON
with open("singscore_new_code/Hallmark_pathway_msigdb_singscore_results.json", "w", encoding="utf-8") as f:
    json.dump(final_result, f, indent=2, ensure_ascii=False)

Number of items: 50

Calculating pathways:   0%|          | 0/50 [00:00<?, ?it/s]

TNF-alpha Signaling via NF-kB: Calculation started
TNF-alpha Signaling via NF-kB: scoring computed

Calculating pathways:   2%|▏         | 1/50 [00:05<04:32,  5.57s/it]

TNF-alpha Signaling via NF-kB: pvalue calculation completed
TNF-alpha Signaling via NF-kB: Calculation completed
Hypoxia: Calculation started
Hypoxia: scoring computed

Calculating pathways:   4%|▍         | 2/50 [00:11<04:25,  5.53s/it]

Hypoxia: pvalue calculation completed
Hypoxia: Calculation completed
Cholesterol Homeostasis: Calculation started
Cholesterol Homeostasis: scoring computed

Calculating pathways:   6%|▌         | 3/50 [00:15<03:50,  4.91s/it]

Cholesterol Homeostasis: pvalue calculation completed
Cholesterol Homeostasis: Calculation completed
Mitotic Spindle: Calculation started
Mitotic Spindle: scoring computed

Calculating pathways:   8%|▊         | 4/50 [00:20<04:00,  5.22s/it]

Mitotic Spindle: pvalue calculation completed
Mitotic Spindle: Calculation completed
Wnt-beta Catenin Signaling: Calculation started
Wnt-beta Catenin Signaling: scoring computed

Calculating pathways:  10%|█         | 5/50 [00:24<03:32,  4.73s/it]

Wnt-beta Catenin Signaling: pvalue calculation completed
Wnt-beta Catenin Signaling: Calculation completed
TGF-beta Signaling: Calculation started
TGF-beta Signaling: scoring computed

Calculating pathways:  12%|█▏        | 6/50 [00:28<03:16,  4.47s/it]

TGF-beta Signaling: pvalue calculation completed
TGF-beta Signaling: Calculation completed
IL-6/JAK/STAT3 Signaling: Calculation started
IL-6/JAK/STAT3 Signaling: scoring computed

Calculating pathways:  14%|█▍        | 7/50 [00:32<03:08,  4.38s/it]

IL-6/JAK/STAT3 Signaling: pvalue calculation completed
IL-6/JAK/STAT3 Signaling: Calculation completed
DNA Repair: Calculation started
DNA Repair: scoring computed

Calculating pathways:  16%|█▌        | 8/50 [00:37<03:11,  4.56s/it]

DNA Repair: pvalue calculation completed
DNA Repair: Calculation completed
G2-M Checkpoint: Calculation started
G2-M Checkpoint: scoring computed

Calculating pathways:  18%|█▊        | 9/50 [00:43<03:20,  4.90s/it]

G2-M Checkpoint: pvalue calculation completed
G2-M Checkpoint: Calculation completed
Apoptosis: Calculation started
Apoptosis: scoring computed

Calculating pathways:  20%|██        | 10/50 [00:48<03:18,  4.97s/it]

Apoptosis: pvalue calculation completed
Apoptosis: Calculation completed
Notch Signaling: Calculation started
Notch Signaling: scoring computed

Calculating pathways:  22%|██▏       | 11/50 [00:52<02:58,  4.58s/it]

Notch Signaling: pvalue calculation completed
Notch Signaling: Calculation completed
Adipogenesis: Calculation started
Adipogenesis: scoring computed

Calculating pathways:  24%|██▍       | 12/50 [00:58<03:06,  4.92s/it]

Adipogenesis: pvalue calculation completed
Adipogenesis: Calculation completed
Estrogen Response Early: Calculation started
Estrogen Response Early: scoring computed

Calculating pathways:  26%|██▌       | 13/50 [01:03<03:08,  5.09s/it]

Estrogen Response Early: pvalue calculation completed
Estrogen Response Early: Calculation completed
Estrogen Response Late: Calculation started
Estrogen Response Late: scoring computed

Calculating pathways:  28%|██▊       | 14/50 [01:09<03:07,  5.21s/it]

Estrogen Response Late: pvalue calculation completed
Estrogen Response Late: Calculation completed
Androgen Response: Calculation started
Androgen Response: scoring computed

Calculating pathways:  30%|███       | 15/50 [01:13<02:55,  5.02s/it]

Androgen Response: pvalue calculation completed
Androgen Response: Calculation completed
Myogenesis: Calculation started
Myogenesis: scoring computed

Calculating pathways:  32%|███▏      | 16/50 [01:19<02:55,  5.17s/it]

Myogenesis: pvalue calculation completed
Myogenesis: Calculation completed
Protein Secretion: Calculation started
Protein Secretion: scoring computed

Calculating pathways:  34%|███▍      | 17/50 [01:23<02:44,  4.97s/it]

Protein Secretion: pvalue calculation completed
Protein Secretion: Calculation completed
Interferon Alpha Response: Calculation started
Interferon Alpha Response: scoring computed

Calculating pathways:  36%|███▌      | 18/50 [01:28<02:36,  4.88s/it]

Interferon Alpha Response: pvalue calculation completed
Interferon Alpha Response: Calculation completed
Interferon Gamma Response: Calculation started
Interferon Gamma Response: scoring computed

Calculating pathways:  38%|███▊      | 19/50 [01:34<02:39,  5.14s/it]

Interferon Gamma Response: pvalue calculation completed
Interferon Gamma Response: Calculation completed
Apical Junction: Calculation started
Apical Junction: scoring computed

Calculating pathways:  40%|████      | 20/50 [01:39<02:37,  5.24s/it]

Apical Junction: pvalue calculation completed
Apical Junction: Calculation completed
Apical Surface: Calculation started
Apical Surface: scoring computed

Calculating pathways:  42%|████▏     | 21/50 [01:43<02:19,  4.82s/it]

Apical Surface: pvalue calculation completed
Apical Surface: Calculation completed
Hedgehog Signaling: Calculation started
Hedgehog Signaling: scoring computed

Calculating pathways:  44%|████▍     | 22/50 [01:47<02:06,  4.52s/it]

Hedgehog Signaling: pvalue calculation completed
Hedgehog Signaling: Calculation completed
Complement: Calculation started
Complement: scoring computed

Calculating pathways:  46%|████▌     | 23/50 [01:52<02:10,  4.85s/it]

Complement: pvalue calculation completed
Complement: Calculation completed
Unfolded Protein Response: Calculation started
Unfolded Protein Response: scoring computed

Calculating pathways:  48%|████▊     | 24/50 [01:57<02:04,  4.78s/it]

Unfolded Protein Response: pvalue calculation completed
Unfolded Protein Response: Calculation completed
PI3K/AKT/mTOR  Signaling: Calculation started
PI3K/AKT/mTOR  Signaling: scoring computed

Calculating pathways:  50%|█████     | 25/50 [02:02<01:58,  4.73s/it]

PI3K/AKT/mTOR  Signaling: pvalue calculation completed
PI3K/AKT/mTOR  Signaling: Calculation completed
mTORC1 Signaling: Calculation started
mTORC1 Signaling: scoring computed

Calculating pathways:  52%|█████▏    | 26/50 [02:07<02:00,  5.01s/it]

mTORC1 Signaling: pvalue calculation completed
mTORC1 Signaling: Calculation completed
E2F Targets: Calculation started
E2F Targets: scoring computed

Calculating pathways:  54%|█████▍    | 27/50 [02:13<01:59,  5.18s/it]

E2F Targets: pvalue calculation completed
E2F Targets: Calculation completed
Myc Targets V1: Calculation started
Myc Targets V1: scoring computed

Calculating pathways:  56%|█████▌    | 28/50 [02:18<01:57,  5.32s/it]

Myc Targets V1: pvalue calculation completed
Myc Targets V1: Calculation completed
Myc Targets V2: Calculation started
Myc Targets V2: scoring computed

Calculating pathways:  58%|█████▊    | 29/50 [02:22<01:43,  4.93s/it]

Myc Targets V2: pvalue calculation completed
Myc Targets V2: Calculation completed
Epithelial Mesenchymal Transition: Calculation started
Epithelial Mesenchymal Transition: scoring computed

Calculating pathways:  60%|██████    | 30/50 [02:28<01:43,  5.19s/it]

Epithelial Mesenchymal Transition: pvalue calculation completed
Epithelial Mesenchymal Transition: Calculation completed
Inflammatory Response: Calculation started
Inflammatory Response: scoring computed

Calculating pathways:  62%|██████▏   | 31/50 [02:34<01:40,  5.29s/it]

Inflammatory Response: pvalue calculation completed
Inflammatory Response: Calculation completed
Xenobiotic Metabolism: Calculation started
Xenobiotic Metabolism: scoring computed

Calculating pathways:  64%|██████▍   | 32/50 [02:39<01:36,  5.34s/it]

Xenobiotic Metabolism: pvalue calculation completed
Xenobiotic Metabolism: Calculation completed
Fatty Acid Metabolism: Calculation started
Fatty Acid Metabolism: scoring computed

Calculating pathways:  66%|██████▌   | 33/50 [02:44<01:29,  5.26s/it]

Fatty Acid Metabolism: pvalue calculation completed
Fatty Acid Metabolism: Calculation completed
Oxidative Phosphorylation: Calculation started
Oxidative Phosphorylation: scoring computed

Calculating pathways:  68%|██████▊   | 34/50 [02:50<01:25,  5.35s/it]

Oxidative Phosphorylation: pvalue calculation completed
Oxidative Phosphorylation: Calculation completed
Glycolysis: Calculation started
Glycolysis: scoring computed

Calculating pathways:  70%|███████   | 35/50 [02:55<01:21,  5.43s/it]

Glycolysis: pvalue calculation completed
Glycolysis: Calculation completed
Reactive Oxygen Species Pathway: Calculation started
Reactive Oxygen Species Pathway: scoring computed

Calculating pathways:  72%|███████▏  | 36/50 [02:59<01:09,  4.99s/it]

Reactive Oxygen Species Pathway: pvalue calculation completed
Reactive Oxygen Species Pathway: Calculation completed
p53 Pathway: Calculation started
p53 Pathway: scoring computed

Calculating pathways:  74%|███████▍  | 37/50 [03:05<01:06,  5.15s/it]

p53 Pathway: pvalue calculation completed
p53 Pathway: Calculation completed
UV Response Up: Calculation started
UV Response Up: scoring computed

Calculating pathways:  76%|███████▌  | 38/50 [03:10<01:01,  5.11s/it]

UV Response Up: pvalue calculation completed
UV Response Up: Calculation completed
UV Response Dn: Calculation started
UV Response Dn: scoring computed

Calculating pathways:  78%|███████▊  | 39/50 [03:15<00:56,  5.13s/it]

UV Response Dn: pvalue calculation completed
UV Response Dn: Calculation completed
Angiogenesis: Calculation started
Angiogenesis: scoring computed

Calculating pathways:  80%|████████  | 40/50 [03:19<00:47,  4.72s/it]

Angiogenesis: pvalue calculation completed
Angiogenesis: Calculation completed
heme Metabolism: Calculation started
heme Metabolism: scoring computed

Calculating pathways:  82%|████████▏ | 41/50 [03:25<00:44,  5.00s/it]

heme Metabolism: pvalue calculation completed
heme Metabolism: Calculation completed
Coagulation: Calculation started
Coagulation: scoring computed

Calculating pathways:  84%|████████▍ | 42/50 [03:29<00:39,  4.93s/it]

Coagulation: pvalue calculation completed
Coagulation: Calculation completed
IL-2/STAT5 Signaling: Calculation started
IL-2/STAT5 Signaling: scoring computed

Calculating pathways:  86%|████████▌ | 43/50 [03:35<00:35,  5.09s/it]

IL-2/STAT5 Signaling: pvalue calculation completed
IL-2/STAT5 Signaling: Calculation completed
Bile Acid Metabolism: Calculation started
Bile Acid Metabolism: scoring computed

Calculating pathways:  88%|████████▊ | 44/50 [03:39<00:29,  4.94s/it]

Bile Acid Metabolism: pvalue calculation completed
Bile Acid Metabolism: Calculation completed
Pperoxisome: Calculation started
Pperoxisome: scoring computed

Calculating pathways:  90%|█████████ | 45/50 [03:44<00:23,  4.79s/it]

Pperoxisome: pvalue calculation completed
Pperoxisome: Calculation completed
Allograft Rejection: Calculation started
Allograft Rejection: scoring computed

Calculating pathways:  92%|█████████▏| 46/50 [03:49<00:19,  4.93s/it]

Allograft Rejection: pvalue calculation completed
Allograft Rejection: Calculation completed
Spermatogenesis: Calculation started
Spermatogenesis: scoring computed

Calculating pathways:  94%|█████████▍| 47/50 [03:54<00:14,  4.79s/it]

Spermatogenesis: pvalue calculation completed
Spermatogenesis: Calculation completed
KRAS Signaling Up: Calculation started
KRAS Signaling Up: scoring computed

Calculating pathways:  96%|█████████▌| 48/50 [03:59<00:09,  4.99s/it]

KRAS Signaling Up: pvalue calculation completed
KRAS Signaling Up: Calculation completed
KRAS Signaling Dn: Calculation started
KRAS Signaling Dn: scoring computed

Calculating pathways:  98%|█████████▊| 49/50 [04:04<00:05,  5.07s/it]

KRAS Signaling Dn: pvalue calculation completed
KRAS Signaling Dn: Calculation completed
Pancreas Beta Cells: Calculation started
Pancreas Beta Cells: scoring computed

Calculating pathways: 100%|██████████| 50/50 [04:08<00:00,  4.97s/it]

Pancreas Beta Cells: pvalue calculation completed
Pancreas Beta Cells: Calculation completed

## Fulvestrant

In [12]:
import os
from singscore.singscore import *
import pandas as pd
import json
from tqdm import tqdm

## loading the patient uk65 data 
uk65 = pd.read_csv("singscore_new_code/UK65_clean_gene_log_tpm.txt", header='infer', sep='\t')
uk65 = uk65.set_index(keys='GeneName')

#loading drug_data
drug_data = json.load(open("singscore_new_code/Fulvestrant/Fulvestrant_relevant_pathways.json"))
count = len(drug_data)
print("Number of items:", count)

final_result = {}

for key, value in tqdm(drug_data.items(), desc="Calculating pathways"):
    print(f"{key}: Calculation started")
    up = drug_data[key]
    up_present = [gene for gene in up if gene in uk65.index]

    # Print counts and summary
    # print(f"Total up genes in signature: {len(up)}")
    # print(f"Up genes found in expression data: {len(up_present)}")

    # Optionally, print the missing ones
    missing_up = set(up) - set(uk65.index)

    # print(f"Missing up genes: {len(missing_up)}")
    scored_data = score(up_gene=up, down_gene=False, sample=uk65,
                    norm_method='theoretical', full_data=True)
    #getting the scored data for a pathway
    total_score = scored_data["total_score"].to_list()[0]
    print(f"{key}: scoring computed")
    permd = permutate(uk65, n_up=len(up_present), n_down=False)
    pvals = empiricalpval(permutations=permd, score=scored_data)
    empirical_p_value = pvals["empirical p value"].to_list()[0]
    print(f"{key}: pvalue calculation completed")
    result = {
    f"{key}":{
        "gene_set_info": {
            "geneset_size": len(up),
            "geneset_covered_in_sample": len(up_present)
        },
        "scores": {
            "total_singscore": total_score
        },
        "statistics": {
            "p_value": empirical_p_value,
            "method": "permutation (empirical)",
            "permutations": 10000
        }}}
    print(f"{key}: Calculation completed")
    final_result.update(result)

# Save final combined JSON
with open("singscore_new_code/Fulvestrant/Fulvestrant_singscore_results.json", "w", encoding="utf-8") as f:
    json.dump(final_result, f, indent=2, ensure_ascii=False)

Number of items: 299

Calculating pathways:   0%|          | 0/299 [00:00<?, ?it/s]

Estrogen Response Early: Calculation started
Estrogen Response Early: scoring computed

Calculating pathways:   0%|          | 1/299 [00:05<28:06,  5.66s/it]

Estrogen Response Early: pvalue calculation completed
Estrogen Response Early: Calculation completed
Estrogen Response Late: Calculation started
Estrogen Response Late: scoring computed

Calculating pathways:   1%|          | 2/299 [00:11<27:31,  5.56s/it]

Estrogen Response Late: pvalue calculation completed
Estrogen Response Late: Calculation completed
Xenobiotic Metabolism: Calculation started
Xenobiotic Metabolism: scoring computed

Calculating pathways:   1%|          | 3/299 [00:16<27:03,  5.49s/it]

Xenobiotic Metabolism: pvalue calculation completed
Xenobiotic Metabolism: Calculation completed
Fatty Acid Metabolism: Calculation started
Fatty Acid Metabolism: scoring computed

Calculating pathways:   1%|▏         | 4/299 [00:21<26:39,  5.42s/it]

Fatty Acid Metabolism: pvalue calculation completed
Fatty Acid Metabolism: Calculation completed
Bile Acid Metabolism: Calculation started
Bile Acid Metabolism: scoring computed

Calculating pathways:   2%|▏         | 5/299 [00:26<25:02,  5.11s/it]

Bile Acid Metabolism: pvalue calculation completed
Bile Acid Metabolism: Calculation completed
Pperoxisome: Calculation started
Pperoxisome: scoring computed

Calculating pathways:   2%|▏         | 6/299 [00:30<23:49,  4.88s/it]

Pperoxisome: pvalue calculation completed
Pperoxisome: Calculation completed
KRAS Signaling Up: Calculation started
KRAS Signaling Up: scoring computed

Calculating pathways:   2%|▏         | 7/299 [00:36<24:50,  5.10s/it]

KRAS Signaling Up: pvalue calculation completed
KRAS Signaling Up: Calculation completed
Arachidonic acid metabolism: Calculation started
Arachidonic acid metabolism: scoring computed

Calculating pathways:   3%|▎         | 8/299 [00:40<22:49,  4.70s/it]

Arachidonic acid metabolism: pvalue calculation completed
Arachidonic acid metabolism: Calculation completed
Bile secretion: Calculation started
Bile secretion: scoring computed

Calculating pathways:   3%|▎         | 9/299 [00:44<21:56,  4.54s/it]

Bile secretion: pvalue calculation completed
Bile secretion: Calculation completed
Breast cancer: Calculation started
Breast cancer: scoring computed

Calculating pathways:   3%|▎         | 10/299 [00:49<22:23,  4.65s/it]

Breast cancer: pvalue calculation completed
Breast cancer: Calculation completed
Chemical carcinogenesis: Calculation started
Chemical carcinogenesis: scoring computed

Calculating pathways:   4%|▎         | 11/299 [00:55<23:56,  4.99s/it]

Chemical carcinogenesis: pvalue calculation completed
Chemical carcinogenesis: Calculation completed
Endocrine and other factor-regulated calcium reabsorption: Calculation started
Endocrine and other factor-regulated calcium reabsorption: scoring computed

Calculating pathways:   4%|▍         | 12/299 [00:58<22:13,  4.65s/it]

Endocrine and other factor-regulated calcium reabsorption: pvalue calculation completed
Endocrine and other factor-regulated calcium reabsorption: Calculation completed
Estrogen signaling pathway: Calculation started
Estrogen signaling pathway: scoring computed

Calculating pathways:   4%|▍         | 13/299 [01:03<22:06,  4.64s/it]

Estrogen signaling pathway: pvalue calculation completed
Estrogen signaling pathway: Calculation completed
GnRH secretion: Calculation started
GnRH secretion: scoring computed

Calculating pathways:   5%|▍         | 14/299 [01:07<21:26,  4.52s/it]

GnRH secretion: pvalue calculation completed
GnRH secretion: Calculation completed
Oocyte meiosis: Calculation started
Oocyte meiosis: scoring computed

Calculating pathways:   5%|▌         | 15/299 [01:12<21:54,  4.63s/it]

Oocyte meiosis: pvalue calculation completed
Oocyte meiosis: Calculation completed
Pathways in cancer: Calculation started
Pathways in cancer: scoring computed

Calculating pathways:   5%|▌         | 16/299 [01:21<27:32,  5.84s/it]

Pathways in cancer: pvalue calculation completed
Pathways in cancer: Calculation completed
Peroxisome: Calculation started
Peroxisome: scoring computed

Calculating pathways:   6%|▌         | 17/299 [01:25<25:12,  5.36s/it]

Peroxisome: pvalue calculation completed
Peroxisome: Calculation completed
Progesterone-mediated oocyte maturation: Calculation started
Progesterone-mediated oocyte maturation: scoring computed

Calculating pathways:   6%|▌         | 18/299 [01:30<23:59,  5.12s/it]

Progesterone-mediated oocyte maturation: pvalue calculation completed
Progesterone-mediated oocyte maturation: Calculation completed
Prolactin signaling pathway: Calculation started
Prolactin signaling pathway: scoring computed

Calculating pathways:   6%|▋         | 19/299 [01:34<22:34,  4.84s/it]

Prolactin signaling pathway: pvalue calculation completed
Prolactin signaling pathway: Calculation completed
Proteoglycans in cancer: Calculation started
Proteoglycans in cancer: scoring computed

Calculating pathways:   7%|▋         | 20/299 [01:39<23:36,  5.08s/it]

Proteoglycans in cancer: pvalue calculation completed
Proteoglycans in cancer: Calculation completed
Thyroid hormone signaling pathway: Calculation started
Thyroid hormone signaling pathway: scoring computed

Calculating pathways:   7%|▋         | 21/299 [01:44<22:56,  4.95s/it]

Thyroid hormone signaling pathway: pvalue calculation completed
Thyroid hormone signaling pathway: Calculation completed
Arachidonate Metabolism: Calculation started
Arachidonate Metabolism: scoring computed

Calculating pathways:   7%|▋         | 22/299 [01:48<21:28,  4.65s/it]

Arachidonate Metabolism: pvalue calculation completed
Arachidonate Metabolism: Calculation completed
Bile Acid and Bile Salt Metabolism: Calculation started
Bile Acid and Bile Salt Metabolism: scoring computed

Calculating pathways:   8%|▊         | 23/299 [01:52<20:30,  4.46s/it]

Bile Acid and Bile Salt Metabolism: pvalue calculation completed
Bile Acid and Bile Salt Metabolism: Calculation completed
Biological Oxidations: Calculation started
Biological Oxidations: scoring computed

Calculating pathways:   8%|▊         | 24/299 [01:57<21:40,  4.73s/it]

Biological Oxidations: pvalue calculation completed
Biological Oxidations: Calculation completed
Biosynthesis of DHA-derived SPMs: Calculation started
Biosynthesis of DHA-derived SPMs: scoring computed

Calculating pathways:   8%|▊         | 25/299 [02:01<19:52,  4.35s/it]

Biosynthesis of DHA-derived SPMs: pvalue calculation completed
Biosynthesis of DHA-derived SPMs: Calculation completed
Biosynthesis of Maresins: Calculation started
Biosynthesis of Maresins: scoring computed

Calculating pathways:   9%|▊         | 26/299 [02:04<18:41,  4.11s/it]

Biosynthesis of Maresins: pvalue calculation completed
Biosynthesis of Maresins: Calculation completed
Biosynthesis of Specialized Proresolving Mediators (SPMs): Calculation started
Biosynthesis of Specialized Proresolving Mediators (SPMs): scoring computed

Calculating pathways:   9%|▉         | 27/299 [02:08<17:46,  3.92s/it]

Biosynthesis of Specialized Proresolving Mediators (SPMs): pvalue calculation completed
Biosynthesis of Specialized Proresolving Mediators (SPMs): Calculation completed
Cellular Responses to Stimuli: Calculation started
Cellular Responses to Stimuli: scoring computed

Calculating pathways:   9%|▉         | 28/299 [02:20<29:21,  6.50s/it]

Cellular Responses to Stimuli: pvalue calculation completed
Cellular Responses to Stimuli: Calculation completed
Cellular Responses to Stress: Calculation started
Cellular Responses to Stress: scoring computed

Calculating pathways:  10%|▉         | 29/299 [02:32<35:46,  7.95s/it]

Cellular Responses to Stress: pvalue calculation completed
Cellular Responses to Stress: Calculation completed
Class A 1 (Rhodopsin-like Receptors): Calculation started
Class A 1 (Rhodopsin-like Receptors): scoring computed

Calculating pathways:  10%|█         | 30/299 [02:38<33:03,  7.37s/it]

Class A 1 (Rhodopsin-like Receptors): pvalue calculation completed
Class A 1 (Rhodopsin-like Receptors): Calculation completed
Constitutive Signaling by Aberrant PI3K in Cancer: Calculation started
Constitutive Signaling by Aberrant PI3K in Cancer: scoring computed

Calculating pathways:  10%|█         | 31/299 [02:42<28:29,  6.38s/it]

Constitutive Signaling by Aberrant PI3K in Cancer: pvalue calculation completed
Constitutive Signaling by Aberrant PI3K in Cancer: Calculation completed
Cytochrome P450 - Arranged by Substrate Type: Calculation started
Cytochrome P450 - Arranged by Substrate Type: scoring computed

Calculating pathways:  11%|█         | 32/299 [02:46<25:11,  5.66s/it]

Cytochrome P450 - Arranged by Substrate Type: pvalue calculation completed
Cytochrome P450 - Arranged by Substrate Type: Calculation completed
Deubiquitination: Calculation started
Deubiquitination: scoring computed

Calculating pathways:  11%|█         | 33/299 [02:52<25:24,  5.73s/it]

Deubiquitination: pvalue calculation completed
Deubiquitination: Calculation completed
Diseases of Signal Transduction by Growth Factor Receptors and Second Messengers: Calculation started
Diseases of Signal Transduction by Growth Factor Receptors and Second Messengers: scoring computed

Calculating pathways:  11%|█▏        | 34/299 [03:00<28:42,  6.50s/it]

Diseases of Signal Transduction by Growth Factor Receptors and Second Messengers: pvalue calculation completed
Diseases of Signal Transduction by Growth Factor Receptors and Second Messengers: Calculation completed
ESR-mediated Signaling: Calculation started
ESR-mediated Signaling: scoring computed

Calculating pathways:  12%|█▏        | 35/299 [03:05<27:10,  6.17s/it]

ESR-mediated Signaling: pvalue calculation completed
ESR-mediated Signaling: Calculation completed
Endogenous Sterols: Calculation started
Endogenous Sterols: scoring computed

Calculating pathways:  12%|█▏        | 36/299 [03:09<23:33,  5.38s/it]

Endogenous Sterols: pvalue calculation completed
Endogenous Sterols: Calculation completed
Estrogen-dependent Gene Expression: Calculation started
Estrogen-dependent Gene Expression: scoring computed

Calculating pathways:  12%|█▏        | 37/299 [03:14<22:26,  5.14s/it]

Estrogen-dependent Gene Expression: pvalue calculation completed
Estrogen-dependent Gene Expression: Calculation completed
Extra-nuclear Estrogen Signaling: Calculation started
Extra-nuclear Estrogen Signaling: scoring computed

Calculating pathways:  13%|█▎        | 38/299 [03:18<21:06,  4.85s/it]

Extra-nuclear Estrogen Signaling: pvalue calculation completed
Extra-nuclear Estrogen Signaling: Calculation completed
G Alpha (I) Signalling Events: Calculation started
G Alpha (I) Signalling Events: scoring computed

Calculating pathways:  13%|█▎        | 39/299 [03:24<22:33,  5.21s/it]

G Alpha (I) Signalling Events: pvalue calculation completed
G Alpha (I) Signalling Events: Calculation completed
G Alpha (S) Signalling Events: Calculation started
G Alpha (S) Signalling Events: scoring computed

Calculating pathways:  13%|█▎        | 40/299 [03:28<21:33,  5.00s/it]

G Alpha (S) Signalling Events: pvalue calculation completed
G Alpha (S) Signalling Events: Calculation completed
GPCR Downstream Signalling: Calculation started
GPCR Downstream Signalling: scoring computed

Calculating pathways:  14%|█▎        | 41/299 [03:37<26:17,  6.12s/it]

GPCR Downstream Signalling: pvalue calculation completed
GPCR Downstream Signalling: Calculation completed
GPCR Ligand Binding: Calculation started
GPCR Ligand Binding: scoring computed

Calculating pathways:  14%|█▍        | 42/299 [03:44<27:16,  6.37s/it]

GPCR Ligand Binding: pvalue calculation completed
GPCR Ligand Binding: Calculation completed
GPER1 Signaling: Calculation started
GPER1 Signaling: scoring computed

Calculating pathways:  14%|█▍        | 43/299 [03:48<23:57,  5.62s/it]

GPER1 Signaling: pvalue calculation completed
GPER1 Signaling: Calculation completed
Gene Expression (Transcription): Calculation started
Gene Expression (Transcription): scoring computed

Calculating pathways:  15%|█▍        | 44/299 [04:07<41:32,  9.77s/it]

Gene Expression (Transcription): pvalue calculation completed
Gene Expression (Transcription): Calculation completed
Generic Transcription Pathway: Calculation started
Generic Transcription Pathway: scoring computed

Calculating pathways:  15%|█▌        | 45/299 [04:23<48:52, 11.54s/it]

Generic Transcription Pathway: pvalue calculation completed
Generic Transcription Pathway: Calculation completed
HSP90 Chaperone Cycle for Steroid Hormone Receptors (SHR) in the Presence of Ligand: Calculation started
HSP90 Chaperone Cycle for Steroid Hormone Receptors (SHR) in the Presence of Ligand: scoring computed

Calculating pathways:  15%|█▌        | 46/299 [04:27<39:00,  9.25s/it]

HSP90 Chaperone Cycle for Steroid Hormone Receptors (SHR) in the Presence of Ligand: pvalue calculation completed
HSP90 Chaperone Cycle for Steroid Hormone Receptors (SHR) in the Presence of Ligand: Calculation completed
Intracellular Signaling by Second Messengers: Calculation started
Intracellular Signaling by Second Messengers: scoring computed

Calculating pathways:  16%|█▌        | 47/299 [04:34<35:33,  8.47s/it]

Intracellular Signaling by Second Messengers: pvalue calculation completed
Intracellular Signaling by Second Messengers: Calculation completed
Metabolism of Lipids: Calculation started
Metabolism of Lipids: scoring computed

Calculating pathways:  16%|█▌        | 48/299 [04:45<38:46,  9.27s/it]

Metabolism of Lipids: pvalue calculation completed
Metabolism of Lipids: Calculation completed
Metabolism of Steroids: Calculation started
Metabolism of Steroids: scoring computed

Calculating pathways:  16%|█▋        | 49/299 [04:50<33:03,  7.94s/it]

Metabolism of Steroids: pvalue calculation completed
Metabolism of Steroids: Calculation completed
Mitochondrial Biogenesis: Calculation started
Mitochondrial Biogenesis: scoring computed

Calculating pathways:  17%|█▋        | 50/299 [04:54<28:36,  6.89s/it]

Mitochondrial Biogenesis: pvalue calculation completed
Mitochondrial Biogenesis: Calculation completed
Mitochondrial Unfolded Protein Response (UPRmt): Calculation started
Mitochondrial Unfolded Protein Response (UPRmt): scoring computed

Calculating pathways:  17%|█▋        | 51/299 [04:58<24:19,  5.89s/it]

Mitochondrial Unfolded Protein Response (UPRmt): pvalue calculation completed
Mitochondrial Unfolded Protein Response (UPRmt): Calculation completed
Negative Regulation of the PI3K AKT Network: Calculation started
Negative Regulation of the PI3K AKT Network: scoring computed

Calculating pathways:  17%|█▋        | 52/299 [05:02<22:27,  5.46s/it]

Negative Regulation of the PI3K AKT Network: pvalue calculation completed
Negative Regulation of the PI3K AKT Network: Calculation completed
Nuclear Receptor Transcription Pathway: Calculation started
Nuclear Receptor Transcription Pathway: scoring computed

Calculating pathways:  18%|█▊        | 53/299 [05:06<20:23,  4.97s/it]

Nuclear Receptor Transcription Pathway: pvalue calculation completed
Nuclear Receptor Transcription Pathway: Calculation completed
Nuclear Signaling by ERBB4: Calculation started
Nuclear Signaling by ERBB4: scoring computed

Calculating pathways:  18%|█▊        | 54/299 [05:09<18:39,  4.57s/it]

Nuclear Signaling by ERBB4: pvalue calculation completed
Nuclear Signaling by ERBB4: Calculation completed
Organelle Biogenesis and Maintenance: Calculation started
Organelle Biogenesis and Maintenance: scoring computed

Calculating pathways:  18%|█▊        | 55/299 [05:16<20:58,  5.16s/it]

Organelle Biogenesis and Maintenance: pvalue calculation completed
Organelle Biogenesis and Maintenance: Calculation completed
Ovarian Tumor Domain Proteases: Calculation started
Ovarian Tumor Domain Proteases: scoring computed

Calculating pathways:  19%|█▊        | 56/299 [05:20<19:12,  4.74s/it]

Ovarian Tumor Domain Proteases: pvalue calculation completed
Ovarian Tumor Domain Proteases: Calculation completed
PI3K AKT Signaling in Cancer: Calculation started
PI3K AKT Signaling in Cancer: scoring computed

Calculating pathways:  19%|█▉        | 57/299 [05:24<18:44,  4.65s/it]

PI3K AKT Signaling in Cancer: pvalue calculation completed
PI3K AKT Signaling in Cancer: Calculation completed
PI5P, PP2A and IER3 Regulate PI3K AKT Signaling: Calculation started
PI5P, PP2A and IER3 Regulate PI3K AKT Signaling: scoring computed

Calculating pathways:  19%|█▉        | 58/299 [05:29<18:26,  4.59s/it]

PI5P, PP2A and IER3 Regulate PI3K AKT Signaling: pvalue calculation completed
PI5P, PP2A and IER3 Regulate PI3K AKT Signaling: Calculation completed
PIP3 Activates AKT Signaling: Calculation started
PIP3 Activates AKT Signaling: scoring computed

Calculating pathways:  20%|█▉        | 59/299 [05:35<20:24,  5.10s/it]

PIP3 Activates AKT Signaling: pvalue calculation completed
PIP3 Activates AKT Signaling: Calculation completed
PPARA Activates Gene Expression: Calculation started
PPARA Activates Gene Expression: scoring computed

Calculating pathways:  20%|██        | 60/299 [05:39<19:40,  4.94s/it]

PPARA Activates Gene Expression: pvalue calculation completed
PPARA Activates Gene Expression: Calculation completed
Peptide Ligand-Binding Receptors: Calculation started
Peptide Ligand-Binding Receptors: scoring computed

Calculating pathways:  20%|██        | 61/299 [05:44<19:33,  4.93s/it]

Peptide Ligand-Binding Receptors: pvalue calculation completed
Peptide Ligand-Binding Receptors: Calculation completed
Peroxisomal Protein Import: Calculation started
Peroxisomal Protein Import: scoring computed

Calculating pathways:  21%|██        | 62/299 [05:48<18:24,  4.66s/it]

Peroxisomal Protein Import: pvalue calculation completed
Peroxisomal Protein Import: Calculation completed
Phase I - Functionalization of Compounds: Calculation started
Phase I - Functionalization of Compounds: scoring computed

Calculating pathways:  21%|██        | 63/299 [05:53<17:58,  4.57s/it]

Phase I - Functionalization of Compounds: pvalue calculation completed
Phase I - Functionalization of Compounds: Calculation completed
Post-translational Protein Modification: Calculation started
Post-translational Protein Modification: scoring computed

Calculating pathways:  21%|██▏       | 64/299 [06:10<33:15,  8.49s/it]

Post-translational Protein Modification: pvalue calculation completed
Post-translational Protein Modification: Calculation completed
Protein Localization: Calculation started
Protein Localization: scoring computed

Calculating pathways:  22%|██▏       | 65/299 [06:16<29:08,  7.47s/it]

Protein Localization: pvalue calculation completed
Protein Localization: Calculation completed
RNA Polymerase II Transcription: Calculation started
RNA Polymerase II Transcription: scoring computed

Calculating pathways:  22%|██▏       | 66/299 [06:32<40:00, 10.30s/it]

RNA Polymerase II Transcription: pvalue calculation completed
RNA Polymerase II Transcription: Calculation completed
RUNX1 Regulates Estrogen Receptor Mediated Transcription: Calculation started
RUNX1 Regulates Estrogen Receptor Mediated Transcription: scoring computed

Calculating pathways:  22%|██▏       | 67/299 [06:36<31:49,  8.23s/it]

RUNX1 Regulates Estrogen Receptor Mediated Transcription: pvalue calculation completed
RUNX1 Regulates Estrogen Receptor Mediated Transcription: Calculation completed
RUNX1 Regulates Transcription of Genes Involved in WNT Signaling: Calculation started
RUNX1 Regulates Transcription of Genes Involved in WNT Signaling: scoring computed

Calculating pathways:  23%|██▎       | 68/299 [06:39<26:02,  6.76s/it]

RUNX1 Regulates Transcription of Genes Involved in WNT Signaling: pvalue calculation completed
RUNX1 Regulates Transcription of Genes Involved in WNT Signaling: Calculation completed
Recycling of Bile Acids and Salts: Calculation started
Recycling of Bile Acids and Salts: scoring computed

Calculating pathways:  23%|██▎       | 69/299 [06:43<22:05,  5.77s/it]

Recycling of Bile Acids and Salts: pvalue calculation completed
Recycling of Bile Acids and Salts: Calculation completed
Regulation of RUNX2 Expression and Activity: Calculation started
Regulation of RUNX2 Expression and Activity: scoring computed

Calculating pathways:  23%|██▎       | 70/299 [06:47<19:55,  5.22s/it]

Regulation of RUNX2 Expression and Activity: pvalue calculation completed
Regulation of RUNX2 Expression and Activity: Calculation completed
Regulation of Lipid Metabolism by PPARalpha: Calculation started
Regulation of Lipid Metabolism by PPARalpha: scoring computed

Calculating pathways:  24%|██▎       | 71/299 [06:51<19:02,  5.01s/it]

Regulation of Lipid Metabolism by PPARalpha: pvalue calculation completed
Regulation of Lipid Metabolism by PPARalpha: Calculation completed
SUMO E3 Ligases SUMOylate Target Proteins: Calculation started
SUMO E3 Ligases SUMOylate Target Proteins: scoring computed

Calculating pathways:  24%|██▍       | 72/299 [06:56<19:15,  5.09s/it]

SUMO E3 Ligases SUMOylate Target Proteins: pvalue calculation completed
SUMO E3 Ligases SUMOylate Target Proteins: Calculation completed
SUMOylation: Calculation started
SUMOylation: scoring computed

Calculating pathways:  24%|██▍       | 73/299 [07:02<19:28,  5.17s/it]

SUMOylation: pvalue calculation completed
SUMOylation: Calculation completed
SUMOylation of Intracellular Receptors: Calculation started
SUMOylation of Intracellular Receptors: scoring computed

Calculating pathways:  25%|██▍       | 74/299 [07:05<17:40,  4.72s/it]

SUMOylation of Intracellular Receptors: pvalue calculation completed
SUMOylation of Intracellular Receptors: Calculation completed
Signaling by ERBB4: Calculation started
Signaling by ERBB4: scoring computed

Calculating pathways:  25%|██▌       | 75/299 [07:09<16:40,  4.47s/it]

Signaling by ERBB4: pvalue calculation completed
Signaling by ERBB4: Calculation completed
Signaling by GPCR: Calculation started
Signaling by GPCR: scoring computed

Calculating pathways:  25%|██▌       | 76/299 [07:19<22:14,  5.98s/it]

Signaling by GPCR: pvalue calculation completed
Signaling by GPCR: Calculation completed
Signaling by Nuclear Receptors: Calculation started
Signaling by Nuclear Receptors: scoring computed

Calculating pathways:  26%|██▌       | 77/299 [07:25<22:23,  6.05s/it]

Signaling by Nuclear Receptors: pvalue calculation completed
Signaling by Nuclear Receptors: Calculation completed
Signaling by Receptor Tyrosine Kinases: Calculation started
Signaling by Receptor Tyrosine Kinases: scoring computed

Calculating pathways:  26%|██▌       | 78/299 [07:34<25:30,  6.93s/it]

Signaling by Receptor Tyrosine Kinases: pvalue calculation completed
Signaling by Receptor Tyrosine Kinases: Calculation completed
Synthesis of Bile Acids and Bile Salts: Calculation started
Synthesis of Bile Acids and Bile Salts: scoring computed

Calculating pathways:  26%|██▋       | 79/299 [07:38<21:46,  5.94s/it]

Synthesis of Bile Acids and Bile Salts: pvalue calculation completed
Synthesis of Bile Acids and Bile Salts: Calculation completed
Synthesis of Bile Acids and Bile Salts via 27-Hydroxycholesterol: Calculation started
Synthesis of Bile Acids and Bile Salts via 27-Hydroxycholesterol: scoring computed

Calculating pathways:  27%|██▋       | 80/299 [07:41<18:59,  5.20s/it]

Synthesis of Bile Acids and Bile Salts via 27-Hydroxycholesterol: pvalue calculation completed
Synthesis of Bile Acids and Bile Salts via 27-Hydroxycholesterol: Calculation completed
Synthesis of Bile Acids and Bile Salts via 7Alpha-Hydroxycholesterol: Calculation started
Synthesis of Bile Acids and Bile Salts via 7Alpha-Hydroxycholesterol: scoring computed

Calculating pathways:  27%|██▋       | 81/299 [07:45<17:10,  4.73s/it]

Synthesis of Bile Acids and Bile Salts via 7Alpha-Hydroxycholesterol: pvalue calculation completed
Synthesis of Bile Acids and Bile Salts via 7Alpha-Hydroxycholesterol: Calculation completed
Synthesis of Epoxy (EET) and Dihydroxyeicosatrienoic Acids (DHET): Calculation started
Synthesis of Epoxy (EET) and Dihydroxyeicosatrienoic Acids (DHET): scoring computed

Calculating pathways:  27%|██▋       | 82/299 [07:48<15:35,  4.31s/it]

Synthesis of Epoxy (EET) and Dihydroxyeicosatrienoic Acids (DHET): pvalue calculation completed
Synthesis of Epoxy (EET) and Dihydroxyeicosatrienoic Acids (DHET): Calculation completed
TFAP2 (AP-2) Family Regulates Transcription of Growth Factors and Their Receptors: Calculation started
TFAP2 (AP-2) Family Regulates Transcription of Growth Factors and Their Receptors: scoring computed

Calculating pathways:  28%|██▊       | 83/299 [07:51<14:36,  4.06s/it]

TFAP2 (AP-2) Family Regulates Transcription of Growth Factors and Their Receptors: pvalue calculation completed
TFAP2 (AP-2) Family Regulates Transcription of Growth Factors and Their Receptors: Calculation completed
Transcriptional Activation of Mitochondrial Biogenesis: Calculation started
Transcriptional Activation of Mitochondrial Biogenesis: scoring computed

Calculating pathways:  28%|██▊       | 84/299 [07:55<14:27,  4.03s/it]

Transcriptional Activation of Mitochondrial Biogenesis: pvalue calculation completed
Transcriptional Activation of Mitochondrial Biogenesis: Calculation completed
Transcriptional Regulation by RUNX1: Calculation started
Transcriptional Regulation by RUNX1: scoring computed

Calculating pathways:  28%|██▊       | 85/299 [08:01<15:44,  4.41s/it]

Transcriptional Regulation by RUNX1: pvalue calculation completed
Transcriptional Regulation by RUNX1: Calculation completed
Transcriptional Regulation by RUNX2: Calculation started
Transcriptional Regulation by RUNX2: scoring computed

Calculating pathways:  29%|██▉       | 86/299 [08:05<15:58,  4.50s/it]

Transcriptional Regulation by RUNX2: pvalue calculation completed
Transcriptional Regulation by RUNX2: Calculation completed
Transcriptional Regulation by the AP-2 (TFAP2) Family of Transcription Factors: Calculation started
Transcriptional Regulation by the AP-2 (TFAP2) Family of Transcription Factors: scoring computed

Calculating pathways:  29%|██▉       | 87/299 [08:09<15:07,  4.28s/it]

Transcriptional Regulation by the AP-2 (TFAP2) Family of Transcription Factors: pvalue calculation completed
Transcriptional Regulation by the AP-2 (TFAP2) Family of Transcription Factors: Calculation completed
RNA Polymerase II Preinitiation Complex Assembly (GO:0051123): Calculation started
RNA Polymerase II Preinitiation Complex Assembly (GO:0051123): scoring computed

Calculating pathways:  29%|██▉       | 88/299 [08:13<14:37,  4.16s/it]

RNA Polymerase II Preinitiation Complex Assembly (GO:0051123): pvalue calculation completed
RNA Polymerase II Preinitiation Complex Assembly (GO:0051123): Calculation completed
Action Potential (GO:0001508): Calculation started
Action Potential (GO:0001508): scoring computed

Calculating pathways:  30%|██▉       | 89/299 [08:17<14:31,  4.15s/it]

Action Potential (GO:0001508): pvalue calculation completed
Action Potential (GO:0001508): Calculation completed
Adenylate Cyclase-Activating G Protein-Coupled Receptor Signaling Pathway (GO:0007189): Calculation started
Adenylate Cyclase-Activating G Protein-Coupled Receptor Signaling Pathway (GO:0007189): scoring computed

Calculating pathways:  30%|███       | 90/299 [08:22<15:36,  4.48s/it]

Adenylate Cyclase-Activating G Protein-Coupled Receptor Signaling Pathway (GO:0007189): pvalue calculation completed
Adenylate Cyclase-Activating G Protein-Coupled Receptor Signaling Pathway (GO:0007189): Calculation completed
Adenylate Cyclase-Modulating G Protein-Coupled Receptor Signaling Pathway (GO:0007188): Calculation started
Adenylate Cyclase-Modulating G Protein-Coupled Receptor Signaling Pathway (GO:0007188): scoring computed

Calculating pathways:  30%|███       | 91/299 [08:28<16:54,  4.88s/it]

Adenylate Cyclase-Modulating G Protein-Coupled Receptor Signaling Pathway (GO:0007188): pvalue calculation completed
Adenylate Cyclase-Modulating G Protein-Coupled Receptor Signaling Pathway (GO:0007188): Calculation completed
Apoptotic Nuclear Changes (GO:0030262): Calculation started
Apoptotic Nuclear Changes (GO:0030262): scoring computed

Calculating pathways:  31%|███       | 92/299 [08:32<15:33,  4.51s/it]

Apoptotic Nuclear Changes (GO:0030262): pvalue calculation completed
Apoptotic Nuclear Changes (GO:0030262): Calculation completed
Bile Acid and Bile Salt Transport (GO:0015721): Calculation started
Bile Acid and Bile Salt Transport (GO:0015721): scoring computed

Calculating pathways:  31%|███       | 93/299 [08:36<14:40,  4.28s/it]

Bile Acid and Bile Salt Transport (GO:0015721): pvalue calculation completed
Bile Acid and Bile Salt Transport (GO:0015721): Calculation completed
Blood Vessel Diameter Maintenance (GO:0097746): Calculation started
Blood Vessel Diameter Maintenance (GO:0097746): scoring computed

Calculating pathways:  31%|███▏      | 94/299 [08:39<14:08,  4.14s/it]

Blood Vessel Diameter Maintenance (GO:0097746): pvalue calculation completed
Blood Vessel Diameter Maintenance (GO:0097746): Calculation completed
Cellular Response to Corticosteroid Stimulus (GO:0071384): Calculation started
Cellular Response to Corticosteroid Stimulus (GO:0071384): scoring computed

Calculating pathways:  32%|███▏      | 95/299 [08:43<13:40,  4.02s/it]

Cellular Response to Corticosteroid Stimulus (GO:0071384): pvalue calculation completed
Cellular Response to Corticosteroid Stimulus (GO:0071384): Calculation completed
Cellular Response to Cytokine Stimulus (GO:0071345): Calculation started
Cellular Response to Cytokine Stimulus (GO:0071345): scoring computed

Calculating pathways:  32%|███▏      | 96/299 [08:50<16:20,  4.83s/it]

Cellular Response to Cytokine Stimulus (GO:0071345): pvalue calculation completed
Cellular Response to Cytokine Stimulus (GO:0071345): Calculation completed
Cellular Response to Estradiol Stimulus (GO:0071392): Calculation started
Cellular Response to Estradiol Stimulus (GO:0071392): scoring computed

Calculating pathways:  32%|███▏      | 97/299 [08:54<15:01,  4.46s/it]

Cellular Response to Estradiol Stimulus (GO:0071392): pvalue calculation completed
Cellular Response to Estradiol Stimulus (GO:0071392): Calculation completed
Cellular Response to Estrogen Stimulus (GO:0071391): Calculation started
Cellular Response to Estrogen Stimulus (GO:0071391): scoring computed

Calculating pathways:  33%|███▎      | 98/299 [08:57<13:55,  4.16s/it]

Cellular Response to Estrogen Stimulus (GO:0071391): pvalue calculation completed
Cellular Response to Estrogen Stimulus (GO:0071391): Calculation completed
Cellular Response to Fatty Acid (GO:0071398): Calculation started
Cellular Response to Fatty Acid (GO:0071398): scoring computed

Calculating pathways:  33%|███▎      | 99/299 [09:01<13:15,  3.98s/it]

Cellular Response to Fatty Acid (GO:0071398): pvalue calculation completed
Cellular Response to Fatty Acid (GO:0071398): Calculation completed
Cellular Response to Glucose Stimulus (GO:0071333): Calculation started
Cellular Response to Glucose Stimulus (GO:0071333): scoring computed

Calculating pathways:  33%|███▎      | 100/299 [09:04<13:06,  3.95s/it]

Cellular Response to Glucose Stimulus (GO:0071333): pvalue calculation completed
Cellular Response to Glucose Stimulus (GO:0071333): Calculation completed
Cellular Response to Hexose Stimulus (GO:0071331): Calculation started
Cellular Response to Hexose Stimulus (GO:0071331): scoring computed

Calculating pathways:  34%|███▍      | 101/299 [09:08<12:49,  3.89s/it]

Cellular Response to Hexose Stimulus (GO:0071331): pvalue calculation completed
Cellular Response to Hexose Stimulus (GO:0071331): Calculation completed
Cellular Response to Hormone Stimulus (GO:0032870): Calculation started
Cellular Response to Hormone Stimulus (GO:0032870): scoring computed

Calculating pathways:  34%|███▍      | 102/299 [09:13<13:17,  4.05s/it]

Cellular Response to Hormone Stimulus (GO:0032870): pvalue calculation completed
Cellular Response to Hormone Stimulus (GO:0032870): Calculation completed
Cellular Response to Lipid (GO:0071396): Calculation started
Cellular Response to Lipid (GO:0071396): scoring computed

Calculating pathways:  34%|███▍      | 103/299 [09:18<14:47,  4.53s/it]

Cellular Response to Lipid (GO:0071396): pvalue calculation completed
Cellular Response to Lipid (GO:0071396): Calculation completed
Cellular Response to Molecule of Bacterial Origin (GO:0071219): Calculation started
Cellular Response to Molecule of Bacterial Origin (GO:0071219): scoring computed

Calculating pathways:  35%|███▍      | 104/299 [09:23<14:38,  4.50s/it]

Cellular Response to Molecule of Bacterial Origin (GO:0071219): pvalue calculation completed
Cellular Response to Molecule of Bacterial Origin (GO:0071219): Calculation completed
Cellular Response to Nitrogen Compound (GO:1901699): Calculation started
Cellular Response to Nitrogen Compound (GO:1901699): scoring computed

Calculating pathways:  35%|███▌      | 105/299 [09:28<15:18,  4.73s/it]

Cellular Response to Nitrogen Compound (GO:1901699): pvalue calculation completed
Cellular Response to Nitrogen Compound (GO:1901699): Calculation completed
Cellular Response to Oxygen-Containing Compound (GO:1901701): Calculation started
Cellular Response to Oxygen-Containing Compound (GO:1901701): scoring computed

Calculating pathways:  35%|███▌      | 106/299 [09:35<17:39,  5.49s/it]

Cellular Response to Oxygen-Containing Compound (GO:1901701): pvalue calculation completed
Cellular Response to Oxygen-Containing Compound (GO:1901701): Calculation completed
Cellular Response to Peptide Hormone Stimulus (GO:0071375): Calculation started
Cellular Response to Peptide Hormone Stimulus (GO:0071375): scoring computed

Calculating pathways:  36%|███▌      | 107/299 [09:40<16:27,  5.14s/it]

Cellular Response to Peptide Hormone Stimulus (GO:0071375): pvalue calculation completed
Cellular Response to Peptide Hormone Stimulus (GO:0071375): Calculation completed
Cellular Response to Steroid Hormone Stimulus (GO:0071383): Calculation started
Cellular Response to Steroid Hormone Stimulus (GO:0071383): scoring computed

Calculating pathways:  36%|███▌      | 108/299 [09:43<14:53,  4.68s/it]

Cellular Response to Steroid Hormone Stimulus (GO:0071383): pvalue calculation completed
Cellular Response to Steroid Hormone Stimulus (GO:0071383): Calculation completed
Cellular Response to Tumor Necrosis Factor (GO:0071356): Calculation started
Cellular Response to Tumor Necrosis Factor (GO:0071356): scoring computed

Calculating pathways:  36%|███▋      | 109/299 [09:47<14:24,  4.55s/it]

Cellular Response to Tumor Necrosis Factor (GO:0071356): pvalue calculation completed
Cellular Response to Tumor Necrosis Factor (GO:0071356): Calculation completed
Cholesterol Homeostasis (GO:0042632): Calculation started
Cholesterol Homeostasis (GO:0042632): scoring computed

Calculating pathways:  37%|███▋      | 110/299 [09:52<14:00,  4.45s/it]

Cholesterol Homeostasis (GO:0042632): pvalue calculation completed
Cholesterol Homeostasis (GO:0042632): Calculation completed
Chromatin Organization (GO:0006325): Calculation started
Chromatin Organization (GO:0006325): scoring computed

Calculating pathways:  37%|███▋      | 111/299 [09:58<16:09,  5.15s/it]

Chromatin Organization (GO:0006325): pvalue calculation completed
Chromatin Organization (GO:0006325): Calculation completed
Chromatin Remodeling (GO:0006338): Calculation started
Chromatin Remodeling (GO:0006338): scoring computed

Calculating pathways:  37%|███▋      | 112/299 [10:05<17:11,  5.51s/it]

Chromatin Remodeling (GO:0006338): pvalue calculation completed
Chromatin Remodeling (GO:0006338): Calculation completed
Chromosome Condensation (GO:0030261): Calculation started
Chromosome Condensation (GO:0030261): scoring computed

Calculating pathways:  38%|███▊      | 113/299 [10:08<15:19,  4.95s/it]

Chromosome Condensation (GO:0030261): pvalue calculation completed
Chromosome Condensation (GO:0030261): Calculation completed
Dephosphorylation (GO:0016311): Calculation started
Dephosphorylation (GO:0016311): scoring computed

Calculating pathways:  38%|███▊      | 114/299 [10:13<14:43,  4.78s/it]

Dephosphorylation (GO:0016311): pvalue calculation completed
Dephosphorylation (GO:0016311): Calculation completed
Estrogen Receptor Signaling Pathway (GO:0030520): Calculation started
Estrogen Receptor Signaling Pathway (GO:0030520): scoring computed

Calculating pathways:  38%|███▊      | 115/299 [10:16<13:26,  4.38s/it]

Estrogen Receptor Signaling Pathway (GO:0030520): pvalue calculation completed
Estrogen Receptor Signaling Pathway (GO:0030520): Calculation completed
Intracellular Calcium Ion Homeostasis (GO:0006874): Calculation started
Intracellular Calcium Ion Homeostasis (GO:0006874): scoring computed

Calculating pathways:  39%|███▉      | 116/299 [10:21<13:41,  4.49s/it]

Intracellular Calcium Ion Homeostasis (GO:0006874): pvalue calculation completed
Intracellular Calcium Ion Homeostasis (GO:0006874): Calculation completed
Intracellular Glucose Homeostasis (GO:0001678): Calculation started
Intracellular Glucose Homeostasis (GO:0001678): scoring computed

Calculating pathways:  39%|███▉      | 117/299 [10:25<13:13,  4.36s/it]

Intracellular Glucose Homeostasis (GO:0001678): pvalue calculation completed
Intracellular Glucose Homeostasis (GO:0001678): Calculation completed
Intracellular Receptor Signaling Pathway (GO:0030522): Calculation started
Intracellular Receptor Signaling Pathway (GO:0030522): scoring computed

Calculating pathways:  39%|███▉      | 118/299 [10:29<12:47,  4.24s/it]

Intracellular Receptor Signaling Pathway (GO:0030522): pvalue calculation completed
Intracellular Receptor Signaling Pathway (GO:0030522): Calculation completed
Intracellular Triglyceride Homeostasis (GO:0035356): Calculation started
Intracellular Triglyceride Homeostasis (GO:0035356): scoring computed

Calculating pathways:  40%|███▉      | 119/299 [10:32<11:55,  3.98s/it]

Intracellular Triglyceride Homeostasis (GO:0035356): pvalue calculation completed
Intracellular Triglyceride Homeostasis (GO:0035356): Calculation completed
Lipid Metabolic Process (GO:0006629): Calculation started
Lipid Metabolic Process (GO:0006629): scoring computed

Calculating pathways:  40%|████      | 120/299 [10:38<13:35,  4.55s/it]

Lipid Metabolic Process (GO:0006629): pvalue calculation completed
Lipid Metabolic Process (GO:0006629): Calculation completed
Lipid Modification (GO:0030258): Calculation started
Lipid Modification (GO:0030258): scoring computed

Calculating pathways:  40%|████      | 121/299 [10:42<12:49,  4.32s/it]

Lipid Modification (GO:0030258): pvalue calculation completed
Lipid Modification (GO:0030258): Calculation completed
Lipid Transport (GO:0006869): Calculation started
Lipid Transport (GO:0006869): scoring computed

Calculating pathways:  41%|████      | 122/299 [10:46<12:48,  4.34s/it]

Lipid Transport (GO:0006869): pvalue calculation completed
Lipid Transport (GO:0006869): Calculation completed
Maintenance of Gastrointestinal Epithelium (GO:0030277): Calculation started
Maintenance of Gastrointestinal Epithelium (GO:0030277): scoring computed

Calculating pathways:  41%|████      | 123/299 [10:50<11:58,  4.09s/it]

Maintenance of Gastrointestinal Epithelium (GO:0030277): pvalue calculation completed
Maintenance of Gastrointestinal Epithelium (GO:0030277): Calculation completed
Maintenance of Protein Localization in Organelle (GO:0072595): Calculation started
Maintenance of Protein Localization in Organelle (GO:0072595): scoring computed

Calculating pathways:  41%|████▏     | 124/299 [10:54<11:28,  3.93s/it]

Maintenance of Protein Localization in Organelle (GO:0072595): pvalue calculation completed
Maintenance of Protein Localization in Organelle (GO:0072595): Calculation completed
Maintenance of Protein Location in Nucleus (GO:0051457): Calculation started
Maintenance of Protein Location in Nucleus (GO:0051457): scoring computed

Calculating pathways:  42%|████▏     | 125/299 [10:57<11:02,  3.81s/it]

Maintenance of Protein Location in Nucleus (GO:0051457): pvalue calculation completed
Maintenance of Protein Location in Nucleus (GO:0051457): Calculation completed
Monocarboxylic Acid Transport (GO:0015718): Calculation started
Monocarboxylic Acid Transport (GO:0015718): scoring computed

Calculating pathways:  42%|████▏     | 126/299 [11:01<11:09,  3.87s/it]

Monocarboxylic Acid Transport (GO:0015718): pvalue calculation completed
Monocarboxylic Acid Transport (GO:0015718): Calculation completed
Negative Regulation of DNA-binding Transcription Factor Activity (GO:0043433): Calculation started
Negative Regulation of DNA-binding Transcription Factor Activity (GO:0043433): scoring computed

Calculating pathways:  42%|████▏     | 127/299 [11:06<11:44,  4.10s/it]

Negative Regulation of DNA-binding Transcription Factor Activity (GO:0043433): pvalue calculation completed
Negative Regulation of DNA-binding Transcription Factor Activity (GO:0043433): Calculation completed
Negative Regulation of DNA-templated Transcription (GO:0045892): Calculation started
Negative Regulation of DNA-templated Transcription (GO:0045892): scoring computed

Calculating pathways:  43%|████▎     | 128/299 [11:19<19:27,  6.83s/it]

Negative Regulation of DNA-templated Transcription (GO:0045892): pvalue calculation completed
Negative Regulation of DNA-templated Transcription (GO:0045892): Calculation completed
Negative Regulation of ERK1 and ERK2 Cascade (GO:0070373): Calculation started
Negative Regulation of ERK1 and ERK2 Cascade (GO:0070373): scoring computed

Calculating pathways:  43%|████▎     | 129/299 [11:23<16:46,  5.92s/it]

Negative Regulation of ERK1 and ERK2 Cascade (GO:0070373): pvalue calculation completed
Negative Regulation of ERK1 and ERK2 Cascade (GO:0070373): Calculation completed
Negative Regulation of MAPK Cascade (GO:0043409): Calculation started
Negative Regulation of MAPK Cascade (GO:0043409): scoring computed

Calculating pathways:  43%|████▎     | 130/299 [11:27<15:44,  5.59s/it]

Negative Regulation of MAPK Cascade (GO:0043409): pvalue calculation completed
Negative Regulation of MAPK Cascade (GO:0043409): Calculation completed
Negative Regulation of RNA Biosynthetic Process (GO:1902679): Calculation started
Negative Regulation of RNA Biosynthetic Process (GO:1902679): scoring computed

Calculating pathways:  44%|████▍     | 131/299 [11:36<17:49,  6.37s/it]

Negative Regulation of RNA Biosynthetic Process (GO:1902679): pvalue calculation completed
Negative Regulation of RNA Biosynthetic Process (GO:1902679): Calculation completed
Negative Regulation of Apoptotic Process (GO:0043066): Calculation started
Negative Regulation of Apoptotic Process (GO:0043066): scoring computed

Calculating pathways:  44%|████▍     | 132/299 [11:44<19:14,  6.91s/it]

Negative Regulation of Apoptotic Process (GO:0043066): pvalue calculation completed
Negative Regulation of Apoptotic Process (GO:0043066): Calculation completed
Negative Regulation of Biosynthetic Process (GO:0009890): Calculation started
Negative Regulation of Biosynthetic Process (GO:0009890): scoring computed

Calculating pathways:  44%|████▍     | 133/299 [11:48<16:39,  6.02s/it]

Negative Regulation of Biosynthetic Process (GO:0009890): pvalue calculation completed
Negative Regulation of Biosynthetic Process (GO:0009890): Calculation completed
Negative Regulation of Canonical NF-kappaB Signal Transduction (GO:0043124): Calculation started
Negative Regulation of Canonical NF-kappaB Signal Transduction (GO:0043124): scoring computed

Calculating pathways:  45%|████▍     | 134/299 [11:52<14:50,  5.40s/it]

Negative Regulation of Canonical NF-kappaB Signal Transduction (GO:0043124): pvalue calculation completed
Negative Regulation of Canonical NF-kappaB Signal Transduction (GO:0043124): Calculation completed
Negative Regulation of Cell Activation (GO:0050866): Calculation started
Negative Regulation of Cell Activation (GO:0050866): scoring computed

Calculating pathways:  45%|████▌     | 135/299 [11:55<13:11,  4.83s/it]

Negative Regulation of Cell Activation (GO:0050866): pvalue calculation completed
Negative Regulation of Cell Activation (GO:0050866): Calculation completed
Negative Regulation of Cell Cycle (GO:0045786): Calculation started
Negative Regulation of Cell Cycle (GO:0045786): scoring computed

Calculating pathways:  45%|████▌     | 136/299 [11:59<12:34,  4.63s/it]

Negative Regulation of Cell Cycle (GO:0045786): pvalue calculation completed
Negative Regulation of Cell Cycle (GO:0045786): Calculation completed
Negative Regulation of Cell Cycle Process (GO:0010948): Calculation started
Negative Regulation of Cell Cycle Process (GO:0010948): scoring computed

Calculating pathways:  46%|████▌     | 137/299 [12:03<11:43,  4.34s/it]

Negative Regulation of Cell Cycle Process (GO:0010948): pvalue calculation completed
Negative Regulation of Cell Cycle Process (GO:0010948): Calculation completed
Negative Regulation of Cell Differentiation (GO:0045596): Calculation started
Negative Regulation of Cell Differentiation (GO:0045596): scoring computed

Calculating pathways:  46%|████▌     | 138/299 [12:09<12:44,  4.75s/it]

Negative Regulation of Cell Differentiation (GO:0045596): pvalue calculation completed
Negative Regulation of Cell Differentiation (GO:0045596): Calculation completed
Negative Regulation of Cell Growth (GO:0030308): Calculation started
Negative Regulation of Cell Growth (GO:0030308): scoring computed

Calculating pathways:  46%|████▋     | 139/299 [12:13<12:34,  4.72s/it]

Negative Regulation of Cell Growth (GO:0030308): pvalue calculation completed
Negative Regulation of Cell Growth (GO:0030308): Calculation completed
Negative Regulation of Cell Population Proliferation (GO:0008285): Calculation started
Negative Regulation of Cell Population Proliferation (GO:0008285): scoring computed

Calculating pathways:  47%|████▋     | 140/299 [12:21<14:31,  5.48s/it]

Negative Regulation of Cell Population Proliferation (GO:0008285): pvalue calculation completed
Negative Regulation of Cell Population Proliferation (GO:0008285): Calculation completed
Negative Regulation of Cellular Component Organization (GO:0051129): Calculation started
Negative Regulation of Cellular Component Organization (GO:0051129): scoring computed

Calculating pathways:  47%|████▋     | 141/299 [12:25<13:18,  5.05s/it]

Negative Regulation of Cellular Component Organization (GO:0051129): pvalue calculation completed
Negative Regulation of Cellular Component Organization (GO:0051129): Calculation completed
Negative Regulation of Cellular Process (GO:0048523): Calculation started
Negative Regulation of Cellular Process (GO:0048523): scoring computed

Calculating pathways:  47%|████▋     | 142/299 [12:33<16:02,  6.13s/it]

Negative Regulation of Cellular Process (GO:0048523): pvalue calculation completed
Negative Regulation of Cellular Process (GO:0048523): Calculation completed
Negative Regulation of Cytokine Production (GO:0001818): Calculation started
Negative Regulation of Cytokine Production (GO:0001818): scoring computed

Calculating pathways:  48%|████▊     | 143/299 [12:39<15:19,  5.89s/it]

Negative Regulation of Cytokine Production (GO:0001818): pvalue calculation completed
Negative Regulation of Cytokine Production (GO:0001818): Calculation completed
Negative Regulation of Defense Response (GO:0031348): Calculation started
Negative Regulation of Defense Response (GO:0031348): scoring computed

Calculating pathways:  48%|████▊     | 144/299 [12:43<14:11,  5.50s/it]

Negative Regulation of Defense Response (GO:0031348): pvalue calculation completed
Negative Regulation of Defense Response (GO:0031348): Calculation completed
Negative Regulation of Fat Cell Differentiation (GO:0045599): Calculation started
Negative Regulation of Fat Cell Differentiation (GO:0045599): scoring computed

Calculating pathways:  48%|████▊     | 145/299 [12:47<12:39,  4.93s/it]

Negative Regulation of Fat Cell Differentiation (GO:0045599): pvalue calculation completed
Negative Regulation of Fat Cell Differentiation (GO:0045599): Calculation completed
Negative Regulation of Gene Expression (GO:0010629): Calculation started
Negative Regulation of Gene Expression (GO:0010629): scoring computed

Calculating pathways:  49%|████▉     | 146/299 [12:54<14:19,  5.62s/it]

Negative Regulation of Gene Expression (GO:0010629): pvalue calculation completed
Negative Regulation of Gene Expression (GO:0010629): Calculation completed
Negative Regulation of Growth (GO:0045926): Calculation started
Negative Regulation of Growth (GO:0045926): scoring computed

Calculating pathways:  49%|████▉     | 147/299 [12:59<13:32,  5.34s/it]

Negative Regulation of Growth (GO:0045926): pvalue calculation completed
Negative Regulation of Growth (GO:0045926): Calculation completed
Negative Regulation of Immune System Process (GO:0002683): Calculation started
Negative Regulation of Immune System Process (GO:0002683): scoring computed

Calculating pathways:  49%|████▉     | 148/299 [13:03<12:23,  4.92s/it]

Negative Regulation of Immune System Process (GO:0002683): pvalue calculation completed
Negative Regulation of Immune System Process (GO:0002683): Calculation completed
Negative Regulation of Inflammatory Response (GO:0050728): Calculation started
Negative Regulation of Inflammatory Response (GO:0050728): scoring computed

Calculating pathways:  50%|████▉     | 149/299 [13:07<12:03,  4.82s/it]

Negative Regulation of Inflammatory Response (GO:0050728): pvalue calculation completed
Negative Regulation of Inflammatory Response (GO:0050728): Calculation completed
Negative Regulation of Intracellular Signal Transduction (GO:1902532): Calculation started
Negative Regulation of Intracellular Signal Transduction (GO:1902532): scoring computed

Calculating pathways:  50%|█████     | 150/299 [13:14<13:16,  5.35s/it]

Negative Regulation of Intracellular Signal Transduction (GO:1902532): pvalue calculation completed
Negative Regulation of Intracellular Signal Transduction (GO:1902532): Calculation completed
Negative Regulation of Leukocyte Activation (GO:0002695): Calculation started
Negative Regulation of Leukocyte Activation (GO:0002695): scoring computed

Calculating pathways:  51%|█████     | 151/299 [13:18<12:01,  4.87s/it]

Negative Regulation of Leukocyte Activation (GO:0002695): pvalue calculation completed
Negative Regulation of Leukocyte Activation (GO:0002695): Calculation completed
Negative Regulation of Lipid Biosynthetic Process (GO:0051055): Calculation started
Negative Regulation of Lipid Biosynthetic Process (GO:0051055): scoring computed

Calculating pathways:  51%|█████     | 152/299 [13:21<10:56,  4.47s/it]

Negative Regulation of Lipid Biosynthetic Process (GO:0051055): pvalue calculation completed
Negative Regulation of Lipid Biosynthetic Process (GO:0051055): Calculation completed
Negative Regulation of Lipid Metabolic Process (GO:0045833): Calculation started
Negative Regulation of Lipid Metabolic Process (GO:0045833): scoring computed

Calculating pathways:  51%|█████     | 153/299 [13:25<10:19,  4.24s/it]

Negative Regulation of Lipid Metabolic Process (GO:0045833): pvalue calculation completed
Negative Regulation of Lipid Metabolic Process (GO:0045833): Calculation completed
Negative Regulation of Macromolecule Biosynthetic Process (GO:0010558): Calculation started
Negative Regulation of Macromolecule Biosynthetic Process (GO:0010558): scoring computed

Calculating pathways:  52%|█████▏    | 154/299 [13:30<11:10,  4.63s/it]

Negative Regulation of Macromolecule Biosynthetic Process (GO:0010558): pvalue calculation completed
Negative Regulation of Macromolecule Biosynthetic Process (GO:0010558): Calculation completed
Negative Regulation of miRNA Metabolic Process (GO:2000629): Calculation started
Negative Regulation of miRNA Metabolic Process (GO:2000629): scoring computed

Calculating pathways:  52%|█████▏    | 155/299 [13:34<10:29,  4.37s/it]

Negative Regulation of miRNA Metabolic Process (GO:2000629): pvalue calculation completed
Negative Regulation of miRNA Metabolic Process (GO:2000629): Calculation completed
Negative Regulation of miRNA Transcription (GO:1902894): Calculation started
Negative Regulation of miRNA Transcription (GO:1902894): scoring computed

Calculating pathways:  52%|█████▏    | 156/299 [13:38<10:02,  4.21s/it]

Negative Regulation of miRNA Transcription (GO:1902894): pvalue calculation completed
Negative Regulation of miRNA Transcription (GO:1902894): Calculation completed
Negative Regulation of Multicellular Organismal Process (GO:0051241): Calculation started
Negative Regulation of Multicellular Organismal Process (GO:0051241): scoring computed

Calculating pathways:  53%|█████▎    | 157/299 [13:44<11:11,  4.73s/it]

Negative Regulation of Multicellular Organismal Process (GO:0051241): pvalue calculation completed
Negative Regulation of Multicellular Organismal Process (GO:0051241): Calculation completed
Negative Regulation of Muscle Cell Apoptotic Process (GO:0010656): Calculation started
Negative Regulation of Muscle Cell Apoptotic Process (GO:0010656): scoring computed

Calculating pathways:  53%|█████▎    | 158/299 [13:47<10:11,  4.34s/it]

Negative Regulation of Muscle Cell Apoptotic Process (GO:0010656): pvalue calculation completed
Negative Regulation of Muscle Cell Apoptotic Process (GO:0010656): Calculation completed
- Reg of Phosphatidylinositol 3-Kinase/Prot Kinase B Signal Transduction (GO:0051898): Calculation started
- Reg of Phosphatidylinositol 3-Kinase/Prot Kinase B Signal Transduction (GO:0051898): scoring computed

Calculating pathways:  53%|█████▎    | 159/299 [13:51<09:42,  4.16s/it]

- Reg of Phosphatidylinositol 3-Kinase/Prot Kinase B Signal Transduction (GO:0051898): pvalue calculation completed
- Reg of Phosphatidylinositol 3-Kinase/Prot Kinase B Signal Transduction (GO:0051898): Calculation completed
Negative Regulation of Programmed Cell Death (GO:0043069): Calculation started
Negative Regulation of Programmed Cell Death (GO:0043069): scoring computed

Calculating pathways:  54%|█████▎    | 160/299 [13:59<11:51,  5.12s/it]

Negative Regulation of Programmed Cell Death (GO:0043069): pvalue calculation completed
Negative Regulation of Programmed Cell Death (GO:0043069): Calculation completed
Negative Regulation of Response to External Stimulus (GO:0032102): Calculation started
Negative Regulation of Response to External Stimulus (GO:0032102): scoring computed

Calculating pathways:  54%|█████▍    | 161/299 [14:03<11:37,  5.05s/it]

Negative Regulation of Response to External Stimulus (GO:0032102): pvalue calculation completed
Negative Regulation of Response to External Stimulus (GO:0032102): Calculation completed
Negative Regulation of Smooth Muscle Cell Apoptotic Process (GO:0034392): Calculation started
Negative Regulation of Smooth Muscle Cell Apoptotic Process (GO:0034392): scoring computed

Calculating pathways:  54%|█████▍    | 162/299 [14:07<10:27,  4.58s/it]

Negative Regulation of Smooth Muscle Cell Apoptotic Process (GO:0034392): pvalue calculation completed
Negative Regulation of Smooth Muscle Cell Apoptotic Process (GO:0034392): Calculation completed
Negative Regulation of Smooth Muscle Cell Proliferation (GO:0048662): Calculation started
Negative Regulation of Smooth Muscle Cell Proliferation (GO:0048662): scoring computed

Calculating pathways:  55%|█████▍    | 163/299 [14:11<09:51,  4.35s/it]

Negative Regulation of Smooth Muscle Cell Proliferation (GO:0048662): pvalue calculation completed
Negative Regulation of Smooth Muscle Cell Proliferation (GO:0048662): Calculation completed
Negative Regulation of Transcription by RNA Polymerase II (GO:0000122): Calculation started
Negative Regulation of Transcription by RNA Polymerase II (GO:0000122): scoring computed

Calculating pathways:  55%|█████▍    | 164/299 [14:21<13:59,  6.22s/it]

Negative Regulation of Transcription by RNA Polymerase II (GO:0000122): pvalue calculation completed
Negative Regulation of Transcription by RNA Polymerase II (GO:0000122): Calculation completed
Negative Regulation of Tumor Necrosis Factor Production (GO:0032720): Calculation started
Negative Regulation of Tumor Necrosis Factor Production (GO:0032720): scoring computed

Calculating pathways:  55%|█████▌    | 165/299 [14:25<12:18,  5.51s/it]

Negative Regulation of Tumor Necrosis Factor Production (GO:0032720): pvalue calculation completed
Negative Regulation of Tumor Necrosis Factor Production (GO:0032720): Calculation completed
Negative Regulation of Tumor Necrosis Factor Superfamily Cytokine Production (GO:1903556): Calculation started
Negative Regulation of Tumor Necrosis Factor Superfamily Cytokine Production (GO:1903556): scoring computed

Calculating pathways:  56%|█████▌    | 166/299 [14:29<11:11,  5.05s/it]

Negative Regulation of Tumor Necrosis Factor Superfamily Cytokine Production (GO:1903556): pvalue calculation completed
Negative Regulation of Tumor Necrosis Factor Superfamily Cytokine Production (GO:1903556): Calculation completed
Negative Regulation of Type II Interferon Production (GO:0032689): Calculation started
Negative Regulation of Type II Interferon Production (GO:0032689): scoring computed

Calculating pathways:  56%|█████▌    | 167/299 [14:33<10:15,  4.66s/it]

Negative Regulation of Type II Interferon Production (GO:0032689): pvalue calculation completed
Negative Regulation of Type II Interferon Production (GO:0032689): Calculation completed
Negative Regulation of Vascular Associated Smooth Muscle Cell Proliferation (GO:1904706): Calculation started
Negative Regulation of Vascular Associated Smooth Muscle Cell Proliferation (GO:1904706): scoring computed

Calculating pathways:  56%|█████▌    | 168/299 [14:36<09:26,  4.32s/it]

Negative Regulation of Vascular Associated Smooth Muscle Cell Proliferation (GO:1904706): pvalue calculation completed
Negative Regulation of Vascular Associated Smooth Muscle Cell Proliferation (GO:1904706): Calculation completed
Neuronal Action Potential (GO:0019228): Calculation started
Neuronal Action Potential (GO:0019228): scoring computed

Calculating pathways:  57%|█████▋    | 169/299 [14:40<08:49,  4.07s/it]

Neuronal Action Potential (GO:0019228): pvalue calculation completed
Neuronal Action Potential (GO:0019228): Calculation completed
Nuclear Membrane Organization (GO:0071763): Calculation started
Nuclear Membrane Organization (GO:0071763): scoring computed

Calculating pathways:  57%|█████▋    | 170/299 [14:43<08:27,  3.93s/it]

Nuclear Membrane Organization (GO:0071763): pvalue calculation completed
Nuclear Membrane Organization (GO:0071763): Calculation completed
Nuclear Receptor-Mediated Signaling Pathway (GO:0141193): Calculation started
Nuclear Receptor-Mediated Signaling Pathway (GO:0141193): scoring computed

Calculating pathways:  57%|█████▋    | 171/299 [14:47<08:11,  3.84s/it]

Nuclear Receptor-Mediated Signaling Pathway (GO:0141193): pvalue calculation completed
Nuclear Receptor-Mediated Signaling Pathway (GO:0141193): Calculation completed
Nuclear Receptor-Mediated Steroid Hormone Signaling Pathway (GO:0030518): Calculation started
Nuclear Receptor-Mediated Steroid Hormone Signaling Pathway (GO:0030518): scoring computed

Calculating pathways:  58%|█████▊    | 172/299 [14:51<08:03,  3.81s/it]

Nuclear Receptor-Mediated Steroid Hormone Signaling Pathway (GO:0030518): pvalue calculation completed
Nuclear Receptor-Mediated Steroid Hormone Signaling Pathway (GO:0030518): Calculation completed
Organic Hydroxy Compound Transport (GO:0015850): Calculation started
Organic Hydroxy Compound Transport (GO:0015850): scoring computed

Calculating pathways:  58%|█████▊    | 173/299 [14:55<08:00,  3.81s/it]

Organic Hydroxy Compound Transport (GO:0015850): pvalue calculation completed
Organic Hydroxy Compound Transport (GO:0015850): Calculation completed
Phosphate-Containing Compound Metabolic Process (GO:0006796): Calculation started
Phosphate-Containing Compound Metabolic Process (GO:0006796): scoring computed

Calculating pathways:  58%|█████▊    | 174/299 [15:00<08:38,  4.15s/it]

Phosphate-Containing Compound Metabolic Process (GO:0006796): pvalue calculation completed
Phosphate-Containing Compound Metabolic Process (GO:0006796): Calculation completed
Phospholipase C-activating G Protein-Coupled Receptor Signaling Pathway (GO:0007200): Calculation started
Phospholipase C-activating G Protein-Coupled Receptor Signaling Pathway (GO:0007200): scoring computed

Calculating pathways:  59%|█████▊    | 175/299 [15:04<08:47,  4.26s/it]

Phospholipase C-activating G Protein-Coupled Receptor Signaling Pathway (GO:0007200): pvalue calculation completed
Phospholipase C-activating G Protein-Coupled Receptor Signaling Pathway (GO:0007200): Calculation completed
Positive Regulation of DNA-binding Transcription Factor Activity (GO:0051091): Calculation started
Positive Regulation of DNA-binding Transcription Factor Activity (GO:0051091): scoring computed

Calculating pathways:  59%|█████▉    | 176/299 [15:09<09:14,  4.51s/it]

Positive Regulation of DNA-binding Transcription Factor Activity (GO:0051091): pvalue calculation completed
Positive Regulation of DNA-binding Transcription Factor Activity (GO:0051091): Calculation completed
Positive Regulation of DNA-templated Transcription (GO:0045893): Calculation started
Positive Regulation of DNA-templated Transcription (GO:0045893): scoring computed

Calculating pathways:  59%|█████▉    | 177/299 [15:25<15:54,  7.83s/it]

Positive Regulation of DNA-templated Transcription (GO:0045893): pvalue calculation completed
Positive Regulation of DNA-templated Transcription (GO:0045893): Calculation completed
Positive Regulation of ERBB Signaling Pathway (GO:1901186): Calculation started
Positive Regulation of ERBB Signaling Pathway (GO:1901186): scoring computed

Calculating pathways:  60%|█████▉    | 178/299 [15:28<13:16,  6.58s/it]

Positive Regulation of ERBB Signaling Pathway (GO:1901186): pvalue calculation completed
Positive Regulation of ERBB Signaling Pathway (GO:1901186): Calculation completed
Positive Regulation of ERK1 and ERK2 Cascade (GO:0070374): Calculation started
Positive Regulation of ERK1 and ERK2 Cascade (GO:0070374): scoring computed

Calculating pathways:  60%|█████▉    | 179/299 [15:34<12:15,  6.13s/it]

Positive Regulation of ERK1 and ERK2 Cascade (GO:0070374): pvalue calculation completed
Positive Regulation of ERK1 and ERK2 Cascade (GO:0070374): Calculation completed
Positive Regulation of G Protein-Coupled Receptor Signaling Pathway (GO:0045745): Calculation started
Positive Regulation of G Protein-Coupled Receptor Signaling Pathway (GO:0045745): scoring computed

Calculating pathways:  60%|██████    | 180/299 [15:37<10:35,  5.34s/it]

Positive Regulation of G Protein-Coupled Receptor Signaling Pathway (GO:0045745): pvalue calculation completed
Positive Regulation of G Protein-Coupled Receptor Signaling Pathway (GO:0045745): Calculation completed
Positive Regulation of MAPK Cascade (GO:0043410): Calculation started
Positive Regulation of MAPK Cascade (GO:0043410): scoring computed

Calculating pathways:  61%|██████    | 181/299 [15:44<11:28,  5.84s/it]

Positive Regulation of MAPK Cascade (GO:0043410): pvalue calculation completed
Positive Regulation of MAPK Cascade (GO:0043410): Calculation completed
Positive Regulation of RNA Biosynthetic Process (GO:1902680): Calculation started
Positive Regulation of RNA Biosynthetic Process (GO:1902680): scoring computed

Calculating pathways:  61%|██████    | 182/299 [15:53<13:11,  6.76s/it]

Positive Regulation of RNA Biosynthetic Process (GO:1902680): pvalue calculation completed
Positive Regulation of RNA Biosynthetic Process (GO:1902680): Calculation completed
Positive Regulation of Apoptotic Process (GO:0043065): Calculation started
Positive Regulation of Apoptotic Process (GO:0043065): scoring computed

Calculating pathways:  61%|██████    | 183/299 [15:59<12:56,  6.69s/it]

Positive Regulation of Apoptotic Process (GO:0043065): pvalue calculation completed
Positive Regulation of Apoptotic Process (GO:0043065): Calculation completed
Positive Regulation of Apoptotic Signaling Pathway (GO:2001235): Calculation started
Positive Regulation of Apoptotic Signaling Pathway (GO:2001235): scoring computed

Calculating pathways:  62%|██████▏   | 184/299 [16:04<11:23,  5.95s/it]

Positive Regulation of Apoptotic Signaling Pathway (GO:2001235): pvalue calculation completed
Positive Regulation of Apoptotic Signaling Pathway (GO:2001235): Calculation completed
Positive Regulation of Biosynthetic Process (GO:0009891): Calculation started
Positive Regulation of Biosynthetic Process (GO:0009891): scoring computed

Calculating pathways:  62%|██████▏   | 185/299 [16:08<10:22,  5.46s/it]

Positive Regulation of Biosynthetic Process (GO:0009891): pvalue calculation completed
Positive Regulation of Biosynthetic Process (GO:0009891): Calculation completed
Positive Regulation of Calcium Ion Transmembrane Transport (GO:1904427): Calculation started
Positive Regulation of Calcium Ion Transmembrane Transport (GO:1904427): scoring computed

Calculating pathways:  62%|██████▏   | 186/299 [16:12<09:23,  4.98s/it]

Positive Regulation of Calcium Ion Transmembrane Transport (GO:1904427): pvalue calculation completed
Positive Regulation of Calcium Ion Transmembrane Transport (GO:1904427): Calculation completed
Positive Regulation of Cardiocyte Differentiation (GO:1905209): Calculation started
Positive Regulation of Cardiocyte Differentiation (GO:1905209): scoring computed

Calculating pathways:  63%|██████▎   | 187/299 [16:15<08:29,  4.55s/it]

Positive Regulation of Cardiocyte Differentiation (GO:1905209): pvalue calculation completed
Positive Regulation of Cardiocyte Differentiation (GO:1905209): Calculation completed
Positive Regulation of Cell Development (GO:0010720): Calculation started
Positive Regulation of Cell Development (GO:0010720): scoring computed

Calculating pathways:  63%|██████▎   | 188/299 [16:19<07:56,  4.30s/it]

Positive Regulation of Cell Development (GO:0010720): pvalue calculation completed
Positive Regulation of Cell Development (GO:0010720): Calculation completed
Positive Regulation of Cell Migration (GO:0030335): Calculation started
Positive Regulation of Cell Migration (GO:0030335): scoring computed

Calculating pathways:  63%|██████▎   | 189/299 [16:26<09:17,  5.07s/it]

Positive Regulation of Cell Migration (GO:0030335): pvalue calculation completed
Positive Regulation of Cell Migration (GO:0030335): Calculation completed
Positive Regulation of Cell Motility (GO:2000147): Calculation started
Positive Regulation of Cell Motility (GO:2000147): scoring computed

Calculating pathways:  64%|██████▎   | 190/299 [16:32<09:40,  5.32s/it]

Positive Regulation of Cell Motility (GO:2000147): pvalue calculation completed
Positive Regulation of Cell Motility (GO:2000147): Calculation completed
Positive Regulation of Cell Population Proliferation (GO:0008284): Calculation started
Positive Regulation of Cell Population Proliferation (GO:0008284): scoring computed

Calculating pathways:  64%|██████▍   | 191/299 [16:40<10:59,  6.11s/it]

Positive Regulation of Cell Population Proliferation (GO:0008284): pvalue calculation completed
Positive Regulation of Cell Population Proliferation (GO:0008284): Calculation completed
Positive Regulation of Cellular Process (GO:0048522): Calculation started
Positive Regulation of Cellular Process (GO:0048522): scoring computed

Calculating pathways:  64%|██████▍   | 192/299 [16:49<12:32,  7.04s/it]

Positive Regulation of Cellular Process (GO:0048522): pvalue calculation completed
Positive Regulation of Cellular Process (GO:0048522): Calculation completed
Positive Regulation of Cytokine Production (GO:0001819): Calculation started
Positive Regulation of Cytokine Production (GO:0001819): scoring computed

Calculating pathways:  65%|██████▍   | 193/299 [16:56<12:08,  6.87s/it]

Positive Regulation of Cytokine Production (GO:0001819): pvalue calculation completed
Positive Regulation of Cytokine Production (GO:0001819): Calculation completed
Positive Regulation of Endothelial Cell Apoptotic Process (GO:2000353): Calculation started
Positive Regulation of Endothelial Cell Apoptotic Process (GO:2000353): scoring computed

Calculating pathways:  65%|██████▍   | 194/299 [16:59<10:13,  5.85s/it]

Positive Regulation of Endothelial Cell Apoptotic Process (GO:2000353): pvalue calculation completed
Positive Regulation of Endothelial Cell Apoptotic Process (GO:2000353): Calculation completed
Positive Regulation of Epidermal Growth Factor Receptor Signaling Pathway (GO:0045742): Calculation started
Positive Regulation of Epidermal Growth Factor Receptor Signaling Pathway (GO:0045742): scoring computed

Calculating pathways:  65%|██████▌   | 195/299 [17:03<08:56,  5.16s/it]

Positive Regulation of Epidermal Growth Factor Receptor Signaling Pathway (GO:0045742): pvalue calculation completed
Positive Regulation of Epidermal Growth Factor Receptor Signaling Pathway (GO:0045742): Calculation completed
Positive Regulation of Extrinsic Apoptotic Signaling Pathway (GO:2001238): Calculation started
Positive Regulation of Extrinsic Apoptotic Signaling Pathway (GO:2001238): scoring computed

Calculating pathways:  66%|██████▌   | 196/299 [17:06<08:06,  4.73s/it]

Positive Regulation of Extrinsic Apoptotic Signaling Pathway (GO:2001238): pvalue calculation completed
Positive Regulation of Extrinsic Apoptotic Signaling Pathway (GO:2001238): Calculation completed
Positive Regulation of Gene Expression (GO:0010628): Calculation started
Positive Regulation of Gene Expression (GO:0010628): scoring computed

Calculating pathways:  66%|██████▌   | 197/299 [17:14<09:32,  5.61s/it]

Positive Regulation of Gene Expression (GO:0010628): pvalue calculation completed
Positive Regulation of Gene Expression (GO:0010628): Calculation completed
Positive Regulation of Inositol Phosphate Biosynthetic Process (GO:0060732): Calculation started
Positive Regulation of Inositol Phosphate Biosynthetic Process (GO:0060732): scoring computed

Calculating pathways:  66%|██████▌   | 198/299 [17:17<08:16,  4.92s/it]

Positive Regulation of Inositol Phosphate Biosynthetic Process (GO:0060732): pvalue calculation completed
Positive Regulation of Inositol Phosphate Biosynthetic Process (GO:0060732): Calculation completed
Positive Regulation of Insulin Secretion (GO:0032024): Calculation started
Positive Regulation of Insulin Secretion (GO:0032024): scoring computed

Calculating pathways:  67%|██████▋   | 199/299 [17:21<07:39,  4.59s/it]

Positive Regulation of Insulin Secretion (GO:0032024): pvalue calculation completed
Positive Regulation of Insulin Secretion (GO:0032024): Calculation completed
Positive Regulation of Interleukin-17 Production (GO:0032740): Calculation started
Positive Regulation of Interleukin-17 Production (GO:0032740): scoring computed

Calculating pathways:  67%|██████▋   | 200/299 [17:25<07:01,  4.26s/it]

Positive Regulation of Interleukin-17 Production (GO:0032740): pvalue calculation completed
Positive Regulation of Interleukin-17 Production (GO:0032740): Calculation completed
Positive Regulation of Intracellular Signal Transduction (GO:1902533): Calculation started
Positive Regulation of Intracellular Signal Transduction (GO:1902533): scoring computed

Calculating pathways:  67%|██████▋   | 201/299 [17:34<09:43,  5.95s/it]

Positive Regulation of Intracellular Signal Transduction (GO:1902533): pvalue calculation completed
Positive Regulation of Intracellular Signal Transduction (GO:1902533): Calculation completed
Positive Regulation of Macromolecule Biosynthetic Process (GO:0010557): Calculation started
Positive Regulation of Macromolecule Biosynthetic Process (GO:0010557): scoring computed

Calculating pathways:  68%|██████▊   | 202/299 [17:41<10:00,  6.19s/it]

Positive Regulation of Macromolecule Biosynthetic Process (GO:0010557): pvalue calculation completed
Positive Regulation of Macromolecule Biosynthetic Process (GO:0010557): Calculation completed
Positive Regulation of Monooxygenase Activity (GO:0032770): Calculation started
Positive Regulation of Monooxygenase Activity (GO:0032770): scoring computed

Calculating pathways:  68%|██████▊   | 203/299 [17:45<08:35,  5.37s/it]

Positive Regulation of Monooxygenase Activity (GO:0032770): pvalue calculation completed
Positive Regulation of Monooxygenase Activity (GO:0032770): Calculation completed
Positive Regulation of Nervous System Development (GO:0051962): Calculation started
Positive Regulation of Nervous System Development (GO:0051962): scoring computed

Calculating pathways:  68%|██████▊   | 204/299 [17:48<07:46,  4.91s/it]

Positive Regulation of Nervous System Development (GO:0051962): pvalue calculation completed
Positive Regulation of Nervous System Development (GO:0051962): Calculation completed
Positive Regulation of Neurogenesis (GO:0050769): Calculation started
Positive Regulation of Neurogenesis (GO:0050769): scoring computed

Calculating pathways:  69%|██████▊   | 205/299 [17:52<07:14,  4.62s/it]

Positive Regulation of Neurogenesis (GO:0050769): pvalue calculation completed
Positive Regulation of Neurogenesis (GO:0050769): Calculation completed
Positive Regulation of Neurotransmitter Secretion (GO:0001956): Calculation started
Positive Regulation of Neurotransmitter Secretion (GO:0001956): scoring computed

Calculating pathways:  69%|██████▉   | 206/299 [17:56<06:36,  4.26s/it]

Positive Regulation of Neurotransmitter Secretion (GO:0001956): pvalue calculation completed
Positive Regulation of Neurotransmitter Secretion (GO:0001956): Calculation completed
Positive Regulation of Neurotransmitter Transport (GO:0051590): Calculation started
Positive Regulation of Neurotransmitter Transport (GO:0051590): scoring computed

Calculating pathways:  69%|██████▉   | 207/299 [17:59<06:09,  4.01s/it]

Positive Regulation of Neurotransmitter Transport (GO:0051590): pvalue calculation completed
Positive Regulation of Neurotransmitter Transport (GO:0051590): Calculation completed
Positive Regulation of Nitric Oxide Biosynthetic Process (GO:0045429): Calculation started
Positive Regulation of Nitric Oxide Biosynthetic Process (GO:0045429): scoring computed

Calculating pathways:  70%|██████▉   | 208/299 [18:03<05:52,  3.88s/it]

Positive Regulation of Nitric Oxide Biosynthetic Process (GO:0045429): pvalue calculation completed
Positive Regulation of Nitric Oxide Biosynthetic Process (GO:0045429): Calculation completed
Positive Regulation of Nitric Oxide Metabolic Process (GO:1904407): Calculation started
Positive Regulation of Nitric Oxide Metabolic Process (GO:1904407): scoring computed

Calculating pathways:  70%|██████▉   | 209/299 [18:06<05:40,  3.78s/it]

Positive Regulation of Nitric Oxide Metabolic Process (GO:1904407): pvalue calculation completed
Positive Regulation of Nitric Oxide Metabolic Process (GO:1904407): Calculation completed
Positive Regulation of Nitric-Oxide Synthase Activity (GO:0051000): Calculation started
Positive Regulation of Nitric-Oxide Synthase Activity (GO:0051000): scoring computed

Calculating pathways:  70%|███████   | 210/299 [18:10<05:25,  3.66s/it]

Positive Regulation of Nitric-Oxide Synthase Activity (GO:0051000): pvalue calculation completed
Positive Regulation of Nitric-Oxide Synthase Activity (GO:0051000): Calculation completed
Positive Regulation of Organelle Organization (GO:0010638): Calculation started
Positive Regulation of Organelle Organization (GO:0010638): scoring computed

Calculating pathways:  71%|███████   | 211/299 [18:14<05:32,  3.78s/it]

Positive Regulation of Organelle Organization (GO:0010638): pvalue calculation completed
Positive Regulation of Organelle Organization (GO:0010638): Calculation completed
Positive Regulation of Peptide Hormone Secretion (GO:0090277): Calculation started
Positive Regulation of Peptide Hormone Secretion (GO:0090277): scoring computed

Calculating pathways:  71%|███████   | 212/299 [18:18<05:28,  3.78s/it]

Positive Regulation of Peptide Hormone Secretion (GO:0090277): pvalue calculation completed
Positive Regulation of Peptide Hormone Secretion (GO:0090277): Calculation completed
+ Reg of Phosphatidylinositol 3-Kinase/Prot Kinase B Signal Transduction (GO:0051897): Calculation started
+ Reg of Phosphatidylinositol 3-Kinase/Prot Kinase B Signal Transduction (GO:0051897): scoring computed

Calculating pathways:  71%|███████   | 213/299 [18:23<05:58,  4.17s/it]

+ Reg of Phosphatidylinositol 3-Kinase/Prot Kinase B Signal Transduction (GO:0051897): pvalue calculation completed
+ Reg of Phosphatidylinositol 3-Kinase/Prot Kinase B Signal Transduction (GO:0051897): Calculation completed
Positive Regulation of Phospholipid Biosynthetic Process (GO:0071073): Calculation started
Positive Regulation of Phospholipid Biosynthetic Process (GO:0071073): scoring computed

Calculating pathways:  72%|███████▏  | 214/299 [18:26<05:31,  3.91s/it]

Positive Regulation of Phospholipid Biosynthetic Process (GO:0071073): pvalue calculation completed
Positive Regulation of Phospholipid Biosynthetic Process (GO:0071073): Calculation completed
Positive Regulation of Phosphorylation (GO:0042327): Calculation started
Positive Regulation of Phosphorylation (GO:0042327): scoring computed

Calculating pathways:  72%|███████▏  | 215/299 [18:30<05:35,  3.99s/it]

Positive Regulation of Phosphorylation (GO:0042327): pvalue calculation completed
Positive Regulation of Phosphorylation (GO:0042327): Calculation completed
Positive Regulation of Programmed Cell Death (GO:0043068): Calculation started
Positive Regulation of Programmed Cell Death (GO:0043068): scoring computed

Calculating pathways:  72%|███████▏  | 216/299 [18:36<06:18,  4.57s/it]

Positive Regulation of Programmed Cell Death (GO:0043068): pvalue calculation completed
Positive Regulation of Programmed Cell Death (GO:0043068): Calculation completed
Positive Regulation of Protein Localization to Cell Periphery (GO:1904377): Calculation started
Positive Regulation of Protein Localization to Cell Periphery (GO:1904377): scoring computed

Calculating pathways:  73%|███████▎  | 217/299 [18:40<05:57,  4.36s/it]

Positive Regulation of Protein Localization to Cell Periphery (GO:1904377): pvalue calculation completed
Positive Regulation of Protein Localization to Cell Periphery (GO:1904377): Calculation completed
Positive Regulation of Protein Localization to Membrane (GO:1905477): Calculation started
Positive Regulation of Protein Localization to Membrane (GO:1905477): scoring computed

Calculating pathways:  73%|███████▎  | 218/299 [18:44<05:45,  4.26s/it]

Positive Regulation of Protein Localization to Membrane (GO:1905477): pvalue calculation completed
Positive Regulation of Protein Localization to Membrane (GO:1905477): Calculation completed
Positive Regulation of Protein Localization to Plasma Membrane (GO:1903078): Calculation started
Positive Regulation of Protein Localization to Plasma Membrane (GO:1903078): scoring computed

Calculating pathways:  73%|███████▎  | 219/299 [18:48<05:30,  4.13s/it]

Positive Regulation of Protein Localization to Plasma Membrane (GO:1903078): pvalue calculation completed
Positive Regulation of Protein Localization to Plasma Membrane (GO:1903078): Calculation completed
Positive Regulation of Protein Modification Process (GO:0031401): Calculation started
Positive Regulation of Protein Modification Process (GO:0031401): scoring computed

Calculating pathways:  74%|███████▎  | 220/299 [18:52<05:32,  4.20s/it]

Positive Regulation of Protein Modification Process (GO:0031401): pvalue calculation completed
Positive Regulation of Protein Modification Process (GO:0031401): Calculation completed
Positive Regulation of Protein Phosphorylation (GO:0001934): Calculation started
Positive Regulation of Protein Phosphorylation (GO:0001934): scoring computed

Calculating pathways:  74%|███████▍  | 221/299 [18:58<05:53,  4.53s/it]

Positive Regulation of Protein Phosphorylation (GO:0001934): pvalue calculation completed
Positive Regulation of Protein Phosphorylation (GO:0001934): Calculation completed
Positive Regulation of Protein Secretion (GO:0050714): Calculation started
Positive Regulation of Protein Secretion (GO:0050714): scoring computed

Calculating pathways:  74%|███████▍  | 222/299 [19:02<05:39,  4.41s/it]

Positive Regulation of Protein Secretion (GO:0050714): pvalue calculation completed
Positive Regulation of Protein Secretion (GO:0050714): Calculation completed
Positive Regulation of Release of Cytochrome C From Mitochondria (GO:0090200): Calculation started
Positive Regulation of Release of Cytochrome C From Mitochondria (GO:0090200): scoring computed

Calculating pathways:  75%|███████▍  | 223/299 [19:05<05:16,  4.17s/it]

Positive Regulation of Release of Cytochrome C From Mitochondria (GO:0090200): pvalue calculation completed
Positive Regulation of Release of Cytochrome C From Mitochondria (GO:0090200): Calculation completed
Positive Regulation of Release of Sequestered Calcium Ion Into Cytosol (GO:0051281): Calculation started
Positive Regulation of Release of Sequestered Calcium Ion Into Cytosol (GO:0051281): scoring computed

Calculating pathways:  75%|███████▍  | 224/299 [19:09<05:08,  4.11s/it]

Positive Regulation of Release of Sequestered Calcium Ion Into Cytosol (GO:0051281): pvalue calculation completed
Positive Regulation of Release of Sequestered Calcium Ion Into Cytosol (GO:0051281): Calculation completed
Positive Regulation of Secretion by Cell (GO:1903532): Calculation started
Positive Regulation of Secretion by Cell (GO:1903532): scoring computed

Calculating pathways:  75%|███████▌  | 225/299 [19:14<05:09,  4.18s/it]

Positive Regulation of Secretion by Cell (GO:1903532): pvalue calculation completed
Positive Regulation of Secretion by Cell (GO:1903532): Calculation completed
Positive Regulation of Signal Transduction (GO:0009967): Calculation started
Positive Regulation of Signal Transduction (GO:0009967): scoring computed

Calculating pathways:  76%|███████▌  | 226/299 [19:19<05:43,  4.71s/it]

Positive Regulation of Signal Transduction (GO:0009967): pvalue calculation completed
Positive Regulation of Signal Transduction (GO:0009967): Calculation completed
Positive Regulation of Small Molecule Metabolic Process (GO:0062013): Calculation started
Positive Regulation of Small Molecule Metabolic Process (GO:0062013): scoring computed

Calculating pathways:  76%|███████▌  | 227/299 [19:23<05:12,  4.33s/it]

Positive Regulation of Small Molecule Metabolic Process (GO:0062013): pvalue calculation completed
Positive Regulation of Small Molecule Metabolic Process (GO:0062013): Calculation completed
Positive Regulation of Smooth Muscle Contraction (GO:0045987): Calculation started
Positive Regulation of Smooth Muscle Contraction (GO:0045987): scoring computed

Calculating pathways:  76%|███████▋  | 228/299 [19:26<04:47,  4.04s/it]

Positive Regulation of Smooth Muscle Contraction (GO:0045987): pvalue calculation completed
Positive Regulation of Smooth Muscle Contraction (GO:0045987): Calculation completed
Positive Regulation of Synaptic Transmission (GO:0050806): Calculation started
Positive Regulation of Synaptic Transmission (GO:0050806): scoring computed

Calculating pathways:  77%|███████▋  | 229/299 [19:31<04:48,  4.12s/it]

Positive Regulation of Synaptic Transmission (GO:0050806): pvalue calculation completed
Positive Regulation of Synaptic Transmission (GO:0050806): Calculation completed
Positive Regulation of Transcription by RNA Polymerase II (GO:0045944): Calculation started
Positive Regulation of Transcription by RNA Polymerase II (GO:0045944): scoring computed

Calculating pathways:  77%|███████▋  | 230/299 [19:44<07:48,  6.79s/it]

Positive Regulation of Transcription by RNA Polymerase II (GO:0045944): pvalue calculation completed
Positive Regulation of Transcription by RNA Polymerase II (GO:0045944): Calculation completed
Positive Regulation of Vascular Associated Smooth Muscle Cell Differentiation (GO:1905065): Calculation started
Positive Regulation of Vascular Associated Smooth Muscle Cell Differentiation (GO:1905065): scoring computed

Calculating pathways:  77%|███████▋  | 231/299 [19:47<06:31,  5.75s/it]

Positive Regulation of Vascular Associated Smooth Muscle Cell Differentiation (GO:1905065): pvalue calculation completed
Positive Regulation of Vascular Associated Smooth Muscle Cell Differentiation (GO:1905065): Calculation completed
Progesterone Receptor Signaling Pathway (GO:0050847): Calculation started
Progesterone Receptor Signaling Pathway (GO:0050847): scoring computed

Calculating pathways:  78%|███████▊  | 232/299 [19:50<05:37,  5.04s/it]

Progesterone Receptor Signaling Pathway (GO:0050847): pvalue calculation completed
Progesterone Receptor Signaling Pathway (GO:0050847): Calculation completed
Protein Localization to Chromatin (GO:0071168): Calculation started
Protein Localization to Chromatin (GO:0071168): scoring computed

Calculating pathways:  78%|███████▊  | 233/299 [19:54<05:04,  4.61s/it]

Protein Localization to Chromatin (GO:0071168): pvalue calculation completed
Protein Localization to Chromatin (GO:0071168): Calculation completed
Protein Localization to Chromosome (GO:0034502): Calculation started
Protein Localization to Chromosome (GO:0034502): scoring computed

Calculating pathways:  78%|███████▊  | 234/299 [19:58<04:48,  4.44s/it]

Protein Localization to Chromosome (GO:0034502): pvalue calculation completed
Protein Localization to Chromosome (GO:0034502): Calculation completed
Protein Localization to Nucleus (GO:0034504): Calculation started
Protein Localization to Nucleus (GO:0034504): scoring computed

Calculating pathways:  79%|███████▊  | 235/299 [20:03<04:47,  4.50s/it]

Protein Localization to Nucleus (GO:0034504): pvalue calculation completed
Protein Localization to Nucleus (GO:0034504): Calculation completed
Regulation of ERK1 and ERK2 Cascade (GO:0070372): Calculation started
Regulation of ERK1 and ERK2 Cascade (GO:0070372): scoring computed

Calculating pathways:  79%|███████▉  | 236/299 [20:08<05:01,  4.79s/it]

Regulation of ERK1 and ERK2 Cascade (GO:0070372): pvalue calculation completed
Regulation of ERK1 and ERK2 Cascade (GO:0070372): Calculation completed
Regulation of G Protein-Coupled Receptor Signaling Pathway (GO:0008277): Calculation started
Regulation of G Protein-Coupled Receptor Signaling Pathway (GO:0008277): scoring computed

Calculating pathways:  79%|███████▉  | 237/299 [20:12<04:40,  4.53s/it]

Regulation of G Protein-Coupled Receptor Signaling Pathway (GO:0008277): pvalue calculation completed
Regulation of G Protein-Coupled Receptor Signaling Pathway (GO:0008277): Calculation completed
Regulation of MAPK Cascade (GO:0043408): Calculation started
Regulation of MAPK Cascade (GO:0043408): scoring computed

Calculating pathways:  80%|███████▉  | 238/299 [20:18<05:00,  4.93s/it]

Regulation of MAPK Cascade (GO:0043408): pvalue calculation completed
Regulation of MAPK Cascade (GO:0043408): Calculation completed
Regulation of RNA Biosynthetic Process (GO:2001141): Calculation started
Regulation of RNA Biosynthetic Process (GO:2001141): scoring computed

Calculating pathways:  80%|███████▉  | 239/299 [20:26<05:50,  5.84s/it]

Regulation of RNA Biosynthetic Process (GO:2001141): pvalue calculation completed
Regulation of RNA Biosynthetic Process (GO:2001141): Calculation completed
Regulation of Apoptotic Process (GO:0042981): Calculation started
Regulation of Apoptotic Process (GO:0042981): scoring computed

Calculating pathways:  80%|████████  | 240/299 [20:36<07:03,  7.19s/it]

Regulation of Apoptotic Process (GO:0042981): pvalue calculation completed
Regulation of Apoptotic Process (GO:0042981): Calculation completed
Regulation of Bile Acid Biosynthetic Process (GO:0070857): Calculation started
Regulation of Bile Acid Biosynthetic Process (GO:0070857): scoring computed

Calculating pathways:  81%|████████  | 241/299 [20:39<05:49,  6.03s/it]

Regulation of Bile Acid Biosynthetic Process (GO:0070857): pvalue calculation completed
Regulation of Bile Acid Biosynthetic Process (GO:0070857): Calculation completed
Regulation of Bile Acid Metabolic Process (GO:1904251): Calculation started
Regulation of Bile Acid Metabolic Process (GO:1904251): scoring computed

Calculating pathways:  81%|████████  | 242/299 [20:43<04:56,  5.21s/it]

Regulation of Bile Acid Metabolic Process (GO:1904251): pvalue calculation completed
Regulation of Bile Acid Metabolic Process (GO:1904251): Calculation completed
Regulation of Canonical NF-kappaB Signal Transduction (GO:0043122): Calculation started
Regulation of Canonical NF-kappaB Signal Transduction (GO:0043122): scoring computed

Calculating pathways:  81%|████████▏ | 243/299 [20:49<05:11,  5.55s/it]

Regulation of Canonical NF-kappaB Signal Transduction (GO:0043122): pvalue calculation completed
Regulation of Canonical NF-kappaB Signal Transduction (GO:0043122): Calculation completed
Regulation of Cell Cycle (GO:0051726): Calculation started
Regulation of Cell Cycle (GO:0051726): scoring computed

Calculating pathways:  82%|████████▏ | 244/299 [20:56<05:26,  5.94s/it]

Regulation of Cell Cycle (GO:0051726): pvalue calculation completed
Regulation of Cell Cycle (GO:0051726): Calculation completed
Regulation of Cell Cycle Process (GO:0010564): Calculation started
Regulation of Cell Cycle Process (GO:0010564): scoring computed

Calculating pathways:  82%|████████▏ | 245/299 [21:01<05:02,  5.61s/it]

Regulation of Cell Cycle Process (GO:0010564): pvalue calculation completed
Regulation of Cell Cycle Process (GO:0010564): Calculation completed
Regulation of Cell Growth (GO:0001558): Calculation started
Regulation of Cell Growth (GO:0001558): scoring computed

Calculating pathways:  82%|████████▏ | 246/299 [21:06<04:57,  5.62s/it]

Regulation of Cell Growth (GO:0001558): pvalue calculation completed
Regulation of Cell Growth (GO:0001558): Calculation completed
Regulation of Cell Migration (GO:0030334): Calculation started
Regulation of Cell Migration (GO:0030334): scoring computed

Calculating pathways:  83%|████████▎ | 247/299 [21:15<05:31,  6.37s/it]

Regulation of Cell Migration (GO:0030334): pvalue calculation completed
Regulation of Cell Migration (GO:0030334): Calculation completed
Regulation of Cell Population Proliferation (GO:0042127): Calculation started
Regulation of Cell Population Proliferation (GO:0042127): scoring computed

Calculating pathways:  83%|████████▎ | 248/299 [21:25<06:32,  7.70s/it]

Regulation of Cell Population Proliferation (GO:0042127): pvalue calculation completed
Regulation of Cell Population Proliferation (GO:0042127): Calculation completed
Regulation of Cellular Component Organization (GO:0051128): Calculation started
Regulation of Cellular Component Organization (GO:0051128): scoring computed

Calculating pathways:  83%|████████▎ | 249/299 [21:30<05:45,  6.91s/it]

Regulation of Cellular Component Organization (GO:0051128): pvalue calculation completed
Regulation of Cellular Component Organization (GO:0051128): Calculation completed
Regulation of Cholesterol Metabolic Process (GO:0090181): Calculation started
Regulation of Cholesterol Metabolic Process (GO:0090181): scoring computed

Calculating pathways:  84%|████████▎ | 250/299 [21:34<04:49,  5.90s/it]

Regulation of Cholesterol Metabolic Process (GO:0090181): pvalue calculation completed
Regulation of Cholesterol Metabolic Process (GO:0090181): Calculation completed
Regulation of Cytosolic Calcium Ion Concentration (GO:0051480): Calculation started
Regulation of Cytosolic Calcium Ion Concentration (GO:0051480): scoring computed

Calculating pathways:  84%|████████▍ | 251/299 [21:38<04:11,  5.25s/it]

Regulation of Cytosolic Calcium Ion Concentration (GO:0051480): pvalue calculation completed
Regulation of Cytosolic Calcium Ion Concentration (GO:0051480): Calculation completed
Regulation of Endothelial Cell Apoptotic Process (GO:2000351): Calculation started
Regulation of Endothelial Cell Apoptotic Process (GO:2000351): scoring computed

Calculating pathways:  84%|████████▍ | 252/299 [21:42<03:46,  4.81s/it]

Regulation of Endothelial Cell Apoptotic Process (GO:2000351): pvalue calculation completed
Regulation of Endothelial Cell Apoptotic Process (GO:2000351): Calculation completed
Regulation of Epidermal Growth Factor Receptor Signaling Pathway (GO:0042058): Calculation started
Regulation of Epidermal Growth Factor Receptor Signaling Pathway (GO:0042058): scoring computed

Calculating pathways:  85%|████████▍ | 253/299 [21:45<03:26,  4.50s/it]

Regulation of Epidermal Growth Factor Receptor Signaling Pathway (GO:0042058): pvalue calculation completed
Regulation of Epidermal Growth Factor Receptor Signaling Pathway (GO:0042058): Calculation completed
Regulation of Extrinsic Apoptotic Signaling Pathway (GO:2001236): Calculation started
Regulation of Extrinsic Apoptotic Signaling Pathway (GO:2001236): scoring computed

Calculating pathways:  85%|████████▍ | 254/299 [21:49<03:16,  4.37s/it]

Regulation of Extrinsic Apoptotic Signaling Pathway (GO:2001236): pvalue calculation completed
Regulation of Extrinsic Apoptotic Signaling Pathway (GO:2001236): Calculation completed
Regulation of Fat Cell Differentiation (GO:0045598): Calculation started
Regulation of Fat Cell Differentiation (GO:0045598): scoring computed

Calculating pathways:  85%|████████▌ | 255/299 [21:54<03:09,  4.30s/it]

Regulation of Fat Cell Differentiation (GO:0045598): pvalue calculation completed
Regulation of Fat Cell Differentiation (GO:0045598): Calculation completed
Regulation of Gene Expression (GO:0010468): Calculation started
Regulation of Gene Expression (GO:0010468): scoring computed

Calculating pathways:  86%|████████▌ | 256/299 [22:08<05:13,  7.29s/it]

Regulation of Gene Expression (GO:0010468): pvalue calculation completed
Regulation of Gene Expression (GO:0010468): Calculation completed
Regulation of Inflammatory Response (GO:0050727): Calculation started
Regulation of Inflammatory Response (GO:0050727): scoring computed

Calculating pathways:  86%|████████▌ | 257/299 [22:13<04:45,  6.81s/it]

Regulation of Inflammatory Response (GO:0050727): pvalue calculation completed
Regulation of Inflammatory Response (GO:0050727): Calculation completed
Regulation of Insulin Secretion (GO:0050796): Calculation started
Regulation of Insulin Secretion (GO:0050796): scoring computed

Calculating pathways:  86%|████████▋ | 258/299 [22:18<04:10,  6.11s/it]

Regulation of Insulin Secretion (GO:0050796): pvalue calculation completed
Regulation of Insulin Secretion (GO:0050796): Calculation completed
Regulation of Insulin Secretion Involved in Cellular Response to Glucose Stimulus (GO:0061178): Calculation started
Regulation of Insulin Secretion Involved in Cellular Response to Glucose Stimulus (GO:0061178): scoring computed

Calculating pathways:  87%|████████▋ | 259/299 [22:22<03:34,  5.37s/it]

Regulation of Insulin Secretion Involved in Cellular Response to Glucose Stimulus (GO:0061178): pvalue calculation completed
Regulation of Insulin Secretion Involved in Cellular Response to Glucose Stimulus (GO:0061178): Calculation completed
Regulation of Interleukin-17 Production (GO:0032660): Calculation started
Regulation of Interleukin-17 Production (GO:0032660): scoring computed

Calculating pathways:  87%|████████▋ | 260/299 [22:25<03:08,  4.82s/it]

Regulation of Interleukin-17 Production (GO:0032660): pvalue calculation completed
Regulation of Interleukin-17 Production (GO:0032660): Calculation completed
Regulation of Ketone Metabolic Process (GO:0010565): Calculation started
Regulation of Ketone Metabolic Process (GO:0010565): scoring computed

Calculating pathways:  87%|████████▋ | 261/299 [22:28<02:46,  4.38s/it]

Regulation of Ketone Metabolic Process (GO:0010565): pvalue calculation completed
Regulation of Ketone Metabolic Process (GO:0010565): Calculation completed
Regulation of Leukocyte Activation (GO:0002694): Calculation started
Regulation of Leukocyte Activation (GO:0002694): scoring computed

Calculating pathways:  88%|████████▊ | 262/299 [22:32<02:33,  4.15s/it]

Regulation of Leukocyte Activation (GO:0002694): pvalue calculation completed
Regulation of Leukocyte Activation (GO:0002694): Calculation completed
Regulation of Lipid Biosynthetic Process (GO:0046890): Calculation started
Regulation of Lipid Biosynthetic Process (GO:0046890): scoring computed

Calculating pathways:  88%|████████▊ | 263/299 [22:36<02:23,  3.98s/it]

Regulation of Lipid Biosynthetic Process (GO:0046890): pvalue calculation completed
Regulation of Lipid Biosynthetic Process (GO:0046890): Calculation completed
Regulation of Low-Density Lipoprotein Particle Clearance (GO:0010988): Calculation started
Regulation of Low-Density Lipoprotein Particle Clearance (GO:0010988): scoring computed

Calculating pathways:  88%|████████▊ | 264/299 [22:39<02:13,  3.80s/it]

Regulation of Low-Density Lipoprotein Particle Clearance (GO:0010988): pvalue calculation completed
Regulation of Low-Density Lipoprotein Particle Clearance (GO:0010988): Calculation completed
Regulation of miRNA Transcription (GO:1902893): Calculation started
Regulation of miRNA Transcription (GO:1902893): scoring computed

Calculating pathways:  89%|████████▊ | 265/299 [22:43<02:12,  3.88s/it]

Regulation of miRNA Transcription (GO:1902893): pvalue calculation completed
Regulation of miRNA Transcription (GO:1902893): Calculation completed
Regulation of Neurogenesis (GO:0050767): Calculation started
Regulation of Neurogenesis (GO:0050767): scoring computed

Calculating pathways:  89%|████████▉ | 266/299 [22:47<02:10,  3.95s/it]

Regulation of Neurogenesis (GO:0050767): pvalue calculation completed
Regulation of Neurogenesis (GO:0050767): Calculation completed
Regulation of Neurotransmitter Secretion (GO:0046928): Calculation started
Regulation of Neurotransmitter Secretion (GO:0046928): scoring computed

Calculating pathways:  89%|████████▉ | 267/299 [22:51<02:04,  3.88s/it]

Regulation of Neurotransmitter Secretion (GO:0046928): pvalue calculation completed
Regulation of Neurotransmitter Secretion (GO:0046928): Calculation completed
Regulation of Nitric Oxide Biosynthetic Process (GO:0045428): Calculation started
Regulation of Nitric Oxide Biosynthetic Process (GO:0045428): scoring computed

Calculating pathways:  90%|████████▉ | 268/299 [22:55<01:59,  3.86s/it]

Regulation of Nitric Oxide Biosynthetic Process (GO:0045428): pvalue calculation completed
Regulation of Nitric Oxide Biosynthetic Process (GO:0045428): Calculation completed
Regulation of Nitric-Oxide Synthase Activity (GO:0050999): Calculation started
Regulation of Nitric-Oxide Synthase Activity (GO:0050999): scoring computed

Calculating pathways:  90%|████████▉ | 269/299 [22:58<01:52,  3.76s/it]

Regulation of Nitric-Oxide Synthase Activity (GO:0050999): pvalue calculation completed
Regulation of Nitric-Oxide Synthase Activity (GO:0050999): Calculation completed
Regulation of Phosphatidylinositol 3-Kinase/Protein Kinase B Signal Transduction (GO:0051896): Calculation started
Regulation of Phosphatidylinositol 3-Kinase/Protein Kinase B Signal Transduction (GO:0051896): scoring computed

Calculating pathways:  90%|█████████ | 270/299 [23:04<02:06,  4.35s/it]

Regulation of Phosphatidylinositol 3-Kinase/Protein Kinase B Signal Transduction (GO:0051896): pvalue calculation completed
Regulation of Phosphatidylinositol 3-Kinase/Protein Kinase B Signal Transduction (GO:0051896): Calculation completed
Regulation of Protein Localization to Plasma Membrane (GO:1903076): Calculation started
Regulation of Protein Localization to Plasma Membrane (GO:1903076): scoring computed

Calculating pathways:  91%|█████████ | 271/299 [23:08<02:02,  4.37s/it]

Regulation of Protein Localization to Plasma Membrane (GO:1903076): pvalue calculation completed
Regulation of Protein Localization to Plasma Membrane (GO:1903076): Calculation completed
Regulation of Protein Phosphorylation (GO:0001932): Calculation started
Regulation of Protein Phosphorylation (GO:0001932): scoring computed

Calculating pathways:  91%|█████████ | 272/299 [23:13<02:00,  4.46s/it]

Regulation of Protein Phosphorylation (GO:0001932): pvalue calculation completed
Regulation of Protein Phosphorylation (GO:0001932): Calculation completed
Regulation of Release of Cytochrome C From Mitochondria (GO:0090199): Calculation started
Regulation of Release of Cytochrome C From Mitochondria (GO:0090199): scoring computed

Calculating pathways:  91%|█████████▏| 273/299 [23:17<01:50,  4.24s/it]

Regulation of Release of Cytochrome C From Mitochondria (GO:0090199): pvalue calculation completed
Regulation of Release of Cytochrome C From Mitochondria (GO:0090199): Calculation completed
Regulation of Release of Sequestered Calcium Ion Into Cytosol (GO:0051279): Calculation started
Regulation of Release of Sequestered Calcium Ion Into Cytosol (GO:0051279): scoring computed

Calculating pathways:  92%|█████████▏| 274/299 [23:21<01:43,  4.13s/it]

Regulation of Release of Sequestered Calcium Ion Into Cytosol (GO:0051279): pvalue calculation completed
Regulation of Release of Sequestered Calcium Ion Into Cytosol (GO:0051279): Calculation completed
Regulation of Small Molecule Metabolic Process (GO:0062012): Calculation started
Regulation of Small Molecule Metabolic Process (GO:0062012): scoring computed

Calculating pathways:  92%|█████████▏| 275/299 [23:24<01:35,  3.98s/it]

Regulation of Small Molecule Metabolic Process (GO:0062012): pvalue calculation completed
Regulation of Small Molecule Metabolic Process (GO:0062012): Calculation completed
Regulation of Smooth Muscle Cell Apoptotic Process (GO:0034391): Calculation started
Regulation of Smooth Muscle Cell Apoptotic Process (GO:0034391): scoring computed

Calculating pathways:  92%|█████████▏| 276/299 [23:28<01:29,  3.88s/it]

Regulation of Smooth Muscle Cell Apoptotic Process (GO:0034391): pvalue calculation completed
Regulation of Smooth Muscle Cell Apoptotic Process (GO:0034391): Calculation completed
Regulation of Steroid Biosynthetic Process (GO:0050810): Calculation started
Regulation of Steroid Biosynthetic Process (GO:0050810): scoring computed

Calculating pathways:  93%|█████████▎| 277/299 [23:32<01:23,  3.78s/it]

Regulation of Steroid Biosynthetic Process (GO:0050810): pvalue calculation completed
Regulation of Steroid Biosynthetic Process (GO:0050810): Calculation completed
Regulation of Steroid Metabolic Process (GO:0019218): Calculation started
Regulation of Steroid Metabolic Process (GO:0019218): scoring computed

Calculating pathways:  93%|█████████▎| 278/299 [23:35<01:19,  3.78s/it]

Regulation of Steroid Metabolic Process (GO:0019218): pvalue calculation completed
Regulation of Steroid Metabolic Process (GO:0019218): Calculation completed
Regulation of Tumor Necrosis Factor Production (GO:0032680): Calculation started
Regulation of Tumor Necrosis Factor Production (GO:0032680): scoring computed

Calculating pathways:  93%|█████████▎| 279/299 [23:40<01:23,  4.18s/it]

Regulation of Tumor Necrosis Factor Production (GO:0032680): pvalue calculation completed
Regulation of Tumor Necrosis Factor Production (GO:0032680): Calculation completed
Regulation of Type II Interferon Production (GO:0032649): Calculation started
Regulation of Type II Interferon Production (GO:0032649): scoring computed

Calculating pathways:  94%|█████████▎| 280/299 [23:45<01:21,  4.27s/it]

Regulation of Type II Interferon Production (GO:0032649): pvalue calculation completed
Regulation of Type II Interferon Production (GO:0032649): Calculation completed
Regulation of Vascular Associated Smooth Muscle Cell Proliferation (GO:1904705): Calculation started
Regulation of Vascular Associated Smooth Muscle Cell Proliferation (GO:1904705): scoring computed

Calculating pathways:  94%|█████████▍| 281/299 [23:49<01:14,  4.13s/it]

Regulation of Vascular Associated Smooth Muscle Cell Proliferation (GO:1904705): pvalue calculation completed
Regulation of Vascular Associated Smooth Muscle Cell Proliferation (GO:1904705): Calculation completed
Regulation of Very-Low-Density Lipoprotein Particle Remodeling (GO:0010901): Calculation started
Regulation of Very-Low-Density Lipoprotein Particle Remodeling (GO:0010901): scoring computed

Calculating pathways:  94%|█████████▍| 282/299 [23:52<01:06,  3.91s/it]

Regulation of Very-Low-Density Lipoprotein Particle Remodeling (GO:0010901): pvalue calculation completed
Regulation of Very-Low-Density Lipoprotein Particle Remodeling (GO:0010901): Calculation completed
Response to Bile Acid (GO:1903412): Calculation started
Response to Bile Acid (GO:1903412): scoring computed

Calculating pathways:  95%|█████████▍| 283/299 [23:56<01:00,  3.77s/it]

Response to Bile Acid (GO:1903412): pvalue calculation completed
Response to Bile Acid (GO:1903412): Calculation completed
Response to Estradiol (GO:0032355): Calculation started
Response to Estradiol (GO:0032355): scoring computed

Calculating pathways:  95%|█████████▍| 284/299 [23:59<00:57,  3.81s/it]

Response to Estradiol (GO:0032355): pvalue calculation completed
Response to Estradiol (GO:0032355): Calculation completed
Response to Estrogen (GO:0043627): Calculation started
Response to Estrogen (GO:0043627): scoring computed

Calculating pathways:  95%|█████████▌| 285/299 [24:03<00:53,  3.79s/it]

Response to Estrogen (GO:0043627): pvalue calculation completed
Response to Estrogen (GO:0043627): Calculation completed
Response to Fatty Acid (GO:0070542): Calculation started
Response to Fatty Acid (GO:0070542): scoring computed

Calculating pathways:  96%|█████████▌| 286/299 [24:07<00:48,  3.73s/it]

Response to Fatty Acid (GO:0070542): pvalue calculation completed
Response to Fatty Acid (GO:0070542): Calculation completed
Response to Glucose (GO:0009749): Calculation started
Response to Glucose (GO:0009749): scoring computed

Calculating pathways:  96%|█████████▌| 287/299 [24:11<00:45,  3.78s/it]

Response to Glucose (GO:0009749): pvalue calculation completed
Response to Glucose (GO:0009749): Calculation completed
Response to Molecule of Bacterial Origin (GO:0002237): Calculation started
Response to Molecule of Bacterial Origin (GO:0002237): scoring computed

Calculating pathways:  96%|█████████▋| 288/299 [24:15<00:42,  3.83s/it]

Response to Molecule of Bacterial Origin (GO:0002237): pvalue calculation completed
Response to Molecule of Bacterial Origin (GO:0002237): Calculation completed
Response to Peptide Hormone (GO:0043434): Calculation started
Response to Peptide Hormone (GO:0043434): scoring computed

Calculating pathways:  97%|█████████▋| 289/299 [24:19<00:38,  3.85s/it]

Response to Peptide Hormone (GO:0043434): pvalue calculation completed
Response to Peptide Hormone (GO:0043434): Calculation completed
Response to Tumor Necrosis Factor (GO:0034612): Calculation started
Response to Tumor Necrosis Factor (GO:0034612): scoring computed

Calculating pathways:  97%|█████████▋| 290/299 [24:23<00:35,  3.94s/it]

Response to Tumor Necrosis Factor (GO:0034612): pvalue calculation completed
Response to Tumor Necrosis Factor (GO:0034612): Calculation completed
Steroid Hormone Receptor Signaling Pathway (GO:0043401): Calculation started
Steroid Hormone Receptor Signaling Pathway (GO:0043401): scoring computed

Calculating pathways:  97%|█████████▋| 291/299 [24:26<00:30,  3.78s/it]

Steroid Hormone Receptor Signaling Pathway (GO:0043401): pvalue calculation completed
Steroid Hormone Receptor Signaling Pathway (GO:0043401): Calculation completed
Steroid Metabolic Process (GO:0008202): Calculation started
Steroid Metabolic Process (GO:0008202): scoring computed

Calculating pathways:  98%|█████████▊| 292/299 [24:30<00:27,  3.90s/it]

Steroid Metabolic Process (GO:0008202): pvalue calculation completed
Steroid Metabolic Process (GO:0008202): Calculation completed
Sterol Homeostasis (GO:0055092): Calculation started
Sterol Homeostasis (GO:0055092): scoring computed

Calculating pathways:  98%|█████████▊| 293/299 [24:34<00:24,  4.00s/it]

Sterol Homeostasis (GO:0055092): pvalue calculation completed
Sterol Homeostasis (GO:0055092): Calculation completed
Transcription Initiation at RNA Polymerase II Promoter (GO:0006367): Calculation started
Transcription Initiation at RNA Polymerase II Promoter (GO:0006367): scoring computed

Calculating pathways:  98%|█████████▊| 294/299 [24:39<00:20,  4.19s/it]

Transcription Initiation at RNA Polymerase II Promoter (GO:0006367): pvalue calculation completed
Transcription Initiation at RNA Polymerase II Promoter (GO:0006367): Calculation completed
Transcription Preinitiation Complex Assembly (GO:0070897): Calculation started
Transcription Preinitiation Complex Assembly (GO:0070897): scoring computed

Calculating pathways:  99%|█████████▊| 295/299 [24:43<00:16,  4.20s/it]

Transcription Preinitiation Complex Assembly (GO:0070897): pvalue calculation completed
Transcription Preinitiation Complex Assembly (GO:0070897): Calculation completed
Triglyceride Homeostasis (GO:0070328): Calculation started
Triglyceride Homeostasis (GO:0070328): scoring computed

Calculating pathways:  99%|█████████▉| 296/299 [24:47<00:12,  4.04s/it]

Triglyceride Homeostasis (GO:0070328): pvalue calculation completed
Triglyceride Homeostasis (GO:0070328): Calculation completed
Vasodilation (GO:0042311): Calculation started
Vasodilation (GO:0042311): scoring computed

Calculating pathways:  99%|█████████▉| 297/299 [24:50<00:07,  3.87s/it]

Vasodilation (GO:0042311): pvalue calculation completed
Vasodilation (GO:0042311): Calculation completed
Xenobiotic Catabolic Process (GO:0042178): Calculation started
Xenobiotic Catabolic Process (GO:0042178): scoring computed

Calculating pathways: 100%|█████████▉| 298/299 [24:54<00:03,  3.77s/it]

Xenobiotic Catabolic Process (GO:0042178): pvalue calculation completed
Xenobiotic Catabolic Process (GO:0042178): Calculation completed
Xenobiotic Transport (GO:0042908): Calculation started
Xenobiotic Transport (GO:0042908): scoring computed

Calculating pathways: 100%|██████████| 299/299 [24:57<00:00,  5.01s/it]

Xenobiotic Transport (GO:0042908): pvalue calculation completed
Xenobiotic Transport (GO:0042908): Calculation completed

## Gemcitabine

In [13]:
import os
from singscore.singscore import *
import pandas as pd
import json
from tqdm import tqdm

## loading the patient uk65 data 
uk65 = pd.read_csv("singscore_new_code/UK65_clean_gene_log_tpm.txt", header='infer', sep='\t')
uk65 = uk65.set_index(keys='GeneName')

#loading drug_data
drug_data = json.load(open("singscore_new_code/Gemcitabine/Gemcitabine_relevant_pathways.json"))
count = len(drug_data)
print("Number of items:", count)

final_result = {}

for key, value in tqdm(drug_data.items(), desc="Calculating pathways"):
    print(f"{key}: Calculation started")
    up = drug_data[key]
    up_present = [gene for gene in up if gene in uk65.index]

    # Print counts and summary
    # print(f"Total up genes in signature: {len(up)}")
    # print(f"Up genes found in expression data: {len(up_present)}")

    # Optionally, print the missing ones
    missing_up = set(up) - set(uk65.index)

    # print(f"Missing up genes: {len(missing_up)}")
    scored_data = score(up_gene=up, down_gene=False, sample=uk65,
                    norm_method='theoretical', full_data=True)
    #getting the scored data for a pathway
    total_score = scored_data["total_score"].to_list()[0]
    print(f"{key}: scoring computed")
    permd = permutate(uk65, n_up=len(up_present), n_down=False)
    pvals = empiricalpval(permutations=permd, score=scored_data)
    empirical_p_value = pvals["empirical p value"].to_list()[0]
    print(f"{key}: pvalue calculation completed")
    result = {
    f"{key}":{
        "gene_set_info": {
            "geneset_size": len(up),
            "geneset_covered_in_sample": len(up_present)
        },
        "scores": {
            "total_singscore": total_score
        },
        "statistics": {
            "p_value": empirical_p_value,
            "method": "permutation (empirical)",
            "permutations": 10000
        }}}
    print(f"{key}: Calculation completed")
    final_result.update(result)

# Save final combined JSON
with open("singscore_new_code/Gemcitabine/Gemcitabine_singscore_results.json", "w", encoding="utf-8") as f:
    json.dump(final_result, f, indent=2, ensure_ascii=False)

Number of items: 140

Calculating pathways:   0%|          | 0/140 [00:00<?, ?it/s]

DNA Repair: Calculation started
DNA Repair: scoring computed

Calculating pathways:   1%|          | 1/140 [00:06<15:26,  6.66s/it]

DNA Repair: pvalue calculation completed
DNA Repair: Calculation completed
G2-M Checkpoint: Calculation started
G2-M Checkpoint: scoring computed

Calculating pathways:   1%|▏         | 2/140 [00:12<13:41,  5.95s/it]

G2-M Checkpoint: pvalue calculation completed
G2-M Checkpoint: Calculation completed
mTORC1 Signaling: Calculation started
mTORC1 Signaling: scoring computed

Calculating pathways:   2%|▏         | 3/140 [00:17<13:15,  5.80s/it]

mTORC1 Signaling: pvalue calculation completed
mTORC1 Signaling: Calculation completed
E2F Targets: Calculation started
E2F Targets: scoring computed

Calculating pathways:   3%|▎         | 4/140 [00:23<12:51,  5.67s/it]

E2F Targets: pvalue calculation completed
E2F Targets: Calculation completed
Myc Targets V1: Calculation started
Myc Targets V1: scoring computed

Calculating pathways:   4%|▎         | 5/140 [00:28<12:45,  5.67s/it]

Myc Targets V1: pvalue calculation completed
Myc Targets V1: Calculation completed
Base excision repair: Calculation started
Base excision repair: scoring computed

Calculating pathways:   4%|▍         | 6/140 [00:32<11:13,  5.03s/it]

Base excision repair: pvalue calculation completed
Base excision repair: Calculation completed
DNA replication: Calculation started
DNA replication: scoring computed

Calculating pathways:   5%|▌         | 7/140 [00:36<10:11,  4.60s/it]

DNA replication: pvalue calculation completed
DNA replication: Calculation completed
Drug metabolism: Calculation started
Drug metabolism: scoring computed

Calculating pathways:   6%|▌         | 8/140 [00:40<09:52,  4.49s/it]

Drug metabolism: pvalue calculation completed
Drug metabolism: Calculation completed
Glutathione metabolism: Calculation started
Glutathione metabolism: scoring computed

Calculating pathways:   6%|▋         | 9/140 [00:44<09:21,  4.29s/it]

Glutathione metabolism: pvalue calculation completed
Glutathione metabolism: Calculation completed
Homologous recombination: Calculation started
Homologous recombination: scoring computed

Calculating pathways:   7%|▋         | 10/140 [00:48<08:54,  4.11s/it]

Homologous recombination: pvalue calculation completed
Homologous recombination: Calculation completed
Mismatch repair: Calculation started
Mismatch repair: scoring computed

Calculating pathways:   8%|▊         | 11/140 [00:51<08:28,  3.94s/it]

Mismatch repair: pvalue calculation completed
Mismatch repair: Calculation completed
Nucleotide excision repair: Calculation started
Nucleotide excision repair: scoring computed

Calculating pathways:   9%|▊         | 12/140 [00:55<08:18,  3.89s/it]

Nucleotide excision repair: pvalue calculation completed
Nucleotide excision repair: Calculation completed
One carbon pool by folate: Calculation started
One carbon pool by folate: scoring computed

Calculating pathways:   9%|▉         | 13/140 [00:59<08:02,  3.80s/it]

One carbon pool by folate: pvalue calculation completed
One carbon pool by folate: Calculation completed
Purine metabolism: Calculation started
Purine metabolism: scoring computed

Calculating pathways:  10%|█         | 14/140 [01:03<08:30,  4.05s/it]

Purine metabolism: pvalue calculation completed
Purine metabolism: Calculation completed
Pyrimidine metabolism: Calculation started
Pyrimidine metabolism: scoring computed

Calculating pathways:  11%|█         | 15/140 [01:07<08:19,  3.99s/it]

Pyrimidine metabolism: pvalue calculation completed
Pyrimidine metabolism: Calculation completed
p53 signaling pathway: Calculation started
p53 signaling pathway: scoring computed

Calculating pathways:  11%|█▏        | 16/140 [01:11<08:20,  4.04s/it]

p53 signaling pathway: pvalue calculation completed
p53 signaling pathway: Calculation completed
Activation of the Pre-Replicative Complex: Calculation started
Activation of the Pre-Replicative Complex: scoring computed

Calculating pathways:  12%|█▏        | 17/140 [01:15<08:04,  3.94s/it]

Activation of the Pre-Replicative Complex: pvalue calculation completed
Activation of the Pre-Replicative Complex: Calculation completed
Base Excision Repair: Calculation started
Base Excision Repair: scoring computed

Calculating pathways:  13%|█▎        | 18/140 [01:19<08:00,  3.94s/it]

Base Excision Repair: pvalue calculation completed
Base Excision Repair: Calculation completed
Cell Cycle: Calculation started
Cell Cycle: scoring computed

Calculating pathways:  14%|█▎        | 19/140 [01:29<11:44,  5.82s/it]

Cell Cycle: pvalue calculation completed
Cell Cycle: Calculation completed
Cell Cycle, Mitotic: Calculation started
Cell Cycle, Mitotic: scoring computed

Calculating pathways:  14%|█▍        | 20/140 [01:38<13:28,  6.74s/it]

Cell Cycle, Mitotic: pvalue calculation completed
Cell Cycle, Mitotic: Calculation completed
Chromosome Maintenance: Calculation started
Chromosome Maintenance: scoring computed

Calculating pathways:  15%|█▌        | 21/140 [01:43<12:03,  6.08s/it]

Chromosome Maintenance: pvalue calculation completed
Chromosome Maintenance: Calculation completed
Cytosolic Iron-Sulfur Cluster Assembly: Calculation started
Cytosolic Iron-Sulfur Cluster Assembly: scoring computed

Calculating pathways:  16%|█▌        | 22/140 [01:46<10:35,  5.39s/it]

Cytosolic Iron-Sulfur Cluster Assembly: pvalue calculation completed
Cytosolic Iron-Sulfur Cluster Assembly: Calculation completed
DNA Damage Bypass: Calculation started
DNA Damage Bypass: scoring computed

Calculating pathways:  16%|█▋        | 23/140 [01:50<09:37,  4.94s/it]

DNA Damage Bypass: pvalue calculation completed
DNA Damage Bypass: Calculation completed
DNA Double-Strand Break Repair: Calculation started
DNA Double-Strand Break Repair: scoring computed

Calculating pathways:  17%|█▋        | 24/140 [01:55<09:30,  4.92s/it]

DNA Double-Strand Break Repair: pvalue calculation completed
DNA Double-Strand Break Repair: Calculation completed
DNA Replication: Calculation started
DNA Replication: scoring computed

Calculating pathways:  18%|█▊        | 25/140 [02:00<09:16,  4.84s/it]

DNA Replication: pvalue calculation completed
DNA Replication: Calculation completed
DNA Replication Pre-Initiation: Calculation started
DNA Replication Pre-Initiation: scoring computed

Calculating pathways:  19%|█▊        | 26/140 [02:04<08:59,  4.74s/it]

DNA Replication Pre-Initiation: pvalue calculation completed
DNA Replication Pre-Initiation: Calculation completed
DNA Replication Initiation: Calculation started
DNA Replication Initiation: scoring computed

Calculating pathways:  19%|█▉        | 27/140 [02:08<08:09,  4.33s/it]

DNA Replication Initiation: pvalue calculation completed
DNA Replication Initiation: Calculation completed
DNA Strand Elongation: Calculation started
DNA Strand Elongation: scoring computed

Calculating pathways:  20%|██        | 28/140 [02:11<07:42,  4.13s/it]

DNA Strand Elongation: pvalue calculation completed
DNA Strand Elongation: Calculation completed
Defective Pyroptosis: Calculation started
Defective Pyroptosis: scoring computed

Calculating pathways:  21%|██        | 29/140 [02:15<07:27,  4.03s/it]

Defective Pyroptosis: pvalue calculation completed
Defective Pyroptosis: Calculation completed
Diseases of Programmed Cell Death: Calculation started
Diseases of Programmed Cell Death: scoring computed

Calculating pathways:  21%|██▏       | 30/140 [02:19<07:25,  4.05s/it]

Diseases of Programmed Cell Death: pvalue calculation completed
Diseases of Programmed Cell Death: Calculation completed
Dual Incision in GG-NER: Calculation started
Dual Incision in GG-NER: scoring computed

Calculating pathways:  22%|██▏       | 31/140 [02:23<07:13,  3.98s/it]

Dual Incision in GG-NER: pvalue calculation completed
Dual Incision in GG-NER: Calculation completed
Dual Incision in TC-NER: Calculation started
Dual Incision in TC-NER: scoring computed

Calculating pathways:  23%|██▎       | 32/140 [02:27<07:12,  4.00s/it]

Dual Incision in TC-NER: pvalue calculation completed
Dual Incision in TC-NER: Calculation completed
E2F Mediated Regulation of DNA Replication: Calculation started
E2F Mediated Regulation of DNA Replication: scoring computed

Calculating pathways:  24%|██▎       | 33/140 [02:31<06:53,  3.86s/it]

E2F Mediated Regulation of DNA Replication: pvalue calculation completed
E2F Mediated Regulation of DNA Replication: Calculation completed
Extension of Telomeres: Calculation started
Extension of Telomeres: scoring computed

Calculating pathways:  24%|██▍       | 34/140 [02:35<06:53,  3.90s/it]

Extension of Telomeres: pvalue calculation completed
Extension of Telomeres: Calculation completed
G1 S Transition: Calculation started
G1 S Transition: scoring computed

Calculating pathways:  25%|██▌       | 35/140 [02:39<07:20,  4.20s/it]

G1 S Transition: pvalue calculation completed
G1 S Transition: Calculation completed
G1 S-Specific Transcription: Calculation started
G1 S-Specific Transcription: scoring computed

Calculating pathways:  26%|██▌       | 36/140 [02:43<06:57,  4.02s/it]

G1 S-Specific Transcription: pvalue calculation completed
G1 S-Specific Transcription: Calculation completed
Gap-filling DNA Repair Synthesis and Ligation in GG-NER: Calculation started
Gap-filling DNA Repair Synthesis and Ligation in GG-NER: scoring computed

Calculating pathways:  26%|██▋       | 37/140 [02:47<06:45,  3.94s/it]

Gap-filling DNA Repair Synthesis and Ligation in GG-NER: pvalue calculation completed
Gap-filling DNA Repair Synthesis and Ligation in GG-NER: Calculation completed
Gap-filling DNA Repair Synthesis and Ligation in TC-NER: Calculation started
Gap-filling DNA Repair Synthesis and Ligation in TC-NER: scoring computed

Calculating pathways:  27%|██▋       | 38/140 [02:51<06:43,  3.95s/it]

Gap-filling DNA Repair Synthesis and Ligation in TC-NER: pvalue calculation completed
Gap-filling DNA Repair Synthesis and Ligation in TC-NER: Calculation completed
Gene Expression (Transcription): Calculation started
Gene Expression (Transcription): scoring computed

Calculating pathways:  28%|██▊       | 39/140 [03:10<14:22,  8.54s/it]

Gene Expression (Transcription): pvalue calculation completed
Gene Expression (Transcription): Calculation completed
Generic Transcription Pathway: Calculation started
Generic Transcription Pathway: scoring computed

Calculating pathways:  29%|██▊       | 40/140 [03:26<17:44, 10.65s/it]

Generic Transcription Pathway: pvalue calculation completed
Generic Transcription Pathway: Calculation completed
Global Genome Nucleotide Excision Repair (GG-NER): Calculation started
Global Genome Nucleotide Excision Repair (GG-NER): scoring computed

Calculating pathways:  29%|██▉       | 41/140 [03:30<14:34,  8.83s/it]

Global Genome Nucleotide Excision Repair (GG-NER): pvalue calculation completed
Global Genome Nucleotide Excision Repair (GG-NER): Calculation completed
HDR Through Homologous Recombination (HRR): Calculation started
HDR Through Homologous Recombination (HRR): scoring computed

Calculating pathways:  30%|███       | 42/140 [03:34<12:04,  7.39s/it]

HDR Through Homologous Recombination (HRR): pvalue calculation completed
HDR Through Homologous Recombination (HRR): Calculation completed
HDR Through Homologous Recombination (HRR) or Single Strand Annealing (SSA): Calculation started
HDR Through Homologous Recombination (HRR) or Single Strand Annealing (SSA): scoring computed

Calculating pathways:  31%|███       | 43/140 [03:39<10:35,  6.56s/it]

HDR Through Homologous Recombination (HRR) or Single Strand Annealing (SSA): pvalue calculation completed
HDR Through Homologous Recombination (HRR) or Single Strand Annealing (SSA): Calculation completed
Homology Directed Repair: Calculation started
Homology Directed Repair: scoring computed

Calculating pathways:  31%|███▏      | 44/140 [03:43<09:33,  5.98s/it]

Homology Directed Repair: pvalue calculation completed
Homology Directed Repair: Calculation completed
Inhibition of Replication Initiation of Damaged DNA by RB1 E2F1: Calculation started
Inhibition of Replication Initiation of Damaged DNA by RB1 E2F1: scoring computed

Calculating pathways:  32%|███▏      | 45/140 [03:47<08:15,  5.22s/it]

Inhibition of Replication Initiation of Damaged DNA by RB1 E2F1: pvalue calculation completed
Inhibition of Replication Initiation of Damaged DNA by RB1 E2F1: Calculation completed
Interconversion of Nucleotide Di- and Triphosphates: Calculation started
Interconversion of Nucleotide Di- and Triphosphates: scoring computed

Calculating pathways:  33%|███▎      | 46/140 [03:50<07:24,  4.73s/it]

Interconversion of Nucleotide Di- and Triphosphates: pvalue calculation completed
Interconversion of Nucleotide Di- and Triphosphates: Calculation completed
Lagging Strand Synthesis: Calculation started
Lagging Strand Synthesis: scoring computed

Calculating pathways:  34%|███▎      | 47/140 [03:54<06:47,  4.38s/it]

Lagging Strand Synthesis: pvalue calculation completed
Lagging Strand Synthesis: Calculation completed
Leading Strand Synthesis: Calculation started
Leading Strand Synthesis: scoring computed

Calculating pathways:  34%|███▍      | 48/140 [03:57<06:16,  4.09s/it]

Leading Strand Synthesis: pvalue calculation completed
Leading Strand Synthesis: Calculation completed
Metabolism of Nucleotides: Calculation started
Metabolism of Nucleotides: scoring computed

Calculating pathways:  35%|███▌      | 49/140 [04:02<06:20,  4.18s/it]

Metabolism of Nucleotides: pvalue calculation completed
Metabolism of Nucleotides: Calculation completed
Mismatch Repair: Calculation started
Mismatch Repair: scoring computed

Calculating pathways:  36%|███▌      | 50/140 [04:05<05:56,  3.96s/it]

Mismatch Repair: pvalue calculation completed
Mismatch Repair: Calculation completed
Mismatch Repair (MMR) Directed by MSH2 MSH3 (MutSbeta): Calculation started
Mismatch Repair (MMR) Directed by MSH2 MSH3 (MutSbeta): scoring computed

Calculating pathways:  36%|███▋      | 51/140 [04:09<05:38,  3.80s/it]

Mismatch Repair (MMR) Directed by MSH2 MSH3 (MutSbeta): pvalue calculation completed
Mismatch Repair (MMR) Directed by MSH2 MSH3 (MutSbeta): Calculation completed
Mismatch Repair (MMR) Directed by MSH2 MSH6 (MutSalpha): Calculation started
Mismatch Repair (MMR) Directed by MSH2 MSH6 (MutSalpha): scoring computed

Calculating pathways:  37%|███▋      | 52/140 [04:12<05:24,  3.69s/it]

Mismatch Repair (MMR) Directed by MSH2 MSH6 (MutSalpha): pvalue calculation completed
Mismatch Repair (MMR) Directed by MSH2 MSH6 (MutSalpha): Calculation completed
Mitotic G1 Phase and G1 S Transition: Calculation started
Mitotic G1 Phase and G1 S Transition: scoring computed

Calculating pathways:  38%|███▊      | 53/140 [04:17<05:49,  4.01s/it]

Mitotic G1 Phase and G1 S Transition: pvalue calculation completed
Mitotic G1 Phase and G1 S Transition: Calculation completed
Nucleotide Excision Repair: Calculation started
Nucleotide Excision Repair: scoring computed

Calculating pathways:  39%|███▊      | 54/140 [04:21<05:56,  4.14s/it]

Nucleotide Excision Repair: pvalue calculation completed
Nucleotide Excision Repair: Calculation completed
Nucleotide Salvage: Calculation started
Nucleotide Salvage: scoring computed

Calculating pathways:  39%|███▉      | 55/140 [04:25<05:36,  3.96s/it]

Nucleotide Salvage: pvalue calculation completed
Nucleotide Salvage: Calculation completed
PCNA-Dependent Long Patch Base Excision Repair: Calculation started
PCNA-Dependent Long Patch Base Excision Repair: scoring computed

Calculating pathways:  40%|████      | 56/140 [04:29<05:28,  3.92s/it]

PCNA-Dependent Long Patch Base Excision Repair: pvalue calculation completed
PCNA-Dependent Long Patch Base Excision Repair: Calculation completed
Polymerase Switching: Calculation started
Polymerase Switching: scoring computed

Calculating pathways:  41%|████      | 57/140 [04:32<05:16,  3.81s/it]

Polymerase Switching: pvalue calculation completed
Polymerase Switching: Calculation completed
Polymerase Switching on the C-strand of the Telomere: Calculation started
Polymerase Switching on the C-strand of the Telomere: scoring computed

Calculating pathways:  41%|████▏     | 58/140 [04:36<05:08,  3.77s/it]

Polymerase Switching on the C-strand of the Telomere: pvalue calculation completed
Polymerase Switching on the C-strand of the Telomere: Calculation completed
Processive Synthesis on the C-strand of the Telomere: Calculation started
Processive Synthesis on the C-strand of the Telomere: scoring computed

Calculating pathways:  42%|████▏     | 59/140 [04:40<05:01,  3.72s/it]

Processive Synthesis on the C-strand of the Telomere: pvalue calculation completed
Processive Synthesis on the C-strand of the Telomere: Calculation completed
Processive Synthesis on the Lagging Strand: Calculation started
Processive Synthesis on the Lagging Strand: scoring computed

Calculating pathways:  43%|████▎     | 60/140 [04:43<04:51,  3.64s/it]

Processive Synthesis on the Lagging Strand: pvalue calculation completed
Processive Synthesis on the Lagging Strand: Calculation completed
Purine Salvage: Calculation started
Purine Salvage: scoring computed

Calculating pathways:  44%|████▎     | 61/140 [04:46<04:43,  3.59s/it]

Purine Salvage: pvalue calculation completed
Purine Salvage: Calculation completed
Pyrimidine Salvage: Calculation started
Pyrimidine Salvage: scoring computed

Calculating pathways:  44%|████▍     | 62/140 [04:50<04:37,  3.56s/it]

Pyrimidine Salvage: pvalue calculation completed
Pyrimidine Salvage: Calculation completed
RNA Polymerase II Transcription: Calculation started
RNA Polymerase II Transcription: scoring computed

Calculating pathways:  45%|████▌     | 63/140 [05:07<09:45,  7.60s/it]

RNA Polymerase II Transcription: pvalue calculation completed
RNA Polymerase II Transcription: Calculation completed
Recognition of DNA Damage by PCNA-containing Replication Complex: Calculation started
Recognition of DNA Damage by PCNA-containing Replication Complex: scoring computed

Calculating pathways:  46%|████▌     | 64/140 [05:11<08:11,  6.46s/it]

Recognition of DNA Damage by PCNA-containing Replication Complex: pvalue calculation completed
Recognition of DNA Damage by PCNA-containing Replication Complex: Calculation completed
Removal of the Flap Intermediate: Calculation started
Removal of the Flap Intermediate: scoring computed

Calculating pathways:  46%|████▋     | 65/140 [05:14<07:00,  5.60s/it]

Removal of the Flap Intermediate: pvalue calculation completed
Removal of the Flap Intermediate: Calculation completed
Removal of the Flap Intermediate From the C-strand: Calculation started
Removal of the Flap Intermediate From the C-strand: scoring computed

Calculating pathways:  47%|████▋     | 66/140 [05:18<06:07,  4.97s/it]

Removal of the Flap Intermediate From the C-strand: pvalue calculation completed
Removal of the Flap Intermediate From the C-strand: Calculation completed
Resolution of AP Sites via the Multiple-Nucleotide Patch Replacement Pathway: Calculation started
Resolution of AP Sites via the Multiple-Nucleotide Patch Replacement Pathway: scoring computed

Calculating pathways:  48%|████▊     | 67/140 [05:21<05:32,  4.55s/it]

Resolution of AP Sites via the Multiple-Nucleotide Patch Replacement Pathway: pvalue calculation completed
Resolution of AP Sites via the Multiple-Nucleotide Patch Replacement Pathway: Calculation completed
Resolution of Abasic Sites (AP Sites): Calculation started
Resolution of Abasic Sites (AP Sites): scoring computed

Calculating pathways:  49%|████▊     | 68/140 [05:25<05:08,  4.28s/it]

Resolution of Abasic Sites (AP Sites): pvalue calculation completed
Resolution of Abasic Sites (AP Sites): Calculation completed
S Phase: Calculation started
S Phase: scoring computed

Calculating pathways:  49%|████▉     | 69/140 [05:30<05:18,  4.48s/it]

S Phase: pvalue calculation completed
S Phase: Calculation completed
Synthesis of DNA: Calculation started
Synthesis of DNA: scoring computed

Calculating pathways:  50%|█████     | 70/140 [05:35<05:18,  4.55s/it]

Synthesis of DNA: pvalue calculation completed
Synthesis of DNA: Calculation completed
Telomere C-strand (Lagging Strand) Synthesis: Calculation started
Telomere C-strand (Lagging Strand) Synthesis: scoring computed

Calculating pathways:  51%|█████     | 71/140 [05:38<04:54,  4.27s/it]

Telomere C-strand (Lagging Strand) Synthesis: pvalue calculation completed
Telomere C-strand (Lagging Strand) Synthesis: Calculation completed
Telomere C-strand Synthesis Initiation: Calculation started
Telomere C-strand Synthesis Initiation: scoring computed

Calculating pathways:  51%|█████▏    | 72/140 [05:42<04:32,  4.00s/it]

Telomere C-strand Synthesis Initiation: pvalue calculation completed
Telomere C-strand Synthesis Initiation: Calculation completed
Telomere Maintenance: Calculation started
Telomere Maintenance: scoring computed

Calculating pathways:  52%|█████▏    | 73/140 [05:46<04:34,  4.10s/it]

Telomere Maintenance: pvalue calculation completed
Telomere Maintenance: Calculation completed
Termination of Translesion DNA Synthesis: Calculation started
Termination of Translesion DNA Synthesis: scoring computed

Calculating pathways:  53%|█████▎    | 74/140 [05:50<04:21,  3.96s/it]

Termination of Translesion DNA Synthesis: pvalue calculation completed
Termination of Translesion DNA Synthesis: Calculation completed
Transcription-Coupled Nucleotide Excision Repair (TC-NER): Calculation started
Transcription-Coupled Nucleotide Excision Repair (TC-NER): scoring computed

Calculating pathways:  54%|█████▎    | 75/140 [05:54<04:20,  4.00s/it]

Transcription-Coupled Nucleotide Excision Repair (TC-NER): pvalue calculation completed
Transcription-Coupled Nucleotide Excision Repair (TC-NER): Calculation completed
Transcriptional Regulation by E2F6: Calculation started
Transcriptional Regulation by E2F6: scoring computed

Calculating pathways:  54%|█████▍    | 76/140 [05:58<04:11,  3.92s/it]

Transcriptional Regulation by E2F6: pvalue calculation completed
Transcriptional Regulation by E2F6: Calculation completed
Translesion Synthesis by Y Family DNA Polymerases Bypasses Lesions on DNA Template: Calculation started
Translesion Synthesis by Y Family DNA Polymerases Bypasses Lesions on DNA Template: scoring computed

Calculating pathways:  55%|█████▌    | 77/140 [06:01<04:02,  3.85s/it]

Translesion Synthesis by Y Family DNA Polymerases Bypasses Lesions on DNA Template: pvalue calculation completed
Translesion Synthesis by Y Family DNA Polymerases Bypasses Lesions on DNA Template: Calculation completed
DNA Biosynthetic Process (GO:0071897): Calculation started
DNA Biosynthetic Process (GO:0071897): scoring computed

Calculating pathways:  56%|█████▌    | 78/140 [06:05<03:53,  3.77s/it]

DNA Biosynthetic Process (GO:0071897): pvalue calculation completed
DNA Biosynthetic Process (GO:0071897): Calculation completed
DNA Damage Response (GO:0006974): Calculation started
DNA Damage Response (GO:0006974): scoring computed

Calculating pathways:  56%|█████▋    | 79/140 [06:13<05:05,  5.02s/it]

DNA Damage Response (GO:0006974): pvalue calculation completed
DNA Damage Response (GO:0006974): Calculation completed
DNA Metabolic Process (GO:0006259): Calculation started
DNA Metabolic Process (GO:0006259): scoring computed

Calculating pathways:  57%|█████▋    | 80/140 [06:19<05:28,  5.47s/it]

DNA Metabolic Process (GO:0006259): pvalue calculation completed
DNA Metabolic Process (GO:0006259): Calculation completed
DNA Repair (GO:0006281): Calculation started
DNA Repair (GO:0006281): scoring computed

Calculating pathways:  58%|█████▊    | 81/140 [06:26<05:40,  5.78s/it]

DNA Repair (GO:0006281): pvalue calculation completed
DNA Repair (GO:0006281): Calculation completed
DNA Replication (GO:0006260): Calculation started
DNA Replication (GO:0006260): scoring computed

Calculating pathways:  59%|█████▊    | 82/140 [06:30<05:08,  5.33s/it]

DNA Replication (GO:0006260): pvalue calculation completed
DNA Replication (GO:0006260): Calculation completed
DNA Replication Initiation (GO:0006270): Calculation started
DNA Replication Initiation (GO:0006270): scoring computed

Calculating pathways:  59%|█████▉    | 83/140 [06:34<04:31,  4.77s/it]

DNA Replication Initiation (GO:0006270): pvalue calculation completed
DNA Replication Initiation (GO:0006270): Calculation completed
DNA Strand Elongation (GO:0022616): Calculation started
DNA Strand Elongation (GO:0022616): scoring computed

Calculating pathways:  60%|██████    | 84/140 [06:37<04:04,  4.36s/it]

DNA Strand Elongation (GO:0022616): pvalue calculation completed
DNA Strand Elongation (GO:0022616): Calculation completed
DNA Strand Elongation Involved in DNA Replication (GO:0006271): Calculation started
DNA Strand Elongation Involved in DNA Replication (GO:0006271): scoring computed

Calculating pathways:  61%|██████    | 85/140 [06:41<03:47,  4.14s/it]

DNA Strand Elongation Involved in DNA Replication (GO:0006271): pvalue calculation completed
DNA Strand Elongation Involved in DNA Replication (GO:0006271): Calculation completed
DNA Synthesis Involved in DNA Repair (GO:0000731): Calculation started
DNA Synthesis Involved in DNA Repair (GO:0000731): scoring computed

Calculating pathways:  61%|██████▏   | 86/140 [06:44<03:34,  3.98s/it]

DNA Synthesis Involved in DNA Repair (GO:0000731): pvalue calculation completed
DNA Synthesis Involved in DNA Repair (GO:0000731): Calculation completed
DNA-templated DNA Replication (GO:0006261): Calculation started
DNA-templated DNA Replication (GO:0006261): scoring computed

Calculating pathways:  62%|██████▏   | 87/140 [06:48<03:31,  3.99s/it]

DNA-templated DNA Replication (GO:0006261): pvalue calculation completed
DNA-templated DNA Replication (GO:0006261): Calculation completed
DNA-templated DNA Replication Maintenance of Fidelity (GO:0045005): Calculation started
DNA-templated DNA Replication Maintenance of Fidelity (GO:0045005): scoring computed

Calculating pathways:  63%|██████▎   | 88/140 [06:52<03:24,  3.92s/it]

DNA-templated DNA Replication Maintenance of Fidelity (GO:0045005): pvalue calculation completed
DNA-templated DNA Replication Maintenance of Fidelity (GO:0045005): Calculation completed
G1/S Transition of Mitotic Cell Cycle (GO:0000082): Calculation started
G1/S Transition of Mitotic Cell Cycle (GO:0000082): scoring computed

Calculating pathways:  64%|██████▎   | 89/140 [06:56<03:22,  3.96s/it]

G1/S Transition of Mitotic Cell Cycle (GO:0000082): pvalue calculation completed
G1/S Transition of Mitotic Cell Cycle (GO:0000082): Calculation completed
RNA Biosynthetic Process (GO:0032774): Calculation started
RNA Biosynthetic Process (GO:0032774): scoring computed

Calculating pathways:  64%|██████▍   | 90/140 [07:01<03:30,  4.20s/it]

RNA Biosynthetic Process (GO:0032774): pvalue calculation completed
RNA Biosynthetic Process (GO:0032774): Calculation completed
UDP Metabolic Process (GO:0046048): Calculation started
UDP Metabolic Process (GO:0046048): scoring computed

Calculating pathways:  65%|██████▌   | 91/140 [07:04<03:15,  3.98s/it]

UDP Metabolic Process (GO:0046048): pvalue calculation completed
UDP Metabolic Process (GO:0046048): Calculation completed
UV-damage Excision Repair (GO:0070914): Calculation started
UV-damage Excision Repair (GO:0070914): scoring computed

Calculating pathways:  66%|██████▌   | 92/140 [07:08<03:03,  3.82s/it]

UV-damage Excision Repair (GO:0070914): pvalue calculation completed
UV-damage Excision Repair (GO:0070914): Calculation completed
Base-Excision Repair (GO:0006284): Calculation started
Base-Excision Repair (GO:0006284): scoring computed

Calculating pathways:  66%|██████▋   | 93/140 [07:11<02:56,  3.76s/it]

Base-Excision Repair (GO:0006284): pvalue calculation completed
Base-Excision Repair (GO:0006284): Calculation completed
Base-Excision Repair, Gap-Filling (GO:0006287): Calculation started
Base-Excision Repair, Gap-Filling (GO:0006287): scoring computed

Calculating pathways:  67%|██████▋   | 94/140 [07:15<02:52,  3.75s/it]

Base-Excision Repair, Gap-Filling (GO:0006287): pvalue calculation completed
Base-Excision Repair, Gap-Filling (GO:0006287): Calculation completed
Carbohydrate Derivative Biosynthetic Process (GO:1901137): Calculation started
Carbohydrate Derivative Biosynthetic Process (GO:1901137): scoring computed

Calculating pathways:  68%|██████▊   | 95/140 [07:19<02:48,  3.75s/it]

Carbohydrate Derivative Biosynthetic Process (GO:1901137): pvalue calculation completed
Carbohydrate Derivative Biosynthetic Process (GO:1901137): Calculation completed
Cell Cycle G1/S Phase Transition (GO:0044843): Calculation started
Cell Cycle G1/S Phase Transition (GO:0044843): scoring computed

Calculating pathways:  69%|██████▊   | 96/140 [07:23<02:49,  3.84s/it]

Cell Cycle G1/S Phase Transition (GO:0044843): pvalue calculation completed
Cell Cycle G1/S Phase Transition (GO:0044843): Calculation completed
Cellular Response to UV (GO:0034644): Calculation started
Cellular Response to UV (GO:0034644): scoring computed

Calculating pathways:  69%|██████▉   | 97/140 [07:27<02:49,  3.94s/it]

Cellular Response to UV (GO:0034644): pvalue calculation completed
Cellular Response to UV (GO:0034644): Calculation completed
Cellular Response to Light Stimulus (GO:0071482): Calculation started
Cellular Response to Light Stimulus (GO:0071482): scoring computed

Calculating pathways:  70%|███████   | 98/140 [07:31<02:47,  3.99s/it]

Cellular Response to Light Stimulus (GO:0071482): pvalue calculation completed
Cellular Response to Light Stimulus (GO:0071482): Calculation completed
Double-Strand Break Repair (GO:0006302): Calculation started
Double-Strand Break Repair (GO:0006302): scoring computed

Calculating pathways:  71%|███████   | 99/140 [07:36<02:57,  4.32s/it]

Double-Strand Break Repair (GO:0006302): pvalue calculation completed
Double-Strand Break Repair (GO:0006302): Calculation completed
Double-Strand Break Repair via Nonhomologous End Joining (GO:0006303): Calculation started
Double-Strand Break Repair via Nonhomologous End Joining (GO:0006303): scoring computed

Calculating pathways:  71%|███████▏  | 100/140 [07:40<02:46,  4.17s/it]

Double-Strand Break Repair via Nonhomologous End Joining (GO:0006303): pvalue calculation completed
Double-Strand Break Repair via Nonhomologous End Joining (GO:0006303): Calculation completed
Fatty Acid Homeostasis (GO:0055089): Calculation started
Fatty Acid Homeostasis (GO:0055089): scoring computed

Calculating pathways:  72%|███████▏  | 101/140 [07:43<02:33,  3.92s/it]

Fatty Acid Homeostasis (GO:0055089): pvalue calculation completed
Fatty Acid Homeostasis (GO:0055089): Calculation completed
Mitochondrial DNA Metabolic Process (GO:0032042): Calculation started
Mitochondrial DNA Metabolic Process (GO:0032042): scoring computed

Calculating pathways:  73%|███████▎  | 102/140 [07:47<02:24,  3.81s/it]

Mitochondrial DNA Metabolic Process (GO:0032042): pvalue calculation completed
Mitochondrial DNA Metabolic Process (GO:0032042): Calculation completed
Mitochondrial DNA Replication (GO:0006264): Calculation started
Mitochondrial DNA Replication (GO:0006264): scoring computed

Calculating pathways:  74%|███████▎  | 103/140 [07:50<02:16,  3.69s/it]

Mitochondrial DNA Replication (GO:0006264): pvalue calculation completed
Mitochondrial DNA Replication (GO:0006264): Calculation completed
Mitotic DNA Replication (GO:1902969): Calculation started
Mitotic DNA Replication (GO:1902969): scoring computed

Calculating pathways:  74%|███████▍  | 104/140 [07:54<02:10,  3.61s/it]

Mitotic DNA Replication (GO:1902969): pvalue calculation completed
Mitotic DNA Replication (GO:1902969): Calculation completed
Mitotic Cell Cycle Phase Transition (GO:0044772): Calculation started
Mitotic Cell Cycle Phase Transition (GO:0044772): scoring computed

Calculating pathways:  75%|███████▌  | 105/140 [07:58<02:17,  3.93s/it]

Mitotic Cell Cycle Phase Transition (GO:0044772): pvalue calculation completed
Mitotic Cell Cycle Phase Transition (GO:0044772): Calculation completed
Negative Regulation of Gene Expression (GO:0010629): Calculation started
Negative Regulation of Gene Expression (GO:0010629): scoring computed

Calculating pathways:  76%|███████▌  | 106/140 [08:06<02:49,  4.98s/it]

Negative Regulation of Gene Expression (GO:0010629): pvalue calculation completed
Negative Regulation of Gene Expression (GO:0010629): Calculation completed
Negative Regulation of Protein Metabolic Process (GO:0051248): Calculation started
Negative Regulation of Protein Metabolic Process (GO:0051248): scoring computed

Calculating pathways:  76%|███████▋  | 107/140 [08:11<02:44,  4.97s/it]

Negative Regulation of Protein Metabolic Process (GO:0051248): pvalue calculation completed
Negative Regulation of Protein Metabolic Process (GO:0051248): Calculation completed
Negative Regulation of Translation (GO:0017148): Calculation started
Negative Regulation of Translation (GO:0017148): scoring computed

Calculating pathways:  77%|███████▋  | 108/140 [08:15<02:35,  4.85s/it]

Negative Regulation of Translation (GO:0017148): pvalue calculation completed
Negative Regulation of Translation (GO:0017148): Calculation completed
Nucleic Acid Biosynthetic Process (GO:0141187): Calculation started
Nucleic Acid Biosynthetic Process (GO:0141187): scoring computed

Calculating pathways:  78%|███████▊  | 109/140 [08:19<02:16,  4.41s/it]

Nucleic Acid Biosynthetic Process (GO:0141187): pvalue calculation completed
Nucleic Acid Biosynthetic Process (GO:0141187): Calculation completed
Nucleobase-Containing Small Molecule Interconversion (GO:0015949): Calculation started
Nucleobase-Containing Small Molecule Interconversion (GO:0015949): scoring computed

Calculating pathways:  79%|███████▊  | 110/140 [08:22<02:03,  4.10s/it]

Nucleobase-Containing Small Molecule Interconversion (GO:0015949): pvalue calculation completed
Nucleobase-Containing Small Molecule Interconversion (GO:0015949): Calculation completed
Nucleobase-Containing Small Molecule Metabolic Process (GO:0055086): Calculation started
Nucleobase-Containing Small Molecule Metabolic Process (GO:0055086): scoring computed

Calculating pathways:  79%|███████▉  | 111/140 [08:26<01:53,  3.93s/it]

Nucleobase-Containing Small Molecule Metabolic Process (GO:0055086): pvalue calculation completed
Nucleobase-Containing Small Molecule Metabolic Process (GO:0055086): Calculation completed
Nucleoside Diphosphate Metabolic Process (GO:0009132): Calculation started
Nucleoside Diphosphate Metabolic Process (GO:0009132): scoring computed

Calculating pathways:  80%|████████  | 112/140 [08:29<01:45,  3.76s/it]

Nucleoside Diphosphate Metabolic Process (GO:0009132): pvalue calculation completed
Nucleoside Diphosphate Metabolic Process (GO:0009132): Calculation completed
Nucleoside Phosphate Biosynthetic Process (GO:1901293): Calculation started
Nucleoside Phosphate Biosynthetic Process (GO:1901293): scoring computed

Calculating pathways:  81%|████████  | 113/140 [08:33<01:39,  3.70s/it]

Nucleoside Phosphate Biosynthetic Process (GO:1901293): pvalue calculation completed
Nucleoside Phosphate Biosynthetic Process (GO:1901293): Calculation completed
Nucleoside Phosphate Metabolic Process (GO:0006753): Calculation started
Nucleoside Phosphate Metabolic Process (GO:0006753): scoring computed

Calculating pathways:  81%|████████▏ | 114/140 [08:36<01:37,  3.75s/it]

Nucleoside Phosphate Metabolic Process (GO:0006753): pvalue calculation completed
Nucleoside Phosphate Metabolic Process (GO:0006753): Calculation completed
Nucleotide Biosynthetic Process (GO:0009165): Calculation started
Nucleotide Biosynthetic Process (GO:0009165): scoring computed

Calculating pathways:  82%|████████▏ | 115/140 [08:40<01:31,  3.67s/it]

Nucleotide Biosynthetic Process (GO:0009165): pvalue calculation completed
Nucleotide Biosynthetic Process (GO:0009165): Calculation completed
Nucleotide Metabolic Process (GO:0009117): Calculation started
Nucleotide Metabolic Process (GO:0009117): scoring computed

Calculating pathways:  83%|████████▎ | 116/140 [08:43<01:26,  3.61s/it]

Nucleotide Metabolic Process (GO:0009117): pvalue calculation completed
Nucleotide Metabolic Process (GO:0009117): Calculation completed
Nucleotide-Excision Repair (GO:0006289): Calculation started
Nucleotide-Excision Repair (GO:0006289): scoring computed

Calculating pathways:  84%|████████▎ | 117/140 [08:47<01:25,  3.70s/it]

Nucleotide-Excision Repair (GO:0006289): pvalue calculation completed
Nucleotide-Excision Repair (GO:0006289): Calculation completed
Nucleotide-Excision Repair, DNA Gap Filling (GO:0006297): Calculation started
Nucleotide-Excision Repair, DNA Gap Filling (GO:0006297): scoring computed

Calculating pathways:  84%|████████▍ | 118/140 [08:51<01:19,  3.62s/it]

Nucleotide-Excision Repair, DNA Gap Filling (GO:0006297): pvalue calculation completed
Nucleotide-Excision Repair, DNA Gap Filling (GO:0006297): Calculation completed
One-Carbon Metabolic Process (GO:0006730): Calculation started
One-Carbon Metabolic Process (GO:0006730): scoring computed

Calculating pathways:  85%|████████▌ | 119/140 [08:54<01:14,  3.55s/it]

One-Carbon Metabolic Process (GO:0006730): pvalue calculation completed
One-Carbon Metabolic Process (GO:0006730): Calculation completed
Organophosphate Biosynthetic Process (GO:0090407): Calculation started
Organophosphate Biosynthetic Process (GO:0090407): scoring computed

Calculating pathways:  86%|████████▌ | 120/140 [08:58<01:12,  3.61s/it]

Organophosphate Biosynthetic Process (GO:0090407): pvalue calculation completed
Organophosphate Biosynthetic Process (GO:0090407): Calculation completed
Positive Regulation of G1/S Transition of Mitotic Cell Cycle (GO:1900087): Calculation started
Positive Regulation of G1/S Transition of Mitotic Cell Cycle (GO:1900087): scoring computed

Calculating pathways:  86%|████████▋ | 121/140 [09:02<01:08,  3.62s/it]

Positive Regulation of G1/S Transition of Mitotic Cell Cycle (GO:1900087): pvalue calculation completed
Positive Regulation of G1/S Transition of Mitotic Cell Cycle (GO:1900087): Calculation completed
Positive Regulation of G2/M Transition of Mitotic Cell Cycle (GO:0010971): Calculation started
Positive Regulation of G2/M Transition of Mitotic Cell Cycle (GO:0010971): scoring computed

Calculating pathways:  87%|████████▋ | 122/140 [09:05<01:04,  3.58s/it]

Positive Regulation of G2/M Transition of Mitotic Cell Cycle (GO:0010971): pvalue calculation completed
Positive Regulation of G2/M Transition of Mitotic Cell Cycle (GO:0010971): Calculation completed
Positive Regulation of Cell Cycle G1/S Phase Transition (GO:1902808): Calculation started
Positive Regulation of Cell Cycle G1/S Phase Transition (GO:1902808): scoring computed

Calculating pathways:  88%|████████▊ | 123/140 [09:09<01:01,  3.64s/it]

Positive Regulation of Cell Cycle G1/S Phase Transition (GO:1902808): pvalue calculation completed
Positive Regulation of Cell Cycle G1/S Phase Transition (GO:1902808): Calculation completed
Positive Regulation of Cell Cycle G2/M Phase Transition (GO:1902751): Calculation started
Positive Regulation of Cell Cycle G2/M Phase Transition (GO:1902751): scoring computed

Calculating pathways:  89%|████████▊ | 124/140 [09:12<00:58,  3.63s/it]

Positive Regulation of Cell Cycle G2/M Phase Transition (GO:1902751): pvalue calculation completed
Positive Regulation of Cell Cycle G2/M Phase Transition (GO:1902751): Calculation completed
Positive Regulation of Cell Cycle Process (GO:0090068): Calculation started
Positive Regulation of Cell Cycle Process (GO:0090068): scoring computed

Calculating pathways:  89%|████████▉ | 125/140 [09:17<00:58,  3.87s/it]

Positive Regulation of Cell Cycle Process (GO:0090068): pvalue calculation completed
Positive Regulation of Cell Cycle Process (GO:0090068): Calculation completed
Positive Regulation of Mitotic Cell Cycle Phase Transition (GO:1901992): Calculation started
Positive Regulation of Mitotic Cell Cycle Phase Transition (GO:1901992): scoring computed

Calculating pathways:  90%|█████████ | 126/140 [09:21<00:55,  3.94s/it]

Positive Regulation of Mitotic Cell Cycle Phase Transition (GO:1901992): pvalue calculation completed
Positive Regulation of Mitotic Cell Cycle Phase Transition (GO:1901992): Calculation completed
Pyrimidine Nucleotide Metabolic Process (GO:0006220): Calculation started
Pyrimidine Nucleotide Metabolic Process (GO:0006220): scoring computed

Calculating pathways:  91%|█████████ | 127/140 [09:24<00:48,  3.75s/it]

Pyrimidine Nucleotide Metabolic Process (GO:0006220): pvalue calculation completed
Pyrimidine Nucleotide Metabolic Process (GO:0006220): Calculation completed
Pyrimidine Ribonucleotide Biosynthetic Process (GO:0009220): Calculation started
Pyrimidine Ribonucleotide Biosynthetic Process (GO:0009220): scoring computed

Calculating pathways:  91%|█████████▏| 128/140 [09:28<00:43,  3.67s/it]

Pyrimidine Ribonucleotide Biosynthetic Process (GO:0009220): pvalue calculation completed
Pyrimidine Ribonucleotide Biosynthetic Process (GO:0009220): Calculation completed
Pyrimidine Ribonucleotide Metabolic Process (GO:0009218): Calculation started
Pyrimidine Ribonucleotide Metabolic Process (GO:0009218): scoring computed

Calculating pathways:  92%|█████████▏| 129/140 [09:31<00:39,  3.57s/it]

Pyrimidine Ribonucleotide Metabolic Process (GO:0009218): pvalue calculation completed
Pyrimidine Ribonucleotide Metabolic Process (GO:0009218): Calculation completed
Regulation of G0 to G1 Transition (GO:0070316): Calculation started
Regulation of G0 to G1 Transition (GO:0070316): scoring computed

Calculating pathways:  93%|█████████▎| 130/140 [09:35<00:36,  3.62s/it]

Regulation of G0 to G1 Transition (GO:0070316): pvalue calculation completed
Regulation of G0 to G1 Transition (GO:0070316): Calculation completed
Regulation of G1/S Transition of Mitotic Cell Cycle (GO:2000045): Calculation started
Regulation of G1/S Transition of Mitotic Cell Cycle (GO:2000045): scoring computed

Calculating pathways:  94%|█████████▎| 131/140 [09:39<00:34,  3.87s/it]

Regulation of G1/S Transition of Mitotic Cell Cycle (GO:2000045): pvalue calculation completed
Regulation of G1/S Transition of Mitotic Cell Cycle (GO:2000045): Calculation completed
Regulation of G2/M Transition of Mitotic Cell Cycle (GO:0010389): Calculation started
Regulation of G2/M Transition of Mitotic Cell Cycle (GO:0010389): scoring computed

Calculating pathways:  94%|█████████▍| 132/140 [09:43<00:30,  3.85s/it]

Regulation of G2/M Transition of Mitotic Cell Cycle (GO:0010389): pvalue calculation completed
Regulation of G2/M Transition of Mitotic Cell Cycle (GO:0010389): Calculation completed
Regulation of Cytokine Production (GO:0001817): Calculation started
Regulation of Cytokine Production (GO:0001817): scoring computed

Calculating pathways:  95%|█████████▌| 133/140 [09:48<00:29,  4.23s/it]

Regulation of Cytokine Production (GO:0001817): pvalue calculation completed
Regulation of Cytokine Production (GO:0001817): Calculation completed
Regulation of Translation (GO:0006417): Calculation started
Regulation of Translation (GO:0006417): scoring computed

Calculating pathways:  96%|█████████▌| 134/140 [09:54<00:27,  4.60s/it]

Regulation of Translation (GO:0006417): pvalue calculation completed
Regulation of Translation (GO:0006417): Calculation completed
Regulation of Type I Interferon Production (GO:0032479): Calculation started
Regulation of Type I Interferon Production (GO:0032479): scoring computed

Calculating pathways:  96%|█████████▋| 135/140 [09:58<00:22,  4.44s/it]

Regulation of Type I Interferon Production (GO:0032479): pvalue calculation completed
Regulation of Type I Interferon Production (GO:0032479): Calculation completed
Response to UV (GO:0009411): Calculation started
Response to UV (GO:0009411): scoring computed

Calculating pathways:  97%|█████████▋| 136/140 [10:02<00:17,  4.42s/it]

Response to UV (GO:0009411): pvalue calculation completed
Response to UV (GO:0009411): Calculation completed
Response to Light Stimulus (GO:0009416): Calculation started
Response to Light Stimulus (GO:0009416): scoring computed

Calculating pathways:  98%|█████████▊| 137/140 [10:06<00:12,  4.29s/it]

Response to Light Stimulus (GO:0009416): pvalue calculation completed
Response to Light Stimulus (GO:0009416): Calculation completed
Tetrahydrofolate Interconversion (GO:0035999): Calculation started
Tetrahydrofolate Interconversion (GO:0035999): scoring computed

Calculating pathways:  99%|█████████▊| 138/140 [10:09<00:08,  4.00s/it]

Tetrahydrofolate Interconversion (GO:0035999): pvalue calculation completed
Tetrahydrofolate Interconversion (GO:0035999): Calculation completed
Tetrahydrofolate Metabolic Process (GO:0046653): Calculation started
Tetrahydrofolate Metabolic Process (GO:0046653): scoring computed

Calculating pathways:  99%|█████████▉| 139/140 [10:13<00:03,  3.85s/it]

Tetrahydrofolate Metabolic Process (GO:0046653): pvalue calculation completed
Tetrahydrofolate Metabolic Process (GO:0046653): Calculation completed
Translesion Synthesis (GO:0019985): Calculation started
Translesion Synthesis (GO:0019985): scoring computed

Calculating pathways: 100%|██████████| 140/140 [10:16<00:00,  4.41s/it]

Translesion Synthesis (GO:0019985): pvalue calculation completed
Translesion Synthesis (GO:0019985): Calculation completed

## Paclitaxel

In [14]:
#loading drug_data
drug_data = json.load(open("singscore_new_code/Paclitaxel/Paclitaxel_relevant_pathways.json"))
count = len(drug_data)
print("Number of items:", count)

final_result = {}

for key, value in tqdm(drug_data.items(), desc="Calculating pathways"):
    print(f"{key}: Calculation started")
    up = drug_data[key]
    up_present = [gene for gene in up if gene in uk65.index]

    # Print counts and summary
    # print(f"Total up genes in signature: {len(up)}")
    # print(f"Up genes found in expression data: {len(up_present)}")

    # Optionally, print the missing ones
    missing_up = set(up) - set(uk65.index)

    # print(f"Missing up genes: {len(missing_up)}")
    scored_data = score(up_gene=up, down_gene=False, sample=uk65,
                    norm_method='theoretical', full_data=True)
    #getting the scored data for a pathway
    total_score = scored_data["total_score"].to_list()[0]
    print(f"{key}: scoring computed")
    permd = permutate(uk65, n_up=len(up_present), n_down=False)
    pvals = empiricalpval(permutations=permd, score=scored_data)
    empirical_p_value = pvals["empirical p value"].to_list()[0]
    print(f"{key}: pvalue calculation completed")
    result = {
    f"{key}":{
        "gene_set_info": {
            "geneset_size": len(up),
            "geneset_covered_in_sample": len(up_present)
        },
        "scores": {
            "total_singscore": total_score
        },
        "statistics": {
            "p_value": empirical_p_value,
            "method": "permutation (empirical)",
            "permutations": 10000
        }}}
    print(f"{key}: Calculation completed")
    final_result.update(result)

# Save final combined JSON
with open("singscore_new_code/Paclitaxel/Paclitaxel_singscore_results.json", "w", encoding="utf-8") as f:
    json.dump(final_result, f, indent=2, ensure_ascii=False)

Number of items: 583

Calculating pathways:   0%|          | 0/583 [00:00<?, ?it/s]

TNF-alpha Signaling via NF-kB: Calculation started
TNF-alpha Signaling via NF-kB: scoring computed

Calculating pathways:   0%|          | 1/583 [00:05<53:08,  5.48s/it]

TNF-alpha Signaling via NF-kB: pvalue calculation completed
TNF-alpha Signaling via NF-kB: Calculation completed
Estrogen Response Early: Calculation started
Estrogen Response Early: scoring computed

Calculating pathways:   0%|          | 2/583 [00:11<54:04,  5.58s/it]

Estrogen Response Early: pvalue calculation completed
Estrogen Response Early: Calculation completed
Androgen Response: Calculation started
Androgen Response: scoring computed

Calculating pathways:   1%|          | 3/583 [00:15<48:42,  5.04s/it]

Androgen Response: pvalue calculation completed
Androgen Response: Calculation completed
Complement: Calculation started
Complement: scoring computed

Calculating pathways:   1%|          | 4/583 [00:20<50:04,  5.19s/it]

Complement: pvalue calculation completed
Complement: Calculation completed
Unfolded Protein Response: Calculation started
Unfolded Protein Response: scoring computed

Calculating pathways:   1%|          | 5/583 [00:25<48:12,  5.00s/it]

Unfolded Protein Response: pvalue calculation completed
Unfolded Protein Response: Calculation completed
E2F Targets: Calculation started
E2F Targets: scoring computed

Calculating pathways:   1%|          | 6/583 [00:31<50:07,  5.21s/it]

E2F Targets: pvalue calculation completed
E2F Targets: Calculation completed
Inflammatory Response: Calculation started
Inflammatory Response: scoring computed

Calculating pathways:   1%|          | 7/583 [00:36<50:56,  5.31s/it]

Inflammatory Response: pvalue calculation completed
Inflammatory Response: Calculation completed
UV Response Up: Calculation started
UV Response Up: scoring computed

Calculating pathways:   1%|▏         | 8/583 [00:41<49:55,  5.21s/it]

UV Response Up: pvalue calculation completed
UV Response Up: Calculation completed
UV Response Dn: Calculation started
UV Response Dn: scoring computed

Calculating pathways:   2%|▏         | 9/583 [00:46<49:00,  5.12s/it]

UV Response Dn: pvalue calculation completed
UV Response Dn: Calculation completed
Coagulation: Calculation started
Coagulation: scoring computed

Calculating pathways:   2%|▏         | 10/583 [00:51<47:22,  4.96s/it]

Coagulation: pvalue calculation completed
Coagulation: Calculation completed
IL-2/STAT5 Signaling: Calculation started
IL-2/STAT5 Signaling: scoring computed

Calculating pathways:   2%|▏         | 11/583 [00:56<49:07,  5.15s/it]

IL-2/STAT5 Signaling: pvalue calculation completed
IL-2/STAT5 Signaling: Calculation completed
Bile Acid Metabolism: Calculation started
Bile Acid Metabolism: scoring computed

Calculating pathways:   2%|▏         | 12/583 [01:01<47:47,  5.02s/it]

Bile Acid Metabolism: pvalue calculation completed
Bile Acid Metabolism: Calculation completed
Pperoxisome: Calculation started
Pperoxisome: scoring computed

Calculating pathways:   2%|▏         | 13/583 [01:06<46:00,  4.84s/it]

Pperoxisome: pvalue calculation completed
Pperoxisome: Calculation completed
KRAS Signaling Up: Calculation started
KRAS Signaling Up: scoring computed

Calculating pathways:   2%|▏         | 14/583 [01:11<47:39,  5.03s/it]

KRAS Signaling Up: pvalue calculation completed
KRAS Signaling Up: Calculation completed
KRAS Signaling Dn: Calculation started
KRAS Signaling Dn: scoring computed

Calculating pathways:   3%|▎         | 15/583 [01:16<47:30,  5.02s/it]

KRAS Signaling Dn: pvalue calculation completed
KRAS Signaling Dn: Calculation completed
ABC transporters: Calculation started
ABC transporters: scoring computed

Calculating pathways:   3%|▎         | 16/583 [01:20<43:52,  4.64s/it]

ABC transporters: pvalue calculation completed
ABC transporters: Calculation completed
Adherens junction: Calculation started
Adherens junction: scoring computed

Calculating pathways:   3%|▎         | 17/583 [01:24<42:00,  4.45s/it]

Adherens junction: pvalue calculation completed
Adherens junction: Calculation completed
Alzheimer disease: Calculation started
Alzheimer disease: scoring computed

Calculating pathways:   3%|▎         | 18/583 [01:31<49:15,  5.23s/it]

Alzheimer disease: pvalue calculation completed
Alzheimer disease: Calculation completed
Amyotrophic lateral sclerosis: Calculation started
Amyotrophic lateral sclerosis: scoring computed

Calculating pathways:   3%|▎         | 19/583 [01:38<54:13,  5.77s/it]

Amyotrophic lateral sclerosis: pvalue calculation completed
Amyotrophic lateral sclerosis: Calculation completed
Autophagy: Calculation started
Autophagy: scoring computed

Calculating pathways:   3%|▎         | 20/583 [01:43<52:18,  5.58s/it]

Autophagy: pvalue calculation completed
Autophagy: Calculation completed
Axon guidance: Calculation started
Axon guidance: scoring computed

Calculating pathways:   4%|▎         | 21/583 [01:48<51:35,  5.51s/it]

Axon guidance: pvalue calculation completed
Axon guidance: Calculation completed
Bile secretion: Calculation started
Bile secretion: scoring computed

Calculating pathways:   4%|▍         | 22/583 [01:52<47:21,  5.06s/it]

Bile secretion: pvalue calculation completed
Bile secretion: Calculation completed
Bladder cancer: Calculation started
Bladder cancer: scoring computed

Calculating pathways:   4%|▍         | 23/583 [01:56<43:43,  4.68s/it]

Bladder cancer: pvalue calculation completed
Bladder cancer: Calculation completed
Breast cancer: Calculation started
Breast cancer: scoring computed

Calculating pathways:   4%|▍         | 24/583 [02:01<43:57,  4.72s/it]

Breast cancer: pvalue calculation completed
Breast cancer: Calculation completed
Calcium signaling pathway: Calculation started
Calcium signaling pathway: scoring computed

Calculating pathways:   4%|▍         | 25/583 [02:07<46:54,  5.04s/it]

Calcium signaling pathway: pvalue calculation completed
Calcium signaling pathway: Calculation completed
Central carbon metabolism in cancer: Calculation started
Central carbon metabolism in cancer: scoring computed

Calculating pathways:   4%|▍         | 26/583 [02:11<44:30,  4.79s/it]

Central carbon metabolism in cancer: pvalue calculation completed
Central carbon metabolism in cancer: Calculation completed
Cholesterol metabolism: Calculation started
Cholesterol metabolism: scoring computed

Calculating pathways:   5%|▍         | 27/583 [02:15<41:32,  4.48s/it]

Cholesterol metabolism: pvalue calculation completed
Cholesterol metabolism: Calculation completed
Cholinergic synapse: Calculation started
Cholinergic synapse: scoring computed

Calculating pathways:   5%|▍         | 28/583 [02:19<41:34,  4.49s/it]

Cholinergic synapse: pvalue calculation completed
Cholinergic synapse: Calculation completed
Endometrial cancer: Calculation started
Endometrial cancer: scoring computed

Calculating pathways:   5%|▍         | 29/583 [02:23<40:00,  4.33s/it]

Endometrial cancer: pvalue calculation completed
Endometrial cancer: Calculation completed
ErbB signaling pathway: Calculation started
ErbB signaling pathway: scoring computed

Calculating pathways:   5%|▌         | 30/583 [02:28<40:02,  4.34s/it]

ErbB signaling pathway: pvalue calculation completed
ErbB signaling pathway: Calculation completed
Fc epsilon RI signaling pathway: Calculation started
Fc epsilon RI signaling pathway: scoring computed

Calculating pathways:   5%|▌         | 31/583 [02:32<39:02,  4.24s/it]

Fc epsilon RI signaling pathway: pvalue calculation completed
Fc epsilon RI signaling pathway: Calculation completed
Focal adhesion: Calculation started
Focal adhesion: scoring computed

Calculating pathways:   5%|▌         | 32/583 [02:37<42:10,  4.59s/it]

Focal adhesion: pvalue calculation completed
Focal adhesion: Calculation completed
Gap junction: Calculation started
Gap junction: scoring computed

Calculating pathways:   6%|▌         | 33/583 [02:41<40:56,  4.47s/it]

Gap junction: pvalue calculation completed
Gap junction: Calculation completed
Gastric cancer: Calculation started
Gastric cancer: scoring computed

Calculating pathways:   6%|▌         | 34/583 [02:46<41:54,  4.58s/it]

Gastric cancer: pvalue calculation completed
Gastric cancer: Calculation completed
HIF-1 signaling pathway: Calculation started
HIF-1 signaling pathway: scoring computed

Calculating pathways:   6%|▌         | 35/583 [02:50<41:20,  4.53s/it]

HIF-1 signaling pathway: pvalue calculation completed
HIF-1 signaling pathway: Calculation completed
Huntington disease: Calculation started
Huntington disease: scoring computed

Calculating pathways:   6%|▌         | 36/583 [02:57<46:44,  5.13s/it]

Huntington disease: pvalue calculation completed
Huntington disease: Calculation completed
Inflammatory bowel disease: Calculation started
Inflammatory bowel disease: scoring computed

Calculating pathways:   6%|▋         | 37/583 [03:01<43:12,  4.75s/it]

Inflammatory bowel disease: pvalue calculation completed
Inflammatory bowel disease: Calculation completed
Insulin secretion: Calculation started
Insulin secretion: scoring computed

Calculating pathways:   7%|▋         | 38/583 [03:05<41:29,  4.57s/it]

Insulin secretion: pvalue calculation completed
Insulin secretion: Calculation completed
MAPK signaling pathway: Calculation started
MAPK signaling pathway: scoring computed

Calculating pathways:   7%|▋         | 39/583 [03:11<46:05,  5.08s/it]

MAPK signaling pathway: pvalue calculation completed
MAPK signaling pathway: Calculation completed
MicroRNAs in cancer: Calculation started
MicroRNAs in cancer: scoring computed

Calculating pathways:   7%|▋         | 40/583 [03:17<47:19,  5.23s/it]

MicroRNAs in cancer: pvalue calculation completed
MicroRNAs in cancer: Calculation completed
NOD-like receptor signaling pathway: Calculation started
NOD-like receptor signaling pathway: scoring computed

Calculating pathways:   7%|▋         | 41/583 [03:22<47:37,  5.27s/it]

NOD-like receptor signaling pathway: pvalue calculation completed
NOD-like receptor signaling pathway: Calculation completed
Natural killer cell mediated cytotoxicity: Calculation started
Natural killer cell mediated cytotoxicity: scoring computed

Calculating pathways:   7%|▋         | 42/583 [03:27<45:27,  5.04s/it]

Natural killer cell mediated cytotoxicity: pvalue calculation completed
Natural killer cell mediated cytotoxicity: Calculation completed
Neuroactive ligand-receptor interaction: Calculation started
Neuroactive ligand-receptor interaction: scoring computed

Calculating pathways:   7%|▋         | 43/583 [03:33<47:42,  5.30s/it]

Neuroactive ligand-receptor interaction: pvalue calculation completed
Neuroactive ligand-receptor interaction: Calculation completed
Non-small cell lung cancer: Calculation started
Non-small cell lung cancer: scoring computed

Calculating pathways:   8%|▊         | 44/583 [03:37<44:33,  4.96s/it]

Non-small cell lung cancer: pvalue calculation completed
Non-small cell lung cancer: Calculation completed
Osteoclast differentiation: Calculation started
Osteoclast differentiation: scoring computed

Calculating pathways:   8%|▊         | 45/583 [03:42<44:31,  4.97s/it]

Osteoclast differentiation: pvalue calculation completed
Osteoclast differentiation: Calculation completed
PI3K-Akt signaling pathway: Calculation started
PI3K-Akt signaling pathway: scoring computed

Calculating pathways:   8%|▊         | 46/583 [03:49<49:55,  5.58s/it]

PI3K-Akt signaling pathway: pvalue calculation completed
PI3K-Akt signaling pathway: Calculation completed
Pancreatic cancer: Calculation started
Pancreatic cancer: scoring computed

Calculating pathways:   8%|▊         | 47/583 [03:53<46:01,  5.15s/it]

Pancreatic cancer: pvalue calculation completed
Pancreatic cancer: Calculation completed
Pancreatic secretion: Calculation started
Pancreatic secretion: scoring computed

Calculating pathways:   8%|▊         | 48/583 [03:57<43:32,  4.88s/it]

Pancreatic secretion: pvalue calculation completed
Pancreatic secretion: Calculation completed
Parkinson disease: Calculation started
Parkinson disease: scoring computed

Calculating pathways:   8%|▊         | 49/583 [04:03<45:46,  5.14s/it]

Parkinson disease: pvalue calculation completed
Parkinson disease: Calculation completed
Pathogenic Escherichia coli infection: Calculation started
Pathogenic Escherichia coli infection: scoring computed

Calculating pathways:   9%|▊         | 50/583 [04:08<46:10,  5.20s/it]

Pathogenic Escherichia coli infection: pvalue calculation completed
Pathogenic Escherichia coli infection: Calculation completed
Pathways in cancer: Calculation started
Pathways in cancer: scoring computed

Calculating pathways:   9%|▊         | 51/583 [04:17<55:59,  6.32s/it]

Pathways in cancer: pvalue calculation completed
Pathways in cancer: Calculation completed
Pathways of neurodegeneration: Calculation started
Pathways of neurodegeneration: scoring computed

Calculating pathways:   9%|▉         | 52/583 [04:25<1:01:06,  6.91s/it]

Pathways of neurodegeneration: pvalue calculation completed
Pathways of neurodegeneration: Calculation completed
Phagosome: Calculation started
Phagosome: scoring computed

Calculating pathways:   9%|▉         | 53/583 [04:30<55:30,  6.28s/it]

Phagosome: pvalue calculation completed
Phagosome: Calculation completed
Phospholipase D signaling pathway: Calculation started
Phospholipase D signaling pathway: scoring computed

Calculating pathways:   9%|▉         | 54/583 [04:35<51:53,  5.89s/it]

Phospholipase D signaling pathway: pvalue calculation completed
Phospholipase D signaling pathway: Calculation completed
Platelet activation: Calculation started
Platelet activation: scoring computed

Calculating pathways:   9%|▉         | 55/583 [04:40<48:53,  5.56s/it]

Platelet activation: pvalue calculation completed
Platelet activation: Calculation completed
Prion disease: Calculation started
Prion disease: scoring computed

Calculating pathways:  10%|▉         | 56/583 [04:46<50:33,  5.76s/it]

Prion disease: pvalue calculation completed
Prion disease: Calculation completed
Prostate cancer: Calculation started
Prostate cancer: scoring computed

Calculating pathways:  10%|▉         | 57/583 [04:51<47:12,  5.38s/it]

Prostate cancer: pvalue calculation completed
Prostate cancer: Calculation completed
Proteoglycans in cancer: Calculation started
Proteoglycans in cancer: scoring computed

Calculating pathways:  10%|▉         | 58/583 [04:56<47:00,  5.37s/it]

Proteoglycans in cancer: pvalue calculation completed
Proteoglycans in cancer: Calculation completed
Salmonella infection: Calculation started
Salmonella infection: scoring computed

Calculating pathways:  10%|█         | 59/583 [05:02<48:57,  5.61s/it]

Salmonella infection: pvalue calculation completed
Salmonella infection: Calculation completed
Sphingolipid signaling pathway: Calculation started
Sphingolipid signaling pathway: scoring computed

Calculating pathways:  10%|█         | 60/583 [05:07<46:20,  5.32s/it]

Sphingolipid signaling pathway: pvalue calculation completed
Sphingolipid signaling pathway: Calculation completed
T cell receptor signaling pathway: Calculation started
T cell receptor signaling pathway: scoring computed

Calculating pathways:  10%|█         | 61/583 [05:11<44:04,  5.07s/it]

T cell receptor signaling pathway: pvalue calculation completed
T cell receptor signaling pathway: Calculation completed
TNF signaling pathway: Calculation started
TNF signaling pathway: scoring computed

Calculating pathways:  11%|█         | 62/583 [05:16<42:41,  4.92s/it]

TNF signaling pathway: pvalue calculation completed
TNF signaling pathway: Calculation completed
Tight junction: Calculation started
Tight junction: scoring computed

Calculating pathways:  11%|█         | 63/583 [05:21<43:22,  5.01s/it]

Tight junction: pvalue calculation completed
Tight junction: Calculation completed
Tuberculosis: Calculation started
Tuberculosis: scoring computed

Calculating pathways:  11%|█         | 64/583 [05:26<43:19,  5.01s/it]

Tuberculosis: pvalue calculation completed
Tuberculosis: Calculation completed
Viral myocarditis: Calculation started
Viral myocarditis: scoring computed

Calculating pathways:  11%|█         | 65/583 [05:30<40:52,  4.73s/it]

Viral myocarditis: pvalue calculation completed
Viral myocarditis: Calculation completed
cGMP-PKG signaling pathway: Calculation started
cGMP-PKG signaling pathway: scoring computed

Calculating pathways:  11%|█▏        | 66/583 [05:35<41:39,  4.83s/it]

cGMP-PKG signaling pathway: pvalue calculation completed
cGMP-PKG signaling pathway: Calculation completed
ABC Transporter Disorders: Calculation started
ABC Transporter Disorders: scoring computed

Calculating pathways:  11%|█▏        | 67/583 [05:39<39:19,  4.57s/it]

ABC Transporter Disorders: pvalue calculation completed
ABC Transporter Disorders: Calculation completed
ABC-family Proteins Mediated Transport: Calculation started
ABC-family Proteins Mediated Transport: scoring computed

Calculating pathways:  12%|█▏        | 68/583 [05:44<38:48,  4.52s/it]

ABC-family Proteins Mediated Transport: pvalue calculation completed
ABC-family Proteins Mediated Transport: Calculation completed
AURKA Activation by TPX2: Calculation started
AURKA Activation by TPX2: scoring computed

Calculating pathways:  12%|█▏        | 69/583 [05:48<38:14,  4.46s/it]

AURKA Activation by TPX2: pvalue calculation completed
AURKA Activation by TPX2: Calculation completed
Abacavir ADME: Calculation started
Abacavir ADME: scoring computed

Calculating pathways:  12%|█▏        | 70/583 [05:51<35:25,  4.14s/it]

Abacavir ADME: pvalue calculation completed
Abacavir ADME: Calculation completed
Abacavir Transmembrane Transport: Calculation started
Abacavir Transmembrane Transport: scoring computed

Calculating pathways:  12%|█▏        | 71/583 [05:55<33:49,  3.96s/it]

Abacavir Transmembrane Transport: pvalue calculation completed
Abacavir Transmembrane Transport: Calculation completed
Activated NTRK2 Signals Through FYN: Calculation started
Activated NTRK2 Signals Through FYN: scoring computed

Calculating pathways:  12%|█▏        | 72/583 [05:58<32:10,  3.78s/it]

Activated NTRK2 Signals Through FYN: pvalue calculation completed
Activated NTRK2 Signals Through FYN: Calculation completed
Activation of AMPK Downstream of NMDARs: Calculation started
Activation of AMPK Downstream of NMDARs: scoring computed

Calculating pathways:  13%|█▎        | 73/583 [06:02<31:52,  3.75s/it]

Activation of AMPK Downstream of NMDARs: pvalue calculation completed
Activation of AMPK Downstream of NMDARs: Calculation completed
Activation of NMDA Receptors and Postsynaptic Events: Calculation started
Activation of NMDA Receptors and Postsynaptic Events: scoring computed

Calculating pathways:  13%|█▎        | 74/583 [06:06<33:27,  3.94s/it]

Activation of NMDA Receptors and Postsynaptic Events: pvalue calculation completed
Activation of NMDA Receptors and Postsynaptic Events: Calculation completed
Adaptive Immune System: Calculation started
Adaptive Immune System: scoring computed

Calculating pathways:  13%|█▎        | 75/583 [06:18<51:54,  6.13s/it]

Adaptive Immune System: pvalue calculation completed
Adaptive Immune System: Calculation completed
Aggrephagy: Calculation started
Aggrephagy: scoring computed

Calculating pathways:  13%|█▎        | 76/583 [06:21<45:34,  5.39s/it]

Aggrephagy: pvalue calculation completed
Aggrephagy: Calculation completed
Anchoring of the Basal Body to the Plasma Membrane: Calculation started
Anchoring of the Basal Body to the Plasma Membrane: scoring computed

Calculating pathways:  13%|█▎        | 77/583 [06:26<43:07,  5.11s/it]

Anchoring of the Basal Body to the Plasma Membrane: pvalue calculation completed
Anchoring of the Basal Body to the Plasma Membrane: Calculation completed
Anti-inflammatory Response Favouring Leishmania Parasite Infection: Calculation started
Anti-inflammatory Response Favouring Leishmania Parasite Infection: scoring computed

Calculating pathways:  13%|█▎        | 78/583 [06:30<41:06,  4.88s/it]

Anti-inflammatory Response Favouring Leishmania Parasite Infection: pvalue calculation completed
Anti-inflammatory Response Favouring Leishmania Parasite Infection: Calculation completed
Antigen Activates B Cell Receptor (BCR) Leading to Generation of Second Messengers: Calculation started
Antigen Activates B Cell Receptor (BCR) Leading to Generation of Second Messengers: scoring computed

Calculating pathways:  14%|█▎        | 79/583 [06:34<38:40,  4.61s/it]

Antigen Activates B Cell Receptor (BCR) Leading to Generation of Second Messengers: pvalue calculation completed
Antigen Activates B Cell Receptor (BCR) Leading to Generation of Second Messengers: Calculation completed
Antiviral Mechanism by IFN-stimulated Genes: Calculation started
Antiviral Mechanism by IFN-stimulated Genes: scoring computed

Calculating pathways:  14%|█▎        | 80/583 [06:39<39:21,  4.70s/it]

Antiviral Mechanism by IFN-stimulated Genes: pvalue calculation completed
Antiviral Mechanism by IFN-stimulated Genes: Calculation completed
Asparagine N-linked Glycosylation: Calculation started
Asparagine N-linked Glycosylation: scoring computed

Calculating pathways:  14%|█▍        | 81/583 [06:46<44:09,  5.28s/it]

Asparagine N-linked Glycosylation: pvalue calculation completed
Asparagine N-linked Glycosylation: Calculation completed
Assembly and Cell Surface Presentation of NMDA Receptors: Calculation started
Assembly and Cell Surface Presentation of NMDA Receptors: scoring computed

Calculating pathways:  14%|█▍        | 82/583 [06:49<40:15,  4.82s/it]

Assembly and Cell Surface Presentation of NMDA Receptors: pvalue calculation completed
Assembly and Cell Surface Presentation of NMDA Receptors: Calculation completed
Atorvastatin ADME: Calculation started
Atorvastatin ADME: scoring computed

Calculating pathways:  14%|█▍        | 83/583 [06:53<36:31,  4.38s/it]

Atorvastatin ADME: pvalue calculation completed
Atorvastatin ADME: Calculation completed
Axon Guidance: Calculation started
Axon Guidance: scoring computed

Calculating pathways:  14%|█▍        | 84/583 [07:02<47:46,  5.74s/it]

Axon Guidance: pvalue calculation completed
Axon Guidance: Calculation completed
Bile Acid and Bile Salt Metabolism: Calculation started
Bile Acid and Bile Salt Metabolism: scoring computed

Calculating pathways:  15%|█▍        | 85/583 [07:05<42:35,  5.13s/it]

Bile Acid and Bile Salt Metabolism: pvalue calculation completed
Bile Acid and Bile Salt Metabolism: Calculation completed
C-type Lectin Receptors (CLRs): Calculation started
C-type Lectin Receptors (CLRs): scoring computed

Calculating pathways:  15%|█▍        | 86/583 [07:10<41:15,  4.98s/it]

C-type Lectin Receptors (CLRs): pvalue calculation completed
C-type Lectin Receptors (CLRs): Calculation completed
CD209 (DC-SIGN) Signaling: Calculation started
CD209 (DC-SIGN) Signaling: scoring computed

Calculating pathways:  15%|█▍        | 87/583 [07:14<37:46,  4.57s/it]

CD209 (DC-SIGN) Signaling: pvalue calculation completed
CD209 (DC-SIGN) Signaling: Calculation completed
CD28 Co-Stimulation: Calculation started
CD28 Co-Stimulation: scoring computed

Calculating pathways:  15%|█▌        | 88/583 [07:17<35:20,  4.28s/it]

CD28 Co-Stimulation: pvalue calculation completed
CD28 Co-Stimulation: Calculation completed
CD28 Dependent PI3K Akt Signaling: Calculation started
CD28 Dependent PI3K Akt Signaling: scoring computed

Calculating pathways:  15%|█▌        | 89/583 [07:21<33:27,  4.06s/it]

CD28 Dependent PI3K Akt Signaling: pvalue calculation completed
CD28 Dependent PI3K Akt Signaling: Calculation completed
CD28 Dependent Vav1 Pathway: Calculation started
CD28 Dependent Vav1 Pathway: scoring computed

Calculating pathways:  15%|█▌        | 90/583 [07:24<31:43,  3.86s/it]

CD28 Dependent Vav1 Pathway: pvalue calculation completed
CD28 Dependent Vav1 Pathway: Calculation completed
COPI-dependent Golgi-to-ER Retrograde Traffic: Calculation started
COPI-dependent Golgi-to-ER Retrograde Traffic: scoring computed

Calculating pathways:  16%|█▌        | 91/583 [07:29<33:18,  4.06s/it]

COPI-dependent Golgi-to-ER Retrograde Traffic: pvalue calculation completed
COPI-dependent Golgi-to-ER Retrograde Traffic: Calculation completed
COPI-independent Golgi-to-ER Retrograde Traffic: Calculation started
COPI-independent Golgi-to-ER Retrograde Traffic: scoring computed

Calculating pathways:  16%|█▌        | 92/583 [07:32<32:34,  3.98s/it]

COPI-independent Golgi-to-ER Retrograde Traffic: pvalue calculation completed
COPI-independent Golgi-to-ER Retrograde Traffic: Calculation completed
COPI-mediated Anterograde Transport: Calculation started
COPI-mediated Anterograde Transport: scoring computed

Calculating pathways:  16%|█▌        | 93/583 [07:37<33:31,  4.11s/it]

COPI-mediated Anterograde Transport: pvalue calculation completed
COPI-mediated Anterograde Transport: Calculation completed
CRMPs in Sema3A Signaling: Calculation started
CRMPs in Sema3A Signaling: scoring computed

Calculating pathways:  16%|█▌        | 94/583 [07:40<31:52,  3.91s/it]

CRMPs in Sema3A Signaling: pvalue calculation completed
CRMPs in Sema3A Signaling: Calculation completed
CTLA4 Inhibitory Signaling: Calculation started
CTLA4 Inhibitory Signaling: scoring computed

Calculating pathways:  16%|█▋        | 95/583 [07:44<30:49,  3.79s/it]

CTLA4 Inhibitory Signaling: pvalue calculation completed
CTLA4 Inhibitory Signaling: Calculation completed
Carboxyterminal Post-Translational Modifications of Tubulin: Calculation started
Carboxyterminal Post-Translational Modifications of Tubulin: scoring computed

Calculating pathways:  16%|█▋        | 96/583 [07:47<30:31,  3.76s/it]

Carboxyterminal Post-Translational Modifications of Tubulin: pvalue calculation completed
Carboxyterminal Post-Translational Modifications of Tubulin: Calculation completed
Cell Cycle: Calculation started
Cell Cycle: scoring computed

Calculating pathways:  17%|█▋        | 97/583 [07:58<46:00,  5.68s/it]

Cell Cycle: pvalue calculation completed
Cell Cycle: Calculation completed
Cell Cycle, Mitotic: Calculation started
Cell Cycle, Mitotic: scoring computed

Calculating pathways:  17%|█▋        | 98/583 [08:06<53:15,  6.59s/it]

Cell Cycle, Mitotic: pvalue calculation completed
Cell Cycle, Mitotic: Calculation completed
Cell Surface Interactions at the Vascular Wall: Calculation started
Cell Surface Interactions at the Vascular Wall: scoring computed

Calculating pathways:  17%|█▋        | 99/583 [08:11<49:25,  6.13s/it]

Cell Surface Interactions at the Vascular Wall: pvalue calculation completed
Cell Surface Interactions at the Vascular Wall: Calculation completed
Cell-Cell Communication: Calculation started
Cell-Cell Communication: scoring computed

Calculating pathways:  17%|█▋        | 100/583 [08:16<46:22,  5.76s/it]

Cell-Cell Communication: pvalue calculation completed
Cell-Cell Communication: Calculation completed
Cellular Responses to Mechanical Stimuli: Calculation started
Cellular Responses to Mechanical Stimuli: scoring computed

Calculating pathways:  17%|█▋        | 101/583 [08:21<42:43,  5.32s/it]

Cellular Responses to Mechanical Stimuli: pvalue calculation completed
Cellular Responses to Mechanical Stimuli: Calculation completed
Cellular Responses to Stimuli: Calculation started
Cellular Responses to Stimuli: scoring computed

Calculating pathways:  17%|█▋        | 102/583 [08:33<59:37,  7.44s/it]

Cellular Responses to Stimuli: pvalue calculation completed
Cellular Responses to Stimuli: Calculation completed
Cellular Responses to Stress: Calculation started
Cellular Responses to Stress: scoring computed

Calculating pathways:  18%|█▊        | 103/583 [08:44<1:09:10,  8.65s/it]

Cellular Responses to Stress: pvalue calculation completed
Cellular Responses to Stress: Calculation completed
Centrosome Maturation: Calculation started
Centrosome Maturation: scoring computed

Calculating pathways:  18%|█▊        | 104/583 [08:49<58:25,  7.32s/it]

Centrosome Maturation: pvalue calculation completed
Centrosome Maturation: Calculation completed
Chaperonin-mediated Protein Folding: Calculation started
Chaperonin-mediated Protein Folding: scoring computed

Calculating pathways:  18%|█▊        | 105/583 [08:53<51:00,  6.40s/it]

Chaperonin-mediated Protein Folding: pvalue calculation completed
Chaperonin-mediated Protein Folding: Calculation completed
Cilium Assembly: Calculation started
Cilium Assembly: scoring computed

Calculating pathways:  18%|█▊        | 106/583 [08:58<48:40,  6.12s/it]

Cilium Assembly: pvalue calculation completed
Cilium Assembly: Calculation completed
Class A 1 (Rhodopsin-like Receptors): Calculation started
Class A 1 (Rhodopsin-like Receptors): scoring computed

Calculating pathways:  18%|█▊        | 107/583 [09:04<48:10,  6.07s/it]

Class A 1 (Rhodopsin-like Receptors): pvalue calculation completed
Class A 1 (Rhodopsin-like Receptors): Calculation completed
Constitutive Signaling by Aberrant PI3K in Cancer: Calculation started
Constitutive Signaling by Aberrant PI3K in Cancer: scoring computed

Calculating pathways:  19%|█▊        | 108/583 [09:09<43:37,  5.51s/it]

Constitutive Signaling by Aberrant PI3K in Cancer: pvalue calculation completed
Constitutive Signaling by Aberrant PI3K in Cancer: Calculation completed
Constitutive Signaling by Overexpressed ERBB2: Calculation started
Constitutive Signaling by Overexpressed ERBB2: scoring computed

Calculating pathways:  19%|█▊        | 109/583 [09:12<38:29,  4.87s/it]

Constitutive Signaling by Overexpressed ERBB2: pvalue calculation completed
Constitutive Signaling by Overexpressed ERBB2: Calculation completed
Cooperation of Prefoldin and TriC CCT in Actin and Tubulin Folding: Calculation started
Cooperation of Prefoldin and TriC CCT in Actin and Tubulin Folding: scoring computed

Calculating pathways:  19%|█▉        | 110/583 [09:16<35:40,  4.53s/it]

Cooperation of Prefoldin and TriC CCT in Actin and Tubulin Folding: pvalue calculation completed
Cooperation of Prefoldin and TriC CCT in Actin and Tubulin Folding: Calculation completed
Costimulation by the CD28 Family: Calculation started
Costimulation by the CD28 Family: scoring computed

Calculating pathways:  19%|█▉        | 111/583 [09:20<34:47,  4.42s/it]

Costimulation by the CD28 Family: pvalue calculation completed
Costimulation by the CD28 Family: Calculation completed
Cytokine Signaling in Immune System: Calculation started
Cytokine Signaling in Immune System: scoring computed

Calculating pathways:  19%|█▉        | 112/583 [09:31<50:06,  6.38s/it]

Cytokine Signaling in Immune System: pvalue calculation completed
Cytokine Signaling in Immune System: Calculation completed
DAP12 Interactions: Calculation started
DAP12 Interactions: scoring computed

Calculating pathways:  19%|█▉        | 113/583 [09:35<44:02,  5.62s/it]

DAP12 Interactions: pvalue calculation completed
DAP12 Interactions: Calculation completed
DAP12 Signaling: Calculation started
DAP12 Signaling: scoring computed

Calculating pathways:  20%|█▉        | 114/583 [09:38<39:17,  5.03s/it]

DAP12 Signaling: pvalue calculation completed
DAP12 Signaling: Calculation completed
DCC Mediated Attractive Signaling: Calculation started
DCC Mediated Attractive Signaling: scoring computed

Calculating pathways:  20%|█▉        | 115/583 [09:42<35:50,  4.60s/it]

DCC Mediated Attractive Signaling: pvalue calculation completed
DCC Mediated Attractive Signaling: Calculation completed
Dectin-2 Family: Calculation started
Dectin-2 Family: scoring computed

Calculating pathways:  20%|█▉        | 116/583 [09:45<33:30,  4.31s/it]

Dectin-2 Family: pvalue calculation completed
Dectin-2 Family: Calculation completed
Deubiquitination: Calculation started
Deubiquitination: scoring computed

Calculating pathways:  20%|██        | 117/583 [09:52<37:33,  4.84s/it]

Deubiquitination: pvalue calculation completed
Deubiquitination: Calculation completed
Developmental Biology: Calculation started
Developmental Biology: scoring computed

Calculating pathways:  20%|██        | 118/583 [10:07<1:01:16,  7.91s/it]

Developmental Biology: pvalue calculation completed
Developmental Biology: Calculation completed
Diseases of Signal Transduction by Growth Factor Receptors and Second Messengers: Calculation started
Diseases of Signal Transduction by Growth Factor Receptors and Second Messengers: scoring computed

Calculating pathways:  20%|██        | 119/583 [10:15<1:02:05,  8.03s/it]

Diseases of Signal Transduction by Growth Factor Receptors and Second Messengers: pvalue calculation completed
Diseases of Signal Transduction by Growth Factor Receptors and Second Messengers: Calculation completed
Disorders of Transmembrane Transporters: Calculation started
Disorders of Transmembrane Transporters: scoring computed

Calculating pathways:  21%|██        | 120/583 [10:20<54:51,  7.11s/it]

Disorders of Transmembrane Transporters: pvalue calculation completed
Disorders of Transmembrane Transporters: Calculation completed
Downregulation of ERBB2 Signaling: Calculation started
Downregulation of ERBB2 Signaling: scoring computed

Calculating pathways:  21%|██        | 121/583 [10:24<47:06,  6.12s/it]

Downregulation of ERBB2 Signaling: pvalue calculation completed
Downregulation of ERBB2 Signaling: Calculation completed
Downregulation of ERBB2 ERBB3 Signaling: Calculation started
Downregulation of ERBB2 ERBB3 Signaling: scoring computed

Calculating pathways:  21%|██        | 122/583 [10:27<40:59,  5.33s/it]

Downregulation of ERBB2 ERBB3 Signaling: pvalue calculation completed
Downregulation of ERBB2 ERBB3 Signaling: Calculation completed
Drug ADME: Calculation started
Drug ADME: scoring computed

Calculating pathways:  21%|██        | 123/583 [10:31<38:21,  5.00s/it]

Drug ADME: pvalue calculation completed
Drug ADME: Calculation completed
EML4 and NUDC in Mitotic Spindle Formation: Calculation started
EML4 and NUDC in Mitotic Spindle Formation: scoring computed

Calculating pathways:  21%|██▏       | 124/583 [10:36<37:19,  4.88s/it]

EML4 and NUDC in Mitotic Spindle Formation: pvalue calculation completed
EML4 and NUDC in Mitotic Spindle Formation: Calculation completed
EPH-Ephrin Signaling: Calculation started
EPH-Ephrin Signaling: scoring computed

Calculating pathways:  21%|██▏       | 125/583 [10:40<35:56,  4.71s/it]

EPH-Ephrin Signaling: pvalue calculation completed
EPH-Ephrin Signaling: Calculation completed
EPH-ephrin Mediated Repulsion of Cells: Calculation started
EPH-ephrin Mediated Repulsion of Cells: scoring computed

Calculating pathways:  22%|██▏       | 126/583 [10:44<34:26,  4.52s/it]

EPH-ephrin Mediated Repulsion of Cells: pvalue calculation completed
EPH-ephrin Mediated Repulsion of Cells: Calculation completed
EPHA-mediated Growth Cone Collapse: Calculation started
EPHA-mediated Growth Cone Collapse: scoring computed

Calculating pathways:  22%|██▏       | 127/583 [10:48<32:26,  4.27s/it]

EPHA-mediated Growth Cone Collapse: pvalue calculation completed
EPHA-mediated Growth Cone Collapse: Calculation completed
EPHB-mediated Forward Signaling: Calculation started
EPHB-mediated Forward Signaling: scoring computed

Calculating pathways:  22%|██▏       | 128/583 [10:52<31:13,  4.12s/it]

EPHB-mediated Forward Signaling: pvalue calculation completed
EPHB-mediated Forward Signaling: Calculation completed
ER to Golgi Anterograde Transport: Calculation started
ER to Golgi Anterograde Transport: scoring computed

Calculating pathways:  22%|██▏       | 129/583 [10:57<33:06,  4.37s/it]

ER to Golgi Anterograde Transport: pvalue calculation completed
ER to Golgi Anterograde Transport: Calculation completed
ERBB2 Activates PTK6 Signaling: Calculation started
ERBB2 Activates PTK6 Signaling: scoring computed

Calculating pathways:  22%|██▏       | 130/583 [11:00<30:52,  4.09s/it]

ERBB2 Activates PTK6 Signaling: pvalue calculation completed
ERBB2 Activates PTK6 Signaling: Calculation completed
ERBB2 Regulates Cell Motility: Calculation started
ERBB2 Regulates Cell Motility: scoring computed

Calculating pathways:  22%|██▏       | 131/583 [11:04<29:25,  3.91s/it]

ERBB2 Regulates Cell Motility: pvalue calculation completed
ERBB2 Regulates Cell Motility: Calculation completed
Ephrin Signaling: Calculation started
Ephrin Signaling: scoring computed

Calculating pathways:  23%|██▎       | 132/583 [11:07<28:22,  3.78s/it]

Ephrin Signaling: pvalue calculation completed
Ephrin Signaling: Calculation completed
FCGR Activation: Calculation started
FCGR Activation: scoring computed

Calculating pathways:  23%|██▎       | 133/583 [11:11<27:52,  3.72s/it]

FCGR Activation: pvalue calculation completed
FCGR Activation: Calculation completed
FCGR3A-mediated IL10 Synthesis: Calculation started
FCGR3A-mediated IL10 Synthesis: scoring computed

Calculating pathways:  23%|██▎       | 134/583 [11:15<28:24,  3.80s/it]

FCGR3A-mediated IL10 Synthesis: pvalue calculation completed
FCGR3A-mediated IL10 Synthesis: Calculation completed
FCGR3A-mediated Phagocytosis: Calculation started
FCGR3A-mediated Phagocytosis: scoring computed

Calculating pathways:  23%|██▎       | 135/583 [11:19<29:12,  3.91s/it]

FCGR3A-mediated Phagocytosis: pvalue calculation completed
FCGR3A-mediated Phagocytosis: Calculation completed
FLT3 Signaling: Calculation started
FLT3 Signaling: scoring computed

Calculating pathways:  23%|██▎       | 136/583 [11:23<28:35,  3.84s/it]

FLT3 Signaling: pvalue calculation completed
FLT3 Signaling: Calculation completed
FLT3 Signaling Through SRC Family Kinases: Calculation started
FLT3 Signaling Through SRC Family Kinases: scoring computed

Calculating pathways:  23%|██▎       | 137/583 [11:26<27:24,  3.69s/it]

FLT3 Signaling Through SRC Family Kinases: pvalue calculation completed
FLT3 Signaling Through SRC Family Kinases: Calculation completed
Factors Involved in Megakaryocyte Development and Platelet Production: Calculation started
Factors Involved in Megakaryocyte Development and Platelet Production: scoring computed

Calculating pathways:  24%|██▎       | 138/583 [11:31<30:22,  4.10s/it]

Factors Involved in Megakaryocyte Development and Platelet Production: pvalue calculation completed
Factors Involved in Megakaryocyte Development and Platelet Production: Calculation completed
Fc Epsilon Receptor (FCERI) Signaling: Calculation started
Fc Epsilon Receptor (FCERI) Signaling: scoring computed

Calculating pathways:  24%|██▍       | 139/583 [11:36<31:44,  4.29s/it]

Fc Epsilon Receptor (FCERI) Signaling: pvalue calculation completed
Fc Epsilon Receptor (FCERI) Signaling: Calculation completed
Fcgamma Receptor (FCGR) Dependent Phagocytosis: Calculation started
Fcgamma Receptor (FCGR) Dependent Phagocytosis: scoring computed

Calculating pathways:  24%|██▍       | 140/583 [11:40<32:17,  4.37s/it]

Fcgamma Receptor (FCGR) Dependent Phagocytosis: pvalue calculation completed
Fcgamma Receptor (FCGR) Dependent Phagocytosis: Calculation completed
Formation of Tubulin Folding Intermediates by CCT TriC: Calculation started
Formation of Tubulin Folding Intermediates by CCT TriC: scoring computed

Calculating pathways:  24%|██▍       | 141/583 [11:44<30:26,  4.13s/it]

Formation of Tubulin Folding Intermediates by CCT TriC: pvalue calculation completed
Formation of Tubulin Folding Intermediates by CCT TriC: Calculation completed
G Alpha (I) Signalling Events: Calculation started
G Alpha (I) Signalling Events: scoring computed

Calculating pathways:  24%|██▍       | 142/583 [11:50<34:35,  4.71s/it]

G Alpha (I) Signalling Events: pvalue calculation completed
G Alpha (I) Signalling Events: Calculation completed
G Alpha (Q) Signalling Events: Calculation started
G Alpha (Q) Signalling Events: scoring computed

Calculating pathways:  25%|██▍       | 143/583 [11:55<36:22,  4.96s/it]

G Alpha (Q) Signalling Events: pvalue calculation completed
G Alpha (Q) Signalling Events: Calculation completed
G Alpha (S) Signalling Events: Calculation started
G Alpha (S) Signalling Events: scoring computed

Calculating pathways:  25%|██▍       | 144/583 [12:00<35:36,  4.87s/it]

G Alpha (S) Signalling Events: pvalue calculation completed
G Alpha (S) Signalling Events: Calculation completed
G2 M Transition: Calculation started
G2 M Transition: scoring computed

Calculating pathways:  25%|██▍       | 145/583 [12:05<36:27,  4.99s/it]

G2 M Transition: pvalue calculation completed
G2 M Transition: Calculation completed
GPCR Downstream Signalling: Calculation started
GPCR Downstream Signalling: scoring computed

Calculating pathways:  25%|██▌       | 146/583 [12:14<44:52,  6.16s/it]

GPCR Downstream Signalling: pvalue calculation completed
GPCR Downstream Signalling: Calculation completed
GPCR Ligand Binding: Calculation started
GPCR Ligand Binding: scoring computed

Calculating pathways:  25%|██▌       | 147/583 [12:22<47:06,  6.48s/it]

GPCR Ligand Binding: pvalue calculation completed
GPCR Ligand Binding: Calculation completed
GPVI-mediated Activation Cascade: Calculation started
GPVI-mediated Activation Cascade: scoring computed

Calculating pathways:  25%|██▌       | 148/583 [12:25<40:54,  5.64s/it]

GPVI-mediated Activation Cascade: pvalue calculation completed
GPVI-mediated Activation Cascade: Calculation completed
GRB2 Events in ERBB2 Signaling: Calculation started
GRB2 Events in ERBB2 Signaling: scoring computed

Calculating pathways:  26%|██▌       | 149/583 [12:29<36:06,  4.99s/it]

GRB2 Events in ERBB2 Signaling: pvalue calculation completed
GRB2 Events in ERBB2 Signaling: Calculation completed
GRB7 Events in ERBB2 Signaling: Calculation started
GRB7 Events in ERBB2 Signaling: scoring computed

Calculating pathways:  26%|██▌       | 150/583 [12:32<32:24,  4.49s/it]

GRB7 Events in ERBB2 Signaling: pvalue calculation completed
GRB7 Events in ERBB2 Signaling: Calculation completed
Gap Junction Assembly: Calculation started
Gap Junction Assembly: scoring computed

Calculating pathways:  26%|██▌       | 151/583 [12:36<30:18,  4.21s/it]

Gap Junction Assembly: pvalue calculation completed
Gap Junction Assembly: Calculation completed
Gap Junction Trafficking: Calculation started
Gap Junction Trafficking: scoring computed

Calculating pathways:  26%|██▌       | 152/583 [12:39<29:07,  4.05s/it]

Gap Junction Trafficking: pvalue calculation completed
Gap Junction Trafficking: Calculation completed
Gap Junction Trafficking and Regulation: Calculation started
Gap Junction Trafficking and Regulation: scoring computed

Calculating pathways:  26%|██▌       | 153/583 [12:43<28:17,  3.95s/it]

Gap Junction Trafficking and Regulation: pvalue calculation completed
Gap Junction Trafficking and Regulation: Calculation completed
Gene Expression (Transcription): Calculation started
Gene Expression (Transcription): scoring computed

Calculating pathways:  26%|██▋       | 154/583 [13:02<1:00:59,  8.53s/it]

Gene Expression (Transcription): pvalue calculation completed
Gene Expression (Transcription): Calculation completed
Generic Transcription Pathway: Calculation started
Generic Transcription Pathway: scoring computed

Calculating pathways:  27%|██▋       | 155/583 [13:18<1:16:23, 10.71s/it]

Generic Transcription Pathway: pvalue calculation completed
Generic Transcription Pathway: Calculation completed
Golgi-to-ER Retrograde Transport: Calculation started
Golgi-to-ER Retrograde Transport: scoring computed

Calculating pathways:  27%|██▋       | 156/583 [13:23<1:03:45,  8.96s/it]

Golgi-to-ER Retrograde Transport: pvalue calculation completed
Golgi-to-ER Retrograde Transport: Calculation completed
HCMV Early Events: Calculation started
HCMV Early Events: scoring computed

Calculating pathways:  27%|██▋       | 157/583 [13:27<54:21,  7.66s/it]

HCMV Early Events: pvalue calculation completed
HCMV Early Events: Calculation completed
HCMV Infection: Calculation started
HCMV Infection: scoring computed

Calculating pathways:  27%|██▋       | 158/583 [13:32<48:28,  6.84s/it]

HCMV Infection: pvalue calculation completed
HCMV Infection: Calculation completed
HIV Infection: Calculation started
HIV Infection: scoring computed

Calculating pathways:  27%|██▋       | 159/583 [13:38<46:04,  6.52s/it]

HIV Infection: pvalue calculation completed
HIV Infection: Calculation completed
HSP90 Chaperone Cycle for Steroid Hormone Receptors (SHR) in the Presence of Ligand: Calculation started
HSP90 Chaperone Cycle for Steroid Hormone Receptors (SHR) in the Presence of Ligand: scoring computed

Calculating pathways:  27%|██▋       | 160/583 [13:42<40:28,  5.74s/it]

HSP90 Chaperone Cycle for Steroid Hormone Receptors (SHR) in the Presence of Ligand: pvalue calculation completed
HSP90 Chaperone Cycle for Steroid Hormone Receptors (SHR) in the Presence of Ligand: Calculation completed
Hedgehog 'Off' State: Calculation started
Hedgehog 'Off' State: scoring computed

Calculating pathways:  28%|██▊       | 161/583 [13:46<37:29,  5.33s/it]

Hedgehog 'Off' State: pvalue calculation completed
Hedgehog 'Off' State: Calculation completed
Hemostasis: Calculation started
Hemostasis: scoring computed

Calculating pathways:  28%|██▊       | 162/583 [13:56<46:32,  6.63s/it]

Hemostasis: pvalue calculation completed
Hemostasis: Calculation completed
High Laminar Flow Shear Stress Activates Signaling by PIEZO1 and PECAM1 CDH5 KDR in Endothelial Cell: Calculation started
High Laminar Flow Shear Stress Activates Signaling by PIEZO1 and PECAM1 CDH5 KDR in Endothelial Cell: scoring computed

Calculating pathways:  28%|██▊       | 163/583 [14:00<41:10,  5.88s/it]

High Laminar Flow Shear Stress Activates Signaling by PIEZO1 and PECAM1 CDH5 KDR in Endothelial Cell: pvalue calculation completed
High Laminar Flow Shear Stress Activates Signaling by PIEZO1 and PECAM1 CDH5 KDR in Endothelial Cell: Calculation completed
Host Interactions of HIV Factors: Calculation started
Host Interactions of HIV Factors: scoring computed

Calculating pathways:  28%|██▊       | 164/583 [14:05<38:51,  5.56s/it]

Host Interactions of HIV Factors: pvalue calculation completed
Host Interactions of HIV Factors: Calculation completed
Infectious Disease: Calculation started
Infectious Disease: scoring computed

Calculating pathways:  28%|██▊       | 165/583 [14:19<55:51,  8.02s/it]

Infectious Disease: pvalue calculation completed
Infectious Disease: Calculation completed
Innate Immune System: Calculation started
Innate Immune System: scoring computed

Calculating pathways:  28%|██▊       | 166/583 [14:33<1:07:30,  9.71s/it]

Innate Immune System: pvalue calculation completed
Innate Immune System: Calculation completed
Interferon Signaling: Calculation started
Interferon Signaling: scoring computed

Calculating pathways:  29%|██▊       | 167/583 [14:39<1:00:04,  8.66s/it]

Interferon Signaling: pvalue calculation completed
Interferon Signaling: Calculation completed
Interleukin-1 Family Signaling: Calculation started
Interleukin-1 Family Signaling: scoring computed

Calculating pathways:  29%|██▉       | 168/583 [14:44<51:59,  7.52s/it]

Interleukin-1 Family Signaling: pvalue calculation completed
Interleukin-1 Family Signaling: Calculation completed
Interleukin-1 Signaling: Calculation started
Interleukin-1 Signaling: scoring computed

Calculating pathways:  29%|██▉       | 169/583 [14:48<45:22,  6.58s/it]

Interleukin-1 Signaling: pvalue calculation completed
Interleukin-1 Signaling: Calculation completed
Interleukin-17 Signaling: Calculation started
Interleukin-17 Signaling: scoring computed

Calculating pathways:  29%|██▉       | 170/583 [14:52<40:06,  5.83s/it]

Interleukin-17 Signaling: pvalue calculation completed
Interleukin-17 Signaling: Calculation completed
Interleukin-3, Interleukin-5 and GM-CSF Signaling: Calculation started
Interleukin-3, Interleukin-5 and GM-CSF Signaling: scoring computed

Calculating pathways:  29%|██▉       | 171/583 [14:56<36:13,  5.28s/it]

Interleukin-3, Interleukin-5 and GM-CSF Signaling: pvalue calculation completed
Interleukin-3, Interleukin-5 and GM-CSF Signaling: Calculation completed
Interleukin-4 and Interleukin-13 Signaling: Calculation started
Interleukin-4 and Interleukin-13 Signaling: scoring computed

Calculating pathways:  30%|██▉       | 172/583 [15:00<34:04,  4.98s/it]

Interleukin-4 and Interleukin-13 Signaling: pvalue calculation completed
Interleukin-4 and Interleukin-13 Signaling: Calculation completed
Intra-Golgi and Retrograde Golgi-to-ER Traffic: Calculation started
Intra-Golgi and Retrograde Golgi-to-ER Traffic: scoring computed

Calculating pathways:  30%|██▉       | 173/583 [15:06<35:21,  5.18s/it]

Intra-Golgi and Retrograde Golgi-to-ER Traffic: pvalue calculation completed
Intra-Golgi and Retrograde Golgi-to-ER Traffic: Calculation completed
Intracellular Signaling by Second Messengers: Calculation started
Intracellular Signaling by Second Messengers: scoring computed

Calculating pathways:  30%|██▉       | 174/583 [15:13<38:14,  5.61s/it]

Intracellular Signaling by Second Messengers: pvalue calculation completed
Intracellular Signaling by Second Messengers: Calculation completed
Intraflagellar Transport: Calculation started
Intraflagellar Transport: scoring computed

Calculating pathways:  30%|███       | 175/583 [15:16<34:27,  5.07s/it]

Intraflagellar Transport: pvalue calculation completed
Intraflagellar Transport: Calculation completed
JNK (c-Jun Kinases) Phosphorylation and Activation Mediated by Activated Human TAK1: Calculation started
JNK (c-Jun Kinases) Phosphorylation and Activation Mediated by Activated Human TAK1: scoring computed

Calculating pathways:  30%|███       | 176/583 [15:20<31:17,  4.61s/it]

JNK (c-Jun Kinases) Phosphorylation and Activation Mediated by Activated Human TAK1: pvalue calculation completed
JNK (c-Jun Kinases) Phosphorylation and Activation Mediated by Activated Human TAK1: Calculation completed
Kinesins: Calculation started
Kinesins: scoring computed

Calculating pathways:  30%|███       | 177/583 [15:24<29:45,  4.40s/it]

Kinesins: pvalue calculation completed
Kinesins: Calculation completed
L1CAM Interactions: Calculation started
L1CAM Interactions: scoring computed

Calculating pathways:  31%|███       | 178/583 [15:28<29:51,  4.42s/it]

L1CAM Interactions: pvalue calculation completed
L1CAM Interactions: Calculation completed
Leishmania Infection: Calculation started
Leishmania Infection: scoring computed

Calculating pathways:  31%|███       | 179/583 [15:34<31:25,  4.67s/it]

Leishmania Infection: pvalue calculation completed
Leishmania Infection: Calculation completed
Leishmania Parasite Growth and Survival: Calculation started
Leishmania Parasite Growth and Survival: scoring computed

Calculating pathways:  31%|███       | 180/583 [15:38<30:57,  4.61s/it]

Leishmania Parasite Growth and Survival: pvalue calculation completed
Leishmania Parasite Growth and Survival: Calculation completed
Leishmania Phagocytosis: Calculation started
Leishmania Phagocytosis: scoring computed

Calculating pathways:  31%|███       | 181/583 [15:42<29:49,  4.45s/it]

Leishmania Phagocytosis: pvalue calculation completed
Leishmania Phagocytosis: Calculation completed
Loss of Nlp From Mitotic Centrosomes: Calculation started
Loss of Nlp From Mitotic Centrosomes: scoring computed

Calculating pathways:  31%|███       | 182/583 [15:46<29:07,  4.36s/it]

Loss of Nlp From Mitotic Centrosomes: pvalue calculation completed
Loss of Nlp From Mitotic Centrosomes: Calculation completed
Loss of Proteins Required for Interphase Microtubule Organization From the Centrosome: Calculation started
Loss of Proteins Required for Interphase Microtubule Organization From the Centrosome: scoring computed

Calculating pathways:  31%|███▏      | 183/583 [15:50<28:20,  4.25s/it]

Loss of Proteins Required for Interphase Microtubule Organization From the Centrosome: pvalue calculation completed
Loss of Proteins Required for Interphase Microtubule Organization From the Centrosome: Calculation completed
M Phase: Calculation started
M Phase: scoring computed

Calculating pathways:  32%|███▏      | 184/583 [15:58<34:50,  5.24s/it]

M Phase: pvalue calculation completed
M Phase: Calculation completed
M-decay Degradation of Maternal mRNAs by Maternally Stored Factors: Calculation started
M-decay Degradation of Maternal mRNAs by Maternally Stored Factors: scoring computed

Calculating pathways:  32%|███▏      | 185/583 [16:02<31:56,  4.81s/it]

M-decay Degradation of Maternal mRNAs by Maternally Stored Factors: pvalue calculation completed
M-decay Degradation of Maternal mRNAs by Maternally Stored Factors: Calculation completed
MAP Kinase Activation: Calculation started
MAP Kinase Activation: scoring computed

Calculating pathways:  32%|███▏      | 186/583 [16:06<30:16,  4.58s/it]

MAP Kinase Activation: pvalue calculation completed
MAP Kinase Activation: Calculation completed
MAPK Family Signaling Cascades: Calculation started
MAPK Family Signaling Cascades: scoring computed

Calculating pathways:  32%|███▏      | 187/583 [16:12<34:07,  5.17s/it]

MAPK Family Signaling Cascades: pvalue calculation completed
MAPK Family Signaling Cascades: Calculation completed
MAPK1 MAPK3 Signaling: Calculation started
MAPK1 MAPK3 Signaling: scoring computed

Calculating pathways:  32%|███▏      | 188/583 [16:18<35:57,  5.46s/it]

MAPK1 MAPK3 Signaling: pvalue calculation completed
MAPK1 MAPK3 Signaling: Calculation completed
MHC Class II Antigen Presentation: Calculation started
MHC Class II Antigen Presentation: scoring computed

Calculating pathways:  32%|███▏      | 189/583 [16:23<33:59,  5.18s/it]

MHC Class II Antigen Presentation: pvalue calculation completed
MHC Class II Antigen Presentation: Calculation completed
MITF-M-regulated Melanocyte Development: Calculation started
MITF-M-regulated Melanocyte Development: scoring computed

Calculating pathways:  33%|███▎      | 190/583 [16:27<32:48,  5.01s/it]

MITF-M-regulated Melanocyte Development: pvalue calculation completed
MITF-M-regulated Melanocyte Development: Calculation completed
Macroautophagy: Calculation started
Macroautophagy: scoring computed

Calculating pathways:  33%|███▎      | 191/583 [16:32<32:40,  5.00s/it]

Macroautophagy: pvalue calculation completed
Macroautophagy: Calculation completed
Maternal to Zygotic Transition (MZT): Calculation started
Maternal to Zygotic Transition (MZT): scoring computed

Calculating pathways:  33%|███▎      | 192/583 [16:37<30:59,  4.76s/it]

Maternal to Zygotic Transition (MZT): pvalue calculation completed
Maternal to Zygotic Transition (MZT): Calculation completed
Membrane Trafficking: Calculation started
Membrane Trafficking: scoring computed

Calculating pathways:  33%|███▎      | 193/583 [16:47<41:31,  6.39s/it]

Membrane Trafficking: pvalue calculation completed
Membrane Trafficking: Calculation completed
Metabolism of Lipids: Calculation started
Metabolism of Lipids: scoring computed

Calculating pathways:  33%|███▎      | 194/583 [16:58<50:31,  7.79s/it]

Metabolism of Lipids: pvalue calculation completed
Metabolism of Lipids: Calculation completed
Metabolism of Steroids: Calculation started
Metabolism of Steroids: scoring computed

Calculating pathways:  33%|███▎      | 195/583 [17:03<44:54,  6.94s/it]

Metabolism of Steroids: pvalue calculation completed
Metabolism of Steroids: Calculation completed
Microtubule-dependent Trafficking of Connexons From Golgi to the Plasma Membrane: Calculation started
Microtubule-dependent Trafficking of Connexons From Golgi to the Plasma Membrane: scoring computed

Calculating pathways:  34%|███▎      | 196/583 [17:06<37:59,  5.89s/it]

Microtubule-dependent Trafficking of Connexons From Golgi to the Plasma Membrane: pvalue calculation completed
Microtubule-dependent Trafficking of Connexons From Golgi to the Plasma Membrane: Calculation completed
Mitotic Anaphase: Calculation started
Mitotic Anaphase: scoring computed

Calculating pathways:  34%|███▍      | 197/583 [17:12<37:48,  5.88s/it]

Mitotic Anaphase: pvalue calculation completed
Mitotic Anaphase: Calculation completed
Mitotic G2-G2 M Phases: Calculation started
Mitotic G2-G2 M Phases: scoring computed

Calculating pathways:  34%|███▍      | 198/583 [17:17<36:36,  5.70s/it]

Mitotic G2-G2 M Phases: pvalue calculation completed
Mitotic G2-G2 M Phases: Calculation completed
Mitotic Metaphase and Anaphase: Calculation started
Mitotic Metaphase and Anaphase: scoring computed

Calculating pathways:  34%|███▍      | 199/583 [17:23<36:52,  5.76s/it]

Mitotic Metaphase and Anaphase: pvalue calculation completed
Mitotic Metaphase and Anaphase: Calculation completed
Mitotic Prometaphase: Calculation started
Mitotic Prometaphase: scoring computed

Calculating pathways:  34%|███▍      | 200/583 [17:29<36:13,  5.68s/it]

Mitotic Prometaphase: pvalue calculation completed
Mitotic Prometaphase: Calculation completed
MyD88 Cascade Initiated on Plasma Membrane: Calculation started
MyD88 Cascade Initiated on Plasma Membrane: scoring computed

Calculating pathways:  34%|███▍      | 201/583 [17:33<33:41,  5.29s/it]

MyD88 Cascade Initiated on Plasma Membrane: pvalue calculation completed
MyD88 Cascade Initiated on Plasma Membrane: Calculation completed
MyD88 Dependent Cascade Initiated on Endosome: Calculation started
MyD88 Dependent Cascade Initiated on Endosome: scoring computed

Calculating pathways:  35%|███▍      | 202/583 [17:38<32:05,  5.05s/it]

MyD88 Dependent Cascade Initiated on Endosome: pvalue calculation completed
MyD88 Dependent Cascade Initiated on Endosome: Calculation completed
MyD88-independent TLR4 Cascade: Calculation started
MyD88-independent TLR4 Cascade: scoring computed

Calculating pathways:  35%|███▍      | 203/583 [17:42<30:53,  4.88s/it]

MyD88-independent TLR4 Cascade: pvalue calculation completed
MyD88-independent TLR4 Cascade: Calculation completed
MyD88 MAL(TIRAP) Cascade Initiated on Plasma Membrane: Calculation started
MyD88 MAL(TIRAP) Cascade Initiated on Plasma Membrane: scoring computed

Calculating pathways:  35%|███▍      | 204/583 [17:47<30:11,  4.78s/it]

MyD88 MAL(TIRAP) Cascade Initiated on Plasma Membrane: pvalue calculation completed
MyD88 MAL(TIRAP) Cascade Initiated on Plasma Membrane: Calculation completed
NCAM Signaling for Neurite Out-Growth: Calculation started
NCAM Signaling for Neurite Out-Growth: scoring computed

Calculating pathways:  35%|███▌      | 205/583 [17:51<28:34,  4.54s/it]

NCAM Signaling for Neurite Out-Growth: pvalue calculation completed
NCAM Signaling for Neurite Out-Growth: Calculation completed
NOD1 2 Signaling Pathway: Calculation started
NOD1 2 Signaling Pathway: scoring computed

Calculating pathways:  35%|███▌      | 206/583 [17:54<26:58,  4.29s/it]

NOD1 2 Signaling Pathway: pvalue calculation completed
NOD1 2 Signaling Pathway: Calculation completed
NTRK2 Activates RAC1: Calculation started
NTRK2 Activates RAC1: scoring computed

Calculating pathways:  36%|███▌      | 207/583 [17:58<25:05,  4.00s/it]

NTRK2 Activates RAC1: pvalue calculation completed
NTRK2 Activates RAC1: Calculation completed
Nef and Signal Transduction: Calculation started
Nef and Signal Transduction: scoring computed

Calculating pathways:  36%|███▌      | 208/583 [18:01<24:02,  3.85s/it]

Nef and Signal Transduction: pvalue calculation completed
Nef and Signal Transduction: Calculation completed
Negative Regulation of the PI3K AKT Network: Calculation started
Negative Regulation of the PI3K AKT Network: scoring computed

Calculating pathways:  36%|███▌      | 209/583 [18:06<25:48,  4.14s/it]

Negative Regulation of the PI3K AKT Network: pvalue calculation completed
Negative Regulation of the PI3K AKT Network: Calculation completed
Nephrin Family Interactions: Calculation started
Nephrin Family Interactions: scoring computed

Calculating pathways:  36%|███▌      | 210/583 [18:10<24:48,  3.99s/it]

Nephrin Family Interactions: pvalue calculation completed
Nephrin Family Interactions: Calculation completed
Nervous System Development: Calculation started
Nervous System Development: scoring computed

Calculating pathways:  36%|███▌      | 211/583 [18:19<34:41,  5.59s/it]

Nervous System Development: pvalue calculation completed
Nervous System Development: Calculation completed
Netrin-1 Signaling: Calculation started
Netrin-1 Signaling: scoring computed

Calculating pathways:  36%|███▋      | 212/583 [18:23<31:04,  5.03s/it]

Netrin-1 Signaling: pvalue calculation completed
Netrin-1 Signaling: Calculation completed
Neuronal System: Calculation started
Neuronal System: scoring computed

Calculating pathways:  37%|███▋      | 213/583 [18:30<35:20,  5.73s/it]

Neuronal System: pvalue calculation completed
Neuronal System: Calculation completed
Neurotransmitter Receptors and Postsynaptic Signal Transmission: Calculation started
Neurotransmitter Receptors and Postsynaptic Signal Transmission: scoring computed

Calculating pathways:  37%|███▋      | 214/583 [18:35<34:33,  5.62s/it]

Neurotransmitter Receptors and Postsynaptic Signal Transmission: pvalue calculation completed
Neurotransmitter Receptors and Postsynaptic Signal Transmission: Calculation completed
Neutrophil Degranulation: Calculation started
Neutrophil Degranulation: scoring computed

Calculating pathways:  37%|███▋      | 215/583 [18:44<39:31,  6.44s/it]

Neutrophil Degranulation: pvalue calculation completed
Neutrophil Degranulation: Calculation completed
Nuclear Envelope (NE) Reassembly: Calculation started
Nuclear Envelope (NE) Reassembly: scoring computed

Calculating pathways:  37%|███▋      | 216/583 [18:48<35:19,  5.77s/it]

Nuclear Envelope (NE) Reassembly: pvalue calculation completed
Nuclear Envelope (NE) Reassembly: Calculation completed
Nuclear Receptor Transcription Pathway: Calculation started
Nuclear Receptor Transcription Pathway: scoring computed

Calculating pathways:  37%|███▋      | 217/583 [18:52<31:41,  5.20s/it]

Nuclear Receptor Transcription Pathway: pvalue calculation completed
Nuclear Receptor Transcription Pathway: Calculation completed
Nucleotide-binding Domain, Leucine Rich Repeat Containing Receptor (NLR) Signaling Pathways: Calculation started
Nucleotide-binding Domain, Leucine Rich Repeat Containing Receptor (NLR) Signaling Pathways: scoring computed

Calculating pathways:  37%|███▋      | 218/583 [18:56<29:27,  4.84s/it]

Nucleotide-binding Domain, Leucine Rich Repeat Containing Receptor (NLR) Signaling Pathways: pvalue calculation completed
Nucleotide-binding Domain, Leucine Rich Repeat Containing Receptor (NLR) Signaling Pathways: Calculation completed
Organelle Biogenesis and Maintenance: Calculation started
Organelle Biogenesis and Maintenance: scoring computed

Calculating pathways:  38%|███▊      | 219/583 [19:03<32:36,  5.37s/it]

Organelle Biogenesis and Maintenance: pvalue calculation completed
Organelle Biogenesis and Maintenance: Calculation completed
Ovarian Tumor Domain Proteases: Calculation started
Ovarian Tumor Domain Proteases: scoring computed

Calculating pathways:  38%|███▊      | 220/583 [19:06<29:38,  4.90s/it]

Ovarian Tumor Domain Proteases: pvalue calculation completed
Ovarian Tumor Domain Proteases: Calculation completed
PECAM1 Interactions: Calculation started
PECAM1 Interactions: scoring computed

Calculating pathways:  38%|███▊      | 221/583 [19:10<27:03,  4.49s/it]

PECAM1 Interactions: pvalue calculation completed
PECAM1 Interactions: Calculation completed
PI3K Events in ERBB2 Signaling: Calculation started
PI3K Events in ERBB2 Signaling: scoring computed

Calculating pathways:  38%|███▊      | 222/583 [19:13<25:09,  4.18s/it]

PI3K Events in ERBB2 Signaling: pvalue calculation completed
PI3K Events in ERBB2 Signaling: Calculation completed
PI3K AKT Signaling in Cancer: Calculation started
PI3K AKT Signaling in Cancer: scoring computed

Calculating pathways:  38%|███▊      | 223/583 [19:18<25:48,  4.30s/it]

PI3K AKT Signaling in Cancer: pvalue calculation completed
PI3K AKT Signaling in Cancer: Calculation completed
PI5P, PP2A and IER3 Regulate PI3K AKT Signaling: Calculation started
PI5P, PP2A and IER3 Regulate PI3K AKT Signaling: scoring computed

Calculating pathways:  38%|███▊      | 224/583 [19:22<26:10,  4.38s/it]

PI5P, PP2A and IER3 Regulate PI3K AKT Signaling: pvalue calculation completed
PI5P, PP2A and IER3 Regulate PI3K AKT Signaling: Calculation completed
PIP3 Activates AKT Signaling: Calculation started
PIP3 Activates AKT Signaling: scoring computed

Calculating pathways:  39%|███▊      | 225/583 [19:29<29:27,  4.94s/it]

PIP3 Activates AKT Signaling: pvalue calculation completed
PIP3 Activates AKT Signaling: Calculation completed
PKR-mediated Signaling: Calculation started
PKR-mediated Signaling: scoring computed

Calculating pathways:  39%|███▉      | 226/583 [19:33<27:58,  4.70s/it]

PKR-mediated Signaling: pvalue calculation completed
PKR-mediated Signaling: Calculation completed
Parasite Infection: Calculation started
Parasite Infection: scoring computed

Calculating pathways:  39%|███▉      | 227/583 [19:37<27:10,  4.58s/it]

Parasite Infection: pvalue calculation completed
Parasite Infection: Calculation completed
Parasitic Infection Pathways: Calculation started
Parasitic Infection Pathways: scoring computed

Calculating pathways:  39%|███▉      | 228/583 [19:42<28:22,  4.80s/it]

Parasitic Infection Pathways: pvalue calculation completed
Parasitic Infection Pathways: Calculation completed
Peptide Ligand-Binding Receptors: Calculation started
Peptide Ligand-Binding Receptors: scoring computed

Calculating pathways:  39%|███▉      | 229/583 [19:47<28:31,  4.84s/it]

Peptide Ligand-Binding Receptors: pvalue calculation completed
Peptide Ligand-Binding Receptors: Calculation completed
Platelet Adhesion to Exposed Collagen: Calculation started
Platelet Adhesion to Exposed Collagen: scoring computed

Calculating pathways:  39%|███▉      | 230/583 [19:51<26:01,  4.42s/it]

Platelet Adhesion to Exposed Collagen: pvalue calculation completed
Platelet Adhesion to Exposed Collagen: Calculation completed
Platelet Activation, Signaling and Aggregation: Calculation started
Platelet Activation, Signaling and Aggregation: scoring computed

Calculating pathways:  40%|███▉      | 231/583 [19:57<28:47,  4.91s/it]

Platelet Activation, Signaling and Aggregation: pvalue calculation completed
Platelet Activation, Signaling and Aggregation: Calculation completed
Post NMDA Receptor Activation Events: Calculation started
Post NMDA Receptor Activation Events: scoring computed

Calculating pathways:  40%|███▉      | 232/583 [20:01<27:57,  4.78s/it]

Post NMDA Receptor Activation Events: pvalue calculation completed
Post NMDA Receptor Activation Events: Calculation completed
Post-chaperonin Tubulin Folding Pathway: Calculation started
Post-chaperonin Tubulin Folding Pathway: scoring computed

Calculating pathways:  40%|███▉      | 233/583 [20:05<25:39,  4.40s/it]

Post-chaperonin Tubulin Folding Pathway: pvalue calculation completed
Post-chaperonin Tubulin Folding Pathway: Calculation completed
Post-translational Protein Modification: Calculation started
Post-translational Protein Modification: scoring computed

Calculating pathways:  40%|████      | 234/583 [20:23<48:52,  8.40s/it]

Post-translational Protein Modification: pvalue calculation completed
Post-translational Protein Modification: Calculation completed
Potential Therapeutics for SARS: Calculation started
Potential Therapeutics for SARS: scoring computed

Calculating pathways:  40%|████      | 235/583 [20:27<41:51,  7.22s/it]

Potential Therapeutics for SARS: pvalue calculation completed
Potential Therapeutics for SARS: Calculation completed
Prednisone ADME: Calculation started
Prednisone ADME: scoring computed

Calculating pathways:  40%|████      | 236/583 [20:31<35:18,  6.11s/it]

Prednisone ADME: pvalue calculation completed
Prednisone ADME: Calculation completed
Prefoldin Mediated Transfer of Substrate to CCT TriC: Calculation started
Prefoldin Mediated Transfer of Substrate to CCT TriC: scoring computed

Calculating pathways:  41%|████      | 237/583 [20:34<30:49,  5.35s/it]

Prefoldin Mediated Transfer of Substrate to CCT TriC: pvalue calculation completed
Prefoldin Mediated Transfer of Substrate to CCT TriC: Calculation completed
Protein Folding: Calculation started
Protein Folding: scoring computed

Calculating pathways:  41%|████      | 238/583 [20:39<29:13,  5.08s/it]

Protein Folding: pvalue calculation completed
Protein Folding: Calculation completed
RAF MAP Kinase Cascade: Calculation started
RAF MAP Kinase Cascade: scoring computed

Calculating pathways:  41%|████      | 239/583 [20:45<30:51,  5.38s/it]

RAF MAP Kinase Cascade: pvalue calculation completed
RAF MAP Kinase Cascade: Calculation completed
RHO GTPase Effectors: Calculation started
RHO GTPase Effectors: scoring computed

Calculating pathways:  41%|████      | 240/583 [20:51<32:39,  5.71s/it]

RHO GTPase Effectors: pvalue calculation completed
RHO GTPase Effectors: Calculation completed
RHO GTPases Activate Formins: Calculation started
RHO GTPases Activate Formins: scoring computed

Calculating pathways:  41%|████▏     | 241/583 [20:56<31:03,  5.45s/it]

RHO GTPases Activate Formins: pvalue calculation completed
RHO GTPases Activate Formins: Calculation completed
RHO GTPases Activate IQGAPs: Calculation started
RHO GTPases Activate IQGAPs: scoring computed

Calculating pathways:  42%|████▏     | 242/583 [21:00<27:51,  4.90s/it]

RHO GTPases Activate IQGAPs: pvalue calculation completed
RHO GTPases Activate IQGAPs: Calculation completed
RNA Polymerase II Transcription: Calculation started
RNA Polymerase II Transcription: scoring computed

Calculating pathways:  42%|████▏     | 243/583 [21:16<48:02,  8.48s/it]

RNA Polymerase II Transcription: pvalue calculation completed
RNA Polymerase II Transcription: Calculation completed
Recruitment of NuMA to Mitotic Centrosomes: Calculation started
Recruitment of NuMA to Mitotic Centrosomes: scoring computed

Calculating pathways:  42%|████▏     | 244/583 [21:21<41:00,  7.26s/it]

Recruitment of NuMA to Mitotic Centrosomes: pvalue calculation completed
Recruitment of NuMA to Mitotic Centrosomes: Calculation completed
Recruitment of Mitotic Centrosome Proteins and Complexes: Calculation started
Recruitment of Mitotic Centrosome Proteins and Complexes: scoring computed

Calculating pathways:  42%|████▏     | 245/583 [21:25<35:49,  6.36s/it]

Recruitment of Mitotic Centrosome Proteins and Complexes: pvalue calculation completed
Recruitment of Mitotic Centrosome Proteins and Complexes: Calculation completed
Recycling of Bile Acids and Salts: Calculation started
Recycling of Bile Acids and Salts: scoring computed

Calculating pathways:  42%|████▏     | 246/583 [21:29<30:52,  5.50s/it]

Recycling of Bile Acids and Salts: pvalue calculation completed
Recycling of Bile Acids and Salts: Calculation completed
Recycling Pathway of L1: Calculation started
Recycling Pathway of L1: scoring computed

Calculating pathways:  42%|████▏     | 247/583 [21:32<27:58,  4.99s/it]

Recycling Pathway of L1: pvalue calculation completed
Recycling Pathway of L1: Calculation completed
Reelin Signalling Pathway: Calculation started
Reelin Signalling Pathway: scoring computed

Calculating pathways:  43%|████▎     | 248/583 [21:36<25:08,  4.50s/it]

Reelin Signalling Pathway: pvalue calculation completed
Reelin Signalling Pathway: Calculation completed
Regulation of KIT Signaling: Calculation started
Regulation of KIT Signaling: scoring computed

Calculating pathways:  43%|████▎     | 249/583 [21:39<23:21,  4.20s/it]

Regulation of KIT Signaling: pvalue calculation completed
Regulation of KIT Signaling: Calculation completed
Regulation of PLK1 Activity at G2 M Transition: Calculation started
Regulation of PLK1 Activity at G2 M Transition: scoring computed

Calculating pathways:  43%|████▎     | 250/583 [21:44<23:36,  4.25s/it]

Regulation of PLK1 Activity at G2 M Transition: pvalue calculation completed
Regulation of PLK1 Activity at G2 M Transition: Calculation completed
Regulation of Signaling by CBL: Calculation started
Regulation of Signaling by CBL: scoring computed

Calculating pathways:  43%|████▎     | 251/583 [21:47<22:38,  4.09s/it]

Regulation of Signaling by CBL: pvalue calculation completed
Regulation of Signaling by CBL: Calculation completed
Resolution of Sister Chromatid Cohesion: Calculation started
Resolution of Sister Chromatid Cohesion: scoring computed

Calculating pathways:  43%|████▎     | 252/583 [21:52<23:35,  4.28s/it]

Resolution of Sister Chromatid Cohesion: pvalue calculation completed
Resolution of Sister Chromatid Cohesion: Calculation completed
Response of Endothelial Cells to Shear Stress: Calculation started
Response of Endothelial Cells to Shear Stress: scoring computed

Calculating pathways:  43%|████▎     | 253/583 [21:56<23:27,  4.27s/it]

Response of Endothelial Cells to Shear Stress: pvalue calculation completed
Response of Endothelial Cells to Shear Stress: Calculation completed
Role of LAT2 NTAL LAB on Calcium Mobilization: Calculation started
Role of LAT2 NTAL LAB on Calcium Mobilization: scoring computed

Calculating pathways:  44%|████▎     | 254/583 [22:00<22:16,  4.06s/it]

Role of LAT2 NTAL LAB on Calcium Mobilization: pvalue calculation completed
Role of LAT2 NTAL LAB on Calcium Mobilization: Calculation completed
SARS-CoV Infections: Calculation started
SARS-CoV Infections: scoring computed

Calculating pathways:  44%|████▎     | 255/583 [22:08<28:07,  5.14s/it]

SARS-CoV Infections: pvalue calculation completed
SARS-CoV Infections: Calculation completed
SARS-CoV-2 Infection: Calculation started
SARS-CoV-2 Infection: scoring computed

Calculating pathways:  44%|████▍     | 256/583 [22:14<30:06,  5.52s/it]

SARS-CoV-2 Infection: pvalue calculation completed
SARS-CoV-2 Infection: Calculation completed
SARS-CoV-2 Activates Modulates Innate and Adaptive Immune Responses: Calculation started
SARS-CoV-2 Activates Modulates Innate and Adaptive Immune Responses: scoring computed

Calculating pathways:  44%|████▍     | 257/583 [22:18<28:18,  5.21s/it]

SARS-CoV-2 Activates Modulates Innate and Adaptive Immune Responses: pvalue calculation completed
SARS-CoV-2 Activates Modulates Innate and Adaptive Immune Responses: Calculation completed
SARS-CoV-2-host Interactions: Calculation started
SARS-CoV-2-host Interactions: scoring computed

Calculating pathways:  44%|████▍     | 258/583 [22:24<28:37,  5.28s/it]

SARS-CoV-2-host Interactions: pvalue calculation completed
SARS-CoV-2-host Interactions: Calculation completed
SEMA3A-Plexin Repulsion Signaling by Inhibiting Integrin Adhesion: Calculation started
SEMA3A-Plexin Repulsion Signaling by Inhibiting Integrin Adhesion: scoring computed

Calculating pathways:  44%|████▍     | 259/583 [22:27<25:33,  4.73s/it]

SEMA3A-Plexin Repulsion Signaling by Inhibiting Integrin Adhesion: pvalue calculation completed
SEMA3A-Plexin Repulsion Signaling by Inhibiting Integrin Adhesion: Calculation completed
SHC1 Events in ERBB2 Signaling: Calculation started
SHC1 Events in ERBB2 Signaling: scoring computed

Calculating pathways:  45%|████▍     | 260/583 [22:31<23:31,  4.37s/it]

SHC1 Events in ERBB2 Signaling: pvalue calculation completed
SHC1 Events in ERBB2 Signaling: Calculation completed
SUMO E3 Ligases SUMOylate Target Proteins: Calculation started
SUMO E3 Ligases SUMOylate Target Proteins: scoring computed

Calculating pathways:  45%|████▍     | 261/583 [22:36<24:35,  4.58s/it]

SUMO E3 Ligases SUMOylate Target Proteins: pvalue calculation completed
SUMO E3 Ligases SUMOylate Target Proteins: Calculation completed
SUMOylation: Calculation started
SUMOylation: scoring computed

Calculating pathways:  45%|████▍     | 262/583 [22:41<25:24,  4.75s/it]

SUMOylation: pvalue calculation completed
SUMOylation: Calculation completed
SUMOylation of Intracellular Receptors: Calculation started
SUMOylation of Intracellular Receptors: scoring computed

Calculating pathways:  45%|████▌     | 263/583 [22:45<23:38,  4.43s/it]

SUMOylation of Intracellular Receptors: pvalue calculation completed
SUMOylation of Intracellular Receptors: Calculation completed
Sealing of the Nuclear Envelope (NE) by ESCRT-III: Calculation started
Sealing of the Nuclear Envelope (NE) by ESCRT-III: scoring computed

Calculating pathways:  45%|████▌     | 264/583 [22:49<22:27,  4.22s/it]

Sealing of the Nuclear Envelope (NE) by ESCRT-III: pvalue calculation completed
Sealing of the Nuclear Envelope (NE) by ESCRT-III: Calculation completed
Selective Autophagy: Calculation started
Selective Autophagy: scoring computed

Calculating pathways:  45%|████▌     | 265/583 [22:53<22:37,  4.27s/it]

Selective Autophagy: pvalue calculation completed
Selective Autophagy: Calculation completed
Sema3A PAK Dependent Axon Repulsion: Calculation started
Sema3A PAK Dependent Axon Repulsion: scoring computed

Calculating pathways:  46%|████▌     | 266/583 [22:56<21:12,  4.01s/it]

Sema3A PAK Dependent Axon Repulsion: pvalue calculation completed
Sema3A PAK Dependent Axon Repulsion: Calculation completed
Sema4D in Semaphorin Signaling: Calculation started
Sema4D in Semaphorin Signaling: scoring computed

Calculating pathways:  46%|████▌     | 267/583 [23:00<20:21,  3.87s/it]

Sema4D in Semaphorin Signaling: pvalue calculation completed
Sema4D in Semaphorin Signaling: Calculation completed
Sema4D Induced Cell Migration and Growth-Cone Collapse: Calculation started
Sema4D Induced Cell Migration and Growth-Cone Collapse: scoring computed

Calculating pathways:  46%|████▌     | 268/583 [23:03<19:44,  3.76s/it]

Sema4D Induced Cell Migration and Growth-Cone Collapse: pvalue calculation completed
Sema4D Induced Cell Migration and Growth-Cone Collapse: Calculation completed
Semaphorin Interactions: Calculation started
Semaphorin Interactions: scoring computed

Calculating pathways:  46%|████▌     | 269/583 [23:07<20:02,  3.83s/it]

Semaphorin Interactions: pvalue calculation completed
Semaphorin Interactions: Calculation completed
Separation of Sister Chromatids: Calculation started
Separation of Sister Chromatids: scoring computed

Calculating pathways:  46%|████▋     | 270/583 [23:12<22:03,  4.23s/it]

Separation of Sister Chromatids: pvalue calculation completed
Separation of Sister Chromatids: Calculation completed
Signaling by CSF1 (M-CSF) in Myeloid Cells: Calculation started
Signaling by CSF1 (M-CSF) in Myeloid Cells: scoring computed

Calculating pathways:  46%|████▋     | 271/583 [23:16<21:27,  4.13s/it]

Signaling by CSF1 (M-CSF) in Myeloid Cells: pvalue calculation completed
Signaling by CSF1 (M-CSF) in Myeloid Cells: Calculation completed
Signaling by ERBB2: Calculation started
Signaling by ERBB2: scoring computed

Calculating pathways:  47%|████▋     | 272/583 [23:20<21:01,  4.06s/it]

Signaling by ERBB2: pvalue calculation completed
Signaling by ERBB2: Calculation completed
Signaling by ERBB2 ECD Mutants: Calculation started
Signaling by ERBB2 ECD Mutants: scoring computed

Calculating pathways:  47%|████▋     | 273/583 [23:24<19:57,  3.86s/it]

Signaling by ERBB2 ECD Mutants: pvalue calculation completed
Signaling by ERBB2 ECD Mutants: Calculation completed
Signaling by ERBB2 KD Mutants: Calculation started
Signaling by ERBB2 KD Mutants: scoring computed

Calculating pathways:  47%|████▋     | 274/583 [23:27<19:26,  3.77s/it]

Signaling by ERBB2 KD Mutants: pvalue calculation completed
Signaling by ERBB2 KD Mutants: Calculation completed
Signaling by ERBB2 TMD JMD Mutants: Calculation started
Signaling by ERBB2 TMD JMD Mutants: scoring computed

Calculating pathways:  47%|████▋     | 275/583 [23:31<19:01,  3.71s/it]

Signaling by ERBB2 TMD JMD Mutants: pvalue calculation completed
Signaling by ERBB2 TMD JMD Mutants: Calculation completed
Signaling by ERBB2 in Cancer: Calculation started
Signaling by ERBB2 in Cancer: scoring computed

Calculating pathways:  47%|████▋     | 276/583 [23:34<18:51,  3.69s/it]

Signaling by ERBB2 in Cancer: pvalue calculation completed
Signaling by ERBB2 in Cancer: Calculation completed
Signaling by GPCR: Calculation started
Signaling by GPCR: scoring computed

Calculating pathways:  48%|████▊     | 277/583 [23:44<27:31,  5.40s/it]

Signaling by GPCR: pvalue calculation completed
Signaling by GPCR: Calculation completed
Signaling by Hedgehog: Calculation started
Signaling by Hedgehog: scoring computed

Calculating pathways:  48%|████▊     | 278/583 [23:49<26:27,  5.20s/it]

Signaling by Hedgehog: pvalue calculation completed
Signaling by Hedgehog: Calculation completed
Signaling by Interleukins: Calculation started
Signaling by Interleukins: scoring computed

Calculating pathways:  48%|████▊     | 279/583 [23:56<30:10,  5.96s/it]

Signaling by Interleukins: pvalue calculation completed
Signaling by Interleukins: Calculation completed
Signaling by KIT in Disease: Calculation started
Signaling by KIT in Disease: scoring computed

Calculating pathways:  48%|████▊     | 280/583 [24:00<26:26,  5.24s/it]

Signaling by KIT in Disease: pvalue calculation completed
Signaling by KIT in Disease: Calculation completed
Signaling by NTRK2 (TRKB): Calculation started
Signaling by NTRK2 (TRKB): scoring computed

Calculating pathways:  48%|████▊     | 281/583 [24:03<23:50,  4.74s/it]

Signaling by NTRK2 (TRKB): pvalue calculation completed
Signaling by NTRK2 (TRKB): Calculation completed
Signaling by NTRKs: Calculation started
Signaling by NTRKs: scoring computed

Calculating pathways:  48%|████▊     | 282/583 [24:08<23:49,  4.75s/it]

Signaling by NTRKs: pvalue calculation completed
Signaling by NTRKs: Calculation completed
Signaling by Non-Receptor Tyrosine Kinases: Calculation started
Signaling by Non-Receptor Tyrosine Kinases: scoring computed

Calculating pathways:  49%|████▊     | 283/583 [24:12<22:23,  4.48s/it]

Signaling by Non-Receptor Tyrosine Kinases: pvalue calculation completed
Signaling by Non-Receptor Tyrosine Kinases: Calculation completed
Signaling by PTK6: Calculation started
Signaling by PTK6: scoring computed

Calculating pathways:  49%|████▊     | 284/583 [24:16<21:50,  4.38s/it]

Signaling by PTK6: pvalue calculation completed
Signaling by PTK6: Calculation completed
Signaling by Receptor Tyrosine Kinases: Calculation started
Signaling by Receptor Tyrosine Kinases: scoring computed

Calculating pathways:  49%|████▉     | 285/583 [24:25<28:31,  5.74s/it]

Signaling by Receptor Tyrosine Kinases: pvalue calculation completed
Signaling by Receptor Tyrosine Kinases: Calculation completed
Signaling by Rho GTPases: Calculation started
Signaling by Rho GTPases: scoring computed

Calculating pathways:  49%|████▉     | 286/583 [24:35<35:10,  7.11s/it]

Signaling by Rho GTPases: pvalue calculation completed
Signaling by Rho GTPases: Calculation completed
Signaling by Rho GTPases, Miro GTPases and RHOBTB3: Calculation started
Signaling by Rho GTPases, Miro GTPases and RHOBTB3: scoring computed

Calculating pathways:  49%|████▉     | 287/583 [24:46<40:16,  8.16s/it]

Signaling by Rho GTPases, Miro GTPases and RHOBTB3: pvalue calculation completed
Signaling by Rho GTPases, Miro GTPases and RHOBTB3: Calculation completed
Signaling by SCF-KIT: Calculation started
Signaling by SCF-KIT: scoring computed

Calculating pathways:  49%|████▉     | 288/583 [24:50<33:37,  6.84s/it]

Signaling by SCF-KIT: pvalue calculation completed
Signaling by SCF-KIT: Calculation completed
Signaling by VEGF: Calculation started
Signaling by VEGF: scoring computed

Calculating pathways:  50%|████▉     | 289/583 [24:54<29:56,  6.11s/it]

Signaling by VEGF: pvalue calculation completed
Signaling by VEGF: Calculation completed
Signaling by Phosphorylated Juxtamembrane, Extracellular and Kinase Domain KIT Mutants: Calculation started
Signaling by Phosphorylated Juxtamembrane, Extracellular and Kinase Domain KIT Mutants: scoring computed

Calculating pathways:  50%|████▉     | 290/583 [24:58<26:02,  5.33s/it]

Signaling by Phosphorylated Juxtamembrane, Extracellular and Kinase Domain KIT Mutants: pvalue calculation completed
Signaling by Phosphorylated Juxtamembrane, Extracellular and Kinase Domain KIT Mutants: Calculation completed
Signaling by the B Cell Receptor (BCR): Calculation started
Signaling by the B Cell Receptor (BCR): scoring computed

Calculating pathways:  50%|████▉     | 291/583 [25:02<24:43,  5.08s/it]

Signaling by the B Cell Receptor (BCR): pvalue calculation completed
Signaling by the B Cell Receptor (BCR): Calculation completed
Synthesis of Bile Acids and Bile Salts: Calculation started
Synthesis of Bile Acids and Bile Salts: scoring computed

Calculating pathways:  50%|█████     | 292/583 [25:06<22:35,  4.66s/it]

Synthesis of Bile Acids and Bile Salts: pvalue calculation completed
Synthesis of Bile Acids and Bile Salts: Calculation completed
Synthesis of Bile Acids and Bile Salts via 7Alpha-Hydroxycholesterol: Calculation started
Synthesis of Bile Acids and Bile Salts via 7Alpha-Hydroxycholesterol: scoring computed

Calculating pathways:  50%|█████     | 293/583 [25:09<20:47,  4.30s/it]

Synthesis of Bile Acids and Bile Salts via 7Alpha-Hydroxycholesterol: pvalue calculation completed
Synthesis of Bile Acids and Bile Salts via 7Alpha-Hydroxycholesterol: Calculation completed
TAK1-dependent IKK and NF-kappa-B Activation: Calculation started
TAK1-dependent IKK and NF-kappa-B Activation: scoring computed

Calculating pathways:  50%|█████     | 294/583 [25:13<19:52,  4.13s/it]

TAK1-dependent IKK and NF-kappa-B Activation: pvalue calculation completed
TAK1-dependent IKK and NF-kappa-B Activation: Calculation completed
TFAP2 (AP-2) Family Regulates Transcription of Growth Factors and Their Receptors: Calculation started
TFAP2 (AP-2) Family Regulates Transcription of Growth Factors and Their Receptors: scoring computed

Calculating pathways:  51%|█████     | 295/583 [25:16<18:44,  3.90s/it]

TFAP2 (AP-2) Family Regulates Transcription of Growth Factors and Their Receptors: pvalue calculation completed
TFAP2 (AP-2) Family Regulates Transcription of Growth Factors and Their Receptors: Calculation completed
TRAF6 Mediated Induction of NFkB and MAP Kinases Upon TLR7 8 or 9 Activation: Calculation started
TRAF6 Mediated Induction of NFkB and MAP Kinases Upon TLR7 8 or 9 Activation: scoring computed

Calculating pathways:  51%|█████     | 296/583 [25:21<19:19,  4.04s/it]

TRAF6 Mediated Induction of NFkB and MAP Kinases Upon TLR7 8 or 9 Activation: pvalue calculation completed
TRAF6 Mediated Induction of NFkB and MAP Kinases Upon TLR7 8 or 9 Activation: Calculation completed
TRIF (TICAM1)-mediated TLR4 Signaling: Calculation started
TRIF (TICAM1)-mediated TLR4 Signaling: scoring computed

Calculating pathways:  51%|█████     | 297/583 [25:25<19:51,  4.17s/it]

TRIF (TICAM1)-mediated TLR4 Signaling: pvalue calculation completed
TRIF (TICAM1)-mediated TLR4 Signaling: Calculation completed
Tachykinin Receptors Bind Tachykinins: Calculation started
Tachykinin Receptors Bind Tachykinins: scoring computed

Calculating pathways:  51%|█████     | 298/583 [25:29<18:38,  3.93s/it]

Tachykinin Receptors Bind Tachykinins: pvalue calculation completed
Tachykinin Receptors Bind Tachykinins: Calculation completed
The Role of GTSE1 in G2 M Progression After G2 Checkpoint: Calculation started
The Role of GTSE1 in G2 M Progression After G2 Checkpoint: scoring computed

Calculating pathways:  51%|█████▏    | 299/583 [25:33<18:43,  3.96s/it]

The Role of GTSE1 in G2 M Progression After G2 Checkpoint: pvalue calculation completed
The Role of GTSE1 in G2 M Progression After G2 Checkpoint: Calculation completed
The Role of Nef in HIV-1 Replication and Disease Pathogenesis: Calculation started
The Role of Nef in HIV-1 Replication and Disease Pathogenesis: scoring computed

Calculating pathways:  51%|█████▏    | 300/583 [25:36<18:11,  3.86s/it]

The Role of Nef in HIV-1 Replication and Disease Pathogenesis: pvalue calculation completed
The Role of Nef in HIV-1 Replication and Disease Pathogenesis: Calculation completed
Toll Like Receptor 10 (TLR10) Cascade: Calculation started
Toll Like Receptor 10 (TLR10) Cascade: scoring computed

Calculating pathways:  52%|█████▏    | 301/583 [25:41<18:52,  4.02s/it]

Toll Like Receptor 10 (TLR10) Cascade: pvalue calculation completed
Toll Like Receptor 10 (TLR10) Cascade: Calculation completed
Toll Like Receptor 2 (TLR2) Cascade: Calculation started
Toll Like Receptor 2 (TLR2) Cascade: scoring computed

Calculating pathways:  52%|█████▏    | 302/583 [25:45<19:36,  4.19s/it]

Toll Like Receptor 2 (TLR2) Cascade: pvalue calculation completed
Toll Like Receptor 2 (TLR2) Cascade: Calculation completed
Toll Like Receptor 3 (TLR3) Cascade: Calculation started
Toll Like Receptor 3 (TLR3) Cascade: scoring computed

Calculating pathways:  52%|█████▏    | 303/583 [25:50<19:56,  4.27s/it]

Toll Like Receptor 3 (TLR3) Cascade: pvalue calculation completed
Toll Like Receptor 3 (TLR3) Cascade: Calculation completed
Toll Like Receptor 4 (TLR4) Cascade: Calculation started
Toll Like Receptor 4 (TLR4) Cascade: scoring computed

Calculating pathways:  52%|█████▏    | 304/583 [25:55<21:07,  4.54s/it]

Toll Like Receptor 4 (TLR4) Cascade: pvalue calculation completed
Toll Like Receptor 4 (TLR4) Cascade: Calculation completed
Toll Like Receptor 5 (TLR5) Cascade: Calculation started
Toll Like Receptor 5 (TLR5) Cascade: scoring computed

Calculating pathways:  52%|█████▏    | 305/583 [25:59<21:04,  4.55s/it]

Toll Like Receptor 5 (TLR5) Cascade: pvalue calculation completed
Toll Like Receptor 5 (TLR5) Cascade: Calculation completed
Toll Like Receptor 7 8 (TLR7 8) Cascade: Calculation started
Toll Like Receptor 7 8 (TLR7 8) Cascade: scoring computed

Calculating pathways:  52%|█████▏    | 306/583 [26:04<21:20,  4.62s/it]

Toll Like Receptor 7 8 (TLR7 8) Cascade: pvalue calculation completed
Toll Like Receptor 7 8 (TLR7 8) Cascade: Calculation completed
Toll Like Receptor 9 (TLR9) Cascade: Calculation started
Toll Like Receptor 9 (TLR9) Cascade: scoring computed

Calculating pathways:  53%|█████▎    | 307/583 [26:09<21:22,  4.65s/it]

Toll Like Receptor 9 (TLR9) Cascade: pvalue calculation completed
Toll Like Receptor 9 (TLR9) Cascade: Calculation completed
Toll Like Receptor TLR1 TLR2 Cascade: Calculation started
Toll Like Receptor TLR1 TLR2 Cascade: scoring computed

Calculating pathways:  53%|█████▎    | 308/583 [26:14<21:26,  4.68s/it]

Toll Like Receptor TLR1 TLR2 Cascade: pvalue calculation completed
Toll Like Receptor TLR1 TLR2 Cascade: Calculation completed
Toll Like Receptor TLR6 TLR2 Cascade: Calculation started
Toll Like Receptor TLR6 TLR2 Cascade: scoring computed

Calculating pathways:  53%|█████▎    | 309/583 [26:19<21:45,  4.76s/it]

Toll Like Receptor TLR6 TLR2 Cascade: pvalue calculation completed
Toll Like Receptor TLR6 TLR2 Cascade: Calculation completed
Toll-like Receptor Cascades: Calculation started
Toll-like Receptor Cascades: scoring computed

Calculating pathways:  53%|█████▎    | 310/583 [26:24<22:47,  5.01s/it]

Toll-like Receptor Cascades: pvalue calculation completed
Toll-like Receptor Cascades: Calculation completed
Transcriptional and Post-Translational Regulation of MITF-M Expression and Activity: Calculation started
Transcriptional and Post-Translational Regulation of MITF-M Expression and Activity: scoring computed

Calculating pathways:  53%|█████▎    | 311/583 [26:28<21:16,  4.69s/it]

Transcriptional and Post-Translational Regulation of MITF-M Expression and Activity: pvalue calculation completed
Transcriptional and Post-Translational Regulation of MITF-M Expression and Activity: Calculation completed
Transcriptional Regulation by the AP-2 (TFAP2) Family of Transcription Factors: Calculation started
Transcriptional Regulation by the AP-2 (TFAP2) Family of Transcription Factors: scoring computed

Calculating pathways:  54%|█████▎    | 312/583 [26:32<20:03,  4.44s/it]

Transcriptional Regulation by the AP-2 (TFAP2) Family of Transcription Factors: pvalue calculation completed
Transcriptional Regulation by the AP-2 (TFAP2) Family of Transcription Factors: Calculation completed
Translocation of SLC2A4 (GLUT4) to the Plasma Membrane: Calculation started
Translocation of SLC2A4 (GLUT4) to the Plasma Membrane: scoring computed

Calculating pathways:  54%|█████▎    | 313/583 [26:36<19:51,  4.41s/it]

Translocation of SLC2A4 (GLUT4) to the Plasma Membrane: pvalue calculation completed
Translocation of SLC2A4 (GLUT4) to the Plasma Membrane: Calculation completed
Transmission Across Chemical Synapses: Calculation started
Transmission Across Chemical Synapses: scoring computed

Calculating pathways:  54%|█████▍    | 314/583 [26:43<22:34,  5.04s/it]

Transmission Across Chemical Synapses: pvalue calculation completed
Transmission Across Chemical Synapses: Calculation completed
Transport of Connexons to the Plasma Membrane: Calculation started
Transport of Connexons to the Plasma Membrane: scoring computed

Calculating pathways:  54%|█████▍    | 315/583 [26:46<20:31,  4.60s/it]

Transport of Connexons to the Plasma Membrane: pvalue calculation completed
Transport of Connexons to the Plasma Membrane: Calculation completed
Transport of Small Molecules: Calculation started
Transport of Small Molecules: scoring computed

Calculating pathways:  54%|█████▍    | 316/583 [26:57<28:51,  6.48s/it]

Transport of Small Molecules: pvalue calculation completed
Transport of Small Molecules: Calculation completed
Transport to the Golgi and Subsequent Modification: Calculation started
Transport to the Golgi and Subsequent Modification: scoring computed

Calculating pathways:  54%|█████▍    | 317/583 [27:03<27:44,  6.26s/it]

Transport to the Golgi and Subsequent Modification: pvalue calculation completed
Transport to the Golgi and Subsequent Modification: Calculation completed
VEGFA-VEGFR2 Pathway: Calculation started
VEGFA-VEGFR2 Pathway: scoring computed

Calculating pathways:  55%|█████▍    | 318/583 [27:08<25:19,  5.73s/it]

VEGFA-VEGFR2 Pathway: pvalue calculation completed
VEGFA-VEGFR2 Pathway: Calculation completed
Vesicle-mediated Transport: Calculation started
Vesicle-mediated Transport: scoring computed

Calculating pathways:  55%|█████▍    | 319/583 [27:19<32:18,  7.34s/it]

Vesicle-mediated Transport: pvalue calculation completed
Vesicle-mediated Transport: Calculation completed
Viral Infection Pathways: Calculation started
Viral Infection Pathways: scoring computed

Calculating pathways:  55%|█████▍    | 320/583 [27:31<38:15,  8.73s/it]

Viral Infection Pathways: pvalue calculation completed
Viral Infection Pathways: Calculation completed
Activated TAK1 Mediates P38 MAPK Activation: Calculation started
Activated TAK1 Mediates P38 MAPK Activation: scoring computed

Calculating pathways:  55%|█████▌    | 321/583 [27:34<31:28,  7.21s/it]

Activated TAK1 Mediates P38 MAPK Activation: pvalue calculation completed
Activated TAK1 Mediates P38 MAPK Activation: Calculation completed
ERBB Signaling Pathway (GO:0038127): Calculation started
ERBB Signaling Pathway (GO:0038127): scoring computed

Calculating pathways:  55%|█████▌    | 322/583 [27:39<27:30,  6.32s/it]

ERBB Signaling Pathway (GO:0038127): pvalue calculation completed
ERBB Signaling Pathway (GO:0038127): Calculation completed
ERBB2 Signaling Pathway (GO:0038128): Calculation started
ERBB2 Signaling Pathway (GO:0038128): scoring computed

Calculating pathways:  55%|█████▌    | 323/583 [27:42<23:46,  5.48s/it]

ERBB2 Signaling Pathway (GO:0038128): pvalue calculation completed
ERBB2 Signaling Pathway (GO:0038128): Calculation completed
ERBB2-EGFR Signaling Pathway (GO:0038134): Calculation started
ERBB2-EGFR Signaling Pathway (GO:0038134): scoring computed

Calculating pathways:  56%|█████▌    | 324/583 [27:46<21:12,  4.91s/it]

ERBB2-EGFR Signaling Pathway (GO:0038134): pvalue calculation completed
ERBB2-EGFR Signaling Pathway (GO:0038134): Calculation completed
Fc Receptor Mediated Stimulatory Signaling Pathway (GO:0002431): Calculation started
Fc Receptor Mediated Stimulatory Signaling Pathway (GO:0002431): scoring computed

Calculating pathways:  56%|█████▌    | 325/583 [27:49<19:30,  4.54s/it]

Fc Receptor Mediated Stimulatory Signaling Pathway (GO:0002431): pvalue calculation completed
Fc Receptor Mediated Stimulatory Signaling Pathway (GO:0002431): Calculation completed
Fc-gamma Receptor Signaling Pathway (GO:0038094): Calculation started
Fc-gamma Receptor Signaling Pathway (GO:0038094): scoring computed

Calculating pathways:  56%|█████▌    | 326/583 [27:53<18:12,  4.25s/it]

Fc-gamma Receptor Signaling Pathway (GO:0038094): pvalue calculation completed
Fc-gamma Receptor Signaling Pathway (GO:0038094): Calculation completed
Fc-gamma Receptor Signaling Pathway Involved in Phagocytosis (GO:0038096): Calculation started
Fc-gamma Receptor Signaling Pathway Involved in Phagocytosis (GO:0038096): scoring computed

Calculating pathways:  56%|█████▌    | 327/583 [27:56<17:12,  4.03s/it]

Fc-gamma Receptor Signaling Pathway Involved in Phagocytosis (GO:0038096): pvalue calculation completed
Fc-gamma Receptor Signaling Pathway Involved in Phagocytosis (GO:0038096): Calculation completed
GPCR Sgnlng Pway, Coupled to Cyclic Nucleotide Second Messenger (GO:0007187): Calculation started
GPCR Sgnlng Pway, Coupled to Cyclic Nucleotide Second Messenger (GO:0007187): scoring computed

Calculating pathways:  56%|█████▋    | 328/583 [28:00<16:43,  3.93s/it]

GPCR Sgnlng Pway, Coupled to Cyclic Nucleotide Second Messenger (GO:0007187): pvalue calculation completed
GPCR Sgnlng Pway, Coupled to Cyclic Nucleotide Second Messenger (GO:0007187): Calculation completed
T Cell Receptor Signaling Pathway (GO:0050852): Calculation started
T Cell Receptor Signaling Pathway (GO:0050852): scoring computed

Calculating pathways:  56%|█████▋    | 329/583 [28:04<16:54,  3.99s/it]

T Cell Receptor Signaling Pathway (GO:0050852): pvalue calculation completed
T Cell Receptor Signaling Pathway (GO:0050852): Calculation completed
Adenylate Cyclase-Activating G Protein-Coupled Receptor Signaling Pathway (GO:0007189): Calculation started
Adenylate Cyclase-Activating G Protein-Coupled Receptor Signaling Pathway (GO:0007189): scoring computed

Calculating pathways:  57%|█████▋    | 330/583 [28:09<17:44,  4.21s/it]

Adenylate Cyclase-Activating G Protein-Coupled Receptor Signaling Pathway (GO:0007189): pvalue calculation completed
Adenylate Cyclase-Activating G Protein-Coupled Receptor Signaling Pathway (GO:0007189): Calculation completed
Adenylate Cyclase-Modulating G Protein-Coupled Receptor Signaling Pathway (GO:0007188): Calculation started
Adenylate Cyclase-Modulating G Protein-Coupled Receptor Signaling Pathway (GO:0007188): scoring computed

Calculating pathways:  57%|█████▋    | 331/583 [28:14<18:56,  4.51s/it]

Adenylate Cyclase-Modulating G Protein-Coupled Receptor Signaling Pathway (GO:0007188): pvalue calculation completed
Adenylate Cyclase-Modulating G Protein-Coupled Receptor Signaling Pathway (GO:0007188): Calculation completed
Antibacterial Innate Immune Response (GO:0140367): Calculation started
Antibacterial Innate Immune Response (GO:0140367): scoring computed

Calculating pathways:  57%|█████▋    | 332/583 [28:18<17:29,  4.18s/it]

Antibacterial Innate Immune Response (GO:0140367): pvalue calculation completed
Antibacterial Innate Immune Response (GO:0140367): Calculation completed
Antigen Receptor-Mediated Signaling Pathway (GO:0050851): Calculation started
Antigen Receptor-Mediated Signaling Pathway (GO:0050851): scoring computed

Calculating pathways:  57%|█████▋    | 333/583 [28:22<17:38,  4.24s/it]

Antigen Receptor-Mediated Signaling Pathway (GO:0050851): pvalue calculation completed
Antigen Receptor-Mediated Signaling Pathway (GO:0050851): Calculation completed
Axon Guidance (GO:0007411): Calculation started
Axon Guidance (GO:0007411): scoring computed

Calculating pathways:  57%|█████▋    | 334/583 [28:27<18:19,  4.42s/it]

Axon Guidance (GO:0007411): pvalue calculation completed
Axon Guidance (GO:0007411): Calculation completed
Axonogenesis (GO:0007409): Calculation started
Axonogenesis (GO:0007409): scoring computed

Calculating pathways:  57%|█████▋    | 335/583 [28:32<19:32,  4.73s/it]

Axonogenesis (GO:0007409): pvalue calculation completed
Axonogenesis (GO:0007409): Calculation completed
Calcium Ion Transport (GO:0006816): Calculation started
Calcium Ion Transport (GO:0006816): scoring computed

Calculating pathways:  58%|█████▊    | 336/583 [28:37<19:07,  4.64s/it]

Calcium Ion Transport (GO:0006816): pvalue calculation completed
Calcium Ion Transport (GO:0006816): Calculation completed
Cell Surface Receptor Protein Tyrosine Kinase Signaling Pathway (GO:0007169): Calculation started
Cell Surface Receptor Protein Tyrosine Kinase Signaling Pathway (GO:0007169): scoring computed

Calculating pathways:  58%|█████▊    | 337/583 [28:43<21:13,  5.18s/it]

Cell Surface Receptor Protein Tyrosine Kinase Signaling Pathway (GO:0007169): pvalue calculation completed
Cell Surface Receptor Protein Tyrosine Kinase Signaling Pathway (GO:0007169): Calculation completed
Cellular Component Maintenance (GO:0043954): Calculation started
Cellular Component Maintenance (GO:0043954): scoring computed

Calculating pathways:  58%|█████▊    | 338/583 [28:47<18:59,  4.65s/it]

Cellular Component Maintenance (GO:0043954): pvalue calculation completed
Cellular Component Maintenance (GO:0043954): Calculation completed
Cellular Response to Amino Acid Stimulus (GO:0071230): Calculation started
Cellular Response to Amino Acid Stimulus (GO:0071230): scoring computed

Calculating pathways:  58%|█████▊    | 339/583 [28:51<18:00,  4.43s/it]

Cellular Response to Amino Acid Stimulus (GO:0071230): pvalue calculation completed
Cellular Response to Amino Acid Stimulus (GO:0071230): Calculation completed
Cellular Response to Amyloid-Beta (GO:1904646): Calculation started
Cellular Response to Amyloid-Beta (GO:1904646): scoring computed

Calculating pathways:  58%|█████▊    | 340/583 [28:54<17:00,  4.20s/it]

Cellular Response to Amyloid-Beta (GO:1904646): pvalue calculation completed
Cellular Response to Amyloid-Beta (GO:1904646): Calculation completed
Cellular Response to Decreased Oxygen Levels (GO:0036294): Calculation started
Cellular Response to Decreased Oxygen Levels (GO:0036294): scoring computed

Calculating pathways:  58%|█████▊    | 341/583 [28:58<16:44,  4.15s/it]

Cellular Response to Decreased Oxygen Levels (GO:0036294): pvalue calculation completed
Cellular Response to Decreased Oxygen Levels (GO:0036294): Calculation completed
Cellular Response to Epidermal Growth Factor Stimulus (GO:0071364): Calculation started
Cellular Response to Epidermal Growth Factor Stimulus (GO:0071364): scoring computed

Calculating pathways:  59%|█████▊    | 342/583 [29:02<16:05,  4.01s/it]

Cellular Response to Epidermal Growth Factor Stimulus (GO:0071364): pvalue calculation completed
Cellular Response to Epidermal Growth Factor Stimulus (GO:0071364): Calculation completed
Cellular Response to Growth Factor Stimulus (GO:0071363): Calculation started
Cellular Response to Growth Factor Stimulus (GO:0071363): scoring computed

Calculating pathways:  59%|█████▉    | 343/583 [29:07<16:56,  4.23s/it]

Cellular Response to Growth Factor Stimulus (GO:0071363): pvalue calculation completed
Cellular Response to Growth Factor Stimulus (GO:0071363): Calculation completed
Cellular Response to Hormone Stimulus (GO:0032870): Calculation started
Cellular Response to Hormone Stimulus (GO:0032870): scoring computed

Calculating pathways:  59%|█████▉    | 344/583 [29:11<16:50,  4.23s/it]

Cellular Response to Hormone Stimulus (GO:0032870): pvalue calculation completed
Cellular Response to Hormone Stimulus (GO:0032870): Calculation completed
Cellular Response to Hydrogen Peroxide (GO:0070301): Calculation started
Cellular Response to Hydrogen Peroxide (GO:0070301): scoring computed

Calculating pathways:  59%|█████▉    | 345/583 [29:15<16:12,  4.09s/it]

Cellular Response to Hydrogen Peroxide (GO:0070301): pvalue calculation completed
Cellular Response to Hydrogen Peroxide (GO:0070301): Calculation completed
Cellular Response to Hypoxia (GO:0071456): Calculation started
Cellular Response to Hypoxia (GO:0071456): scoring computed

Calculating pathways:  59%|█████▉    | 346/583 [29:19<16:13,  4.11s/it]

Cellular Response to Hypoxia (GO:0071456): pvalue calculation completed
Cellular Response to Hypoxia (GO:0071456): Calculation completed
Cellular Response to Lectin (GO:1990858): Calculation started
Cellular Response to Lectin (GO:1990858): scoring computed

Calculating pathways:  60%|█████▉    | 347/583 [29:22<15:25,  3.92s/it]

Cellular Response to Lectin (GO:1990858): pvalue calculation completed
Cellular Response to Lectin (GO:1990858): Calculation completed
Cellular Response to Lipid (GO:0071396): Calculation started
Cellular Response to Lipid (GO:0071396): scoring computed

Calculating pathways:  60%|█████▉    | 348/583 [29:28<17:12,  4.39s/it]

Cellular Response to Lipid (GO:0071396): pvalue calculation completed
Cellular Response to Lipid (GO:0071396): Calculation completed
Cellular Response to Lipopolysaccharide (GO:0071222): Calculation started
Cellular Response to Lipopolysaccharide (GO:0071222): scoring computed

Calculating pathways:  60%|█████▉    | 349/583 [29:32<17:09,  4.40s/it]

Cellular Response to Lipopolysaccharide (GO:0071222): pvalue calculation completed
Cellular Response to Lipopolysaccharide (GO:0071222): Calculation completed
Cellular Response to Molecule of Bacterial Origin (GO:0071219): Calculation started
Cellular Response to Molecule of Bacterial Origin (GO:0071219): scoring computed

Calculating pathways:  60%|██████    | 350/583 [29:37<17:11,  4.43s/it]

Cellular Response to Molecule of Bacterial Origin (GO:0071219): pvalue calculation completed
Cellular Response to Molecule of Bacterial Origin (GO:0071219): Calculation completed
Cellular Response to Muramyl Dipeptide (GO:0071225): Calculation started
Cellular Response to Muramyl Dipeptide (GO:0071225): scoring computed

Calculating pathways:  60%|██████    | 351/583 [29:40<16:02,  4.15s/it]

Cellular Response to Muramyl Dipeptide (GO:0071225): pvalue calculation completed
Cellular Response to Muramyl Dipeptide (GO:0071225): Calculation completed
Cellular Response to Nitrogen Compound (GO:1901699): Calculation started
Cellular Response to Nitrogen Compound (GO:1901699): scoring computed

Calculating pathways:  60%|██████    | 352/583 [29:45<17:00,  4.42s/it]

Cellular Response to Nitrogen Compound (GO:1901699): pvalue calculation completed
Cellular Response to Nitrogen Compound (GO:1901699): Calculation completed
Cellular Response to Oxygen-Containing Compound (GO:1901701): Calculation started
Cellular Response to Oxygen-Containing Compound (GO:1901701): scoring computed

Calculating pathways:  61%|██████    | 353/583 [29:52<19:58,  5.21s/it]

Cellular Response to Oxygen-Containing Compound (GO:1901701): pvalue calculation completed
Cellular Response to Oxygen-Containing Compound (GO:1901701): Calculation completed
Cellular Response to Reactive Oxygen Species (GO:0034614): Calculation started
Cellular Response to Reactive Oxygen Species (GO:0034614): scoring computed

Calculating pathways:  61%|██████    | 354/583 [29:56<18:38,  4.88s/it]

Cellular Response to Reactive Oxygen Species (GO:0034614): pvalue calculation completed
Cellular Response to Reactive Oxygen Species (GO:0034614): Calculation completed
Ceramide Transport (GO:0035627): Calculation started
Ceramide Transport (GO:0035627): scoring computed

Calculating pathways:  61%|██████    | 355/583 [30:00<16:51,  4.44s/it]

Ceramide Transport (GO:0035627): pvalue calculation completed
Ceramide Transport (GO:0035627): Calculation completed
Cholesterol Homeostasis (GO:0042632): Calculation started
Cholesterol Homeostasis (GO:0042632): scoring computed

Calculating pathways:  61%|██████    | 356/583 [30:04<16:23,  4.33s/it]

Cholesterol Homeostasis (GO:0042632): pvalue calculation completed
Cholesterol Homeostasis (GO:0042632): Calculation completed
Cytoskeleton-Dependent Intracellular Transport (GO:0030705): Calculation started
Cytoskeleton-Dependent Intracellular Transport (GO:0030705): scoring computed

Calculating pathways:  61%|██████    | 357/583 [30:07<15:23,  4.08s/it]

Cytoskeleton-Dependent Intracellular Transport (GO:0030705): pvalue calculation completed
Cytoskeleton-Dependent Intracellular Transport (GO:0030705): Calculation completed
Defense Response to Bacterium (GO:0042742): Calculation started
Defense Response to Bacterium (GO:0042742): scoring computed

Calculating pathways:  61%|██████▏   | 358/583 [30:13<16:29,  4.40s/it]

Defense Response to Bacterium (GO:0042742): pvalue calculation completed
Defense Response to Bacterium (GO:0042742): Calculation completed
Dendritic Spine Organization (GO:0097061): Calculation started
Dendritic Spine Organization (GO:0097061): scoring computed

Calculating pathways:  62%|██████▏   | 359/583 [30:16<15:26,  4.14s/it]

Dendritic Spine Organization (GO:0097061): pvalue calculation completed
Dendritic Spine Organization (GO:0097061): Calculation completed
Detection of Bacterium (GO:0016045): Calculation started
Detection of Bacterium (GO:0016045): scoring computed

Calculating pathways:  62%|██████▏   | 360/583 [30:20<14:38,  3.94s/it]

Detection of Bacterium (GO:0016045): pvalue calculation completed
Detection of Bacterium (GO:0016045): Calculation completed
Enzyme-Linked Receptor Protein Signaling Pathway (GO:0007167): Calculation started
Enzyme-Linked Receptor Protein Signaling Pathway (GO:0007167): scoring computed

Calculating pathways:  62%|██████▏   | 361/583 [30:24<15:22,  4.16s/it]

Enzyme-Linked Receptor Protein Signaling Pathway (GO:0007167): pvalue calculation completed
Enzyme-Linked Receptor Protein Signaling Pathway (GO:0007167): Calculation completed
Ephrin Receptor Signaling Pathway (GO:0048013): Calculation started
Ephrin Receptor Signaling Pathway (GO:0048013): scoring computed

Calculating pathways:  62%|██████▏   | 362/583 [30:28<14:55,  4.05s/it]

Ephrin Receptor Signaling Pathway (GO:0048013): pvalue calculation completed
Ephrin Receptor Signaling Pathway (GO:0048013): Calculation completed
Epidermal Growth Factor Receptor Signaling Pathway (GO:0007173): Calculation started
Epidermal Growth Factor Receptor Signaling Pathway (GO:0007173): scoring computed

Calculating pathways:  62%|██████▏   | 363/583 [30:32<14:33,  3.97s/it]

Epidermal Growth Factor Receptor Signaling Pathway (GO:0007173): pvalue calculation completed
Epidermal Growth Factor Receptor Signaling Pathway (GO:0007173): Calculation completed
Epithelial Structure Maintenance (GO:0010669): Calculation started
Epithelial Structure Maintenance (GO:0010669): scoring computed

Calculating pathways:  62%|██████▏   | 364/583 [30:35<14:03,  3.85s/it]

Epithelial Structure Maintenance (GO:0010669): pvalue calculation completed
Epithelial Structure Maintenance (GO:0010669): Calculation completed
Fatty Acid Metabolic Process (GO:0006631): Calculation started
Fatty Acid Metabolic Process (GO:0006631): scoring computed

Calculating pathways:  63%|██████▎   | 365/583 [30:40<15:02,  4.14s/it]

Fatty Acid Metabolic Process (GO:0006631): pvalue calculation completed
Fatty Acid Metabolic Process (GO:0006631): Calculation completed
Female Meiotic Nuclear Division (GO:0007143): Calculation started
Female Meiotic Nuclear Division (GO:0007143): scoring computed

Calculating pathways:  63%|██████▎   | 366/583 [30:44<14:14,  3.94s/it]

Female Meiotic Nuclear Division (GO:0007143): pvalue calculation completed
Female Meiotic Nuclear Division (GO:0007143): Calculation completed
Ganglion Development (GO:0061548): Calculation started
Ganglion Development (GO:0061548): scoring computed

Calculating pathways:  63%|██████▎   | 367/583 [30:47<13:32,  3.76s/it]

Ganglion Development (GO:0061548): pvalue calculation completed
Ganglion Development (GO:0061548): Calculation completed
Generation of Neurons (GO:0048699): Calculation started
Generation of Neurons (GO:0048699): scoring computed

Calculating pathways:  63%|██████▎   | 368/583 [30:52<14:59,  4.18s/it]

Generation of Neurons (GO:0048699): pvalue calculation completed
Generation of Neurons (GO:0048699): Calculation completed
Glutamate Receptor Signaling Pathway (GO:0007215): Calculation started
Glutamate Receptor Signaling Pathway (GO:0007215): scoring computed

Calculating pathways:  63%|██████▎   | 369/583 [30:56<14:19,  4.02s/it]

Glutamate Receptor Signaling Pathway (GO:0007215): pvalue calculation completed
Glutamate Receptor Signaling Pathway (GO:0007215): Calculation completed
Heart Process (GO:0003015): Calculation started
Heart Process (GO:0003015): scoring computed

Calculating pathways:  63%|██████▎   | 370/583 [30:59<13:35,  3.83s/it]

Heart Process (GO:0003015): pvalue calculation completed
Heart Process (GO:0003015): Calculation completed
Host-Mediated Regulation of Intestinal Microbiota Composition (GO:0048874): Calculation started
Host-Mediated Regulation of Intestinal Microbiota Composition (GO:0048874): scoring computed

Calculating pathways:  64%|██████▎   | 371/583 [31:02<12:59,  3.68s/it]

Host-Mediated Regulation of Intestinal Microbiota Composition (GO:0048874): pvalue calculation completed
Host-Mediated Regulation of Intestinal Microbiota Composition (GO:0048874): Calculation completed
Icosanoid Metabolic Process (GO:0006690): Calculation started
Icosanoid Metabolic Process (GO:0006690): scoring computed

Calculating pathways:  64%|██████▍   | 372/583 [31:06<13:04,  3.72s/it]

Icosanoid Metabolic Process (GO:0006690): pvalue calculation completed
Icosanoid Metabolic Process (GO:0006690): Calculation completed
Icosanoid Transport (GO:0071715): Calculation started
Icosanoid Transport (GO:0071715): scoring computed

Calculating pathways:  64%|██████▍   | 373/583 [31:10<12:40,  3.62s/it]

Icosanoid Transport (GO:0071715): pvalue calculation completed
Icosanoid Transport (GO:0071715): Calculation completed
Innate Immune Response Activating Cell Surface Receptor Signaling Pathway (GO:0002220): Calculation started
Innate Immune Response Activating Cell Surface Receptor Signaling Pathway (GO:0002220): scoring computed

Calculating pathways:  64%|██████▍   | 374/583 [31:13<12:43,  3.65s/it]

Innate Immune Response Activating Cell Surface Receptor Signaling Pathway (GO:0002220): pvalue calculation completed
Innate Immune Response Activating Cell Surface Receptor Signaling Pathway (GO:0002220): Calculation completed
Innate Immune Response-Activating Signaling Pathway (GO:0002758): Calculation started
Innate Immune Response-Activating Signaling Pathway (GO:0002758): scoring computed

Calculating pathways:  64%|██████▍   | 375/583 [31:17<12:33,  3.62s/it]

Innate Immune Response-Activating Signaling Pathway (GO:0002758): pvalue calculation completed
Innate Immune Response-Activating Signaling Pathway (GO:0002758): Calculation completed
Intracellular Receptor Signaling Pathway (GO:0030522): Calculation started
Intracellular Receptor Signaling Pathway (GO:0030522): scoring computed

Calculating pathways:  64%|██████▍   | 376/583 [31:21<12:32,  3.64s/it]

Intracellular Receptor Signaling Pathway (GO:0030522): pvalue calculation completed
Intracellular Receptor Signaling Pathway (GO:0030522): Calculation completed
Intracellular Signaling Cassette (GO:0141124): Calculation started
Intracellular Signaling Cassette (GO:0141124): scoring computed

Calculating pathways:  65%|██████▍   | 377/583 [31:28<16:06,  4.69s/it]

Intracellular Signaling Cassette (GO:0141124): pvalue calculation completed
Intracellular Signaling Cassette (GO:0141124): Calculation completed
Learning (GO:0007612): Calculation started
Learning (GO:0007612): scoring computed

Calculating pathways:  65%|██████▍   | 378/583 [31:32<15:07,  4.43s/it]

Learning (GO:0007612): pvalue calculation completed
Learning (GO:0007612): Calculation completed
Leukotriene Metabolic Process (GO:0006691): Calculation started
Leukotriene Metabolic Process (GO:0006691): scoring computed

Calculating pathways:  65%|██████▌   | 379/583 [31:35<14:10,  4.17s/it]

Leukotriene Metabolic Process (GO:0006691): pvalue calculation completed
Leukotriene Metabolic Process (GO:0006691): Calculation completed
Leukotriene Transport (GO:0071716): Calculation started
Leukotriene Transport (GO:0071716): scoring computed

Calculating pathways:  65%|██████▌   | 380/583 [31:39<13:16,  3.92s/it]

Leukotriene Transport (GO:0071716): pvalue calculation completed
Leukotriene Transport (GO:0071716): Calculation completed
Lipid Metabolic Process (GO:0006629): Calculation started
Lipid Metabolic Process (GO:0006629): scoring computed

Calculating pathways:  65%|██████▌   | 381/583 [31:45<15:19,  4.55s/it]

Lipid Metabolic Process (GO:0006629): pvalue calculation completed
Lipid Metabolic Process (GO:0006629): Calculation completed
Lipid Translocation (GO:0034204): Calculation started
Lipid Translocation (GO:0034204): scoring computed

Calculating pathways:  66%|██████▌   | 382/583 [31:48<14:13,  4.25s/it]

Lipid Translocation (GO:0034204): pvalue calculation completed
Lipid Translocation (GO:0034204): Calculation completed
Lipid Transport (GO:0006869): Calculation started
Lipid Transport (GO:0006869): scoring computed

Calculating pathways:  66%|██████▌   | 383/583 [31:52<14:14,  4.27s/it]

Lipid Transport (GO:0006869): pvalue calculation completed
Lipid Transport (GO:0006869): Calculation completed
Maintenance of Gastrointestinal Epithelium (GO:0030277): Calculation started
Maintenance of Gastrointestinal Epithelium (GO:0030277): scoring computed

Calculating pathways:  66%|██████▌   | 384/583 [31:56<13:25,  4.05s/it]

Maintenance of Gastrointestinal Epithelium (GO:0030277): pvalue calculation completed
Maintenance of Gastrointestinal Epithelium (GO:0030277): Calculation completed
Meiotic Spindle Assembly (GO:0090306): Calculation started
Meiotic Spindle Assembly (GO:0090306): scoring computed

Calculating pathways:  66%|██████▌   | 385/583 [31:59<12:42,  3.85s/it]

Meiotic Spindle Assembly (GO:0090306): pvalue calculation completed
Meiotic Spindle Assembly (GO:0090306): Calculation completed
Metal Ion Transport (GO:0030001): Calculation started
Metal Ion Transport (GO:0030001): scoring computed

Calculating pathways:  66%|██████▌   | 386/583 [32:05<13:59,  4.26s/it]

Metal Ion Transport (GO:0030001): pvalue calculation completed
Metal Ion Transport (GO:0030001): Calculation completed
Monocarboxylic Acid Metabolic Process (GO:0032787): Calculation started
Monocarboxylic Acid Metabolic Process (GO:0032787): scoring computed

Calculating pathways:  66%|██████▋   | 387/583 [32:09<14:15,  4.37s/it]

Monocarboxylic Acid Metabolic Process (GO:0032787): pvalue calculation completed
Monocarboxylic Acid Metabolic Process (GO:0032787): Calculation completed
Muscle Contraction (GO:0006936): Calculation started
Muscle Contraction (GO:0006936): scoring computed

Calculating pathways:  67%|██████▋   | 388/583 [32:14<14:22,  4.42s/it]

Muscle Contraction (GO:0006936): pvalue calculation completed
Muscle Contraction (GO:0006936): Calculation completed
Natural Killer Cell Activation (GO:0030101): Calculation started
Natural Killer Cell Activation (GO:0030101): scoring computed

Calculating pathways:  67%|██████▋   | 389/583 [32:17<13:29,  4.17s/it]

Natural Killer Cell Activation (GO:0030101): pvalue calculation completed
Natural Killer Cell Activation (GO:0030101): Calculation completed
Natural Killer Cell Mediated Cytotoxicity (GO:0042267): Calculation started
Natural Killer Cell Mediated Cytotoxicity (GO:0042267): scoring computed

Calculating pathways:  67%|██████▋   | 390/583 [32:21<12:49,  3.99s/it]

Natural Killer Cell Mediated Cytotoxicity (GO:0042267): pvalue calculation completed
Natural Killer Cell Mediated Cytotoxicity (GO:0042267): Calculation completed
Natural Killer Cell Mediated Immunity (GO:0002228): Calculation started
Natural Killer Cell Mediated Immunity (GO:0002228): scoring computed

Calculating pathways:  67%|██████▋   | 391/583 [32:24<12:22,  3.87s/it]

Natural Killer Cell Mediated Immunity (GO:0002228): pvalue calculation completed
Natural Killer Cell Mediated Immunity (GO:0002228): Calculation completed
Negative Regulation of DNA-templated Transcription (GO:0045892): Calculation started
Negative Regulation of DNA-templated Transcription (GO:0045892): scoring computed

Calculating pathways:  67%|██████▋   | 392/583 [32:38<21:12,  6.66s/it]

Negative Regulation of DNA-templated Transcription (GO:0045892): pvalue calculation completed
Negative Regulation of DNA-templated Transcription (GO:0045892): Calculation completed
Negative Regulation of RNA Biosynthetic Process (GO:1902679): Calculation started
Negative Regulation of RNA Biosynthetic Process (GO:1902679): scoring computed

Calculating pathways:  67%|██████▋   | 393/583 [32:46<22:27,  7.09s/it]

Negative Regulation of RNA Biosynthetic Process (GO:1902679): pvalue calculation completed
Negative Regulation of RNA Biosynthetic Process (GO:1902679): Calculation completed
Negative Regulation of Apoptotic Process (GO:0043066): Calculation started
Negative Regulation of Apoptotic Process (GO:0043066): scoring computed

Calculating pathways:  68%|██████▊   | 394/583 [32:54<23:18,  7.40s/it]

Negative Regulation of Apoptotic Process (GO:0043066): pvalue calculation completed
Negative Regulation of Apoptotic Process (GO:0043066): Calculation completed
Negative Regulation of Cell Projection Organization (GO:0031345): Calculation started
Negative Regulation of Cell Projection Organization (GO:0031345): scoring computed

Calculating pathways:  68%|██████▊   | 395/583 [32:58<19:47,  6.32s/it]

Negative Regulation of Cell Projection Organization (GO:0031345): pvalue calculation completed
Negative Regulation of Cell Projection Organization (GO:0031345): Calculation completed
Negative Regulation of Cellular Component Organization (GO:0051129): Calculation started
Negative Regulation of Cellular Component Organization (GO:0051129): scoring computed

Calculating pathways:  68%|██████▊   | 396/583 [33:02<17:40,  5.67s/it]

Negative Regulation of Cellular Component Organization (GO:0051129): pvalue calculation completed
Negative Regulation of Cellular Component Organization (GO:0051129): Calculation completed
Negative Regulation of Gene Expression (GO:0010629): Calculation started
Negative Regulation of Gene Expression (GO:0010629): scoring computed

Calculating pathways:  68%|██████▊   | 397/583 [33:09<18:56,  6.11s/it]

Negative Regulation of Gene Expression (GO:0010629): pvalue calculation completed
Negative Regulation of Gene Expression (GO:0010629): Calculation completed
Negative Regulation of Immune Response (GO:0050777): Calculation started
Negative Regulation of Immune Response (GO:0050777): scoring computed

Calculating pathways:  68%|██████▊   | 398/583 [33:13<16:49,  5.46s/it]

Negative Regulation of Immune Response (GO:0050777): pvalue calculation completed
Negative Regulation of Immune Response (GO:0050777): Calculation completed
Negative Regulation of Inflammatory Response (GO:0050728): Calculation started
Negative Regulation of Inflammatory Response (GO:0050728): scoring computed

Calculating pathways:  68%|██████▊   | 399/583 [33:17<15:49,  5.16s/it]

Negative Regulation of Inflammatory Response (GO:0050728): pvalue calculation completed
Negative Regulation of Inflammatory Response (GO:0050728): Calculation completed
Negative Regulation of Inflammatory Response to Antigenic Stimulus (GO:0002862): Calculation started
Negative Regulation of Inflammatory Response to Antigenic Stimulus (GO:0002862): scoring computed

Calculating pathways:  69%|██████▊   | 400/583 [33:21<14:13,  4.66s/it]

Negative Regulation of Inflammatory Response to Antigenic Stimulus (GO:0002862): pvalue calculation completed
Negative Regulation of Inflammatory Response to Antigenic Stimulus (GO:0002862): Calculation completed
Negative Regulation of Intrinsic Apoptotic Signaling Pathway (GO:2001243): Calculation started
Negative Regulation of Intrinsic Apoptotic Signaling Pathway (GO:2001243): scoring computed

Calculating pathways:  69%|██████▉   | 401/583 [33:25<13:32,  4.46s/it]

Negative Regulation of Intrinsic Apoptotic Signaling Pathway (GO:2001243): pvalue calculation completed
Negative Regulation of Intrinsic Apoptotic Signaling Pathway (GO:2001243): Calculation completed
Negative Regulation of Leukocyte Apoptotic Process (GO:2000107): Calculation started
Negative Regulation of Leukocyte Apoptotic Process (GO:2000107): scoring computed

Calculating pathways:  69%|██████▉   | 402/583 [33:28<12:33,  4.16s/it]

Negative Regulation of Leukocyte Apoptotic Process (GO:2000107): pvalue calculation completed
Negative Regulation of Leukocyte Apoptotic Process (GO:2000107): Calculation completed
Negative Regulation of Macromolecule Biosynthetic Process (GO:0010558): Calculation started
Negative Regulation of Macromolecule Biosynthetic Process (GO:0010558): scoring computed

Calculating pathways:  69%|██████▉   | 403/583 [33:34<13:49,  4.61s/it]

Negative Regulation of Macromolecule Biosynthetic Process (GO:0010558): pvalue calculation completed
Negative Regulation of Macromolecule Biosynthetic Process (GO:0010558): Calculation completed
Negative Regulation of Microtubule Polymerization (GO:0031115): Calculation started
Negative Regulation of Microtubule Polymerization (GO:0031115): scoring computed

Calculating pathways:  69%|██████▉   | 404/583 [33:37<12:39,  4.24s/it]

Negative Regulation of Microtubule Polymerization (GO:0031115): pvalue calculation completed
Negative Regulation of Microtubule Polymerization (GO:0031115): Calculation completed
Negative Regulation of Microtubule Polymerization or Depolymerization (GO:0031111): Calculation started
Negative Regulation of Microtubule Polymerization or Depolymerization (GO:0031111): scoring computed

Calculating pathways:  69%|██████▉   | 405/583 [33:41<12:07,  4.09s/it]

Negative Regulation of Microtubule Polymerization or Depolymerization (GO:0031111): pvalue calculation completed
Negative Regulation of Microtubule Polymerization or Depolymerization (GO:0031111): Calculation completed
Negative Regulation of Myeloid Cell Apoptotic Process (GO:0033033): Calculation started
Negative Regulation of Myeloid Cell Apoptotic Process (GO:0033033): scoring computed

Calculating pathways:  70%|██████▉   | 406/583 [33:44<11:23,  3.86s/it]

Negative Regulation of Myeloid Cell Apoptotic Process (GO:0033033): pvalue calculation completed
Negative Regulation of Myeloid Cell Apoptotic Process (GO:0033033): Calculation completed
Negative Regulation of Oxidative Stress-Induced Intrinsic Apoptotic Signaling Pathway (GO:1902176): Calculation started
Negative Regulation of Oxidative Stress-Induced Intrinsic Apoptotic Signaling Pathway (GO:1902176): scoring computed

Calculating pathways:  70%|██████▉   | 407/583 [33:48<11:09,  3.80s/it]

Negative Regulation of Oxidative Stress-Induced Intrinsic Apoptotic Signaling Pathway (GO:1902176): pvalue calculation completed
Negative Regulation of Oxidative Stress-Induced Intrinsic Apoptotic Signaling Pathway (GO:1902176): Calculation completed
Negative Regulation of Programmed Cell Death (GO:0043069): Calculation started
Negative Regulation of Programmed Cell Death (GO:0043069): scoring computed

Calculating pathways:  70%|██████▉   | 408/583 [33:56<14:18,  4.90s/it]

Negative Regulation of Programmed Cell Death (GO:0043069): pvalue calculation completed
Negative Regulation of Programmed Cell Death (GO:0043069): Calculation completed
Negative Regulation of Protein Polymerization (GO:0032272): Calculation started
Negative Regulation of Protein Polymerization (GO:0032272): scoring computed

Calculating pathways:  70%|███████   | 409/583 [33:59<13:25,  4.63s/it]

Negative Regulation of Protein Polymerization (GO:0032272): pvalue calculation completed
Negative Regulation of Protein Polymerization (GO:0032272): Calculation completed
Negative Regulation of Protein-Containing Complex Assembly (GO:0031333): Calculation started
Negative Regulation of Protein-Containing Complex Assembly (GO:0031333): scoring computed

Calculating pathways:  70%|███████   | 410/583 [34:04<12:49,  4.45s/it]

Negative Regulation of Protein-Containing Complex Assembly (GO:0031333): pvalue calculation completed
Negative Regulation of Protein-Containing Complex Assembly (GO:0031333): Calculation completed
Negative Regulation of Reactive Oxygen Species Biosynthetic Process (GO:1903427): Calculation started
Negative Regulation of Reactive Oxygen Species Biosynthetic Process (GO:1903427): scoring computed

Calculating pathways:  70%|███████   | 411/583 [34:07<11:48,  4.12s/it]

Negative Regulation of Reactive Oxygen Species Biosynthetic Process (GO:1903427): pvalue calculation completed
Negative Regulation of Reactive Oxygen Species Biosynthetic Process (GO:1903427): Calculation completed
Negative Regulation of Supramolecular Fiber Organization (GO:1902904): Calculation started
Negative Regulation of Supramolecular Fiber Organization (GO:1902904): scoring computed

Calculating pathways:  71%|███████   | 412/583 [34:11<11:42,  4.11s/it]

Negative Regulation of Supramolecular Fiber Organization (GO:1902904): pvalue calculation completed
Negative Regulation of Supramolecular Fiber Organization (GO:1902904): Calculation completed
Negative Regulation of Transcription by RNA Polymerase II (GO:0000122): Calculation started
Negative Regulation of Transcription by RNA Polymerase II (GO:0000122): scoring computed

Calculating pathways:  71%|███████   | 413/583 [34:21<16:57,  5.99s/it]

Negative Regulation of Transcription by RNA Polymerase II (GO:0000122): pvalue calculation completed
Negative Regulation of Transcription by RNA Polymerase II (GO:0000122): Calculation completed
Nervous System Development (GO:0007399): Calculation started
Nervous System Development (GO:0007399): scoring computed

Calculating pathways:  71%|███████   | 414/583 [34:29<18:29,  6.56s/it]

Nervous System Development (GO:0007399): pvalue calculation completed
Nervous System Development (GO:0007399): Calculation completed
Neuroepithelial Cell Differentiation (GO:0060563): Calculation started
Neuroepithelial Cell Differentiation (GO:0060563): scoring computed

Calculating pathways:  71%|███████   | 415/583 [34:33<15:40,  5.60s/it]

Neuroepithelial Cell Differentiation (GO:0060563): pvalue calculation completed
Neuroepithelial Cell Differentiation (GO:0060563): Calculation completed
Neuron Differentiation (GO:0030182): Calculation started
Neuron Differentiation (GO:0030182): scoring computed

Calculating pathways:  71%|███████▏  | 416/583 [34:38<15:09,  5.45s/it]

Neuron Differentiation (GO:0030182): pvalue calculation completed
Neuron Differentiation (GO:0030182): Calculation completed
Neuron Migration (GO:0001764): Calculation started
Neuron Migration (GO:0001764): scoring computed

Calculating pathways:  72%|███████▏  | 417/583 [34:42<13:44,  4.96s/it]

Neuron Migration (GO:0001764): pvalue calculation completed
Neuron Migration (GO:0001764): Calculation completed
Neuron Projection Guidance (GO:0097485): Calculation started
Neuron Projection Guidance (GO:0097485): scoring computed

Calculating pathways:  72%|███████▏  | 418/583 [34:46<13:27,  4.89s/it]

Neuron Projection Guidance (GO:0097485): pvalue calculation completed
Neuron Projection Guidance (GO:0097485): Calculation completed
Neuropeptide Signaling Pathway (GO:0007218): Calculation started
Neuropeptide Signaling Pathway (GO:0007218): scoring computed

Calculating pathways:  72%|███████▏  | 419/583 [34:50<12:34,  4.60s/it]

Neuropeptide Signaling Pathway (GO:0007218): pvalue calculation completed
Neuropeptide Signaling Pathway (GO:0007218): Calculation completed
Nucleotide-Binding Domain, Leucine Rich Repeat Containing Receptor Signaling Pathway (GO:0035872): Calculation started
Nucleotide-Binding Domain, Leucine Rich Repeat Containing Receptor Signaling Pathway (GO:0035872): scoring computed

Calculating pathways:  72%|███████▏  | 420/583 [34:54<11:36,  4.27s/it]

Nucleotide-Binding Domain, Leucine Rich Repeat Containing Receptor Signaling Pathway (GO:0035872): pvalue calculation completed
Nucleotide-Binding Domain, Leucine Rich Repeat Containing Receptor Signaling Pathway (GO:0035872): Calculation completed
Nucleotide-Binding Oligomerization Domain Containing 2 Signaling Pathway (GO:0070431): Calculation started
Nucleotide-Binding Oligomerization Domain Containing 2 Signaling Pathway (GO:0070431): scoring computed

Calculating pathways:  72%|███████▏  | 421/583 [34:57<10:55,  4.05s/it]

Nucleotide-Binding Oligomerization Domain Containing 2 Signaling Pathway (GO:0070431): pvalue calculation completed
Nucleotide-Binding Oligomerization Domain Containing 2 Signaling Pathway (GO:0070431): Calculation completed
Pattern Recognition Receptor Signaling Pathway (GO:0002221): Calculation started
Pattern Recognition Receptor Signaling Pathway (GO:0002221): scoring computed

Calculating pathways:  72%|███████▏  | 422/583 [35:01<10:49,  4.04s/it]

Pattern Recognition Receptor Signaling Pathway (GO:0002221): pvalue calculation completed
Pattern Recognition Receptor Signaling Pathway (GO:0002221): Calculation completed
Peptidyl-Tyrosine Modification (GO:0018212): Calculation started
Peptidyl-Tyrosine Modification (GO:0018212): scoring computed

Calculating pathways:  73%|███████▎  | 423/583 [35:05<10:31,  3.95s/it]

Peptidyl-Tyrosine Modification (GO:0018212): pvalue calculation completed
Peptidyl-Tyrosine Modification (GO:0018212): Calculation completed
Peptidyl-Tyrosine Phosphorylation (GO:0018108): Calculation started
Peptidyl-Tyrosine Phosphorylation (GO:0018108): scoring computed

Calculating pathways:  73%|███████▎  | 424/583 [35:09<10:27,  3.95s/it]

Peptidyl-Tyrosine Phosphorylation (GO:0018108): pvalue calculation completed
Peptidyl-Tyrosine Phosphorylation (GO:0018108): Calculation completed
Phagocytosis (GO:0006909): Calculation started
Phagocytosis (GO:0006909): scoring computed

Calculating pathways:  73%|███████▎  | 425/583 [35:13<10:26,  3.97s/it]

Phagocytosis (GO:0006909): pvalue calculation completed
Phagocytosis (GO:0006909): Calculation completed
Phosphatidylinositol 3-Kinase/Protein Kinase B Signal Transduction (GO:0043491): Calculation started
Phosphatidylinositol 3-Kinase/Protein Kinase B Signal Transduction (GO:0043491): scoring computed

Calculating pathways:  73%|███████▎  | 426/583 [35:17<10:12,  3.90s/it]

Phosphatidylinositol 3-Kinase/Protein Kinase B Signal Transduction (GO:0043491): pvalue calculation completed
Phosphatidylinositol 3-Kinase/Protein Kinase B Signal Transduction (GO:0043491): Calculation completed
Phospholipase C-activating G Protein-Coupled Receptor Signaling Pathway (GO:0007200): Calculation started
Phospholipase C-activating G Protein-Coupled Receptor Signaling Pathway (GO:0007200): scoring computed

Calculating pathways:  73%|███████▎  | 427/583 [35:21<10:22,  3.99s/it]

Phospholipase C-activating G Protein-Coupled Receptor Signaling Pathway (GO:0007200): pvalue calculation completed
Phospholipase C-activating G Protein-Coupled Receptor Signaling Pathway (GO:0007200): Calculation completed
Phospholipid Homeostasis (GO:0055091): Calculation started
Phospholipid Homeostasis (GO:0055091): scoring computed

Calculating pathways:  73%|███████▎  | 428/583 [35:24<09:49,  3.81s/it]

Phospholipid Homeostasis (GO:0055091): pvalue calculation completed
Phospholipid Homeostasis (GO:0055091): Calculation completed
Phospholipid Translocation (GO:0045332): Calculation started
Phospholipid Translocation (GO:0045332): scoring computed

Calculating pathways:  74%|███████▎  | 429/583 [35:28<09:50,  3.83s/it]

Phospholipid Translocation (GO:0045332): pvalue calculation completed
Phospholipid Translocation (GO:0045332): Calculation completed
Phospholipid Transport (GO:0015914): Calculation started
Phospholipid Transport (GO:0015914): scoring computed

Calculating pathways:  74%|███████▍  | 430/583 [35:32<09:47,  3.84s/it]

Phospholipid Transport (GO:0015914): pvalue calculation completed
Phospholipid Transport (GO:0015914): Calculation completed
Phosphorylation (GO:0016310): Calculation started
Phosphorylation (GO:0016310): scoring computed

Calculating pathways:  74%|███████▍  | 431/583 [35:38<11:43,  4.63s/it]

Phosphorylation (GO:0016310): pvalue calculation completed
Phosphorylation (GO:0016310): Calculation completed
Positive Regulation of B Cell Activation (GO:0050871): Calculation started
Positive Regulation of B Cell Activation (GO:0050871): scoring computed

Calculating pathways:  74%|███████▍  | 432/583 [35:42<11:01,  4.38s/it]

Positive Regulation of B Cell Activation (GO:0050871): pvalue calculation completed
Positive Regulation of B Cell Activation (GO:0050871): Calculation completed
Positive Regulation of CREB Transcription Factor Activity (GO:0032793): Calculation started
Positive Regulation of CREB Transcription Factor Activity (GO:0032793): scoring computed

Calculating pathways:  74%|███████▍  | 433/583 [35:46<10:22,  4.15s/it]

Positive Regulation of CREB Transcription Factor Activity (GO:0032793): pvalue calculation completed
Positive Regulation of CREB Transcription Factor Activity (GO:0032793): Calculation completed
Positive Regulation of DNA-binding Transcription Factor Activity (GO:0051091): Calculation started
Positive Regulation of DNA-binding Transcription Factor Activity (GO:0051091): scoring computed

Calculating pathways:  74%|███████▍  | 434/583 [35:51<10:59,  4.43s/it]

Positive Regulation of DNA-binding Transcription Factor Activity (GO:0051091): pvalue calculation completed
Positive Regulation of DNA-binding Transcription Factor Activity (GO:0051091): Calculation completed
Positive Regulation of DNA-templated Transcription (GO:0045893): Calculation started
Positive Regulation of DNA-templated Transcription (GO:0045893): scoring computed

Calculating pathways:  75%|███████▍  | 435/583 [36:06<19:04,  7.73s/it]

Positive Regulation of DNA-templated Transcription (GO:0045893): pvalue calculation completed
Positive Regulation of DNA-templated Transcription (GO:0045893): Calculation completed
Positive Regulation of ERK1 and ERK2 Cascade (GO:0070374): Calculation started
Positive Regulation of ERK1 and ERK2 Cascade (GO:0070374): scoring computed

Calculating pathways:  75%|███████▍  | 436/583 [36:11<16:59,  6.94s/it]

Positive Regulation of ERK1 and ERK2 Cascade (GO:0070374): pvalue calculation completed
Positive Regulation of ERK1 and ERK2 Cascade (GO:0070374): Calculation completed
Positive Regulation of JNK Cascade (GO:0046330): Calculation started
Positive Regulation of JNK Cascade (GO:0046330): scoring computed

Calculating pathways:  75%|███████▍  | 437/583 [36:16<14:58,  6.15s/it]

Positive Regulation of JNK Cascade (GO:0046330): pvalue calculation completed
Positive Regulation of JNK Cascade (GO:0046330): Calculation completed
Positive Regulation of MAP Kinase Activity (GO:0043406): Calculation started
Positive Regulation of MAP Kinase Activity (GO:0043406): scoring computed

Calculating pathways:  75%|███████▌  | 438/583 [36:20<13:23,  5.54s/it]

Positive Regulation of MAP Kinase Activity (GO:0043406): pvalue calculation completed
Positive Regulation of MAP Kinase Activity (GO:0043406): Calculation completed
Positive Regulation of MAPK Cascade (GO:0043410): Calculation started
Positive Regulation of MAPK Cascade (GO:0043410): scoring computed

Calculating pathways:  75%|███████▌  | 439/583 [36:27<14:12,  5.92s/it]

Positive Regulation of MAPK Cascade (GO:0043410): pvalue calculation completed
Positive Regulation of MAPK Cascade (GO:0043410): Calculation completed
Positive Regulation of NF-kappaB Transcription Factor Activity (GO:0051092): Calculation started
Positive Regulation of NF-kappaB Transcription Factor Activity (GO:0051092): scoring computed

Calculating pathways:  75%|███████▌  | 440/583 [36:31<13:13,  5.55s/it]

Positive Regulation of NF-kappaB Transcription Factor Activity (GO:0051092): pvalue calculation completed
Positive Regulation of NF-kappaB Transcription Factor Activity (GO:0051092): Calculation completed
Positive Regulation of Notch Signaling Pathway (GO:0045747): Calculation started
Positive Regulation of Notch Signaling Pathway (GO:0045747): scoring computed

Calculating pathways:  76%|███████▌  | 441/583 [36:35<11:49,  4.99s/it]

Positive Regulation of Notch Signaling Pathway (GO:0045747): pvalue calculation completed
Positive Regulation of Notch Signaling Pathway (GO:0045747): Calculation completed
Positive Regulation of RNA Biosynthetic Process (GO:1902680): Calculation started
Positive Regulation of RNA Biosynthetic Process (GO:1902680): scoring computed

Calculating pathways:  76%|███████▌  | 442/583 [36:44<14:35,  6.21s/it]

Positive Regulation of RNA Biosynthetic Process (GO:1902680): pvalue calculation completed
Positive Regulation of RNA Biosynthetic Process (GO:1902680): Calculation completed
Positive Regulation of Rho Protein Signal Transduction (GO:0035025): Calculation started
Positive Regulation of Rho Protein Signal Transduction (GO:0035025): scoring computed

Calculating pathways:  76%|███████▌  | 443/583 [36:48<12:39,  5.42s/it]

Positive Regulation of Rho Protein Signal Transduction (GO:0035025): pvalue calculation completed
Positive Regulation of Rho Protein Signal Transduction (GO:0035025): Calculation completed
Positive Regulation of T Cell Activation (GO:0050870): Calculation started
Positive Regulation of T Cell Activation (GO:0050870): scoring computed

Calculating pathways:  76%|███████▌  | 444/583 [36:52<11:58,  5.17s/it]

Positive Regulation of T Cell Activation (GO:0050870): pvalue calculation completed
Positive Regulation of T Cell Activation (GO:0050870): Calculation completed
Positive Regulation of Antigen Processing and Presentation (GO:0002579): Calculation started
Positive Regulation of Antigen Processing and Presentation (GO:0002579): scoring computed

Calculating pathways:  76%|███████▋  | 445/583 [36:56<10:36,  4.61s/it]

Positive Regulation of Antigen Processing and Presentation (GO:0002579): pvalue calculation completed
Positive Regulation of Antigen Processing and Presentation (GO:0002579): Calculation completed
Positive Regulation of Autophagy of Mitochondrion (GO:1903599): Calculation started
Positive Regulation of Autophagy of Mitochondrion (GO:1903599): scoring computed

Calculating pathways:  77%|███████▋  | 446/583 [36:59<09:48,  4.30s/it]

Positive Regulation of Autophagy of Mitochondrion (GO:1903599): pvalue calculation completed
Positive Regulation of Autophagy of Mitochondrion (GO:1903599): Calculation completed
Positive Regulation of Canonical NF-kappaB Signal Transduction (GO:0043123): Calculation started
Positive Regulation of Canonical NF-kappaB Signal Transduction (GO:0043123): scoring computed

Calculating pathways:  77%|███████▋  | 447/583 [37:05<10:34,  4.67s/it]

Positive Regulation of Canonical NF-kappaB Signal Transduction (GO:0043123): pvalue calculation completed
Positive Regulation of Canonical NF-kappaB Signal Transduction (GO:0043123): Calculation completed
Positive Regulation of Cell Adhesion (GO:0045785): Calculation started
Positive Regulation of Cell Adhesion (GO:0045785): scoring computed

Calculating pathways:  77%|███████▋  | 448/583 [37:09<10:13,  4.54s/it]

Positive Regulation of Cell Adhesion (GO:0045785): pvalue calculation completed
Positive Regulation of Cell Adhesion (GO:0045785): Calculation completed
Positive Regulation of Cell Growth (GO:0030307): Calculation started
Positive Regulation of Cell Growth (GO:0030307): scoring computed

Calculating pathways:  77%|███████▋  | 449/583 [37:13<09:59,  4.47s/it]

Positive Regulation of Cell Growth (GO:0030307): pvalue calculation completed
Positive Regulation of Cell Growth (GO:0030307): Calculation completed
Positive Regulation of Cell Population Proliferation (GO:0008284): Calculation started
Positive Regulation of Cell Population Proliferation (GO:0008284): scoring computed

Calculating pathways:  77%|███████▋  | 450/583 [37:21<12:18,  5.55s/it]

Positive Regulation of Cell Population Proliferation (GO:0008284): pvalue calculation completed
Positive Regulation of Cell Population Proliferation (GO:0008284): Calculation completed
Positive Regulation of Cellular Process (GO:0048522): Calculation started
Positive Regulation of Cellular Process (GO:0048522): scoring computed

Calculating pathways:  77%|███████▋  | 451/583 [37:31<14:46,  6.72s/it]

Positive Regulation of Cellular Process (GO:0048522): pvalue calculation completed
Positive Regulation of Cellular Process (GO:0048522): Calculation completed
Positive Regulation of Cilium Movement (GO:0003353): Calculation started
Positive Regulation of Cilium Movement (GO:0003353): scoring computed

Calculating pathways:  78%|███████▊  | 452/583 [37:34<12:28,  5.72s/it]

Positive Regulation of Cilium Movement (GO:0003353): pvalue calculation completed
Positive Regulation of Cilium Movement (GO:0003353): Calculation completed
Positive Regulation of Cilium-Dependent Cell Motility (GO:2000155): Calculation started
Positive Regulation of Cilium-Dependent Cell Motility (GO:2000155): scoring computed

Calculating pathways:  78%|███████▊  | 453/583 [37:37<10:50,  5.00s/it]

Positive Regulation of Cilium-Dependent Cell Motility (GO:2000155): pvalue calculation completed
Positive Regulation of Cilium-Dependent Cell Motility (GO:2000155): Calculation completed
Positive Regulation of Cytokine Production (GO:0001819): Calculation started
Positive Regulation of Cytokine Production (GO:0001819): scoring computed

Calculating pathways:  78%|███████▊  | 454/583 [37:44<11:36,  5.40s/it]

Positive Regulation of Cytokine Production (GO:0001819): pvalue calculation completed
Positive Regulation of Cytokine Production (GO:0001819): Calculation completed
Positive Regulation of Cytokine Production Involved in Immune Response (GO:0002720): Calculation started
Positive Regulation of Cytokine Production Involved in Immune Response (GO:0002720): scoring computed

Calculating pathways:  78%|███████▊  | 455/583 [37:47<10:23,  4.87s/it]

Positive Regulation of Cytokine Production Involved in Immune Response (GO:0002720): pvalue calculation completed
Positive Regulation of Cytokine Production Involved in Immune Response (GO:0002720): Calculation completed
Positive Regulation of Cytokine Production Involved in Inflammatory Response (GO:1900017): Calculation started
Positive Regulation of Cytokine Production Involved in Inflammatory Response (GO:1900017): scoring computed

Calculating pathways:  78%|███████▊  | 456/583 [37:51<09:22,  4.43s/it]

Positive Regulation of Cytokine Production Involved in Inflammatory Response (GO:1900017): pvalue calculation completed
Positive Regulation of Cytokine Production Involved in Inflammatory Response (GO:1900017): Calculation completed
Positive Regulation of Dendritic Cell Antigen Processing and Presentation (GO:0002606): Calculation started
Positive Regulation of Dendritic Cell Antigen Processing and Presentation (GO:0002606): scoring computed

Calculating pathways:  78%|███████▊  | 457/583 [37:54<08:37,  4.11s/it]

Positive Regulation of Dendritic Cell Antigen Processing and Presentation (GO:0002606): pvalue calculation completed
Positive Regulation of Dendritic Cell Antigen Processing and Presentation (GO:0002606): Calculation completed
Positive Regulation of Endocytosis (GO:0045807): Calculation started
Positive Regulation of Endocytosis (GO:0045807): scoring computed

Calculating pathways:  79%|███████▊  | 458/583 [37:58<08:35,  4.13s/it]

Positive Regulation of Endocytosis (GO:0045807): pvalue calculation completed
Positive Regulation of Endocytosis (GO:0045807): Calculation completed
Positive Regulation of Epithelial Cell Proliferation (GO:0050679): Calculation started
Positive Regulation of Epithelial Cell Proliferation (GO:0050679): scoring computed

Calculating pathways:  79%|███████▊  | 459/583 [38:03<08:45,  4.24s/it]

Positive Regulation of Epithelial Cell Proliferation (GO:0050679): pvalue calculation completed
Positive Regulation of Epithelial Cell Proliferation (GO:0050679): Calculation completed
Positive Regulation of Establishment of Protein Localization (GO:1904951): Calculation started
Positive Regulation of Establishment of Protein Localization (GO:1904951): scoring computed

Calculating pathways:  79%|███████▉  | 460/583 [38:07<08:18,  4.06s/it]

Positive Regulation of Establishment of Protein Localization (GO:1904951): pvalue calculation completed
Positive Regulation of Establishment of Protein Localization (GO:1904951): Calculation completed
Positive Regulation of Flagellated Sperm Motility (GO:1902093): Calculation started
Positive Regulation of Flagellated Sperm Motility (GO:1902093): scoring computed

Calculating pathways:  79%|███████▉  | 461/583 [38:10<07:47,  3.83s/it]

Positive Regulation of Flagellated Sperm Motility (GO:1902093): pvalue calculation completed
Positive Regulation of Flagellated Sperm Motility (GO:1902093): Calculation completed
Positive Regulation of Gene Expression (GO:0010628): Calculation started
Positive Regulation of Gene Expression (GO:0010628): scoring computed

Calculating pathways:  79%|███████▉  | 462/583 [38:18<10:08,  5.03s/it]

Positive Regulation of Gene Expression (GO:0010628): pvalue calculation completed
Positive Regulation of Gene Expression (GO:0010628): Calculation completed
Positive Regulation of Growth (GO:0045927): Calculation started
Positive Regulation of Growth (GO:0045927): scoring computed

Calculating pathways:  79%|███████▉  | 463/583 [38:22<09:29,  4.75s/it]

Positive Regulation of Growth (GO:0045927): pvalue calculation completed
Positive Regulation of Growth (GO:0045927): Calculation completed
Positive Regulation of Immune Response (GO:0050778): Calculation started
Positive Regulation of Immune Response (GO:0050778): scoring computed

Calculating pathways:  80%|███████▉  | 464/583 [38:26<09:12,  4.65s/it]

Positive Regulation of Immune Response (GO:0050778): pvalue calculation completed
Positive Regulation of Immune Response (GO:0050778): Calculation completed
Positive Regulation of Interleukin-1 Beta Production (GO:0032731): Calculation started
Positive Regulation of Interleukin-1 Beta Production (GO:0032731): scoring computed

Calculating pathways:  80%|███████▉  | 465/583 [38:30<08:44,  4.44s/it]

Positive Regulation of Interleukin-1 Beta Production (GO:0032731): pvalue calculation completed
Positive Regulation of Interleukin-1 Beta Production (GO:0032731): Calculation completed
Positive Regulation of Interleukin-1 Production (GO:0032732): Calculation started
Positive Regulation of Interleukin-1 Production (GO:0032732): scoring computed

Calculating pathways:  80%|███████▉  | 466/583 [38:34<08:20,  4.28s/it]

Positive Regulation of Interleukin-1 Production (GO:0032732): pvalue calculation completed
Positive Regulation of Interleukin-1 Production (GO:0032732): Calculation completed
Positive Regulation of Interleukin-10 Production (GO:0032733): Calculation started
Positive Regulation of Interleukin-10 Production (GO:0032733): scoring computed

Calculating pathways:  80%|████████  | 467/583 [38:38<07:52,  4.07s/it]

Positive Regulation of Interleukin-10 Production (GO:0032733): pvalue calculation completed
Positive Regulation of Interleukin-10 Production (GO:0032733): Calculation completed
Positive Regulation of Interleukin-17 Production (GO:0032740): Calculation started
Positive Regulation of Interleukin-17 Production (GO:0032740): scoring computed

Calculating pathways:  80%|████████  | 468/583 [38:41<07:29,  3.91s/it]

Positive Regulation of Interleukin-17 Production (GO:0032740): pvalue calculation completed
Positive Regulation of Interleukin-17 Production (GO:0032740): Calculation completed
Positive Regulation of Interleukin-6 Production (GO:0032755): Calculation started
Positive Regulation of Interleukin-6 Production (GO:0032755): scoring computed

Calculating pathways:  80%|████████  | 469/583 [38:45<07:27,  3.93s/it]

Positive Regulation of Interleukin-6 Production (GO:0032755): pvalue calculation completed
Positive Regulation of Interleukin-6 Production (GO:0032755): Calculation completed
Positive Regulation of Interleukin-8 Production (GO:0032757): Calculation started
Positive Regulation of Interleukin-8 Production (GO:0032757): scoring computed

Calculating pathways:  81%|████████  | 470/583 [38:49<07:27,  3.96s/it]

Positive Regulation of Interleukin-8 Production (GO:0032757): pvalue calculation completed
Positive Regulation of Interleukin-8 Production (GO:0032757): Calculation completed
Positive Regulation of Intracellular Signal Transduction (GO:1902533): Calculation started
Positive Regulation of Intracellular Signal Transduction (GO:1902533): scoring computed

Calculating pathways:  81%|████████  | 471/583 [38:59<10:49,  5.80s/it]

Positive Regulation of Intracellular Signal Transduction (GO:1902533): pvalue calculation completed
Positive Regulation of Intracellular Signal Transduction (GO:1902533): Calculation completed
Positive Regulation of Lymphocyte Activation (GO:0051251): Calculation started
Positive Regulation of Lymphocyte Activation (GO:0051251): scoring computed

Calculating pathways:  81%|████████  | 472/583 [39:03<09:34,  5.18s/it]

Positive Regulation of Lymphocyte Activation (GO:0051251): pvalue calculation completed
Positive Regulation of Lymphocyte Activation (GO:0051251): Calculation completed
Positive Regulation of Macroautophagy (GO:0016239): Calculation started
Positive Regulation of Macroautophagy (GO:0016239): scoring computed

Calculating pathways:  81%|████████  | 473/583 [39:07<08:56,  4.87s/it]

Positive Regulation of Macroautophagy (GO:0016239): pvalue calculation completed
Positive Regulation of Macroautophagy (GO:0016239): Calculation completed
Positive Regulation of Mitophagy (GO:1901526): Calculation started
Positive Regulation of Mitophagy (GO:1901526): scoring computed

Calculating pathways:  81%|████████▏ | 474/583 [39:11<08:06,  4.47s/it]

Positive Regulation of Mitophagy (GO:1901526): pvalue calculation completed
Positive Regulation of Mitophagy (GO:1901526): Calculation completed
Positive Regulation of Muscle Contraction (GO:0045933): Calculation started
Positive Regulation of Muscle Contraction (GO:0045933): scoring computed

Calculating pathways:  81%|████████▏ | 475/583 [39:14<07:27,  4.15s/it]

Positive Regulation of Muscle Contraction (GO:0045933): pvalue calculation completed
Positive Regulation of Muscle Contraction (GO:0045933): Calculation completed
Positive Regulation of Neuron Projection Development (GO:0010976): Calculation started
Positive Regulation of Neuron Projection Development (GO:0010976): scoring computed

Calculating pathways:  82%|████████▏ | 476/583 [39:18<07:32,  4.23s/it]

Positive Regulation of Neuron Projection Development (GO:0010976): pvalue calculation completed
Positive Regulation of Neuron Projection Development (GO:0010976): Calculation completed
Positive Regulation of Non-Canonical NF-kappaB Signal Transduction (GO:1901224): Calculation started
Positive Regulation of Non-Canonical NF-kappaB Signal Transduction (GO:1901224): scoring computed

Calculating pathways:  82%|████████▏ | 477/583 [39:22<07:14,  4.10s/it]

Positive Regulation of Non-Canonical NF-kappaB Signal Transduction (GO:1901224): pvalue calculation completed
Positive Regulation of Non-Canonical NF-kappaB Signal Transduction (GO:1901224): Calculation completed
Positive Regulation of Peptidyl-Serine Phosphorylation (GO:0033138): Calculation started
Positive Regulation of Peptidyl-Serine Phosphorylation (GO:0033138): scoring computed

Calculating pathways:  82%|████████▏ | 478/583 [39:26<07:00,  4.01s/it]

Positive Regulation of Peptidyl-Serine Phosphorylation (GO:0033138): pvalue calculation completed
Positive Regulation of Peptidyl-Serine Phosphorylation (GO:0033138): Calculation completed
Positive Regulation of Phagocytosis (GO:0050766): Calculation started
Positive Regulation of Phagocytosis (GO:0050766): scoring computed

Calculating pathways:  82%|████████▏ | 479/583 [39:30<06:56,  4.01s/it]

Positive Regulation of Phagocytosis (GO:0050766): pvalue calculation completed
Positive Regulation of Phagocytosis (GO:0050766): Calculation completed
Positive Regulation of Production of Molecular Mediator of Immune Response (GO:0002702): Calculation started
Positive Regulation of Production of Molecular Mediator of Immune Response (GO:0002702): scoring computed

Calculating pathways:  82%|████████▏ | 480/583 [39:34<06:45,  3.94s/it]

Positive Regulation of Production of Molecular Mediator of Immune Response (GO:0002702): pvalue calculation completed
Positive Regulation of Production of Molecular Mediator of Immune Response (GO:0002702): Calculation completed
Positive Regulation of Protein K63-linked Ubiquitination (GO:1902523): Calculation started
Positive Regulation of Protein K63-linked Ubiquitination (GO:1902523): scoring computed

Calculating pathways:  83%|████████▎ | 481/583 [39:37<06:24,  3.77s/it]

Positive Regulation of Protein K63-linked Ubiquitination (GO:1902523): pvalue calculation completed
Positive Regulation of Protein K63-linked Ubiquitination (GO:1902523): Calculation completed
Positive Regulation of Protein Localization (GO:1903829): Calculation started
Positive Regulation of Protein Localization (GO:1903829): scoring computed

Calculating pathways:  83%|████████▎ | 482/583 [39:42<06:47,  4.03s/it]

Positive Regulation of Protein Localization (GO:1903829): pvalue calculation completed
Positive Regulation of Protein Localization (GO:1903829): Calculation completed
Positive Regulation of Protein Localization to Membrane (GO:1905477): Calculation started
Positive Regulation of Protein Localization to Membrane (GO:1905477): scoring computed

Calculating pathways:  83%|████████▎ | 483/583 [39:46<06:43,  4.04s/it]

Positive Regulation of Protein Localization to Membrane (GO:1905477): pvalue calculation completed
Positive Regulation of Protein Localization to Membrane (GO:1905477): Calculation completed
Positive Regulation of Protein Metabolic Process (GO:0051247): Calculation started
Positive Regulation of Protein Metabolic Process (GO:0051247): scoring computed

Calculating pathways:  83%|████████▎ | 484/583 [39:52<07:28,  4.53s/it]

Positive Regulation of Protein Metabolic Process (GO:0051247): pvalue calculation completed
Positive Regulation of Protein Metabolic Process (GO:0051247): Calculation completed
Positive Regulation of Protein Phosphorylation (GO:0001934): Calculation started
Positive Regulation of Protein Phosphorylation (GO:0001934): scoring computed

Calculating pathways:  83%|████████▎ | 485/583 [39:57<07:45,  4.75s/it]

Positive Regulation of Protein Phosphorylation (GO:0001934): pvalue calculation completed
Positive Regulation of Protein Phosphorylation (GO:0001934): Calculation completed
Positive Regulation of Protein Polyubiquitination (GO:1902916): Calculation started
Positive Regulation of Protein Polyubiquitination (GO:1902916): scoring computed

Calculating pathways:  83%|████████▎ | 486/583 [40:00<07:06,  4.40s/it]

Positive Regulation of Protein Polyubiquitination (GO:1902916): pvalue calculation completed
Positive Regulation of Protein Polyubiquitination (GO:1902916): Calculation completed
Positive Regulation of Protein Serine/Threonine Kinase Activity (GO:0071902): Calculation started
Positive Regulation of Protein Serine/Threonine Kinase Activity (GO:0071902): scoring computed

Calculating pathways:  84%|████████▎ | 487/583 [40:04<06:51,  4.29s/it]

Positive Regulation of Protein Serine/Threonine Kinase Activity (GO:0071902): pvalue calculation completed
Positive Regulation of Protein Serine/Threonine Kinase Activity (GO:0071902): Calculation completed
Positive Regulation of Protein Targeting to Membrane (GO:0090314): Calculation started
Positive Regulation of Protein Targeting to Membrane (GO:0090314): scoring computed

Calculating pathways:  84%|████████▎ | 488/583 [40:08<06:25,  4.06s/it]

Positive Regulation of Protein Targeting to Membrane (GO:0090314): pvalue calculation completed
Positive Regulation of Protein Targeting to Membrane (GO:0090314): Calculation completed
Positive Regulation of Reproductive Process (GO:2000243): Calculation started
Positive Regulation of Reproductive Process (GO:2000243): scoring computed

Calculating pathways:  84%|████████▍ | 489/583 [40:12<06:08,  3.92s/it]

Positive Regulation of Reproductive Process (GO:2000243): pvalue calculation completed
Positive Regulation of Reproductive Process (GO:2000243): Calculation completed
Positive Regulation of Signal Transduction (GO:0009967): Calculation started
Positive Regulation of Signal Transduction (GO:0009967): scoring computed

Calculating pathways:  84%|████████▍ | 490/583 [40:17<06:59,  4.52s/it]

Positive Regulation of Signal Transduction (GO:0009967): pvalue calculation completed
Positive Regulation of Signal Transduction (GO:0009967): Calculation completed
Positive Regulation of Small GTPase Mediated Signal Transduction (GO:0051057): Calculation started
Positive Regulation of Small GTPase Mediated Signal Transduction (GO:0051057): scoring computed

Calculating pathways:  84%|████████▍ | 491/583 [40:21<06:36,  4.31s/it]

Positive Regulation of Small GTPase Mediated Signal Transduction (GO:0051057): pvalue calculation completed
Positive Regulation of Small GTPase Mediated Signal Transduction (GO:0051057): Calculation completed
Positive Regulation of Smooth Muscle Contraction (GO:0045987): Calculation started
Positive Regulation of Smooth Muscle Contraction (GO:0045987): scoring computed

Calculating pathways:  84%|████████▍ | 492/583 [40:25<06:07,  4.04s/it]

Positive Regulation of Smooth Muscle Contraction (GO:0045987): pvalue calculation completed
Positive Regulation of Smooth Muscle Contraction (GO:0045987): Calculation completed
Positive Regulation of Stress-Activated MAPK Cascade (GO:0032874): Calculation started
Positive Regulation of Stress-Activated MAPK Cascade (GO:0032874): scoring computed

Calculating pathways:  85%|████████▍ | 493/583 [40:28<05:47,  3.86s/it]

Positive Regulation of Stress-Activated MAPK Cascade (GO:0032874): pvalue calculation completed
Positive Regulation of Stress-Activated MAPK Cascade (GO:0032874): Calculation completed
Positive Regulation of Stress-Activated Protein Kinase Signaling Cascade (GO:0070304): Calculation started
Positive Regulation of Stress-Activated Protein Kinase Signaling Cascade (GO:0070304): scoring computed

Calculating pathways:  85%|████████▍ | 494/583 [40:32<05:35,  3.77s/it]

Positive Regulation of Stress-Activated Protein Kinase Signaling Cascade (GO:0070304): pvalue calculation completed
Positive Regulation of Stress-Activated Protein Kinase Signaling Cascade (GO:0070304): Calculation completed
Positive Regulation of Transcription by RNA Polymerase I (GO:0045943): Calculation started
Positive Regulation of Transcription by RNA Polymerase I (GO:0045943): scoring computed

Calculating pathways:  85%|████████▍ | 495/583 [40:36<05:33,  3.79s/it]

Positive Regulation of Transcription by RNA Polymerase I (GO:0045943): pvalue calculation completed
Positive Regulation of Transcription by RNA Polymerase I (GO:0045943): Calculation completed
Positive Regulation of Transcription by RNA Polymerase II (GO:0045944): Calculation started
Positive Regulation of Transcription by RNA Polymerase II (GO:0045944): scoring computed

Calculating pathways:  85%|████████▌ | 496/583 [40:49<09:29,  6.55s/it]

Positive Regulation of Transcription by RNA Polymerase II (GO:0045944): pvalue calculation completed
Positive Regulation of Transcription by RNA Polymerase II (GO:0045944): Calculation completed
Positive Regulation of Translation (GO:0045727): Calculation started
Positive Regulation of Translation (GO:0045727): scoring computed

Calculating pathways:  85%|████████▌ | 497/583 [40:53<08:30,  5.93s/it]

Positive Regulation of Translation (GO:0045727): pvalue calculation completed
Positive Regulation of Translation (GO:0045727): Calculation completed
Positive Regulation of Tumor Necrosis Factor Production (GO:0032760): Calculation started
Positive Regulation of Tumor Necrosis Factor Production (GO:0032760): scoring computed

Calculating pathways:  85%|████████▌ | 498/583 [40:57<07:40,  5.42s/it]

Positive Regulation of Tumor Necrosis Factor Production (GO:0032760): pvalue calculation completed
Positive Regulation of Tumor Necrosis Factor Production (GO:0032760): Calculation completed
Positive Regulation of Tumor Necrosis Factor Superfamily Cytokine Production (GO:1903557): Calculation started
Positive Regulation of Tumor Necrosis Factor Superfamily Cytokine Production (GO:1903557): scoring computed

Calculating pathways:  86%|████████▌ | 499/583 [41:01<07:04,  5.06s/it]

Positive Regulation of Tumor Necrosis Factor Superfamily Cytokine Production (GO:1903557): pvalue calculation completed
Positive Regulation of Tumor Necrosis Factor Superfamily Cytokine Production (GO:1903557): Calculation completed
Positive Regulation of Type 2 Immune Response (GO:0002830): Calculation started
Positive Regulation of Type 2 Immune Response (GO:0002830): scoring computed

Calculating pathways:  86%|████████▌ | 500/583 [41:05<06:19,  4.57s/it]

Positive Regulation of Type 2 Immune Response (GO:0002830): pvalue calculation completed
Positive Regulation of Type 2 Immune Response (GO:0002830): Calculation completed
Protein Modification Process (GO:0036211): Calculation started
Protein Modification Process (GO:0036211): scoring computed

Calculating pathways:  86%|████████▌ | 501/583 [41:14<08:05,  5.92s/it]

Protein Modification Process (GO:0036211): pvalue calculation completed
Protein Modification Process (GO:0036211): Calculation completed
Protein Phosphorylation (GO:0006468): Calculation started
Protein Phosphorylation (GO:0006468): scoring computed

Calculating pathways:  86%|████████▌ | 502/583 [41:21<08:33,  6.34s/it]

Protein Phosphorylation (GO:0006468): pvalue calculation completed
Protein Phosphorylation (GO:0006468): Calculation completed
Reelin-Mediated Signaling Pathway (GO:0038026): Calculation started
Reelin-Mediated Signaling Pathway (GO:0038026): scoring computed

Calculating pathways:  86%|████████▋ | 503/583 [41:25<07:18,  5.48s/it]

Reelin-Mediated Signaling Pathway (GO:0038026): pvalue calculation completed
Reelin-Mediated Signaling Pathway (GO:0038026): Calculation completed
Regulation of B Cell Activation (GO:0050864): Calculation started
Regulation of B Cell Activation (GO:0050864): scoring computed

Calculating pathways:  86%|████████▋ | 504/583 [41:28<06:27,  4.90s/it]

Regulation of B Cell Activation (GO:0050864): pvalue calculation completed
Regulation of B Cell Activation (GO:0050864): Calculation completed
Regulation of ERK1 and ERK2 Cascade (GO:0070372): Calculation started
Regulation of ERK1 and ERK2 Cascade (GO:0070372): scoring computed

Calculating pathways:  87%|████████▋ | 505/583 [41:34<06:40,  5.13s/it]

Regulation of ERK1 and ERK2 Cascade (GO:0070372): pvalue calculation completed
Regulation of ERK1 and ERK2 Cascade (GO:0070372): Calculation completed
Regulation of JNK Cascade (GO:0046328): Calculation started
Regulation of JNK Cascade (GO:0046328): scoring computed

Calculating pathways:  87%|████████▋ | 506/583 [41:39<06:24,  4.99s/it]

Regulation of JNK Cascade (GO:0046328): pvalue calculation completed
Regulation of JNK Cascade (GO:0046328): Calculation completed
Regulation of MAP Kinase Activity (GO:0043405): Calculation started
Regulation of MAP Kinase Activity (GO:0043405): scoring computed

Calculating pathways:  87%|████████▋ | 507/583 [41:43<05:58,  4.71s/it]

Regulation of MAP Kinase Activity (GO:0043405): pvalue calculation completed
Regulation of MAP Kinase Activity (GO:0043405): Calculation completed
Regulation of MAPK Cascade (GO:0043408): Calculation started
Regulation of MAPK Cascade (GO:0043408): scoring computed

Calculating pathways:  87%|████████▋ | 508/583 [41:49<06:19,  5.06s/it]

Regulation of MAPK Cascade (GO:0043408): pvalue calculation completed
Regulation of MAPK Cascade (GO:0043408): Calculation completed
Regulation of Notch Signaling Pathway (GO:0008593): Calculation started
Regulation of Notch Signaling Pathway (GO:0008593): scoring computed

Calculating pathways:  87%|████████▋ | 509/583 [41:53<05:52,  4.76s/it]

Regulation of Notch Signaling Pathway (GO:0008593): pvalue calculation completed
Regulation of Notch Signaling Pathway (GO:0008593): Calculation completed
Regulation of RNA Biosynthetic Process (GO:2001141): Calculation started
Regulation of RNA Biosynthetic Process (GO:2001141): scoring computed

Calculating pathways:  87%|████████▋ | 510/583 [42:01<07:05,  5.82s/it]

Regulation of RNA Biosynthetic Process (GO:2001141): pvalue calculation completed
Regulation of RNA Biosynthetic Process (GO:2001141): Calculation completed
Regulation of Rho Protein Signal Transduction (GO:0035023): Calculation started
Regulation of Rho Protein Signal Transduction (GO:0035023): scoring computed

Calculating pathways:  88%|████████▊ | 511/583 [42:05<06:23,  5.32s/it]

Regulation of Rho Protein Signal Transduction (GO:0035023): pvalue calculation completed
Regulation of Rho Protein Signal Transduction (GO:0035023): Calculation completed
Regulation of Anatomical Structure Morphogenesis (GO:0022603): Calculation started
Regulation of Anatomical Structure Morphogenesis (GO:0022603): scoring computed

Calculating pathways:  88%|████████▊ | 512/583 [42:10<06:06,  5.16s/it]

Regulation of Anatomical Structure Morphogenesis (GO:0022603): pvalue calculation completed
Regulation of Anatomical Structure Morphogenesis (GO:0022603): Calculation completed
Regulation of Angiogenesis (GO:0045765): Calculation started
Regulation of Angiogenesis (GO:0045765): scoring computed

Calculating pathways:  88%|████████▊ | 513/583 [42:16<06:11,  5.31s/it]

Regulation of Angiogenesis (GO:0045765): pvalue calculation completed
Regulation of Angiogenesis (GO:0045765): Calculation completed
Regulation of Apoptotic Process (GO:0042981): Calculation started
Regulation of Apoptotic Process (GO:0042981): scoring computed

Calculating pathways:  88%|████████▊ | 514/583 [42:26<07:53,  6.86s/it]

Regulation of Apoptotic Process (GO:0042981): pvalue calculation completed
Regulation of Apoptotic Process (GO:0042981): Calculation completed
Regulation of Axon Guidance (GO:1902667): Calculation started
Regulation of Axon Guidance (GO:1902667): scoring computed

Calculating pathways:  88%|████████▊ | 515/583 [42:29<06:34,  5.80s/it]

Regulation of Axon Guidance (GO:1902667): pvalue calculation completed
Regulation of Axon Guidance (GO:1902667): Calculation completed
Regulation of Calcium Ion Import (GO:0090279): Calculation started
Regulation of Calcium Ion Import (GO:0090279): scoring computed

Calculating pathways:  89%|████████▊ | 516/583 [42:33<05:43,  5.12s/it]

Regulation of Calcium Ion Import (GO:0090279): pvalue calculation completed
Regulation of Calcium Ion Import (GO:0090279): Calculation completed
Regulation of Calcium Ion Import Across Plasma Membrane (GO:1905664): Calculation started
Regulation of Calcium Ion Import Across Plasma Membrane (GO:1905664): scoring computed

Calculating pathways:  89%|████████▊ | 517/583 [42:36<05:06,  4.64s/it]

Regulation of Calcium Ion Import Across Plasma Membrane (GO:1905664): pvalue calculation completed
Regulation of Calcium Ion Import Across Plasma Membrane (GO:1905664): Calculation completed
Regulation of Calcium Ion Transmembrane Transport (GO:1903169): Calculation started
Regulation of Calcium Ion Transmembrane Transport (GO:1903169): scoring computed

Calculating pathways:  89%|████████▉ | 518/583 [42:40<04:41,  4.33s/it]

Regulation of Calcium Ion Transmembrane Transport (GO:1903169): pvalue calculation completed
Regulation of Calcium Ion Transmembrane Transport (GO:1903169): Calculation completed
Regulation of Canonical NF-kappaB Signal Transduction (GO:0043122): Calculation started
Regulation of Canonical NF-kappaB Signal Transduction (GO:0043122): scoring computed

Calculating pathways:  89%|████████▉ | 519/583 [42:46<05:11,  4.87s/it]

Regulation of Canonical NF-kappaB Signal Transduction (GO:0043122): pvalue calculation completed
Regulation of Canonical NF-kappaB Signal Transduction (GO:0043122): Calculation completed
Regulation of Cell Adhesion (GO:0030155): Calculation started
Regulation of Cell Adhesion (GO:0030155): scoring computed

Calculating pathways:  89%|████████▉ | 520/583 [42:51<05:07,  4.87s/it]

Regulation of Cell Adhesion (GO:0030155): pvalue calculation completed
Regulation of Cell Adhesion (GO:0030155): Calculation completed
Regulation of Cell Communication (GO:0010646): Calculation started
Regulation of Cell Communication (GO:0010646): scoring computed

Calculating pathways:  89%|████████▉ | 521/583 [42:55<04:45,  4.61s/it]

Regulation of Cell Communication (GO:0010646): pvalue calculation completed
Regulation of Cell Communication (GO:0010646): Calculation completed
Regulation of Cell Growth (GO:0001558): Calculation started
Regulation of Cell Growth (GO:0001558): scoring computed

Calculating pathways:  90%|████████▉ | 522/583 [43:01<05:00,  4.93s/it]

Regulation of Cell Growth (GO:0001558): pvalue calculation completed
Regulation of Cell Growth (GO:0001558): Calculation completed
Regulation of Cytokine Production Involved in Immune Response (GO:0002718): Calculation started
Regulation of Cytokine Production Involved in Immune Response (GO:0002718): scoring computed

Calculating pathways:  90%|████████▉ | 523/583 [43:04<04:33,  4.55s/it]

Regulation of Cytokine Production Involved in Immune Response (GO:0002718): pvalue calculation completed
Regulation of Cytokine Production Involved in Immune Response (GO:0002718): Calculation completed
Regulation of Cytokine Production Involved in Inflammatory Response (GO:1900015): Calculation started
Regulation of Cytokine Production Involved in Inflammatory Response (GO:1900015): scoring computed

Calculating pathways:  90%|████████▉ | 524/583 [43:08<04:17,  4.37s/it]

Regulation of Cytokine Production Involved in Inflammatory Response (GO:1900015): pvalue calculation completed
Regulation of Cytokine Production Involved in Inflammatory Response (GO:1900015): Calculation completed
Regulation of Defense Response (GO:0031347): Calculation started
Regulation of Defense Response (GO:0031347): scoring computed

Calculating pathways:  90%|█████████ | 525/583 [43:13<04:12,  4.35s/it]

Regulation of Defense Response (GO:0031347): pvalue calculation completed
Regulation of Defense Response (GO:0031347): Calculation completed
Regulation of Dendritic Cell Antigen Processing and Presentation (GO:0002604): Calculation started
Regulation of Dendritic Cell Antigen Processing and Presentation (GO:0002604): scoring computed

Calculating pathways:  90%|█████████ | 526/583 [43:16<03:51,  4.06s/it]

Regulation of Dendritic Cell Antigen Processing and Presentation (GO:0002604): pvalue calculation completed
Regulation of Dendritic Cell Antigen Processing and Presentation (GO:0002604): Calculation completed
Regulation of Dendritic Spine Maintenance (GO:1902950): Calculation started
Regulation of Dendritic Spine Maintenance (GO:1902950): scoring computed

Calculating pathways:  90%|█████████ | 527/583 [43:19<03:35,  3.85s/it]

Regulation of Dendritic Spine Maintenance (GO:1902950): pvalue calculation completed
Regulation of Dendritic Spine Maintenance (GO:1902950): Calculation completed
Regulation of Epithelial Cell Proliferation (GO:0050678): Calculation started
Regulation of Epithelial Cell Proliferation (GO:0050678): scoring computed

Calculating pathways:  91%|█████████ | 528/583 [43:24<03:39,  3.99s/it]

Regulation of Epithelial Cell Proliferation (GO:0050678): pvalue calculation completed
Regulation of Epithelial Cell Proliferation (GO:0050678): Calculation completed
Regulation of Flagellated Sperm Motility (GO:1901317): Calculation started
Regulation of Flagellated Sperm Motility (GO:1901317): scoring computed

Calculating pathways:  91%|█████████ | 529/583 [43:27<03:25,  3.81s/it]

Regulation of Flagellated Sperm Motility (GO:1901317): pvalue calculation completed
Regulation of Flagellated Sperm Motility (GO:1901317): Calculation completed
Regulation of Gene Expression (GO:0010468): Calculation started
Regulation of Gene Expression (GO:0010468): scoring computed

Calculating pathways:  91%|█████████ | 530/583 [43:41<06:07,  6.94s/it]

Regulation of Gene Expression (GO:0010468): pvalue calculation completed
Regulation of Gene Expression (GO:0010468): Calculation completed
Regulation of Glutamate Receptor Signaling Pathway (GO:1900449): Calculation started
Regulation of Glutamate Receptor Signaling Pathway (GO:1900449): scoring computed

Calculating pathways:  91%|█████████ | 531/583 [43:45<05:04,  5.86s/it]

Regulation of Glutamate Receptor Signaling Pathway (GO:1900449): pvalue calculation completed
Regulation of Glutamate Receptor Signaling Pathway (GO:1900449): Calculation completed
Regulation of Hormone Secretion (GO:0046883): Calculation started
Regulation of Hormone Secretion (GO:0046883): scoring computed

Calculating pathways:  91%|█████████▏| 532/583 [43:48<04:21,  5.12s/it]

Regulation of Hormone Secretion (GO:0046883): pvalue calculation completed
Regulation of Hormone Secretion (GO:0046883): Calculation completed
Regulation of Inflammatory Response (GO:0050727): Calculation started
Regulation of Inflammatory Response (GO:0050727): scoring computed

Calculating pathways:  91%|█████████▏| 533/583 [43:54<04:26,  5.33s/it]

Regulation of Inflammatory Response (GO:0050727): pvalue calculation completed
Regulation of Inflammatory Response (GO:0050727): Calculation completed
Regulation of Inflammatory Response to Antigenic Stimulus (GO:0002861): Calculation started
Regulation of Inflammatory Response to Antigenic Stimulus (GO:0002861): scoring computed

Calculating pathways:  92%|█████████▏| 534/583 [43:57<03:55,  4.81s/it]

Regulation of Inflammatory Response to Antigenic Stimulus (GO:0002861): pvalue calculation completed
Regulation of Inflammatory Response to Antigenic Stimulus (GO:0002861): Calculation completed
Regulation of Interleukin-1 Beta Production (GO:0032651): Calculation started
Regulation of Interleukin-1 Beta Production (GO:0032651): scoring computed

Calculating pathways:  92%|█████████▏| 535/583 [44:02<03:42,  4.64s/it]

Regulation of Interleukin-1 Beta Production (GO:0032651): pvalue calculation completed
Regulation of Interleukin-1 Beta Production (GO:0032651): Calculation completed
Regulation of Interleukin-10 Production (GO:0032653): Calculation started
Regulation of Interleukin-10 Production (GO:0032653): scoring computed

Calculating pathways:  92%|█████████▏| 536/583 [44:06<03:27,  4.41s/it]

Regulation of Interleukin-10 Production (GO:0032653): pvalue calculation completed
Regulation of Interleukin-10 Production (GO:0032653): Calculation completed
Regulation of Interleukin-17 Production (GO:0032660): Calculation started
Regulation of Interleukin-17 Production (GO:0032660): scoring computed

Calculating pathways:  92%|█████████▏| 537/583 [44:09<03:12,  4.19s/it]

Regulation of Interleukin-17 Production (GO:0032660): pvalue calculation completed
Regulation of Interleukin-17 Production (GO:0032660): Calculation completed
Regulation of Interleukin-6 Production (GO:0032675): Calculation started
Regulation of Interleukin-6 Production (GO:0032675): scoring computed

Calculating pathways:  92%|█████████▏| 538/583 [44:14<03:10,  4.24s/it]

Regulation of Interleukin-6 Production (GO:0032675): pvalue calculation completed
Regulation of Interleukin-6 Production (GO:0032675): Calculation completed
Regulation of Interleukin-8 Production (GO:0032677): Calculation started
Regulation of Interleukin-8 Production (GO:0032677): scoring computed

Calculating pathways:  92%|█████████▏| 539/583 [44:18<03:07,  4.26s/it]

Regulation of Interleukin-8 Production (GO:0032677): pvalue calculation completed
Regulation of Interleukin-8 Production (GO:0032677): Calculation completed
Regulation of Macrophage Apoptotic Process (GO:2000109): Calculation started
Regulation of Macrophage Apoptotic Process (GO:2000109): scoring computed

Calculating pathways:  93%|█████████▎| 540/583 [44:21<02:51,  3.99s/it]

Regulation of Macrophage Apoptotic Process (GO:2000109): pvalue calculation completed
Regulation of Macrophage Apoptotic Process (GO:2000109): Calculation completed
Regulation of Metabolic Process (GO:0019222): Calculation started
Regulation of Metabolic Process (GO:0019222): scoring computed

Calculating pathways:  93%|█████████▎| 541/583 [44:25<02:45,  3.95s/it]

Regulation of Metabolic Process (GO:0019222): pvalue calculation completed
Regulation of Metabolic Process (GO:0019222): Calculation completed
Regulation of Microtubule Polymerization (GO:0031113): Calculation started
Regulation of Microtubule Polymerization (GO:0031113): scoring computed

Calculating pathways:  93%|█████████▎| 542/583 [44:29<02:42,  3.96s/it]

Regulation of Microtubule Polymerization (GO:0031113): pvalue calculation completed
Regulation of Microtubule Polymerization (GO:0031113): Calculation completed
Regulation of Microtubule-Based Process (GO:0032886): Calculation started
Regulation of Microtubule-Based Process (GO:0032886): scoring computed

Calculating pathways:  93%|█████████▎| 543/583 [44:33<02:36,  3.91s/it]

Regulation of Microtubule-Based Process (GO:0032886): pvalue calculation completed
Regulation of Microtubule-Based Process (GO:0032886): Calculation completed
Regulation of Mitochondrial Membrane Potential (GO:0051881): Calculation started
Regulation of Mitochondrial Membrane Potential (GO:0051881): scoring computed

Calculating pathways:  93%|█████████▎| 544/583 [44:37<02:29,  3.84s/it]

Regulation of Mitochondrial Membrane Potential (GO:0051881): pvalue calculation completed
Regulation of Mitochondrial Membrane Potential (GO:0051881): Calculation completed
Regulation of Mitophagy (GO:1901524): Calculation started
Regulation of Mitophagy (GO:1901524): scoring computed

Calculating pathways:  93%|█████████▎| 545/583 [44:40<02:23,  3.78s/it]

Regulation of Mitophagy (GO:1901524): pvalue calculation completed
Regulation of Mitophagy (GO:1901524): Calculation completed
Regulation of Non-Canonical NF-kappaB Signal Transduction (GO:1901222): Calculation started
Regulation of Non-Canonical NF-kappaB Signal Transduction (GO:1901222): scoring computed

Calculating pathways:  94%|█████████▎| 546/583 [44:44<02:22,  3.86s/it]

Regulation of Non-Canonical NF-kappaB Signal Transduction (GO:1901222): pvalue calculation completed
Regulation of Non-Canonical NF-kappaB Signal Transduction (GO:1901222): Calculation completed
Regulation of Oxidative Stress-Induced Intrinsic Apoptotic Signaling Pathway (GO:1902175): Calculation started
Regulation of Oxidative Stress-Induced Intrinsic Apoptotic Signaling Pathway (GO:1902175): scoring computed

Calculating pathways:  94%|█████████▍| 547/583 [44:48<02:15,  3.76s/it]

Regulation of Oxidative Stress-Induced Intrinsic Apoptotic Signaling Pathway (GO:1902175): pvalue calculation completed
Regulation of Oxidative Stress-Induced Intrinsic Apoptotic Signaling Pathway (GO:1902175): Calculation completed
Regulation of Peptidyl-Serine Phosphorylation (GO:0033135): Calculation started
Regulation of Peptidyl-Serine Phosphorylation (GO:0033135): scoring computed

Calculating pathways:  94%|█████████▍| 548/583 [44:52<02:11,  3.76s/it]

Regulation of Peptidyl-Serine Phosphorylation (GO:0033135): pvalue calculation completed
Regulation of Peptidyl-Serine Phosphorylation (GO:0033135): Calculation completed
Regulation of Phagocytosis (GO:0050764): Calculation started
Regulation of Phagocytosis (GO:0050764): scoring computed

Calculating pathways:  94%|█████████▍| 549/583 [44:56<02:12,  3.91s/it]

Regulation of Phagocytosis (GO:0050764): pvalue calculation completed
Regulation of Phagocytosis (GO:0050764): Calculation completed
Regulation of Protein K63-linked Ubiquitination (GO:1900044): Calculation started
Regulation of Protein K63-linked Ubiquitination (GO:1900044): scoring computed

Calculating pathways:  94%|█████████▍| 550/583 [44:59<02:04,  3.78s/it]

Regulation of Protein K63-linked Ubiquitination (GO:1900044): pvalue calculation completed
Regulation of Protein K63-linked Ubiquitination (GO:1900044): Calculation completed
Regulation of Protein Localization to Membrane (GO:1905475): Calculation started
Regulation of Protein Localization to Membrane (GO:1905475): scoring computed

Calculating pathways:  95%|█████████▍| 551/583 [45:03<02:01,  3.79s/it]

Regulation of Protein Localization to Membrane (GO:1905475): pvalue calculation completed
Regulation of Protein Localization to Membrane (GO:1905475): Calculation completed
Regulation of Protein Targeting to Membrane (GO:0090313): Calculation started
Regulation of Protein Targeting to Membrane (GO:0090313): scoring computed

Calculating pathways:  95%|█████████▍| 552/583 [45:07<01:55,  3.74s/it]

Regulation of Protein Targeting to Membrane (GO:0090313): pvalue calculation completed
Regulation of Protein Targeting to Membrane (GO:0090313): Calculation completed
Regulation of Protein-Containing Complex Assembly (GO:0043254): Calculation started
Regulation of Protein-Containing Complex Assembly (GO:0043254): scoring computed

Calculating pathways:  95%|█████████▍| 553/583 [45:11<02:00,  4.02s/it]

Regulation of Protein-Containing Complex Assembly (GO:0043254): pvalue calculation completed
Regulation of Protein-Containing Complex Assembly (GO:0043254): Calculation completed
Regulation of Response to External Stimulus (GO:0032101): Calculation started
Regulation of Response to External Stimulus (GO:0032101): scoring computed

Calculating pathways:  95%|█████████▌| 554/583 [45:16<02:02,  4.21s/it]

Regulation of Response to External Stimulus (GO:0032101): pvalue calculation completed
Regulation of Response to External Stimulus (GO:0032101): Calculation completed
Regulation of Secretion by Cell (GO:1903530): Calculation started
Regulation of Secretion by Cell (GO:1903530): scoring computed

Calculating pathways:  95%|█████████▌| 555/583 [45:20<01:55,  4.12s/it]

Regulation of Secretion by Cell (GO:1903530): pvalue calculation completed
Regulation of Secretion by Cell (GO:1903530): Calculation completed
Regulation of Signal Transduction (GO:0009966): Calculation started
Regulation of Signal Transduction (GO:0009966): scoring computed

Calculating pathways:  95%|█████████▌| 556/583 [45:26<02:03,  4.58s/it]

Regulation of Signal Transduction (GO:0009966): pvalue calculation completed
Regulation of Signal Transduction (GO:0009966): Calculation completed
Regulation of Smooth Muscle Contraction (GO:0006940): Calculation started
Regulation of Smooth Muscle Contraction (GO:0006940): scoring computed

Calculating pathways:  96%|█████████▌| 557/583 [45:29<01:50,  4.25s/it]

Regulation of Smooth Muscle Contraction (GO:0006940): pvalue calculation completed
Regulation of Smooth Muscle Contraction (GO:0006940): Calculation completed
Regulation of Steroid Metabolic Process (GO:0019218): Calculation started
Regulation of Steroid Metabolic Process (GO:0019218): scoring computed

Calculating pathways:  96%|█████████▌| 558/583 [45:33<01:40,  4.03s/it]

Regulation of Steroid Metabolic Process (GO:0019218): pvalue calculation completed
Regulation of Steroid Metabolic Process (GO:0019218): Calculation completed
Regulation of Stress-Activated MAPK Cascade (GO:0032872): Calculation started
Regulation of Stress-Activated MAPK Cascade (GO:0032872): scoring computed

Calculating pathways:  96%|█████████▌| 559/583 [45:36<01:34,  3.93s/it]

Regulation of Stress-Activated MAPK Cascade (GO:0032872): pvalue calculation completed
Regulation of Stress-Activated MAPK Cascade (GO:0032872): Calculation completed
Regulation of Transcription by RNA Polymerase I (GO:0006356): Calculation started
Regulation of Transcription by RNA Polymerase I (GO:0006356): scoring computed

Calculating pathways:  96%|█████████▌| 560/583 [45:40<01:27,  3.82s/it]

Regulation of Transcription by RNA Polymerase I (GO:0006356): pvalue calculation completed
Regulation of Transcription by RNA Polymerase I (GO:0006356): Calculation completed
Regulation of Translation (GO:0006417): Calculation started
Regulation of Translation (GO:0006417): scoring computed

Calculating pathways:  96%|█████████▌| 561/583 [45:45<01:35,  4.32s/it]

Regulation of Translation (GO:0006417): pvalue calculation completed
Regulation of Translation (GO:0006417): Calculation completed
Regulation of Tumor Necrosis Factor Production (GO:0032680): Calculation started
Regulation of Tumor Necrosis Factor Production (GO:0032680): scoring computed

Calculating pathways:  96%|█████████▋| 562/583 [45:50<01:32,  4.41s/it]

Regulation of Tumor Necrosis Factor Production (GO:0032680): pvalue calculation completed
Regulation of Tumor Necrosis Factor Production (GO:0032680): Calculation completed
Regulation of Type 2 Immune Response (GO:0002828): Calculation started
Regulation of Type 2 Immune Response (GO:0002828): scoring computed

Calculating pathways:  97%|█████████▋| 563/583 [45:53<01:21,  4.09s/it]

Regulation of Type 2 Immune Response (GO:0002828): pvalue calculation completed
Regulation of Type 2 Immune Response (GO:0002828): Calculation completed
Regulation of Vasculature Development (GO:1901342): Calculation started
Regulation of Vasculature Development (GO:1901342): scoring computed

Calculating pathways:  97%|█████████▋| 564/583 [45:57<01:15,  3.98s/it]

Regulation of Vasculature Development (GO:1901342): pvalue calculation completed
Regulation of Vasculature Development (GO:1901342): Calculation completed
Response to Amyloid-Beta (GO:1904645): Calculation started
Response to Amyloid-Beta (GO:1904645): scoring computed

Calculating pathways:  97%|█████████▋| 565/583 [46:01<01:10,  3.92s/it]

Response to Amyloid-Beta (GO:1904645): pvalue calculation completed
Response to Amyloid-Beta (GO:1904645): Calculation completed
Response to Epidermal Growth Factor (GO:0070849): Calculation started
Response to Epidermal Growth Factor (GO:0070849): scoring computed

Calculating pathways:  97%|█████████▋| 566/583 [46:04<01:05,  3.84s/it]

Response to Epidermal Growth Factor (GO:0070849): pvalue calculation completed
Response to Epidermal Growth Factor (GO:0070849): Calculation completed
Response to Hydrogen Peroxide (GO:0042542): Calculation started
Response to Hydrogen Peroxide (GO:0042542): scoring computed

Calculating pathways:  97%|█████████▋| 567/583 [46:09<01:02,  3.92s/it]

Response to Hydrogen Peroxide (GO:0042542): pvalue calculation completed
Response to Hydrogen Peroxide (GO:0042542): Calculation completed
Response to Lipopolysaccharide (GO:0032496): Calculation started
Response to Lipopolysaccharide (GO:0032496): scoring computed

Calculating pathways:  97%|█████████▋| 568/583 [46:14<01:03,  4.24s/it]

Response to Lipopolysaccharide (GO:0032496): pvalue calculation completed
Response to Lipopolysaccharide (GO:0032496): Calculation completed
Response to Molecule of Bacterial Origin (GO:0002237): Calculation started
Response to Molecule of Bacterial Origin (GO:0002237): scoring computed

Calculating pathways:  98%|█████████▊| 569/583 [46:18<00:58,  4.16s/it]

Response to Molecule of Bacterial Origin (GO:0002237): pvalue calculation completed
Response to Molecule of Bacterial Origin (GO:0002237): Calculation completed
Response to Muramyl Dipeptide (GO:0032495): Calculation started
Response to Muramyl Dipeptide (GO:0032495): scoring computed

Calculating pathways:  98%|█████████▊| 570/583 [46:21<00:51,  3.96s/it]

Response to Muramyl Dipeptide (GO:0032495): pvalue calculation completed
Response to Muramyl Dipeptide (GO:0032495): Calculation completed
Response to Reactive Oxygen Species (GO:0000302): Calculation started
Response to Reactive Oxygen Species (GO:0000302): scoring computed

Calculating pathways:  98%|█████████▊| 571/583 [46:25<00:47,  3.97s/it]

Response to Reactive Oxygen Species (GO:0000302): pvalue calculation completed
Response to Reactive Oxygen Species (GO:0000302): Calculation completed
Semaphorin-Plexin Signaling Pathway (GO:0071526): Calculation started
Semaphorin-Plexin Signaling Pathway (GO:0071526): scoring computed

Calculating pathways:  98%|█████████▊| 572/583 [46:29<00:43,  3.99s/it]

Semaphorin-Plexin Signaling Pathway (GO:0071526): pvalue calculation completed
Semaphorin-Plexin Signaling Pathway (GO:0071526): Calculation completed
Spindle Assembly Involved in Female Meiosis (GO:0007056): Calculation started
Spindle Assembly Involved in Female Meiosis (GO:0007056): scoring computed

Calculating pathways:  98%|█████████▊| 573/583 [46:32<00:37,  3.79s/it]

Spindle Assembly Involved in Female Meiosis (GO:0007056): pvalue calculation completed
Spindle Assembly Involved in Female Meiosis (GO:0007056): Calculation completed
Steroid Metabolic Process (GO:0008202): Calculation started
Steroid Metabolic Process (GO:0008202): scoring computed

Calculating pathways:  98%|█████████▊| 574/583 [46:37<00:35,  3.94s/it]

Steroid Metabolic Process (GO:0008202): pvalue calculation completed
Steroid Metabolic Process (GO:0008202): Calculation completed
Sterol Homeostasis (GO:0055092): Calculation started
Sterol Homeostasis (GO:0055092): scoring computed

Calculating pathways:  99%|█████████▊| 575/583 [46:41<00:32,  4.08s/it]

Sterol Homeostasis (GO:0055092): pvalue calculation completed
Sterol Homeostasis (GO:0055092): Calculation completed
Stimulatory C-type Lectin Receptor Signaling Pathway (GO:0002223): Calculation started
Stimulatory C-type Lectin Receptor Signaling Pathway (GO:0002223): scoring computed

Calculating pathways:  99%|█████████▉| 576/583 [46:45<00:27,  3.93s/it]

Stimulatory C-type Lectin Receptor Signaling Pathway (GO:0002223): pvalue calculation completed
Stimulatory C-type Lectin Receptor Signaling Pathway (GO:0002223): Calculation completed
Tachykinin Receptor Signaling Pathway (GO:0007217): Calculation started
Tachykinin Receptor Signaling Pathway (GO:0007217): scoring computed

Calculating pathways:  99%|█████████▉| 577/583 [46:48<00:22,  3.76s/it]

Tachykinin Receptor Signaling Pathway (GO:0007217): pvalue calculation completed
Tachykinin Receptor Signaling Pathway (GO:0007217): Calculation completed
Transport Across Blood-Brain Barrier (GO:0150104): Calculation started
Transport Across Blood-Brain Barrier (GO:0150104): scoring computed

Calculating pathways:  99%|█████████▉| 578/583 [46:52<00:19,  3.90s/it]

Transport Across Blood-Brain Barrier (GO:0150104): pvalue calculation completed
Transport Across Blood-Brain Barrier (GO:0150104): Calculation completed
Vascular Endothelial Growth Factor Receptor Signaling Pathway (GO:0048010): Calculation started
Vascular Endothelial Growth Factor Receptor Signaling Pathway (GO:0048010): scoring computed

Calculating pathways:  99%|█████████▉| 579/583 [46:56<00:15,  3.82s/it]

Vascular Endothelial Growth Factor Receptor Signaling Pathway (GO:0048010): pvalue calculation completed
Vascular Endothelial Growth Factor Receptor Signaling Pathway (GO:0048010): Calculation completed
Vascular Transport (GO:0010232): Calculation started
Vascular Transport (GO:0010232): scoring computed

Calculating pathways:  99%|█████████▉| 580/583 [47:00<00:11,  3.95s/it]

Vascular Transport (GO:0010232): pvalue calculation completed
Vascular Transport (GO:0010232): Calculation completed
Wound Healing (GO:0042060): Calculation started
Wound Healing (GO:0042060): scoring computed

Calculating pathways: 100%|█████████▉| 581/583 [47:04<00:07,  3.98s/it]

Wound Healing (GO:0042060): pvalue calculation completed
Wound Healing (GO:0042060): Calculation completed
Xenobiotic Catabolic Process (GO:0042178): Calculation started
Xenobiotic Catabolic Process (GO:0042178): scoring computed

Calculating pathways: 100%|█████████▉| 582/583 [47:08<00:03,  3.84s/it]

Xenobiotic Catabolic Process (GO:0042178): pvalue calculation completed
Xenobiotic Catabolic Process (GO:0042178): Calculation completed
Xenobiotic Transport (GO:0042908): Calculation started
Xenobiotic Transport (GO:0042908): scoring computed

Calculating pathways: 100%|██████████| 583/583 [47:11<00:00,  4.86s/it]

Xenobiotic Transport (GO:0042908): pvalue calculation completed
Xenobiotic Transport (GO:0042908): Calculation completed

## Palbociclib

In [15]:
#loading drug_data
drug_data = json.load(open("singscore_new_code/Palbociclib/Palbociclib_relevant_pathways.json"))
count = len(drug_data)
print("Number of items:", count)

final_result = {}

for key, value in tqdm(drug_data.items(), desc="Calculating pathways"):
    print(f"{key}: Calculation started")
    up = drug_data[key]
    up_present = [gene for gene in up if gene in uk65.index]

    # Print counts and summary
    # print(f"Total up genes in signature: {len(up)}")
    # print(f"Up genes found in expression data: {len(up_present)}")

    # Optionally, print the missing ones
    missing_up = set(up) - set(uk65.index)

    # print(f"Missing up genes: {len(missing_up)}")
    scored_data = score(up_gene=up, down_gene=False, sample=uk65,
                    norm_method='theoretical', full_data=True)
    #getting the scored data for a pathway
    total_score = scored_data["total_score"].to_list()[0]
    print(f"{key}: scoring computed")
    permd = permutate(uk65, n_up=len(up_present), n_down=False)
    pvals = empiricalpval(permutations=permd, score=scored_data)
    empirical_p_value = pvals["empirical p value"].to_list()[0]
    print(f"{key}: pvalue calculation completed")
    result = {
    f"{key}":{
        "gene_set_info": {
            "geneset_size": len(up),
            "geneset_covered_in_sample": len(up_present)
        },
        "scores": {
            "total_singscore": total_score
        },
        "statistics": {
            "p_value": empirical_p_value,
            "method": "permutation (empirical)",
            "permutations": 10000
        }}}
    print(f"{key}: Calculation completed")
    final_result.update(result)

# Save final combined JSON
with open("singscore_new_code/Palbociclib/Palbociclib_singscore_results.json", "w", encoding="utf-8") as f:
    json.dump(final_result, f, indent=2, ensure_ascii=False)

Number of items: 502

Calculating pathways:   0%|          | 0/502 [00:00<?, ?it/s]

TNF-alpha Signaling via NF-kB: Calculation started
TNF-alpha Signaling via NF-kB: scoring computed

Calculating pathways:   0%|          | 1/502 [00:05<47:14,  5.66s/it]

TNF-alpha Signaling via NF-kB: pvalue calculation completed
TNF-alpha Signaling via NF-kB: Calculation completed
TGF-beta Signaling: Calculation started
TGF-beta Signaling: scoring computed

Calculating pathways:   0%|          | 2/502 [00:09<39:19,  4.72s/it]

TGF-beta Signaling: pvalue calculation completed
TGF-beta Signaling: Calculation completed
DNA Repair: Calculation started
DNA Repair: scoring computed

Calculating pathways:   1%|          | 3/502 [00:16<47:15,  5.68s/it]

DNA Repair: pvalue calculation completed
DNA Repair: Calculation completed
G2-M Checkpoint: Calculation started
G2-M Checkpoint: scoring computed

Calculating pathways:   1%|          | 4/502 [00:22<46:55,  5.65s/it]

G2-M Checkpoint: pvalue calculation completed
G2-M Checkpoint: Calculation completed
Notch Signaling: Calculation started
Notch Signaling: scoring computed

Calculating pathways:   1%|          | 5/502 [00:25<40:55,  4.94s/it]

Notch Signaling: pvalue calculation completed
Notch Signaling: Calculation completed
Adipogenesis: Calculation started
Adipogenesis: scoring computed

Calculating pathways:   1%|          | 6/502 [00:30<39:32,  4.78s/it]

Adipogenesis: pvalue calculation completed
Adipogenesis: Calculation completed
Estrogen Response Early: Calculation started
Estrogen Response Early: scoring computed

Calculating pathways:   1%|▏         | 7/502 [00:35<41:46,  5.06s/it]

Estrogen Response Early: pvalue calculation completed
Estrogen Response Early: Calculation completed
Estrogen Response Late: Calculation started
Estrogen Response Late: scoring computed

Calculating pathways:   2%|▏         | 8/502 [00:41<43:00,  5.22s/it]

Estrogen Response Late: pvalue calculation completed
Estrogen Response Late: Calculation completed
Androgen Response: Calculation started
Androgen Response: scoring computed

Calculating pathways:   2%|▏         | 9/502 [00:46<41:06,  5.00s/it]

Androgen Response: pvalue calculation completed
Androgen Response: Calculation completed
Hedgehog Signaling: Calculation started
Hedgehog Signaling: scoring computed

Calculating pathways:   2%|▏         | 10/502 [00:49<37:44,  4.60s/it]

Hedgehog Signaling: pvalue calculation completed
Hedgehog Signaling: Calculation completed
PI3K/AKT/mTOR  Signaling: Calculation started
PI3K/AKT/mTOR  Signaling: scoring computed

Calculating pathways:   2%|▏         | 11/502 [00:54<38:01,  4.65s/it]

PI3K/AKT/mTOR  Signaling: pvalue calculation completed
PI3K/AKT/mTOR  Signaling: Calculation completed
E2F Targets: Calculation started
E2F Targets: scoring computed

Calculating pathways:   2%|▏         | 12/502 [01:00<40:45,  4.99s/it]

E2F Targets: pvalue calculation completed
E2F Targets: Calculation completed
Myc Targets V1: Calculation started
Myc Targets V1: scoring computed

Calculating pathways:   3%|▎         | 13/502 [01:06<44:00,  5.40s/it]

Myc Targets V1: pvalue calculation completed
Myc Targets V1: Calculation completed
Myc Targets V2: Calculation started
Myc Targets V2: scoring computed

Calculating pathways:   3%|▎         | 14/502 [01:10<41:23,  5.09s/it]

Myc Targets V2: pvalue calculation completed
Myc Targets V2: Calculation completed
UV Response Up: Calculation started
UV Response Up: scoring computed

Calculating pathways:   3%|▎         | 15/502 [01:16<42:45,  5.27s/it]

UV Response Up: pvalue calculation completed
UV Response Up: Calculation completed
UV Response Dn: Calculation started
UV Response Dn: scoring computed

Calculating pathways:   3%|▎         | 16/502 [01:22<43:22,  5.36s/it]

UV Response Dn: pvalue calculation completed
UV Response Dn: Calculation completed
AGE-RAGE signaling pathway in diabetic complications: Calculation started
AGE-RAGE signaling pathway in diabetic complications: scoring computed

Calculating pathways:   3%|▎         | 17/502 [01:27<42:10,  5.22s/it]

AGE-RAGE signaling pathway in diabetic complications: pvalue calculation completed
AGE-RAGE signaling pathway in diabetic complications: Calculation completed
AMPK signaling pathway: Calculation started
AMPK signaling pathway: scoring computed

Calculating pathways:   4%|▎         | 18/502 [01:32<41:50,  5.19s/it]

AMPK signaling pathway: pvalue calculation completed
AMPK signaling pathway: Calculation completed
Acute myeloid leukemia: Calculation started
Acute myeloid leukemia: scoring computed

Calculating pathways:   4%|▍         | 19/502 [01:36<40:06,  4.98s/it]

Acute myeloid leukemia: pvalue calculation completed
Acute myeloid leukemia: Calculation completed
Apelin signaling pathway: Calculation started
Apelin signaling pathway: scoring computed

Calculating pathways:   4%|▍         | 20/502 [01:42<41:08,  5.12s/it]

Apelin signaling pathway: pvalue calculation completed
Apelin signaling pathway: Calculation completed
Bladder cancer: Calculation started
Bladder cancer: scoring computed

Calculating pathways:   4%|▍         | 21/502 [01:46<38:41,  4.83s/it]

Bladder cancer: pvalue calculation completed
Bladder cancer: Calculation completed
Breast cancer: Calculation started
Breast cancer: scoring computed

Calculating pathways:   4%|▍         | 22/502 [01:51<40:08,  5.02s/it]

Breast cancer: pvalue calculation completed
Breast cancer: Calculation completed
Cell cycle: Calculation started
Cell cycle: scoring computed

Calculating pathways:   5%|▍         | 23/502 [01:57<40:52,  5.12s/it]

Cell cycle: pvalue calculation completed
Cell cycle: Calculation completed
Cellular senescence: Calculation started
Cellular senescence: scoring computed

Calculating pathways:   5%|▍         | 24/502 [02:03<42:35,  5.35s/it]

Cellular senescence: pvalue calculation completed
Cellular senescence: Calculation completed
Central carbon metabolism in cancer: Calculation started
Central carbon metabolism in cancer: scoring computed

Calculating pathways:   5%|▍         | 25/502 [02:07<40:54,  5.15s/it]

Central carbon metabolism in cancer: pvalue calculation completed
Central carbon metabolism in cancer: Calculation completed
Chemical carcinogenesis: Calculation started
Chemical carcinogenesis: scoring computed

Calculating pathways:   5%|▌         | 26/502 [02:13<43:25,  5.47s/it]

Chemical carcinogenesis: pvalue calculation completed
Chemical carcinogenesis: Calculation completed
Chemokine signaling pathway: Calculation started
Chemokine signaling pathway: scoring computed

Calculating pathways:   5%|▌         | 27/502 [02:19<44:13,  5.59s/it]

Chemokine signaling pathway: pvalue calculation completed
Chemokine signaling pathway: Calculation completed
Chronic myeloid leukemia: Calculation started
Chronic myeloid leukemia: scoring computed

Calculating pathways:   6%|▌         | 28/502 [02:24<41:51,  5.30s/it]

Chronic myeloid leukemia: pvalue calculation completed
Chronic myeloid leukemia: Calculation completed
Colorectal cancer: Calculation started
Colorectal cancer: scoring computed

Calculating pathways:   6%|▌         | 29/502 [02:28<39:35,  5.02s/it]

Colorectal cancer: pvalue calculation completed
Colorectal cancer: Calculation completed
Cushing syndrome: Calculation started
Cushing syndrome: scoring computed

Calculating pathways:   6%|▌         | 30/502 [02:33<39:18,  5.00s/it]

Cushing syndrome: pvalue calculation completed
Cushing syndrome: Calculation completed
Endometrial cancer: Calculation started
Endometrial cancer: scoring computed

Calculating pathways:   6%|▌         | 31/502 [02:37<36:57,  4.71s/it]

Endometrial cancer: pvalue calculation completed
Endometrial cancer: Calculation completed
Epstein-Barr virus infection: Calculation started
Epstein-Barr virus infection: scoring computed

Calculating pathways:   6%|▋         | 32/502 [02:43<38:21,  4.90s/it]

Epstein-Barr virus infection: pvalue calculation completed
Epstein-Barr virus infection: Calculation completed
Focal adhesion: Calculation started
Focal adhesion: scoring computed

Calculating pathways:   7%|▋         | 33/502 [02:48<39:51,  5.10s/it]

Focal adhesion: pvalue calculation completed
Focal adhesion: Calculation completed
FoxO signaling pathway: Calculation started
FoxO signaling pathway: scoring computed

Calculating pathways:   7%|▋         | 34/502 [02:53<39:07,  5.02s/it]

FoxO signaling pathway: pvalue calculation completed
FoxO signaling pathway: Calculation completed
Gastric cancer: Calculation started
Gastric cancer: scoring computed

Calculating pathways:   7%|▋         | 35/502 [02:58<38:43,  4.98s/it]

Gastric cancer: pvalue calculation completed
Gastric cancer: Calculation completed
Glioma: Calculation started
Glioma: scoring computed

Calculating pathways:   7%|▋         | 36/502 [03:02<36:56,  4.76s/it]

Glioma: pvalue calculation completed
Glioma: Calculation completed
Hedgehog signaling pathway: Calculation started
Hedgehog signaling pathway: scoring computed

Calculating pathways:   7%|▋         | 37/502 [03:06<35:07,  4.53s/it]

Hedgehog signaling pathway: pvalue calculation completed
Hedgehog signaling pathway: Calculation completed
Hematopoietic cell lineage: Calculation started
Hematopoietic cell lineage: scoring computed

Calculating pathways:   8%|▊         | 38/502 [03:10<34:19,  4.44s/it]

Hematopoietic cell lineage: pvalue calculation completed
Hematopoietic cell lineage: Calculation completed
Hepatitis B: Calculation started
Hepatitis B: scoring computed

Calculating pathways:   8%|▊         | 39/502 [03:15<35:33,  4.61s/it]

Hepatitis B: pvalue calculation completed
Hepatitis B: Calculation completed
Hepatitis C: Calculation started
Hepatitis C: scoring computed

Calculating pathways:   8%|▊         | 40/502 [03:20<36:22,  4.72s/it]

Hepatitis C: pvalue calculation completed
Hepatitis C: Calculation completed
Hepatocellular carcinoma: Calculation started
Hepatocellular carcinoma: scoring computed

Calculating pathways:   8%|▊         | 41/502 [03:25<37:04,  4.83s/it]

Hepatocellular carcinoma: pvalue calculation completed
Hepatocellular carcinoma: Calculation completed
Hippo signaling pathway: Calculation started
Hippo signaling pathway: scoring computed

Calculating pathways:   8%|▊         | 42/502 [03:31<37:48,  4.93s/it]

Hippo signaling pathway: pvalue calculation completed
Hippo signaling pathway: Calculation completed
Human T-cell leukemia virus 1 infection: Calculation started
Human T-cell leukemia virus 1 infection: scoring computed

Calculating pathways:   9%|▊         | 43/502 [03:36<39:28,  5.16s/it]

Human T-cell leukemia virus 1 infection: pvalue calculation completed
Human T-cell leukemia virus 1 infection: Calculation completed
Human cytomegalovirus infection: Calculation started
Human cytomegalovirus infection: scoring computed

Calculating pathways:   9%|▉         | 44/502 [03:42<40:43,  5.34s/it]

Human cytomegalovirus infection: pvalue calculation completed
Human cytomegalovirus infection: Calculation completed
Human papillomavirus infection: Calculation started
Human papillomavirus infection: scoring computed

Calculating pathways:   9%|▉         | 45/502 [03:49<43:39,  5.73s/it]

Human papillomavirus infection: pvalue calculation completed
Human papillomavirus infection: Calculation completed
Influenza A: Calculation started
Influenza A: scoring computed

Calculating pathways:   9%|▉         | 46/502 [03:54<41:46,  5.50s/it]

Influenza A: pvalue calculation completed
Influenza A: Calculation completed
Insulin resistance: Calculation started
Insulin resistance: scoring computed

Calculating pathways:   9%|▉         | 47/502 [03:58<39:34,  5.22s/it]

Insulin resistance: pvalue calculation completed
Insulin resistance: Calculation completed
JAK-STAT signaling pathway: Calculation started
JAK-STAT signaling pathway: scoring computed

Calculating pathways:  10%|▉         | 48/502 [04:03<38:45,  5.12s/it]

JAK-STAT signaling pathway: pvalue calculation completed
JAK-STAT signaling pathway: Calculation completed
Kaposi sarcoma-associated herpesvirus infection: Calculation started
Kaposi sarcoma-associated herpesvirus infection: scoring computed

Calculating pathways:  10%|▉         | 49/502 [04:08<39:00,  5.17s/it]

Kaposi sarcoma-associated herpesvirus infection: pvalue calculation completed
Kaposi sarcoma-associated herpesvirus infection: Calculation completed
Long-term potentiation: Calculation started
Long-term potentiation: scoring computed

Calculating pathways:  10%|▉         | 50/502 [04:13<36:45,  4.88s/it]

Long-term potentiation: pvalue calculation completed
Long-term potentiation: Calculation completed
MAPK signaling pathway: Calculation started
MAPK signaling pathway: scoring computed

Calculating pathways:  10%|█         | 51/502 [04:19<39:55,  5.31s/it]

MAPK signaling pathway: pvalue calculation completed
MAPK signaling pathway: Calculation completed
Measles: Calculation started
Measles: scoring computed

Calculating pathways:  10%|█         | 52/502 [04:24<38:29,  5.13s/it]

Measles: pvalue calculation completed
Measles: Calculation completed
Melanoma: Calculation started
Melanoma: scoring computed

Calculating pathways:  11%|█         | 53/502 [04:28<36:13,  4.84s/it]

Melanoma: pvalue calculation completed
Melanoma: Calculation completed
MicroRNAs in cancer: Calculation started
MicroRNAs in cancer: scoring computed

Calculating pathways:  11%|█         | 54/502 [04:33<37:57,  5.08s/it]

MicroRNAs in cancer: pvalue calculation completed
MicroRNAs in cancer: Calculation completed
Necroptosis: Calculation started
Necroptosis: scoring computed

Calculating pathways:  11%|█         | 55/502 [04:38<37:38,  5.05s/it]

Necroptosis: pvalue calculation completed
Necroptosis: Calculation completed
Neurotrophin signaling pathway: Calculation started
Neurotrophin signaling pathway: scoring computed

Calculating pathways:  11%|█         | 56/502 [04:43<36:22,  4.89s/it]

Neurotrophin signaling pathway: pvalue calculation completed
Neurotrophin signaling pathway: Calculation completed
Non-small cell lung cancer: Calculation started
Non-small cell lung cancer: scoring computed

Calculating pathways:  11%|█▏        | 57/502 [04:47<34:26,  4.64s/it]

Non-small cell lung cancer: pvalue calculation completed
Non-small cell lung cancer: Calculation completed
Oocyte meiosis: Calculation started
Oocyte meiosis: scoring computed

Calculating pathways:  12%|█▏        | 58/502 [04:52<34:47,  4.70s/it]

Oocyte meiosis: pvalue calculation completed
Oocyte meiosis: Calculation completed
Oxytocin signaling pathway: Calculation started
Oxytocin signaling pathway: scoring computed

Calculating pathways:  12%|█▏        | 59/502 [04:57<35:23,  4.79s/it]

Oxytocin signaling pathway: pvalue calculation completed
Oxytocin signaling pathway: Calculation completed
PI3K-Akt signaling pathway: Calculation started
PI3K-Akt signaling pathway: scoring computed

Calculating pathways:  12%|█▏        | 60/502 [05:04<39:58,  5.43s/it]

PI3K-Akt signaling pathway: pvalue calculation completed
PI3K-Akt signaling pathway: Calculation completed
Pancreatic cancer: Calculation started
Pancreatic cancer: scoring computed

Calculating pathways:  12%|█▏        | 61/502 [05:08<37:25,  5.09s/it]

Pancreatic cancer: pvalue calculation completed
Pancreatic cancer: Calculation completed
Pathways in cancer: Calculation started
Pathways in cancer: scoring computed

Calculating pathways:  12%|█▏        | 62/502 [05:17<45:15,  6.17s/it]

Pathways in cancer: pvalue calculation completed
Pathways in cancer: Calculation completed
Primary immunodeficiency: Calculation started
Primary immunodeficiency: scoring computed

Calculating pathways:  13%|█▎        | 63/502 [05:20<39:45,  5.43s/it]

Primary immunodeficiency: pvalue calculation completed
Primary immunodeficiency: Calculation completed
Progesterone-mediated oocyte maturation: Calculation started
Progesterone-mediated oocyte maturation: scoring computed

Calculating pathways:  13%|█▎        | 64/502 [05:25<37:35,  5.15s/it]

Progesterone-mediated oocyte maturation: pvalue calculation completed
Progesterone-mediated oocyte maturation: Calculation completed
Prolactin signaling pathway: Calculation started
Prolactin signaling pathway: scoring computed

Calculating pathways:  13%|█▎        | 65/502 [05:29<35:20,  4.85s/it]

Prolactin signaling pathway: pvalue calculation completed
Prolactin signaling pathway: Calculation completed
Prostate cancer: Calculation started
Prostate cancer: scoring computed

Calculating pathways:  13%|█▎        | 66/502 [05:34<34:30,  4.75s/it]

Prostate cancer: pvalue calculation completed
Prostate cancer: Calculation completed
Proteoglycans in cancer: Calculation started
Proteoglycans in cancer: scoring computed

Calculating pathways:  13%|█▎        | 67/502 [05:39<36:02,  4.97s/it]

Proteoglycans in cancer: pvalue calculation completed
Proteoglycans in cancer: Calculation completed
Ras signaling pathway: Calculation started
Ras signaling pathway: scoring computed

Calculating pathways:  14%|█▎        | 68/502 [05:45<37:14,  5.15s/it]

Ras signaling pathway: pvalue calculation completed
Ras signaling pathway: Calculation completed
Signaling pathways regulating pluripotency of stem cells: Calculation started
Signaling pathways regulating pluripotency of stem cells: scoring computed

Calculating pathways:  14%|█▎        | 69/502 [05:50<36:39,  5.08s/it]

Signaling pathways regulating pluripotency of stem cells: pvalue calculation completed
Signaling pathways regulating pluripotency of stem cells: Calculation completed
Small cell lung cancer: Calculation started
Small cell lung cancer: scoring computed

Calculating pathways:  14%|█▍        | 70/502 [05:54<34:58,  4.86s/it]

Small cell lung cancer: pvalue calculation completed
Small cell lung cancer: Calculation completed
T cell receptor signaling pathway: Calculation started
T cell receptor signaling pathway: scoring computed

Calculating pathways:  14%|█▍        | 71/502 [05:58<34:04,  4.74s/it]

T cell receptor signaling pathway: pvalue calculation completed
T cell receptor signaling pathway: Calculation completed
Th1 and Th2 cell differentiation: Calculation started
Th1 and Th2 cell differentiation: scoring computed

Calculating pathways:  14%|█▍        | 72/502 [06:03<33:04,  4.61s/it]

Th1 and Th2 cell differentiation: pvalue calculation completed
Th1 and Th2 cell differentiation: Calculation completed
Th17 cell differentiation: Calculation started
Th17 cell differentiation: scoring computed

Calculating pathways:  15%|█▍        | 73/502 [06:07<32:31,  4.55s/it]

Th17 cell differentiation: pvalue calculation completed
Th17 cell differentiation: Calculation completed
Thermogenesis: Calculation started
Thermogenesis: scoring computed

Calculating pathways:  15%|█▍        | 74/502 [06:13<34:37,  4.85s/it]

Thermogenesis: pvalue calculation completed
Thermogenesis: Calculation completed
Thyroid cancer: Calculation started
Thyroid cancer: scoring computed

Calculating pathways:  15%|█▍        | 75/502 [06:16<32:08,  4.52s/it]

Thyroid cancer: pvalue calculation completed
Thyroid cancer: Calculation completed
Thyroid hormone signaling pathway: Calculation started
Thyroid hormone signaling pathway: scoring computed

Calculating pathways:  15%|█▌        | 76/502 [06:21<32:01,  4.51s/it]

Thyroid hormone signaling pathway: pvalue calculation completed
Thyroid hormone signaling pathway: Calculation completed
Tight junction: Calculation started
Tight junction: scoring computed

Calculating pathways:  15%|█▌        | 77/502 [06:26<33:34,  4.74s/it]

Tight junction: pvalue calculation completed
Tight junction: Calculation completed
Transcriptional misregulation in cancer: Calculation started
Transcriptional misregulation in cancer: scoring computed

Calculating pathways:  16%|█▌        | 78/502 [06:32<34:52,  4.93s/it]

Transcriptional misregulation in cancer: pvalue calculation completed
Transcriptional misregulation in cancer: Calculation completed
Viral carcinogenesis: Calculation started
Viral carcinogenesis: scoring computed

Calculating pathways:  16%|█▌        | 79/502 [06:37<35:41,  5.06s/it]

Viral carcinogenesis: pvalue calculation completed
Viral carcinogenesis: Calculation completed
Viral myocarditis: Calculation started
Viral myocarditis: scoring computed

Calculating pathways:  16%|█▌        | 80/502 [06:41<33:06,  4.71s/it]

Viral myocarditis: pvalue calculation completed
Viral myocarditis: Calculation completed
Wnt signaling pathway: Calculation started
Wnt signaling pathway: scoring computed

Calculating pathways:  16%|█▌        | 81/502 [06:46<33:16,  4.74s/it]

Wnt signaling pathway: pvalue calculation completed
Wnt signaling pathway: Calculation completed
Yersinia infection: Calculation started
Yersinia infection: scoring computed

Calculating pathways:  16%|█▋        | 82/502 [06:50<33:01,  4.72s/it]

Yersinia infection: pvalue calculation completed
Yersinia infection: Calculation completed
mTOR signaling pathway: Calculation started
mTOR signaling pathway: scoring computed

Calculating pathways:  17%|█▋        | 83/502 [06:55<33:06,  4.74s/it]

mTOR signaling pathway: pvalue calculation completed
mTOR signaling pathway: Calculation completed
p53 signaling pathway: Calculation started
p53 signaling pathway: scoring computed

Calculating pathways:  17%|█▋        | 84/502 [06:59<31:33,  4.53s/it]

p53 signaling pathway: pvalue calculation completed
p53 signaling pathway: Calculation completed
APC C-mediated Degradation of Cell Cycle Proteins: Calculation started
APC C-mediated Degradation of Cell Cycle Proteins: scoring computed

Calculating pathways:  17%|█▋        | 85/502 [07:03<30:43,  4.42s/it]

APC C-mediated Degradation of Cell Cycle Proteins: pvalue calculation completed
APC C-mediated Degradation of Cell Cycle Proteins: Calculation completed
APC C Cdc20 Mediated Degradation of Mitotic Proteins: Calculation started
APC C Cdc20 Mediated Degradation of Mitotic Proteins: scoring computed

Calculating pathways:  17%|█▋        | 86/502 [07:07<29:34,  4.26s/it]

APC C Cdc20 Mediated Degradation of Mitotic Proteins: pvalue calculation completed
APC C Cdc20 Mediated Degradation of Mitotic Proteins: Calculation completed
APC Cdc20 Mediated Degradation of Cell Cycle Proteins Prior to Satisfation of the Checkpoint: Calculation started
APC Cdc20 Mediated Degradation of Cell Cycle Proteins Prior to Satisfation of the Checkpoint: scoring computed

Calculating pathways:  17%|█▋        | 87/502 [07:11<28:47,  4.16s/it]

APC Cdc20 Mediated Degradation of Cell Cycle Proteins Prior to Satisfation of the Checkpoint: pvalue calculation completed
APC Cdc20 Mediated Degradation of Cell Cycle Proteins Prior to Satisfation of the Checkpoint: Calculation completed
Aberrant Regulation of Mitotic G1 S Transition in Cancer Due to RB1 Defects: Calculation started
Aberrant Regulation of Mitotic G1 S Transition in Cancer Due to RB1 Defects: scoring computed

Calculating pathways:  18%|█▊        | 88/502 [07:15<27:11,  3.94s/it]

Aberrant Regulation of Mitotic G1 S Transition in Cancer Due to RB1 Defects: pvalue calculation completed
Aberrant Regulation of Mitotic G1 S Transition in Cancer Due to RB1 Defects: Calculation completed
Aberrant Regulation of Mitotic Cell Cycle Due to RB1 Defects: Calculation started
Aberrant Regulation of Mitotic Cell Cycle Due to RB1 Defects: scoring computed

Calculating pathways:  18%|█▊        | 89/502 [07:18<26:35,  3.86s/it]

Aberrant Regulation of Mitotic Cell Cycle Due to RB1 Defects: pvalue calculation completed
Aberrant Regulation of Mitotic Cell Cycle Due to RB1 Defects: Calculation completed
Activation of APC C and APC C Cdc20 Mediated Degradation of Mitotic Proteins: Calculation started
Activation of APC C and APC C Cdc20 Mediated Degradation of Mitotic Proteins: scoring computed

Calculating pathways:  18%|█▊        | 90/502 [07:22<26:51,  3.91s/it]

Activation of APC C and APC C Cdc20 Mediated Degradation of Mitotic Proteins: pvalue calculation completed
Activation of APC C and APC C Cdc20 Mediated Degradation of Mitotic Proteins: Calculation completed
Activation of ATR in Response to Replication Stress: Calculation started
Activation of ATR in Response to Replication Stress: scoring computed

Calculating pathways:  18%|█▊        | 91/502 [07:26<26:55,  3.93s/it]

Activation of ATR in Response to Replication Stress: pvalue calculation completed
Activation of ATR in Response to Replication Stress: Calculation completed
Activation of NMDA Receptors and Postsynaptic Events: Calculation started
Activation of NMDA Receptors and Postsynaptic Events: scoring computed

Calculating pathways:  18%|█▊        | 92/502 [07:31<27:42,  4.05s/it]

Activation of NMDA Receptors and Postsynaptic Events: pvalue calculation completed
Activation of NMDA Receptors and Postsynaptic Events: Calculation completed
Activation of the Pre-Replicative Complex: Calculation started
Activation of the Pre-Replicative Complex: scoring computed

Calculating pathways:  19%|█▊        | 93/502 [07:34<26:46,  3.93s/it]

Activation of the Pre-Replicative Complex: pvalue calculation completed
Activation of the Pre-Replicative Complex: Calculation completed
Axon Guidance: Calculation started
Axon Guidance: scoring computed

Calculating pathways:  19%|█▊        | 94/502 [07:43<37:03,  5.45s/it]

Axon Guidance: pvalue calculation completed
Axon Guidance: Calculation completed
CDK-mediated Phosphorylation and Removal of Cdc6: Calculation started
CDK-mediated Phosphorylation and Removal of Cdc6: scoring computed

Calculating pathways:  19%|█▉        | 95/502 [07:47<34:18,  5.06s/it]

CDK-mediated Phosphorylation and Removal of Cdc6: pvalue calculation completed
CDK-mediated Phosphorylation and Removal of Cdc6: Calculation completed
CREB Phosphorylation: Calculation started
CREB Phosphorylation: scoring computed

Calculating pathways:  19%|█▉        | 96/502 [07:51<30:51,  4.56s/it]

CREB Phosphorylation: pvalue calculation completed
CREB Phosphorylation: Calculation completed
CREB1 Phosphorylation Through NMDA Receptor-Mediated Activation of RAS Signaling: Calculation started
CREB1 Phosphorylation Through NMDA Receptor-Mediated Activation of RAS Signaling: scoring computed

Calculating pathways:  19%|█▉        | 97/502 [07:54<28:54,  4.28s/it]

CREB1 Phosphorylation Through NMDA Receptor-Mediated Activation of RAS Signaling: pvalue calculation completed
CREB1 Phosphorylation Through NMDA Receptor-Mediated Activation of RAS Signaling: Calculation completed
Cdc20 Phospho-APC C Mediated Degradation of Cyclin A: Calculation started
Cdc20 Phospho-APC C Mediated Degradation of Cyclin A: scoring computed

Calculating pathways:  20%|█▉        | 98/502 [07:58<28:11,  4.19s/it]

Cdc20 Phospho-APC C Mediated Degradation of Cyclin A: pvalue calculation completed
Cdc20 Phospho-APC C Mediated Degradation of Cyclin A: Calculation completed
Cell Cycle: Calculation started
Cell Cycle: scoring computed

Calculating pathways:  20%|█▉        | 99/502 [08:09<40:36,  6.05s/it]

Cell Cycle: pvalue calculation completed
Cell Cycle: Calculation completed
Cell Cycle Checkpoints: Calculation started
Cell Cycle Checkpoints: scoring computed

Calculating pathways:  20%|█▉        | 100/502 [08:15<40:51,  6.10s/it]

Cell Cycle Checkpoints: pvalue calculation completed
Cell Cycle Checkpoints: Calculation completed
Cell Cycle, Mitotic: Calculation started
Cell Cycle, Mitotic: scoring computed

Calculating pathways:  20%|██        | 101/502 [08:24<46:41,  6.99s/it]

Cell Cycle, Mitotic: pvalue calculation completed
Cell Cycle, Mitotic: Calculation completed
Cellular Senescence: Calculation started
Cellular Senescence: scoring computed

Calculating pathways:  20%|██        | 102/502 [08:29<42:51,  6.43s/it]

Cellular Senescence: pvalue calculation completed
Cellular Senescence: Calculation completed
Cellular Responses to Stimuli: Calculation started
Cellular Responses to Stimuli: scoring computed

Calculating pathways:  21%|██        | 103/502 [08:41<54:18,  8.17s/it]

Cellular Responses to Stimuli: pvalue calculation completed
Cellular Responses to Stimuli: Calculation completed
Cellular Responses to Stress: Calculation started
Cellular Responses to Stress: scoring computed

Calculating pathways:  21%|██        | 104/502 [08:53<1:00:49,  9.17s/it]

Cellular Responses to Stress: pvalue calculation completed
Cellular Responses to Stress: Calculation completed
Chromatin Modifying Enzymes: Calculation started
Chromatin Modifying Enzymes: scoring computed

Calculating pathways:  21%|██        | 105/502 [08:59<54:13,  8.20s/it]

Chromatin Modifying Enzymes: pvalue calculation completed
Chromatin Modifying Enzymes: Calculation completed
Chromatin Organization: Calculation started
Chromatin Organization: scoring computed

Calculating pathways:  21%|██        | 106/502 [09:05<49:14,  7.46s/it]

Chromatin Organization: pvalue calculation completed
Chromatin Organization: Calculation completed
Chromosome Maintenance: Calculation started
Chromosome Maintenance: scoring computed

Calculating pathways:  21%|██▏       | 107/502 [09:09<43:17,  6.58s/it]

Chromosome Maintenance: pvalue calculation completed
Chromosome Maintenance: Calculation completed
Constitutive Signaling by Aberrant PI3K in Cancer: Calculation started
Constitutive Signaling by Aberrant PI3K in Cancer: scoring computed

Calculating pathways:  22%|██▏       | 108/502 [09:13<38:17,  5.83s/it]

Constitutive Signaling by Aberrant PI3K in Cancer: pvalue calculation completed
Constitutive Signaling by Aberrant PI3K in Cancer: Calculation completed
Cyclin A B1 B2 Associated Events During G2 M Transition: Calculation started
Cyclin A B1 B2 Associated Events During G2 M Transition: scoring computed

Calculating pathways:  22%|██▏       | 109/502 [09:17<33:48,  5.16s/it]

Cyclin A B1 B2 Associated Events During G2 M Transition: pvalue calculation completed
Cyclin A B1 B2 Associated Events During G2 M Transition: Calculation completed
Cyclin A Cdk2-associated Events at S Phase Entry: Calculation started
Cyclin A Cdk2-associated Events at S Phase Entry: scoring computed

Calculating pathways:  22%|██▏       | 110/502 [09:21<31:45,  4.86s/it]

Cyclin A Cdk2-associated Events at S Phase Entry: pvalue calculation completed
Cyclin A Cdk2-associated Events at S Phase Entry: Calculation completed
Cyclin D Associated Events in G1: Calculation started
Cyclin D Associated Events in G1: scoring computed

Calculating pathways:  22%|██▏       | 111/502 [09:25<29:38,  4.55s/it]

Cyclin D Associated Events in G1: pvalue calculation completed
Cyclin D Associated Events in G1: Calculation completed
Cyclin E Associated Events During G1 S Transition: Calculation started
Cyclin E Associated Events During G1 S Transition: scoring computed

Calculating pathways:  22%|██▏       | 112/502 [09:29<29:01,  4.47s/it]

Cyclin E Associated Events During G1 S Transition: pvalue calculation completed
Cyclin E Associated Events During G1 S Transition: Calculation completed
Cytokine Signaling in Immune System: Calculation started
Cytokine Signaling in Immune System: scoring computed

Calculating pathways:  23%|██▎       | 113/502 [09:40<41:49,  6.45s/it]

Cytokine Signaling in Immune System: pvalue calculation completed
Cytokine Signaling in Immune System: Calculation completed
DNA Damage Telomere Stress Induced Senescence: Calculation started
DNA Damage Telomere Stress Induced Senescence: scoring computed

Calculating pathways:  23%|██▎       | 114/502 [09:44<36:41,  5.67s/it]

DNA Damage Telomere Stress Induced Senescence: pvalue calculation completed
DNA Damage Telomere Stress Induced Senescence: Calculation completed
DNA Double-Strand Break Repair: Calculation started
DNA Double-Strand Break Repair: scoring computed

Calculating pathways:  23%|██▎       | 115/502 [09:49<34:58,  5.42s/it]

DNA Double-Strand Break Repair: pvalue calculation completed
DNA Double-Strand Break Repair: Calculation completed
DNA Replication: Calculation started
DNA Replication: scoring computed

Calculating pathways:  23%|██▎       | 116/502 [09:54<33:34,  5.22s/it]

DNA Replication: pvalue calculation completed
DNA Replication: Calculation completed
DNA Replication Pre-Initiation: Calculation started
DNA Replication Pre-Initiation: scoring computed

Calculating pathways:  23%|██▎       | 117/502 [09:58<32:05,  5.00s/it]

DNA Replication Pre-Initiation: pvalue calculation completed
DNA Replication Pre-Initiation: Calculation completed
Defective Binding of RB1 Mutants to E2F1,(E2F2, E2F3): Calculation started
Defective Binding of RB1 Mutants to E2F1,(E2F2, E2F3): scoring computed

Calculating pathways:  24%|██▎       | 118/502 [10:02<29:17,  4.58s/it]

Defective Binding of RB1 Mutants to E2F1,(E2F2, E2F3): pvalue calculation completed
Defective Binding of RB1 Mutants to E2F1,(E2F2, E2F3): Calculation completed
Deubiquitination: Calculation started
Deubiquitination: scoring computed

Calculating pathways:  24%|██▎       | 119/502 [10:08<31:54,  5.00s/it]

Deubiquitination: pvalue calculation completed
Deubiquitination: Calculation completed
Developmental Biology: Calculation started
Developmental Biology: scoring computed

Calculating pathways:  24%|██▍       | 120/502 [10:22<50:18,  7.90s/it]

Developmental Biology: pvalue calculation completed
Developmental Biology: Calculation completed
Diseases of Mitotic Cell Cycle: Calculation started
Diseases of Mitotic Cell Cycle: scoring computed

Calculating pathways:  24%|██▍       | 121/502 [10:26<42:20,  6.67s/it]

Diseases of Mitotic Cell Cycle: pvalue calculation completed
Diseases of Mitotic Cell Cycle: Calculation completed
Diseases of Signal Transduction by Growth Factor Receptors and Second Messengers: Calculation started
Diseases of Signal Transduction by Growth Factor Receptors and Second Messengers: scoring computed

Calculating pathways:  24%|██▍       | 122/502 [10:34<45:12,  7.14s/it]

Diseases of Signal Transduction by Growth Factor Receptors and Second Messengers: pvalue calculation completed
Diseases of Signal Transduction by Growth Factor Receptors and Second Messengers: Calculation completed
Drug-mediated Inhibition of CDK4 CDK6 Activity: Calculation started
Drug-mediated Inhibition of CDK4 CDK6 Activity: scoring computed

Calculating pathways:  25%|██▍       | 123/502 [10:38<38:02,  6.02s/it]

Drug-mediated Inhibition of CDK4 CDK6 Activity: pvalue calculation completed
Drug-mediated Inhibition of CDK4 CDK6 Activity: Calculation completed
ERK MAPK Targets: Calculation started
ERK MAPK Targets: scoring computed

Calculating pathways:  25%|██▍       | 124/502 [10:41<33:13,  5.27s/it]

ERK MAPK Targets: pvalue calculation completed
ERK MAPK Targets: Calculation completed
ESR-mediated Signaling: Calculation started
ESR-mediated Signaling: scoring computed

Calculating pathways:  25%|██▍       | 125/502 [10:46<32:52,  5.23s/it]

ESR-mediated Signaling: pvalue calculation completed
ESR-mediated Signaling: Calculation completed
Estrogen-dependent Gene Expression: Calculation started
Estrogen-dependent Gene Expression: scoring computed

Calculating pathways:  25%|██▌       | 126/502 [10:51<31:33,  5.04s/it]

Estrogen-dependent Gene Expression: pvalue calculation completed
Estrogen-dependent Gene Expression: Calculation completed
Estrogen-dependent Nuclear Events Downstream of ESR-membrane Signaling: Calculation started
Estrogen-dependent Nuclear Events Downstream of ESR-membrane Signaling: scoring computed

Calculating pathways:  25%|██▌       | 127/502 [10:55<28:46,  4.60s/it]

Estrogen-dependent Nuclear Events Downstream of ESR-membrane Signaling: pvalue calculation completed
Estrogen-dependent Nuclear Events Downstream of ESR-membrane Signaling: Calculation completed
Extension of Telomeres: Calculation started
Extension of Telomeres: scoring computed

Calculating pathways:  25%|██▌       | 128/502 [10:59<27:46,  4.46s/it]

Extension of Telomeres: pvalue calculation completed
Extension of Telomeres: Calculation completed
Extra-nuclear Estrogen Signaling: Calculation started
Extra-nuclear Estrogen Signaling: scoring computed

Calculating pathways:  26%|██▌       | 129/502 [11:03<27:16,  4.39s/it]

Extra-nuclear Estrogen Signaling: pvalue calculation completed
Extra-nuclear Estrogen Signaling: Calculation completed
FLT3 Signaling: Calculation started
FLT3 Signaling: scoring computed

Calculating pathways:  26%|██▌       | 130/502 [11:07<25:56,  4.18s/it]

FLT3 Signaling: pvalue calculation completed
FLT3 Signaling: Calculation completed
FLT3 Signaling by CBL Mutants: Calculation started
FLT3 Signaling by CBL Mutants: scoring computed

Calculating pathways:  26%|██▌       | 131/502 [11:10<24:27,  3.96s/it]

FLT3 Signaling by CBL Mutants: pvalue calculation completed
FLT3 Signaling by CBL Mutants: Calculation completed
FLT3 Signaling in Disease: Calculation started
FLT3 Signaling in Disease: scoring computed

Calculating pathways:  26%|██▋       | 132/502 [11:14<23:43,  3.85s/it]

FLT3 Signaling in Disease: pvalue calculation completed
FLT3 Signaling in Disease: Calculation completed
FLT3 Signaling Through SRC Family Kinases: Calculation started
FLT3 Signaling Through SRC Family Kinases: scoring computed

Calculating pathways:  26%|██▋       | 133/502 [11:17<22:46,  3.70s/it]

FLT3 Signaling Through SRC Family Kinases: pvalue calculation completed
FLT3 Signaling Through SRC Family Kinases: Calculation completed
Factors Involved in Megakaryocyte Development and Platelet Production: Calculation started
Factors Involved in Megakaryocyte Development and Platelet Production: scoring computed

Calculating pathways:  27%|██▋       | 134/502 [11:22<24:44,  4.03s/it]

Factors Involved in Megakaryocyte Development and Platelet Production: pvalue calculation completed
Factors Involved in Megakaryocyte Development and Platelet Production: Calculation completed
Formation of HIV Elongation Complex in the Absence of HIV Tat: Calculation started
Formation of HIV Elongation Complex in the Absence of HIV Tat: scoring computed

Calculating pathways:  27%|██▋       | 135/502 [11:26<24:25,  3.99s/it]

Formation of HIV Elongation Complex in the Absence of HIV Tat: pvalue calculation completed
Formation of HIV Elongation Complex in the Absence of HIV Tat: Calculation completed
Formation of HIV-1 Elongation Complex Containing HIV-1 Tat: Calculation started
Formation of HIV-1 Elongation Complex Containing HIV-1 Tat: scoring computed

Calculating pathways:  27%|██▋       | 136/502 [11:29<23:58,  3.93s/it]

Formation of HIV-1 Elongation Complex Containing HIV-1 Tat: pvalue calculation completed
Formation of HIV-1 Elongation Complex Containing HIV-1 Tat: Calculation completed
Formation of RNA Pol II Elongation Complex: Calculation started
Formation of RNA Pol II Elongation Complex: scoring computed

Calculating pathways:  27%|██▋       | 137/502 [11:33<24:08,  3.97s/it]

Formation of RNA Pol II Elongation Complex: pvalue calculation completed
Formation of RNA Pol II Elongation Complex: Calculation completed
G Alpha (Q) Signalling Events: Calculation started
G Alpha (Q) Signalling Events: scoring computed

Calculating pathways:  27%|██▋       | 138/502 [11:39<26:37,  4.39s/it]

G Alpha (Q) Signalling Events: pvalue calculation completed
G Alpha (Q) Signalling Events: Calculation completed
G0 and Early G1: Calculation started
G0 and Early G1: scoring computed

Calculating pathways:  28%|██▊       | 139/502 [11:43<25:14,  4.17s/it]

G0 and Early G1: pvalue calculation completed
G0 and Early G1: Calculation completed
G1 Phase: Calculation started
G1 Phase: scoring computed

Calculating pathways:  28%|██▊       | 140/502 [11:46<24:39,  4.09s/it]

G1 Phase: pvalue calculation completed
G1 Phase: Calculation completed
G1 S DNA Damage Checkpoints: Calculation started
G1 S DNA Damage Checkpoints: scoring computed

Calculating pathways:  28%|██▊       | 141/502 [11:50<24:13,  4.03s/it]

G1 S DNA Damage Checkpoints: pvalue calculation completed
G1 S DNA Damage Checkpoints: Calculation completed
G1 S Transition: Calculation started
G1 S Transition: scoring computed

Calculating pathways:  28%|██▊       | 142/502 [11:55<25:37,  4.27s/it]

G1 S Transition: pvalue calculation completed
G1 S Transition: Calculation completed
G2 Phase: Calculation started
G2 Phase: scoring computed

Calculating pathways:  28%|██▊       | 143/502 [11:58<23:47,  3.98s/it]

G2 Phase: pvalue calculation completed
G2 Phase: Calculation completed
G2 M Checkpoints: Calculation started
G2 M Checkpoints: scoring computed

Calculating pathways:  29%|██▊       | 144/502 [12:03<25:28,  4.27s/it]

G2 M Checkpoints: pvalue calculation completed
G2 M Checkpoints: Calculation completed
G2 M Transition: Calculation started
G2 M Transition: scoring computed

Calculating pathways:  29%|██▉       | 145/502 [12:09<27:20,  4.59s/it]

G2 M Transition: pvalue calculation completed
G2 M Transition: Calculation completed
GPCR Downstream Signalling: Calculation started
GPCR Downstream Signalling: scoring computed

Calculating pathways:  29%|██▉       | 146/502 [12:18<34:45,  5.86s/it]

GPCR Downstream Signalling: pvalue calculation completed
GPCR Downstream Signalling: Calculation completed
Gastrin-CREB Signalling Pathway via PKC and MAPK: Calculation started
Gastrin-CREB Signalling Pathway via PKC and MAPK: scoring computed

Calculating pathways:  29%|██▉       | 147/502 [12:21<30:54,  5.23s/it]

Gastrin-CREB Signalling Pathway via PKC and MAPK: pvalue calculation completed
Gastrin-CREB Signalling Pathway via PKC and MAPK: Calculation completed
Gene Expression (Transcription): Calculation started
Gene Expression (Transcription): scoring computed

Calculating pathways:  29%|██▉       | 148/502 [12:41<55:36,  9.43s/it]

Gene Expression (Transcription): pvalue calculation completed
Gene Expression (Transcription): Calculation completed
Generic Transcription Pathway: Calculation started
Generic Transcription Pathway: scoring computed

Calculating pathways:  30%|██▉       | 149/502 [12:56<1:06:23, 11.29s/it]

Generic Transcription Pathway: pvalue calculation completed
Generic Transcription Pathway: Calculation completed
HDR Through Homologous Recombination (HRR) or Single Strand Annealing (SSA): Calculation started
HDR Through Homologous Recombination (HRR) or Single Strand Annealing (SSA): scoring computed

Calculating pathways:  30%|██▉       | 150/502 [13:01<54:07,  9.23s/it]

HDR Through Homologous Recombination (HRR) or Single Strand Annealing (SSA): pvalue calculation completed
HDR Through Homologous Recombination (HRR) or Single Strand Annealing (SSA): Calculation completed
HIV Infection: Calculation started
HIV Infection: scoring computed

Calculating pathways:  30%|███       | 151/502 [13:06<47:41,  8.15s/it]

HIV Infection: pvalue calculation completed
HIV Infection: Calculation completed
HIV Life Cycle: Calculation started
HIV Life Cycle: scoring computed

Calculating pathways:  30%|███       | 152/502 [13:11<41:53,  7.18s/it]

HIV Life Cycle: pvalue calculation completed
HIV Life Cycle: Calculation completed
HIV Transcription Elongation: Calculation started
HIV Transcription Elongation: scoring computed

Calculating pathways:  30%|███       | 153/502 [13:15<36:03,  6.20s/it]

HIV Transcription Elongation: pvalue calculation completed
HIV Transcription Elongation: Calculation completed
HIV Elongation Arrest and Recovery: Calculation started
HIV Elongation Arrest and Recovery: scoring computed

Calculating pathways:  31%|███       | 154/502 [13:19<31:35,  5.45s/it]

HIV Elongation Arrest and Recovery: pvalue calculation completed
HIV Elongation Arrest and Recovery: Calculation completed
Hemostasis: Calculation started
Hemostasis: scoring computed

Calculating pathways:  31%|███       | 155/502 [13:28<38:55,  6.73s/it]

Hemostasis: pvalue calculation completed
Hemostasis: Calculation completed
Homology Directed Repair: Calculation started
Homology Directed Repair: scoring computed

Calculating pathways:  31%|███       | 156/502 [13:33<35:29,  6.15s/it]

Homology Directed Repair: pvalue calculation completed
Homology Directed Repair: Calculation completed
Host Interactions of HIV Factors: Calculation started
Host Interactions of HIV Factors: scoring computed

Calculating pathways:  31%|███▏      | 157/502 [13:38<33:42,  5.86s/it]

Host Interactions of HIV Factors: pvalue calculation completed
Host Interactions of HIV Factors: Calculation completed
IGF1R Signaling Cascade: Calculation started
IGF1R Signaling Cascade: scoring computed

Calculating pathways:  31%|███▏      | 158/502 [13:43<30:47,  5.37s/it]

IGF1R Signaling Cascade: pvalue calculation completed
IGF1R Signaling Cascade: Calculation completed
IRS-mediated Signalling: Calculation started
IRS-mediated Signalling: scoring computed

Calculating pathways:  32%|███▏      | 159/502 [13:47<28:05,  4.91s/it]

IRS-mediated Signalling: pvalue calculation completed
IRS-mediated Signalling: Calculation completed
IRS-related Events Triggered by IGF1R: Calculation started
IRS-related Events Triggered by IGF1R: scoring computed

Calculating pathways:  32%|███▏      | 160/502 [13:50<26:12,  4.60s/it]

IRS-related Events Triggered by IGF1R: pvalue calculation completed
IRS-related Events Triggered by IGF1R: Calculation completed
Infectious Disease: Calculation started
Infectious Disease: scoring computed

Calculating pathways:  32%|███▏      | 161/502 [14:05<42:57,  7.56s/it]

Infectious Disease: pvalue calculation completed
Infectious Disease: Calculation completed
Innate Immune System: Calculation started
Innate Immune System: scoring computed

Calculating pathways:  32%|███▏      | 162/502 [14:19<54:14,  9.57s/it]

Innate Immune System: pvalue calculation completed
Innate Immune System: Calculation completed
Insulin Receptor Signalling Cascade: Calculation started
Insulin Receptor Signalling Cascade: scoring computed

Calculating pathways:  32%|███▏      | 163/502 [14:23<44:55,  7.95s/it]

Insulin Receptor Signalling Cascade: pvalue calculation completed
Insulin Receptor Signalling Cascade: Calculation completed
Interleukin Receptor SHC Signaling: Calculation started
Interleukin Receptor SHC Signaling: scoring computed

Calculating pathways:  33%|███▎      | 164/502 [14:27<37:43,  6.70s/it]

Interleukin Receptor SHC Signaling: pvalue calculation completed
Interleukin Receptor SHC Signaling: Calculation completed
Interleukin-15 Signaling: Calculation started
Interleukin-15 Signaling: scoring computed

Calculating pathways:  33%|███▎      | 165/502 [14:31<32:18,  5.75s/it]

Interleukin-15 Signaling: pvalue calculation completed
Interleukin-15 Signaling: Calculation completed
Interleukin-17 Signaling: Calculation started
Interleukin-17 Signaling: scoring computed

Calculating pathways:  33%|███▎      | 166/502 [14:35<29:44,  5.31s/it]

Interleukin-17 Signaling: pvalue calculation completed
Interleukin-17 Signaling: Calculation completed
Interleukin-2 Family Signaling: Calculation started
Interleukin-2 Family Signaling: scoring computed

Calculating pathways:  33%|███▎      | 167/502 [14:39<27:12,  4.87s/it]

Interleukin-2 Family Signaling: pvalue calculation completed
Interleukin-2 Family Signaling: Calculation completed
Interleukin-2 Signaling: Calculation started
Interleukin-2 Signaling: scoring computed

Calculating pathways:  33%|███▎      | 168/502 [14:42<25:07,  4.51s/it]

Interleukin-2 Signaling: pvalue calculation completed
Interleukin-2 Signaling: Calculation completed
Interleukin-20 Family Signaling: Calculation started
Interleukin-20 Family Signaling: scoring computed

Calculating pathways:  34%|███▎      | 169/502 [14:46<23:54,  4.31s/it]

Interleukin-20 Family Signaling: pvalue calculation completed
Interleukin-20 Family Signaling: Calculation completed
Interleukin-21 Signaling: Calculation started
Interleukin-21 Signaling: scoring computed

Calculating pathways:  34%|███▍      | 170/502 [14:50<22:29,  4.07s/it]

Interleukin-21 Signaling: pvalue calculation completed
Interleukin-21 Signaling: Calculation completed
Interleukin-3, Interleukin-5 and GM-CSF Signaling: Calculation started
Interleukin-3, Interleukin-5 and GM-CSF Signaling: scoring computed

Calculating pathways:  34%|███▍      | 171/502 [14:54<22:20,  4.05s/it]

Interleukin-3, Interleukin-5 and GM-CSF Signaling: pvalue calculation completed
Interleukin-3, Interleukin-5 and GM-CSF Signaling: Calculation completed
Interleukin-4 and Interleukin-13 Signaling: Calculation started
Interleukin-4 and Interleukin-13 Signaling: scoring computed

Calculating pathways:  34%|███▍      | 172/502 [14:59<23:32,  4.28s/it]

Interleukin-4 and Interleukin-13 Signaling: pvalue calculation completed
Interleukin-4 and Interleukin-13 Signaling: Calculation completed
Interleukin-7 Signaling: Calculation started
Interleukin-7 Signaling: scoring computed

Calculating pathways:  34%|███▍      | 173/502 [15:02<22:34,  4.12s/it]

Interleukin-7 Signaling: pvalue calculation completed
Interleukin-7 Signaling: Calculation completed
Interleukin-9 Signaling: Calculation started
Interleukin-9 Signaling: scoring computed

Calculating pathways:  35%|███▍      | 174/502 [15:06<21:44,  3.98s/it]

Interleukin-9 Signaling: pvalue calculation completed
Interleukin-9 Signaling: Calculation completed
Intracellular Signaling by Second Messengers: Calculation started
Intracellular Signaling by Second Messengers: scoring computed

Calculating pathways:  35%|███▍      | 175/502 [15:13<26:43,  4.90s/it]

Intracellular Signaling by Second Messengers: pvalue calculation completed
Intracellular Signaling by Second Messengers: Calculation completed
L1CAM Interactions: Calculation started
L1CAM Interactions: scoring computed

Calculating pathways:  35%|███▌      | 176/502 [15:18<26:45,  4.92s/it]

L1CAM Interactions: pvalue calculation completed
L1CAM Interactions: Calculation completed
Late Phase of HIV Life Cycle: Calculation started
Late Phase of HIV Life Cycle: scoring computed

Calculating pathways:  35%|███▌      | 177/502 [15:23<27:13,  5.03s/it]

Late Phase of HIV Life Cycle: pvalue calculation completed
Late Phase of HIV Life Cycle: Calculation completed
MAP Kinase Activation: Calculation started
MAP Kinase Activation: scoring computed

Calculating pathways:  35%|███▌      | 178/502 [15:28<25:54,  4.80s/it]

MAP Kinase Activation: pvalue calculation completed
MAP Kinase Activation: Calculation completed
MAPK Family Signaling Cascades: Calculation started
MAPK Family Signaling Cascades: scoring computed

Calculating pathways:  36%|███▌      | 179/502 [15:35<29:26,  5.47s/it]

MAPK Family Signaling Cascades: pvalue calculation completed
MAPK Family Signaling Cascades: Calculation completed
MAPK Targets Nuclear Events Mediated by MAP Kinases: Calculation started
MAPK Targets Nuclear Events Mediated by MAP Kinases: scoring computed

Calculating pathways:  36%|███▌      | 180/502 [15:38<26:40,  4.97s/it]

MAPK Targets Nuclear Events Mediated by MAP Kinases: pvalue calculation completed
MAPK Targets Nuclear Events Mediated by MAP Kinases: Calculation completed
MAPK1 MAPK3 Signaling: Calculation started
MAPK1 MAPK3 Signaling: scoring computed

Calculating pathways:  36%|███▌      | 181/502 [15:45<29:13,  5.46s/it]

MAPK1 MAPK3 Signaling: pvalue calculation completed
MAPK1 MAPK3 Signaling: Calculation completed
MITF-M-dependent Gene Expression: Calculation started
MITF-M-dependent Gene Expression: scoring computed

Calculating pathways:  36%|███▋      | 182/502 [15:49<27:30,  5.16s/it]

MITF-M-dependent Gene Expression: pvalue calculation completed
MITF-M-dependent Gene Expression: Calculation completed
MITF-M-regulated Melanocyte Development: Calculation started
MITF-M-regulated Melanocyte Development: scoring computed

Calculating pathways:  36%|███▋      | 183/502 [15:55<27:27,  5.17s/it]

MITF-M-regulated Melanocyte Development: pvalue calculation completed
MITF-M-regulated Melanocyte Development: Calculation completed
Meiosis: Calculation started
Meiosis: scoring computed

Calculating pathways:  37%|███▋      | 184/502 [15:59<25:58,  4.90s/it]

Meiosis: pvalue calculation completed
Meiosis: Calculation completed
Meiotic Recombination: Calculation started
Meiotic Recombination: scoring computed

Calculating pathways:  37%|███▋      | 185/502 [16:03<24:33,  4.65s/it]

Meiotic Recombination: pvalue calculation completed
Meiotic Recombination: Calculation completed
Mitotic G1 Phase and G1 S Transition: Calculation started
Mitotic G1 Phase and G1 S Transition: scoring computed

Calculating pathways:  37%|███▋      | 186/502 [16:08<25:29,  4.84s/it]

Mitotic G1 Phase and G1 S Transition: pvalue calculation completed
Mitotic G1 Phase and G1 S Transition: Calculation completed
Mitotic G2-G2 M Phases: Calculation started
Mitotic G2-G2 M Phases: scoring computed

Calculating pathways:  37%|███▋      | 187/502 [16:14<26:58,  5.14s/it]

Mitotic G2-G2 M Phases: pvalue calculation completed
Mitotic G2-G2 M Phases: Calculation completed
MyD88 Cascade Initiated on Plasma Membrane: Calculation started
MyD88 Cascade Initiated on Plasma Membrane: scoring computed

Calculating pathways:  37%|███▋      | 188/502 [16:19<26:04,  4.98s/it]

MyD88 Cascade Initiated on Plasma Membrane: pvalue calculation completed
MyD88 Cascade Initiated on Plasma Membrane: Calculation completed
MyD88 Dependent Cascade Initiated on Endosome: Calculation started
MyD88 Dependent Cascade Initiated on Endosome: scoring computed

Calculating pathways:  38%|███▊      | 189/502 [16:23<25:40,  4.92s/it]

MyD88 Dependent Cascade Initiated on Endosome: pvalue calculation completed
MyD88 Dependent Cascade Initiated on Endosome: Calculation completed
MyD88-independent TLR4 Cascade: Calculation started
MyD88-independent TLR4 Cascade: scoring computed

Calculating pathways:  38%|███▊      | 190/502 [16:28<25:36,  4.92s/it]

MyD88-independent TLR4 Cascade: pvalue calculation completed
MyD88-independent TLR4 Cascade: Calculation completed
MyD88 MAL(TIRAP) Cascade Initiated on Plasma Membrane: Calculation started
MyD88 MAL(TIRAP) Cascade Initiated on Plasma Membrane: scoring computed

Calculating pathways:  38%|███▊      | 191/502 [16:33<25:34,  4.93s/it]

MyD88 MAL(TIRAP) Cascade Initiated on Plasma Membrane: pvalue calculation completed
MyD88 MAL(TIRAP) Cascade Initiated on Plasma Membrane: Calculation completed
Negative Regulation of FLT3: Calculation started
Negative Regulation of FLT3: scoring computed

Calculating pathways:  38%|███▊      | 192/502 [16:37<23:24,  4.53s/it]

Negative Regulation of FLT3: pvalue calculation completed
Negative Regulation of FLT3: Calculation completed
Negative Regulation of the PI3K AKT Network: Calculation started
Negative Regulation of the PI3K AKT Network: scoring computed

Calculating pathways:  38%|███▊      | 193/502 [16:42<23:42,  4.60s/it]

Negative Regulation of the PI3K AKT Network: pvalue calculation completed
Negative Regulation of the PI3K AKT Network: Calculation completed
Nervous System Development: Calculation started
Nervous System Development: scoring computed

Calculating pathways:  39%|███▊      | 194/502 [16:51<31:20,  6.11s/it]

Nervous System Development: pvalue calculation completed
Nervous System Development: Calculation completed
Neuronal System: Calculation started
Neuronal System: scoring computed

Calculating pathways:  39%|███▉      | 195/502 [16:59<33:49,  6.61s/it]

Neuronal System: pvalue calculation completed
Neuronal System: Calculation completed
Neurotransmitter Receptors and Postsynaptic Signal Transmission: Calculation started
Neurotransmitter Receptors and Postsynaptic Signal Transmission: scoring computed

Calculating pathways:  39%|███▉      | 196/502 [17:05<32:27,  6.37s/it]

Neurotransmitter Receptors and Postsynaptic Signal Transmission: pvalue calculation completed
Neurotransmitter Receptors and Postsynaptic Signal Transmission: Calculation completed
Nuclear Events (Kinase and Transcription Factor Activation): Calculation started
Nuclear Events (Kinase and Transcription Factor Activation): scoring computed

Calculating pathways:  39%|███▉      | 197/502 [17:09<28:57,  5.70s/it]

Nuclear Events (Kinase and Transcription Factor Activation): pvalue calculation completed
Nuclear Events (Kinase and Transcription Factor Activation): Calculation completed
Oncogene Induced Senescence: Calculation started
Oncogene Induced Senescence: scoring computed

Calculating pathways:  39%|███▉      | 198/502 [17:13<26:15,  5.18s/it]

Oncogene Induced Senescence: pvalue calculation completed
Oncogene Induced Senescence: Calculation completed
Orc1 Removal From Chromatin: Calculation started
Orc1 Removal From Chromatin: scoring computed

Calculating pathways:  40%|███▉      | 199/502 [17:17<24:38,  4.88s/it]

Orc1 Removal From Chromatin: pvalue calculation completed
Orc1 Removal From Chromatin: Calculation completed
Oxidative Stress Induced Senescence: Calculation started
Oxidative Stress Induced Senescence: scoring computed

Calculating pathways:  40%|███▉      | 200/502 [17:22<24:00,  4.77s/it]

Oxidative Stress Induced Senescence: pvalue calculation completed
Oxidative Stress Induced Senescence: Calculation completed
PI3K Cascade: Calculation started
PI3K Cascade: scoring computed

Calculating pathways:  40%|████      | 201/502 [17:26<22:37,  4.51s/it]

PI3K Cascade: pvalue calculation completed
PI3K Cascade: Calculation completed
PI3K AKT Signaling in Cancer: Calculation started
PI3K AKT Signaling in Cancer: scoring computed

Calculating pathways:  40%|████      | 202/502 [17:30<22:56,  4.59s/it]

PI3K AKT Signaling in Cancer: pvalue calculation completed
PI3K AKT Signaling in Cancer: Calculation completed
PI5P, PP2A and IER3 Regulate PI3K AKT Signaling: Calculation started
PI5P, PP2A and IER3 Regulate PI3K AKT Signaling: scoring computed

Calculating pathways:  40%|████      | 203/502 [17:35<23:05,  4.63s/it]

PI5P, PP2A and IER3 Regulate PI3K AKT Signaling: pvalue calculation completed
PI5P, PP2A and IER3 Regulate PI3K AKT Signaling: Calculation completed
PIP3 Activates AKT Signaling: Calculation started
PIP3 Activates AKT Signaling: scoring computed

Calculating pathways:  41%|████      | 204/502 [17:42<26:04,  5.25s/it]

PIP3 Activates AKT Signaling: pvalue calculation completed
PIP3 Activates AKT Signaling: Calculation completed
PTK6 Regulates Cell Cycle: Calculation started
PTK6 Regulates Cell Cycle: scoring computed

Calculating pathways:  41%|████      | 205/502 [17:45<23:34,  4.76s/it]

PTK6 Regulates Cell Cycle: pvalue calculation completed
PTK6 Regulates Cell Cycle: Calculation completed
Pausing and Recovery of HIV Elongation: Calculation started
Pausing and Recovery of HIV Elongation: scoring computed

Calculating pathways:  41%|████      | 206/502 [17:49<22:15,  4.51s/it]

Pausing and Recovery of HIV Elongation: pvalue calculation completed
Pausing and Recovery of HIV Elongation: Calculation completed
Pausing and Recovery of Tat-mediated HIV Elongation: Calculation started
Pausing and Recovery of Tat-mediated HIV Elongation: scoring computed

Calculating pathways:  41%|████      | 207/502 [17:53<21:23,  4.35s/it]

Pausing and Recovery of Tat-mediated HIV Elongation: pvalue calculation completed
Pausing and Recovery of Tat-mediated HIV Elongation: Calculation completed
Post NMDA Receptor Activation Events: Calculation started
Post NMDA Receptor Activation Events: scoring computed

Calculating pathways:  41%|████▏     | 208/502 [17:58<21:15,  4.34s/it]

Post NMDA Receptor Activation Events: pvalue calculation completed
Post NMDA Receptor Activation Events: Calculation completed
Post-translational Protein Modification: Calculation started
Post-translational Protein Modification: scoring computed

Calculating pathways:  42%|████▏     | 209/502 [18:16<41:44,  8.55s/it]

Post-translational Protein Modification: pvalue calculation completed
Post-translational Protein Modification: Calculation completed
Potential Therapeutics for SARS: Calculation started
Potential Therapeutics for SARS: scoring computed

Calculating pathways:  42%|████▏     | 210/502 [18:21<36:10,  7.43s/it]

Potential Therapeutics for SARS: pvalue calculation completed
Potential Therapeutics for SARS: Calculation completed
Pre-NOTCH Expression and Processing: Calculation started
Pre-NOTCH Expression and Processing: scoring computed

Calculating pathways:  42%|████▏     | 211/502 [18:25<31:29,  6.49s/it]

Pre-NOTCH Expression and Processing: pvalue calculation completed
Pre-NOTCH Expression and Processing: Calculation completed
Pre-NOTCH Transcription and Translation: Calculation started
Pre-NOTCH Transcription and Translation: scoring computed

Calculating pathways:  42%|████▏     | 212/502 [18:29<27:53,  5.77s/it]

Pre-NOTCH Transcription and Translation: pvalue calculation completed
Pre-NOTCH Transcription and Translation: Calculation completed
Processing of DNA Double-Strand Break Ends: Calculation started
Processing of DNA Double-Strand Break Ends: scoring computed

Calculating pathways:  42%|████▏     | 213/502 [18:33<25:32,  5.30s/it]

Processing of DNA Double-Strand Break Ends: pvalue calculation completed
Processing of DNA Double-Strand Break Ends: Calculation completed
RAF MAP Kinase Cascade: Calculation started
RAF MAP Kinase Cascade: scoring computed

Calculating pathways:  43%|████▎     | 214/502 [18:40<27:20,  5.70s/it]

RAF MAP Kinase Cascade: pvalue calculation completed
RAF MAP Kinase Cascade: Calculation completed
RMTs Methylate Histone Arginines: Calculation started
RMTs Methylate Histone Arginines: scoring computed

Calculating pathways:  43%|████▎     | 215/502 [18:44<24:59,  5.22s/it]

RMTs Methylate Histone Arginines: pvalue calculation completed
RMTs Methylate Histone Arginines: Calculation completed
RNA Polymerase II Pre-transcription Events: Calculation started
RNA Polymerase II Pre-transcription Events: scoring computed

Calculating pathways:  43%|████▎     | 216/502 [18:49<23:42,  4.97s/it]

RNA Polymerase II Pre-transcription Events: pvalue calculation completed
RNA Polymerase II Pre-transcription Events: Calculation completed
RNA Polymerase II Transcription: Calculation started
RNA Polymerase II Transcription: scoring computed

Calculating pathways:  43%|████▎     | 217/502 [19:06<41:28,  8.73s/it]

RNA Polymerase II Transcription: pvalue calculation completed
RNA Polymerase II Transcription: Calculation completed
RNA Polymerase II Transcription Elongation: Calculation started
RNA Polymerase II Transcription Elongation: scoring computed

Calculating pathways:  43%|████▎     | 218/502 [19:10<34:38,  7.32s/it]

RNA Polymerase II Transcription Elongation: pvalue calculation completed
RNA Polymerase II Transcription Elongation: Calculation completed
RNA Polymerase II Transcribes snRNA Genes: Calculation started
RNA Polymerase II Transcribes snRNA Genes: scoring computed

Calculating pathways:  44%|████▎     | 219/502 [19:15<30:30,  6.47s/it]

RNA Polymerase II Transcribes snRNA Genes: pvalue calculation completed
RNA Polymerase II Transcribes snRNA Genes: Calculation completed
RSK Activation: Calculation started
RSK Activation: scoring computed

Calculating pathways:  44%|████▍     | 220/502 [19:18<26:20,  5.60s/it]

RSK Activation: pvalue calculation completed
RSK Activation: Calculation completed
RUNX3 Regulates WNT Signaling: Calculation started
RUNX3 Regulates WNT Signaling: scoring computed

Calculating pathways:  44%|████▍     | 221/502 [19:22<23:13,  4.96s/it]

RUNX3 Regulates WNT Signaling: pvalue calculation completed
RUNX3 Regulates WNT Signaling: Calculation completed
RUNX3 Regulates p14-ARF: Calculation started
RUNX3 Regulates p14-ARF: scoring computed

Calculating pathways:  44%|████▍     | 222/502 [19:25<21:15,  4.56s/it]

RUNX3 Regulates p14-ARF: pvalue calculation completed
RUNX3 Regulates p14-ARF: Calculation completed
Recycling Pathway of L1: Calculation started
Recycling Pathway of L1: scoring computed

Calculating pathways:  44%|████▍     | 223/502 [19:29<20:14,  4.35s/it]

Recycling Pathway of L1: pvalue calculation completed
Recycling Pathway of L1: Calculation completed
Regulation of APC C Activators Between G1 S and Early Anaphase: Calculation started
Regulation of APC C Activators Between G1 S and Early Anaphase: scoring computed

Calculating pathways:  45%|████▍     | 224/502 [19:33<20:05,  4.34s/it]

Regulation of APC C Activators Between G1 S and Early Anaphase: pvalue calculation completed
Regulation of APC C Activators Between G1 S and Early Anaphase: Calculation completed
Regulation of MITF-M-dependent Genes Involved in Cell Cycle and Proliferation: Calculation started
Regulation of MITF-M-dependent Genes Involved in Cell Cycle and Proliferation: scoring computed

Calculating pathways:  45%|████▍     | 225/502 [19:37<19:10,  4.15s/it]

Regulation of MITF-M-dependent Genes Involved in Cell Cycle and Proliferation: pvalue calculation completed
Regulation of MITF-M-dependent Genes Involved in Cell Cycle and Proliferation: Calculation completed
Regulation of RUNX1 Expression and Activity: Calculation started
Regulation of RUNX1 Expression and Activity: scoring computed

Calculating pathways:  45%|████▌     | 226/502 [19:41<18:38,  4.05s/it]

Regulation of RUNX1 Expression and Activity: pvalue calculation completed
Regulation of RUNX1 Expression and Activity: Calculation completed
Regulation of TP53 Activity: Calculation started
Regulation of TP53 Activity: scoring computed

Calculating pathways:  45%|████▌     | 227/502 [19:46<20:36,  4.50s/it]

Regulation of TP53 Activity: pvalue calculation completed
Regulation of TP53 Activity: Calculation completed
Regulation of TP53 Activity Through Phosphorylation: Calculation started
Regulation of TP53 Activity Through Phosphorylation: scoring computed

Calculating pathways:  45%|████▌     | 228/502 [19:51<20:35,  4.51s/it]

Regulation of TP53 Activity Through Phosphorylation: pvalue calculation completed
Regulation of TP53 Activity Through Phosphorylation: Calculation completed
Regulation of TP53 Degradation: Calculation started
Regulation of TP53 Degradation: scoring computed

Calculating pathways:  46%|████▌     | 229/502 [19:55<19:52,  4.37s/it]

Regulation of TP53 Degradation: pvalue calculation completed
Regulation of TP53 Degradation: Calculation completed
Regulation of TP53 Expression and Degradation: Calculation started
Regulation of TP53 Expression and Degradation: scoring computed

Calculating pathways:  46%|████▌     | 230/502 [19:59<19:03,  4.20s/it]

Regulation of TP53 Expression and Degradation: pvalue calculation completed
Regulation of TP53 Expression and Degradation: Calculation completed
Regulation of Mitotic Cell Cycle: Calculation started
Regulation of Mitotic Cell Cycle: scoring computed

Calculating pathways:  46%|████▌     | 231/502 [20:03<18:59,  4.20s/it]

Regulation of Mitotic Cell Cycle: pvalue calculation completed
Regulation of Mitotic Cell Cycle: Calculation completed
Reproduction: Calculation started
Reproduction: scoring computed

Calculating pathways:  46%|████▌     | 232/502 [20:08<19:43,  4.38s/it]

Reproduction: pvalue calculation completed
Reproduction: Calculation completed
S Phase: Calculation started
S Phase: scoring computed

Calculating pathways:  46%|████▋     | 233/502 [20:13<21:08,  4.71s/it]

S Phase: pvalue calculation completed
S Phase: Calculation completed
SARS-CoV Infections: Calculation started
SARS-CoV Infections: scoring computed

Calculating pathways:  47%|████▋     | 234/502 [20:22<25:50,  5.78s/it]

SARS-CoV Infections: pvalue calculation completed
SARS-CoV Infections: Calculation completed
SCF(Skp2)-mediated Degradation of P27 P21: Calculation started
SCF(Skp2)-mediated Degradation of P27 P21: scoring computed

Calculating pathways:  47%|████▋     | 235/502 [20:26<23:37,  5.31s/it]

SCF(Skp2)-mediated Degradation of P27 P21: pvalue calculation completed
SCF(Skp2)-mediated Degradation of P27 P21: Calculation completed
SMAD2 SMAD3 SMAD4 Heterotrimer Regulates Transcription: Calculation started
SMAD2 SMAD3 SMAD4 Heterotrimer Regulates Transcription: scoring computed

Calculating pathways:  47%|████▋     | 236/502 [20:30<21:35,  4.87s/it]

SMAD2 SMAD3 SMAD4 Heterotrimer Regulates Transcription: pvalue calculation completed
SMAD2 SMAD3 SMAD4 Heterotrimer Regulates Transcription: Calculation completed
STAT5 Activation: Calculation started
STAT5 Activation: scoring computed

Calculating pathways:  47%|████▋     | 237/502 [20:33<19:43,  4.47s/it]

STAT5 Activation: pvalue calculation completed
STAT5 Activation: Calculation completed
STAT5 Activation Downstream of FLT3 ITD Mutants: Calculation started
STAT5 Activation Downstream of FLT3 ITD Mutants: scoring computed

Calculating pathways:  47%|████▋     | 238/502 [20:37<18:21,  4.17s/it]

STAT5 Activation Downstream of FLT3 ITD Mutants: pvalue calculation completed
STAT5 Activation Downstream of FLT3 ITD Mutants: Calculation completed
Senescence-Associated Secretory Phenotype (SASP): Calculation started
Senescence-Associated Secretory Phenotype (SASP): scoring computed

Calculating pathways:  48%|████▊     | 239/502 [20:41<18:17,  4.17s/it]

Senescence-Associated Secretory Phenotype (SASP): pvalue calculation completed
Senescence-Associated Secretory Phenotype (SASP): Calculation completed
Signaling by ALK: Calculation started
Signaling by ALK: scoring computed

Calculating pathways:  48%|████▊     | 240/502 [20:45<17:41,  4.05s/it]

Signaling by ALK: pvalue calculation completed
Signaling by ALK: Calculation completed
Signaling by FLT3 ITD and TKD Mutants: Calculation started
Signaling by FLT3 ITD and TKD Mutants: scoring computed

Calculating pathways:  48%|████▊     | 241/502 [20:49<17:26,  4.01s/it]

Signaling by FLT3 ITD and TKD Mutants: pvalue calculation completed
Signaling by FLT3 ITD and TKD Mutants: Calculation completed
Signaling by GPCR: Calculation started
Signaling by GPCR: scoring computed

Calculating pathways:  48%|████▊     | 242/502 [20:59<25:08,  5.80s/it]

Signaling by GPCR: pvalue calculation completed
Signaling by GPCR: Calculation completed
Signaling by Insulin Receptor: Calculation started
Signaling by Insulin Receptor: scoring computed

Calculating pathways:  48%|████▊     | 243/502 [21:03<23:00,  5.33s/it]

Signaling by Insulin Receptor: pvalue calculation completed
Signaling by Insulin Receptor: Calculation completed
Signaling by Interleukins: Calculation started
Signaling by Interleukins: scoring computed

Calculating pathways:  49%|████▊     | 244/502 [21:11<26:43,  6.22s/it]

Signaling by Interleukins: pvalue calculation completed
Signaling by Interleukins: Calculation completed
Signaling by NOTCH: Calculation started
Signaling by NOTCH: scoring computed

Calculating pathways:  49%|████▉     | 245/502 [21:17<26:03,  6.08s/it]

Signaling by NOTCH: pvalue calculation completed
Signaling by NOTCH: Calculation completed
Signaling by NTRK1 (TRKA): Calculation started
Signaling by NTRK1 (TRKA): scoring computed

Calculating pathways:  49%|████▉     | 246/502 [21:22<24:28,  5.73s/it]

Signaling by NTRK1 (TRKA): pvalue calculation completed
Signaling by NTRK1 (TRKA): Calculation completed
Signaling by NTRKs: Calculation started
Signaling by NTRKs: scoring computed

Calculating pathways:  49%|████▉     | 247/502 [21:27<23:34,  5.55s/it]

Signaling by NTRKs: pvalue calculation completed
Signaling by NTRKs: Calculation completed
Signaling by Non-Receptor Tyrosine Kinases: Calculation started
Signaling by Non-Receptor Tyrosine Kinases: scoring computed

Calculating pathways:  49%|████▉     | 248/502 [21:31<21:45,  5.14s/it]

Signaling by Non-Receptor Tyrosine Kinases: pvalue calculation completed
Signaling by Non-Receptor Tyrosine Kinases: Calculation completed
Signaling by Nuclear Receptors: Calculation started
Signaling by Nuclear Receptors: scoring computed

Calculating pathways:  50%|████▉     | 249/502 [21:38<23:25,  5.56s/it]

Signaling by Nuclear Receptors: pvalue calculation completed
Signaling by Nuclear Receptors: Calculation completed
Signaling by PTK6: Calculation started
Signaling by PTK6: scoring computed

Calculating pathways:  50%|████▉     | 250/502 [21:42<21:24,  5.10s/it]

Signaling by PTK6: pvalue calculation completed
Signaling by PTK6: Calculation completed
Signaling by Receptor Tyrosine Kinases: Calculation started
Signaling by Receptor Tyrosine Kinases: scoring computed

Calculating pathways:  50%|█████     | 251/502 [21:51<26:45,  6.40s/it]

Signaling by Receptor Tyrosine Kinases: pvalue calculation completed
Signaling by Receptor Tyrosine Kinases: Calculation completed
Signaling by TGF-beta Receptor Complex: Calculation started
Signaling by TGF-beta Receptor Complex: scoring computed

Calculating pathways:  50%|█████     | 252/502 [21:56<24:32,  5.89s/it]

Signaling by TGF-beta Receptor Complex: pvalue calculation completed
Signaling by TGF-beta Receptor Complex: Calculation completed
Signaling by TGFB Family Members: Calculation started
Signaling by TGFB Family Members: scoring computed

Calculating pathways:  50%|█████     | 253/502 [22:01<23:52,  5.75s/it]

Signaling by TGFB Family Members: pvalue calculation completed
Signaling by TGFB Family Members: Calculation completed
Signaling by Type 1 Insulin-like Growth Factor 1 Receptor (IGF1R): Calculation started
Signaling by Type 1 Insulin-like Growth Factor 1 Receptor (IGF1R): scoring computed

Calculating pathways:  51%|█████     | 254/502 [22:05<21:35,  5.22s/it]

Signaling by Type 1 Insulin-like Growth Factor 1 Receptor (IGF1R): pvalue calculation completed
Signaling by Type 1 Insulin-like Growth Factor 1 Receptor (IGF1R): Calculation completed
Switching of Origins to a Post-Replicative State: Calculation started
Switching of Origins to a Post-Replicative State: scoring computed

Calculating pathways:  51%|█████     | 255/502 [22:10<20:35,  5.00s/it]

Switching of Origins to a Post-Replicative State: pvalue calculation completed
Switching of Origins to a Post-Replicative State: Calculation completed
Synthesis of DNA: Calculation started
Synthesis of DNA: scoring computed

Calculating pathways:  51%|█████     | 256/502 [22:15<20:28,  5.00s/it]

Synthesis of DNA: pvalue calculation completed
Synthesis of DNA: Calculation completed
TP53 Regulates Transcription of Cell Cycle Genes: Calculation started
TP53 Regulates Transcription of Cell Cycle Genes: scoring computed

Calculating pathways:  51%|█████     | 257/502 [22:19<19:18,  4.73s/it]

TP53 Regulates Transcription of Cell Cycle Genes: pvalue calculation completed
TP53 Regulates Transcription of Cell Cycle Genes: Calculation completed
TP53 Regulates Transcription of DNA Repair Genes: Calculation started
TP53 Regulates Transcription of DNA Repair Genes: scoring computed

Calculating pathways:  51%|█████▏    | 258/502 [22:23<18:44,  4.61s/it]

TP53 Regulates Transcription of DNA Repair Genes: pvalue calculation completed
TP53 Regulates Transcription of DNA Repair Genes: Calculation completed
TP53 Regulates Transcription of Genes Involved in G1 Cell Cycle Arrest: Calculation started
TP53 Regulates Transcription of Genes Involved in G1 Cell Cycle Arrest: scoring computed

Calculating pathways:  52%|█████▏    | 259/502 [22:27<17:24,  4.30s/it]

TP53 Regulates Transcription of Genes Involved in G1 Cell Cycle Arrest: pvalue calculation completed
TP53 Regulates Transcription of Genes Involved in G1 Cell Cycle Arrest: Calculation completed
TRAF6 Mediated Induction of NFkB and MAP Kinases Upon TLR7 8 or 9 Activation: Calculation started
TRAF6 Mediated Induction of NFkB and MAP Kinases Upon TLR7 8 or 9 Activation: scoring computed

Calculating pathways:  52%|█████▏    | 260/502 [22:31<17:51,  4.43s/it]

TRAF6 Mediated Induction of NFkB and MAP Kinases Upon TLR7 8 or 9 Activation: pvalue calculation completed
TRAF6 Mediated Induction of NFkB and MAP Kinases Upon TLR7 8 or 9 Activation: Calculation completed
TRIF (TICAM1)-mediated TLR4 Signaling: Calculation started
TRIF (TICAM1)-mediated TLR4 Signaling: scoring computed

Calculating pathways:  52%|█████▏    | 261/502 [22:36<18:25,  4.59s/it]

TRIF (TICAM1)-mediated TLR4 Signaling: pvalue calculation completed
TRIF (TICAM1)-mediated TLR4 Signaling: Calculation completed
Tat-mediated HIV Elongation Arrest and Recovery: Calculation started
Tat-mediated HIV Elongation Arrest and Recovery: scoring computed

Calculating pathways:  52%|█████▏    | 262/502 [22:40<17:30,  4.38s/it]

Tat-mediated HIV Elongation Arrest and Recovery: pvalue calculation completed
Tat-mediated HIV Elongation Arrest and Recovery: Calculation completed
Tat-mediated Elongation of the HIV-1 Transcript: Calculation started
Tat-mediated Elongation of the HIV-1 Transcript: scoring computed

Calculating pathways:  52%|█████▏    | 263/502 [22:44<16:57,  4.26s/it]

Tat-mediated Elongation of the HIV-1 Transcript: pvalue calculation completed
Tat-mediated Elongation of the HIV-1 Transcript: Calculation completed
Telomere Extension By Telomerase: Calculation started
Telomere Extension By Telomerase: scoring computed

Calculating pathways:  53%|█████▎    | 264/502 [22:48<16:09,  4.07s/it]

Telomere Extension By Telomerase: pvalue calculation completed
Telomere Extension By Telomerase: Calculation completed
Telomere Maintenance: Calculation started
Telomere Maintenance: scoring computed

Calculating pathways:  53%|█████▎    | 265/502 [22:52<16:40,  4.22s/it]

Telomere Maintenance: pvalue calculation completed
Telomere Maintenance: Calculation completed
Toll Like Receptor 10 (TLR10) Cascade: Calculation started
Toll Like Receptor 10 (TLR10) Cascade: scoring computed

Calculating pathways:  53%|█████▎    | 266/502 [22:57<16:58,  4.32s/it]

Toll Like Receptor 10 (TLR10) Cascade: pvalue calculation completed
Toll Like Receptor 10 (TLR10) Cascade: Calculation completed
Toll Like Receptor 2 (TLR2) Cascade: Calculation started
Toll Like Receptor 2 (TLR2) Cascade: scoring computed

Calculating pathways:  53%|█████▎    | 267/502 [23:02<17:41,  4.52s/it]

Toll Like Receptor 2 (TLR2) Cascade: pvalue calculation completed
Toll Like Receptor 2 (TLR2) Cascade: Calculation completed
Toll Like Receptor 3 (TLR3) Cascade: Calculation started
Toll Like Receptor 3 (TLR3) Cascade: scoring computed

Calculating pathways:  53%|█████▎    | 268/502 [23:07<18:02,  4.63s/it]

Toll Like Receptor 3 (TLR3) Cascade: pvalue calculation completed
Toll Like Receptor 3 (TLR3) Cascade: Calculation completed
Toll Like Receptor 4 (TLR4) Cascade: Calculation started
Toll Like Receptor 4 (TLR4) Cascade: scoring computed

Calculating pathways:  54%|█████▎    | 269/502 [23:12<18:49,  4.85s/it]

Toll Like Receptor 4 (TLR4) Cascade: pvalue calculation completed
Toll Like Receptor 4 (TLR4) Cascade: Calculation completed
Toll Like Receptor 5 (TLR5) Cascade: Calculation started
Toll Like Receptor 5 (TLR5) Cascade: scoring computed

Calculating pathways:  54%|█████▍    | 270/502 [23:17<18:39,  4.82s/it]

Toll Like Receptor 5 (TLR5) Cascade: pvalue calculation completed
Toll Like Receptor 5 (TLR5) Cascade: Calculation completed
Toll Like Receptor 7 8 (TLR7 8) Cascade: Calculation started
Toll Like Receptor 7 8 (TLR7 8) Cascade: scoring computed

Calculating pathways:  54%|█████▍    | 271/502 [23:22<18:41,  4.85s/it]

Toll Like Receptor 7 8 (TLR7 8) Cascade: pvalue calculation completed
Toll Like Receptor 7 8 (TLR7 8) Cascade: Calculation completed
Toll Like Receptor 9 (TLR9) Cascade: Calculation started
Toll Like Receptor 9 (TLR9) Cascade: scoring computed

Calculating pathways:  54%|█████▍    | 272/502 [23:27<18:39,  4.87s/it]

Toll Like Receptor 9 (TLR9) Cascade: pvalue calculation completed
Toll Like Receptor 9 (TLR9) Cascade: Calculation completed
Toll Like Receptor TLR1 TLR2 Cascade: Calculation started
Toll Like Receptor TLR1 TLR2 Cascade: scoring computed

Calculating pathways:  54%|█████▍    | 273/502 [23:32<18:36,  4.88s/it]

Toll Like Receptor TLR1 TLR2 Cascade: pvalue calculation completed
Toll Like Receptor TLR1 TLR2 Cascade: Calculation completed
Toll Like Receptor TLR6 TLR2 Cascade: Calculation started
Toll Like Receptor TLR6 TLR2 Cascade: scoring computed

Calculating pathways:  55%|█████▍    | 274/502 [23:37<18:39,  4.91s/it]

Toll Like Receptor TLR6 TLR2 Cascade: pvalue calculation completed
Toll Like Receptor TLR6 TLR2 Cascade: Calculation completed
Toll-like Receptor Cascades: Calculation started
Toll-like Receptor Cascades: scoring computed

Calculating pathways:  55%|█████▍    | 275/502 [23:42<19:25,  5.14s/it]

Toll-like Receptor Cascades: pvalue calculation completed
Toll-like Receptor Cascades: Calculation completed
Transcription of E2F Targets Under Neg Control by P107 (RBL1) and P130 (RBL2) in Complex With HDAC1: Calculation started
Transcription of E2F Targets Under Neg Control by P107 (RBL1) and P130 (RBL2) in Complex With HDAC1: scoring computed

Calculating pathways:  55%|█████▍    | 276/502 [23:46<17:39,  4.69s/it]

Transcription of E2F Targets Under Neg Control by P107 (RBL1) and P130 (RBL2) in Complex With HDAC1: pvalue calculation completed
Transcription of E2F Targets Under Neg Control by P107 (RBL1) and P130 (RBL2) in Complex With HDAC1: Calculation completed
Transcription of the HIV Genome: Calculation started
Transcription of the HIV Genome: scoring computed

Calculating pathways:  55%|█████▌    | 277/502 [23:50<17:01,  4.54s/it]

Transcription of the HIV Genome: pvalue calculation completed
Transcription of the HIV Genome: Calculation completed
Transcriptional Regulation by TP53: Calculation started
Transcriptional Regulation by TP53: scoring computed

Calculating pathways:  55%|█████▌    | 278/502 [23:58<20:41,  5.54s/it]

Transcriptional Regulation by TP53: pvalue calculation completed
Transcriptional Regulation by TP53: Calculation completed
Transcriptional Regulation by VENTX: Calculation started
Transcriptional Regulation by VENTX: scoring computed

Calculating pathways:  56%|█████▌    | 279/502 [24:02<18:44,  5.04s/it]

Transcriptional Regulation by VENTX: pvalue calculation completed
Transcriptional Regulation by VENTX: Calculation completed
Transcriptional Activity of SMAD2 SMAD3 SMAD4 Heterotrimer: Calculation started
Transcriptional Activity of SMAD2 SMAD3 SMAD4 Heterotrimer: scoring computed

Calculating pathways:  56%|█████▌    | 280/502 [24:06<17:36,  4.76s/it]

Transcriptional Activity of SMAD2 SMAD3 SMAD4 Heterotrimer: pvalue calculation completed
Transcriptional Activity of SMAD2 SMAD3 SMAD4 Heterotrimer: Calculation completed
Transcriptional and Post-Translational Regulation of MITF-M Expression and Activity: Calculation started
Transcriptional and Post-Translational Regulation of MITF-M Expression and Activity: scoring computed

Calculating pathways:  56%|█████▌    | 281/502 [24:10<16:38,  4.52s/it]

Transcriptional and Post-Translational Regulation of MITF-M Expression and Activity: pvalue calculation completed
Transcriptional and Post-Translational Regulation of MITF-M Expression and Activity: Calculation completed
Transcriptional Regulation by RUNX1: Calculation started
Transcriptional Regulation by RUNX1: scoring computed

Calculating pathways:  56%|█████▌    | 282/502 [24:16<17:56,  4.89s/it]

Transcriptional Regulation by RUNX1: pvalue calculation completed
Transcriptional Regulation by RUNX1: Calculation completed
Transcriptional Regulation by RUNX2: Calculation started
Transcriptional Regulation by RUNX2: scoring computed

Calculating pathways:  56%|█████▋    | 283/502 [24:21<17:54,  4.91s/it]

Transcriptional Regulation by RUNX2: pvalue calculation completed
Transcriptional Regulation by RUNX2: Calculation completed
Transcriptional Regulation by RUNX3: Calculation started
Transcriptional Regulation by RUNX3: scoring computed

Calculating pathways:  57%|█████▋    | 284/502 [24:25<17:18,  4.76s/it]

Transcriptional Regulation by RUNX3: pvalue calculation completed
Transcriptional Regulation by RUNX3: Calculation completed
Transcriptional Regulation of Granulopoiesis: Calculation started
Transcriptional Regulation of Granulopoiesis: scoring computed

Calculating pathways:  57%|█████▋    | 285/502 [24:29<16:21,  4.52s/it]

Transcriptional Regulation of Granulopoiesis: pvalue calculation completed
Transcriptional Regulation of Granulopoiesis: Calculation completed
Transcriptional Regulation of White Adipocyte Differentiation: Calculation started
Transcriptional Regulation of White Adipocyte Differentiation: scoring computed

Calculating pathways:  57%|█████▋    | 286/502 [24:34<16:22,  4.55s/it]

Transcriptional Regulation of White Adipocyte Differentiation: pvalue calculation completed
Transcriptional Regulation of White Adipocyte Differentiation: Calculation completed
Transmission Across Chemical Synapses: Calculation started
Transmission Across Chemical Synapses: scoring computed

Calculating pathways:  57%|█████▋    | 287/502 [24:40<18:26,  5.15s/it]

Transmission Across Chemical Synapses: pvalue calculation completed
Transmission Across Chemical Synapses: Calculation completed
Ub-specific Processing Proteases: Calculation started
Ub-specific Processing Proteases: scoring computed

Calculating pathways:  57%|█████▋    | 288/502 [24:46<18:51,  5.29s/it]

Ub-specific Processing Proteases: pvalue calculation completed
Ub-specific Processing Proteases: Calculation completed
Ubiquitin-dependent Degradation of Cyclin D: Calculation started
Ubiquitin-dependent Degradation of Cyclin D: scoring computed

Calculating pathways:  58%|█████▊    | 289/502 [24:50<17:14,  4.86s/it]

Ubiquitin-dependent Degradation of Cyclin D: pvalue calculation completed
Ubiquitin-dependent Degradation of Cyclin D: Calculation completed
Viral Infection Pathways: Calculation started
Viral Infection Pathways: scoring computed

Calculating pathways:  58%|█████▊    | 290/502 [25:02<25:00,  7.08s/it]

Viral Infection Pathways: pvalue calculation completed
Viral Infection Pathways: Calculation completed
p53-Dependent G1 DNA Damage Response: Calculation started
p53-Dependent G1 DNA Damage Response: scoring computed

Calculating pathways:  58%|█████▊    | 291/502 [25:06<21:37,  6.15s/it]

p53-Dependent G1 DNA Damage Response: pvalue calculation completed
p53-Dependent G1 DNA Damage Response: Calculation completed
p53-Dependent G1 S DNA Damage Checkpoint: Calculation started
p53-Dependent G1 S DNA Damage Checkpoint: scoring computed

Calculating pathways:  58%|█████▊    | 292/502 [25:10<19:17,  5.51s/it]

p53-Dependent G1 S DNA Damage Checkpoint: pvalue calculation completed
p53-Dependent G1 S DNA Damage Checkpoint: Calculation completed
B Cell Activation (GO:0042113): Calculation started
B Cell Activation (GO:0042113): scoring computed

Calculating pathways:  58%|█████▊    | 293/502 [25:14<18:11,  5.22s/it]

B Cell Activation (GO:0042113): pvalue calculation completed
B Cell Activation (GO:0042113): Calculation completed
B Cell Differentiation (GO:0030183): Calculation started
B Cell Differentiation (GO:0030183): scoring computed

Calculating pathways:  59%|█████▊    | 294/502 [25:18<16:48,  4.85s/it]

B Cell Differentiation (GO:0030183): pvalue calculation completed
B Cell Differentiation (GO:0030183): Calculation completed
DNA Damage Response (GO:0006974): Calculation started
DNA Damage Response (GO:0006974): scoring computed

Calculating pathways:  59%|█████▉    | 295/502 [25:27<20:18,  5.89s/it]

DNA Damage Response (GO:0006974): pvalue calculation completed
DNA Damage Response (GO:0006974): Calculation completed
DNA Metabolic Process (GO:0006259): Calculation started
DNA Metabolic Process (GO:0006259): scoring computed

Calculating pathways:  59%|█████▉    | 296/502 [25:34<21:24,  6.24s/it]

DNA Metabolic Process (GO:0006259): pvalue calculation completed
DNA Metabolic Process (GO:0006259): Calculation completed
DNA Replication (GO:0006260): Calculation started
DNA Replication (GO:0006260): scoring computed

Calculating pathways:  59%|█████▉    | 297/502 [25:38<19:21,  5.66s/it]

DNA Replication (GO:0006260): pvalue calculation completed
DNA Replication (GO:0006260): Calculation completed
DNA-templated DNA Replication Maintenance of Fidelity (GO:0045005): Calculation started
DNA-templated DNA Replication Maintenance of Fidelity (GO:0045005): scoring computed

Calculating pathways:  59%|█████▉    | 298/502 [25:42<17:33,  5.16s/it]

DNA-templated DNA Replication Maintenance of Fidelity (GO:0045005): pvalue calculation completed
DNA-templated DNA Replication Maintenance of Fidelity (GO:0045005): Calculation completed
DNA-templated Transcription (GO:0006351): Calculation started
DNA-templated Transcription (GO:0006351): scoring computed

Calculating pathways:  60%|█████▉    | 299/502 [25:48<18:16,  5.40s/it]

DNA-templated Transcription (GO:0006351): pvalue calculation completed
DNA-templated Transcription (GO:0006351): Calculation completed
DNA-templated Transcription Elongation (GO:0006354): Calculation started
DNA-templated Transcription Elongation (GO:0006354): scoring computed

Calculating pathways:  60%|█████▉    | 300/502 [25:52<16:32,  4.91s/it]

DNA-templated Transcription Elongation (GO:0006354): pvalue calculation completed
DNA-templated Transcription Elongation (GO:0006354): Calculation completed
DNA-templated Transcription Initiation (GO:0006352): Calculation started
DNA-templated Transcription Initiation (GO:0006352): scoring computed

Calculating pathways:  60%|█████▉    | 301/502 [25:56<15:53,  4.74s/it]

DNA-templated Transcription Initiation (GO:0006352): pvalue calculation completed
DNA-templated Transcription Initiation (GO:0006352): Calculation completed
G1/S Transition of Mitotic Cell Cycle (GO:0000082): Calculation started
G1/S Transition of Mitotic Cell Cycle (GO:0000082): scoring computed

Calculating pathways:  60%|██████    | 302/502 [26:00<15:09,  4.55s/it]

G1/S Transition of Mitotic Cell Cycle (GO:0000082): pvalue calculation completed
G1/S Transition of Mitotic Cell Cycle (GO:0000082): Calculation completed
G2/M Transition of Mitotic Cell Cycle (GO:0000086): Calculation started
G2/M Transition of Mitotic Cell Cycle (GO:0000086): scoring computed

Calculating pathways:  60%|██████    | 303/502 [26:04<14:37,  4.41s/it]

G2/M Transition of Mitotic Cell Cycle (GO:0000086): pvalue calculation completed
G2/M Transition of Mitotic Cell Cycle (GO:0000086): Calculation completed
Ras Protein Signal Transduction (GO:0007265): Calculation started
Ras Protein Signal Transduction (GO:0007265): scoring computed

Calculating pathways:  61%|██████    | 304/502 [26:09<14:28,  4.39s/it]

Ras Protein Signal Transduction (GO:0007265): pvalue calculation completed
Ras Protein Signal Transduction (GO:0007265): Calculation completed
T Cell Homeostasis (GO:0043029): Calculation started
T Cell Homeostasis (GO:0043029): scoring computed

Calculating pathways:  61%|██████    | 305/502 [26:12<13:39,  4.16s/it]

T Cell Homeostasis (GO:0043029): pvalue calculation completed
T Cell Homeostasis (GO:0043029): Calculation completed
TOR Signaling (GO:0031929): Calculation started
TOR Signaling (GO:0031929): scoring computed

Calculating pathways:  61%|██████    | 306/502 [26:16<13:15,  4.06s/it]

TOR Signaling (GO:0031929): pvalue calculation completed
TOR Signaling (GO:0031929): Calculation completed
TORC1 Signaling (GO:0038202): Calculation started
TORC1 Signaling (GO:0038202): scoring computed

Calculating pathways:  61%|██████    | 307/502 [26:20<12:38,  3.89s/it]

TORC1 Signaling (GO:0038202): pvalue calculation completed
TORC1 Signaling (GO:0038202): Calculation completed
Amyloid Precursor Protein Catabolic Process (GO:0042987): Calculation started
Amyloid Precursor Protein Catabolic Process (GO:0042987): scoring computed

Calculating pathways:  61%|██████▏   | 308/502 [26:23<12:19,  3.81s/it]

Amyloid Precursor Protein Catabolic Process (GO:0042987): pvalue calculation completed
Amyloid Precursor Protein Catabolic Process (GO:0042987): Calculation completed
Amyloid-Beta Formation (GO:0034205): Calculation started
Amyloid-Beta Formation (GO:0034205): scoring computed

Calculating pathways:  62%|██████▏   | 309/502 [26:27<11:55,  3.71s/it]

Amyloid-Beta Formation (GO:0034205): pvalue calculation completed
Amyloid-Beta Formation (GO:0034205): Calculation completed
Amyloid-Beta Metabolic Process (GO:0050435): Calculation started
Amyloid-Beta Metabolic Process (GO:0050435): scoring computed

Calculating pathways:  62%|██████▏   | 310/502 [26:30<11:43,  3.67s/it]

Amyloid-Beta Metabolic Process (GO:0050435): pvalue calculation completed
Amyloid-Beta Metabolic Process (GO:0050435): Calculation completed
Anterograde Trans-Synaptic Signaling (GO:0098916): Calculation started
Anterograde Trans-Synaptic Signaling (GO:0098916): scoring computed

Calculating pathways:  62%|██████▏   | 311/502 [26:36<13:06,  4.12s/it]

Anterograde Trans-Synaptic Signaling (GO:0098916): pvalue calculation completed
Anterograde Trans-Synaptic Signaling (GO:0098916): Calculation completed
Astrocyte Development (GO:0014002): Calculation started
Astrocyte Development (GO:0014002): scoring computed

Calculating pathways:  62%|██████▏   | 312/502 [26:39<12:24,  3.92s/it]

Astrocyte Development (GO:0014002): pvalue calculation completed
Astrocyte Development (GO:0014002): Calculation completed
Cell Cycle G1/S Phase Transition (GO:0044843): Calculation started
Cell Cycle G1/S Phase Transition (GO:0044843): scoring computed

Calculating pathways:  62%|██████▏   | 313/502 [26:43<12:22,  3.93s/it]

Cell Cycle G1/S Phase Transition (GO:0044843): pvalue calculation completed
Cell Cycle G1/S Phase Transition (GO:0044843): Calculation completed
Cell Cycle G2/M Phase Transition (GO:0044839): Calculation started
Cell Cycle G2/M Phase Transition (GO:0044839): scoring computed

Calculating pathways:  63%|██████▎   | 314/502 [26:47<12:09,  3.88s/it]

Cell Cycle G2/M Phase Transition (GO:0044839): pvalue calculation completed
Cell Cycle G2/M Phase Transition (GO:0044839): Calculation completed
Cell Surface Receptor Protein Tyrosine Kinase Signaling Pathway (GO:0007169): Calculation started
Cell Surface Receptor Protein Tyrosine Kinase Signaling Pathway (GO:0007169): scoring computed

Calculating pathways:  63%|██████▎   | 315/502 [26:53<14:31,  4.66s/it]

Cell Surface Receptor Protein Tyrosine Kinase Signaling Pathway (GO:0007169): pvalue calculation completed
Cell Surface Receptor Protein Tyrosine Kinase Signaling Pathway (GO:0007169): Calculation completed
Cell Surface Receptor Signaling Pathway via JAK-STAT (GO:0007259): Calculation started
Cell Surface Receptor Signaling Pathway via JAK-STAT (GO:0007259): scoring computed

Calculating pathways:  63%|██████▎   | 316/502 [26:57<13:33,  4.38s/it]

Cell Surface Receptor Signaling Pathway via JAK-STAT (GO:0007259): pvalue calculation completed
Cell Surface Receptor Signaling Pathway via JAK-STAT (GO:0007259): Calculation completed
Cell Surface Receptor Signaling Pathway via STAT (GO:0097696): Calculation started
Cell Surface Receptor Signaling Pathway via STAT (GO:0097696): scoring computed

Calculating pathways:  63%|██████▎   | 317/502 [27:01<13:04,  4.24s/it]

Cell Surface Receptor Signaling Pathway via STAT (GO:0097696): pvalue calculation completed
Cell Surface Receptor Signaling Pathway via STAT (GO:0097696): Calculation completed
Cellular Response to Cytokine Stimulus (GO:0071345): Calculation started
Cellular Response to Cytokine Stimulus (GO:0071345): scoring computed

Calculating pathways:  63%|██████▎   | 318/502 [27:07<14:56,  4.87s/it]

Cellular Response to Cytokine Stimulus (GO:0071345): pvalue calculation completed
Cellular Response to Cytokine Stimulus (GO:0071345): Calculation completed
Cellular Response to Interleukin-15 (GO:0071350): Calculation started
Cellular Response to Interleukin-15 (GO:0071350): scoring computed

Calculating pathways:  64%|██████▎   | 319/502 [27:11<13:35,  4.46s/it]

Cellular Response to Interleukin-15 (GO:0071350): pvalue calculation completed
Cellular Response to Interleukin-15 (GO:0071350): Calculation completed
Cellular Response to Interleukin-2 (GO:0071352): Calculation started
Cellular Response to Interleukin-2 (GO:0071352): scoring computed

Calculating pathways:  64%|██████▎   | 320/502 [27:14<12:31,  4.13s/it]

Cellular Response to Interleukin-2 (GO:0071352): pvalue calculation completed
Cellular Response to Interleukin-2 (GO:0071352): Calculation completed
Cellular Response to Interleukin-4 (GO:0071353): Calculation started
Cellular Response to Interleukin-4 (GO:0071353): scoring computed

Calculating pathways:  64%|██████▍   | 321/502 [27:17<11:48,  3.92s/it]

Cellular Response to Interleukin-4 (GO:0071353): pvalue calculation completed
Cellular Response to Interleukin-4 (GO:0071353): Calculation completed
Cellular Response to Interleukin-7 (GO:0098761): Calculation started
Cellular Response to Interleukin-7 (GO:0098761): scoring computed

Calculating pathways:  64%|██████▍   | 322/502 [27:21<11:22,  3.79s/it]

Cellular Response to Interleukin-7 (GO:0098761): pvalue calculation completed
Cellular Response to Interleukin-7 (GO:0098761): Calculation completed
Cellular Response to Interleukin-9 (GO:0071355): Calculation started
Cellular Response to Interleukin-9 (GO:0071355): scoring computed

Calculating pathways:  64%|██████▍   | 323/502 [27:24<10:53,  3.65s/it]

Cellular Response to Interleukin-9 (GO:0071355): pvalue calculation completed
Cellular Response to Interleukin-9 (GO:0071355): Calculation completed
Cellular Response to Oxygen-Containing Compound (GO:1901701): Calculation started
Cellular Response to Oxygen-Containing Compound (GO:1901701): scoring computed

Calculating pathways:  65%|██████▍   | 324/502 [27:32<14:11,  4.78s/it]

Cellular Response to Oxygen-Containing Compound (GO:1901701): pvalue calculation completed
Cellular Response to Oxygen-Containing Compound (GO:1901701): Calculation completed
Chemical Synaptic Transmission (GO:0007268): Calculation started
Chemical Synaptic Transmission (GO:0007268): scoring computed

Calculating pathways:  65%|██████▍   | 325/502 [27:37<14:58,  5.08s/it]

Chemical Synaptic Transmission (GO:0007268): pvalue calculation completed
Chemical Synaptic Transmission (GO:0007268): Calculation completed
Chromatin Remodeling (GO:0006338): Calculation started
Chromatin Remodeling (GO:0006338): scoring computed

Calculating pathways:  65%|██████▍   | 326/502 [27:44<15:56,  5.43s/it]

Chromatin Remodeling (GO:0006338): pvalue calculation completed
Chromatin Remodeling (GO:0006338): Calculation completed
Cytokine-Mediated Signaling Pathway (GO:0019221): Calculation started
Cytokine-Mediated Signaling Pathway (GO:0019221): scoring computed

Calculating pathways:  65%|██████▌   | 327/502 [27:50<16:10,  5.55s/it]

Cytokine-Mediated Signaling Pathway (GO:0019221): pvalue calculation completed
Cytokine-Mediated Signaling Pathway (GO:0019221): Calculation completed
Dendritic Cell Differentiation (GO:0097028): Calculation started
Dendritic Cell Differentiation (GO:0097028): scoring computed

Calculating pathways:  65%|██████▌   | 328/502 [27:53<14:19,  4.94s/it]

Dendritic Cell Differentiation (GO:0097028): pvalue calculation completed
Dendritic Cell Differentiation (GO:0097028): Calculation completed
Enzyme-Linked Receptor Protein Signaling Pathway (GO:0007167): Calculation started
Enzyme-Linked Receptor Protein Signaling Pathway (GO:0007167): scoring computed

Calculating pathways:  66%|██████▌   | 329/502 [27:58<14:01,  4.86s/it]

Enzyme-Linked Receptor Protein Signaling Pathway (GO:0007167): pvalue calculation completed
Enzyme-Linked Receptor Protein Signaling Pathway (GO:0007167): Calculation completed
Epithelial Cell Development (GO:0002064): Calculation started
Epithelial Cell Development (GO:0002064): scoring computed

Calculating pathways:  66%|██████▌   | 330/502 [28:01<12:48,  4.47s/it]

Epithelial Cell Development (GO:0002064): pvalue calculation completed
Epithelial Cell Development (GO:0002064): Calculation completed
Generation of Neurons (GO:0048699): Calculation started
Generation of Neurons (GO:0048699): scoring computed

Calculating pathways:  66%|██████▌   | 331/502 [28:06<13:16,  4.66s/it]

Generation of Neurons (GO:0048699): pvalue calculation completed
Generation of Neurons (GO:0048699): Calculation completed
Glial Cell Development (GO:0021782): Calculation started
Glial Cell Development (GO:0021782): scoring computed

Calculating pathways:  66%|██████▌   | 332/502 [28:10<12:16,  4.33s/it]

Glial Cell Development (GO:0021782): pvalue calculation completed
Glial Cell Development (GO:0021782): Calculation completed
Gliogenesis (GO:0042063): Calculation started
Gliogenesis (GO:0042063): scoring computed

Calculating pathways:  66%|██████▋   | 333/502 [28:14<11:33,  4.11s/it]

Gliogenesis (GO:0042063): pvalue calculation completed
Gliogenesis (GO:0042063): Calculation completed
Growth Hormone Receptor Signaling Pathway (GO:0060396): Calculation started
Growth Hormone Receptor Signaling Pathway (GO:0060396): scoring computed

Calculating pathways:  67%|██████▋   | 334/502 [28:17<11:03,  3.95s/it]

Growth Hormone Receptor Signaling Pathway (GO:0060396): pvalue calculation completed
Growth Hormone Receptor Signaling Pathway (GO:0060396): Calculation completed
Growth Hormone Receptor Signaling Pathway via JAK-STAT (GO:0060397): Calculation started
Growth Hormone Receptor Signaling Pathway via JAK-STAT (GO:0060397): scoring computed

Calculating pathways:  67%|██████▋   | 335/502 [28:21<10:39,  3.83s/it]

Growth Hormone Receptor Signaling Pathway via JAK-STAT (GO:0060397): pvalue calculation completed
Growth Hormone Receptor Signaling Pathway via JAK-STAT (GO:0060397): Calculation completed
Hematopoietic Progenitor Cell Differentiation (GO:0002244): Calculation started
Hematopoietic Progenitor Cell Differentiation (GO:0002244): scoring computed

Calculating pathways:  67%|██████▋   | 336/502 [28:24<10:24,  3.76s/it]

Hematopoietic Progenitor Cell Differentiation (GO:0002244): pvalue calculation completed
Hematopoietic Progenitor Cell Differentiation (GO:0002244): Calculation completed
Hemopoiesis (GO:0030097): Calculation started
Hemopoiesis (GO:0030097): scoring computed

Calculating pathways:  67%|██████▋   | 337/502 [28:29<10:55,  3.97s/it]

Hemopoiesis (GO:0030097): pvalue calculation completed
Hemopoiesis (GO:0030097): Calculation completed
Interleukin-15-Mediated Signaling Pathway (GO:0035723): Calculation started
Interleukin-15-Mediated Signaling Pathway (GO:0035723): scoring computed

Calculating pathways:  67%|██████▋   | 338/502 [28:32<10:24,  3.81s/it]

Interleukin-15-Mediated Signaling Pathway (GO:0035723): pvalue calculation completed
Interleukin-15-Mediated Signaling Pathway (GO:0035723): Calculation completed
Interleukin-2-Mediated Signaling Pathway (GO:0038110): Calculation started
Interleukin-2-Mediated Signaling Pathway (GO:0038110): scoring computed

Calculating pathways:  68%|██████▊   | 339/502 [28:36<10:00,  3.68s/it]

Interleukin-2-Mediated Signaling Pathway (GO:0038110): pvalue calculation completed
Interleukin-2-Mediated Signaling Pathway (GO:0038110): Calculation completed
Interleukin-4-Mediated Signaling Pathway (GO:0035771): Calculation started
Interleukin-4-Mediated Signaling Pathway (GO:0035771): scoring computed

Calculating pathways:  68%|██████▊   | 340/502 [28:39<09:49,  3.64s/it]

Interleukin-4-Mediated Signaling Pathway (GO:0035771): pvalue calculation completed
Interleukin-4-Mediated Signaling Pathway (GO:0035771): Calculation completed
Interleukin-7-Mediated Signaling Pathway (GO:0038111): Calculation started
Interleukin-7-Mediated Signaling Pathway (GO:0038111): scoring computed

Calculating pathways:  68%|██████▊   | 341/502 [28:43<09:39,  3.60s/it]

Interleukin-7-Mediated Signaling Pathway (GO:0038111): pvalue calculation completed
Interleukin-7-Mediated Signaling Pathway (GO:0038111): Calculation completed
Interleukin-9-Mediated Signaling Pathway (GO:0038113): Calculation started
Interleukin-9-Mediated Signaling Pathway (GO:0038113): scoring computed

Calculating pathways:  68%|██████▊   | 342/502 [28:46<09:23,  3.52s/it]

Interleukin-9-Mediated Signaling Pathway (GO:0038113): pvalue calculation completed
Interleukin-9-Mediated Signaling Pathway (GO:0038113): Calculation completed
Lymphocyte Differentiation (GO:0030098): Calculation started
Lymphocyte Differentiation (GO:0030098): scoring computed

Calculating pathways:  68%|██████▊   | 343/502 [28:50<09:55,  3.75s/it]

Lymphocyte Differentiation (GO:0030098): pvalue calculation completed
Lymphocyte Differentiation (GO:0030098): Calculation completed
Lymphocyte Proliferation (GO:0046651): Calculation started
Lymphocyte Proliferation (GO:0046651): scoring computed

Calculating pathways:  69%|██████▊   | 344/502 [28:54<09:48,  3.73s/it]

Lymphocyte Proliferation (GO:0046651): pvalue calculation completed
Lymphocyte Proliferation (GO:0046651): Calculation completed
Lymphoid Progenitor Cell Differentiation (GO:0002320): Calculation started
Lymphoid Progenitor Cell Differentiation (GO:0002320): scoring computed

Calculating pathways:  69%|██████▊   | 345/502 [28:57<09:31,  3.64s/it]

Lymphoid Progenitor Cell Differentiation (GO:0002320): pvalue calculation completed
Lymphoid Progenitor Cell Differentiation (GO:0002320): Calculation completed
Mitotic DNA Damage Checkpoint Signaling (GO:0044773): Calculation started
Mitotic DNA Damage Checkpoint Signaling (GO:0044773): scoring computed

Calculating pathways:  69%|██████▉   | 346/502 [29:01<09:41,  3.72s/it]

Mitotic DNA Damage Checkpoint Signaling (GO:0044773): pvalue calculation completed
Mitotic DNA Damage Checkpoint Signaling (GO:0044773): Calculation completed
Mitotic G1 DNA Damage Checkpoint Signaling (GO:0031571): Calculation started
Mitotic G1 DNA Damage Checkpoint Signaling (GO:0031571): scoring computed

Calculating pathways:  69%|██████▉   | 347/502 [29:05<09:24,  3.64s/it]

Mitotic G1 DNA Damage Checkpoint Signaling (GO:0031571): pvalue calculation completed
Mitotic G1 DNA Damage Checkpoint Signaling (GO:0031571): Calculation completed
Mitotic G1/S Transition Checkpoint Signaling (GO:0044819): Calculation started
Mitotic G1/S Transition Checkpoint Signaling (GO:0044819): scoring computed

Calculating pathways:  69%|██████▉   | 348/502 [29:08<09:11,  3.58s/it]

Mitotic G1/S Transition Checkpoint Signaling (GO:0044819): pvalue calculation completed
Mitotic G1/S Transition Checkpoint Signaling (GO:0044819): Calculation completed
Mitotic Cell Cycle Phase Transition (GO:0044772): Calculation started
Mitotic Cell Cycle Phase Transition (GO:0044772): scoring computed

Calculating pathways:  70%|██████▉   | 349/502 [29:13<09:58,  3.91s/it]

Mitotic Cell Cycle Phase Transition (GO:0044772): pvalue calculation completed
Mitotic Cell Cycle Phase Transition (GO:0044772): Calculation completed
Mononuclear Cell Differentiation (GO:1903131): Calculation started
Mononuclear Cell Differentiation (GO:1903131): scoring computed

Calculating pathways:  70%|██████▉   | 350/502 [29:17<09:47,  3.86s/it]

Mononuclear Cell Differentiation (GO:1903131): pvalue calculation completed
Mononuclear Cell Differentiation (GO:1903131): Calculation completed
Negative Regulation of DNA Damage Response, Signal Transduction by P53 Class Mediator (GO:0043518): Calculation started
Negative Regulation of DNA Damage Response, Signal Transduction by P53 Class Mediator (GO:0043518): scoring computed

Calculating pathways:  70%|██████▉   | 351/502 [29:20<09:32,  3.79s/it]

Negative Regulation of DNA Damage Response, Signal Transduction by P53 Class Mediator (GO:0043518): pvalue calculation completed
Negative Regulation of DNA Damage Response, Signal Transduction by P53 Class Mediator (GO:0043518): Calculation completed
Negative Regulation of DNA-templated Transcription (GO:0045892): Calculation started
Negative Regulation of DNA-templated Transcription (GO:0045892): scoring computed

Calculating pathways:  70%|███████   | 352/502 [29:33<16:31,  6.61s/it]

Negative Regulation of DNA-templated Transcription (GO:0045892): pvalue calculation completed
Negative Regulation of DNA-templated Transcription (GO:0045892): Calculation completed
Negative Regulation of T Cell Activation (GO:0050868): Calculation started
Negative Regulation of T Cell Activation (GO:0050868): scoring computed

Calculating pathways:  70%|███████   | 353/502 [29:37<14:18,  5.76s/it]

Negative Regulation of T Cell Activation (GO:0050868): pvalue calculation completed
Negative Regulation of T Cell Activation (GO:0050868): Calculation completed
Negative Regulation of T Cell Apoptotic Process (GO:0070233): Calculation started
Negative Regulation of T Cell Apoptotic Process (GO:0070233): scoring computed

Calculating pathways:  71%|███████   | 354/502 [29:41<12:26,  5.05s/it]

Negative Regulation of T Cell Apoptotic Process (GO:0070233): pvalue calculation completed
Negative Regulation of T Cell Apoptotic Process (GO:0070233): Calculation completed
Negative Regulation of T-helper 17 Cell Differentiation (GO:2000320): Calculation started
Negative Regulation of T-helper 17 Cell Differentiation (GO:2000320): scoring computed

Calculating pathways:  71%|███████   | 355/502 [29:44<11:08,  4.54s/it]

Negative Regulation of T-helper 17 Cell Differentiation (GO:2000320): pvalue calculation completed
Negative Regulation of T-helper 17 Cell Differentiation (GO:2000320): Calculation completed
Negative Regulation of T-helper 17 Cell Lineage Commitment (GO:2000329): Calculation started
Negative Regulation of T-helper 17 Cell Lineage Commitment (GO:2000329): scoring computed

Calculating pathways:  71%|███████   | 356/502 [29:47<10:10,  4.18s/it]

Negative Regulation of T-helper 17 Cell Lineage Commitment (GO:2000329): pvalue calculation completed
Negative Regulation of T-helper 17 Cell Lineage Commitment (GO:2000329): Calculation completed
Negative Regulation of T-helper Cell Differentiation (GO:0045623): Calculation started
Negative Regulation of T-helper Cell Differentiation (GO:0045623): scoring computed

Calculating pathways:  71%|███████   | 357/502 [29:51<09:31,  3.94s/it]

Negative Regulation of T-helper Cell Differentiation (GO:0045623): pvalue calculation completed
Negative Regulation of T-helper Cell Differentiation (GO:0045623): Calculation completed
Negative Regulation of TOR Signaling (GO:0032007): Calculation started
Negative Regulation of TOR Signaling (GO:0032007): scoring computed

Calculating pathways:  71%|███████▏  | 358/502 [29:55<09:39,  4.03s/it]

Negative Regulation of TOR Signaling (GO:0032007): pvalue calculation completed
Negative Regulation of TOR Signaling (GO:0032007): Calculation completed
Negative Regulation of Apoptotic Process (GO:0043066): Calculation started
Negative Regulation of Apoptotic Process (GO:0043066): scoring computed

Calculating pathways:  72%|███████▏  | 359/502 [30:03<12:36,  5.29s/it]

Negative Regulation of Apoptotic Process (GO:0043066): pvalue calculation completed
Negative Regulation of Apoptotic Process (GO:0043066): Calculation completed
Negative Regulation of Cell Cycle (GO:0045786): Calculation started
Negative Regulation of Cell Cycle (GO:0045786): scoring computed

Calculating pathways:  72%|███████▏  | 360/502 [30:07<11:46,  4.97s/it]

Negative Regulation of Cell Cycle (GO:0045786): pvalue calculation completed
Negative Regulation of Cell Cycle (GO:0045786): Calculation completed
Negative Regulation of Cell Differentiation (GO:0045596): Calculation started
Negative Regulation of Cell Differentiation (GO:0045596): scoring computed

Calculating pathways:  72%|███████▏  | 361/502 [30:13<12:12,  5.20s/it]

Negative Regulation of Cell Differentiation (GO:0045596): pvalue calculation completed
Negative Regulation of Cell Differentiation (GO:0045596): Calculation completed
Negative Regulation of Cell Fate Commitment (GO:0010454): Calculation started
Negative Regulation of Cell Fate Commitment (GO:0010454): scoring computed

Calculating pathways:  72%|███████▏  | 362/502 [30:16<10:50,  4.65s/it]

Negative Regulation of Cell Fate Commitment (GO:0010454): pvalue calculation completed
Negative Regulation of Cell Fate Commitment (GO:0010454): Calculation completed
Negative Regulation of Cell Population Proliferation (GO:0008285): Calculation started
Negative Regulation of Cell Population Proliferation (GO:0008285): scoring computed

Calculating pathways:  72%|███████▏  | 363/502 [30:24<12:33,  5.42s/it]

Negative Regulation of Cell Population Proliferation (GO:0008285): pvalue calculation completed
Negative Regulation of Cell Population Proliferation (GO:0008285): Calculation completed
Negative Regulation of Cellular Process (GO:0048523): Calculation started
Negative Regulation of Cellular Process (GO:0048523): scoring computed

Calculating pathways:  73%|███████▎  | 364/502 [30:32<14:44,  6.41s/it]

Negative Regulation of Cellular Process (GO:0048523): pvalue calculation completed
Negative Regulation of Cellular Process (GO:0048523): Calculation completed
Negative Regulation of Cellular Senescence (GO:2000773): Calculation started
Negative Regulation of Cellular Senescence (GO:2000773): scoring computed

Calculating pathways:  73%|███████▎  | 365/502 [30:36<12:36,  5.52s/it]

Negative Regulation of Cellular Senescence (GO:2000773): pvalue calculation completed
Negative Regulation of Cellular Senescence (GO:2000773): Calculation completed
Negative Regulation of Cytokine Production (GO:0001818): Calculation started
Negative Regulation of Cytokine Production (GO:0001818): scoring computed

Calculating pathways:  73%|███████▎  | 366/502 [30:41<12:22,  5.46s/it]

Negative Regulation of Cytokine Production (GO:0001818): pvalue calculation completed
Negative Regulation of Cytokine Production (GO:0001818): Calculation completed
Negative Regulation of Cytokine Production Involved in Immune Response (GO:0002719): Calculation started
Negative Regulation of Cytokine Production Involved in Immune Response (GO:0002719): scoring computed

Calculating pathways:  73%|███████▎  | 367/502 [30:45<10:55,  4.86s/it]

Negative Regulation of Cytokine Production Involved in Immune Response (GO:0002719): pvalue calculation completed
Negative Regulation of Cytokine Production Involved in Immune Response (GO:0002719): Calculation completed
Negative Regulation of Developmental Process (GO:0051093): Calculation started
Negative Regulation of Developmental Process (GO:0051093): scoring computed

Calculating pathways:  73%|███████▎  | 368/502 [30:49<10:32,  4.72s/it]

Negative Regulation of Developmental Process (GO:0051093): pvalue calculation completed
Negative Regulation of Developmental Process (GO:0051093): Calculation completed
Negative Regulation of Epithelial Cell Proliferation (GO:0050680): Calculation started
Negative Regulation of Epithelial Cell Proliferation (GO:0050680): scoring computed

Calculating pathways:  74%|███████▎  | 369/502 [30:53<10:00,  4.51s/it]

Negative Regulation of Epithelial Cell Proliferation (GO:0050680): pvalue calculation completed
Negative Regulation of Epithelial Cell Proliferation (GO:0050680): Calculation completed
Negative Regulation of Glycoprotein Biosynthetic Process (GO:0010561): Calculation started
Negative Regulation of Glycoprotein Biosynthetic Process (GO:0010561): scoring computed

Calculating pathways:  74%|███████▎  | 370/502 [30:56<09:11,  4.18s/it]

Negative Regulation of Glycoprotein Biosynthetic Process (GO:0010561): pvalue calculation completed
Negative Regulation of Glycoprotein Biosynthetic Process (GO:0010561): Calculation completed
Negative Regulation of Interleukin-10 Production (GO:0032693): Calculation started
Negative Regulation of Interleukin-10 Production (GO:0032693): scoring computed

Calculating pathways:  74%|███████▍  | 371/502 [31:00<08:39,  3.97s/it]

Negative Regulation of Interleukin-10 Production (GO:0032693): pvalue calculation completed
Negative Regulation of Interleukin-10 Production (GO:0032693): Calculation completed
Negative Regulation of Interleukin-12 Production (GO:0032695): Calculation started
Negative Regulation of Interleukin-12 Production (GO:0032695): scoring computed

Calculating pathways:  74%|███████▍  | 372/502 [31:03<08:14,  3.81s/it]

Negative Regulation of Interleukin-12 Production (GO:0032695): pvalue calculation completed
Negative Regulation of Interleukin-12 Production (GO:0032695): Calculation completed
Negative Regulation of Intracellular Signal Transduction (GO:1902532): Calculation started
Negative Regulation of Intracellular Signal Transduction (GO:1902532): scoring computed

Calculating pathways:  74%|███████▍  | 373/502 [31:10<09:44,  4.53s/it]

Negative Regulation of Intracellular Signal Transduction (GO:1902532): pvalue calculation completed
Negative Regulation of Intracellular Signal Transduction (GO:1902532): Calculation completed
Negative Regulation of Leukocyte Cell-Cell Adhesion (GO:1903038): Calculation started
Negative Regulation of Leukocyte Cell-Cell Adhesion (GO:1903038): scoring computed

Calculating pathways:  75%|███████▍  | 374/502 [31:13<09:00,  4.23s/it]

Negative Regulation of Leukocyte Cell-Cell Adhesion (GO:1903038): pvalue calculation completed
Negative Regulation of Leukocyte Cell-Cell Adhesion (GO:1903038): Calculation completed
Negative Regulation of Lymphocyte Activation (GO:0051250): Calculation started
Negative Regulation of Lymphocyte Activation (GO:0051250): scoring computed

Calculating pathways:  75%|███████▍  | 375/502 [31:17<08:35,  4.06s/it]

Negative Regulation of Lymphocyte Activation (GO:0051250): pvalue calculation completed
Negative Regulation of Lymphocyte Activation (GO:0051250): Calculation completed
Negative Regulation of Microtubule Polymerization (GO:0031115): Calculation started
Negative Regulation of Microtubule Polymerization (GO:0031115): scoring computed

Calculating pathways:  75%|███████▍  | 376/502 [31:20<08:11,  3.90s/it]

Negative Regulation of Microtubule Polymerization (GO:0031115): pvalue calculation completed
Negative Regulation of Microtubule Polymerization (GO:0031115): Calculation completed
Negative Regulation of Microtubule Polymerization or Depolymerization (GO:0031111): Calculation started
Negative Regulation of Microtubule Polymerization or Depolymerization (GO:0031111): scoring computed

Calculating pathways:  75%|███████▌  | 377/502 [31:24<07:58,  3.83s/it]

Negative Regulation of Microtubule Polymerization or Depolymerization (GO:0031111): pvalue calculation completed
Negative Regulation of Microtubule Polymerization or Depolymerization (GO:0031111): Calculation completed
Negative Regulation of Myeloid Cell Differentiation (GO:0045638): Calculation started
Negative Regulation of Myeloid Cell Differentiation (GO:0045638): scoring computed

Calculating pathways:  75%|███████▌  | 378/502 [31:27<07:44,  3.74s/it]

Negative Regulation of Myeloid Cell Differentiation (GO:0045638): pvalue calculation completed
Negative Regulation of Myeloid Cell Differentiation (GO:0045638): Calculation completed
Negative Regulation of Myeloid Leukocyte Differentiation (GO:0002762): Calculation started
Negative Regulation of Myeloid Leukocyte Differentiation (GO:0002762): scoring computed

Calculating pathways:  75%|███████▌  | 379/502 [31:31<07:37,  3.72s/it]

Negative Regulation of Myeloid Leukocyte Differentiation (GO:0002762): pvalue calculation completed
Negative Regulation of Myeloid Leukocyte Differentiation (GO:0002762): Calculation completed
Negative Regulation of Osteoblast Differentiation (GO:0045668): Calculation started
Negative Regulation of Osteoblast Differentiation (GO:0045668): scoring computed

Calculating pathways:  76%|███████▌  | 380/502 [31:35<07:37,  3.75s/it]

Negative Regulation of Osteoblast Differentiation (GO:0045668): pvalue calculation completed
Negative Regulation of Osteoblast Differentiation (GO:0045668): Calculation completed
Negative Regulation of Programmed Cell Death (GO:0043069): Calculation started
Negative Regulation of Programmed Cell Death (GO:0043069): scoring computed

Calculating pathways:  76%|███████▌  | 381/502 [31:42<09:47,  4.85s/it]

Negative Regulation of Programmed Cell Death (GO:0043069): pvalue calculation completed
Negative Regulation of Programmed Cell Death (GO:0043069): Calculation completed
Negative Regulation of Protein Localization (GO:1903828): Calculation started
Negative Regulation of Protein Localization (GO:1903828): scoring computed

Calculating pathways:  76%|███████▌  | 382/502 [31:46<09:06,  4.55s/it]

Negative Regulation of Protein Localization (GO:1903828): pvalue calculation completed
Negative Regulation of Protein Localization (GO:1903828): Calculation completed
Negative Regulation of Protein Polymerization (GO:0032272): Calculation started
Negative Regulation of Protein Polymerization (GO:0032272): scoring computed

Calculating pathways:  76%|███████▋  | 383/502 [31:50<08:27,  4.27s/it]

Negative Regulation of Protein Polymerization (GO:0032272): pvalue calculation completed
Negative Regulation of Protein Polymerization (GO:0032272): Calculation completed
Negative Regulation of Signal Transduction by P53 Class Mediator (GO:1901797): Calculation started
Negative Regulation of Signal Transduction by P53 Class Mediator (GO:1901797): scoring computed

Calculating pathways:  76%|███████▋  | 384/502 [31:53<07:56,  4.04s/it]

Negative Regulation of Signal Transduction by P53 Class Mediator (GO:1901797): pvalue calculation completed
Negative Regulation of Signal Transduction by P53 Class Mediator (GO:1901797): Calculation completed
Negative Regulation of Supramolecular Fiber Organization (GO:1902904): Calculation started
Negative Regulation of Supramolecular Fiber Organization (GO:1902904): scoring computed

Calculating pathways:  77%|███████▋  | 385/502 [31:57<07:54,  4.06s/it]

Negative Regulation of Supramolecular Fiber Organization (GO:1902904): pvalue calculation completed
Negative Regulation of Supramolecular Fiber Organization (GO:1902904): Calculation completed
Negative Regulation of Transcription by RNA Polymerase II (GO:0000122): Calculation started
Negative Regulation of Transcription by RNA Polymerase II (GO:0000122): scoring computed

Calculating pathways:  77%|███████▋  | 386/502 [32:08<11:37,  6.01s/it]

Negative Regulation of Transcription by RNA Polymerase II (GO:0000122): pvalue calculation completed
Negative Regulation of Transcription by RNA Polymerase II (GO:0000122): Calculation completed
Nervous System Development (GO:0007399): Calculation started
Nervous System Development (GO:0007399): scoring computed

Calculating pathways:  77%|███████▋  | 387/502 [32:16<12:37,  6.59s/it]

Nervous System Development (GO:0007399): pvalue calculation completed
Nervous System Development (GO:0007399): Calculation completed
Neurogenesis (GO:0022008): Calculation started
Neurogenesis (GO:0022008): scoring computed

Calculating pathways:  77%|███████▋  | 388/502 [32:20<10:58,  5.78s/it]

Neurogenesis (GO:0022008): pvalue calculation completed
Neurogenesis (GO:0022008): Calculation completed
Peptidyl-Serine Autophosphorylation (GO:0036289): Calculation started
Peptidyl-Serine Autophosphorylation (GO:0036289): scoring computed

Calculating pathways:  77%|███████▋  | 389/502 [32:23<09:30,  5.05s/it]

Peptidyl-Serine Autophosphorylation (GO:0036289): pvalue calculation completed
Peptidyl-Serine Autophosphorylation (GO:0036289): Calculation completed
Peptidyl-Serine Modification (GO:0018209): Calculation started
Peptidyl-Serine Modification (GO:0018209): scoring computed

Calculating pathways:  78%|███████▊  | 390/502 [32:27<08:55,  4.78s/it]

Peptidyl-Serine Modification (GO:0018209): pvalue calculation completed
Peptidyl-Serine Modification (GO:0018209): Calculation completed
Peptidyl-Serine Phosphorylation (GO:0018105): Calculation started
Peptidyl-Serine Phosphorylation (GO:0018105): scoring computed

Calculating pathways:  78%|███████▊  | 391/502 [32:31<08:27,  4.58s/it]

Peptidyl-Serine Phosphorylation (GO:0018105): pvalue calculation completed
Peptidyl-Serine Phosphorylation (GO:0018105): Calculation completed
Peptidyl-Threonine Modification (GO:0018210): Calculation started
Peptidyl-Threonine Modification (GO:0018210): scoring computed

Calculating pathways:  78%|███████▊  | 392/502 [32:35<07:57,  4.34s/it]

Peptidyl-Threonine Modification (GO:0018210): pvalue calculation completed
Peptidyl-Threonine Modification (GO:0018210): Calculation completed
Peptidyl-Threonine Phosphorylation (GO:0018107): Calculation started
Peptidyl-Threonine Phosphorylation (GO:0018107): scoring computed

Calculating pathways:  78%|███████▊  | 393/502 [32:39<07:31,  4.14s/it]

Peptidyl-Threonine Phosphorylation (GO:0018107): pvalue calculation completed
Peptidyl-Threonine Phosphorylation (GO:0018107): Calculation completed
Peptidyl-Tyrosine Autophosphorylation (GO:0038083): Calculation started
Peptidyl-Tyrosine Autophosphorylation (GO:0038083): scoring computed

Calculating pathways:  78%|███████▊  | 394/502 [32:42<07:03,  3.92s/it]

Peptidyl-Tyrosine Autophosphorylation (GO:0038083): pvalue calculation completed
Peptidyl-Tyrosine Autophosphorylation (GO:0038083): Calculation completed
Peptidyl-Tyrosine Modification (GO:0018212): Calculation started
Peptidyl-Tyrosine Modification (GO:0018212): scoring computed

Calculating pathways:  79%|███████▊  | 395/502 [32:46<06:55,  3.88s/it]

Peptidyl-Tyrosine Modification (GO:0018212): pvalue calculation completed
Peptidyl-Tyrosine Modification (GO:0018212): Calculation completed
Peptidyl-Tyrosine Phosphorylation (GO:0018108): Calculation started
Peptidyl-Tyrosine Phosphorylation (GO:0018108): scoring computed

Calculating pathways:  79%|███████▉  | 396/502 [32:50<06:55,  3.92s/it]

Peptidyl-Tyrosine Phosphorylation (GO:0018108): pvalue calculation completed
Peptidyl-Tyrosine Phosphorylation (GO:0018108): Calculation completed
Phosphorylation (GO:0016310): Calculation started
Phosphorylation (GO:0016310): scoring computed

Calculating pathways:  79%|███████▉  | 397/502 [32:57<08:22,  4.78s/it]

Phosphorylation (GO:0016310): pvalue calculation completed
Phosphorylation (GO:0016310): Calculation completed
Positive Regulation by Host of Viral Transcription (GO:0043923): Calculation started
Positive Regulation by Host of Viral Transcription (GO:0043923): scoring computed

Calculating pathways:  79%|███████▉  | 398/502 [33:00<07:37,  4.40s/it]

Positive Regulation by Host of Viral Transcription (GO:0043923): pvalue calculation completed
Positive Regulation by Host of Viral Transcription (GO:0043923): Calculation completed
Positive Regulation of DNA Metabolic Process (GO:0051054): Calculation started
Positive Regulation of DNA Metabolic Process (GO:0051054): scoring computed

Calculating pathways:  79%|███████▉  | 399/502 [33:05<07:37,  4.44s/it]

Positive Regulation of DNA Metabolic Process (GO:0051054): pvalue calculation completed
Positive Regulation of DNA Metabolic Process (GO:0051054): Calculation completed
Positive Regulation of DNA Replication (GO:0045740): Calculation started
Positive Regulation of DNA Replication (GO:0045740): scoring computed

Calculating pathways:  80%|███████▉  | 400/502 [33:08<07:05,  4.17s/it]

Positive Regulation of DNA Replication (GO:0045740): pvalue calculation completed
Positive Regulation of DNA Replication (GO:0045740): Calculation completed
Positive Regulation of DNA-templated Transcription (GO:0045893): Calculation started
Positive Regulation of DNA-templated Transcription (GO:0045893): scoring computed

Calculating pathways:  80%|███████▉  | 401/502 [33:25<13:01,  7.73s/it]

Positive Regulation of DNA-templated Transcription (GO:0045893): pvalue calculation completed
Positive Regulation of DNA-templated Transcription (GO:0045893): Calculation completed
Positive Regulation of DNA-templated Transcription, Elongation (GO:0032786): Calculation started
Positive Regulation of DNA-templated Transcription, Elongation (GO:0032786): scoring computed

Calculating pathways:  80%|████████  | 402/502 [33:29<11:05,  6.66s/it]

Positive Regulation of DNA-templated Transcription, Elongation (GO:0032786): pvalue calculation completed
Positive Regulation of DNA-templated Transcription, Elongation (GO:0032786): Calculation completed
Positive Regulation of G1/S Transition of Mitotic Cell Cycle (GO:1900087): Calculation started
Positive Regulation of G1/S Transition of Mitotic Cell Cycle (GO:1900087): scoring computed

Calculating pathways:  80%|████████  | 403/502 [33:33<09:42,  5.88s/it]

Positive Regulation of G1/S Transition of Mitotic Cell Cycle (GO:1900087): pvalue calculation completed
Positive Regulation of G1/S Transition of Mitotic Cell Cycle (GO:1900087): Calculation completed
Positive Regulation of G2/M Transition of Mitotic Cell Cycle (GO:0010971): Calculation started
Positive Regulation of G2/M Transition of Mitotic Cell Cycle (GO:0010971): scoring computed

Calculating pathways:  80%|████████  | 404/502 [33:37<08:34,  5.25s/it]

Positive Regulation of G2/M Transition of Mitotic Cell Cycle (GO:0010971): pvalue calculation completed
Positive Regulation of G2/M Transition of Mitotic Cell Cycle (GO:0010971): Calculation completed
Positive Regulation of MAP Kinase Activity (GO:0043406): Calculation started
Positive Regulation of MAP Kinase Activity (GO:0043406): scoring computed

Calculating pathways:  81%|████████  | 405/502 [33:41<07:56,  4.91s/it]

Positive Regulation of MAP Kinase Activity (GO:0043406): pvalue calculation completed
Positive Regulation of MAP Kinase Activity (GO:0043406): Calculation completed
Positive Regulation of MAPK Cascade (GO:0043410): Calculation started
Positive Regulation of MAPK Cascade (GO:0043410): scoring computed

Calculating pathways:  81%|████████  | 406/502 [33:48<09:05,  5.68s/it]

Positive Regulation of MAPK Cascade (GO:0043410): pvalue calculation completed
Positive Regulation of MAPK Cascade (GO:0043410): Calculation completed
Positive Regulation of RNA Biosynthetic Process (GO:1902680): Calculation started
Positive Regulation of RNA Biosynthetic Process (GO:1902680): scoring computed

Calculating pathways:  81%|████████  | 407/502 [33:58<10:53,  6.88s/it]

Positive Regulation of RNA Biosynthetic Process (GO:1902680): pvalue calculation completed
Positive Regulation of RNA Biosynthetic Process (GO:1902680): Calculation completed
Positive Regulation of RNA Splicing (GO:0033120): Calculation started
Positive Regulation of RNA Splicing (GO:0033120): scoring computed

Calculating pathways:  81%|████████▏ | 408/502 [34:02<09:18,  5.94s/it]

Positive Regulation of RNA Splicing (GO:0033120): pvalue calculation completed
Positive Regulation of RNA Splicing (GO:0033120): Calculation completed
Positive Regulation of Cell Activation (GO:0050867): Calculation started
Positive Regulation of Cell Activation (GO:0050867): scoring computed

Calculating pathways:  81%|████████▏ | 409/502 [34:05<08:10,  5.27s/it]

Positive Regulation of Cell Activation (GO:0050867): pvalue calculation completed
Positive Regulation of Cell Activation (GO:0050867): Calculation completed
Positive Regulation of Cell Cycle G1/S Phase Transition (GO:1902808): Calculation started
Positive Regulation of Cell Cycle G1/S Phase Transition (GO:1902808): scoring computed

Calculating pathways:  82%|████████▏ | 410/502 [34:09<07:34,  4.94s/it]

Positive Regulation of Cell Cycle G1/S Phase Transition (GO:1902808): pvalue calculation completed
Positive Regulation of Cell Cycle G1/S Phase Transition (GO:1902808): Calculation completed
Positive Regulation of Cell Cycle G2/M Phase Transition (GO:1902751): Calculation started
Positive Regulation of Cell Cycle G2/M Phase Transition (GO:1902751): scoring computed

Calculating pathways:  82%|████████▏ | 411/502 [34:13<06:54,  4.55s/it]

Positive Regulation of Cell Cycle G2/M Phase Transition (GO:1902751): pvalue calculation completed
Positive Regulation of Cell Cycle G2/M Phase Transition (GO:1902751): Calculation completed
Positive Regulation of Cell Differentiation (GO:0045597): Calculation started
Positive Regulation of Cell Differentiation (GO:0045597): scoring computed

Calculating pathways:  82%|████████▏ | 412/502 [34:20<07:48,  5.21s/it]

Positive Regulation of Cell Differentiation (GO:0045597): pvalue calculation completed
Positive Regulation of Cell Differentiation (GO:0045597): Calculation completed
Positive Regulation of Cell Growth (GO:0030307): Calculation started
Positive Regulation of Cell Growth (GO:0030307): scoring computed

Calculating pathways:  82%|████████▏ | 413/502 [34:24<07:27,  5.02s/it]

Positive Regulation of Cell Growth (GO:0030307): pvalue calculation completed
Positive Regulation of Cell Growth (GO:0030307): Calculation completed
Positive Regulation of Cell Population Proliferation (GO:0008284): Calculation started
Positive Regulation of Cell Population Proliferation (GO:0008284): scoring computed

Calculating pathways:  82%|████████▏ | 414/502 [34:33<08:57,  6.11s/it]

Positive Regulation of Cell Population Proliferation (GO:0008284): pvalue calculation completed
Positive Regulation of Cell Population Proliferation (GO:0008284): Calculation completed
Positive Regulation of Cell-Matrix Adhesion (GO:0001954): Calculation started
Positive Regulation of Cell-Matrix Adhesion (GO:0001954): scoring computed

Calculating pathways:  83%|████████▎ | 415/502 [34:37<07:56,  5.47s/it]

Positive Regulation of Cell-Matrix Adhesion (GO:0001954): pvalue calculation completed
Positive Regulation of Cell-Matrix Adhesion (GO:0001954): Calculation completed
Positive Regulation of Cell-Substrate Adhesion (GO:0010811): Calculation started
Positive Regulation of Cell-Substrate Adhesion (GO:0010811): scoring computed

Calculating pathways:  83%|████████▎ | 416/502 [34:41<07:17,  5.08s/it]

Positive Regulation of Cell-Substrate Adhesion (GO:0010811): pvalue calculation completed
Positive Regulation of Cell-Substrate Adhesion (GO:0010811): Calculation completed
Positive Regulation of Cellular Component Biogenesis (GO:0044089): Calculation started
Positive Regulation of Cellular Component Biogenesis (GO:0044089): scoring computed

Calculating pathways:  83%|████████▎ | 417/502 [34:46<06:59,  4.93s/it]

Positive Regulation of Cellular Component Biogenesis (GO:0044089): pvalue calculation completed
Positive Regulation of Cellular Component Biogenesis (GO:0044089): Calculation completed
Positive Regulation of Cellular Process (GO:0048522): Calculation started
Positive Regulation of Cellular Process (GO:0048522): scoring computed

Calculating pathways:  83%|████████▎ | 418/502 [34:56<09:03,  6.47s/it]

Positive Regulation of Cellular Process (GO:0048522): pvalue calculation completed
Positive Regulation of Cellular Process (GO:0048522): Calculation completed
Positive Regulation of Developmental Process (GO:0051094): Calculation started
Positive Regulation of Developmental Process (GO:0051094): scoring computed

Calculating pathways:  83%|████████▎ | 419/502 [35:02<08:54,  6.45s/it]

Positive Regulation of Developmental Process (GO:0051094): pvalue calculation completed
Positive Regulation of Developmental Process (GO:0051094): Calculation completed
Positive Regulation of Fibroblast Proliferation (GO:0048146): Calculation started
Positive Regulation of Fibroblast Proliferation (GO:0048146): scoring computed

Calculating pathways:  84%|████████▎ | 420/502 [35:06<07:44,  5.66s/it]

Positive Regulation of Fibroblast Proliferation (GO:0048146): pvalue calculation completed
Positive Regulation of Fibroblast Proliferation (GO:0048146): Calculation completed
Positive Regulation of Gene Expression (GO:0010628): Calculation started
Positive Regulation of Gene Expression (GO:0010628): scoring computed

Calculating pathways:  84%|████████▍ | 421/502 [35:14<08:43,  6.46s/it]

Positive Regulation of Gene Expression (GO:0010628): pvalue calculation completed
Positive Regulation of Gene Expression (GO:0010628): Calculation completed
Positive Regulation of Growth (GO:0045927): Calculation started
Positive Regulation of Growth (GO:0045927): scoring computed

Calculating pathways:  84%|████████▍ | 422/502 [35:19<07:44,  5.80s/it]

Positive Regulation of Growth (GO:0045927): pvalue calculation completed
Positive Regulation of Growth (GO:0045927): Calculation completed
Positive Regulation of Intracellular Signal Transduction (GO:1902533): Calculation started
Positive Regulation of Intracellular Signal Transduction (GO:1902533): scoring computed

Calculating pathways:  84%|████████▍ | 423/502 [35:29<09:32,  7.25s/it]

Positive Regulation of Intracellular Signal Transduction (GO:1902533): pvalue calculation completed
Positive Regulation of Intracellular Signal Transduction (GO:1902533): Calculation completed
Positive Regulation of Mitotic Cell Cycle Phase Transition (GO:1901992): Calculation started
Positive Regulation of Mitotic Cell Cycle Phase Transition (GO:1901992): scoring computed

Calculating pathways:  84%|████████▍ | 424/502 [35:34<08:14,  6.34s/it]

Positive Regulation of Mitotic Cell Cycle Phase Transition (GO:1901992): pvalue calculation completed
Positive Regulation of Mitotic Cell Cycle Phase Transition (GO:1901992): Calculation completed
Positive Regulation of Peptidyl-Tyrosine Phosphorylation (GO:0050731): Calculation started
Positive Regulation of Peptidyl-Tyrosine Phosphorylation (GO:0050731): scoring computed

Calculating pathways:  85%|████████▍ | 425/502 [35:38<07:21,  5.73s/it]

Positive Regulation of Peptidyl-Tyrosine Phosphorylation (GO:0050731): pvalue calculation completed
Positive Regulation of Peptidyl-Tyrosine Phosphorylation (GO:0050731): Calculation completed
+ Reg of Phosphatidylinositol 3-Kinase/Prot Kinase B Signal Transduction (GO:0051897): Calculation started
+ Reg of Phosphatidylinositol 3-Kinase/Prot Kinase B Signal Transduction (GO:0051897): scoring computed

Calculating pathways:  85%|████████▍ | 426/502 [35:43<07:12,  5.69s/it]

+ Reg of Phosphatidylinositol 3-Kinase/Prot Kinase B Signal Transduction (GO:0051897): pvalue calculation completed
+ Reg of Phosphatidylinositol 3-Kinase/Prot Kinase B Signal Transduction (GO:0051897): Calculation completed
Positive Regulation of Protein Localization (GO:1903829): Calculation started
Positive Regulation of Protein Localization (GO:1903829): scoring computed

Calculating pathways:  85%|████████▌ | 427/502 [35:48<06:46,  5.42s/it]

Positive Regulation of Protein Localization (GO:1903829): pvalue calculation completed
Positive Regulation of Protein Localization (GO:1903829): Calculation completed
Positive Regulation of Protein Serine/Threonine Kinase Activity (GO:0071902): Calculation started
Positive Regulation of Protein Serine/Threonine Kinase Activity (GO:0071902): scoring computed

Calculating pathways:  85%|████████▌ | 428/502 [35:52<06:14,  5.06s/it]

Positive Regulation of Protein Serine/Threonine Kinase Activity (GO:0071902): pvalue calculation completed
Positive Regulation of Protein Serine/Threonine Kinase Activity (GO:0071902): Calculation completed
Positive Regulation of Transcription by RNA Polymerase II (GO:0045944): Calculation started
Positive Regulation of Transcription by RNA Polymerase II (GO:0045944): scoring computed

Calculating pathways:  85%|████████▌ | 429/502 [36:06<09:16,  7.62s/it]

Positive Regulation of Transcription by RNA Polymerase II (GO:0045944): pvalue calculation completed
Positive Regulation of Transcription by RNA Polymerase II (GO:0045944): Calculation completed
Positive Regulation of Transcription Elongation by RNA Polymerase II (GO:0032968): Calculation started
Positive Regulation of Transcription Elongation by RNA Polymerase II (GO:0032968): scoring computed

Calculating pathways:  86%|████████▌ | 430/502 [36:10<07:49,  6.53s/it]

Positive Regulation of Transcription Elongation by RNA Polymerase II (GO:0032968): pvalue calculation completed
Positive Regulation of Transcription Elongation by RNA Polymerase II (GO:0032968): Calculation completed
Positive Regulation of Tyrosine Phosphorylation of STAT Protein (GO:0042531): Calculation started
Positive Regulation of Tyrosine Phosphorylation of STAT Protein (GO:0042531): scoring computed

Calculating pathways:  86%|████████▌ | 431/502 [36:14<06:40,  5.64s/it]

Positive Regulation of Tyrosine Phosphorylation of STAT Protein (GO:0042531): pvalue calculation completed
Positive Regulation of Tyrosine Phosphorylation of STAT Protein (GO:0042531): Calculation completed
Post-Translational Protein Modification (GO:0043687): Calculation started
Post-Translational Protein Modification (GO:0043687): scoring computed

Calculating pathways:  86%|████████▌ | 432/502 [36:18<06:00,  5.15s/it]

Post-Translational Protein Modification (GO:0043687): pvalue calculation completed
Post-Translational Protein Modification (GO:0043687): Calculation completed
Protein Autophosphorylation (GO:0046777): Calculation started
Protein Autophosphorylation (GO:0046777): scoring computed

Calculating pathways:  86%|████████▋ | 433/502 [36:23<05:58,  5.19s/it]

Protein Autophosphorylation (GO:0046777): pvalue calculation completed
Protein Autophosphorylation (GO:0046777): Calculation completed
Protein Modification Process (GO:0036211): Calculation started
Protein Modification Process (GO:0036211): scoring computed

Calculating pathways:  86%|████████▋ | 434/502 [36:32<07:24,  6.53s/it]

Protein Modification Process (GO:0036211): pvalue calculation completed
Protein Modification Process (GO:0036211): Calculation completed
Protein Phosphorylation (GO:0006468): Calculation started
Protein Phosphorylation (GO:0006468): scoring computed

Calculating pathways:  87%|████████▋ | 435/502 [36:40<07:45,  6.94s/it]

Protein Phosphorylation (GO:0006468): pvalue calculation completed
Protein Phosphorylation (GO:0006468): Calculation completed
Regulation of DNA Damage Response, Signal Transduction by P53 Class Mediator (GO:0043516): Calculation started
Regulation of DNA Damage Response, Signal Transduction by P53 Class Mediator (GO:0043516): scoring computed

Calculating pathways:  87%|████████▋ | 436/502 [36:44<06:39,  6.05s/it]

Regulation of DNA Damage Response, Signal Transduction by P53 Class Mediator (GO:0043516): pvalue calculation completed
Regulation of DNA Damage Response, Signal Transduction by P53 Class Mediator (GO:0043516): Calculation completed
Regulation of DNA Metabolic Process (GO:0051052): Calculation started
Regulation of DNA Metabolic Process (GO:0051052): scoring computed

Calculating pathways:  87%|████████▋ | 437/502 [36:50<06:15,  5.78s/it]

Regulation of DNA Metabolic Process (GO:0051052): pvalue calculation completed
Regulation of DNA Metabolic Process (GO:0051052): Calculation completed
Regulation of DNA Repair (GO:0006282): Calculation started
Regulation of DNA Repair (GO:0006282): scoring computed

Calculating pathways:  87%|████████▋ | 438/502 [36:55<06:00,  5.63s/it]

Regulation of DNA Repair (GO:0006282): pvalue calculation completed
Regulation of DNA Repair (GO:0006282): Calculation completed
Regulation of DNA Replication (GO:0006275): Calculation started
Regulation of DNA Replication (GO:0006275): scoring computed

Calculating pathways:  87%|████████▋ | 439/502 [36:59<05:29,  5.22s/it]

Regulation of DNA Replication (GO:0006275): pvalue calculation completed
Regulation of DNA Replication (GO:0006275): Calculation completed
Regulation of DNA-templated Transcription Initiation (GO:2000142): Calculation started
Regulation of DNA-templated Transcription Initiation (GO:2000142): scoring computed

Calculating pathways:  88%|████████▊ | 440/502 [37:03<04:55,  4.77s/it]

Regulation of DNA-templated Transcription Initiation (GO:2000142): pvalue calculation completed
Regulation of DNA-templated Transcription Initiation (GO:2000142): Calculation completed
Regulation of G1/S Transition of Mitotic Cell Cycle (GO:2000045): Calculation started
Regulation of G1/S Transition of Mitotic Cell Cycle (GO:2000045): scoring computed

Calculating pathways:  88%|████████▊ | 441/502 [37:08<04:54,  4.82s/it]

Regulation of G1/S Transition of Mitotic Cell Cycle (GO:2000045): pvalue calculation completed
Regulation of G1/S Transition of Mitotic Cell Cycle (GO:2000045): Calculation completed
Regulation of G2/M Transition of Mitotic Cell Cycle (GO:0010389): Calculation started
Regulation of G2/M Transition of Mitotic Cell Cycle (GO:0010389): scoring computed

Calculating pathways:  88%|████████▊ | 442/502 [37:12<04:31,  4.53s/it]

Regulation of G2/M Transition of Mitotic Cell Cycle (GO:0010389): pvalue calculation completed
Regulation of G2/M Transition of Mitotic Cell Cycle (GO:0010389): Calculation completed
Regulation of MAP Kinase Activity (GO:0043405): Calculation started
Regulation of MAP Kinase Activity (GO:0043405): scoring computed

Calculating pathways:  88%|████████▊ | 443/502 [37:16<04:22,  4.45s/it]

Regulation of MAP Kinase Activity (GO:0043405): pvalue calculation completed
Regulation of MAP Kinase Activity (GO:0043405): Calculation completed
Regulation of MAPK Cascade (GO:0043408): Calculation started
Regulation of MAPK Cascade (GO:0043408): scoring computed

Calculating pathways:  88%|████████▊ | 444/502 [37:22<04:51,  5.03s/it]

Regulation of MAPK Cascade (GO:0043408): pvalue calculation completed
Regulation of MAPK Cascade (GO:0043408): Calculation completed
Regulation of RNA Splicing (GO:0043484): Calculation started
Regulation of RNA Splicing (GO:0043484): scoring computed

Calculating pathways:  89%|████████▊ | 445/502 [37:27<04:44,  5.00s/it]

Regulation of RNA Splicing (GO:0043484): pvalue calculation completed
Regulation of RNA Splicing (GO:0043484): Calculation completed
Regulation of T Cell Activation (GO:0050863): Calculation started
Regulation of T Cell Activation (GO:0050863): scoring computed

Calculating pathways:  89%|████████▉ | 446/502 [37:31<04:27,  4.78s/it]

Regulation of T Cell Activation (GO:0050863): pvalue calculation completed
Regulation of T Cell Activation (GO:0050863): Calculation completed
Regulation of T Cell Apoptotic Process (GO:0070232): Calculation started
Regulation of T Cell Apoptotic Process (GO:0070232): scoring computed

Calculating pathways:  89%|████████▉ | 447/502 [37:35<04:02,  4.41s/it]

Regulation of T Cell Apoptotic Process (GO:0070232): pvalue calculation completed
Regulation of T Cell Apoptotic Process (GO:0070232): Calculation completed
Regulation of T-helper 1 Cell Differentiation (GO:0045625): Calculation started
Regulation of T-helper 1 Cell Differentiation (GO:0045625): scoring computed

Calculating pathways:  89%|████████▉ | 448/502 [37:39<03:46,  4.20s/it]

Regulation of T-helper 1 Cell Differentiation (GO:0045625): pvalue calculation completed
Regulation of T-helper 1 Cell Differentiation (GO:0045625): Calculation completed
Regulation of T-helper 17 Cell Lineage Commitment (GO:2000328): Calculation started
Regulation of T-helper 17 Cell Lineage Commitment (GO:2000328): scoring computed

Calculating pathways:  89%|████████▉ | 449/502 [37:42<03:33,  4.03s/it]

Regulation of T-helper 17 Cell Lineage Commitment (GO:2000328): pvalue calculation completed
Regulation of T-helper 17 Cell Lineage Commitment (GO:2000328): Calculation completed
Regulation of TOR Signaling (GO:0032006): Calculation started
Regulation of TOR Signaling (GO:0032006): scoring computed

Calculating pathways:  90%|████████▉ | 450/502 [37:47<03:34,  4.13s/it]

Regulation of TOR Signaling (GO:0032006): pvalue calculation completed
Regulation of TOR Signaling (GO:0032006): Calculation completed
Regulation of Apoptotic Process (GO:0042981): Calculation started
Regulation of Apoptotic Process (GO:0042981): scoring computed

Calculating pathways:  90%|████████▉ | 451/502 [37:58<05:16,  6.22s/it]

Regulation of Apoptotic Process (GO:0042981): pvalue calculation completed
Regulation of Apoptotic Process (GO:0042981): Calculation completed
Regulation of Cell Cycle (GO:0051726): Calculation started
Regulation of Cell Cycle (GO:0051726): scoring computed

Calculating pathways:  90%|█████████ | 452/502 [38:05<05:26,  6.53s/it]

Regulation of Cell Cycle (GO:0051726): pvalue calculation completed
Regulation of Cell Cycle (GO:0051726): Calculation completed
Regulation of Cell Cycle G2/M Phase Transition (GO:1902749): Calculation started
Regulation of Cell Cycle G2/M Phase Transition (GO:1902749): scoring computed

Calculating pathways:  90%|█████████ | 453/502 [38:09<04:37,  5.67s/it]

Regulation of Cell Cycle G2/M Phase Transition (GO:1902749): pvalue calculation completed
Regulation of Cell Cycle G2/M Phase Transition (GO:1902749): Calculation completed
Regulation of Cell Differentiation (GO:0045595): Calculation started
Regulation of Cell Differentiation (GO:0045595): scoring computed

Calculating pathways:  90%|█████████ | 454/502 [38:15<04:36,  5.75s/it]

Regulation of Cell Differentiation (GO:0045595): pvalue calculation completed
Regulation of Cell Differentiation (GO:0045595): Calculation completed
Regulation of Cell Growth (GO:0001558): Calculation started
Regulation of Cell Growth (GO:0001558): scoring computed

Calculating pathways:  91%|█████████ | 455/502 [38:21<04:36,  5.88s/it]

Regulation of Cell Growth (GO:0001558): pvalue calculation completed
Regulation of Cell Growth (GO:0001558): Calculation completed
Regulation of Cell Motility (GO:2000145): Calculation started
Regulation of Cell Motility (GO:2000145): scoring computed

Calculating pathways:  91%|█████████ | 456/502 [38:26<04:17,  5.60s/it]

Regulation of Cell Motility (GO:2000145): pvalue calculation completed
Regulation of Cell Motility (GO:2000145): Calculation completed
Regulation of Cell Population Proliferation (GO:0042127): Calculation started
Regulation of Cell Population Proliferation (GO:0042127): scoring computed

Calculating pathways:  91%|█████████ | 457/502 [38:37<05:32,  7.38s/it]

Regulation of Cell Population Proliferation (GO:0042127): pvalue calculation completed
Regulation of Cell Population Proliferation (GO:0042127): Calculation completed
Regulation of Cell-Matrix Adhesion (GO:0001952): Calculation started
Regulation of Cell-Matrix Adhesion (GO:0001952): scoring computed

Calculating pathways:  91%|█████████ | 458/502 [38:42<04:43,  6.45s/it]

Regulation of Cell-Matrix Adhesion (GO:0001952): pvalue calculation completed
Regulation of Cell-Matrix Adhesion (GO:0001952): Calculation completed
Regulation of Cellular Response to Stress (GO:0080135): Calculation started
Regulation of Cellular Response to Stress (GO:0080135): scoring computed

Calculating pathways:  91%|█████████▏| 459/502 [38:46<04:17,  5.99s/it]

Regulation of Cellular Response to Stress (GO:0080135): pvalue calculation completed
Regulation of Cellular Response to Stress (GO:0080135): Calculation completed
Regulation of Cellular Senescence (GO:2000772): Calculation started
Regulation of Cellular Senescence (GO:2000772): scoring computed

Calculating pathways:  92%|█████████▏| 460/502 [38:50<03:46,  5.39s/it]

Regulation of Cellular Senescence (GO:2000772): pvalue calculation completed
Regulation of Cellular Senescence (GO:2000772): Calculation completed
Regulation of Epithelial Cell Proliferation (GO:0050678): Calculation started
Regulation of Epithelial Cell Proliferation (GO:0050678): scoring computed

Calculating pathways:  92%|█████████▏| 461/502 [38:55<03:30,  5.14s/it]

Regulation of Epithelial Cell Proliferation (GO:0050678): pvalue calculation completed
Regulation of Epithelial Cell Proliferation (GO:0050678): Calculation completed
Regulation of Erythrocyte Differentiation (GO:0045646): Calculation started
Regulation of Erythrocyte Differentiation (GO:0045646): scoring computed

Calculating pathways:  92%|█████████▏| 462/502 [38:59<03:11,  4.78s/it]

Regulation of Erythrocyte Differentiation (GO:0045646): pvalue calculation completed
Regulation of Erythrocyte Differentiation (GO:0045646): Calculation completed
Regulation of Fibroblast Proliferation (GO:0048145): Calculation started
Regulation of Fibroblast Proliferation (GO:0048145): scoring computed

Calculating pathways:  92%|█████████▏| 463/502 [39:03<02:58,  4.58s/it]

Regulation of Fibroblast Proliferation (GO:0048145): pvalue calculation completed
Regulation of Fibroblast Proliferation (GO:0048145): Calculation completed
Regulation of Gene Expression (GO:0010468): Calculation started
Regulation of Gene Expression (GO:0010468): scoring computed

Calculating pathways:  92%|█████████▏| 464/502 [39:18<04:51,  7.67s/it]

Regulation of Gene Expression (GO:0010468): pvalue calculation completed
Regulation of Gene Expression (GO:0010468): Calculation completed
Regulation of Interleukin-10 Production (GO:0032653): Calculation started
Regulation of Interleukin-10 Production (GO:0032653): scoring computed

Calculating pathways:  93%|█████████▎| 465/502 [39:22<04:01,  6.53s/it]

Regulation of Interleukin-10 Production (GO:0032653): pvalue calculation completed
Regulation of Interleukin-10 Production (GO:0032653): Calculation completed
Regulation of Interleukin-12 Production (GO:0032655): Calculation started
Regulation of Interleukin-12 Production (GO:0032655): scoring computed

Calculating pathways:  93%|█████████▎| 466/502 [39:26<03:28,  5.80s/it]

Regulation of Interleukin-12 Production (GO:0032655): pvalue calculation completed
Regulation of Interleukin-12 Production (GO:0032655): Calculation completed
Regulation of Lymphocyte Apoptotic Process (GO:0070228): Calculation started
Regulation of Lymphocyte Apoptotic Process (GO:0070228): scoring computed

Calculating pathways:  93%|█████████▎| 467/502 [39:29<02:58,  5.10s/it]

Regulation of Lymphocyte Apoptotic Process (GO:0070228): pvalue calculation completed
Regulation of Lymphocyte Apoptotic Process (GO:0070228): Calculation completed
Regulation of mRNA 3'-End Processing (GO:0031440): Calculation started
Regulation of mRNA 3'-End Processing (GO:0031440): scoring computed

Calculating pathways:  93%|█████████▎| 468/502 [39:33<02:37,  4.64s/it]

Regulation of mRNA 3'-End Processing (GO:0031440): pvalue calculation completed
Regulation of mRNA 3'-End Processing (GO:0031440): Calculation completed
Regulation of mRNA Processing (GO:0050684): Calculation started
Regulation of mRNA Processing (GO:0050684): scoring computed

Calculating pathways:  93%|█████████▎| 469/502 [39:37<02:24,  4.39s/it]

Regulation of mRNA Processing (GO:0050684): pvalue calculation completed
Regulation of mRNA Processing (GO:0050684): Calculation completed
Regulation of Macromolecule Biosynthetic Process (GO:0010556): Calculation started
Regulation of Macromolecule Biosynthetic Process (GO:0010556): scoring computed

Calculating pathways:  94%|█████████▎| 470/502 [39:42<02:28,  4.66s/it]

Regulation of Macromolecule Biosynthetic Process (GO:0010556): pvalue calculation completed
Regulation of Macromolecule Biosynthetic Process (GO:0010556): Calculation completed
Regulation of Microtubule Polymerization (GO:0031113): Calculation started
Regulation of Microtubule Polymerization (GO:0031113): scoring computed

Calculating pathways:  94%|█████████▍| 471/502 [39:46<02:18,  4.48s/it]

Regulation of Microtubule Polymerization (GO:0031113): pvalue calculation completed
Regulation of Microtubule Polymerization (GO:0031113): Calculation completed
Regulation of Mitotic Cell Cycle (GO:0007346): Calculation started
Regulation of Mitotic Cell Cycle (GO:0007346): scoring computed

Calculating pathways:  94%|█████████▍| 472/502 [39:51<02:19,  4.66s/it]

Regulation of Mitotic Cell Cycle (GO:0007346): pvalue calculation completed
Regulation of Mitotic Cell Cycle (GO:0007346): Calculation completed
Regulation of Mitotic Cell Cycle Phase Transition (GO:1901990): Calculation started
Regulation of Mitotic Cell Cycle Phase Transition (GO:1901990): scoring computed

Calculating pathways:  94%|█████████▍| 473/502 [39:56<02:12,  4.58s/it]

Regulation of Mitotic Cell Cycle Phase Transition (GO:1901990): pvalue calculation completed
Regulation of Mitotic Cell Cycle Phase Transition (GO:1901990): Calculation completed
Regulation of Monocyte Differentiation (GO:0045655): Calculation started
Regulation of Monocyte Differentiation (GO:0045655): scoring computed

Calculating pathways:  94%|█████████▍| 474/502 [39:59<01:59,  4.27s/it]

Regulation of Monocyte Differentiation (GO:0045655): pvalue calculation completed
Regulation of Monocyte Differentiation (GO:0045655): Calculation completed
Regulation of Muscle Cell Differentiation (GO:0051147): Calculation started
Regulation of Muscle Cell Differentiation (GO:0051147): scoring computed

Calculating pathways:  95%|█████████▍| 475/502 [40:03<01:50,  4.08s/it]

Regulation of Muscle Cell Differentiation (GO:0051147): pvalue calculation completed
Regulation of Muscle Cell Differentiation (GO:0051147): Calculation completed
Regulation of Myeloid Cell Differentiation (GO:0045637): Calculation started
Regulation of Myeloid Cell Differentiation (GO:0045637): scoring computed

Calculating pathways:  95%|█████████▍| 476/502 [40:06<01:42,  3.95s/it]

Regulation of Myeloid Cell Differentiation (GO:0045637): pvalue calculation completed
Regulation of Myeloid Cell Differentiation (GO:0045637): Calculation completed
Regulation of Osteoblast Differentiation (GO:0045667): Calculation started
Regulation of Osteoblast Differentiation (GO:0045667): scoring computed

Calculating pathways:  95%|█████████▌| 477/502 [40:11<01:42,  4.11s/it]

Regulation of Osteoblast Differentiation (GO:0045667): pvalue calculation completed
Regulation of Osteoblast Differentiation (GO:0045667): Calculation completed
Regulation of Phosphatidylinositol 3-Kinase/Protein Kinase B Signal Transduction (GO:0051896): Calculation started
Regulation of Phosphatidylinositol 3-Kinase/Protein Kinase B Signal Transduction (GO:0051896): scoring computed

Calculating pathways:  95%|█████████▌| 478/502 [40:17<01:52,  4.70s/it]

Regulation of Phosphatidylinositol 3-Kinase/Protein Kinase B Signal Transduction (GO:0051896): pvalue calculation completed
Regulation of Phosphatidylinositol 3-Kinase/Protein Kinase B Signal Transduction (GO:0051896): Calculation completed
Regulation of Programmed Cell Death (GO:0043067): Calculation started
Regulation of Programmed Cell Death (GO:0043067): scoring computed

Calculating pathways:  95%|█████████▌| 479/502 [40:23<01:54,  5.00s/it]

Regulation of Programmed Cell Death (GO:0043067): pvalue calculation completed
Regulation of Programmed Cell Death (GO:0043067): Calculation completed
Regulation of Proteasomal Ubiquitin-Dependent Protein Catabolic Process (GO:0032434): Calculation started
Regulation of Proteasomal Ubiquitin-Dependent Protein Catabolic Process (GO:0032434): scoring computed

Calculating pathways:  96%|█████████▌| 480/502 [40:27<01:48,  4.94s/it]

Regulation of Proteasomal Ubiquitin-Dependent Protein Catabolic Process (GO:0032434): pvalue calculation completed
Regulation of Proteasomal Ubiquitin-Dependent Protein Catabolic Process (GO:0032434): Calculation completed
Regulation of Receptor Signaling Pathway via JAK-STAT (GO:0046425): Calculation started
Regulation of Receptor Signaling Pathway via JAK-STAT (GO:0046425): scoring computed

Calculating pathways:  96%|█████████▌| 481/502 [40:31<01:38,  4.67s/it]

Regulation of Receptor Signaling Pathway via JAK-STAT (GO:0046425): pvalue calculation completed
Regulation of Receptor Signaling Pathway via JAK-STAT (GO:0046425): Calculation completed
Regulation of Receptor Signaling Pathway via STAT (GO:1904892): Calculation started
Regulation of Receptor Signaling Pathway via STAT (GO:1904892): scoring computed

Calculating pathways:  96%|█████████▌| 482/502 [40:35<01:26,  4.34s/it]

Regulation of Receptor Signaling Pathway via STAT (GO:1904892): pvalue calculation completed
Regulation of Receptor Signaling Pathway via STAT (GO:1904892): Calculation completed
Regulation of Thymocyte Apoptotic Process (GO:0070243): Calculation started
Regulation of Thymocyte Apoptotic Process (GO:0070243): scoring computed

Calculating pathways:  96%|█████████▌| 483/502 [40:39<01:18,  4.12s/it]

Regulation of Thymocyte Apoptotic Process (GO:0070243): pvalue calculation completed
Regulation of Thymocyte Apoptotic Process (GO:0070243): Calculation completed
Regulation of Transcription Elongation by RNA Polymerase II (GO:0034243): Calculation started
Regulation of Transcription Elongation by RNA Polymerase II (GO:0034243): scoring computed

Calculating pathways:  96%|█████████▋| 484/502 [40:43<01:15,  4.19s/it]

Regulation of Transcription Elongation by RNA Polymerase II (GO:0034243): pvalue calculation completed
Regulation of Transcription Elongation by RNA Polymerase II (GO:0034243): Calculation completed
Regulation of Translation (GO:0006417): Calculation started
Regulation of Translation (GO:0006417): scoring computed

Calculating pathways:  97%|█████████▋| 485/502 [40:49<01:20,  4.73s/it]

Regulation of Translation (GO:0006417): pvalue calculation completed
Regulation of Translation (GO:0006417): Calculation completed
Regulation of Translation in Response to Stress (GO:0043555): Calculation started
Regulation of Translation in Response to Stress (GO:0043555): scoring computed

Calculating pathways:  97%|█████████▋| 486/502 [40:53<01:09,  4.37s/it]

Regulation of Translation in Response to Stress (GO:0043555): pvalue calculation completed
Regulation of Translation in Response to Stress (GO:0043555): Calculation completed
Regulation of Tyrosine Phosphorylation of STAT Protein (GO:0042509): Calculation started
Regulation of Tyrosine Phosphorylation of STAT Protein (GO:0042509): scoring computed

Calculating pathways:  97%|█████████▋| 487/502 [40:56<01:02,  4.18s/it]

Regulation of Tyrosine Phosphorylation of STAT Protein (GO:0042509): pvalue calculation completed
Regulation of Tyrosine Phosphorylation of STAT Protein (GO:0042509): Calculation completed
Replication Fork Processing (GO:0031297): Calculation started
Replication Fork Processing (GO:0031297): scoring computed

Calculating pathways:  97%|█████████▋| 488/502 [41:00<00:58,  4.15s/it]

Replication Fork Processing (GO:0031297): pvalue calculation completed
Replication Fork Processing (GO:0031297): Calculation completed
Response to UV (GO:0009411): Calculation started
Response to UV (GO:0009411): scoring computed

Calculating pathways:  97%|█████████▋| 489/502 [41:05<00:56,  4.31s/it]

Response to UV (GO:0009411): pvalue calculation completed
Response to UV (GO:0009411): Calculation completed
Response to UV-A (GO:0070141): Calculation started
Response to UV-A (GO:0070141): scoring computed

Calculating pathways:  98%|█████████▊| 490/502 [41:09<00:49,  4.13s/it]

Response to UV-A (GO:0070141): pvalue calculation completed
Response to UV-A (GO:0070141): Calculation completed
Response to Cytokine (GO:0034097): Calculation started
Response to Cytokine (GO:0034097): scoring computed

Calculating pathways:  98%|█████████▊| 491/502 [41:14<00:48,  4.43s/it]

Response to Cytokine (GO:0034097): pvalue calculation completed
Response to Cytokine (GO:0034097): Calculation completed
Response to Interleukin-4 (GO:0070670): Calculation started
Response to Interleukin-4 (GO:0070670): scoring computed

Calculating pathways:  98%|█████████▊| 492/502 [41:18<00:41,  4.19s/it]

Response to Interleukin-4 (GO:0070670): pvalue calculation completed
Response to Interleukin-4 (GO:0070670): Calculation completed
Response to Nitric Oxide (GO:0071731): Calculation started
Response to Nitric Oxide (GO:0071731): scoring computed

Calculating pathways:  98%|█████████▊| 493/502 [41:21<00:35,  4.00s/it]

Response to Nitric Oxide (GO:0071731): pvalue calculation completed
Response to Nitric Oxide (GO:0071731): Calculation completed
Small GTPase-mediated Signal Transduction (GO:0007264): Calculation started
Small GTPase-mediated Signal Transduction (GO:0007264): scoring computed

Calculating pathways:  98%|█████████▊| 494/502 [41:27<00:36,  4.56s/it]

Small GTPase-mediated Signal Transduction (GO:0007264): pvalue calculation completed
Small GTPase-mediated Signal Transduction (GO:0007264): Calculation completed
Telomere Maintenance (GO:0000723): Calculation started
Telomere Maintenance (GO:0000723): scoring computed

Calculating pathways:  99%|█████████▊| 495/502 [41:31<00:31,  4.48s/it]

Telomere Maintenance (GO:0000723): pvalue calculation completed
Telomere Maintenance (GO:0000723): Calculation completed
Telomere Maintenance in Response to DNA Damage (GO:0043247): Calculation started
Telomere Maintenance in Response to DNA Damage (GO:0043247): scoring computed

Calculating pathways:  99%|█████████▉| 496/502 [41:35<00:25,  4.26s/it]

Telomere Maintenance in Response to DNA Damage (GO:0043247): pvalue calculation completed
Telomere Maintenance in Response to DNA Damage (GO:0043247): Calculation completed
Transcription by RNA Polymerase II (GO:0006366): Calculation started
Transcription by RNA Polymerase II (GO:0006366): scoring computed

Calculating pathways:  99%|█████████▉| 497/502 [41:41<00:23,  4.75s/it]

Transcription by RNA Polymerase II (GO:0006366): pvalue calculation completed
Transcription by RNA Polymerase II (GO:0006366): Calculation completed
Transcription Elongation by RNA Polymerase II (GO:0006368): Calculation started
Transcription Elongation by RNA Polymerase II (GO:0006368): scoring computed

Calculating pathways:  99%|█████████▉| 498/502 [41:45<00:18,  4.52s/it]

Transcription Elongation by RNA Polymerase II (GO:0006368): pvalue calculation completed
Transcription Elongation by RNA Polymerase II (GO:0006368): Calculation completed
Transcription Initiation at RNA Polymerase II Promoter (GO:0006367): Calculation started
Transcription Initiation at RNA Polymerase II Promoter (GO:0006367): scoring computed

Calculating pathways:  99%|█████████▉| 499/502 [41:50<00:13,  4.66s/it]

Transcription Initiation at RNA Polymerase II Promoter (GO:0006367): pvalue calculation completed
Transcription Initiation at RNA Polymerase II Promoter (GO:0006367): Calculation completed
Type B Pancreatic Cell Development (GO:0003323): Calculation started
Type B Pancreatic Cell Development (GO:0003323): scoring computed

Calculating pathways: 100%|█████████▉| 500/502 [41:53<00:08,  4.32s/it]

Type B Pancreatic Cell Development (GO:0003323): pvalue calculation completed
Type B Pancreatic Cell Development (GO:0003323): Calculation completed
Type B Pancreatic Cell Differentiation (GO:0003309): Calculation started
Type B Pancreatic Cell Differentiation (GO:0003309): scoring computed

Calculating pathways: 100%|█████████▉| 501/502 [41:57<00:04,  4.08s/it]

Type B Pancreatic Cell Differentiation (GO:0003309): pvalue calculation completed
Type B Pancreatic Cell Differentiation (GO:0003309): Calculation completed
Tyrosine Phosphorylation of STAT Protein (GO:0007260): Calculation started
Tyrosine Phosphorylation of STAT Protein (GO:0007260): scoring computed

Calculating pathways: 100%|██████████| 502/502 [42:00<00:00,  5.02s/it]

Tyrosine Phosphorylation of STAT Protein (GO:0007260): pvalue calculation completed
Tyrosine Phosphorylation of STAT Protein (GO:0007260): Calculation completed

## Zoledronic_Acid

In [17]:
#loading drug_data
drug_data = json.load(open("singscore_new_code/Zoledronic_Acid/Zoledronic_Acid_relevant_pathways.json"))
count = len(drug_data)
print("Number of items:", count)

final_result = {}

for key, value in tqdm(drug_data.items(), desc="Calculating pathways"):
    print(f"{key}: Calculation started")
    up = drug_data[key]
    up_present = [gene for gene in up if gene in uk65.index]

    # Print counts and summary
    # print(f"Total up genes in signature: {len(up)}")
    # print(f"Up genes found in expression data: {len(up_present)}")

    # Optionally, print the missing ones
    missing_up = set(up) - set(uk65.index)

    # print(f"Missing up genes: {len(missing_up)}")
    scored_data = score(up_gene=up, down_gene=False, sample=uk65,
                    norm_method='theoretical', full_data=True)
    #getting the scored data for a pathway
    total_score = scored_data["total_score"].to_list()[0]
    print(f"{key}: scoring computed")
    permd = permutate(uk65, n_up=len(up_present), n_down=False)
    pvals = empiricalpval(permutations=permd, score=scored_data)
    empirical_p_value = pvals["empirical p value"].to_list()[0]
    print(f"{key}: pvalue calculation completed")
    result = {
    f"{key}":{
        "gene_set_info": {
            "geneset_size": len(up),
            "geneset_covered_in_sample": len(up_present)
        },
        "scores": {
            "total_singscore": total_score
        },
        "statistics": {
            "p_value": empirical_p_value,
            "method": "permutation (empirical)",
            "permutations": 10000
        }}}
    print(f"{key}: Calculation completed")
    final_result.update(result)

# Save final combined JSON
with open("singscore_new_code/Zoledronic_Acid/Zoledronic_Acid_singscore_results.json", "w", encoding="utf-8") as f:
    json.dump(final_result, f, indent=2, ensure_ascii=False)

Number of items: 206

Calculating pathways:   0%|          | 0/206 [00:00<?, ?it/s]

Hypoxia: Calculation started
Hypoxia: scoring computed

Calculating pathways:   0%|          | 1/206 [00:05<18:52,  5.52s/it]

Hypoxia: pvalue calculation completed
Hypoxia: Calculation completed
Cholesterol Homeostasis: Calculation started
Cholesterol Homeostasis: scoring computed

Calculating pathways:   1%|          | 2/206 [00:09<16:08,  4.75s/it]

Cholesterol Homeostasis: pvalue calculation completed
Cholesterol Homeostasis: Calculation completed
Estrogen Response Early: Calculation started
Estrogen Response Early: scoring computed

Calculating pathways:   1%|▏         | 3/206 [00:15<17:26,  5.15s/it]

Estrogen Response Early: pvalue calculation completed
Estrogen Response Early: Calculation completed
Estrogen Response Late: Calculation started
Estrogen Response Late: scoring computed

Calculating pathways:   2%|▏         | 4/206 [00:20<17:55,  5.33s/it]

Estrogen Response Late: pvalue calculation completed
Estrogen Response Late: Calculation completed
Apical Junction: Calculation started
Apical Junction: scoring computed

Calculating pathways:   2%|▏         | 5/206 [00:26<17:56,  5.36s/it]

Apical Junction: pvalue calculation completed
Apical Junction: Calculation completed
Complement: Calculation started
Complement: scoring computed

Calculating pathways:   3%|▎         | 6/206 [00:31<18:05,  5.43s/it]

Complement: pvalue calculation completed
Complement: Calculation completed
Epithelial Mesenchymal Transition: Calculation started
Epithelial Mesenchymal Transition: scoring computed

Calculating pathways:   3%|▎         | 7/206 [00:37<18:06,  5.46s/it]

Epithelial Mesenchymal Transition: pvalue calculation completed
Epithelial Mesenchymal Transition: Calculation completed
Inflammatory Response: Calculation started
Inflammatory Response: scoring computed

Calculating pathways:   4%|▍         | 8/206 [00:42<18:00,  5.46s/it]

Inflammatory Response: pvalue calculation completed
Inflammatory Response: Calculation completed
Xenobiotic Metabolism: Calculation started
Xenobiotic Metabolism: scoring computed

Calculating pathways:   4%|▍         | 9/206 [00:48<18:00,  5.48s/it]

Xenobiotic Metabolism: pvalue calculation completed
Xenobiotic Metabolism: Calculation completed
UV Response Up: Calculation started
UV Response Up: scoring computed

Calculating pathways:   5%|▍         | 10/206 [00:53<17:26,  5.34s/it]

UV Response Up: pvalue calculation completed
UV Response Up: Calculation completed
heme Metabolism: Calculation started
heme Metabolism: scoring computed

Calculating pathways:   5%|▌         | 11/206 [00:58<17:29,  5.38s/it]

heme Metabolism: pvalue calculation completed
heme Metabolism: Calculation completed
Coagulation: Calculation started
Coagulation: scoring computed

Calculating pathways:   6%|▌         | 12/206 [01:03<16:46,  5.19s/it]

Coagulation: pvalue calculation completed
Coagulation: Calculation completed
IL-2/STAT5 Signaling: Calculation started
IL-2/STAT5 Signaling: scoring computed

Calculating pathways:   6%|▋         | 13/206 [01:09<17:03,  5.30s/it]

IL-2/STAT5 Signaling: pvalue calculation completed
IL-2/STAT5 Signaling: Calculation completed
Pperoxisome: Calculation started
Pperoxisome: scoring computed

Calculating pathways:   7%|▋         | 14/206 [01:13<16:15,  5.08s/it]

Pperoxisome: pvalue calculation completed
Pperoxisome: Calculation completed
Allograft Rejection: Calculation started
Allograft Rejection: scoring computed

Calculating pathways:   7%|▋         | 15/206 [01:19<16:23,  5.15s/it]

Allograft Rejection: pvalue calculation completed
Allograft Rejection: Calculation completed
KRAS Signaling Up: Calculation started
KRAS Signaling Up: scoring computed

Calculating pathways:   8%|▊         | 16/206 [01:24<16:44,  5.29s/it]

KRAS Signaling Up: pvalue calculation completed
KRAS Signaling Up: Calculation completed
AGE-RAGE signaling pathway in diabetic complications: Calculation started
AGE-RAGE signaling pathway in diabetic complications: scoring computed

Calculating pathways:   8%|▊         | 17/206 [01:29<15:51,  5.04s/it]

AGE-RAGE signaling pathway in diabetic complications: pvalue calculation completed
AGE-RAGE signaling pathway in diabetic complications: Calculation completed
Bile secretion: Calculation started
Bile secretion: scoring computed

Calculating pathways:   9%|▊         | 18/206 [01:33<14:52,  4.75s/it]

Bile secretion: pvalue calculation completed
Bile secretion: Calculation completed
Bladder cancer: Calculation started
Bladder cancer: scoring computed

Calculating pathways:   9%|▉         | 19/206 [01:37<13:56,  4.47s/it]

Bladder cancer: pvalue calculation completed
Bladder cancer: Calculation completed
Collecting duct acid secretion: Calculation started
Collecting duct acid secretion: scoring computed

Calculating pathways:  10%|▉         | 20/206 [01:40<13:04,  4.22s/it]

Collecting duct acid secretion: pvalue calculation completed
Collecting duct acid secretion: Calculation completed
Diabetic cardiomyopathy: Calculation started
Diabetic cardiomyopathy: scoring computed

Calculating pathways:  10%|█         | 21/206 [01:46<14:01,  4.55s/it]

Diabetic cardiomyopathy: pvalue calculation completed
Diabetic cardiomyopathy: Calculation completed
Estrogen signaling pathway: Calculation started
Estrogen signaling pathway: scoring computed

Calculating pathways:  11%|█         | 22/206 [01:50<14:03,  4.58s/it]

Estrogen signaling pathway: pvalue calculation completed
Estrogen signaling pathway: Calculation completed
Fluid shear stress and atherosclerosis: Calculation started
Fluid shear stress and atherosclerosis: scoring computed

Calculating pathways:  11%|█         | 23/206 [01:55<14:17,  4.68s/it]

Fluid shear stress and atherosclerosis: pvalue calculation completed
Fluid shear stress and atherosclerosis: Calculation completed
Gastric acid secretion: Calculation started
Gastric acid secretion: scoring computed

Calculating pathways:  12%|█▏        | 24/206 [01:59<13:40,  4.51s/it]

Gastric acid secretion: pvalue calculation completed
Gastric acid secretion: Calculation completed
GnRH signaling pathway: Calculation started
GnRH signaling pathway: scoring computed

Calculating pathways:  12%|█▏        | 25/206 [02:04<13:29,  4.47s/it]

GnRH signaling pathway: pvalue calculation completed
GnRH signaling pathway: Calculation completed
Hepatitis B: Calculation started
Hepatitis B: scoring computed

Calculating pathways:  13%|█▎        | 26/206 [02:09<13:58,  4.66s/it]

Hepatitis B: pvalue calculation completed
Hepatitis B: Calculation completed
Human T-cell leukemia virus 1 infection: Calculation started
Human T-cell leukemia virus 1 infection: scoring computed

Calculating pathways:  13%|█▎        | 27/206 [02:14<14:47,  4.96s/it]

Human T-cell leukemia virus 1 infection: pvalue calculation completed
Human T-cell leukemia virus 1 infection: Calculation completed
IL-17 signaling pathway: Calculation started
IL-17 signaling pathway: scoring computed

Calculating pathways:  14%|█▎        | 28/206 [02:19<14:05,  4.75s/it]

IL-17 signaling pathway: pvalue calculation completed
IL-17 signaling pathway: Calculation completed
Influenza A: Calculation started
Influenza A: scoring computed

Calculating pathways:  14%|█▍        | 29/206 [02:24<14:14,  4.83s/it]

Influenza A: pvalue calculation completed
Influenza A: Calculation completed
Leukocyte transendothelial migration: Calculation started
Leukocyte transendothelial migration: scoring computed

Calculating pathways:  15%|█▍        | 30/206 [02:28<13:53,  4.73s/it]

Leukocyte transendothelial migration: pvalue calculation completed
Leukocyte transendothelial migration: Calculation completed
Lipid and atherosclerosis: Calculation started
Lipid and atherosclerosis: scoring computed

Calculating pathways:  15%|█▌        | 31/206 [02:34<14:32,  4.99s/it]

Lipid and atherosclerosis: pvalue calculation completed
Lipid and atherosclerosis: Calculation completed
MicroRNAs in cancer: Calculation started
MicroRNAs in cancer: scoring computed

Calculating pathways:  16%|█▌        | 32/206 [02:39<14:53,  5.13s/it]

MicroRNAs in cancer: pvalue calculation completed
MicroRNAs in cancer: Calculation completed
Nitrogen metabolism: Calculation started
Nitrogen metabolism: scoring computed

Calculating pathways:  16%|█▌        | 33/206 [02:43<13:22,  4.64s/it]

Nitrogen metabolism: pvalue calculation completed
Nitrogen metabolism: Calculation completed
Pancreatic secretion: Calculation started
Pancreatic secretion: scoring computed

Calculating pathways:  17%|█▋        | 34/206 [02:47<12:58,  4.52s/it]

Pancreatic secretion: pvalue calculation completed
Pancreatic secretion: Calculation completed
Parathyroid hormone synthesis, secretion and action: Calculation started
Parathyroid hormone synthesis, secretion and action: scoring computed

Calculating pathways:  17%|█▋        | 35/206 [02:52<12:55,  4.53s/it]

Parathyroid hormone synthesis, secretion and action: pvalue calculation completed
Parathyroid hormone synthesis, secretion and action: Calculation completed
Pathways in cancer: Calculation started
Pathways in cancer: scoring computed

Calculating pathways:  17%|█▋        | 36/206 [03:00<16:19,  5.76s/it]

Pathways in cancer: pvalue calculation completed
Pathways in cancer: Calculation completed
Prostate cancer: Calculation started
Prostate cancer: scoring computed

Calculating pathways:  18%|█▊        | 37/206 [03:05<15:07,  5.37s/it]

Prostate cancer: pvalue calculation completed
Prostate cancer: Calculation completed
Proteoglycans in cancer: Calculation started
Proteoglycans in cancer: scoring computed

Calculating pathways:  18%|█▊        | 38/206 [03:10<15:11,  5.42s/it]

Proteoglycans in cancer: pvalue calculation completed
Proteoglycans in cancer: Calculation completed
Proximal tubule bicarbonate reclamation: Calculation started
Proximal tubule bicarbonate reclamation: scoring computed

Calculating pathways:  19%|█▉        | 39/206 [03:14<13:32,  4.87s/it]

Proximal tubule bicarbonate reclamation: pvalue calculation completed
Proximal tubule bicarbonate reclamation: Calculation completed
Relaxin signaling pathway: Calculation started
Relaxin signaling pathway: scoring computed

Calculating pathways:  19%|█▉        | 40/206 [03:18<13:20,  4.82s/it]

Relaxin signaling pathway: pvalue calculation completed
Relaxin signaling pathway: Calculation completed
TNF signaling pathway: Calculation started
TNF signaling pathway: scoring computed

Calculating pathways:  20%|█▉        | 41/206 [03:23<13:09,  4.78s/it]

TNF signaling pathway: pvalue calculation completed
TNF signaling pathway: Calculation completed
Terpenoid backbone biosynthesis: Calculation started
Terpenoid backbone biosynthesis: scoring computed

Calculating pathways:  20%|██        | 42/206 [03:27<12:04,  4.42s/it]

Terpenoid backbone biosynthesis: pvalue calculation completed
Terpenoid backbone biosynthesis: Calculation completed
Transcriptional misregulation in cancer: Calculation started
Transcriptional misregulation in cancer: scoring computed

Calculating pathways:  21%|██        | 43/206 [03:32<12:46,  4.70s/it]

Transcriptional misregulation in cancer: pvalue calculation completed
Transcriptional misregulation in cancer: Calculation completed
Activation of Matrix Metalloproteinases: Calculation started
Activation of Matrix Metalloproteinases: scoring computed

Calculating pathways:  21%|██▏       | 44/206 [03:36<11:48,  4.37s/it]

Activation of Matrix Metalloproteinases: pvalue calculation completed
Activation of Matrix Metalloproteinases: Calculation completed
Activation of Gene Expression by SREBF (SREBP): Calculation started
Activation of Gene Expression by SREBF (SREBP): scoring computed

Calculating pathways:  22%|██▏       | 45/206 [03:40<11:23,  4.25s/it]

Activation of Gene Expression by SREBF (SREBP): pvalue calculation completed
Activation of Gene Expression by SREBF (SREBP): Calculation completed
Adaptive Immune System: Calculation started
Adaptive Immune System: scoring computed

Calculating pathways:  22%|██▏       | 46/206 [03:51<16:49,  6.31s/it]

Adaptive Immune System: pvalue calculation completed
Adaptive Immune System: Calculation completed
Assembly of Collagen Fibrils and Other Multimeric Structures: Calculation started
Assembly of Collagen Fibrils and Other Multimeric Structures: scoring computed

Calculating pathways:  23%|██▎       | 47/206 [03:55<14:51,  5.61s/it]

Assembly of Collagen Fibrils and Other Multimeric Structures: pvalue calculation completed
Assembly of Collagen Fibrils and Other Multimeric Structures: Calculation completed
Axon Guidance: Calculation started
Axon Guidance: scoring computed

Calculating pathways:  23%|██▎       | 48/206 [04:04<17:21,  6.59s/it]

Axon Guidance: pvalue calculation completed
Axon Guidance: Calculation completed
Butyrophilin (BTN) Family Interactions: Calculation started
Butyrophilin (BTN) Family Interactions: scoring computed

Calculating pathways:  24%|██▍       | 49/206 [04:07<14:53,  5.69s/it]

Butyrophilin (BTN) Family Interactions: pvalue calculation completed
Butyrophilin (BTN) Family Interactions: Calculation completed
Cellular Response to Hypoxia: Calculation started
Cellular Response to Hypoxia: scoring computed

Calculating pathways:  24%|██▍       | 50/206 [04:11<13:29,  5.19s/it]

Cellular Response to Hypoxia: pvalue calculation completed
Cellular Response to Hypoxia: Calculation completed
Cellular Responses to Mechanical Stimuli: Calculation started
Cellular Responses to Mechanical Stimuli: scoring computed

Calculating pathways:  25%|██▍       | 51/206 [04:15<12:40,  4.90s/it]

Cellular Responses to Mechanical Stimuli: pvalue calculation completed
Cellular Responses to Mechanical Stimuli: Calculation completed
Cellular Responses to Stimuli: Calculation started
Cellular Responses to Stimuli: scoring computed

Calculating pathways:  25%|██▌       | 52/206 [04:28<18:15,  7.11s/it]

Cellular Responses to Stimuli: pvalue calculation completed
Cellular Responses to Stimuli: Calculation completed
Cellular Responses to Stress: Calculation started
Cellular Responses to Stress: scoring computed

Calculating pathways:  26%|██▌       | 53/206 [04:39<21:26,  8.41s/it]

Cellular Responses to Stress: pvalue calculation completed
Cellular Responses to Stress: Calculation completed
Cholesterol Biosynthesis: Calculation started
Cholesterol Biosynthesis: scoring computed

Calculating pathways:  26%|██▌       | 54/206 [04:43<17:38,  6.96s/it]

Cholesterol Biosynthesis: pvalue calculation completed
Cholesterol Biosynthesis: Calculation completed
Collagen Degradation: Calculation started
Collagen Degradation: scoring computed

Calculating pathways:  27%|██▋       | 55/206 [04:47<15:13,  6.05s/it]

Collagen Degradation: pvalue calculation completed
Collagen Degradation: Calculation completed
Collagen Formation: Calculation started
Collagen Formation: scoring computed

Calculating pathways:  27%|██▋       | 56/206 [04:51<13:46,  5.51s/it]

Collagen Formation: pvalue calculation completed
Collagen Formation: Calculation completed
Cytokine Signaling in Immune System: Calculation started
Cytokine Signaling in Immune System: scoring computed

Calculating pathways:  28%|██▊       | 57/206 [05:02<17:42,  7.13s/it]

Cytokine Signaling in Immune System: pvalue calculation completed
Cytokine Signaling in Immune System: Calculation completed
Degradation of the Extracellular Matrix: Calculation started
Degradation of the Extracellular Matrix: scoring computed

Calculating pathways:  28%|██▊       | 58/206 [05:06<15:46,  6.39s/it]

Degradation of the Extracellular Matrix: pvalue calculation completed
Degradation of the Extracellular Matrix: Calculation completed
Developmental Biology: Calculation started
Developmental Biology: scoring computed

Calculating pathways:  29%|██▊       | 59/206 [05:21<21:40,  8.85s/it]

Developmental Biology: pvalue calculation completed
Developmental Biology: Calculation completed
EPH-Ephrin Signaling: Calculation started
EPH-Ephrin Signaling: scoring computed

Calculating pathways:  29%|██▉       | 60/206 [05:25<18:10,  7.47s/it]

EPH-Ephrin Signaling: pvalue calculation completed
EPH-Ephrin Signaling: Calculation completed
EPH-ephrin Mediated Repulsion of Cells: Calculation started
EPH-ephrin Mediated Repulsion of Cells: scoring computed

Calculating pathways:  30%|██▉       | 61/206 [05:29<15:34,  6.44s/it]

EPH-ephrin Mediated Repulsion of Cells: pvalue calculation completed
EPH-ephrin Mediated Repulsion of Cells: Calculation completed
ESR-mediated Signaling: Calculation started
ESR-mediated Signaling: scoring computed

Calculating pathways:  30%|███       | 62/206 [05:35<14:42,  6.13s/it]

ESR-mediated Signaling: pvalue calculation completed
ESR-mediated Signaling: Calculation completed
Erythrocytes Take up Carbon Dioxide and Release Oxygen: Calculation started
Erythrocytes Take up Carbon Dioxide and Release Oxygen: scoring computed

Calculating pathways:  31%|███       | 63/206 [05:38<12:40,  5.32s/it]

Erythrocytes Take up Carbon Dioxide and Release Oxygen: pvalue calculation completed
Erythrocytes Take up Carbon Dioxide and Release Oxygen: Calculation completed
Erythrocytes Take up Oxygen and Release Carbon Dioxide: Calculation started
Erythrocytes Take up Oxygen and Release Carbon Dioxide: scoring computed

Calculating pathways:  31%|███       | 64/206 [05:41<11:10,  4.72s/it]

Erythrocytes Take up Oxygen and Release Carbon Dioxide: pvalue calculation completed
Erythrocytes Take up Oxygen and Release Carbon Dioxide: Calculation completed
Extra-nuclear Estrogen Signaling: Calculation started
Extra-nuclear Estrogen Signaling: scoring computed

Calculating pathways:  32%|███▏      | 65/206 [05:46<10:40,  4.54s/it]

Extra-nuclear Estrogen Signaling: pvalue calculation completed
Extra-nuclear Estrogen Signaling: Calculation completed
Extracellular Matrix Organization: Calculation started
Extracellular Matrix Organization: scoring computed

Calculating pathways:  32%|███▏      | 66/206 [05:52<12:01,  5.15s/it]

Extracellular Matrix Organization: pvalue calculation completed
Extracellular Matrix Organization: Calculation completed
High Laminar Flow Shear Stress Activates Signaling by PIEZO1 and PECAM1 CDH5 KDR in Endothelial Cell: Calculation started
High Laminar Flow Shear Stress Activates Signaling by PIEZO1 and PECAM1 CDH5 KDR in Endothelial Cell: scoring computed

Calculating pathways:  33%|███▎      | 67/206 [05:56<11:14,  4.85s/it]

High Laminar Flow Shear Stress Activates Signaling by PIEZO1 and PECAM1 CDH5 KDR in Endothelial Cell: pvalue calculation completed
High Laminar Flow Shear Stress Activates Signaling by PIEZO1 and PECAM1 CDH5 KDR in Endothelial Cell: Calculation completed
Innate Immune System: Calculation started
Innate Immune System: scoring computed

Calculating pathways:  33%|███▎      | 68/206 [06:10<17:12,  7.48s/it]

Innate Immune System: pvalue calculation completed
Innate Immune System: Calculation completed
Interleukin-4 and Interleukin-13 Signaling: Calculation started
Interleukin-4 and Interleukin-13 Signaling: scoring computed

Calculating pathways:  33%|███▎      | 69/206 [06:14<14:57,  6.55s/it]

Interleukin-4 and Interleukin-13 Signaling: pvalue calculation completed
Interleukin-4 and Interleukin-13 Signaling: Calculation completed
MAPK Family Signaling Cascades: Calculation started
MAPK Family Signaling Cascades: scoring computed

Calculating pathways:  34%|███▍      | 70/206 [06:21<15:00,  6.62s/it]

MAPK Family Signaling Cascades: pvalue calculation completed
MAPK Family Signaling Cascades: Calculation completed
MAPK6 MAPK4 Signaling: Calculation started
MAPK6 MAPK4 Signaling: scoring computed

Calculating pathways:  34%|███▍      | 71/206 [06:25<13:13,  5.88s/it]

MAPK6 MAPK4 Signaling: pvalue calculation completed
MAPK6 MAPK4 Signaling: Calculation completed
Metabolism of Lipids: Calculation started
Metabolism of Lipids: scoring computed

Calculating pathways:  35%|███▍      | 72/206 [06:36<16:36,  7.43s/it]

Metabolism of Lipids: pvalue calculation completed
Metabolism of Lipids: Calculation completed
Metabolism of Steroids: Calculation started
Metabolism of Steroids: scoring computed

Calculating pathways:  35%|███▌      | 73/206 [06:41<14:52,  6.71s/it]

Metabolism of Steroids: pvalue calculation completed
Metabolism of Steroids: Calculation completed
Nervous System Development: Calculation started
Nervous System Development: scoring computed

Calculating pathways:  36%|███▌      | 74/206 [06:51<16:26,  7.47s/it]

Nervous System Development: pvalue calculation completed
Nervous System Development: Calculation completed
Neutrophil Degranulation: Calculation started
Neutrophil Degranulation: scoring computed

Calculating pathways:  36%|███▋      | 75/206 [07:00<17:31,  8.03s/it]

Neutrophil Degranulation: pvalue calculation completed
Neutrophil Degranulation: Calculation completed
O2 CO2 Exchange in Erythrocytes: Calculation started
O2 CO2 Exchange in Erythrocytes: scoring computed

Calculating pathways:  37%|███▋      | 76/206 [07:04<14:30,  6.69s/it]

O2 CO2 Exchange in Erythrocytes: pvalue calculation completed
O2 CO2 Exchange in Erythrocytes: Calculation completed
Regulation of IGF Transport and Uptake by Insulin-like Growth Factor Binding Proteins (IGFBPs): Calculation started
Regulation of IGF Transport and Uptake by Insulin-like Growth Factor Binding Proteins (IGFBPs): scoring computed

Calculating pathways:  37%|███▋      | 77/206 [07:08<13:01,  6.06s/it]

Regulation of IGF Transport and Uptake by Insulin-like Growth Factor Binding Proteins (IGFBPs): pvalue calculation completed
Regulation of IGF Transport and Uptake by Insulin-like Growth Factor Binding Proteins (IGFBPs): Calculation completed
Regulation of Cholesterol Biosynthesis by SREBP (SREBF): Calculation started
Regulation of Cholesterol Biosynthesis by SREBP (SREBF): scoring computed

Calculating pathways:  38%|███▊      | 78/206 [07:12<11:37,  5.45s/it]

Regulation of Cholesterol Biosynthesis by SREBP (SREBF): pvalue calculation completed
Regulation of Cholesterol Biosynthesis by SREBP (SREBF): Calculation completed
Regulation of Gene Expression by Hypoxia-inducible Factor: Calculation started
Regulation of Gene Expression by Hypoxia-inducible Factor: scoring computed

Calculating pathways:  38%|███▊      | 79/206 [07:16<10:14,  4.84s/it]

Regulation of Gene Expression by Hypoxia-inducible Factor: pvalue calculation completed
Regulation of Gene Expression by Hypoxia-inducible Factor: Calculation completed
Response of Endothelial Cells to Shear Stress: Calculation started
Response of Endothelial Cells to Shear Stress: scoring computed

Calculating pathways:  39%|███▉      | 80/206 [07:20<09:50,  4.68s/it]

Response of Endothelial Cells to Shear Stress: pvalue calculation completed
Response of Endothelial Cells to Shear Stress: Calculation completed
Reversible Hydration of Carbon Dioxide: Calculation started
Reversible Hydration of Carbon Dioxide: scoring computed

Calculating pathways:  39%|███▉      | 81/206 [07:23<08:58,  4.30s/it]

Reversible Hydration of Carbon Dioxide: pvalue calculation completed
Reversible Hydration of Carbon Dioxide: Calculation completed
Signaling by Interleukins: Calculation started
Signaling by Interleukins: scoring computed

Calculating pathways:  40%|███▉      | 82/206 [07:31<11:03,  5.35s/it]

Signaling by Interleukins: pvalue calculation completed
Signaling by Interleukins: Calculation completed
Signaling by Nuclear Receptors: Calculation started
Signaling by Nuclear Receptors: scoring computed

Calculating pathways:  40%|████      | 83/206 [07:37<11:28,  5.60s/it]

Signaling by Nuclear Receptors: pvalue calculation completed
Signaling by Nuclear Receptors: Calculation completed
Signaling by Receptor Tyrosine Kinases: Calculation started
Signaling by Receptor Tyrosine Kinases: scoring computed

Calculating pathways:  41%|████      | 84/206 [07:47<13:43,  6.75s/it]

Signaling by Receptor Tyrosine Kinases: pvalue calculation completed
Signaling by Receptor Tyrosine Kinases: Calculation completed
Signaling by SCF-KIT: Calculation started
Signaling by SCF-KIT: scoring computed

Calculating pathways:  41%|████▏     | 85/206 [07:51<12:05,  5.99s/it]

Signaling by SCF-KIT: pvalue calculation completed
Signaling by SCF-KIT: Calculation completed
Signaling by TGFB Family Members: Calculation started
Signaling by TGFB Family Members: scoring computed

Calculating pathways:  42%|████▏     | 86/206 [07:56<11:35,  5.80s/it]

Signaling by TGFB Family Members: pvalue calculation completed
Signaling by TGFB Family Members: Calculation completed
Signaling by TGFBR3: Calculation started
Signaling by TGFBR3: scoring computed

Calculating pathways:  42%|████▏     | 87/206 [08:00<10:26,  5.26s/it]

Signaling by TGFBR3: pvalue calculation completed
Signaling by TGFBR3: Calculation completed
TGFBR3 PTM Regulation: Calculation started
TGFBR3 PTM Regulation: scoring computed

Calculating pathways:  43%|████▎     | 88/206 [08:04<09:18,  4.73s/it]

TGFBR3 PTM Regulation: pvalue calculation completed
TGFBR3 PTM Regulation: Calculation completed
Transport of Small Molecules: Calculation started
Transport of Small Molecules: scoring computed

Calculating pathways:  43%|████▎     | 89/206 [08:14<12:35,  6.46s/it]

Transport of Small Molecules: pvalue calculation completed
Transport of Small Molecules: Calculation completed
T Cell Receptor Signaling Pathway (GO:0050852): Calculation started
T Cell Receptor Signaling Pathway (GO:0050852): scoring computed

Calculating pathways:  44%|████▎     | 90/206 [08:19<11:19,  5.86s/it]

T Cell Receptor Signaling Pathway (GO:0050852): pvalue calculation completed
T Cell Receptor Signaling Pathway (GO:0050852): Calculation completed
Angiotensin-Activated Signaling Pathway (GO:0038166): Calculation started
Angiotensin-Activated Signaling Pathway (GO:0038166): scoring computed

Calculating pathways:  44%|████▍     | 91/206 [08:22<09:56,  5.19s/it]

Angiotensin-Activated Signaling Pathway (GO:0038166): pvalue calculation completed
Angiotensin-Activated Signaling Pathway (GO:0038166): Calculation completed
Antigen Receptor-Mediated Signaling Pathway (GO:0050851): Calculation started
Antigen Receptor-Mediated Signaling Pathway (GO:0050851): scoring computed

Calculating pathways:  45%|████▍     | 92/206 [08:27<09:30,  5.00s/it]

Antigen Receptor-Mediated Signaling Pathway (GO:0050851): pvalue calculation completed
Antigen Receptor-Mediated Signaling Pathway (GO:0050851): Calculation completed
Carbon Dioxide Transport (GO:0015670): Calculation started
Carbon Dioxide Transport (GO:0015670): scoring computed

Calculating pathways:  45%|████▌     | 93/206 [08:30<08:34,  4.55s/it]

Carbon Dioxide Transport (GO:0015670): pvalue calculation completed
Carbon Dioxide Transport (GO:0015670): Calculation completed
Cell Surface Receptor Protein Tyrosine Kinase Signaling Pathway (GO:0007169): Calculation started
Cell Surface Receptor Protein Tyrosine Kinase Signaling Pathway (GO:0007169): scoring computed

Calculating pathways:  46%|████▌     | 94/206 [08:37<09:41,  5.19s/it]

Cell Surface Receptor Protein Tyrosine Kinase Signaling Pathway (GO:0007169): pvalue calculation completed
Cell Surface Receptor Protein Tyrosine Kinase Signaling Pathway (GO:0007169): Calculation completed
Cellular Component Disassembly (GO:0022411): Calculation started
Cellular Component Disassembly (GO:0022411): scoring computed

Calculating pathways:  46%|████▌     | 95/206 [08:41<08:51,  4.79s/it]

Cellular Component Disassembly (GO:0022411): pvalue calculation completed
Cellular Component Disassembly (GO:0022411): Calculation completed
Cellular Response to UV (GO:0034644): Calculation started
Cellular Response to UV (GO:0034644): scoring computed

Calculating pathways:  47%|████▋     | 96/206 [08:45<08:22,  4.57s/it]

Cellular Response to UV (GO:0034644): pvalue calculation completed
Cellular Response to UV (GO:0034644): Calculation completed
Cellular Response to UV-A (GO:0071492): Calculation started
Cellular Response to UV-A (GO:0071492): scoring computed

Calculating pathways:  47%|████▋     | 97/206 [08:48<07:40,  4.23s/it]

Cellular Response to UV-A (GO:0071492): pvalue calculation completed
Cellular Response to UV-A (GO:0071492): Calculation completed
Cellular Response to Angiotensin (GO:1904385): Calculation started
Cellular Response to Angiotensin (GO:1904385): scoring computed

Calculating pathways:  48%|████▊     | 98/206 [08:52<07:09,  3.98s/it]

Cellular Response to Angiotensin (GO:1904385): pvalue calculation completed
Cellular Response to Angiotensin (GO:1904385): Calculation completed
Cellular Response to Lipid (GO:0071396): Calculation started
Cellular Response to Lipid (GO:0071396): scoring computed

Calculating pathways:  48%|████▊     | 99/206 [08:58<08:00,  4.49s/it]

Cellular Response to Lipid (GO:0071396): pvalue calculation completed
Cellular Response to Lipid (GO:0071396): Calculation completed
Cellular Response to Lipopolysaccharide (GO:0071222): Calculation started
Cellular Response to Lipopolysaccharide (GO:0071222): scoring computed

Calculating pathways:  49%|████▊     | 100/206 [09:02<08:00,  4.53s/it]

Cellular Response to Lipopolysaccharide (GO:0071222): pvalue calculation completed
Cellular Response to Lipopolysaccharide (GO:0071222): Calculation completed
Cellular Response to Molecule of Bacterial Origin (GO:0071219): Calculation started
Cellular Response to Molecule of Bacterial Origin (GO:0071219): scoring computed

Calculating pathways:  49%|████▉     | 101/206 [09:07<07:56,  4.54s/it]

Cellular Response to Molecule of Bacterial Origin (GO:0071219): pvalue calculation completed
Cellular Response to Molecule of Bacterial Origin (GO:0071219): Calculation completed
Cellular Response to Oxygen-Containing Compound (GO:1901701): Calculation started
Cellular Response to Oxygen-Containing Compound (GO:1901701): scoring computed

Calculating pathways:  50%|████▉     | 102/206 [09:14<09:14,  5.33s/it]

Cellular Response to Oxygen-Containing Compound (GO:1901701): pvalue calculation completed
Cellular Response to Oxygen-Containing Compound (GO:1901701): Calculation completed
Collagen Catabolic Process (GO:0030574): Calculation started
Collagen Catabolic Process (GO:0030574): scoring computed

Calculating pathways:  50%|█████     | 103/206 [09:17<08:15,  4.81s/it]

Collagen Catabolic Process (GO:0030574): pvalue calculation completed
Collagen Catabolic Process (GO:0030574): Calculation completed
Endoderm Formation (GO:0001706): Calculation started
Endoderm Formation (GO:0001706): scoring computed

Calculating pathways:  50%|█████     | 104/206 [09:21<07:34,  4.45s/it]

Endoderm Formation (GO:0001706): pvalue calculation completed
Endoderm Formation (GO:0001706): Calculation completed
Endodermal Cell Differentiation (GO:0035987): Calculation started
Endodermal Cell Differentiation (GO:0035987): scoring computed

Calculating pathways:  51%|█████     | 105/206 [09:25<07:04,  4.21s/it]

Endodermal Cell Differentiation (GO:0035987): pvalue calculation completed
Endodermal Cell Differentiation (GO:0035987): Calculation completed
Ephrin Receptor Signaling Pathway (GO:0048013): Calculation started
Ephrin Receptor Signaling Pathway (GO:0048013): scoring computed

Calculating pathways:  51%|█████▏    | 106/206 [09:29<06:56,  4.16s/it]

Ephrin Receptor Signaling Pathway (GO:0048013): pvalue calculation completed
Ephrin Receptor Signaling Pathway (GO:0048013): Calculation completed
External Encapsulating Structure Organization (GO:0045229): Calculation started
External Encapsulating Structure Organization (GO:0045229): scoring computed

Calculating pathways:  52%|█████▏    | 107/206 [09:33<07:03,  4.27s/it]

External Encapsulating Structure Organization (GO:0045229): pvalue calculation completed
External Encapsulating Structure Organization (GO:0045229): Calculation completed
Extracellular Matrix Disassembly (GO:0022617): Calculation started
Extracellular Matrix Disassembly (GO:0022617): scoring computed

Calculating pathways:  52%|█████▏    | 108/206 [09:37<06:46,  4.15s/it]

Extracellular Matrix Disassembly (GO:0022617): pvalue calculation completed
Extracellular Matrix Disassembly (GO:0022617): Calculation completed
Extracellular Matrix Organization (GO:0030198): Calculation started
Extracellular Matrix Organization (GO:0030198): scoring computed

Calculating pathways:  53%|█████▎    | 109/206 [09:42<07:16,  4.50s/it]

Extracellular Matrix Organization (GO:0030198): pvalue calculation completed
Extracellular Matrix Organization (GO:0030198): Calculation completed
Extracellular Structure Organization (GO:0043062): Calculation started
Extracellular Structure Organization (GO:0043062): scoring computed

Calculating pathways:  53%|█████▎    | 110/206 [09:47<07:09,  4.48s/it]

Extracellular Structure Organization (GO:0043062): pvalue calculation completed
Extracellular Structure Organization (GO:0043062): Calculation completed
Gas Transport (GO:0015669): Calculation started
Gas Transport (GO:0015669): scoring computed

Calculating pathways:  54%|█████▍    | 111/206 [09:50<06:36,  4.18s/it]

Gas Transport (GO:0015669): pvalue calculation completed
Gas Transport (GO:0015669): Calculation completed
Isoprenoid Biosynthetic Process (GO:0008299): Calculation started
Isoprenoid Biosynthetic Process (GO:0008299): scoring computed

Calculating pathways:  54%|█████▍    | 112/206 [09:54<06:10,  3.95s/it]

Isoprenoid Biosynthetic Process (GO:0008299): pvalue calculation completed
Isoprenoid Biosynthetic Process (GO:0008299): Calculation completed
Lipid Biosynthetic Process (GO:0008610): Calculation started
Lipid Biosynthetic Process (GO:0008610): scoring computed

Calculating pathways:  55%|█████▍    | 113/206 [09:58<06:20,  4.09s/it]

Lipid Biosynthetic Process (GO:0008610): pvalue calculation completed
Lipid Biosynthetic Process (GO:0008610): Calculation completed
Lipid Metabolic Process (GO:0006629): Calculation started
Lipid Metabolic Process (GO:0006629): scoring computed

Calculating pathways:  55%|█████▌    | 114/206 [10:04<07:02,  4.59s/it]

Lipid Metabolic Process (GO:0006629): pvalue calculation completed
Lipid Metabolic Process (GO:0006629): Calculation completed
Macromolecule Catabolic Process (GO:0009057): Calculation started
Macromolecule Catabolic Process (GO:0009057): scoring computed

Calculating pathways:  56%|█████▌    | 115/206 [10:08<06:37,  4.37s/it]

Macromolecule Catabolic Process (GO:0009057): pvalue calculation completed
Macromolecule Catabolic Process (GO:0009057): Calculation completed
Macrophage Differentiation (GO:0030225): Calculation started
Macrophage Differentiation (GO:0030225): scoring computed

Calculating pathways:  56%|█████▋    | 116/206 [10:11<06:10,  4.11s/it]

Macrophage Differentiation (GO:0030225): pvalue calculation completed
Macrophage Differentiation (GO:0030225): Calculation completed
Mononuclear Cell Differentiation (GO:1903131): Calculation started
Mononuclear Cell Differentiation (GO:1903131): scoring computed

Calculating pathways:  57%|█████▋    | 117/206 [10:15<05:57,  4.02s/it]

Mononuclear Cell Differentiation (GO:1903131): pvalue calculation completed
Mononuclear Cell Differentiation (GO:1903131): Calculation completed
Myeloid Leukocyte Differentiation (GO:0002573): Calculation started
Myeloid Leukocyte Differentiation (GO:0002573): scoring computed

Calculating pathways:  57%|█████▋    | 118/206 [10:19<05:56,  4.06s/it]

Myeloid Leukocyte Differentiation (GO:0002573): pvalue calculation completed
Myeloid Leukocyte Differentiation (GO:0002573): Calculation completed
Negative Regulation of Notch Signaling Pathway (GO:0045746): Calculation started
Negative Regulation of Notch Signaling Pathway (GO:0045746): scoring computed

Calculating pathways:  58%|█████▊    | 119/206 [10:23<05:44,  3.96s/it]

Negative Regulation of Notch Signaling Pathway (GO:0045746): pvalue calculation completed
Negative Regulation of Notch Signaling Pathway (GO:0045746): Calculation completed
Negative Regulation of Apoptotic Process (GO:0043066): Calculation started
Negative Regulation of Apoptotic Process (GO:0043066): scoring computed

Calculating pathways:  58%|█████▊    | 120/206 [10:31<07:30,  5.24s/it]

Negative Regulation of Apoptotic Process (GO:0043066): pvalue calculation completed
Negative Regulation of Apoptotic Process (GO:0043066): Calculation completed
Negative Regulation of Apoptotic Signaling Pathway (GO:2001234): Calculation started
Negative Regulation of Apoptotic Signaling Pathway (GO:2001234): scoring computed

Calculating pathways:  59%|█████▊    | 121/206 [10:36<07:00,  4.94s/it]

Negative Regulation of Apoptotic Signaling Pathway (GO:2001234): pvalue calculation completed
Negative Regulation of Apoptotic Signaling Pathway (GO:2001234): Calculation completed
Negative Regulation of Cation Channel Activity (GO:2001258): Calculation started
Negative Regulation of Cation Channel Activity (GO:2001258): scoring computed

Calculating pathways:  59%|█████▉    | 122/206 [10:39<06:18,  4.51s/it]

Negative Regulation of Cation Channel Activity (GO:2001258): pvalue calculation completed
Negative Regulation of Cation Channel Activity (GO:2001258): Calculation completed
Negative Regulation of Cation Transmembrane Transport (GO:1904063): Calculation started
Negative Regulation of Cation Transmembrane Transport (GO:1904063): scoring computed

Calculating pathways:  60%|█████▉    | 123/206 [10:43<05:50,  4.22s/it]

Negative Regulation of Cation Transmembrane Transport (GO:1904063): pvalue calculation completed
Negative Regulation of Cation Transmembrane Transport (GO:1904063): Calculation completed
Negative Regulation of Epithelial Cell Differentiation (GO:0030857): Calculation started
Negative Regulation of Epithelial Cell Differentiation (GO:0030857): scoring computed

Calculating pathways:  60%|██████    | 124/206 [10:46<05:27,  4.00s/it]

Negative Regulation of Epithelial Cell Differentiation (GO:0030857): pvalue calculation completed
Negative Regulation of Epithelial Cell Differentiation (GO:0030857): Calculation completed
Negative Regulation of Intracellular Signal Transduction (GO:1902532): Calculation started
Negative Regulation of Intracellular Signal Transduction (GO:1902532): scoring computed

Calculating pathways:  61%|██████    | 125/206 [10:53<06:26,  4.77s/it]

Negative Regulation of Intracellular Signal Transduction (GO:1902532): pvalue calculation completed
Negative Regulation of Intracellular Signal Transduction (GO:1902532): Calculation completed
Negative Regulation of Intrinsic Apoptotic Signaling Pathway (GO:2001243): Calculation started
Negative Regulation of Intrinsic Apoptotic Signaling Pathway (GO:2001243): scoring computed

Calculating pathways:  61%|██████    | 126/206 [10:57<06:00,  4.51s/it]

Negative Regulation of Intrinsic Apoptotic Signaling Pathway (GO:2001243): pvalue calculation completed
Negative Regulation of Intrinsic Apoptotic Signaling Pathway (GO:2001243): Calculation completed
Negative Regulation of Ion Transmembrane Transporter Activity (GO:0032413): Calculation started
Negative Regulation of Ion Transmembrane Transporter Activity (GO:0032413): scoring computed

Calculating pathways:  62%|██████▏   | 127/206 [11:00<05:32,  4.21s/it]

Negative Regulation of Ion Transmembrane Transporter Activity (GO:0032413): pvalue calculation completed
Negative Regulation of Ion Transmembrane Transporter Activity (GO:0032413): Calculation completed
Negative Regulation of Programmed Cell Death (GO:0043069): Calculation started
Negative Regulation of Programmed Cell Death (GO:0043069): scoring computed

Calculating pathways:  62%|██████▏   | 128/206 [11:08<06:46,  5.21s/it]

Negative Regulation of Programmed Cell Death (GO:0043069): pvalue calculation completed
Negative Regulation of Programmed Cell Death (GO:0043069): Calculation completed
Negative Regulation of Signal Transduction (GO:0009968): Calculation started
Negative Regulation of Signal Transduction (GO:0009968): scoring computed

Calculating pathways:  63%|██████▎   | 129/206 [11:14<07:06,  5.54s/it]

Negative Regulation of Signal Transduction (GO:0009968): pvalue calculation completed
Negative Regulation of Signal Transduction (GO:0009968): Calculation completed
One-Carbon Compound Transport (GO:0019755): Calculation started
One-Carbon Compound Transport (GO:0019755): scoring computed

Calculating pathways:  63%|██████▎   | 130/206 [11:17<06:13,  4.91s/it]

One-Carbon Compound Transport (GO:0019755): pvalue calculation completed
One-Carbon Compound Transport (GO:0019755): Calculation completed
Phospholipid Biosynthetic Process (GO:0008654): Calculation started
Phospholipid Biosynthetic Process (GO:0008654): scoring computed

Calculating pathways:  64%|██████▎   | 131/206 [11:21<05:38,  4.51s/it]

Phospholipid Biosynthetic Process (GO:0008654): pvalue calculation completed
Phospholipid Biosynthetic Process (GO:0008654): Calculation completed
Positive Regulation of B Cell Activation (GO:0050871): Calculation started
Positive Regulation of B Cell Activation (GO:0050871): scoring computed

Calculating pathways:  64%|██████▍   | 132/206 [11:25<05:19,  4.32s/it]

Positive Regulation of B Cell Activation (GO:0050871): pvalue calculation completed
Positive Regulation of B Cell Activation (GO:0050871): Calculation completed
Positive Regulation of B Cell Differentiation (GO:0045579): Calculation started
Positive Regulation of B Cell Differentiation (GO:0045579): scoring computed

Calculating pathways:  65%|██████▍   | 133/206 [11:28<04:57,  4.07s/it]

Positive Regulation of B Cell Differentiation (GO:0045579): pvalue calculation completed
Positive Regulation of B Cell Differentiation (GO:0045579): Calculation completed
Positive Regulation of DNA Binding (GO:0043388): Calculation started
Positive Regulation of DNA Binding (GO:0043388): scoring computed

Calculating pathways:  65%|██████▌   | 134/206 [11:32<04:42,  3.93s/it]

Positive Regulation of DNA Binding (GO:0043388): pvalue calculation completed
Positive Regulation of DNA Binding (GO:0043388): Calculation completed
Positive Regulation of ERBB Signaling Pathway (GO:1901186): Calculation started
Positive Regulation of ERBB Signaling Pathway (GO:1901186): scoring computed

Calculating pathways:  66%|██████▌   | 135/206 [11:35<04:32,  3.84s/it]

Positive Regulation of ERBB Signaling Pathway (GO:1901186): pvalue calculation completed
Positive Regulation of ERBB Signaling Pathway (GO:1901186): Calculation completed
Positive Regulation of Binding (GO:0051099): Calculation started
Positive Regulation of Binding (GO:0051099): scoring computed

Calculating pathways:  66%|██████▌   | 136/206 [11:40<04:34,  3.92s/it]

Positive Regulation of Binding (GO:0051099): pvalue calculation completed
Positive Regulation of Binding (GO:0051099): Calculation completed
Positive Regulation of Cell Growth (GO:0030307): Calculation started
Positive Regulation of Cell Growth (GO:0030307): scoring computed

Calculating pathways:  67%|██████▋   | 137/206 [11:44<04:41,  4.07s/it]

Positive Regulation of Cell Growth (GO:0030307): pvalue calculation completed
Positive Regulation of Cell Growth (GO:0030307): Calculation completed
Positive Regulation of Cell Migration (GO:0030335): Calculation started
Positive Regulation of Cell Migration (GO:0030335): scoring computed

Calculating pathways:  67%|██████▋   | 138/206 [11:51<05:36,  4.95s/it]

Positive Regulation of Cell Migration (GO:0030335): pvalue calculation completed
Positive Regulation of Cell Migration (GO:0030335): Calculation completed
Positive Regulation of Cell Motility (GO:2000147): Calculation started
Positive Regulation of Cell Motility (GO:2000147): scoring computed

Calculating pathways:  67%|██████▋   | 139/206 [11:57<05:51,  5.25s/it]

Positive Regulation of Cell Motility (GO:2000147): pvalue calculation completed
Positive Regulation of Cell Motility (GO:2000147): Calculation completed
Positive Regulation of Cellular Process (GO:0048522): Calculation started
Positive Regulation of Cellular Process (GO:0048522): scoring computed

Calculating pathways:  68%|██████▊   | 140/206 [12:06<07:08,  6.49s/it]

Positive Regulation of Cellular Process (GO:0048522): pvalue calculation completed
Positive Regulation of Cellular Process (GO:0048522): Calculation completed
Positive Regulation of Cytokine Production (GO:0001819): Calculation started
Positive Regulation of Cytokine Production (GO:0001819): scoring computed

Calculating pathways:  68%|██████▊   | 141/206 [12:13<07:00,  6.46s/it]

Positive Regulation of Cytokine Production (GO:0001819): pvalue calculation completed
Positive Regulation of Cytokine Production (GO:0001819): Calculation completed
Positive Regulation of Cytokine-Mediated Signaling Pathway (GO:0001961): Calculation started
Positive Regulation of Cytokine-Mediated Signaling Pathway (GO:0001961): scoring computed

Calculating pathways:  69%|██████▉   | 142/206 [12:16<06:01,  5.65s/it]

Positive Regulation of Cytokine-Mediated Signaling Pathway (GO:0001961): pvalue calculation completed
Positive Regulation of Cytokine-Mediated Signaling Pathway (GO:0001961): Calculation completed
Positive Regulation of Epidermal Growth Factor Receptor Signaling Pathway (GO:0045742): Calculation started
Positive Regulation of Epidermal Growth Factor Receptor Signaling Pathway (GO:0045742): scoring computed

Calculating pathways:  69%|██████▉   | 143/206 [12:20<05:16,  5.03s/it]

Positive Regulation of Epidermal Growth Factor Receptor Signaling Pathway (GO:0045742): pvalue calculation completed
Positive Regulation of Epidermal Growth Factor Receptor Signaling Pathway (GO:0045742): Calculation completed
Positive Regulation of Epithelial Cell Migration (GO:0010634): Calculation started
Positive Regulation of Epithelial Cell Migration (GO:0010634): scoring computed

Calculating pathways:  70%|██████▉   | 144/206 [12:24<04:49,  4.66s/it]

Positive Regulation of Epithelial Cell Migration (GO:0010634): pvalue calculation completed
Positive Regulation of Epithelial Cell Migration (GO:0010634): Calculation completed
Positive Regulation of Gene Expression (GO:0010628): Calculation started
Positive Regulation of Gene Expression (GO:0010628): scoring computed

Calculating pathways:  70%|███████   | 145/206 [12:32<05:42,  5.62s/it]

Positive Regulation of Gene Expression (GO:0010628): pvalue calculation completed
Positive Regulation of Gene Expression (GO:0010628): Calculation completed
Positive Regulation of Growth (GO:0045927): Calculation started
Positive Regulation of Growth (GO:0045927): scoring computed

Calculating pathways:  71%|███████   | 146/206 [12:36<05:09,  5.15s/it]

Positive Regulation of Growth (GO:0045927): pvalue calculation completed
Positive Regulation of Growth (GO:0045927): Calculation completed
Positive Regulation of Inflammatory Response (GO:0050729): Calculation started
Positive Regulation of Inflammatory Response (GO:0050729): scoring computed

Calculating pathways:  71%|███████▏  | 147/206 [12:40<04:53,  4.97s/it]

Positive Regulation of Inflammatory Response (GO:0050729): pvalue calculation completed
Positive Regulation of Inflammatory Response (GO:0050729): Calculation completed
Positive Regulation of Keratinocyte Migration (GO:0051549): Calculation started
Positive Regulation of Keratinocyte Migration (GO:0051549): scoring computed

Calculating pathways:  72%|███████▏  | 148/206 [12:44<04:21,  4.51s/it]

Positive Regulation of Keratinocyte Migration (GO:0051549): pvalue calculation completed
Positive Regulation of Keratinocyte Migration (GO:0051549): Calculation completed
Positive Regulation of Lymphocyte Differentiation (GO:0045621): Calculation started
Positive Regulation of Lymphocyte Differentiation (GO:0045621): scoring computed

Calculating pathways:  72%|███████▏  | 149/206 [12:48<04:04,  4.28s/it]

Positive Regulation of Lymphocyte Differentiation (GO:0045621): pvalue calculation completed
Positive Regulation of Lymphocyte Differentiation (GO:0045621): Calculation completed
Positive Regulation of Macrophage Activation (GO:0043032): Calculation started
Positive Regulation of Macrophage Activation (GO:0043032): scoring computed

Calculating pathways:  73%|███████▎  | 150/206 [12:51<03:45,  4.03s/it]

Positive Regulation of Macrophage Activation (GO:0043032): pvalue calculation completed
Positive Regulation of Macrophage Activation (GO:0043032): Calculation completed
Positive Regulation of Microglial Cell Activation (GO:1903980): Calculation started
Positive Regulation of Microglial Cell Activation (GO:1903980): scoring computed

Calculating pathways:  73%|███████▎  | 151/206 [12:54<03:31,  3.84s/it]

Positive Regulation of Microglial Cell Activation (GO:1903980): pvalue calculation completed
Positive Regulation of Microglial Cell Activation (GO:1903980): Calculation completed
Positive Regulation of Multicellular Organismal Process (GO:0051240): Calculation started
Positive Regulation of Multicellular Organismal Process (GO:0051240): scoring computed

Calculating pathways:  74%|███████▍  | 152/206 [13:02<04:27,  4.95s/it]

Positive Regulation of Multicellular Organismal Process (GO:0051240): pvalue calculation completed
Positive Regulation of Multicellular Organismal Process (GO:0051240): Calculation completed
Positive Regulation of Myotube Differentiation (GO:0010831): Calculation started
Positive Regulation of Myotube Differentiation (GO:0010831): scoring computed

Calculating pathways:  74%|███████▍  | 153/206 [13:05<03:56,  4.46s/it]

Positive Regulation of Myotube Differentiation (GO:0010831): pvalue calculation completed
Positive Regulation of Myotube Differentiation (GO:0010831): Calculation completed
Positive Regulation of Neuroinflammatory Response (GO:0150078): Calculation started
Positive Regulation of Neuroinflammatory Response (GO:0150078): scoring computed

Calculating pathways:  75%|███████▍  | 154/206 [13:09<03:35,  4.15s/it]

Positive Regulation of Neuroinflammatory Response (GO:0150078): pvalue calculation completed
Positive Regulation of Neuroinflammatory Response (GO:0150078): Calculation completed
Positive Regulation of Organelle Organization (GO:0010638): Calculation started
Positive Regulation of Organelle Organization (GO:0010638): scoring computed

Calculating pathways:  75%|███████▌  | 155/206 [13:13<03:34,  4.21s/it]

Positive Regulation of Organelle Organization (GO:0010638): pvalue calculation completed
Positive Regulation of Organelle Organization (GO:0010638): Calculation completed
Positive Regulation of Phosphorylation (GO:0042327): Calculation started
Positive Regulation of Phosphorylation (GO:0042327): scoring computed

Calculating pathways:  76%|███████▌  | 156/206 [13:17<03:33,  4.27s/it]

Positive Regulation of Phosphorylation (GO:0042327): pvalue calculation completed
Positive Regulation of Phosphorylation (GO:0042327): Calculation completed
Positive Regulation of Protein Binding (GO:0032092): Calculation started
Positive Regulation of Protein Binding (GO:0032092): scoring computed

Calculating pathways:  76%|███████▌  | 157/206 [13:21<03:23,  4.16s/it]

Positive Regulation of Protein Binding (GO:0032092): pvalue calculation completed
Positive Regulation of Protein Binding (GO:0032092): Calculation completed
Positive Regulation of Protein Modification Process (GO:0031401): Calculation started
Positive Regulation of Protein Modification Process (GO:0031401): scoring computed

Calculating pathways:  77%|███████▋  | 158/206 [13:26<03:26,  4.31s/it]

Positive Regulation of Protein Modification Process (GO:0031401): pvalue calculation completed
Positive Regulation of Protein Modification Process (GO:0031401): Calculation completed
Positive Regulation of Protein Phosphorylation (GO:0001934): Calculation started
Positive Regulation of Protein Phosphorylation (GO:0001934): scoring computed

Calculating pathways:  77%|███████▋  | 159/206 [13:31<03:36,  4.61s/it]

Positive Regulation of Protein Phosphorylation (GO:0001934): pvalue calculation completed
Positive Regulation of Protein Phosphorylation (GO:0001934): Calculation completed
Positive Regulation of Release of Cytochrome C From Mitochondria (GO:0090200): Calculation started
Positive Regulation of Release of Cytochrome C From Mitochondria (GO:0090200): scoring computed

Calculating pathways:  78%|███████▊  | 160/206 [13:35<03:16,  4.28s/it]

Positive Regulation of Release of Cytochrome C From Mitochondria (GO:0090200): pvalue calculation completed
Positive Regulation of Release of Cytochrome C From Mitochondria (GO:0090200): Calculation completed
Positive Regulation of Smooth Muscle Cell Proliferation (GO:0048661): Calculation started
Positive Regulation of Smooth Muscle Cell Proliferation (GO:0048661): scoring computed

Calculating pathways:  78%|███████▊  | 161/206 [13:39<03:09,  4.21s/it]

Positive Regulation of Smooth Muscle Cell Proliferation (GO:0048661): pvalue calculation completed
Positive Regulation of Smooth Muscle Cell Proliferation (GO:0048661): Calculation completed
Positive Regulation of Striated Muscle Cell Differentiation (GO:0051155): Calculation started
Positive Regulation of Striated Muscle Cell Differentiation (GO:0051155): scoring computed

Calculating pathways:  79%|███████▊  | 162/206 [13:43<02:58,  4.05s/it]

Positive Regulation of Striated Muscle Cell Differentiation (GO:0051155): pvalue calculation completed
Positive Regulation of Striated Muscle Cell Differentiation (GO:0051155): Calculation completed
Positive Regulation of Transmembrane Transport (GO:0034764): Calculation started
Positive Regulation of Transmembrane Transport (GO:0034764): scoring computed

Calculating pathways:  79%|███████▉  | 163/206 [13:46<02:48,  3.91s/it]

Positive Regulation of Transmembrane Transport (GO:0034764): pvalue calculation completed
Positive Regulation of Transmembrane Transport (GO:0034764): Calculation completed
Positive Regulation of Tumor Necrosis Factor Production (GO:0032760): Calculation started
Positive Regulation of Tumor Necrosis Factor Production (GO:0032760): scoring computed

Calculating pathways:  80%|███████▉  | 164/206 [13:50<02:46,  3.96s/it]

Positive Regulation of Tumor Necrosis Factor Production (GO:0032760): pvalue calculation completed
Positive Regulation of Tumor Necrosis Factor Production (GO:0032760): Calculation completed
Positive Regulation of Tumor Necrosis Factor Superfamily Cytokine Production (GO:1903557): Calculation started
Positive Regulation of Tumor Necrosis Factor Superfamily Cytokine Production (GO:1903557): scoring computed

Calculating pathways:  80%|████████  | 165/206 [13:54<02:45,  4.04s/it]

Positive Regulation of Tumor Necrosis Factor Superfamily Cytokine Production (GO:1903557): pvalue calculation completed
Positive Regulation of Tumor Necrosis Factor Superfamily Cytokine Production (GO:1903557): Calculation completed
Positive Regulation of Tumor Necrosis Factor-Mediated Signaling Pathway (GO:1903265): Calculation started
Positive Regulation of Tumor Necrosis Factor-Mediated Signaling Pathway (GO:1903265): scoring computed

Calculating pathways:  81%|████████  | 166/206 [13:58<02:33,  3.85s/it]

Positive Regulation of Tumor Necrosis Factor-Mediated Signaling Pathway (GO:1903265): pvalue calculation completed
Positive Regulation of Tumor Necrosis Factor-Mediated Signaling Pathway (GO:1903265): Calculation completed
Positive Regulation of Type II Interferon Production (GO:0032729): Calculation started
Positive Regulation of Type II Interferon Production (GO:0032729): scoring computed

Calculating pathways:  81%|████████  | 167/206 [14:02<02:30,  3.85s/it]

Positive Regulation of Type II Interferon Production (GO:0032729): pvalue calculation completed
Positive Regulation of Type II Interferon Production (GO:0032729): Calculation completed
Positive Regulation of Vascular Associated Smooth Muscle Cell Proliferation (GO:1904707): Calculation started
Positive Regulation of Vascular Associated Smooth Muscle Cell Proliferation (GO:1904707): scoring computed

Calculating pathways:  82%|████████▏ | 168/206 [14:05<02:22,  3.76s/it]

Positive Regulation of Vascular Associated Smooth Muscle Cell Proliferation (GO:1904707): pvalue calculation completed
Positive Regulation of Vascular Associated Smooth Muscle Cell Proliferation (GO:1904707): Calculation completed
Protein Catabolic Process (GO:0030163): Calculation started
Protein Catabolic Process (GO:0030163): scoring computed

Calculating pathways:  82%|████████▏ | 169/206 [14:10<02:27,  3.98s/it]

Protein Catabolic Process (GO:0030163): pvalue calculation completed
Protein Catabolic Process (GO:0030163): Calculation completed
Protein Maturation (GO:0051604): Calculation started
Protein Maturation (GO:0051604): scoring computed

Calculating pathways:  83%|████████▎ | 170/206 [14:15<02:35,  4.31s/it]

Protein Maturation (GO:0051604): pvalue calculation completed
Protein Maturation (GO:0051604): Calculation completed
Protein Metabolic Process (GO:0019538): Calculation started
Protein Metabolic Process (GO:0019538): scoring computed

Calculating pathways:  83%|████████▎ | 171/206 [14:24<03:25,  5.88s/it]

Protein Metabolic Process (GO:0019538): pvalue calculation completed
Protein Metabolic Process (GO:0019538): Calculation completed
Protein Processing (GO:0016485): Calculation started
Protein Processing (GO:0016485): scoring computed

Calculating pathways:  83%|████████▎ | 172/206 [14:29<03:06,  5.50s/it]

Protein Processing (GO:0016485): pvalue calculation completed
Protein Processing (GO:0016485): Calculation completed
Proteolysis (GO:0006508): Calculation started
Proteolysis (GO:0006508): scoring computed

Calculating pathways:  84%|████████▍ | 173/206 [14:35<03:11,  5.79s/it]

Proteolysis (GO:0006508): pvalue calculation completed
Proteolysis (GO:0006508): Calculation completed
Regulation of B Cell Differentiation (GO:0045577): Calculation started
Regulation of B Cell Differentiation (GO:0045577): scoring computed

Calculating pathways:  84%|████████▍ | 174/206 [14:39<02:43,  5.11s/it]

Regulation of B Cell Differentiation (GO:0045577): pvalue calculation completed
Regulation of B Cell Differentiation (GO:0045577): Calculation completed
Regulation of DNA Binding (GO:0051101): Calculation started
Regulation of DNA Binding (GO:0051101): scoring computed

Calculating pathways:  85%|████████▍ | 175/206 [14:43<02:26,  4.73s/it]

Regulation of DNA Binding (GO:0051101): pvalue calculation completed
Regulation of DNA Binding (GO:0051101): Calculation completed
Regulation of Notch Signaling Pathway (GO:0008593): Calculation started
Regulation of Notch Signaling Pathway (GO:0008593): scoring computed

Calculating pathways:  85%|████████▌ | 176/206 [14:47<02:15,  4.53s/it]

Regulation of Notch Signaling Pathway (GO:0008593): pvalue calculation completed
Regulation of Notch Signaling Pathway (GO:0008593): Calculation completed
Regulation of Apoptotic Process (GO:0042981): Calculation started
Regulation of Apoptotic Process (GO:0042981): scoring computed

Calculating pathways:  86%|████████▌ | 177/206 [14:57<03:03,  6.34s/it]

Regulation of Apoptotic Process (GO:0042981): pvalue calculation completed
Regulation of Apoptotic Process (GO:0042981): Calculation completed
Regulation of Cation Channel Activity (GO:2001257): Calculation started
Regulation of Cation Channel Activity (GO:2001257): scoring computed

Calculating pathways:  86%|████████▋ | 178/206 [15:01<02:34,  5.52s/it]

Regulation of Cation Channel Activity (GO:2001257): pvalue calculation completed
Regulation of Cation Channel Activity (GO:2001257): Calculation completed
Regulation of Cell Growth (GO:0001558): Calculation started
Regulation of Cell Growth (GO:0001558): scoring computed

Calculating pathways:  87%|████████▋ | 179/206 [15:07<02:29,  5.55s/it]

Regulation of Cell Growth (GO:0001558): pvalue calculation completed
Regulation of Cell Growth (GO:0001558): Calculation completed
Regulation of Cell Migration (GO:0030334): Calculation started
Regulation of Cell Migration (GO:0030334): scoring computed

Calculating pathways:  87%|████████▋ | 180/206 [15:15<02:45,  6.37s/it]

Regulation of Cell Migration (GO:0030334): pvalue calculation completed
Regulation of Cell Migration (GO:0030334): Calculation completed
Regulation of Cellular Response to Stress (GO:0080135): Calculation started
Regulation of Cellular Response to Stress (GO:0080135): scoring computed

Calculating pathways:  88%|████████▊ | 181/206 [15:20<02:28,  5.93s/it]

Regulation of Cellular Response to Stress (GO:0080135): pvalue calculation completed
Regulation of Cellular Response to Stress (GO:0080135): Calculation completed
Regulation of Cytokine Production (GO:0001817): Calculation started
Regulation of Cytokine Production (GO:0001817): scoring computed

Calculating pathways:  88%|████████▊ | 182/206 [15:25<02:15,  5.66s/it]

Regulation of Cytokine Production (GO:0001817): pvalue calculation completed
Regulation of Cytokine Production (GO:0001817): Calculation completed
Regulation of Epidermal Growth Factor Receptor Signaling Pathway (GO:0042058): Calculation started
Regulation of Epidermal Growth Factor Receptor Signaling Pathway (GO:0042058): scoring computed

Calculating pathways:  89%|████████▉ | 183/206 [15:29<01:57,  5.11s/it]

Regulation of Epidermal Growth Factor Receptor Signaling Pathway (GO:0042058): pvalue calculation completed
Regulation of Epidermal Growth Factor Receptor Signaling Pathway (GO:0042058): Calculation completed
Regulation of Gene Expression (GO:0010468): Calculation started
Regulation of Gene Expression (GO:0010468): scoring computed

Calculating pathways:  89%|████████▉ | 184/206 [15:43<02:53,  7.88s/it]

Regulation of Gene Expression (GO:0010468): pvalue calculation completed
Regulation of Gene Expression (GO:0010468): Calculation completed
Regulation of Inflammatory Response (GO:0050727): Calculation started
Regulation of Inflammatory Response (GO:0050727): scoring computed

Calculating pathways:  90%|████████▉ | 185/206 [15:49<02:32,  7.27s/it]

Regulation of Inflammatory Response (GO:0050727): pvalue calculation completed
Regulation of Inflammatory Response (GO:0050727): Calculation completed
Regulation of Intrinsic Apoptotic Signaling Pathway (GO:2001242): Calculation started
Regulation of Intrinsic Apoptotic Signaling Pathway (GO:2001242): scoring computed

Calculating pathways:  90%|█████████ | 186/206 [15:53<02:05,  6.25s/it]

Regulation of Intrinsic Apoptotic Signaling Pathway (GO:2001242): pvalue calculation completed
Regulation of Intrinsic Apoptotic Signaling Pathway (GO:2001242): Calculation completed
Regulation of Keratinocyte Migration (GO:0051547): Calculation started
Regulation of Keratinocyte Migration (GO:0051547): scoring computed

Calculating pathways:  91%|█████████ | 187/206 [15:56<01:42,  5.41s/it]

Regulation of Keratinocyte Migration (GO:0051547): pvalue calculation completed
Regulation of Keratinocyte Migration (GO:0051547): Calculation completed
Regulation of Microglial Cell Activation (GO:1903978): Calculation started
Regulation of Microglial Cell Activation (GO:1903978): scoring computed

Calculating pathways:  91%|█████████▏| 188/206 [16:00<01:27,  4.85s/it]

Regulation of Microglial Cell Activation (GO:1903978): pvalue calculation completed
Regulation of Microglial Cell Activation (GO:1903978): Calculation completed
Regulation of Monoatomic Anion Transport (GO:0044070): Calculation started
Regulation of Monoatomic Anion Transport (GO:0044070): scoring computed

Calculating pathways:  92%|█████████▏| 189/206 [16:03<01:14,  4.40s/it]

Regulation of Monoatomic Anion Transport (GO:0044070): pvalue calculation completed
Regulation of Monoatomic Anion Transport (GO:0044070): Calculation completed
Regulation of Myotube Differentiation (GO:0010830): Calculation started
Regulation of Myotube Differentiation (GO:0010830): scoring computed

Calculating pathways:  92%|█████████▏| 190/206 [16:07<01:06,  4.14s/it]

Regulation of Myotube Differentiation (GO:0010830): pvalue calculation completed
Regulation of Myotube Differentiation (GO:0010830): Calculation completed
Regulation of Neuroinflammatory Response (GO:0150077): Calculation started
Regulation of Neuroinflammatory Response (GO:0150077): scoring computed

Calculating pathways:  93%|█████████▎| 191/206 [16:10<00:59,  3.96s/it]

Regulation of Neuroinflammatory Response (GO:0150077): pvalue calculation completed
Regulation of Neuroinflammatory Response (GO:0150077): Calculation completed
Regulation of Protein Localization to Cell Periphery (GO:1904375): Calculation started
Regulation of Protein Localization to Cell Periphery (GO:1904375): scoring computed

Calculating pathways:  93%|█████████▎| 192/206 [16:14<00:53,  3.84s/it]

Regulation of Protein Localization to Cell Periphery (GO:1904375): pvalue calculation completed
Regulation of Protein Localization to Cell Periphery (GO:1904375): Calculation completed
Regulation of Protein Localization to Membrane (GO:1905475): Calculation started
Regulation of Protein Localization to Membrane (GO:1905475): scoring computed

Calculating pathways:  94%|█████████▎| 193/206 [16:18<00:49,  3.84s/it]

Regulation of Protein Localization to Membrane (GO:1905475): pvalue calculation completed
Regulation of Protein Localization to Membrane (GO:1905475): Calculation completed
Regulation of Protein Localization to Plasma Membrane (GO:1903076): Calculation started
Regulation of Protein Localization to Plasma Membrane (GO:1903076): scoring computed

Calculating pathways:  94%|█████████▍| 194/206 [16:22<00:48,  4.01s/it]

Regulation of Protein Localization to Plasma Membrane (GO:1903076): pvalue calculation completed
Regulation of Protein Localization to Plasma Membrane (GO:1903076): Calculation completed
Regulation of Protein Phosphorylation (GO:0001932): Calculation started
Regulation of Protein Phosphorylation (GO:0001932): scoring computed

Calculating pathways:  95%|█████████▍| 195/206 [16:27<00:46,  4.24s/it]

Regulation of Protein Phosphorylation (GO:0001932): pvalue calculation completed
Regulation of Protein Phosphorylation (GO:0001932): Calculation completed
Regulation of Receptor Binding (GO:1900120): Calculation started
Regulation of Receptor Binding (GO:1900120): scoring computed

Calculating pathways:  95%|█████████▌| 196/206 [16:30<00:39,  3.99s/it]

Regulation of Receptor Binding (GO:1900120): pvalue calculation completed
Regulation of Receptor Binding (GO:1900120): Calculation completed
Regulation of Release of Cytochrome C From Mitochondria (GO:0090199): Calculation started
Regulation of Release of Cytochrome C From Mitochondria (GO:0090199): scoring computed

Calculating pathways:  96%|█████████▌| 197/206 [16:34<00:35,  3.95s/it]

Regulation of Release of Cytochrome C From Mitochondria (GO:0090199): pvalue calculation completed
Regulation of Release of Cytochrome C From Mitochondria (GO:0090199): Calculation completed
Regulation of Tumor Necrosis Factor Production (GO:0032680): Calculation started
Regulation of Tumor Necrosis Factor Production (GO:0032680): scoring computed

Calculating pathways:  96%|█████████▌| 198/206 [16:39<00:33,  4.19s/it]

Regulation of Tumor Necrosis Factor Production (GO:0032680): pvalue calculation completed
Regulation of Tumor Necrosis Factor Production (GO:0032680): Calculation completed
Regulation of Tumor Necrosis Factor-Mediated Signaling Pathway (GO:0010803): Calculation started
Regulation of Tumor Necrosis Factor-Mediated Signaling Pathway (GO:0010803): scoring computed

Calculating pathways:  97%|█████████▋| 199/206 [16:43<00:28,  4.09s/it]

Regulation of Tumor Necrosis Factor-Mediated Signaling Pathway (GO:0010803): pvalue calculation completed
Regulation of Tumor Necrosis Factor-Mediated Signaling Pathway (GO:0010803): Calculation completed
Regulation of Type II Interferon Production (GO:0032649): Calculation started
Regulation of Type II Interferon Production (GO:0032649): scoring computed

Calculating pathways:  97%|█████████▋| 200/206 [16:47<00:25,  4.17s/it]

Regulation of Type II Interferon Production (GO:0032649): pvalue calculation completed
Regulation of Type II Interferon Production (GO:0032649): Calculation completed
Regulation of Vascular Associated Smooth Muscle Cell Proliferation (GO:1904705): Calculation started
Regulation of Vascular Associated Smooth Muscle Cell Proliferation (GO:1904705): scoring computed

Calculating pathways:  98%|█████████▊| 201/206 [16:51<00:20,  4.03s/it]

Regulation of Vascular Associated Smooth Muscle Cell Proliferation (GO:1904705): pvalue calculation completed
Regulation of Vascular Associated Smooth Muscle Cell Proliferation (GO:1904705): Calculation completed
Response to UV-A (GO:0070141): Calculation started
Response to UV-A (GO:0070141): scoring computed

Calculating pathways:  98%|█████████▊| 202/206 [16:54<00:15,  3.85s/it]

Response to UV-A (GO:0070141): pvalue calculation completed
Response to UV-A (GO:0070141): Calculation completed
Response to Amyloid-Beta (GO:1904645): Calculation started
Response to Amyloid-Beta (GO:1904645): scoring computed

Calculating pathways:  99%|█████████▊| 203/206 [16:58<00:11,  3.86s/it]

Response to Amyloid-Beta (GO:1904645): pvalue calculation completed
Response to Amyloid-Beta (GO:1904645): Calculation completed
Response to Lipopolysaccharide (GO:0032496): Calculation started
Response to Lipopolysaccharide (GO:0032496): scoring computed

Calculating pathways:  99%|█████████▉| 204/206 [17:03<00:08,  4.18s/it]

Response to Lipopolysaccharide (GO:0032496): pvalue calculation completed
Response to Lipopolysaccharide (GO:0032496): Calculation completed
Skeletal System Development (GO:0001501): Calculation started
Skeletal System Development (GO:0001501): scoring computed

Calculating pathways: 100%|█████████▉| 205/206 [17:08<00:04,  4.41s/it]

Skeletal System Development (GO:0001501): pvalue calculation completed
Skeletal System Development (GO:0001501): Calculation completed
Zymogen Activation (GO:0031638): Calculation started
Zymogen Activation (GO:0031638): scoring computed

Calculating pathways: 100%|██████████| 206/206 [17:11<00:00,  5.01s/it]

Zymogen Activation (GO:0031638): pvalue calculation completed
Zymogen Activation (GO:0031638): Calculation completed

## Checking if the drug names are present in the IDG_2022_dataset

In [1]:
import requests
import time
import json
from typing import List, Dict, Optional

# === Configuration ===
SLEEP_BETWEEN_REQUESTS = 0.2   # seconds, be polite to the APIs
USER_AGENT = "synonym-fetcher/1.0 (+https://example.org/)"
CHEMBL_BASE = "https://www.ebi.ac.uk/chembl/api/data"
PUBCHEM_SYNS_URL = "https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/name/{}/synonyms/JSON"

HEADERS = {"User-Agent": USER_AGENT}

# === Helper utilities ===
def _dedupe_preserve_order(items: List[str]) -> List[str]:
    seen = set()
    out = []
    for i in items:
        i2 = i.strip()
        if not i2:
            continue
        if i2 not in seen:
            seen.add(i2)
            out.append(i2)
    return out

# === ChEMBL lookup ===
def chembl_synonyms(drug_name: str, max_candidates: int = 1) -> List[str]:
    """Search ChEMBL by name, then get synonyms for the first candidate(s).
       Returns list of synonyms (may be empty)."""
    syns = []
    try:
        # Search molecules by text
        r = requests.get(f"{CHEMBL_BASE}/molecule", params={"search": drug_name, "format": "json"}, headers=HEADERS, timeout=15)
        r.raise_for_status()
        j = r.json()
        molecules = j.get("molecules") or j.get("molecule") or []
        # take up to max_candidates molecules
        for mol in molecules[:max_candidates]:
            chembl_id = mol.get("molecule_chembl_id")
            if not chembl_id:
                continue
            # fetch synonyms for this ChEMBL id
            time.sleep(SLEEP_BETWEEN_REQUESTS)
            r2 = requests.get(f"{CHEMBL_BASE}/molecule_synonym", params={"molecule_chembl_id": chembl_id, "format": "json"}, headers=HEADERS, timeout=15)
            r2.raise_for_status()
            j2 = r2.json()
            syn_entries = j2.get("molecule_synonyms") or j2.get("molecule_synonym") or []
            # field name differs: items often have 'synonyms' or 'molecule_synonym'
            for se in syn_entries:
                # common keys: 'synonym' or 'molecule_synonym' or 'synonyms'
                s = se.get("synonym") or se.get("molecule_synonym") or se.get("synonyms")
                if s:
                    syns.append(s)
            # also add the molecule pref name if available
            pref_name = mol.get("pref_name")
            if pref_name:
                syns.append(pref_name)
            # add the canonical name and chembl id
            mol_name = mol.get("molecule_name")
            if mol_name:
                syns.append(mol_name)
            syns.append(chembl_id)
    except requests.HTTPError:
        # API returned non-200; ignore and return what we have
        pass
    except Exception:
        # network or JSON parse errors - ignore and continue
        pass

    time.sleep(SLEEP_BETWEEN_REQUESTS)
    return _dedupe_preserve_order(syns)


# === PubChem lookup ===
def pubchem_synonyms(drug_name: str) -> List[str]:
    """Query PubChem PUG-REST synonyms endpoint for the supplied name."""
    syns = []
    try:
        url = PUBCHEM_SYNS_URL.format(requests.utils.requote_uri(drug_name))
        r = requests.get(url, headers=HEADERS, timeout=15)
        if r.status_code == 200:
            j = r.json()
            info_list = j.get("InformationList", {}).get("Information", [])
            if info_list:
                first = info_list[0]
                synonyms = first.get("Synonym") or []
                syns.extend(synonyms)
        # else: non-200 (e.g., 404), just return empty
    except Exception:
        pass

    time.sleep(SLEEP_BETWEEN_REQUESTS)
    return _dedupe_preserve_order(syns)


# === Combined lookup routine ===
def get_combined_synonyms(drug_names: List[str], use_chembl: bool = True, use_pubchem: bool = True) -> Dict[str, List[str]]:
    """For each drug name in drug_names, query selected sources and merge synonyms."""
    results: Dict[str, List[str]] = {}
    for drug in drug_names:
        merged = []
        # canonical input name first (helps preserve mapping)
        merged.append(drug.strip())
        # ChEMBL
        if use_chembl:
            try:
                ch_syns = chembl_synonyms(drug)
                merged.extend(ch_syns)
            except Exception:
                pass
        # PubChem
        if use_pubchem:
            try:
                pc_syns = pubchem_synonyms(drug)
                merged.extend(pc_syns)
            except Exception:
                pass

        # final dedupe/preserve order
        final_list = _dedupe_preserve_order(merged)
        results[drug] = final_list
    return results

In [3]:
drugs = [
    "Abemaciclib",
    "Alpelisib",
    "Anastrozole",
    "Aromatase inhibitor",
    "Atezolizumab",
    "Bevacizumab",
    "Capivasertib",
    "Dostarlimab",
    "Elacestrant",
    "Entrectinib",
    "Everolimus",
    "Exemestane",
    "Fulvestrant",
    "Lapatinib",
    "Larotrectinib",
    "Letrozole",
    "Margetuximab",
    "Neratinib",
    "Olaparib",
    "Palbociclib",
    "Pembrolizumab",
    "Pertuzumab",
    "Ribociclib",
    "Sacituzumab govitecan",
    "Selpercatinib",
    "Talazoparib",
    "Tamoxifen",
    "Toremifene",
    "Trastuzumab",
    "Trastuzumab deruxtecan",
    "Trastuzumab emtansine",
    "Tucatinib"
]


out = get_combined_synonyms(drugs)
# print to console nicely
print(json.dumps(out, indent=2, ensure_ascii=False))

# optionally save to file
with open("drug_synonyms_combined.json", "w", encoding="utf-8") as f:
    json.dump(out, f, indent=2, ensure_ascii=False)
print("Saved -> drug_synonyms_combined.json")

{
  "Abemaciclib": [
    "Abemaciclib",
    "1231929-97-7",
    "LY2835219",
    "Verzenio",
    "LY-2835219",
    "N-(5-((4-ethylpiperazin-1-yl)methyl)pyridin-2-yl)-5-fluoro-4-(4-fluoro-1-isopropyl-2-methyl-1H-benzo[d]imidazol-6-yl)pyrimidin-2-amine",
    "Verzenios",
    "60UAB198HK",
    "N-[5-[(4-ethylpiperazin-1-yl)methyl]pyridin-2-yl]-5-fluoro-4-(7-fluoro-2-methyl-3-propan-2-ylbenzimidazol-5-yl)pyrimidin-2-amine",
    "LY 2835219",
    "LY2835210",
    "LY-2835210",
    "2-Pyrimidinamine, N-(5-((4-ethyl-1-piperazinyl)methyl)-2-pyridinyl)-5-fluoro-4-(4-fluoro-2-methyl-1-(1-methylethyl)-1H-benzimidazol-6-yl)",
    "5-(4-ethylpiperazin-1-ylmethyl)pyridin-2-yl)-(5-fluoro-4-(7-fluoro-3-isopropyl-2-methyl-3H-benzimidazol-5-yl)pyrimidin-2-yl)amine",
    "5-(4-ethylpiperazin-1-ylmethyl)pyridin-2-yl)-(5-fluoro-4-(7-fluoro-3-isopropyl-2-methyl-3H-benzoimidazol-5-yl)pyrimidin-2-yl)amine",
    "abemaciclibum",
    "N-(5-((4-ethylpiperazin-1-yl)methyl)pyridin-2-yl)-5-fluoro-4-(4-fluoro-1-isopropyl-2-methyl-1H-benzo(d)imidazol-6-yl)pyrimidin-2-amine",
    "N-(5-((4-ethylpiperazin-1-yl)methyl)pyridin-2-yl)-5-fluoro-4-(4-fluoro-2-methyl-1-(propan-2-yl)-1H-1,3-benzodiazol-6-yl)pyrimidin-2-amine",
    "N-(5-((4-ethylpiperazin-1-yl)methyl)pyridin-2-yl)-5-fluoro-4-(7-fluoro-2-methyl-3-propan-2-ylbenzimidazol-5-yl)pyrimidin-2-amine",
    "N-{5-[(4-ethylpiperazin-1-yl)methyl]pyridin-2-yl}-5-fluoro-4-[4-fluoro-2-methyl-1-(propan-2-yl)-1H-1,3-benzodiazol-6-yl]pyrimidin-2-amine",
    "RefChem:58097",
    "L01XE50",
    "LY2385219",
    "806-670-8",
    "LY2835219 free base",
    "UNII-60UAB198HK",
    "MFCD22665744",
    "2-Pyrimidinamine, N-[5-[(4-ethyl-1-piperazinyl)methyl]-2-pyridinyl]-5-fluoro-4-[4-fluoro-2-methyl-1-(1-methylethyl)-1H-benzimidazol-6-yl]-",
    "C27H32F2N8",
    "HY-16297A",
    "s5716",
    "CS-1230",
    "N-{5-[(4-ethylpiperazin-1-yl)methyl]pyridin-2-yl}-5-fluoro-4-(7-fluoro-3-isopropyl-2-methyl-1,3-benzodiazol-5-yl)pyrimidin-2-amine",
    "N-{5-[(4-Ethylpiperazin-1-yl)methyl]pyridin-2-yl}-5-fluoro-4-[4-fluoro-2-methyl-1-(propan-2-yl)-1H-benzimidazol-6-yl]pyrimidin-2-amine",
    "Abemaciclib [USAN:INN]",
    "LY2835219 (free base)",
    "rimidin-2-amine",
    "Verzenio (TN)",
    "6ZV",
    "N-{5-[(4-ethylpiperazin-1-yl)methyl]pyridin-2-yl}-5-fluoro-4-[4-fluoro-2-methyl-1-(propan-2-yl)-1H-benzimidazol-6-yl]py rimidin-2-amine",
    "Abemaciclib (Standard)",
    "ABEMACICLIB [MI]",
    "ABEMACICLIB [INN]",
    "ABEMACICLIB [JAN]",
    "ABEMACICLIB [USAN]",
    "ABEMACICLIB [WHO-DD]",
    "Abemaciclib (JAN/USAN/INN)",
    "GTPL7382",
    "orb1305567",
    "SCHEMBL2487229",
    "CHEMBL3301610",
    "SCHEMBL29356350",
    "SCHEMBL29423472",
    "SCHEMBL29591527",
    "ABEMACICLIB [ORANGE BOOK]",
    "DTXSID20673119",
    "EX-A521",
    "LY 2835219 (free base)",
    "CHEBI:233362",
    "UZWDCWONPYILKI-UHFFFAOYSA-N",
    "HMS3673I05",
    "HMS5085C17",
    "HY-16297AR",
    "EX-A1588",
    "BDBM50110183",
    "NSC768073",
    "NSC783671",
    "1231929-97-7, Verzenio,",
    "AKOS025404907",
    "LY2835219 free base (Abemaciclib)",
    "CCG-269750",
    "DB12001",
    "NSC-768073",
    "NSC-783671",
    "SB16476",
    "LY2835219 free base (Abemaciclib)?",
    "NCGC00351599-02",
    "NCGC00351599-06",
    "AC-30666",
    "AS-10230",
    "BP-43621",
    "DA-33422",
    "FE103812",
    "LY2835219 Ms salt, Abemaciclib Ms salt",
    "LY 2835210",
    "NS00072970",
    "D10688",
    "EN300-7406007",
    "F979456",
    "BRD-K33622447-066-01-9",
    "Q23901483",
    "[5-(4-ethyl-piperazin-1-ylmethyl)-pyridin-2-yl]-[5-fluoro-4-(7-fluoro-3-isopropyl-2-methyl-3H-benzoimidazol-5-yl)-pyrimidin-2-yl]-amine",
    "Ethyl-1-piperazinyl)methyl]-2-pyridinyl]-5-fluoro-4-[4-fluoro-2-methyl-1-(1-methylethyl)-1H-benzimidazol-6-yl]-2-pyrimidinamine",
    "N-[5-[(4-Ethyl-1-piperazinyl)methyl]-2-pyridinyl]-5-fluoro-4-[4-fluoro-2-methyl-1-(1-methylethyl)-1H-benzimidazol-6-yl]-2-pyrimidinamine",
    "N-[5-[(4-ethylpiperazin-1-yl)methyl]-2-pyridyl]-5-fluoro-4-(7-fluoro-3-isopropyl-2-methyl-benzimidazol-5-yl)pyrimidin-2-amine",
    "N-{5-[(4-ethylpiperazin-1-yl)methyl]pyridin-2-yl}-5-fluoro-4-[4-fluoro-2-methyl-1-(propan-2-yl)-1H-benzimidazol-6-yl]py"
  ],
  "Alpelisib": [
    "Alpelisib",
    "alpelisib",
    "1217486-61-7",
    "BYL-719",
    "BYL719",
    "Piqray",
    "NVP-BYL719",
    "Vijoice",
    "BYL 719",
    "08W5N2C97Q",
    "1,2-PYRROLIDINEDICARBOXAMIDE, N1-[4-METHYL-5-[2-(2,2,2-TRIFLUORO-1,1-DIMETHYLETHYL)-4-PYRIDINYL]-2-THIAZOLYL]-, (2S)-",
    "(2S)-1-N-[4-methyl-5-[2-(1,1,1-trifluoro-2-methylpropan-2-yl)pyridin-4-yl]-1,3-thiazol-2-yl]pyrrolidine-1,2-dicarboxamide",
    "1,2-Pyrrolidinedicarboxamide, N1-(4-methyl-5-(2-(2,2,2-trifluoro-1,1-dimethylethyl)-4-pyridinyl)-2-thiazolyl)-, (2S)-",
    "DTXSID70153355",
    "(S)-Pyrrolidine-1,2-dicarboxylic acid 2-amide 1-(4-methyl-5-(2-(2,2,2-trifluoro-1,1-dimethylethyl)-pyridin-4-yl)thiazol-2-yl)amide",
    "alpelisibum",
    "(2S)-1-N-(4-methyl-5-(2-(1,1,1-trifluoro-2-methylpropan-2-yl)pyridin-4-yl)-1,3-thiazol-2-yl)pyrrolidine-1,2-dicarboxamide",
    "(2S)-1-N-{4-methyl-5-[2-(1,1,1-trifluoro-2-methylpropan-2-yl)pyridin-4-yl]-1,3-thiazol-2-yl}pyrrolidine-1,2-dicarboxamide",
    "RefChem:57062",
    "DTXCID7075846",
    "L01XX65",
    "Phosphoinositide 3-kinase Inhibitor BYL719",
    "Alpelisib (BYL719)",
    "(S)-N1-(4-Methyl-5-(2-(1,1,1-trifluoro-2-methylpropan-2-yl)pyridin-4-yl)thiazol-2-yl)pyrrolidine-1,2-dicarboxamide",
    "MFCD22417085",
    "UNII-08W5N2C97Q",
    "Alpelisib [USAN:INN]",
    "CHEMBL2396661",
    "Alpelisib [INN]",
    "(2s)-N~1~-{4-Methyl-5-[2-(1,1,1-Trifluoro-2-Methylpropan-2-Yl)pyridin-4-Yl]-1,3-Thiazol-2-Yl}pyrrolidine-1,2-Dicarboxamide",
    "(S)-N1-(4-methyl-5-(2-(1,1,1-trifluoro-2-methylpropan-2-yl)pyridin-4-yl)thiazol-2-yl)pyrrolidine-1,2-dicarboxamide.",
    "C19H22F3N5O2S",
    "4jps",
    "1LT",
    "Alpelisib [USAN]",
    "Vijoice (TN)",
    "Piqray (TN)",
    "ALPELISIB [JAN]",
    "ALPELISIB [MI]",
    "ALPELISIB [WHO-DD]",
    "Alpelisib (JAN/USAN/INN)",
    "GTPL7955",
    "orb1307105",
    "SCHEMBL1911869",
    "ALPELISIB [ORANGE BOOK]",
    "SCHEMBL29358059",
    "CHEBI:93752",
    "EX-A405",
    "STUWGJZDJHPWGZ-LBPRGKRZSA-N",
    "BDBM738244",
    "BYL 719; BYL719",
    "BDBM50436459",
    "NSC765974",
    "NSC800065",
    "s2814",
    "AKOS022186315",
    "CCG-269139",
    "CS-0663",
    "DB12015",
    "FP71607",
    "NSC-765974",
    "NSC-800065",
    "SDCCGSBI-0654479.P001",
    "US20250145589, Example Alpelisib",
    "NCGC00346717-03",
    "NCGC00346717-06",
    "NCGC00346717-12",
    "(2S)-N1-[4-Methyl-5-[2-(2,2,2-trifluoro-1,1-dimethylethyl)-4-pyridinyl]-2-thiazolyl]-1,2-pyrrolidine",
    "AC-37083",
    "AS-16349",
    "HY-15244",
    "NS00072895",
    "SW220128-1",
    "cas:1217486-61-7;BYL-719",
    "D11011",
    "EN300-23810842",
    "BRD-K54997624-001-06-0",
    "Q27074391",
    "(2S)-N1-[4-methyl-5-[2-(2,2,2-trifluoro-1,1-dimethyl-ethyl)-4-pyridyl]thiazol-2-yl]pyrrolidine-1,2-dicarboxamide",
    "(2S)-N1-{4-Methyl-5-[1-(1,1,1-trifluoro-2-methylpropan-2-yl)pyridin-4-yl]-1,3-thiazol-2-yl}pyrrolidine-1,2-dicarboxamide",
    "(2S)-N1-{4-METHYL-5-[2-(1,1,1-TRIFLUORO-2-METHYLPROPAN-2-YL)PYRIDIN-4-YL]-1,3-THIAZOL-2-YL}PYRROLIDINE-1,2-DICARBOXAMIDE",
    "(S)-Pyrrolidine-1,2-dicarboxylic acid 2-amide 1-[4-methyl-5-[2-(2,2,2-trifluoro-1,1-dimethylethyl)-pyridin-4-yl]thiazol-2-yl]amide;A  lpelisib"
  ],
  "Anastrozole": [
    "Anastrozole",
    "anastrozole",
    "120511-73-1",
    "Arimidex",
    "anastrazole",
    "Anastrozol",
    "ZD1033",
    "ICI D1033",
    "ZD-1033",
    "ICI-D1033",
    "ZD 1033",
    "DTXSID9022607",
    "2Z07MYW1AZ",
    "NSC-719344",
    "NSC-759855",
    "CHEBI:2704",
    "alpha,alpha,alpha',alpha'-Tetramethyl-5-(1H-1,2,4-triazol-1-ylmethyl)-m-benzenediacetonitrile",
    "Rvg-106400",
    "NSC719344",
    "DTXCID202607",
    "1,3-Benzenediacetonitrile, alpha,alpha,alpha',alpha'-tetramethyl-5-(1H-1,2,4-triazol-1-ylmethyl)-",
    "Zeneca ZD 1033",
    "2-[3-(1-cyano-1-methylethyl)-5-(1H-1,2,4-triazol-1-ylmethyl)phenyl]-2-methylpropanenitrile",
    "anastrozolum",
    "Nastrosa",
    "Anastrozole Tablets",
    "2-(3-(1-Cyano-1-methylethyl)-5-(1H-1,2,4-triazol-1-ylmethyl)phenyl)-2-methylpropanenitrile",
    "2,2'-(5-(1H-1,2,4-triazol-1-ylmethyl)-1,3-phenylene)bis(2-methylpropionitrile)",
    "RefChem:54202",
    "L02BG03",
    "2,2'-(5-(1H-1,2,4-Triazol-1-ylmethyl)-1,3-phenylene)di(2-methylpropionitrile)",
    "Alpha,alpha,alpha', alpha'-tetramethyl-5-(1H-1,2,4-triazol-1-ylmethyl)-1,3-benzenediacetonitrile",
    "2,2'-(5-((1H-1,2,4-triazol-1-yl)methyl)-1,3-phenylene)bis(2-methylpropanenitrile)",
    "MFCD00866298",
    "CHEMBL1399",
    "2,2'-[5-(1H-1,2,4-triazol-1-ylmethyl)benzene-1,3-diyl]bis(2-methylpropanenitrile)",
    "NCGC00164619-01",
    "Asiolex",
    "alpha1,alpha1,alpha3,alpha3-Tetramethyl-5-(1H-1,2,4-triazol-1-ylmethyl)-1,3-benzenediacetonitrile",
    "Arimidex (TN)",
    "SMR000466301",
    "CAS-120511-73-1",
    "HSDB 7462",
    "ICI-D 1033",
    "SR-01000759390",
    "UNII-2Z07MYW1AZ",
    "Anastrozole?",
    "2-[3-(2-cyanopropan-2-yl)-5-(1,2,4-triazol-1-ylmethyl)phenyl]-2-methylpropanenitrile",
    "CCRIS 9352",
    "Anastrozole [USAN:USP:INN:BAN]",
    "Anastrozole; 2,2'-[5-(1H-1,2,4-Triazol-1-ylmethyl)benzene-1,3-diyl]bis(2-methylpropanenitrile)",
    "Anastrozole (Standard)",
    "Arimidex (AstraZeneca)",
    "ANASTROZOLE [MI]",
    "ANASTROZOLE [INN]",
    "ANASTROZOLE [JAN]",
    "ANASTROZOLE [HSDB]",
    "ANASTROZOLE [USAN]",
    "SCHEMBL9726",
    "ANASTROZOLE [MART.]",
    "ANASTROZOLE [USP-RS]",
    "ANASTROZOLE [WHO-DD]",
    "MLS000759396",
    "MLS001424217",
    "MLS006011961",
    "GTPL5137",
    "orb1310655",
    "Anastrozole (JP18/USP/INN)",
    "Anastrozole - Bio-X trade mark",
    "BDBM10015",
    "ANASTROZOLE [ORANGE BOOK]",
    "ANASTROZOLE [EP MONOGRAPH]",
    "ANASTROZOLE [USP IMPURITY]",
    "GLXC-03925",
    "HMS2052M11",
    "HMS2089N10",
    "HMS2235M06",
    "HMS3369K05",
    "HMS3394M11",
    "HMS3654I18",
    "HMS3715B05",
    "HMS3742O21",
    "HMS3866K03",
    "HMS5079E13",
    "Pharmakon1600-01502278",
    "ANASTROZOLE [USP MONOGRAPH]",
    "ALBB-037397",
    "VEA51232",
    "Tox21_112238",
    "Tox21_303568",
    "HY-14274R",
    "NSC759855",
    "s1188",
    "STL451008",
    "AKOS015894980",
    "tetramethyl-5-(1h-1,2,4-triazol-1ylmethyl) 1,3-benzenediacetionitrile",
    "Tox21_112238_1",
    "AC-4234",
    "CCG-101109",
    "CS-0716",
    "DB01217",
    "FT10600",
    "KS-5052",
    "NC00359",
    "NSC 719344",
    "NSC 759855",
    "SB17304",
    "2,2'-[5-(1H-1,2,4-triazol-1-ylmethyl)-1,3-phenylene]bis(2-methylpropanenitrile)",
    "2-[3-(1-cyano-1-methyl-ethyl)-5-(1,2,4-triazol-1-ylmethyl)phenyl]-2-methyl-propanenitrile",
    "3-Phenylene]bis(2-methyl-propiononitrile",
    "NCGC00164619-02",
    "NCGC00164619-04",
    "NCGC00257356-01",
    "BT164176",
    "HY-14274",
    "A2370",
    "NS00005588",
    "SW197739-4",
    "11A731",
    "C08159",
    "D00960",
    "EN300-118709",
    "AB00639929-06",
    "AB00639929-08",
    "AB00639929-09",
    "AB00639929-10",
    "AB00639929_11",
    "AB00639929_13",
    "A804526",
    "Q419143",
    "2;2\"-[5-(1H-1;2;4-Triazol-1-ylmethyl)-1",
    "SR-01000759390-4",
    "SR-01000759390-5",
    "BRD-K52172416-001-10-6",
    "BRD-K52172416-001-11-4",
    "Z1515385077",
    "1,.alpha.,alpha.,alpha.',.alpha.'-tetramethyl-5-(1H-1,2,4-triazol-1-ylmethyl)-",
    "2,2'-[5-(1H-1,2,4-triazol-1-yl-methyl)-1,3-phenylene]-di(2-methyl propionitrile)",
    "2,2'-[5-(1H-1,2,4-triazol-1-ylmethyl)-1,3-phenylene]di(2-methylpropiononitrile)",
    "2,2'-[5-(1H-1,2,4-triazole-1-yl-methyl)-1,3-phenylene]di(2-methyl propionitrile)",
    "2-[3-(2-cyano-2-propyl)-5-(1,2,4-triazol-1-ylmethyl)phenyl]-2-methylpropiononitrile",
    "2-[3-(2-cyanopropan-2-yl)-5-(1,2,4-triazol-1-ylmethyl)phenyl]-2-methyl-propanenitrile",
    "a,a,a',a'-Tetramethyl-5-(1H-1,2,4-triazol-1-ylmethyl)-1,3-benzenediacetonitrile",
    ".alpha.,.alpha.',.alpha.'-tetramethyl-5(1H-1,2,4-triazol-1-ylmethyl)-m-benzenediacetonitrile",
    ".ALPHA.,.ALPHA.,.ALPHA.',.ALPHA.'-TETRAMETHYL-5-(1H-1,2,4-TRIAZOL-1-YLMETHYL)-M-BENZENEDIACETONITRILE",
    "1,3-BENZENEDIACETONITRILE,.ALPHA.,.ALPHA.,.ALPHA.',.ALPHA.'-TETRAMETHYL-5-(1H-1,2,4-TRIAZOL-1-YLMETHYL)-",
    "2-[3-(1-cyano-1-methylethyl)-5-[(1H-1,2,4-triazol-1-yl)methyl]phenyl]-2-methylpropanenitrile",
    "alpha,alpha,alpha',alpha'-Tetramethyl-5-(1H-1,2,4-triazol-1-ylmethyl)-1,3-benzenediacetonitrile"
  ],
  "Aromatase inhibitor": [
    "Aromatase inhibitor"
  ],
  "Atezolizumab": [
    "Atezolizumab"
  ],
  "Bevacizumab": [
    "Bevacizumab"
  ],
  "Capivasertib": [
    "Capivasertib",
    "capivasertib",
    "1143532-39-1",
    "AZD5363",
    "AZD-5363",
    "AZD 5363",
    "Truqap",
    "4-Amino-N-[(1s)-1-(4-Chlorophenyl)-3-Hydroxypropyl]-1-(7h-Pyrrolo[2,3-D]pyrimidin-4-Yl)piperidine-4-Carboxamide",
    "WFR23M21IE",
    "DTXSID40150710",
    "4-amino-N-(1-(4-chlorophenyl)-3-hydroxypropyl)-1-(7H-pyrrolo(2,3-d)pyrimidin-4-yl)piperidine-4-carboxamide",
    "capivasertibum",
    "4-Amino-N-((1S)-1-(4-chlorophenyl)-3-hydroxypropyl)-1-(7H-pyrrolo(2,3-d)pyrimidin-4-yl)piperidine-4-carboxamide",
    "RefChem:573743",
    "DTXCID4073201",
    "(S)-4-AMINO-N-(1-(4-CHLOROPHENYL)-3-HYDROXYPROPYL)-1-(7H-PYRROLO[2,3-D]PYRIMIDIN-4-YL)PIPERIDINE-4-CARBOXAMIDE",
    "MFCD22628785",
    "4-Piperidinecarboxamide, 4-amino-N-[(1S)-1-(4-chlorophenyl)-3-hydroxypropyl]-1-(7H-pyrrolo[2,3-d]pyrimidin-4-yl)-",
    "4-amino-N-[(1S)-1-(4-chlorophenyl)-3-hydroxy-propyl]-1-(7H-pyrrolo[2,3-d]pyrimidin-4-yl)piperidine-4-carboxamide",
    "UNII-WFR23M21IE",
    "CHEMBL2325741",
    "C21H25ClN6O2",
    "cc-638",
    "Capivasertib?",
    "(S)-4-Amino-N-[1-(4-chlorophenyl)-3-hydroxypropyl]-1-(7H-pyrrolo[2,3-d]pyrimidin-4-yl)piperidine-4-carboxamide",
    "4-PIPERIDINECARBOXAMIDE, 4-AMINO-N-((1S)-1-(4-CHLOROPHENYL)-3-HYDROXYPROPYL)-1-(7H-PYRROLO(2,3-D)PYRIMIDIN-4-YL)-",
    "Truqap (TN)",
    "Capivasertib (JAN/USAN)",
    "CAPIVASERTIB [INN]",
    "CAPIVASERTIB [JAN]",
    "CAPIVASERTIB [USAN]",
    "Capivasertib (AZD5363)",
    "4-Amino-N-[(1S)-1-(4-chlorophenyl)-3-hydroxypropyl]-1-(7H-pyrrolo[2,3-d]pyrimidin-4-yl)-4-piperidinecarboxamide",
    "MLS006011179",
    "CAPIVASERTIB [WHO-DD]",
    "SCHEMBL390243",
    "GTPL7709",
    "orb1307109",
    "SCHEMBL29357463",
    "SCHEMBL29557103",
    "AZC5363",
    "EX-A285",
    "CHEBI:229222",
    "JDUBGYFRJFOXQC-KRWDZBQOSA-N",
    "US10654855, Example 9",
    "BDBM443385",
    "AZD5363?",
    "NSC764039",
    "NSC782347",
    "NSC799347",
    "s8019",
    "AKOS027323693",
    "CCG-268989",
    "CS-1284",
    "DB12218",
    "FA29493",
    "NSC-764039",
    "NSC-782347",
    "NSC-799347",
    "NCGC00345795-01",
    "NCGC00345795-03",
    "NCGC00345795-04",
    "NCGC00345795-08",
    "AC-32685",
    "BP-43630",
    "HY-15431",
    "SMR004702948",
    "SY018928",
    "DB-290280",
    "NS00072563",
    "SW220158-1",
    "D11371",
    "BRD-K99023089-001-03-7",
    "Q27074756",
    "0XZ",
    "4-AMINO-N-((1S)-1-(4-CHLOROPHENYL)-3-HYDROXYPROPYL)-1- (1H-PYRROLO(2,3-D)PYRIMIDIN-4-YL)PIPERIDINE-4-CARBOXAMIDE",
    "ALTERNATIVE ROUTE 1: (S)-4-AMINO-N-(1-(4-CHLOROPHENYL)-3-HYDROXYPROPYL)-1-(7H-PYRROLO[2,3-D]PYRIMIDIN-4-YL)PIPERIDINE-4-CARBOXAMIDE"
  ],
  "Dostarlimab": [
    "Dostarlimab"
  ],
  "Elacestrant": [
    "Elacestrant",
    "722533-56-4",
    "RAD1901",
    "RAD-1901",
    "ORSERDU",
    "ER-306323",
    "elacestrantum",
    "FM6A2627A8",
    "DTXSID901045846",
    "(2R)-2-(2-(Ethyl-((4-(2-(ethylamino)ethyl)phenyl)methyl)amino)-4-methoxy-phenyl)tetralin-6-ol",
    "(6R)-6-{2-[ethyl({4-[2-(ethylamino)ethyl]phenyl}methyl)amino]-4-methoxyphenyl}-5,6,7,8-tetrahydronaphthalen-2-ol",
    "2-Naphthalenol, 6-(2-(ethyl((4-(2-(ethylamino)ethyl)phenyl)methyl)amino)-4-methoxyphenyl)-5,6,7,8-tetrahydro-, (6R)-",
    "(2R)-2-[2-[ethyl-[[4-[2-(ethylamino)ethyl]phenyl]methyl]amino]-4-methoxy-phenyl]tetralin-6-ol",
    "(6R)-6-(2-(Ethyl((4-(2-(ethylamino)ethyl)phenyl)methyl)amino)-4-methoxyphenyl)-5,6,7,8-tetrahydronaphthalen-2-ol",
    "RefChem:57007",
    "SERD/SERM RAD1901",
    "DTXCID401527776",
    "Elacestrant [INN]",
    "Elacestrant [USAN]",
    "MFCD30532693",
    "(6R)-6-[2-[ethyl-[[4-[2-(ethylamino)ethyl]phenyl]methyl]amino]-4-methoxyphenyl]-5,6,7,8-tetrahydronaphthalen-2-ol",
    "(R)-6-(2-(Ethyl(4-(2-(ethylamino)ethyl)benzyl)amino)-4-methoxyphenyl)-5,6,7,8-tetrahydronaphthalen-2-ol",
    "(6R)-6-(2-(Ethyl((4-(2- (ethylamino)ethyl)phenyl)methyl)amino)-4-methoxyphenyl)- 5,6,7,8-tetrahydronaphthalen-2-ol",
    "(R)-6-[2-[Ethyl[4-[2-(ethylamino)ethyl]benzyl]amino]-4-methoxyphenyl]-5,6,7,8-tetrahydronaphthalen-2-ol",
    "Elacestrant (USAN/INN)",
    "Elacestrant [USAN:INN]",
    "ELACESTRANT [WHO-DD]",
    "SCHEMBL229431",
    "UNII-FM6A2627A8",
    "orb1308827",
    "CHEMBL4297509",
    "SCHEMBL29359701",
    "GTPL12339",
    "CHEBI:229213",
    "BDBM349630",
    "C30H38N2O2",
    "GLXC-26208",
    "EX-A5070",
    "RAD 1901",
    "US10208011, Compound RAD-",
    "?RAD-1901",
    "NSC854010",
    "WHO 10247",
    "XH1617",
    "AKOS032946378",
    "CS-6306",
    "DB06374",
    "NSC-854010",
    "AC-37208",
    "DA-63145",
    "ER306323",
    "HY-19822",
    "MS-28398",
    "SY357698",
    "D11671",
    "G15928",
    "Q27278069",
    "(6R)-6-[2-(ethyl{4-[2-(ethylamino)ethyl]benzyl}amino)-4-methoxyphenyl]-5,6,7,8-tetrahydronaphthalen-2-ol",
    "(6R)-6-[2-[ethyl[[4-[2-(ethylamino)ethyl]phenyl]methyl]amino]-4-methoxyphenyl]-5, 6,7,8-tetrahydro-2-Naphthalenol",
    "I0V"
  ],
  "Entrectinib": [
    "Entrectinib",
    "1108743-60-7",
    "Rozlytrek",
    "RXDX-101",
    "NMS-E628",
    "entrectinibum",
    "L5ORF0AN1I",
    "RXDX 101",
    "N-[5-[(3,5-difluorophenyl)methyl]-1H-indazol-3-yl]-4-(4-methylpiperazin-1-yl)-2-(oxan-4-ylamino)benzamide",
    "DTXSID101026450",
    "Benzamide, N-(5-((3,5-difluorophenyl)methyl)-1H-indazol-3-yl)-4-(4-methyl-1-piperazinyl)-2-((tetrahydro-2H-pyran-4-yl)amino)-",
    "N-(5-(3,5-Difluorobenzyl)-1H-indazol-3-yl)-4-(4-methylpiperazin-1yl)-2-(tetrahydro-2H-pyran-4-ylamino)benzamide",
    "N-(5-(3,5-difluorobenzyl)-1H-indazol-3-yl)-4-(4-methyl-1-piperazinyl)-2-(tetrahydro-2H-pyran-4-ylamino)benzamide",
    "N-{5-[(3,5-difluorophenyl)methyl]-1H-indazol-3-yl}-4-(4-methylpiperazin-1-yl)-2-[(oxan-4-yl)amino]benzamide",
    "Benzamide, N-[5-[(3,5-difluorophenyl)methyl]-1H-indazol-3-yl]-4-(4-methyl-1-piperazinyl)-2-[(tetrahydro-2H-pyran-4-yl)amino]-",
    "RXDX101",
    "N-(5-((3,5-Difluorophenyl)methyl)-1H-indazol-3-yl)-4-(4-methylpiperazin-1-yl)-2-((oxan-4-yl)amino)benzamide",
    "N-(5-((3,5-difluorophenyl)methyl)-1H-indazol-3-yl)-4-(4-methylpiperazin-1-yl)-2-(oxan-4-ylamino)benzamide",
    "RefChem:58006",
    "L01XE56",
    "DTXCID101510637",
    "Entrectinib (RXDX-101)",
    "Entrectinib(rxdx-101)",
    "N-(5-(3,5-difluorobenzyl)-1H-indazol-3-yl)-4-(4-methylpiperazin-1-yl)-2-((tetrahydro-2H-pyran-4-yl)amino)benzamide",
    "MFCD28129099",
    "N-[5-[(3,5-Difluorophenyl)methyl]-1H-indazol-3-yl]-4-(4-methyl-1-piperazinyl)-2-[(tetrahydro-2H-pyran-4-yl)amino]benzamide",
    "N-[5-[(3,5-difluorophenyl)methyl]-1H-indazol-3-yl]-4-(4-methylpiperazin-1-yl)-2-(tetrahydropyran-4-ylamino)benzamide",
    "Entrectinib [INN]",
    "UNII-L5ORF0AN1I",
    "Entrectinib [USAN:INN]",
    "C31H34F2N6O2",
    "Rozlytrek (TN)",
    "N-(5-(3,5-difluorobenzyl)-1H-indazol-3-yl)-4-(4-methylpiperazin-1-yl)-2-(tetrahydro-2H-pyran-4-ylamino)benzamide",
    "N-[5-(3,5-difluorobenzyl)-1H-indazol-3-yl]-4-(4-methylpiperazin-1-yl)-2-(tetrahydro-2H-pyran-4-ylamino)benzamide",
    "YMX",
    "Entrectinib, 95%",
    "RG 6268",
    "Entrectinib (Standard)",
    "Kinome_2659",
    "ENTRECTINIB [MI]",
    "ENTRECTINIB [JAN]",
    "Entrectinib; NMS-E628",
    "ENTRECTINIB [USAN]",
    "ENTRECTINIB [WHO-DD]",
    "Entrectinib (RXDX-101)?",
    "Entrectinib (JAN/USAN/INN)",
    "GTPL8290",
    "orb1303916",
    "SCHEMBL3512601",
    "CHEMBL1983268",

In [7]:
out

{'Abemaciclib': ['Abemaciclib',
  '1231929-97-7',
  'LY2835219',
  'Verzenio',
  'LY-2835219',
  'N-(5-((4-ethylpiperazin-1-yl)methyl)pyridin-2-yl)-5-fluoro-4-(4-fluoro-1-isopropyl-2-methyl-1H-benzo[d]imidazol-6-yl)pyrimidin-2-amine',
  'Verzenios',
  '60UAB198HK',
  'N-[5-[(4-ethylpiperazin-1-yl)methyl]pyridin-2-yl]-5-fluoro-4-(7-fluoro-2-methyl-3-propan-2-ylbenzimidazol-5-yl)pyrimidin-2-amine',
  'LY 2835219',
  'LY2835210',
  'LY-2835210',
  '2-Pyrimidinamine, N-(5-((4-ethyl-1-piperazinyl)methyl)-2-pyridinyl)-5-fluoro-4-(4-fluoro-2-methyl-1-(1-methylethyl)-1H-benzimidazol-6-yl)',
  '5-(4-ethylpiperazin-1-ylmethyl)pyridin-2-yl)-(5-fluoro-4-(7-fluoro-3-isopropyl-2-methyl-3H-benzimidazol-5-yl)pyrimidin-2-yl)amine',
  '5-(4-ethylpiperazin-1-ylmethyl)pyridin-2-yl)-(5-fluoro-4-(7-fluoro-3-isopropyl-2-methyl-3H-benzoimidazol-5-yl)pyrimidin-2-yl)amine',
  'abemaciclibum',
  'N-(5-((4-ethylpiperazin-1-yl)methyl)pyridin-2-yl)-5-fluoro-4-(4-fluoro-1-isopropyl-2-methyl-1H-benzo(d)imidazol-6-yl)pyrimidin-2-amine',
  'N-(5-((4-ethylpiperazin-1-yl)methyl)pyridin-2-yl)-5-fluoro-4-(4-fluoro-2-methyl-1-(propan-2-yl)-1H-1,3-benzodiazol-6-yl)pyrimidin-2-amine',
  'N-(5-((4-ethylpiperazin-1-yl)methyl)pyridin-2-yl)-5-fluoro-4-(7-fluoro-2-methyl-3-propan-2-ylbenzimidazol-5-yl)pyrimidin-2-amine',
  'N-{5-[(4-ethylpiperazin-1-yl)methyl]pyridin-2-yl}-5-fluoro-4-[4-fluoro-2-methyl-1-(propan-2-yl)-1H-1,3-benzodiazol-6-yl]pyrimidin-2-amine',
  'RefChem:58097',
  'L01XE50',
  'LY2385219',
  '806-670-8',
  'LY2835219 free base',
  'UNII-60UAB198HK',
  'MFCD22665744',
  '2-Pyrimidinamine, N-[5-[(4-ethyl-1-piperazinyl)methyl]-2-pyridinyl]-5-fluoro-4-[4-fluoro-2-methyl-1-(1-methylethyl)-1H-benzimidazol-6-yl]-',
  'C27H32F2N8',
  'HY-16297A',
  's5716',
  'CS-1230',
  'N-{5-[(4-ethylpiperazin-1-yl)methyl]pyridin-2-yl}-5-fluoro-4-(7-fluoro-3-isopropyl-2-methyl-1,3-benzodiazol-5-yl)pyrimidin-2-amine',
  'N-{5-[(4-Ethylpiperazin-1-yl)methyl]pyridin-2-yl}-5-fluoro-4-[4-fluoro-2-methyl-1-(propan-2-yl)-1H-benzimidazol-6-yl]pyrimidin-2-amine',
  'Abemaciclib [USAN:INN]',
  'LY2835219 (free base)',
  'rimidin-2-amine',
  'Verzenio (TN)',
  '6ZV',
  'N-{5-[(4-ethylpiperazin-1-yl)methyl]pyridin-2-yl}-5-fluoro-4-[4-fluoro-2-methyl-1-(propan-2-yl)-1H-benzimidazol-6-yl]py rimidin-2-amine',
  'Abemaciclib (Standard)',
  'ABEMACICLIB [MI]',
  'ABEMACICLIB [INN]',
  'ABEMACICLIB [JAN]',
  'ABEMACICLIB [USAN]',
  'ABEMACICLIB [WHO-DD]',
  'Abemaciclib (JAN/USAN/INN)',
  'GTPL7382',
  'orb1305567',
  'SCHEMBL2487229',
  'CHEMBL3301610',
  'SCHEMBL29356350',
  'SCHEMBL29423472',
  'SCHEMBL29591527',
  'ABEMACICLIB [ORANGE BOOK]',
  'DTXSID20673119',
  'EX-A521',
  'LY 2835219 (free base)',
  'CHEBI:233362',
  'UZWDCWONPYILKI-UHFFFAOYSA-N',
  'HMS3673I05',
  'HMS5085C17',
  'HY-16297AR',
  'EX-A1588',
  'BDBM50110183',
  'NSC768073',
  'NSC783671',
  '1231929-97-7, Verzenio,',
  'AKOS025404907',
  'LY2835219 free base (Abemaciclib)',
  'CCG-269750',
  'DB12001',
  'NSC-768073',
  'NSC-783671',
  'SB16476',
  'LY2835219 free base (Abemaciclib)?',
  'NCGC00351599-02',
  'NCGC00351599-06',
  'AC-30666',
  'AS-10230',
  'BP-43621',
  'DA-33422',
  'FE103812',
  'LY2835219 Ms salt, Abemaciclib Ms salt',
  'LY 2835210',
  'NS00072970',
  'D10688',
  'EN300-7406007',
  'F979456',
  'BRD-K33622447-066-01-9',
  'Q23901483',
  '[5-(4-ethyl-piperazin-1-ylmethyl)-pyridin-2-yl]-[5-fluoro-4-(7-fluoro-3-isopropyl-2-methyl-3H-benzoimidazol-5-yl)-pyrimidin-2-yl]-amine',
  'Ethyl-1-piperazinyl)methyl]-2-pyridinyl]-5-fluoro-4-[4-fluoro-2-methyl-1-(1-methylethyl)-1H-benzimidazol-6-yl]-2-pyrimidinamine',
  'N-[5-[(4-Ethyl-1-piperazinyl)methyl]-2-pyridinyl]-5-fluoro-4-[4-fluoro-2-methyl-1-(1-methylethyl)-1H-benzimidazol-6-yl]-2-pyrimidinamine',
  'N-[5-[(4-ethylpiperazin-1-yl)methyl]-2-pyridyl]-5-fluoro-4-(7-fluoro-3-isopropyl-2-methyl-benzimidazol-5-yl)pyrimidin-2-amine',
  'N-{5-[(4-ethylpiperazin-1-yl)methyl]pyridin-2-yl}-5-fluoro-4-[4-fluoro-2-methyl-1-(propan-2-yl)-1H-benzimidazol-6-yl]py'],
 'Alpelisib': ['Alpelisib',
  'alpelisib',
  '1217486-61-7',
  'BYL-719',
  'BYL719',
  'Piqray',
  'NVP-BYL719',
  'Vijoice',
  'BYL 719',
  '08W5N2C97Q',
  '1,2-PYRROLIDINEDICARBOXAMIDE, N1-[4-METHYL-5-[2-(2,2,2-TRIFLUORO-1,1-DIMETHYLETHYL)-4-PYRIDINYL]-2-THIAZOLYL]-, (2S)-',
  '(2S)-1-N-[4-methyl-5-[2-(1,1,1-trifluoro-2-methylpropan-2-yl)pyridin-4-yl]-1,3-thiazol-2-yl]pyrrolidine-1,2-dicarboxamide',
  '1,2-Pyrrolidinedicarboxamide, N1-(4-methyl-5-(2-(2,2,2-trifluoro-1,1-dimethylethyl)-4-pyridinyl)-2-thiazolyl)-, (2S)-',
  'DTXSID70153355',
  '(S)-Pyrrolidine-1,2-dicarboxylic acid 2-amide 1-(4-methyl-5-(2-(2,2,2-trifluoro-1,1-dimethylethyl)-pyridin-4-yl)thiazol-2-yl)amide',
  'alpelisibum',
  '(2S)-1-N-(4-methyl-5-(2-(1,1,1-trifluoro-2-methylpropan-2-yl)pyridin-4-yl)-1,3-thiazol-2-yl)pyrrolidine-1,2-dicarboxamide',
  '(2S)-1-N-{4-methyl-5-[2-(1,1,1-trifluoro-2-methylpropan-2-yl)pyridin-4-yl]-1,3-thiazol-2-yl}pyrrolidine-1,2-dicarboxamide',
  'RefChem:57062',
  'DTXCID7075846',
  'L01XX65',
  'Phosphoinositide 3-kinase Inhibitor BYL719',
  'Alpelisib (BYL719)',
  '(S)-N1-(4-Methyl-5-(2-(1,1,1-trifluoro-2-methylpropan-2-yl)pyridin-4-yl)thiazol-2-yl)pyrrolidine-1,2-dicarboxamide',
  'MFCD22417085',
  'UNII-08W5N2C97Q',
  'Alpelisib [USAN:INN]',
  'CHEMBL2396661',
  'Alpelisib [INN]',
  '(2s)-N~1~-{4-Methyl-5-[2-(1,1,1-Trifluoro-2-Methylpropan-2-Yl)pyridin-4-Yl]-1,3-Thiazol-2-Yl}pyrrolidine-1,2-Dicarboxamide',
  '(S)-N1-(4-methyl-5-(2-(1,1,1-trifluoro-2-methylpropan-2-yl)pyridin-4-yl)thiazol-2-yl)pyrrolidine-1,2-dicarboxamide.',
  'C19H22F3N5O2S',
  '4jps',
  '1LT',
  'Alpelisib [USAN]',
  'Vijoice (TN)',
  'Piqray (TN)',
  'ALPELISIB [JAN]',
  'ALPELISIB [MI]',
  'ALPELISIB [WHO-DD]',
  'Alpelisib (JAN/USAN/INN)',
  'GTPL7955',
  'orb1307105',
  'SCHEMBL1911869',
  'ALPELISIB [ORANGE BOOK]',
  'SCHEMBL29358059',
  'CHEBI:93752',
  'EX-A405',
  'STUWGJZDJHPWGZ-LBPRGKRZSA-N',
  'BDBM738244',
  'BYL 719; BYL719',
  'BDBM50436459',
  'NSC765974',
  'NSC800065',
  's2814',
  'AKOS022186315',
  'CCG-269139',
  'CS-0663',
  'DB12015',
  'FP71607',
  'NSC-765974',
  'NSC-800065',
  'SDCCGSBI-0654479.P001',
  'US20250145589, Example Alpelisib',
  'NCGC00346717-03',
  'NCGC00346717-06',
  'NCGC00346717-12',
  '(2S)-N1-[4-Methyl-5-[2-(2,2,2-trifluoro-1,1-dimethylethyl)-4-pyridinyl]-2-thiazolyl]-1,2-pyrrolidine',
  'AC-37083',
  'AS-16349',
  'HY-15244',
  'NS00072895',
  'SW220128-1',
  'cas:1217486-61-7;BYL-719',
  'D11011',
  'EN300-23810842',
  'BRD-K54997624-001-06-0',
  'Q27074391',
  '(2S)-N1-[4-methyl-5-[2-(2,2,2-trifluoro-1,1-dimethyl-ethyl)-4-pyridyl]thiazol-2-yl]pyrrolidine-1,2-dicarboxamide',
  '(2S)-N1-{4-Methyl-5-[1-(1,1,1-trifluoro-2-methylpropan-2-yl)pyridin-4-yl]-1,3-thiazol-2-yl}pyrrolidine-1,2-dicarboxamide',
  '(2S)-N1-{4-METHYL-5-[2-(1,1,1-TRIFLUORO-2-METHYLPROPAN-2-YL)PYRIDIN-4-YL]-1,3-THIAZOL-2-YL}PYRROLIDINE-1,2-DICARBOXAMIDE',
  '(S)-Pyrrolidine-1,2-dicarboxylic acid 2-amide 1-[4-methyl-5-[2-(2,2,2-trifluoro-1,1-dimethylethyl)-pyridin-4-yl]thiazol-2-yl]amide;A  lpelisib'],
 'Anastrozole': ['Anastrozole',
  'anastrozole',
  '120511-73-1',
  'Arimidex',
  'anastrazole',
  'Anastrozol',
  'ZD1033',
  'ICI D1033',
  'ZD-1033',
  'ICI-D1033',
  'ZD 1033',
  'DTXSID9022607',
  '2Z07MYW1AZ',
  'NSC-719344',
  'NSC-759855',
  'CHEBI:2704',
  "alpha,alpha,alpha',alpha'-Tetramethyl-5-(1H-1,2,4-triazol-1-ylmethyl)-m-benzenediacetonitrile",
  'Rvg-106400',
  'NSC719344',
  'DTXCID202607',
  "1,3-Benzenediacetonitrile, alpha,alpha,alpha',alpha'-tetramethyl-5-(1H-1,2,4-triazol-1-ylmethyl)-",
  'Zeneca ZD 1033',
  '2-[3-(1-cyano-1-methylethyl)-5-(1H-1,2,4-triazol-1-ylmethyl)phenyl]-2-methylpropanenitrile',
  'anastrozolum',
  'Nastrosa',
  'Anastrozole Tablets',
  '2-(3-(1-Cyano-1-methylethyl)-5-(1H-1,2,4-triazol-1-ylmethyl)phenyl)-2-methylpropanenitrile',
  "2,2'-(5-(1H-1,2,4-triazol-1-ylmethyl)-1,3-phenylene)bis(2-methylpropionitrile)",
  'RefChem:54202',
  'L02BG03',
  "2,2'-(5-(1H-1,2,4-Triazol-1-ylmethyl)-1,3-phenylene)di(2-methylpropionitrile)",
  "Alpha,alpha,alpha', alpha'-tetramethyl-5-(1H-1,2,4-triazol-1-ylmethyl)-1,3-benzenediacetonitrile",
  "2,2'-(5-((1H-1,2,4-triazol-1-yl)methyl)-1,3-phenylene)bis(2-methylpropanenitrile)",
  'MFCD00866298',
  'CHEMBL1399',
  "2,2'-[5-(1H-1,2,4-triazol-1-ylmethyl)benzene-1,3-diyl]bis(2-methylpropanenitrile)",
  'NCGC00164619-01',
  'Asiolex',
  'alpha1,alpha1,alpha3,alpha3-Tetramethyl-5-(1H-1,2,4-triazol-1-ylmethyl)-1,3-benzenediacetonitrile',
  'Arimidex (TN)',
  'SMR000466301',
  'CAS-120511-73-1',
  'HSDB 7462',
  'ICI-D 1033',
  'SR-01000759390',
  'UNII-2Z07MYW1AZ',
  'Anastrozole?',
  '2-[3-(2-cyanopropan-2-yl)-5-(1,2,4-triazol-1-ylmethyl)phenyl]-2-methylpropanenitrile',
  'CCRIS 9352',
  'Anastrozole [USAN:USP:INN:BAN]',
  "Anastrozole; 2,2'-[5-(1H-1,2,4-Triazol-1-ylmethyl)benzene-1,3-diyl]bis(2-methylpropanenitrile)",
  'Anastrozole (Standard)',
  'Arimidex (AstraZeneca)',
  'ANASTROZOLE [MI]',
  'ANASTROZOLE [INN]',
  'ANASTROZOLE [JAN]',
  'ANASTROZOLE [HSDB]',
  'ANASTROZOLE [USAN]',
  'SCHEMBL9726',
  'ANASTROZOLE [MART.]',
  'ANASTROZOLE [USP-RS]',
  'ANASTROZOLE [WHO-DD]',
  'MLS000759396',
  'MLS001424217',
  'MLS006011961',
  'GTPL5137',
  'orb1310655',
  'Anastrozole (JP18/USP/INN)',
  'Anastrozole - Bio-X trade mark',
  'BDBM10015',
  'ANASTROZOLE [ORANGE BOOK]',
  'ANASTROZOLE [EP MONOGRAPH]',
  'ANASTROZOLE [USP IMPURITY]',
  'GLXC-03925',
  'HMS2052M11',
  'HMS2089N10',
  'HMS2235M06',
  'HMS3369K05',
  'HMS3394M11',
  'HMS3654I18',
  'HMS3715B05',
  'HMS3742O21',
  'HMS3866K03',
  'HMS5079E13',
  'Pharmakon1600-01502278',
  'ANASTROZOLE [USP MONOGRAPH]',
  'ALBB-037397',
  'VEA51232',
  'Tox21_112238',
  'Tox21_303568',
  'HY-14274R',
  'NSC759855',
  's1188',
  'STL451008',
  'AKOS015894980',
  'tetramethyl-5-(1h-1,2,4-triazol-1ylmethyl) 1,3-benzenediacetionitrile',
  'Tox21_112238_1',
  'AC-4234',
  'CCG-101109',
  'CS-0716',
  'DB01217',
  'FT10600',
  'KS-5052',
  'NC00359',
  'NSC 719344',
  'NSC 759855',
  'SB17304',
  "2,2'-[5-(1H-1,2,4-triazol-1-ylmethyl)-1,3-phenylene]bis(2-methylpropanenitrile)",
  '2-[3-(1-cyano-1-methyl-ethyl)-5-(1,2,4-triazol-1-ylmethyl)phenyl]-2-methyl-propanenitrile',
  '3-Phenylene]bis(2-methyl-propiononitrile',
  'NCGC00164619-02',
  'NCGC00164619-04',
  'NCGC00257356-01',
  'BT164176',
  'HY-14274',
  'A2370',
  'NS00005588',
  'SW197739-4',
  '11A731',
  'C08159',
  'D00960',
  'EN300-118709',
  'AB00639929-06',
  'AB00639929-08',
  'AB00639929-09',
  'AB00639929-10',
  'AB00639929_11',
  'AB00639929_13',
  'A804526',
  'Q419143',
  '2;2"-[5-(1H-1;2;4-Triazol-1-ylmethyl)-1',
  'SR-01000759390-4',
  'SR-01000759390-5',
  'BRD-K52172416-001-10-6',
  'BRD-K52172416-001-11-4',
  'Z1515385077',
  "1,.alpha.,alpha.,alpha.',.alpha.'-tetramethyl-5-(1H-1,2,4-triazol-1-ylmethyl)-",
  "2,2'-[5-(1H-1,2,4-triazol-1-yl-methyl)-1,3-phenylene]-di(2-methyl propionitrile)",
  "2,2'-[5-(1H-1,2,4-triazol-1-ylmethyl)-1,3-phenylene]di(2-methylpropiononitrile)",
  "2,2'-[5-(1H-1,2,4-triazole-1-yl-methyl)-1,3-phenylene]di(2-methyl propionitrile)",
  '2-[3-(2-cyano-2-propyl)-5-(1,2,4-triazol-1-ylmethyl)phenyl]-2-methylpropiononitrile',
  '2-[3-(2-cyanopropan-2-yl)-5-(1,2,4-triazol-1-ylmethyl)phenyl]-2-methyl-propanenitrile',
  "a,a,a',a'-Tetramethyl-5-(1H-1,2,4-triazol-1-ylmethyl)-1,3-benzenediacetonitrile",
  ".alpha.,.alpha.',.alpha.'-tetramethyl-5(1H-1,2,4-triazol-1-ylmethyl)-m-benzenediacetonitrile",
  ".ALPHA.,.ALPHA.,.ALPHA.',.ALPHA.'-TETRAMETHYL-5-(1H-1,2,4-TRIAZOL-1-YLMETHYL)-M-BENZENEDIACETONITRILE",
  "1,3-BENZENEDIACETONITRILE,.ALPHA.,.ALPHA.,.ALPHA.',.ALPHA.'-TETRAMETHYL-5-(1H-1,2,4-TRIAZOL-1-YLMETHYL)-",
  '2-[3-(1-cyano-1-methylethyl)-5-[(1H-1,2,4-triazol-1-yl)methyl]phenyl]-2-methylpropanenitrile',
  "alpha,alpha,alpha',alpha'-Tetramethyl-5-(1H-1,2,4-triazol-1-ylmethyl)-1,3-benzenediacetonitrile"],
 'Aromatase inhibitor': ['Aromatase inhibitor'],
 'Atezolizumab': ['Atezolizumab'],
 'Bevacizumab': ['Bevacizumab'],
 'Capivasertib': ['Capivasertib',
  'capivasertib',
  '1143532-39-1',
  'AZD5363',
  'AZD-5363',
  'AZD 5363',
  'Truqap',
  '4-Amino-N-[(1s)-1-(4-Chlorophenyl)-3-Hydroxypropyl]-1-(7h-Pyrrolo[2,3-D]pyrimidin-4-Yl)piperidine-4-Carboxamide',
  'WFR23M21IE',
  'DTXSID40150710',
  '4-amino-N-(1-(4-chlorophenyl)-3-hydroxypropyl)-1-(7H-pyrrolo(2,3-d)pyrimidin-4-yl)piperidine-4-carboxamide',
  'capivasertibum',
  '4-Amino-N-((1S)-1-(4-chlorophenyl)-3-hydroxypropyl)-1-(7H-pyrrolo(2,3-d)pyrimidin-4-yl)piperidine-4-carboxamide',
  'RefChem:573743',
  'DTXCID4073201',
  '(S)-4-AMINO-N-(1-(4-CHLOROPHENYL)-3-HYDROXYPROPYL)-1-(7H-PYRROLO[2,3-D]PYRIMIDIN-4-YL)PIPERIDINE-4-CARBOXAMIDE',
  'MFCD22628785',
  '4-Piperidinecarboxamide, 4-amino-N-[(1S)-1-(4-chlorophenyl)-3-hydroxypropyl]-1-(7H-pyrrolo[2,3-d]pyrimidin-4-yl)-',
  '4-amino-N-[(1S)-1-(4-chlorophenyl)-3-hydroxy-propyl]-1-(7H-pyrrolo[2,3-d]pyrimidin-4-yl)piperidine-4-carboxamide',
  'UNII-WFR23M21IE',
  'CHEMBL2325741',
  'C21H25ClN6O2',
  'cc-638',
  'Capivasertib?',
  '(S)-4-Amino-N-[1-(4-chlorophenyl)-3-hydroxypropyl]-1-(7H-pyrrolo[2,3-d]pyrimidin-4-yl)piperidine-4-carboxamide',
  '4-PIPERIDINECARBOXAMIDE, 4-AMINO-N-((1S)-1-(4-CHLOROPHENYL)-3-HYDROXYPROPYL)-1-(7H-PYRROLO(2,3-D)PYRIMIDIN-4-YL)-',
  'Truqap (TN)',
  'Capivasertib (JAN/USAN)',
  'CAPIVASERTIB [INN]',
  'CAPIVASERTIB [JAN]',
  'CAPIVASERTIB [USAN]',
  'Capivasertib (AZD5363)',
  '4-Amino-N-[(1S)-1-(4-chlorophenyl)-3-hydroxypropyl]-1-(7H-pyrrolo[2,3-d]pyrimidin-4-yl)-4-piperidinecarboxamide',
  'MLS006011179',
  'CAPIVASERTIB [WHO-DD]',
  'SCHEMBL390243',
  'GTPL7709',
  'orb1307109',
  'SCHEMBL29357463',
  'SCHEMBL29557103',
  'AZC5363',
  'EX-A285',
  'CHEBI:229222',
  'JDUBGYFRJFOXQC-KRWDZBQOSA-N',
  'US10654855, Example 9',
  'BDBM443385',
  'AZD5363?',
  'NSC764039',
  'NSC782347',
  'NSC799347',
  's8019',
  'AKOS027323693',
  'CCG-268989',
  'CS-1284',
  'DB12218',
  'FA29493',
  'NSC-764039',
  'NSC-782347',
  'NSC-799347',
  'NCGC00345795-01',
  'NCGC00345795-03',
  'NCGC00345795-04',
  'NCGC00345795-08',
  'AC-32685',
  'BP-43630',
  'HY-15431',
  'SMR004702948',
  'SY018928',
  'DB-290280',
  'NS00072563',
  'SW220158-1',
  'D11371',
  'BRD-K99023089-001-03-7',
  'Q27074756',
  '0XZ',
  '4-AMINO-N-((1S)-1-(4-CHLOROPHENYL)-3-HYDROXYPROPYL)-1- (1H-PYRROLO(2,3-D)PYRIMIDIN-4-YL)PIPERIDINE-4-CARBOXAMIDE',
  'ALTERNATIVE ROUTE 1: (S)-4-AMINO-N-(1-(4-CHLOROPHENYL)-3-HYDROXYPROPYL)-1-(7H-PYRROLO[2,3-D]PYRIMIDIN-4-YL)PIPERIDINE-4-CARBOXAMIDE'],
 'Dostarlimab': ['Dostarlimab'],
 'Elacestrant': ['Elacestrant',
  '722533-56-4',
  'RAD1901',
  'RAD-1901',
  'ORSERDU',
  'ER-306323',
  'elacestrantum',
  'FM6A2627A8',
  'DTXSID901045846',
  '(2R)-2-(2-(Ethyl-((4-(2-(ethylamino)ethyl)phenyl)methyl)amino)-4-methoxy-phenyl)tetralin-6-ol',
  '(6R)-6-{2-[ethyl({4-[2-(ethylamino)ethyl]phenyl}methyl)amino]-4-methoxyphenyl}-5,6,7,8-tetrahydronaphthalen-2-ol',
  '2-Naphthalenol, 6-(2-(ethyl((4-(2-(ethylamino)ethyl)phenyl)methyl)amino)-4-methoxyphenyl)-5,6,7,8-tetrahydro-, (6R)-',
  '(2R)-2-[2-[ethyl-[[4-[2-(ethylamino)ethyl]phenyl]methyl]amino]-4-methoxy-phenyl]tetralin-6-ol',
  '(6R)-6-(2-(Ethyl((4-(2-(ethylamino)ethyl)phenyl)methyl)amino)-4-methoxyphenyl)-5,6,7,8-tetrahydronaphthalen-2-ol',
  'RefChem:57007',
  'SERD/SERM RAD1901',
  'DTXCID401527776',
  'Elacestrant [INN]',
  'Elacestrant [USAN]',
  'MFCD30532693',
  '(6R)-6-[2-[ethyl-[[4-[2-(ethylamino)ethyl]phenyl]methyl]amino]-4-methoxyphenyl]-5,6,7,8-tetrahydronaphthalen-2-ol',
  '(R)-6-(2-(Ethyl(4-(2-(ethylamino)ethyl)benzyl)amino)-4-methoxyphenyl)-5,6,7,8-tetrahydronaphthalen-2-ol',
  '(6R)-6-(2-(Ethyl((4-(2- (ethylamino)ethyl)phenyl)methyl)amino)-4-methoxyphenyl)- 5,6,7,8-tetrahydronaphthalen-2-ol',
  '(R)-6-[2-[Ethyl[4-[2-(ethylamino)ethyl]benzyl]amino]-4-methoxyphenyl]-5,6,7,8-tetrahydronaphthalen-2-ol',
  'Elacestrant (USAN/INN)',
  'Elacestrant [USAN:INN]',
  'ELACESTRANT [WHO-DD]',
  'SCHEMBL229431',
  'UNII-FM6A2627A8',
  'orb1308827',
  'CHEMBL4297509',
  'SCHEMBL29359701',
  'GTPL12339',
  'CHEBI:229213',
  'BDBM349630',
  'C30H38N2O2',
  'GLXC-26208',
  'EX-A5070',
  'RAD 1901',
  'US10208011, Compound RAD-',
  '?RAD-1901',
  'NSC854010',
  'WHO 10247',
  'XH1617',
  'AKOS032946378',
  'CS-6306',
  'DB06374',
  'NSC-854010',
  'AC-37208',
  'DA-63145',
  'ER306323',
  'HY-19822',
  'MS-28398',
  'SY357698',
  'D11671',
  'G15928',
  'Q27278069',
  '(6R)-6-[2-(ethyl{4-[2-(ethylamino)ethyl]benzyl}amino)-4-methoxyphenyl]-5,6,7,8-tetrahydronaphthalen-2-ol',
  '(6R)-6-[2-[ethyl[[4-[2-(ethylamino)ethyl]phenyl]methyl]amino]-4-methoxyphenyl]-5, 6,7,8-tetrahydro-2-Naphthalenol',
  'I0V'],
 'Entrectinib': ['Entrectinib',
  '1108743-60-7',
  'Rozlytrek',
  'RXDX-101',
  'NMS-E628',
  'entrectinibum',
  'L5ORF0AN1I',
  'RXDX 101',
  'N-[5-[(3,5-difluorophenyl)methyl]-1H-indazol-3-yl]-4-(4-methylpiperazin-1-yl)-2-(oxan-4-ylamino)benzamide',
  'DTXSID101026450',
  'Benzamide, N-(5-((3,5-difluorophenyl)methyl)-1H-indazol-3-yl)-4-(4-methyl-1-piperazinyl)-2-((tetrahydro-2H-pyran-4-yl)amino)-',
  'N-(5-(3,5-Difluorobenzyl)-1H-indazol-3-yl)-4-(4-methylpiperazin-1yl)-2-(tetrahydro-2H-pyran-4-ylamino)benzamide',
  'N-(5-(3,5-difluorobenzyl)-1H-indazol-3-yl)-4-(4-methyl-1-piperazinyl)-2-(tetrahydro-2H-pyran-4-ylamino)benzamide',
  'N-{5-[(3,5-difluorophenyl)methyl]-1H-indazol-3-yl}-4-(4-methylpiperazin-1-yl)-2-[(oxan-4-yl)amino]benzamide',
  'Benzamide, N-[5-[(3,5-difluorophenyl)methyl]-1H-indazol-3-yl]-4-(4-methyl-1-piperazinyl)-2-[(tetrahydro-2H-pyran-4-yl)amino]-',
  'RXDX101',
  'N-(5-((3,5-Difluorophenyl)methyl)-1H-indazol-3-yl)-4-(4-methylpiperazin-1-yl)-2-((oxan-4-yl)amino)benzamide',
  'N-(5-((3,5-difluorophenyl)methyl)-1H-indazol-3-yl)-4-(4-methylpiperazin-1-yl)-2-(oxan-4-ylamino)benzamide',
  'RefChem:58006',
  'L01XE56',
  'DTXCID101510637',
  'Entrectinib (RXDX-101)',
  'Entrectinib(rxdx-101)',
  'N-(5-(3,5-difluorobenzyl)-1H-indazol-3-yl)-4-(4-methylpiperazin-1-yl)-2-((tetrahydro-2H-pyran-4-yl)amino)benzamide',
  'MFCD28129099',
  'N-[5-[(3,5-Difluorophenyl)methyl]-1H-indazol-3-yl]-4-(4-methyl-1-piperazinyl)-2-[(tetrahydro-2H-pyran-4-yl)amino]benzamide',
  'N-[5-[(3,5-difluorophenyl)methyl]-1H-indazol-3-yl]-4-(4-methylpiperazin-1-yl)-2-(tetrahydropyran-4-ylamino)benzamide',
  'Entrectinib [INN]',
  'UNII-L5ORF0AN1I',
  'Entrectinib [USAN:INN]',
  'C31H34F2N6O2',
  'Rozlytrek (TN)',
  'N-(5-(3,5-difluorobenzyl)-1H-indazol-3-yl)-4-(4-methylpiperazin-1-yl)-2-(tetrahydro-2H-pyran-4-ylamino)benzamide',
  'N-[5-(3,5-difluorobenzyl)-1H-indazol-3-yl]-4-(4-methylpiperazin-1-yl)-2-(tetrahydro-2H-pyran-4-ylamino)benzamide',
  'YMX',
  'Entrectinib, 95%',
  'RG 6268',
  'Entrectinib (Standard)',
  'Kinome_2659',
  'ENTRECTINIB [MI]',
  'ENTRECTINIB [JAN]',
  'Entrectinib; NMS-E628',
  'ENTRECTINIB [USAN]',
  'ENTRECTINIB [WHO-DD]',
  'Entrectinib (RXDX-101)?',
  'Entrectinib (JAN/USAN/INN)',
  'GTPL8290',
  'orb1303916',
  'SCHEMBL3512601',
  'CHEMBL1983268',
  'SCHEMBL29358922',
  'SCHEMBL29394152',
  'NMS-E 628',
  'ENTRECTINIB [ORANGE BOOK]',
  'CHEBI:195558',
  'HAYYBYPASCDWEQ-UHFFFAOYSA-N',
  'NMS-E628;RXDX-101',
  'HMS3886H21',
  'HMS5086A05',
  'EX-A2261',
  'HY-12678R',
  'NSC774769',
  'NSC800095',
  'RG6268',
  's7998',
  'AKOS030632786',
  'CCG-270048',
  'DB11986',
  'NSC-774769',
  'NSC-800095',
  'RG-6268',
  'SB17194',
  'NCGC00484067-01',
  'NCGC00484067-02',
  'NCGC00484067-03',
  'AC-31286',
  'AS-75092',
  'BP-43651',
  'DA-47850',
  'HY-12678',
  'NS00072566',
  'D10926',
  'EN300-7376549',
  'BRD-K39009484-001-01-4',
  'Q25323953',
  'N-[5-(3,5-Difluoro-benzyl)-1H-indazol-3-yl]-4-(4-methyl-piperazin-1-yl)-2-(tetrahydro-pyran-4-ylamino)-benzamide',
  'N-[5-[[3,5-bis(fluoranyl)phenyl]methyl]-1H-indazol-3-yl]-4-(4-methylpiperazin-1-yl)-2-(oxan-4-ylamino)benzamide',
  'N-{5-[(3,5-difluorophenyl)methyl]-3H-indazol-3-ylidene}-4-(4-methylpiperazin-1-yl)-2-[(oxan-4-yl)amino]benzamide'],
 'Everolimus': ['Everolimus',
  'Afinitor',
  'Certican',
  'Zortress',
  'RAD001',
  '159351-69-6',
  'SDZ-RAD',
  '42-O-(2-Hydroxyethyl)rapamycin',

In [8]:
# your dictionary
drug_targets = idg

# example synonyms JSON (replace with your actual JSON)
synonym_json = out

# function to match synonyms to dictionary keys (case-insensitive)
def match_synonyms_to_dict(synonym_json, drug_dict):
    results = {}

    # create lowercase mapping for dictionary keys
    lower_dict_keys = {k.lower(): k for k in drug_dict.keys()}

    for drug, synonyms in synonym_json.items():
        matches = []
        for syn in synonyms:
            syn_lower = syn.lower()
            if syn_lower in lower_dict_keys:   # direct match 
                matches.append(lower_dict_keys[syn_lower])
            else:
                # fuzzy: check if synonym closely matches a drug name
                for dk_lower, original in lower_dict_keys.items():
                    if syn_lower == dk_lower:
                        matches.append(original)

        results[drug] = matches if matches else "No match found"

    return results


# run the function
output = match_synonyms_to_dict(synonym_json, drug_targets)

print(output)

{'Abemaciclib': ['Abemaciclib'], 'Alpelisib': 'No match found', 'Anastrozole': 'No match found', 'Aromatase inhibitor': 'No match found', 'Atezolizumab': 'No match found', 'Bevacizumab': 'No match found', 'Capivasertib': 'No match found', 'Dostarlimab': 'No match found', 'Elacestrant': 'No match found', 'Entrectinib': ['Entrectinib'], 'Everolimus': 'No match found', 'Exemestane': 'No match found', 'Fulvestrant': ['Fulvestrant'], 'Lapatinib': ['Lapatinib'], 'Larotrectinib': 'No match found', 'Letrozole': 'No match found', 'Margetuximab': 'No match found', 'Neratinib': ['Neratinib'], 'Olaparib': ['Olaparib'], 'Palbociclib': ['Palbociclib'], 'Pembrolizumab': 'No match found', 'Pertuzumab': 'No match found', 'Ribociclib': 'No match found', 'Sacituzumab govitecan': 'No match found', 'Selpercatinib': 'No match found', 'Talazoparib': 'No match found', 'Tamoxifen': ['Tamoxifen', 'Tamoxifen'], 'Toremifene': 'No match found', 'Trastuzumab': 'No match found', 'Trastuzumab deruxtecan': 'No match found', 'Trastuzumab emtansine': ['Trastuzumab Emtansine'], 'Tucatinib': 'No match found'}

In [9]:
total_keys = len(output)

# Count "No match found"
no_match = sum(1 for v in output.values() if v == "No match found")

# Count matches
matches = total_keys - no_match

print("Total keys:", total_keys)
print("No match found:", no_match)
print("With matches:", matches)

Total keys: 32
No match found: 23
With matches: 9

In [2]:
import os
import json
import inspect
import pandas as pd
from tqdm import tqdm
from singscore.singscore import score, permutate, empiricalpval

# -----------------------------
# 1) Load expression (UK65)
# -----------------------------
uk65 = pd.read_csv(
    "singscore_new_code/UK65_clean_gene_log_tpm.txt",
    header="infer",
    sep="\t"
)
uk65 = uk65.set_index("GeneName")  # rows = genes, cols = samples

# -----------------------------
# 2) Load the "master" geneset JSON
# -----------------------------
geneset_json_path = "singscore_new_code/results/Deep_search_results/master_drug_pathways_genesets.json"  # <-- change
all_drugs = json.load(open(geneset_json_path, "r", encoding="utf-8"))

# Output config
N_PERM = 10000
out_path = "singscore_new_code/results/Deep_search_results/singscore_results_all_drugs.json"  # <-- change

# -----------------------------
# 3) Robust permutation call (handles different permutate() signatures)
# -----------------------------
def run_permutations(sample_df, n_up, n_down=False, n_perm=10000):
    """
    Calls permutate() with whatever signature your singscore version exposes.
    Tries common parameter names for #permutations.
    """
    sig = inspect.signature(permutate)
    kwargs = {}

    # Some versions use: n_perm / n_permutations / permutations / n
    for cand in ["n_perm", "n_permutations", "permutations", "n"]:
        if cand in sig.parameters:
            kwargs[cand] = n_perm
            break

    # n_up / n_down are present in most versions
    if "n_up" in sig.parameters:
        kwargs["n_up"] = n_up
    if "n_down" in sig.parameters:
        kwargs["n_down"] = n_down

    # Some versions just accept positional (sample, n_up, n_down)
    try:
        return permutate(sample_df, **kwargs)
    except TypeError:
        return permutate(sample_df, n_up=n_up, n_down=n_down)

# -----------------------------
# 4) Compute singscore + empirical p-value for EVERY pathway in JSON
#     - Keeps SAME JSON nesting keys
#     - Each pathway becomes:
#         {
#           "total_score": <float or null>,
#           "empirical_p_value": <float or null>
#         }
# -----------------------------
final_result = {}

for drug_name, drug_block in tqdm(all_drugs.items(), desc="Drugs"):
    final_result[drug_name] = {}

    # drug_block contains categories like:
    # pathways_sensitive_upregulated, pathway_sensitive_downregulated, pathway_resistant_upregulated, ...
    for category_name, category_block in drug_block.items():
        # Preserve empty dicts as empty dicts
        if not isinstance(category_block, dict) or len(category_block) == 0:
            final_result[drug_name][category_name] = {}
            continue

        final_result[drug_name][category_name] = {}

        for pathway_name, genes in tqdm(category_block.items(),
                                        desc=f"{drug_name} :: {category_name}",
                                        leave=False):
            # genes is a list of symbols
            if not isinstance(genes, list) or len(genes) == 0:
                final_result[drug_name][category_name][pathway_name] = {
                    "total_score": None,
                    "empirical_p_value": None
                }
                continue

            # Filter genes to those present in expression matrix
            up_present = [g for g in genes if g in uk65.index]

            # If nothing overlaps, we can’t compute a meaningful score/p-value
            if len(up_present) == 0:
                final_result[drug_name][category_name][pathway_name] = {
                    "total_score": None,
                    "empirical_p_value": None
                }
                continue

            # Compute singscore (UP only)
            scored = score(
                up_gene=up_present,
                down_gene=False,
                sample=uk65,
                norm_method="theoretical",
                full_data=True
            )
            total_score = float(scored["total_score"].to_list()[0])

            # Permutations + empirical p-value
            permd = run_permutations(uk65, n_up=len(up_present), n_down=False, n_perm=N_PERM)
            pvals = empiricalpval(permutations=permd, score=scored)
            empirical_p_value = float(pvals["empirical p value"].to_list()[0])

            # Store ONLY the 2 entries per pathway (as you requested)
            final_result[drug_name][category_name][pathway_name] = {
                "total_score": total_score,
                "empirical_p_value": empirical_p_value
            }

# -----------------------------
# 5) Save JSON (same nesting keys)
# -----------------------------
os.makedirs(os.path.dirname(out_path), exist_ok=True)
with open(out_path, "w", encoding="utf-8") as f:
    json.dump(final_result, f, indent=2, ensure_ascii=False)

print(f"Saved: {out_path}")

Drugs: 100%|██████████| 32/32 [57:12<00:00, 107.25s/it]

Saved: singscore_new_code/results/Deep_search_results/singscore_results_all_drugs.json

In [ ]:
import os
import json
import re
import inspect
from pathlib import Path
import pandas as pd
from tqdm import tqdm
from singscore.singscore import score, permutate, empiricalpval
# from src.common.constants import DEFAULT_DATA_PATHS


def run_singscore_all_drugs(sample, geneset=None, out_path=None, n_perm=10000, norm_method="theoretical"):
    """
    Compute singscore total score and empirical p-value for every pathway in a master geneset.

    Parameters
    - sample: pandas.DataFrame (indexed by gene symbol) or path to expression TSV/CSV.
    - geneset: dict (preloaded) or path to geneset JSON. If None, uses
      DEFAULT_DATA_PATHS['drug_genesets'] from src.common.constants.
    - out_path: optional path to write result JSON. If None, does not write.
    - n_perm: number of permutations for empirical p-value.
    - norm_method: passed to `score()` as `norm_method`.

    Returns
    - final_result: nested dict preserving master geneset keys with
      {"total_score": float|None, "empirical_p_value": float|None}

    Notes: Accepts genesets with structure: drug -> category -> pathway -> [genes]
    """

    def _load_sample(sample_input):
        gene_keywords = ["gene", "genes", "symbol", "symbols", "name", "genename"]
        if isinstance(sample_input, pd.DataFrame):
            df = sample_input.copy()
        else:
            # try to read with tab separator first, fallback to comma
            try:
                df = pd.read_csv(sample_input, sep="\t", header=0)
            except Exception:
                df = pd.read_csv(sample_input, header=0)

        # find matching column for gene names
        gene_col = next(
            (col for col in df.columns if any(re.search(k, col, re.IGNORECASE) for k in gene_keywords)),
            df.columns[0]
        )
        df = df.set_index(gene_col)
        return df

    def _load_geneset(geneset_input):
        if geneset_input is None:
            path = DEFAULT_DATA_PATHS.get("drug_genesets")
            if path is None:
                raise ValueError("No default drug_genesets path found in DEFAULT_DATA_PATHS")
            geneset_input = path

        if isinstance(geneset_input, dict):
            return geneset_input

        # assume path
        with open(geneset_input, "r", encoding="utf-8") as fh:
            return json.load(fh)

    def run_permutations(sample_df, n_up, n_down=False, n_perm=10000):
        sig = inspect.signature(permutate)
        kwargs = {}

        for cand in ["n_perm", "n_permutations", "permutations", "n"]:
            if cand in sig.parameters:
                kwargs[cand] = n_perm
                break

        if "n_up" in sig.parameters:
            kwargs["n_up"] = n_up
        if "n_down" in sig.parameters:
            kwargs["n_down"] = n_down

        try:
            return permutate(sample_df, **kwargs)
        except TypeError:
            return permutate(sample_df, n_up=n_up, n_down=n_down)

    # load inputs
    expr = _load_sample(sample)
    all_drugs = _load_geneset(geneset)

    final_result = {}

    for drug_name, drug_block in tqdm(all_drugs.items(), desc="Drugs"):
        final_result[drug_name] = {}

        for category_name, category_block in drug_block.items():
            if not isinstance(category_block, dict) or len(category_block) == 0:
                final_result[drug_name][category_name] = {}
                continue

            final_result[drug_name][category_name] = {}

            for pathway_name, genes in tqdm(category_block.items(), desc=f"{drug_name} :: {category_name}", leave=False):
                if not isinstance(genes, list) or len(genes) == 0:
                    final_result[drug_name][category_name][pathway_name] = {"total_score": None, "empirical_p_value": None}
                    continue

                up_present = [g for g in genes if g in expr.index]

                if len(up_present) == 0:
                    final_result[drug_name][category_name][pathway_name] = {"total_score": None, "empirical_p_value": None}
                    continue

                scored = score(up_gene=up_present, down_gene=False, sample=expr, norm_method=norm_method, full_data=True)
                total_score = float(scored["total_score"].to_list()[0])

                permd = run_permutations(expr, n_up=len(up_present), n_down=False, n_perm=n_perm)
                pvals = empiricalpval(permutations=permd, score=scored)
                empirical_p_value = float(pvals["empirical p value"].to_list()[0])

                final_result[drug_name][category_name][pathway_name] = {"total_score": total_score, "empirical_p_value": empirical_p_value}

    if out_path:
        out_path = Path(out_path)
        out_path.parent.mkdir(parents=True, exist_ok=True)
        with open(out_path, "w", encoding="utf-8") as f:
            json.dump(final_result, f, indent=2, ensure_ascii=False)

    return final_result


# Example usage (commented):
from src.inference.singscore.run_singscore_all_drugs import run_singscore_all_drugs
# from src.common import constants
#
# # 1) Call with file path for sample and default geneset from constants, write output
# # result = run_singscore_all_drugs(
# #     sample="/path/to/sample_expression.tsv",
# #     geneset=constants.DEFAULT_DATA_PATHS['drug_genesets'],
# #     out_path="/path/to/output/singscore.json",
# #     n_perm=10000
# # )
#
# # 2) Call with preloaded DataFrame and preloaded geneset dict
# # df = pd.read_csv("/path/to/sample.tsv", sep="\t", header=0)
# # geneset_dict = json.load(open(constants.DEFAULT_DATA_PATHS['drug_genesets']))
# # result = run_singscore_all_drugs(df, geneset=geneset_dict, out_path=None, n_perm=1000)